### PR TITLE
[coord] use preferred default keys for SELECT statements

### LINKED ISSUE #7012: [coord] Queries create redundant arrangements
A relatively simple queries like
```
materialize=> insert into t (a, b) values (1, 2), (2, 3), (3, 1);
INSERT 0 3
materialize=> select a, sum(b) from t group by a;
 a | sum 
---+-----
 1 |   2
 2 |   3
 3 |   1
(3 rows)
```
Should be just a reduce operator, which produces arranged data that can then be consulted. However, the `DataflowDesc` built at the coordinator has two objects to build, 
```
    BuildDesc { id: Transient(27), relation_expr: OptimizedMirRelationExpr(Reduce { input: Get { id: Global(User(1)), typ: RelationType { column_types: [ColumnType { nullable: true, scalar_type: Int32 }, ColumnType { nullable: true, scalar_type: Int32 }], keys: [] } }, group_key: [Column(0)], aggregates: [AggregateExpr { func: SumInt32, expr: Column(1), distinct: false }], monotonic: false, expected_group_size: None }), typ: Some(RelationType { column_types: [ColumnType { nullable: true, scalar_type: Int32 }, ColumnType { nullable: true, scalar_type: Int64 }], keys: [[0]] }) }, 

    BuildDesc { id: Transient(26), relation_expr: OptimizedMirRelationExpr(ArrangeBy { input: Get { id: Global(Transient(27)), typ: RelationType { column_types: [ColumnType { nullable: true, scalar_type: Int32 }, ColumnType { nullable: true, scalar_type: Int64 }], keys: [[0]] } }, keys: [[Column(0), Column(1)]] }), typ: None }
```
There are 1. the reduce operator, which produces an arrangement by its key, and 2. a new arrangement using both columns. We have elsewhere the information that primary keys are a great basis for arrangements, and in this case the (perhaps secret) knowledge that the data are already arranged. We could avoid the second built arrangement, and generally improve query answering in this case.

### PR DESCRIPTION
**Pull request by frankmcsherry**
Fixes #7012

### CODE REVIEW

**Review by mjibson — APPROVED** [review]
Should this come with a test that verifies the improved plan so we ensure it doesn't regress?

**Comment by frankmcsherry** [comment]
I'm not sure how we test the `DataflowDesc` that the coordinator produces. If you do I can add it.

**Comment by mjibson** [comment]
Merge away then. I might experiment with a test later.

**Comment by frankmcsherry** [comment]
Thanks for the speedy review!

**Comment by mjibson** [comment]
Ah I thought you could use EXPLAIN PLAN to get this. :(

**Pull request merged**
