### PR TITLE
Increasing batch size in ingest mode

### PR DESCRIPTION
**Pull request by nacrooks**
As suggested by @frankmcsherry, this PR reduces the frequency at which we downgrade capabilities (thus creating larger batch sizes) when we detect that we are trailing behind a source (when the number of known messages in the topic is greater than the number of processed messages by X). 

I wanted to get this PR up before leaving but I have not verified that it actually improves performance.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/3822)

### CODE REVIEW

**Comment by rjnn** [comment]
Assigned to @umanwizard to merge and verify it helps!

**Comment by frankmcsherry** [comment]
This dovetails with a related ask for consistency: that on start-up, one be able to force all timestamps of existing records to at most `now()` (and possibly exactly `now()`), for the purposes of ensuring that users are able to maintain consistency across restarts. This is one candidate remedy, so it's not dictum that it should happen, but we would like to find a mechanism for users to ensure that previously seen records are not timestamped in their future, and this may be such a mechanism.

**Comment by frankmcsherry** [comment]
This PR (or something like it) probably would have helped prevent some of the issues encountered in #5013.

**Comment by benesch** [comment]
This unfortunately went a bit stale and will need to be rewritten for changes that have occurred to the timestamper. I think this is still desired, so I filed #5690 to track.

**Pull request closed without merging**
