### PR TITLE
ci: Use mold linker to speed up building

### PR DESCRIPTION
**Pull request by def-**
> mold is available under the AGPL license. Note that this does not mean
> you have to license your program under AGPL if you use mold to link your
> program. The output of the mold linker is a derived work of the object
> files and libraries you pass to the linker, but not a derived work of
> the mold linker itself.

The runtimes of build fluctuate so much that I don't dare to say how much faster this is. Locally I've been using mold on Linux for a while and seen no problems.

Part of #20132 

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by def-** [comment]
Keeps crashing:
```
[2023-06-26T16:50:18Z] [0m[0m[1m[31merror[0m[1m:[0m failed to run custom build command for `mz-proto v0.0.0 (/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04f7908e38b3c2534-1/materialize/tests/src/proto)`
[2023-06-26T16:50:18Z] 
[2023-06-26T16:50:18Z] Caused by:
[2023-06-26T16:50:18Z]   process didn't exit successfully: `/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04f7908e38b3c2534-1/materialize/tests/miri-target/miri/debug/build/mz-proto-aae622cf6233f2ba/build-script-build` (exit status: 101)
[2023-06-26T16:50:18Z]   --- stderr
[2023-06-26T16:50:18Z]   thread 'main' panicked at 'protoc failed: ', src/proto/build.rs:87:29
[2023-06-26T16:50:18Z]   stack backtrace:
[2023-06-26T16:50:18Z]      0: rust_begin_unwind
[2023-06-26T16:50:18Z]                at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/std/src/panicking.rs:577:5
[2023-06-26T16:50:18Z]      1: core::panicking::panic_fmt
[2023-06-26T16:50:18Z]                at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/panicking.rs:67:14
[2023-06-26T16:50:18Z]      2: build_script_build::main::{{closure}}
[2023-06-26T16:50:18Z]                at ./build.rs:87:29
[2023-06-26T16:50:18Z]      3: core::result::Result<T,E>::unwrap_or_else
[2023-06-26T16:50:18Z]                at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/result.rs:1464:23
[2023-06-26T16:50:18Z]      4: build_script_build::main
[2023-06-26T16:50:18Z]                at ./build.rs:81:5
[2023-06-26T16:50:18Z]      5: core::ops::function::FnOnce::call_once
[2023-06-26T16:50:18Z]                at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/ops/function.rs:250:5
[2023-06-26T16:50:18Z]   note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by danhhz** [comment]
does this affect the binaries that we than use in production? if so, is that concerning? I'm very excited about mold, but the last time I looked, there was some apprehension about using it in production

**Comment by def-** [comment]
I checked and the apprehension seems to have been about mold's plans to change their interpretation of the AGPL license. The part I quoted in the first message is the proper interpretation, which should be no problem for us, based on my understanding.

**Comment by benesch** [comment]
Agree it shouldn't be a problem based on my understanding of the AGPL, but
we'd need to run it past the lawyers nonetheless because having any AGPL
code in our toolchain can raise legal yellow flags that we need to be
prepared to handle.

I'm not wild about using mold for linking our production binaries if it
doesn't obviously move the needle on compile times. There's risk to using a
more immature linker that we may discover the hard way in production. Not
strongly opposed but it's a tradeoff to be carefully weighed. I'd also love
to do this on a week after things have been stable for a while. Given the
chaos of v0.57 (segfaults, mem usage regression) I'm not eager to throw
another risky change into the mix; most important goal right now is to
safely deliver v0.58 with the memory usage fixed, and ideally v0.59 and
v0.60 are similarly uneventful.

**Comment by benesch** [comment]
We should also evaluate whether we should buy a commercial license for
sold, even though it's not technically required by the mold license.

**Comment by def-** [comment]
I did a measurement, along the lines of
```bash
  cargo build --release
  find target/release -type f ! -name "*.*" -delete
  export RUSTFLAGS="-C link-arg=-fuse-ld=mold"
  cargo build --release
  echo "#!/usr/bin/bash\n(time /usr/local/bin/orig/ld.mold "$@") 2>> /home/deen/mold-times" > /usr/local/bin/mold
  ln -s /usr/local/bin/ld.mold
  cargo build --release
  echo "#!/usr/bin/bash\n(time /usr/bin/ld.lld "$@") 2>> /home/deen/lld-times" > /usr/local/bin/ld.lld
  export RUSTFLAGS="-C link-arg=-fuse-ld=lld"
```
And the result is not great:
```bash
grep real lld-times | sed -e "s/.*0m//" -e "s/s//" | paste -s -d+ - | bc
36.676
grep real mold-times | sed -e "s/.*0m//" -e "s/s//" | paste -s -d+ - | bc
38.335
```
So mold seemed even slower.

**Pull request closed without merging**
