### PR TITLE
optbench: replace deprecated `pkg_resources` package

### LINKED ISSUE #18527: Replace deprecated `pkg_resources` library
### What version of Materialize are you using?

v0.49.0-dev

### How did you install Materialize?

Built from source

### What is the issue?

Our optimizer benchmarking python scripts rely on the `pkg_resources` library which is deprecated.

https://github.com/MaterializeInc/materialize/blob/138bf7fcb694fac900e32219b7024ef5b3cdd96c/misc/python/materialize/optbench/__init__.py#L13

The documentation for `pkg_resources` and the deprecation notice can be found here: https://setuptools.pypa.io/en/latest/pkg_resources.html

You can also see the warning when running one of our python linters:
```bash
$ ./bin/pyactivate -m pytest -qq --doctest-modules misc/python
..                                                                                                                                                                                 [100%]
==================================================================================== warnings summary ====================================================================================
misc/python/venv/lib/python3.10/site-packages/pkg_resources/__init__.py:121
  /home/joe/materialize/misc/python/venv/lib/python3.10/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)

misc/python/venv/lib/python3.10/site-packages/pkg_resources/__init__.py:2870
  /home/joe/materialize/misc/python/venv/lib/python3.10/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

The suggested alternative is to switch to the `importlib.resources`: https://docs.python.org/3/library/importlib.resources.html

I found a useful migration guide here: https://importlib-resources.readthedocs.io/en/latest/migration.html#pkg-resources-resource-filename

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by aalexandrov**
Fixes #18527.

### Motivation

  * This PR adds a known-desirable feature.

### Tips for reviewer

I followed [the `pkg_resources` migration guide to `importlib.resources`](https://docs.python.org/3/library/importlib.resources.html#module-importlib.resources). @jkosh44 feel to auto-allow "rebase and merge" after approval.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - There are no user-facing behavior changes.

### CODE REVIEW

**Comment by aalexandrov** [comment]
I fixed the `mypy` issues.

**Comment by jkosh44** [comment]
Is the otpbench run as part of normal CI? Or do we need to run it separately?

**Comment by jkosh44** [comment]
The feature benchmark failed, but I don't know if it's related to this change. I kicked off a retry.

**Comment by aalexandrov** [comment]
I don't think it was related, the optbench tests are prefixed with `OptbenchTPCHQuery`.

**Review by jkosh44 — APPROVED** [review]

**Comment by jkosh44** [comment]
> I don't think it was related, the optbench tests are prefixed with `OptbenchTPCHQuery`.

Oh it doesn't even look like the benchmark was able to start the Opt benches. I'll take your word for it that it works locally.

**Comment by aalexandrov** [comment]
> I'll take your word for it that it works locally.

No need to - the failed first run [lists results for each of the 22 queries at the bottom](https://buildkite.com/materialize/nightlies/builds/2141#01874d49-5dbd-42bc-8f44-9776145edaa8/13543-13579).

**Pull request merged**
