### PR TITLE
doc: Revise maintenance window language

### PR DESCRIPTION
**Pull request by jseldess**
Minor improvements to how we describe our maintenance windows and what happens after the window, based on input from Nikhil.

Fixes: #18339

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by jseldess** [comment]
@benesch, we're not making any recommendations about how to gracefully handle the downtime. Let me know if you think we should and, if so, what a best practice approach might be.

**Comment by benesch** [comment]
I _do_ think we should, but we don't have many great answers right now. @sjwiesman and the field engineering team have worked with customers to do this and have a better understanding of how to do this than we do, to be quite honest.

The rough points are, I _think:_

  * Create materialized views for complex queries, and then build indexes on _top_ of those materialized views. That way the indexes can quickly rehydrate from the materialized view after the upgrade to get back to (now stale) data they had before the upgrade. 
  * Set `transaction_isolation = serializable` to see this stale data while the system is still catching up to the present.
  * Put less data in Materialize. This sounds silly, but if you don't _need_ all your historical data in Materialize, not putting it in Materialize will mean faster rehydration for your current data.

**Comment by sjwiesman** [comment]
What you've written looks good as is to me. 

> Create materialized views for complex queries, and then build indexes on top of those materialized views. That way the indexes can quickly rehydrate from the materialized view after the upgrade to get back to (now stale) data they had before the upgrade.
Set transaction_isolation = serializable to see this stale data while the system is still catching up to the present.

This is the recommendation we've been giving. That said, we haven't really tested it and I think we probably should before putting it in the docs.

**Comment by jseldess** [comment]
Thanks, @sjwiesman and @benesch. I've logged a docs issue to follow up with recs for gracefully handling downtime, once we've tested them: https://github.com/MaterializeInc/materialize/issues/20191.

**Review by benesch — APPROVED** [review]
LGTM.

**Review by sjwiesman — APPROVED** [review]

**Pull request merged**
