### PR TITLE
Re-order imports

### PR DESCRIPTION
**Pull request by teskje**
This PR attempts to unify the import grouping in all our Rust modules. The new import order is chosen to be compatible with [how rust-analyzer's auto-import feature groups imports](https://rust-analyzer.github.io/manual.html#auto-import), i.e.:
 * `std::`
 * external crates
 * `crate::`

The rationale is that this is likely the grouping that our code will naturally gravitate to, given that most engineers at Materialize use rust-analyzer (I assume). Every other grouping is likely to be less stable without automatic enforcement. I realize that not everyone uses rust-analyzer. My hope is that the above grouping also suits people using alternative editor integrations, or at least doesn't make their lives harder.

An alternative to this approach would be to enforce a certain grouping in CI. If we did this then which grouping we use would barely matter. There are no ready-made tools to do the CI checking, but it seems feasible that we could fork rustfmt and modify it for this purpose. It already includes [unstable support for import group formatting](https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=import#group_imports), it would be easy to mark that as stable. The obvious drawbacks would be a) the rustfmt version used in CI would differ from that used by developers by default and b) we would have to put in effort to keep our fork updated. I assume we don't want to have to deal with that.

I also took the opportunity to apply a consistent module-level import granularity. Like the import grouping, I don't expect this consistency to remain for long, but as I'm already touching every source file anyway I figured I might as well clean up a little.

Finally, this PR also makes all crate-level imports use absolute paths (rather than (`super` or `self` paths). This was pointed out as desirable in https://github.com/MaterializeInc/materialize/pull/19244#issuecomment-1548855540 and folk seem to generally agree that this is a good change to make for consistency.

I adjusted `style.md` to describe this style as our preferred import style and document the rust-analyzer settings necessary to make the auto import feature conform to this style as well.

### Motivation

   * This PR refactors existing code.

See [discussion in Slack](https://materializeinc.slack.com/archives/CM7ATT65S/p1683795115572069).

### Tips for reviewer

The diff is huge, but you probably don't have to look at all of it to understand the gist of what is happening. All changes made here are barely cosmetical and shouldn't introduce any risk whatsoever.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by def- — APPROVED** [review]
Based on a quick skim this seems to do what it promises, should be fine from QA side.

**Review by aalexandrov — APPROVED** [review]

**Review by benesch — APPROVED** [review]
LGTM, with two requests:

1. I think it's time to formalize this style. Can you update STYLE.md with a description of this style?
2. Can you update doc/developer/guide.md with a description of how to configure Rust Analyzer to use this style?

**Comment by teskje** [comment]
> I think it's time to formalize this style. Can you update STYLE.md with a description of this style?

Will do!

> Can you update doc/developer/guide.md with a description of how to configure Rust Analyzer to use this style?

AFAIK there are no options in rust-analyzer to control the import style. [At least nothing is documented.](https://rust-analyzer.github.io/manual.html#auto-import) When you use the auto import feature, this import grouping is the one you get.

**Comment by benesch** [comment]
> > Can you update doc/developer/guide.md with a description of how to configure Rust Analyzer to use this style?
> 
> AFAIK there are no options in rust-analyzer to control the import style. [At least nothing is documented.](https://rust-analyzer.github.io/manual.html#auto-import) When you use the auto import feature, this import grouping is the one you get.

Ah, sorry, I meant setting `imports.granularity.group` to `module` and `imports.prefix` to `crate`.

**Comment by teskje** [comment]
Ah, yes! Although I didn't consider `imports.prefix` = `crate` at all until now. My reading is that this would simplify the imports to only three groups (std, external, crate) since `self` and `super` imports would be removed. This has the potential benefit of being compatible with how rustfmt would like to group imports. The drawback is that it is not obvious anymore which imports are from submodules of the current module.

Alternatively, we could prescribe `imports.prefix` = `self`, which would be similar to what we have now, but would disallow  un-prefixed imports from submodules.

**Comment by benesch** [comment]
> The drawback is that it is not obvious anymore which imports are from submodules of the current module.

I've been using crate style for years, since I find `self` and `super` to be too flexible to use consistently, and that actually makes it _harder_ to see the module structure in the imports:

```
# Suppose you have the following files:
#   src/foo/bar/baz.rs
#   src/foo/bar/baz/zoo.rs
#   src/foo/bar/bazzle.rs
#
# Suppose this file is foo/bar.rs

# Crate-absolute imports.

use crate::Stuff;
use crate::foo::Foo;
use crate::foo::bar::baz::zoo::SomeImport;
use crate::foo::bar::bazzle::SomeOtherImport;

# Relative imports.

use crate::Stuff;
use crate::foo::bar::bazzle::SomeOtherImport;
use super::Foo;
use self::bar::baz::zoo::SomeImport;
```

With `super` and `self`, I find that it's just too easy to import the same path in many ways, and that ends up making the module hierarchy less clear rather than more clear. If you use crate-absolute imports, you're guaranteed that all types in the current crate are imported in the same way, and so all you have to do is remember where the file you're looking at sits in the `use` block, vs having to resolve `super` and `self` as you read.

**Comment by teskje** [comment]
I added two more commits, based on the discussion here and in Slack, to:
* consistently apply `imports.prefix = crate` to all imports
* add a section about import style to `style.md`

We can iterate more of course, but I'd like to merge this PR soon (i.e. tomorrow), given that it is a pain to keep updated with `main`. I think there is broad consensus about the idea behind these changes even though I may have overlooked some details.

**Comment by aljoscha** [comment]
> We can iterate more of course, but I'd like to merge this PR soon (i.e. tomorrow), given that it is a pain to keep updated with `main`. I think there is broad consensus about the idea behind these changes even though I may have overlooked some details.

100 %!

**Comment by benesch** [comment]
> > We can iterate more of course, but I'd like to merge this PR soon (i.e. tomorrow), given that it is a pain to keep updated with `main`. I think there is broad consensus about the idea behind these changes even though I may have overlooked some details.
> 
> 100 %!

Seconded!

**Pull request merged**
