### PR TITLE
expr: make predicate canonizalization output reliable (attempt 2)

### LINKED ISSUE #9794: Plan instability with LATERAL join
The following plan is unstable and oscillates between two different variants.

```
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

CREATE TABLE table_f1 (f1 INTEGER);
CREATE TAble table_f4_f5_f6 (f4 INTEGER, f5 INTEGER, f6 INTEGER);
CREATE TAble table_f5_f6 (f5 INTEGER, f6 INTEGER);

EXPLAIN  SELECT *  FROM table_f1 , ( table_f4_f5_f6 AS a2 LEFT JOIN table_f5_f6 AS a3 USING ( f5 , f6  ) ) WHERE f5 = f6 AND  f4 = f6;
EXPLAIN  SELECT *  FROM table_f1 , ( table_f4_f5_f6 AS a2 LEFT JOIN table_f5_f6 AS a3 USING ( f5 , f6  ) ) WHERE f5 = f6 AND  f4 = f6;
EXPLAIN  SELECT *  FROM table_f1 , ( table_f4_f5_f6 AS a2 LEFT JOIN table_f5_f6 AS a3 USING ( f5 , f6  ) ) WHERE f5 = f6 AND  f4 = f6;
EXPLAIN  SELECT *  FROM table_f1 , ( table_f4_f5_f6 AS a2 LEFT JOIN table_f5_f6 AS a3 USING ( f5 , f6  ) ) WHERE f5 = f6 AND  f4 = f6;
EXPLAIN  SELECT *  FROM table_f1 , ( table_f4_f5_f6 AS a2 LEFT JOIN table_f5_f6 AS a3 USING ( f5 , f6  ) ) WHERE f5 = f6 AND  f4 = f6;
EXPLAIN  SELECT *  FROM table_f1 , ( table_f4_f5_f6 AS a2 LEFT JOIN table_f5_f6 AS a3 USING ( f5 , f6  ) ) WHERE f5 = f6 AND  f4 = f6;
EXPLAIN  SELECT *  FROM table_f1 , ( table_f4_f5_f6 AS a2 LEFT JOIN table_f5_f6 AS a3 USING ( f5 , f6  ) ) WHERE f5 = f6 AND  f4 = f6;
EXPLAIN  SELECT *  FROM table_f1 , ( table_f4_f5_f6 AS a2 LEFT JOIN table_f5_f6 AS a3 USING ( f5 , f6  ) ) WHERE f5 = f6 AND  f4 = f6;
EXPLAIN  SELECT *  FROM table_f1 , ( table_f4_f5_f6 AS a2 LEFT JOIN table_f5_f6 AS a3 USING ( f5 , f6  ) ) WHERE f5 = f6 AND  f4 = f6;
EXPLAIN  SELECT *  FROM table_f1 , ( table_f4_f5_f6 AS a2 LEFT JOIN table_f5_f6 AS a3 USING ( f5 , f6  ) ) WHERE f5 = f6 AND  f4 = f6;
```

The diff in this case is more subtle:

```
EXPLAIN SELECT *
  FROM table_f1 , (table_f4_f5_f6 AS a2 LEFT JOIN table_f5_f6 AS a3 USING (f5, f6))
 WHERE f5 = f6
   AND f4 = f6;

--- 6875.out	2021-12-28 11:31:09.957303336 +0100
+++ 16875.out	2021-12-28 11:31:10.001303896 +0100
@@ -1,33 +1,32 @@
-%0 =
+%0 = Let l0 =
 | Get materialize.public.table_f4_f5_f6 (####)
-| Filter ((isnull(#0) && isnull(#2)) || (#0 = #2)), (#0 = #1), (#1 = #2)
-| ArrangeBy (#0)
+| Filter ((isnull(#1) && isnull(#2)) || (#1 = #2)), (#0 = #1), (#0 = #2)
 
 %1 =
+| Get %0 (l0)
+| ArrangeBy (#0)
+
+%2 =
 | Get materialize.public.table_f5_f6 (####)
 | Filter (#0 = #1)
 | Project (#0)
 
-%2 = Let l0 =
-| Join %0 %1 (= #0 #3)
-| | implementation = Differential %1 %0.(#0)
-| Project (#0..#2)
-
 %3 = Let l1 =
-| Get materialize.public.table_f4_f5_f6 (####)
-| Filter ((isnull(#1) && isnull(#2)) || (#1 = #2)), (#0 = #1), (#0 = #2)
+| Join %1 %2 (= #0 #3)
+| | implementation = Differential %2 %1.(#0)
+| Project (#0..#2)
 
 %4 =
 | Get materialize.public.table_f1 (####)
 | ArrangeBy ()
 
 %5 =
-| Get %2 (l0)
+| Get %3 (l1)
 | Distinct group=(#0, #1, #2)
 | Negate
 
 %6 =
-| Get %3 (l1)
+| Get %0 (l0)
 | Distinct group=(#0, #1, #2)
 
 %7 =
@@ -35,7 +34,7 @@
 | ArrangeBy (#0)
 
 %8 =
-| Get %3 (l1)
+| Get %0 (l0)
 | Project (#0)
 
 %9 =
@@ -44,7 +43,7 @@
 | Project (#0..#2)
 
 %10 =
-| Union %2 %9
+| Union %3 %9
 
 %11 =
 | Join %4 %10
```

_Originally posted by @philip-stoev in https://github.com/MaterializeInc/materialize/issues/9782#issuecomment-1002000481_

### PR DESCRIPTION
**Pull request by asenac**
... regardless of the order of the input predicates.

Fixes #9794.

### Motivation

This PR fixes a recognized bug.

Another PR will fix `PredicatePushdown`'s output unreliability.

### Tips for reviewer

It turns out #9783 didn't fully fix `canonicalize_predicates`'s reliability.

This PR also extends that logic to simplify `isnull` expressions if there is another predicate rejecting nulls coming from the same sub-expression.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

**Comment by asenac** [comment]
The failing test fails due to the following difference with postgres:

This is us:

```
materialize=> CREATE TABLE int4_tbl (f1 int)
materialize-> ;
CREATE TABLE
materialize=> INSERT INTO int4_tbl (f1) VALUES (0), (123456), (-123456), (2147483647), (-2147483647);
INSERT 0 5
materialize=> select * from int4_tbl where f1 < 2147483647 and f1 != f1 + 1;
ERROR:  numeric field overflow
materialize=> explain select * from int4_tbl where f1 < 2147483647 and f1 != f1 + 1;
                Optimized Plan                
----------------------------------------------
 %0 =                                        +
 | Get materialize.public.int4_tbl (u387)    +
 | Filter (#0 != (#0 + 1)), (#0 < 2147483647)+
 
(1 row)

materialize=> 
```
This is portgres:
```
asenac=> select * from int4_tbl where f1 < 2147483647 and f1 != f1 + 1;                                                                    
     f1      
-------------
           0
      123456
     -123456
 -2147483647
(4 rows)

asenac=> explain                                                                                                                                  
select * from int4_tbl where f1 < 2147483647 and f1 != f1 + 1;                                                                    
                        QUERY PLAN                         
-----------------------------------------------------------
 Seq Scan on int4_tbl  (cost=0.00..54.63 rows=846 width=4)
   Filter: ((f1 < 2147483647) AND (f1 <> (f1 + 1)))
(2 rows)

asenac=>
```

**Comment by philip-stoev** [comment]
Item No 1 . In this branch, the following query has had the predicate `f4 <= 10` travel from above the join to below the join, as compared to the prior commit:

```
EXPLAIN WITH cte_f1_f2_f3 AS (
        SELECT *
          FROM table_f1_f2_f3 AS a1
       ) SELECT COUNT(*)
  FROM table_f1_f2_f3
 INNER JOIN LATERAL (
        SELECT *
          FROM (
                SELECT *
                  FROM (
                        SELECT f3,
                               f4,
                               f5,
                               f6
                          FROM (table_f1_f2_f3 JOIN table_f2_f3_f4 AS a2 USING (f2, f3))
                          LEFT JOIN ((table_f3_f4 AS a3 LEFT JOIN table_f4_f5 USING (f4)) JOIN table_f5_f6 AS a4 USING (f5)) USING (f3, f4)
                       ) AS a5
                 WHERE f3 <= f1
               ) AS a6
       ) AS a7 USING (f3)
 WHERE f4 <= 10
    OR f1 IS NULL;

--- 6875.out	2021-12-29 17:30:37.170358151 +0100
+++ 16875.out	2021-12-29 17:30:37.218359120 +0100
@@ -10,18 +10,18 @@
 
 %2 =
 | Get materialize.public.table_f2_f3_f4 (####)
-| Filter !(isnull(#0)), !(isnull(#1)), (#2 <= 10)
+| Filter !(isnull(#0)), !(isnull(#1))
 | ArrangeBy (#0, #1)
 
 %3 = Let l0 =
 | Join %0 %1 %2 (= #2 #4) (= #3 #5)
 | | implementation = Differential %1 %2.(#0, #1) %0.()
-| Filter (#3 <= #0)
+| Filter (isnull(#0) || (#6 <= 10)), (#3 <= #0)
 | Project (#0..#3, #6)
 
 %4 =
 | Get %3 (l0)
-| Filter (#3 <= #0)
+| Filter (#3 <= #0), (#4 <= 10)
 | ArrangeBy (#4)
 
 %5 =
@@ -30,7 +30,7 @@
 
 %6 =
 | Get materialize.public.table_f4_f5 (####)
-| Filter !(isnull(#1)), (#0 <= 10)
+| Filter !(isnull(#0)), !(isnull(#1))
 | ArrangeBy (#1)
 
 %7 =
@@ -41,7 +41,6 @@
 %8 = Let l1 =
 | Join %4 %5 %6 %7 (= #3 #5) (= #4 #6 #7) (= #8 #9)
 | | implementation = Differential %7 %6.(#1) %4.(#4) %5.(#0, #1)
-| Filter (#4 <= 10)
 | Project (#0..#4)
 
 %9 =
```

Apologies for the hairy query, but I simplifying it manually has been slow going. It seems that the `WITH` clause is required even though the CTE is **not** used in the query at all.

**Review by philip-stoev — APPROVED** [review]
The plan instability is gone and there are no more sporadic EXPLAIN differences.

With respect to the prior commit, most plans are changed for the better, with the removal of redundant `isnull` checks, more conditions being pushed to the Filter of a Get, more plans declared as Constant, etc. The only plan that seems to have suffered is the one in Item # 1. 

There were no wrong results or panics.

**Review by wangandi — APPROVED** [review]

**Comment by asenac** [comment]
Added a third commit for addressing the test failure by sorting predicates by their complexity measured as the number of non-literal expression nodes. Not many tests have changed.

As mentioned in slack, only the first commit is strictly needed for fixing the issue. If this last commit results to be controversial, I could just push the first commit.

The second commit was added since it resulted in a better plan for the query in this issue.

**Pull request merged**
