### PR TITLE
persist: rework JsonStats

### PR DESCRIPTION
**Pull request by danhhz**
At interpret-time, we don't need detailed stats about cases where more than one "category" of json datums (bool, numeric, string, list, map) were present. In practice, these will always involve some sort of cast, which would error on at least one of the categories. So, we rework our json stats to be detailed if 0 or 1 categories are present, but replaced with a sentinel if more than 1 are present. Note that this is not true of JsonNull, so it's pulled out and always counted.

This is strictly less information than we used to keep, so we could add a migration to convert the old format to the new, but this has only been used on staging, so we save the complexity and pick a new proto id for part stats.

Touches #12684 

### Motivation

  * This PR adds a known-desirable feature.

### Tips for reviewer

Verified that the included proptest catches a copy-pasta bug that I had at one point during development.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by bkirwi** [comment]
> Note that this is not true of JsonNull, so it's pulled out and always counted.

Do you have a snippet of sql that demonstrates `JsonNull` not erroring during a cast? (That isn't either `::text` or back to `::jsonb` which have special behaviour.) Poking at it briefly I haven't found a case where a separate json-null count is useful, but I definitely have not investigated every case!

**Review by bkirwi — APPROVED** [review]
Restructure looks great! This seems good to merge assuming you're satisfied with the json-null question.

**Comment by danhhz** [comment]
> > Note that this is not true of JsonNull, so it's pulled out and always counted.
> 
> Do you have a snippet of sql that demonstrates `JsonNull` not erroring during a cast? (Other than`::text` or back to `::jsonb`, I guess, since those are a little special.) Poking at it briefly I haven't found a case where a separate json-null count is useful, but I definitely have not investigated every case!

I thought I did, but you're right! I dug up the example I based this off of and it turns out I was comparing two jsonb objects (which, fun fact, mz's behavior here does not match postgres right now). i did some exploring of actual queries but just ended up looking up our source for every jsonb cast and they all accept exactly one type and error on the rest, none of them special casing JsonNull. i'll back this out (which is a nice simplification!)

**Comment by danhhz** [comment]
okay, fixed to treat jsonnull like any other category

**Review by bkirwi — APPROVED** [review]

**Comment by danhhz** [comment]
TFTR!

**Pull request merged**
