### PR TITLE
prof: rename to alloc + take responsibility for configuring allocator 

### PR DESCRIPTION
**Pull request by benesch**
Details in commit messages.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/3854)

### CODE REVIEW

**Comment by umanwizard** [comment]
Not sure about this... I think we might add other profiling tools that have nothing to do with the allocator (e.g., CPU profiling). I was never envisioning that this crate/module would be purely related to jemalloc.

**Comment by benesch** [comment]
Then we have abstracted too soon, and I would strongly prefer to not have a separate crate for this.

**Comment by quodlibetor** [comment]
I agree that this should not be renamed to alloc, and that it should not have responsibility for configuring the global allocator.

I think it's more correct if it fails if the global allocator is not jemalloc.

**Comment by quodlibetor** [comment]
Specifically I agree with Brennan that the correct abstraction for this crate is "things that can be used to profile the currently running process".

**Comment by umanwizard** [comment]
Brandon we have been discussing this offline; I think both of us agree with
you. The problem is that it's non-trivial to check what the currently used
global allocator is.

**Comment by benesch** [comment]
Alternative coming shortly, but I stand by my position that we abstracted too early.

**Pull request closed without merging**
