### PR TITLE
ci: Run Nightly on PRs that may cause Nightly to break

### PR DESCRIPTION
**Pull request by philip-stoev**
Run Nightly on PRs that may cause Nightly to break.

PRs that modify any of the files listed in the respective section of pipeline.template.yml will trigger Nightly. See the documentation in pipeline.template.yml for the justification of individual rules.

### Motivation

Changes in certain areas of the product are more likely to break Nightly, requiring follow-up fixes to either the product or the tests. It is best to catch those in the PR phase.

### CODE REVIEW

**Review by nrainer-materialize — APPROVED** [review]
Good idea, thank you! I hope (but am confident) that the pipeline is shown in the PR if it is triggered like this (unlike when manually triggering a build).

**Comment by philip-stoev** [comment]
Nope, it is not shown :-(

**Comment by philip-stoev** [comment]
Also, the pipline step is listed as pruned by mkpipline, but still runs ...

**Comment by philip-stoev** [comment]
> Also, the pipline step is listed as pruned by mkpipline, but still runs ...

Nevermind, this is because of `Repository glue code has changed, so the trimmed pipeline below does not apply`

**Comment by philip-stoev** [comment]
> Nope, it is not shown :-(

I fixed this one too. The Nightly stuff is now shown.

**Comment by nrainer-materialize** [comment]
> > Nope, it is not shown :-(
> 
> I fixed this one too. The Nightly stuff is now shown.

Awesome. What was the fix?

**Pull request merged**
