### PR TITLE
Collect updated differential; update deprecated calls

### LINKED ISSUE #5774: Wrong result with inner join, disjunction and workers > 1
### What version of Materialize are you using?

```
materialized v0.7.1-dev (f26c4dac1)
```

### What was the issue?

This is similar in outward appearances to #5622, but it does not require outer joins or multi-column indexes. Instead it seems to require a disjunction and multiple single-column indexes. The offending query is:

```
SELECT COUNT(*)
FROM lineitem
JOIN orders ON ( l_orderkey  = o_orderkey )
JOIN customer ON ( o_custkey = c_custkey  )
WHERE c_acctbal  >=  1 OR o_orderDATE  > '1000-01-01'  AND c_custkey = 1;
```

### Is the issue reproducible? If so, please provide reproduction instructions.

Yes, pipe the attached script against ```-w 32``` :

```
cat q2.sql | psql -p 6875 -h 127.0.0.1 -U materialize | sort | uniq -c

...
    176     31
      1     62
...
```
In order words, 1 invocation of the query returned 2x rows the expected number. IF X=31 is the expected result, the anomalous result is either ```X+1```, ```2*X``` or ```2*X + 1```.

### PR DESCRIPTION
**Pull request by frankmcsherry**
This collects an updated DD that fixes #5774, and addresses several method calls that have been deprecated.

fixes #5774.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5857)

### CODE REVIEW

**Comment by philip-stoev** [comment]
@frankmcsherry I am going to push the test cases for that into this branch.

**Comment by frankmcsherry** [comment]
That sounds great, thank you!

**Review by philip-stoev — APPROVED** [review]
Thanks, the issue is gone, as expected.

**Comment by frankmcsherry** [comment]
Thanks very much!

**Pull request merged**
