### PR TITLE
canary-cloud: Use Redpanda Cloud

### PR DESCRIPTION
**Pull request by def-**
Fixes: https://github.com/MaterializeInc/cloud/issues/9721

Nightly run: https://buildkite.com/materialize/nightly/builds/9274

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

**Review by benesch — COMMENTED** [review]
This looks fantastic, @def-—thank you! 

We can only run one cloud canary test with Redpanda Cloud at a time, right? Should we create a new pipeline ("Expensive nightly"? "External services nightly"?) so that folks using trigger-ci don't run this test when validating a PR?

**Comment by benesch** [comment]
Ah, beautiful! Well this basically LGTM. Are you still working to get it to pass nightlies? Let me know when you're ready for a full review (and how thorough of a review you feel you need).

**Comment by def-** [comment]
> Ah, beautiful! Well this basically LGTM. Are you still working to get it to pass nightlies?

It worked before, I broke it again by some refactoring. Hopefully the new run is green now: https://buildkite.com/materialize/nightly/builds/9268
If not, should only be some minor changes required. So this should be ready for review.

**Review by benesch — APPROVED** [review]
This is fantastic work, Dennis—thank you so much!

**Pull request merged**
