### PR TITLE
sql: WITH (timestamp_frequency ... ) => WITH (TIMESTAMP GRANULARITY ...)

### PR DESCRIPTION
**Pull request by benesch**
Move the legacy WITH (timestamp_frequency ...) option into the new
enum-ified WITH block as TIMESTAMP GRANULARITY. This is another step
towards #14341 and corrects a longstanding misuse of the word
"frequency." It's an interval, not a frequency; we use "granularity"
here to match the INTROSPECTION GRANULARITY option on clusters.

### Motivation

  * This PR makes progress towards a recognized bug.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-protobuf` label.
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - n/a

### CODE REVIEW

**Review by guswynn — APPROVED** [review]
looks good!

**Review by bkirwi — APPROVED** [review]

**Comment by benesch** [comment]
Well this got approved faster than I expected! Thanks, y'all! If this makes it through tests I'm going to merge as is, even though on Slack I said I might push up a few more commits. I'll submit those as separate PRs instead.

**Comment by frankmcsherry** [comment]
What about "interval"? It could even be an interval!

**Comment by benesch** [comment]
> What about "interval"? It could even be an interval!

Talked with Frank on Slack. Going to send up a different PR to do this for `INTROSPECTION GRANULARITY` and `TIMESTAMP GRANULARITY` all at once!

**Pull request merged**
