### PR TITLE
ore: introduce a canceling retry_async variant

### PR DESCRIPTION
**Pull request by benesch**
It is often desirable to forcibly terminate the operation under retry
when the max duration is reached. Add a `retry_async_canceling` variant
that does this, and use this in testdrive.

Alternative to https://github.com/MaterializeInc/materialize/pull/11172.

### Motivation

  * This PR fixes a previously unreported bug: CI hangs forever if a `SELECT` statement wedges.

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - N/A

### CODE REVIEW

**Review by philip-stoev — APPROVED** [review]
Thank you very much -- if you can fix the CI panics that would be perfect. If there are any test failures left after that, I can fix any timeouts that are needed, etc.

**Comment by benesch** [comment]
I'm off to bed, but hopefully this revision goes over a bit better. Note that this PR is unfortunately going to break @ruchirK's trick to run queries exactly once in  https://github.com/MaterializeInc/materialize/blob/10db3265f2628cfae1fcc534c8fa40cf841e2eda/test/testdrive/github-10587.td#L133-L137.

**Comment by benesch** [comment]
Ok, @philip-stoev, gonna kick this back to you. test/kafka-resumption/sleep.td seems to be correctly timing out, but I'm not sure what it was intended to test before!

**Comment by philip-stoev** [comment]
@benesch Thank you, I will fix the remaining test failures.

**Pull request merged**
