### PR TITLE
tests: platform checks: support changing system vars, add scenario TogglePersistRoundtripSpine

### PR DESCRIPTION
**Pull request by nrainer-materialize**
Nightly: https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Atests%2Fconf-prop-scenario

### CODE REVIEW

**Comment by nrainer-materialize** [comment]
✅ Nightly passes now.

**Comment by danhhz** [comment]
Awesome! Out of curiosity, I kicked off a nightlies run with this new test plus a revert of a bugfix that hopefully it would have caught: https://buildkite.com/materialize/nightly/builds/7594

**Comment by nrainer-materialize** [comment]
> Awesome! Out of curiosity, I kicked off a nightlies run with this new test plus a revert of a bugfix that hopefully it would have caught: https://buildkite.com/materialize/nightly/builds/7594

Cool! Looking forward to the result (and deferring the merge until we have it).

**Review by danhhz — APPROVED** [review]

**Comment by nrainer-materialize** [comment]
> > Awesome! Out of curiosity, I kicked off a nightlies run with this new test plus a revert of a bugfix that hopefully it would have caught: https://buildkite.com/materialize/nightly/builds/7594

@danhhz: Did we expect this build to fail?

**Comment by danhhz** [comment]
That was the hope, yeah. Seems like maybe it's not flipping the config back and forth enough (or concurrently enough?) to have tickled the bug? But also @bkirwi is the real expert here, so I'd be curious for his thoughts

**Comment by nrainer-materialize** [comment]
As suggested by @bkirwi, I will trigger a retry. Furthermore, I will integrate the flipping into the parallel-workload framework (and applying it in there more often).

**Comment by nrainer-materialize** [comment]
> Furthermore, I will integrate the flipping into the parallel-workload framework (and applying it in there more often).

I will do this in a follow-up PR.

**Comment by nrainer-materialize** [comment]
One more question, does the/this changed property actually get effective immediately?

**Comment by bkirwi** [comment]
> I will trigger a retry. Furthermore, I will integrate the flipping into the parallel-workload framework (and applying it in there more often).

Wow, thanks very much!

> does the/this changed property actually get effective immediately?

Yes, generally Persist configs take effect ~immediately. (They need to stream out over the clusterd protocol to take effect there, but in practice it's very quick.)

**Review by def- — COMMENTED** [review]
lgtm

**Pull request merged**
