### PR TITLE
Add a bunch of lints

### PR DESCRIPTION
**Pull request by umanwizard**
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5927)

### CODE REVIEW

**Comment by umanwizard** [comment]
Discussion here: https://gist.github.com/umanwizard/3b8ee3e501f86a2323e6cad68ada1501

**Review by frankmcsherry — APPROVED** [review]
I apologize but I have no clue about lints by name, but rather the visceral experience of being shamed by a program. So, totally up for all of this, as long as each time it happens now I have permission to say things like "rah, this is so wrong" and then be told either 1. "no, it's important for us because ..." or 2. "idc change it".

It seems like the intent here is to have a stronger pre-fab opinion on "if you violate this lint, fix it and don't complain" which seems fine and I'm happy to change my internal thresholds accordingly.

**Comment by umanwizard** [comment]
@frankmcsherry The intent is to have only the lints that are the intersection of the ones we all think are worthwhile.

If you want to look up the effects by name, they are here: https://rust-lang.github.io/rust-clippy/master/

But, the intent is very much "if a lint bothers you, feel free to remove it as part of your PR, without asking anyone".

**Comment by frankmcsherry** [comment]
Well I 100% approve this then!

**Pull request merged**
