### PR TITLE
sql: INSERT RETURNING

### PR DESCRIPTION
**Pull request by mjibson**
See #8521

### Motivation

  * This PR adds a known-desirable feature. #8521

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - Adds support for `RETURNING` in `INSERT`.

### CODE REVIEW

**Comment by benesch** [comment]
Neat! I'm sure @philip-stoev will want to review. One thing that comes to mind is testing unmaterializable functions in the `RETURNING` clause. What happens if you write `RETURNING now()` or `RETURNING mz_logical_timestamp()`, for example?

**Comment by mjibson** [comment]
We need a unique_rowid function now to use as a column default!

**Comment by philip-stoev** [comment]
Item No 1. This panics:

```
CREATE TABLE t (a INT, b INT DEFAULT 11);
 INSERT INTO t (a) VALUES (10) RETURNING b
thread 'coordinator' panicked at 'index out of bounds: the len is 1 but the index is 1', src/sql/src/plan/expr.rs:1779:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::panicking::panic_bounds_check
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:84:5
   3: <mz_sql::plan::expr::HirScalarExpr as mz_sql::plan::expr::AbstractExpr>::typ::{{closure}}
   4: <mz_sql::plan::expr::HirScalarExpr as mz_sql::plan::expr::AbstractExpr>::typ
   5: mz_sql::plan::query::ExprContext::column_type
   6: mz_sql::plan::query::plan_insert_query
   7: mz_sql::plan::statement::dml::describe_insert
   8: mz_sql::plan::statement::describe
   9: mz_coord::coord::describe
  10: mz_coord::coord::Coordinator<S>::describe
  11: mz_coord::coord::Coordinator<S>::handle_describe
  12: mz_coord::coord::Coordinator<S>::message_command::{{closure}}
  13: mz_coord::coord::Coordinator<S>::serve::{{closure}}
  14: std::thread::local::LocalKey<T>::with
  15: tokio::park::thread::CachedParkThread::block_on
  16: tokio::runtime::handle::Handle::block_on
```

**Comment by philip-stoev** [comment]
ITem No 2. This also panics, a variant of the one above:

```
    INSERT INTO t DEFAULT VALUES RETURNING a, b
thread 'coordinator' panicked at 'index out of bounds: the len is 0 but the index is 0', src/sql/src/plan/expr.rs:1779:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::panicking::panic_bounds_check
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:84:5
   3: <mz_sql::plan::expr::HirScalarExpr as mz_sql::plan::expr::AbstractExpr>::typ::{{closure}}
   4: <mz_sql::plan::expr::HirScalarExpr as mz_sql::plan::expr::AbstractExpr>::typ
   5: mz_sql::plan::query::ExprContext::column_type
   6: mz_sql::plan::query::plan_insert_query
   7: mz_sql::plan::statement::dml::describe_insert
   8: mz_sql::plan::statement::describe
   9: mz_coord::coord::describe
  10: mz_coord::coord::Coordinator<S>::describe
  11: mz_coord::coord::Coordinator<S>::handle_describe
  12: mz_coord::coord::Coordinator<S>::message_command::{{closure}}
  13: mz_coord::coord::Coordinator<S>::serve::{{closure}}
  14: std::thread::local::LocalKey<T>::with
  15: tokio::park::thread::CachedParkThread::block_on
  16: tokio::runtime::handle::Handle::block_on
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by philip-stoev** [comment]
Item No 3. This is also a manifestation of the same problem, but more insidious:

This:

```
INSERT INTO t (b) VALUES (10) RETURNING a
```

returns the default for `b` and not the default for `a`

**Comment by mjibson** [comment]
@sploiselle RFAL. Tests from Philip added and fixed, test results manually verified against Postgres.

**Review by sploiselle — APPROVED** [review]
Super clean!

**Pull request merged**
