### PR TITLE
cloudtest: Migrate from psycopg2 to psycopg3

### PR DESCRIPTION
**Pull request by philip-stoev**
Remove all mentions of psycopg2 except in the test/lang/python tests

### Motivation

I am not sure how multiple generations of psycopg will play together, so lets not risk it.

### CODE REVIEW

**Comment by nrainer-materialize** [comment]
> test/lang/python

Why do we want to keep this folder as it is?

**Comment by philip-stoev** [comment]
> test/lang/python

This folder contains tests that use both versions 2 and 3 . It also has its own requirements.txt file.

I tried at least to get that requirements.txt to not use a github SHA for psycopg3 but the same version used elsewhere in the codebase, but for some reason pip fails to install it ... as it uses its own docker image with a stand-alone python, I do not know what the problem is.

**Comment by nrainer-materialize** [comment]
> > test/lang/python
> 
> This folder contains tests that use both versions 2 and 3 . It also has its own requirements.txt file.
> 
> I tried at least to get that requirements.txt to not use a github SHA for psycopg3 but the same version used elsewhere in the codebase, but for some reason pip fails to install it ... as it uses its own docker image with a stand-alone python, I do not know what the problem is.

Ok!

**Comment by nrainer-materialize** [comment]
I am preparing an upgrade for the cloud repo. CC @necaris

**Review by nrainer-materialize — APPROVED** [review]

**Pull request merged**
