### PR TITLE
output consistency: add join support

### PR DESCRIPTION
**Pull request by nrainer-materialize**
This addresses https://github.com/MaterializeInc/materialize/issues/19825 and adds support for joins in all output consistency framework variants.

It replaces the first try in https://github.com/MaterializeInc/materialize/pull/27103.

### Description
* multiple tables per evaluation source are created for the vertical column layout
* data values are randomly assigned to one or more of these tables (that is, the same value can be in multiple tables)
* the first table is supposed to hold most values to avoid that all queries need joins
* data sources for a query are randomly selected
* leafs of expressions are randomly assigned to the query's data sources
* data sources that are not used by any expression in a query will be removed during the minimization step
* for all remaining data sources, the join type (INNER, LEFT OUTER, ...) is chosen and join constraints are generated
* when generating SQL, all expressions and tables use an alias
* random row index filters are applied to all tables
* necessary adjustments to row filters, column filters, minimal reproducible code generator, derivation of expression characteristics, ignore filters, ...

### Examples of Generated Queries (outdated)
```
SELECT
  (trim(LEADING s2.bpchar_8_val FROM s2.text_val)),
  degrees(s3.decimal_39_8_val)
FROM
  <source>_vert_0 s0
INNER JOIN <source>_vert_2 s2
  ON (s0.uint8_val = s2.uint8_val)
LEFT OUTER JOIN <source>_vert_3 s3
  ON (NOT ((s3.int8_val IS NULL)))
WHERE (s0.row_index IN (4, 15))
ORDER BY s0.row_index ASC, s2.row_index ASC, s3.row_index ASC
OFFSET 7;
```

```
SELECT
  bool_or((substring(s0.char_6_val, jsonb_array_length((s0.jsonb_val #> NULL)), s2.uint2_val) !~* NULL)),
  max(s0.timestamptz_array_val),
  array_agg(s0.bpchar_8_val ORDER BY row_index, s0.bpchar_8_val)
FROM
  <source>_vert_0 s0
INNER JOIN <source>_vert_2 s2
  ON (s0.multi_dim_text_array_val = s2.multi_dim_text_array_val)
WHERE (s0.row_index IN (0, 7));
```

```
SELECT
  (s1.int4range_val || s0.int4range_val),
  (s0.uint2_val <= s0.decimal_39_0_val)
FROM
  <source>_vert_0 s0
FULL OUTER JOIN <source>_vert_1 s1
  ON (s0.real_val = s1.real_val)
WHERE (s0.row_index IN (0, 2, 3, 4, 5, 6, 7, 8, 9, 12, 14, 17))
ORDER BY s0.row_index ASC, s1.row_index ASC;
```

```
SELECT
  (s3.jsonb_val #> '{1}'),
  ((s0.jsonb_val @> (s0.jsonb_val -> 1)) OR s3.bool_val),
  (s0.text_val NOT LIKE 'a?c'),
  (UUID 'invalid_value_123')
FROM
  <source>_vert_0 s0
LEFT OUTER JOIN <source>_vert_3 s3
  ON (s0.timestamptz_list_val = s3.timestamptz_list_val)
WHERE (s0.row_index IN (11, 5))
ORDER BY s0.row_index ASC, s3.row_index ASC
LIMIT 13;
```

### Performance Impact
```
select * from v_output_consistency_stats
where branch in ('main', 'nrainer-materialize:output-consistency/join-support')
and framework in ('output-consistency-internal', 'output-consistency-postgres')
order by date desc;
```

```
select build_number, branch, framework, count_generated_expressions, count_ignored_expressions, count_executed_queries
from v_output_consistency_stats
where build_number in (9105, 9101)
and framework in ('output-consistency-internal', 'output-consistency-postgres')
order by framework desc, date desc;
```

#### Output Consistency

|  version  |  build |  generated expressions | executed queries  |
|---|---|---|---|
|  main  |  #9101  |  16101  | 8797  | 
|  main  |  #9159  |  18045  | 9919  | 
|  join-support  | #9105  |  14344  |  8101 |
|  join-support  | #9167  |  43021 ⁉️  |  10455 |
|  join-support  | #9169  |  65611 ⁉️  |  16131 |

#### Postgres Consistency

|  version  |  build |  generated expressions | executed queries  |
|---|---|---|---|
|  main  |  #9101  |  18825  | 9084  | 
|  main  |  #9159  |  16800  | 7958  | 
|  join-support  | #9105  |  17121  |  8153 |
|  join-support  | #9167  |  36032 ⁉️  |  8000 |
|  join-support  | #9169  |  38638 ⁉️  |  3789 |

✅ <s>Ok, this seems to have improved again during the development.</s>
⁉️ join-support is now way faster, why??

### [Commits](https://github.com/MaterializeInc/materialize/pull/28995/commits)
This is based on https://github.com/MaterializeInc/materialize/pull/28992.

### Nightly
❓ https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Aoutput-consistency%2Fjoin-support

### CODE REVIEW

**Comment by nrainer-materialize** [comment]
RFR, sorry for the large change set...

**Review by def- — COMMENTED** [review]
Oh wow, that is huge! Has it found any interesting issues yet?

**Comment by nrainer-materialize** [comment]
> Oh wow, that is huge! Has it found any interesting issues yet?

There were some further instances of evaluation order mismatches but besides that not yet. 😞

**Comment by nrainer-materialize** [comment]
Ready for review. 3 of the 4 last builds passed, the failure was not an inconsistency.

**Review by def- — APPROVED** [review]
Thank you for working on this! I'm a bit disappointed that it hasn't shown issues yet, so maybe not an area for further work. But always good to be able to catch correctness issues in the future with join optimizations coming in.

**Pull request merged**
