### PR TITLE
tests: Expect 0 timestamp in EXPLAIN TIMESTAMP

### PR DESCRIPTION
**Pull request by def-**
Fixes: #19043

### Motivation

  * This PR fixes a recognized bug.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by philip-stoev — APPROVED** [review]
It is OK in terms of silencing the test failure, but it still not clear to me how the timestamp can be zero for a source that is validated to have some data in it (by a prior `SELECT` statement against the source).

**Comment by teskje** [comment]
> It is OK in terms of silencing the test failure, but it still not clear to me how the timestamp can be zero for a source that is validated to have some data in it (by a prior SELECT statement against the source).

For https://github.com/MaterializeInc/materialize/issues/19043, the frontier that is `[0]` is the `since` frontier. That just means the collection was not allowed to compact, not that it's empty.

**Review by teskje — APPROVED** [review]
If this passes the tests, I'm fine with it. I fear it might not though:

* The returned output from https://github.com/MaterializeInc/materialize/issues/19043 contained a bunch of whitespace before the `0` and I'm not sure if anything will remove that.
* There might be FPs, since "0" is a very unspecific regex that can match other things than timestamps.

**Comment by def-** [comment]
It passed locally, but I'll wait for CI of course.

**Comment by teskje** [comment]
> And I couldn't reproduce the 0.

Ah, right, the test is flaky. So it's likely that CI will pass because it doesn't hit the 0 `since` and we still don't actually manage to remove the flake.

**Comment by def-** [comment]
The checker is indeed whitespace-sensitive, so I added the number of whitespaces now (12 since it has to fill the number to the 13 digit minimum of timestamps).

**Pull request merged**
