### PR TITLE
sql: support column specification in INSERTs

### PR DESCRIPTION
**Pull request by elindsey**
https://github.com/MaterializeInc/materialize/issues/3911

This adds support for fully-specified column specs in INSERT. Note that non-fully specified column specs are still unsupported (ie. default values are not inserted for missing columns).

One area I could use feedback on - the RelationDesc type is more flexible than I expected, supporting duplicate and unnamed columns. It's not clear to me if or when that could happen along the INSERT path, but either would lead to a rejection if a column specification is used (which seems like correct behavior).

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4354)

### CODE REVIEW

**Comment by umanwizard** [comment]
unless you need to share a branch with a customer or there is some other good reason to make it live in the main repo, the convention is to make a branch in your own fork and PR from there.

**Review by benesch — COMMENTED** [review]
Looking good! Left you some comments inline.

> One area I could use feedback on - the RelationDesc type is more flexible than I expected, supporting duplicate and unnamed columns. It's not clear to me if or when that could happen along the INSERT path, but either would lead to a rejection if a column specification is used (which seems like correct behavior).

Ah, yeah, this is because something like `SELECT 1` does not assign a column name to the single output column; it comes out as "?column?" in psql. Similarly you can easily construct relations with duplicate columns: `SELECT 1 AS bar, SELECT 1 AS bar`. Since we use `RelationDesc`s for all types of relations, not just tables, we need this flexibility.

Tables should enforce that a) all columns have names, and b) there are no duplicate names. I think currently we enforce (a) but not (b). Would you actually be up for adding the check for (b)? Should be pretty straightforward. As written there are some bugs like the following that result from allowing duplicate names in tables:

```
materialize=> create table t (a int, b int, a int);
CREATE TABLE
materialize=> insert into t (a, a, a) values (1, 2, 1);
INSERT 0 1
materialize=> select * from t;
 a | b | a 
---+---+---
 1 | 1 | 1
(1 row)
```

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4354#-:-MI_QS8IECxtvLAcFo6A:b-x1x914)* status: all files reviewed, 4 unresolved discussions (waiting on @elindsey and @JLDLaughlin)

___
*[src/sql/src/plan/query.rs, line 155 at r1](https://reviewable.io/reviews/materializeinc/materialize/4354#-MI_QAoq16SEkD5lq8Q_:-MI_QAoq16SEkD5lq8Qa:bqpwbgo) ([raw file](https://github.com/materializeinc/materialize/blob/da4401894896ad90450861775014a18cfd790841/src/sql/src/plan/query.rs#L155)):*
> ```Rust
>                 (expr, typ)
>             } else if columns.len() < desc.arity() {
>                 unsupported!("INSERT statement with incomplete column set")
> ```

See note in test file below; this check needs to be a bit more involved in order to reject duplicate columns in the specification.
___
*[src/sql/src/plan/query.rs, line 161 at r1](https://reviewable.io/reviews/materializeinc/materialize/4354#-MI_PBIt5Pi4poBnVo5P:-MI_PBIu4Fpu4KgnxzVh:b-po3k1v) ([raw file](https://github.com/materializeinc/materialize/blob/da4401894896ad90450861775014a18cfd790841/src/sql/src/plan/query.rs#L161)):*
> ```Rust
>                     .filter_map(|x| x)
>                     .enumerate()
>                     .map(|(idx, name)| (name.as_str(), idx))
> ```

We try to keep things as a `ColumnName` wherever possible to ensure normalization happens consistently. This code is correct as written, but it will be a bit more resistant to future refactorings if you remove this call to `as_str`...
___
*[src/sql/src/plan/query.rs, line 166 at r1](https://reviewable.io/reviews/materializeinc/materialize/4354#-MI_PNFM0j-qKp95Z9kG:-MI_PNFM0j-qKp95Z9kH:b-7aje19) ([raw file](https://github.com/materializeinc/materialize/blob/da4401894896ad90450861775014a18cfd790841/src/sql/src/plan/query.rs#L166)):*
> ```Rust
>                 let mut ordering = Vec::with_capacity(columns.len());
>                 for c in &columns {
>                     if let Some(idx) = column_to_index.get(c.as_str()) {
> ```

...and then replace `c.as_str()` here with `normalize::column_name(c))`.
___
*[src/sql/src/plan/query.rs, line 194 at r1](https://reviewable.io/reviews/materializeinc/materialize/4354#-MI_MX2K-LLnEOH5UvCA:-MI_MX2K-LLnEOH5UvCB:b3l32jg) ([raw file](https://github.com/materializeinc/materialize/blob/da4401894896ad90450861775014a18cfd790841/src/sql/src/plan/query.rs#L194)):*
> ```Rust
>             "INSERT statement specifies {} columns, but table has {} columns",
>             typ.arity(),
>             desc.arity(),
> ```

Whoops, good catch!
___
*[test/testdrive/tables.td, line 251 at r1](https://reviewable.io/reviews/materializeinc/materialize/4354#-MI_Pa4LB9GBbK0RX9jV:-MI_Pa4LB9GBbK0RX9jW:bsgsz5) ([raw file](https://github.com/materializeinc/materialize/blob/da4401894896ad90450861775014a18cfd790841/test/testdrive/tables.td#L251)):*
> ```
> 
> ! INSERT INTO t (a) VALUES (1, 'str');
> INSERT statement with incomplete column set not yet supported
> ```

Can you add a test for the following case? Seems to be mishandled currently!

```sql
INSERT INTO t (a, a) VALUES (1, 2)
```

Also, the following causes a panic:

```sql
CREATE TABLE t (a int, b int);
INSERT INTO t (a, b) VALUES (1);
```

I believe you need to verify that the expression you get back from `plan_values` has the correct `.arity()` before calling `project`; otherwise you'll construct an invalid expression upon which `.typ()` panics.

**Comment by JLDLaughlin** [comment]
I didn't see Nikhil's review in time! His comments are a superset of mine, so feel free to address his!

**Review by benesch — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4354#-:-MIa888B1FiGunRSRUhO:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @elindsey)

___
*[src/ore/src/iter.rs, line 31 at r2](https://reviewable.io/reviews/materializeinc/materialize/4354#-MIa81swD8dz6NIae_LN:-MIa81sx2irpE3g9sZ3F:b-ovwawk) ([raw file](https://github.com/materializeinc/materialize/blob/4199f176f5e4fa91da236e4bd5cc8bbbe5f55e07/src/ore/src/iter.rs#L31)):*
> ```Rust
>     {
>         let (lower, _) = self.size_hint();
>         let mut seen = HashSet::with_capacity(lower);
> ```

Good idea!

**Pull request merged**
