### PR TITLE
buildkite insights: make pipeline a positional arg

### PR DESCRIPTION
**Pull request by nrainer-materialize**

### CODE REVIEW

**Review by def- — COMMENTED** [review]
I have an alternative suggestion. The pipeline always has to be passed, so just make it a parameter without a `--pipeline`:
```
bin/buildkite-step-insights --build-step-key pg-cdc-resumption --branch 'main' --build-step-state failed nightlies
```

**Comment by nrainer-materialize** [comment]
> The pipeline always has to be passed

It actually has the `tests` pipeline as default. However, it is not consistent with `buildkite-annotation-search` where this is not the case. I will think about it and make it consistent.

**Comment by def-** [comment]
That still works with my suggestion, you can still have a default, then for tests pipeline it stays as currently.

**Comment by nrainer-materialize** [comment]
> That still works with my suggestion, you can still have a default, then for tests pipeline it stays as currently.

I will do that (once https://github.com/MaterializeInc/materialize/pull/26517 landed).

**Comment by def-** [comment]
You can go first, I have to wait for Nikhil to get up, so I can resolve the conflicts in the meantime.

**Comment by nrainer-materialize** [comment]
Reworked as suggested.

**Review by def- — APPROVED** [review]
No default anymore?

**Comment by nrainer-materialize** [comment]
> No default anymore?

No, it's probably better to make it explicit. And definitively better to have it consistent.

**Pull request merged**
