### PR TITLE
dataflow: enable reading zstd-compressed Kafka topics

### PR DESCRIPTION
**Pull request by benesch**
Support for this is already builtin into librdkafka. Just needed to
enable the "zstd" feature.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4342)

### CODE REVIEW

**Review by ruchirK — APPROVED** [review]

**Comment by cajbecu** [comment]
@benesch how do you do that?

**Comment by benesch** [comment]
@cajbecu how do you do what? Enable compression on a Kafka topic? Set the `compression.type` configuration on either the Kafka topic or your Kafka producer to the desired codec, e.g. `zstd`.

**Comment by benesch** [comment]
Added some testdrive tests to protect against regressions, if either you, @ruchirK, or @wangandi could take another look!

**Comment by cajbecu** [comment]
@benesch how do you make materialize to read from `zstd` enabled kafka topics? I have enabled `zstd` on topics but materialize throws some errors:

```
Sep 30 21:57:10.529 ERROR dataflow::source::kafka: kafka error: Message consumption error: NotImplemented (Local: Not implemented)
```

Is this PR enables this feature? Or do I have to make some configs on materialize side?

**Comment by benesch** [comment]
Oh, @cajbecu, that's exactly the error that this PR is fixing! Once this lands, zstd-compressed topics will just work out of the box.

**Comment by cajbecu** [comment]
@benesch great!

**Review by wangandi — COMMENTED** [review]
Could there be a negative test using a not-real compression algorithm so we can ensure that testdrive is actually trying to feed in the compression type? That way we can be assured in the future that tests are not frivolously passing because testdrive accidentally stopped paying attention to compression type?

**Comment by benesch** [comment]
Not easily, unfortunately. Testdrive doesn't permit you to expect a `$` to fail.

**Review by wangandi — APPROVED** [review]

**Pull request merged**
