### PR TITLE
catalog: Remove shadow catalog

### PR DESCRIPTION
**Pull request by jkosh44**
The shadow catalog was used to test the persist catalog and compare the results to the stash catalog. Now that the persist catalog has been rolled out to all environments we no longer need to constantly test the persist catalog. Removing the shadow catalog will also give us some speed benefits in CI.

Part of #24218

### Motivation
This PR refactors existing code.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [X] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [X] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - There are no user-facing behavior changes.

### CODE REVIEW

**Review by def- — APPROVED** [review]
Great, thank you!

**Comment by jkosh44** [comment]
I'm getting some interesting nightly failures:

```
platform-checks-mz_txn_tables_eager-1  | environmentd: 2024-02-29T15:54:01.918348Z  WARN coord::advance_timelines_interval:coord::group_commit_initiate: mz_adapter::util: halting process: unable to confirm leadership: Catalog(Error { kind: Durable(Fence("current catalog upper 2078 fenced by new catalog upper 2080")) })
```

and 

```
platform-checks-materialized-1  | environmentd: fatal: incompatible persist version 0.88.2, current: 0.90.0-dev, make sure to upgrade the catalog one version at a time
```

It's a bit surprising that these wouldn't happen with the shadow catalog but would happen with the shadow catalog (which wraps the persist catalog). I'll dig deeper.

**Review by mjibson — APPROVED** [review]

**Comment by jkosh44** [comment]
@def- "Checks upgrade from previous version, whole-Mz restart" is failing because it's testing an upgrade from `v0.88.2` to `0.90.0-dev`, which skips `v0.89.X`. Is that on purpose?

**Comment by def-** [comment]
Yes, on purpose, but this scenario makes no sense anymore. I'll remove it: https://github.com/MaterializeInc/materialize/pull/25685

**Comment by nrainer-materialize** [comment]
You can ignore both failures in Nightly. They are unrelated.

**Comment by jkosh44** [comment]
Weirdly the stash tests are all failing at a much higher rate now with transaction conflict errors which is completely unexpected.

**Pull request merged**
