### PR TITLE
Limit row regions to 2MiB

### PR DESCRIPTION
**Pull request by antiguru**
Limit the size of allocations to store Row regions to 2MiB. This counters the doubling effect of using columnation without any limit.

Signed-off-by: Moritz Hoffmann <mh@materialize.com>

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Review by vmarcos — APPROVED** [review]
This looks fine, and a necessary follow-up item from https://github.com/MaterializeInc/materialize/pull/6763#pullrequestreview-1216913582. It might be good to get some performance measurements to back the choice up, or at least to ensure that there is no negative impact, if time allows. I believe @tokenrove was intending to do so?

**Comment by antiguru** [comment]
Feature benchmark in https://buildkite.com/materialize/nightlies/builds/4739

**Comment by umanwizard** [comment]
I'm not sure this will make a difference, though, because for allocations larger than page size, the kernel shouldn't need to allocate any pages that aren't actually touched.

**Comment by antiguru** [comment]
Feature benchmark doesn't report any new findings.

**Pull request merged**
