### PR TITLE
persist-txn: ensure each unique batch's serialization is unique

### PR DESCRIPTION
**Pull request by danhhz**
The code to handle retracting applied batches assumes that the encoded representation of each is unique (it works by retracting and cancelling out the raw bytes). It's possible to make that code handle any diff value but the complexity isn't worth it.

So ensure that every committed batch has a unique serialization. Technically, I'm pretty sure that they're naturally unique but the justification is long, subtle, and brittle. Instead, just slap a random uuid on it.

Replaces #23821

Touches https://github.com/MaterializeInc/materialize/issues/22173
Touches https://github.com/MaterializeInc/materialize/issues/22801

### Motivation

  * This PR adds a known-desirable feature.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by jkosh44 — APPROVED** [review]

**Comment by danhhz** [comment]
TFTR!

**Comment by danhhz** [comment]
Oh shit. Was just about to merge this and realized that it's not backward compatible with what just rolled out to staging. Hmmm... gonna have to think about this

**Comment by danhhz** [comment]
Okay this backward compatibility is a little spicy but it should work. I'll see if I can test it end-to-end locally before I merge

**Comment by danhhz** [comment]
:tada:

```
environmentd: 2024-01-04T22:33:46.347656Z  WARN environmentd::run:environmentd::serve:bootstrap: mz_persist_txn::proto: WIP got batch in legacy format ProtoBatch { shard_id: "s7370eaa4-2b62-403f-9dc8-184c28413071", version: "0.82.0-dev", batch: Some(ProtoHollowBatch { desc: Some(ProtoU64Description { lower: Some(ProtoU64Antichain { elements: [0] }), upper: Some(ProtoU64Antichain { elements: [1704407178741] }), since: Some(ProtoU64Antichain { elements: [0] }) }), parts: [ProtoHollowBatchPart { key: "n0008200/p491defea-dd97-4b5b-992c-24286df2f6fe", encoded_size_bytes: 976, key_lower: b"\n\x04\n\x02\x18\x01", key_stats: Some(b"\x08\x01\x12\x0f\n\x03err\x12\x08\n\x02\x08\x01\"\x02\n\0\x12\x1c\n\x02ok\x12\x16\n\0\x12\x12\x08\x01\x12\x0e\n\x01a\x12\t\n\0\x1a\x05@\x01\xa8\x01\x01") }], len: 1, runs: [], deprecated_keys: [] }) }
environmentd: 2024-01-04T22:33:46.376883Z  WARN environmentd::run:environmentd::serve:bootstrap: mz_persist_txn::proto: WIP got batch in legacy format ProtoBatch { shard_id: "s7370eaa4-2b62-403f-9dc8-184c28413071", version: "0.82.0-dev", batch: Some(ProtoHollowBatch { desc: Some(ProtoU64Description { lower: Some(ProtoU64Antichain { elements: [0] }), upper: Some(ProtoU64Antichain { elements: [1704407178741] }), since: Some(ProtoU64Antichain { elements: [0] }) }), parts: [ProtoHollowBatchPart { key: "n0008200/p491defea-dd97-4b5b-992c-24286df2f6fe", encoded_size_bytes: 976, key_lower: b"\n\x04\n\x02\x18\x01", key_stats: Some(b"\x08\x01\x12\x0f\n\x03err\x12\x08\n\x02\x08\x01\"\x02\n\0\x12\x1c\n\x02ok\x12\x16\n\0\x12\x12\x08\x01\x12\x0e\n\x01a\x12\t\n\0\x1a\x05@\x01\xa8\x01\x01") }], len: 1, runs: [], deprecated_keys: [] }) }
environmentd: 2024-01-04T22:33:46.562655Z  WARN environmentd::run:environmentd::serve:bootstrap: mz_persist_txn::proto: WIP got batch in legacy format ProtoBatch { shard_id: "s7370eaa4-2b62-403f-9dc8-184c28413071", version: "0.82.0-dev", batch: Some(ProtoHollowBatch { desc: Some(ProtoU64Description { lower: Some(ProtoU64Antichain { elements: [0] }), upper: Some(ProtoU64Antichain { elements: [1704407178741] }), since: Some(ProtoU64Antichain { elements: [0] }) }), parts: [ProtoHollowBatchPart { key: "n0008200/p491defea-dd97-4b5b-992c-24286df2f6fe", encoded_size_bytes: 976, key_lower: b"\n\x04\n\x02\x18\x01", key_stats: Some(b"\x08\x01\x12\x0f\n\x03err\x12\x08\n\x02\x08\x01\"\x02\n\0\x12\x1c\n\x02ok\x12\x16\n\0\x12\x12\x08\x01\x12\x0e\n\x01a\x12\t\n\0\x1a\x05@\x01\xa8\x01\x01") }], len: 1, runs: [], deprecated_keys: [] }) }
```

**Pull request merged**
