### PR TITLE
Rename `{expr, sql}::{Relation, Scalar}Expr to `{Mir, Hir}{Relation, Scalar}Expr`

### PR DESCRIPTION
**Pull request by umanwizard**
In a long Slack thread (https://materializeinc.slack.com/archives/CM7ATT65S/p1611772013041400) , this seemed to be the set of names that annoyed the fewest people!

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5491)

### CODE REVIEW

**Comment by ruchirK** [comment]
maybe dumb q but should the `expr` crate still be called `expr` now? or is there a better name we could use?

**Comment by benesch** [comment]
No great point! Probably ought to rename that crate to `mir`

**Review by frankmcsherry — APPROVED** [review]
lgtm!

**Comment by JLDLaughlin** [comment]
🎉

**Review by JLDLaughlin — APPROVED** [review]
🎉

**Review by benesch — APPROVED** [review]

**Pull request merged**
