### PR TITLE
storage/sources: Minor fixes for source table objects

### PR DESCRIPTION
**Pull request by rjobanp**
### Motivation

  * This PR fixes a recognized bug. Fixes https://github.com/MaterializeInc/materialize/issues/29496

Also fixes https://github.com/MaterializeInc/materialize/issues/29562 and fixes https://github.com/MaterializeInc/materialize/issues/29503 and fixes https://github.com/MaterializeInc/materialize/issues/29564

We were error logging whenever source tables were dropped after their corresponding source which was always happening when they are dropped together in a transaction due to the implicit ordering in `src/adapter/src/coord/ddl.rs`. There isn't an actual bug in dropping out-of-order so I could have just removed the error log but I thought that it would be better to keep it since it might be useful in any future issue around dependency ordering.

The error log happens here:
https://github.com/MaterializeInc/materialize/blob/03b586b73d8379be9113fc9fd96fc1d9a71544dc/src/storage-controller/src/lib.rs#L1453-L1461

### Tips for reviewer

@MaterializeInc/testing I wasn't actually able to repro https://github.com/MaterializeInc/materialize/issues/29496 using the command in that issue but I believe this is the fix for that issue. If you could try to repro on this branch that would be awesome.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

**Review by jkosh44 — APPROVED** [review]

**Review by def- — COMMENTED** [review]
This is failing a bunch, but is it possible to create a deterministic test for this?

**Comment by rjobanp** [comment]
> This is failing a bunch, but is it possible to create a deterministic test for this?

@def- what do you mean by 'this'? Do you mean the `primary source {ingestion_id} seemingly dropped before subsource {id}` error report? Since it is only reported as an error log and is not an actual bug or error I don't know how we can add a test for it. It should be reproducible on main without this PR when doing a `DROP SOURCE {} CASCADE` for a source with a table attached, since that causes the source to be dropped from the storage controller before the table which is the thing I fixed here

**Comment by def-** [comment]
Something like this:
https://github.com/MaterializeInc/materialize/blob/03b586b73d8379be9113fc9fd96fc1d9a71544dc/test/cluster/mzcompose.py#L781-L786

**Comment by nrainer-materialize** [comment]
> Something like this:
> 
> https://github.com/MaterializeInc/materialize/blob/03b586b73d8379be9113fc9fd96fc1d9a71544dc/test/cluster/mzcompose.py#L781-L786

Well, we are expecting that this error message no longer occurs.

**Comment by rjobanp** [comment]
Yes exactly, if this fix works we will no longer see other tests fail when encountering that error message

**Pull request merged**
