### PR TITLE
coord: handle already existing views for CREATE VIEWS

### PR DESCRIPTION
**Pull request by petrosagg**
fixes issue reported by Annie Dang: https://materializecommunity.slack.com/archives/C015KDVS7EV/p1628052544035300

### CODE REVIEW

**Comment by philip-stoev** [comment]
@petrosagg can you please add a test? Thanks!

**Comment by benesch** [comment]
Aw, hm, seems like `if_not_exists` really wants to live on `CreateViewsPlan`, rather than on the inner plan.

**Comment by benesch** [comment]
I sent #7688. I haven't tested that at all, but I figured it could be a good base.

**Comment by petrosagg** [comment]
@benesch @philip-stoev I pushed a test in Nikhil's PR. Closing this one in favour of #7688

**Pull request closed without merging**
