### PR TITLE
test: unburden single-replica cluster more widely

### LINKED ISSUE #24399: kafka-time-offset.td: Kafka source gets stuck
### What version of Materialize are you using?

d6a3c785559d40564f9b70fb8536a43ac1e8cdc0

### What is the issue?

`kafka-time-offset.td` fails with
```
kafka-time-offset.td:108:1: error: deadline has elapsed
```

in "testdrive with SIZE 8" of https://buildkite.com/materialize/nightlies/builds/5946#018cf9ca-e4c3-44df-8c1c-10fdca360fae.

Other builds:
* https://buildkite.com/materialize/nightlies/builds/5960
* https://buildkite.com/materialize/nightlies/builds/5952

This seems to occur only since 5ec8eb4d8d5322ad81ec67f6d56c917b132c1c88 (verified with https://buildkite.com/materialize/nightlies/builds/5960).

### PR DESCRIPTION
**Pull request by sploiselle**
kafka-time-offset creates too many sources to have it run on a single cluster. for simplicity's sake move each sources to its own cluster.

This approach also makes sense to take more widely, so I've applied it to most testdrive tests that create more than 4 sources or sinks.

### Motivation

This PR fixes a recognized bug. Fixes #24399

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by sploiselle** [comment]
@philip-stoev Have some anecdotal data that generally reducing the load on the single cluster causes fewer spurious failures. https://buildkite.com/materialize/nightlies/builds/6021#018d17f2-5e4f-4928-8f9c-85af5107ee91

**Comment by philip-stoev** [comment]
@nrainer-materialize I must admit I have no idea. the testdrive source code would say.

**Comment by nrainer-materialize** [comment]
> Triggered a nightly build with testdrive checks: https://buildkite.com/materialize/nightlies/builds/6036

Nightly is green.

**Review by nrainer-materialize — APPROVED** [review]

**Comment by nrainer-materialize** [comment]
> > @philip-stoev, when will clusters created in td files be torn down? After the execution of each td file?

> @nrainer-materialize I must admit I have no idea. the testdrive source code would say.

Apparently not. `c.sanity_restart_mz()` is conducted after each file but no cleanup seems to happen. Though, there is a `# TODO: should we drop clusters as part of resetting the MZ state?`.

**Comment by sploiselle** [comment]
@philip-stoev can I get more detail about what your question is/scenario you're thinking of?

**Comment by sploiselle** [comment]
@nrainer-materialize Sorry--that TODO should have been removed. We tear down clusters that aren't running any user objects whenever we reset the testdrive state. #24308

**Pull request merged**
