### PR TITLE
orchestrator-process: add context to secrets errors

### PR DESCRIPTION
**Pull request by benesch**
This will help us confirm whether the error in #28570 is missing secrets or something else.

### Motivation

   * This PR will help us track down a bug.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

**Review by def- — APPROVED** [review]
If this is just temporary, then no need to merge. I'll run it locally:
```shell
while true; do bin/mzcompose --find platform-checks down &&  bin/mzcompose --find platform-checks run default --scenario=ZeroDowntimeUpgradeEntireMzFourVersions --seed=019117ca-ac2b-41f2-ab72-85fd9fa744fd || break; done
```

**Review by aljoscha — APPROVED** [review]
lgtm! also if/when we want this in prod

**Comment by benesch** [comment]
> If this is just temporary, then no need to merge.

No this is good hygiene for errors and will make it much more obvious if something in this realm goes wrong in the future. Very much want this additional context in CI for the long haul!

**Review by def- — COMMENTED** [review]
Maybe I'm missing something. I reproduced the issue locally but am not seeing anything with these contexts:
```
13:1: error: executing query failed: db error: ERROR: No such file or directory (os error 2): ERROR: No such file or directory (os error 2)
```
services.log: 
[services.log.zip](https://github.com/user-attachments/files/16500261/services.log.zip) (`grep -E "(writing secret|deleting secret|listing secrets|reading secret)" services.log` is empty)

Edit: oh, this can't work because the old versions in the upgrade (where this is failing) don't have the changes of course!

**Comment by benesch** [comment]
> Edit: oh, this can't work because the old versions in the upgrade (where this is failing) don't have the changes of course!

Yep, exactly! 🙈 I was thinking we could just let CI run with this for a week or two and after this makes it into a release, we should start seeing it in the upgrade test.

**Comment by def-** [comment]
It seems risky to not know for a week where this error comes from. I can locally patch this change into older versions and use those as the upgrade base and then we can get results later today.

**Comment by benesch** [comment]
Oh, wow, incredible. That sounds great to me. Although do note that since we're not planning to roll this out to production in the next week I'm not too worried about the risk here; it could only strike staging and canary environments.

**Comment by def-** [comment]
```
19:1: error: executing query failed: db error: ERROR: reading secret {id}: No such file or directory (os error 2): ERROR: reading secret {id}: No such file or directory (os error 2)
```
Fix for the `{id}` not being formatted: https://github.com/MaterializeInc/materialize/pull/28823

**Pull request merged**
