### PR TITLE
Allow --orchestrator=kubernetes-local flag

### PR DESCRIPTION
**Pull request by brennanvincent**
This will be useful for the k8s-based local testing framework.

Currently just prevents anti-affinity rules from being applied, but I can imagine there being more differences in the future

### Motivation

AA rules do not make sense for local dev

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-protobuf` label.
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - None

### CODE REVIEW

**Comment by benesch** [comment]
Gonna drop some comments on Slack!

**Comment by benesch** [comment]
Recording Slack comments for posterity: I'd personally feel better if we didn't special case this, and instead just created multinode kind/minikube clusters!

**Comment by philip-stoev** [comment]
Lets keep this open for a big while I get my bearings around KinD

**Comment by brennanvincent** [comment]
*shrug* I'm happy to leave it open! @philip-stoev , @benesch , let me know if we come to a consensus about closing it or landing it.

**Comment by philip-stoev** [comment]
I was able to get a multi-node KinD cluster going, so this hack is no longer needed. Thank you and apologies for the time wasted.

**Comment by brennanvincent** [comment]
The time wasted was at most a few minutes. No worries at all!

**Pull request closed without merging**
