### PR TITLE
(doc) Added note recommending use of CREATE SOURCE for streaming data

### PR DESCRIPTION
**Pull request by msudberg**
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5627)

### CODE REVIEW

**Comment by benesch** [comment]
Is there somewhere I can get more context on this? I'm not sure I understand where the 10% recommendation came from!

Also—and this is separate—I'm really confused about why this doc calls tables "non-streaming data." I don't think that's ... accurate? In a very real sense tables are a materialized source representing a stream of `INSERT` commands. Happy to take a pass at this, if folks want!

**Comment by wangandi** [comment]
Context is here: #5611. A user tried to stream in many TBs of data using `CREATE TABLE` and then was confused when Materialize OOM'ed. To me, this represents a need to highlight in our docs that if you have lots of data that you want Materialize to read, you shouldn't be getting it into Materialize using `CREATE TABLE`.

**Comment by msudberg** [comment]
The part where we define TABLES as for non-streaming data isn't new, so if that's wrong, it would be great to get a better definition.

**Comment by wangandi** [comment]
As for the 10% recommendation, as stated in [here](https://materializeinc.slack.com/archives/C015RHB3LDR/p1612486773118200) it is a completely handwavy guesstimate at the upper bound of how much space should be devoted to tables if you're just trying out the product. The guesstimate takes into account that
* we probably want to have at least several x (table size) of RAM remaining in case the user creates materialized views like `select max(a) from foo` which expands O(table size) memory. 
* We don't want the percentage taken up by tables to be too low in case a user is trying out a Materialize on a low-resource machine since that would prevent the user from trying out a Materialize with an adequate amount of data.

**Comment by benesch** [comment]
Ok, I refactored the `CREATE TABLE` docs here (https://github.com/MaterializeInc/materialize/pull/5634) to avoid the term "non-streaming" and to really stress that you should be using sources instead of tables. I also tried to capture your logic in prose, @wangandi, without explicitly specifying a number. What do you two think? My fear with saying "10%" is that a number that specific implies a rule that is far more precise that it actually is.

**Comment by benesch** [comment]
This got incorporated into #5634. Thanks again @msudberg, and sorry for derailing your PR with broader comments about the `CREATE TABLE` doc!

**Pull request closed without merging**
