### PR TITLE
http-util: extract handle_prometheus handler

### PR DESCRIPTION
**Pull request by danhhz**
This pulls the logic out of materialized into a new crate so other
binaries can depend on it. It also wires the handler up to the existing
http console servers in storaged and computed.

### Motivation

   * This PR refactors existing code.

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - N/A

### CODE REVIEW

**Comment by danhhz** [comment]
I swear I saw a TODO for this somewhere earlier today and now I can't seem to find it...

Also, for computed/storaged, should the flag get passed through the orchestrator or will cloud set them as env vars?

**Comment by benesch** [comment]
So `storaged` and `computed` already have a `--http-console-addr` server which is meant to serve this kind of stuff! And the `MetricsServer` is turning into an `InternalServer` in `materialized` after #12740. I would advocate for pulling out _just_ `handle_prometheus` into its own crate, and dropping a route for that handler into the existing HTTP console server in `storaged` and `computed`. If it doesn't seem worth having a whole crate for just one function, you could drop `handle_metrics` into `http-util` alongside `handle_liveness_check`.

> Also, for computed/storaged, should the flag get passed through the orchestrator or will cloud set them as env vars?

If you make this part of the HTTP console server then it's already properly wired up in the orchestrator!

**Comment by benesch** [comment]
Sorry, it's late, and that's kind of word soup. Give me a holler tomorrow if unclear.

**Comment by danhhz** [comment]
makes sense! I only did it this way because I thought I saw a TODO that specified this (then I couldn't find the TODO once I'd typed it up). unclear if I hallucinated the TODO or was just on an old branch or what. looks like 12740 is merging imminently, so I'll wait for that and retype this

**Comment by danhhz** [comment]
followup Q! is it desirable to move InternalServer (or its moral equivalent) next to the two route handlers so all of environmentd, storated, computed can share it? it seems close but not identical to what storaged and computed are doing. dunno if that's historical accident or if they actually do want different behaviors

**Comment by benesch** [comment]
Each binary will want the ability to potentially mount in custom route handlers. I'm good with any solution that permits that. It does seem like a liveness check and a metrics server are fundamental to all binaries. Could rig it up so that you each binary could [`merge`](https://docs.rs/axum/latest/axum/struct.Router.html#method.merge) in additional routers to the `InternalServer`.

**Comment by danhhz** [comment]
gotcha! I was just about finished putting the finishing touches on pulling the handler out and hooking it up to the existing servers, so I went ahead and pushed that as a commit. I'll take a swing at extracting the server

**Comment by danhhz** [comment]
hmm just re-read your comment and you didn't actually even say to do that. okay, I think this is ready for review!

**Review by benesch — APPROVED** [review]
LGTM too!

**Comment by danhhz** [comment]
TFTR!

**Pull request merged**
