### PR TITLE
persist: fix bug with stats on shards with all no-stats columns

### PR DESCRIPTION
**Pull request by danhhz**
We skip stats on certain ScalarTypes, including MzAclItem. If every column in a struct is skipped, we end up with an empty struct. This resulted in a len-mismatch error at validate time because we were defaulting empty structs to len 0. Instead, manually maintain the length of columnar structs during construction.

### Motivation

  * This PR fixes a previously unreported bug.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by danhhz** [comment]
@bkirwi I don't love this fix, so happy to brainstorm further. happy to explain what's going on in detail, but might be easier on a huddle

**Comment by danhhz** [comment]
okay talked this out offline and it seems that all long-term solutions to the issue look basically like what's here, plus maybe a better abstraction. I did have one idea for really hacky fix (sniff out zero column key schemas in `PartStats::legacy_part_stats`), but it feels particularly gross and I think the regression test we'd have to write for it would be pretty unfortunate, so don't think it's a nice targeted hack

marking this as ready to go

**Review by bkirwi — APPROVED** [review]
Looks good!

**Comment by danhhz** [comment]
TFTR!

**Pull request merged**
