### PR TITLE
coord: Fix timestamp selection for read then write queries 

### PR DESCRIPTION
**Pull request by jkosh44**
Previously, read then write queries performed reads by explicitly
specifying an AS OF equal to the global read timestamp. There was no
validation that the selected timestamp was greater than or equal to the
since of the involved tables. This is usually not an issue, because the
global read timestamp is usually greater than or equal to since. This
is not true when logical compaction window is 0, in which case the
global read timestamp is less than since.

This commit modifies the timestamp selection for read then write
operations to be identical to timestamp selection for normal reads.
Normal timestamp selection already factors in the global timestamp for
user tables, so the timestamp selected should be the same for all
values of logical compaction window greater than 0.

Additionally, and maybe more importantly, this commit also happens to
fix a bug that allowed certain read-then-write statements to execute
inside of a transaction. 

Works towards fixing https://github.com/MaterializeInc/materialize/issues/13221

### Motivation
This PR fixes a recognized bug.

### Testing

- [X] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - N/A

### CODE REVIEW

**Comment by jkosh44** [comment]
@teskje We'll see if this fixes anything

**Comment by jkosh44** [comment]
Well it seems like that fixed half the errors. Still not really sure what the others ones are about.

**Comment by jkosh44** [comment]
I probably won't look into the other errors now because I don't have the bandwidth. This might be worth merging on it's own though since it fixes some issues.

**Review by teskje — APPROVED** [review]

**Comment by jkosh44** [comment]
Also, there probably are some strict serializable consistency violations in this, due to the fact that we sometimes read a user table ahead of the global timestamp. It's probably not worth thinking about right now since we don't guarantee strict serializability anyway.

Also this only works because table advancements don't try and lock the global write lock. The sequence of events is something like this when logical compaction window is set to 0:
1. Read then Write acquires lock.
2. Read then Write sends out a read at with a timestamp equal to `upper`.
3. Read is blocked.
4. Tables are eventually advanced to `upper` is increased.
5. Read is able to execute and return at the old `upper`.
6. Read then Write executes write.

If the table advancement tried to acquire the write lock, then we'd encounter a deadlock. (This is a problem in https://github.com/MaterializeInc/materialize/pull/12979).

**Comment by teskje** [comment]
> I probably won't look into the other errors now because I don't have the bandwidth.

I didn't expect all these to be fixed quickly! I don't think they are very critical, since setting the compaction window to zero is probably not something anyone ever does in production. It just seems worth doing from time to time to shake out wrong assumptions in our code.

Thanks for taking a look!

**Comment by mjibson** [comment]
> current transaction is aborted, commands ignored until end of transaction block: ERROR: current transaction is aborted

From testdrive this often means that something failed (with a useful error message) and moved the txn into a failed state, then testdrive happily retried that statement which will now always fail due to the txn state, and it returns that not useful error message. Generally this means you need to run this locally without testdrive or add coord logging to see what the original error message is. Sometimes this also means teaching testdrive to *not* retry certain kinds of things so that it always returns the useful error message, which should always be the case inside of a txn.

**Comment by mjibson** [comment]
> we sometimes read a user table ahead of the global timestamp

> This is not true when logical compaction window is 0, in which case the global read timestamp is less than since.

I think these are worth understanding more before merging this PR. I am worried that the change here is working around something that's not working as expected. For example, if global timestamp is advanced to 5 in read mode and so coord sends a close (well, append) message at ts 5 for all tables. With 0 compaction window, the controller advances the uppers and sinces of all tables to 5 (is that right? do i have an off-by-one here?). Then I would expect the RTW to select 5 as its read time, so I wouldn't expect this failure to happen at all.

> We should perhaps teach testdrive to check the txn state and not retry in that case

I'm not able to find an API for this in the rust postgres client. This means it might be non-trivial to do.

> `INSERT INTO now_inc VALUES (now()), (now())`

Is being planned as a RTW because `now()` isn't a constant: https://github.com/MaterializeInc/materialize/blob/e88d02f1778276dfd9650940524fe51386740d3b/src/coord/src/coord.rs#L4491. Yes, we should absolutely disallow this in a txn before reaching this point. Luckily the txn ops correctly detect and handle this case preventing correctness problems, but it's obviously just wrong for users.

**Comment by jkosh44** [comment]
> For example, if global timestamp is advanced to 5 in read mode and so coord sends a close (well, append) message at ts 5 for all tables. With 0 compaction window, the controller advances the uppers and sinces of all tables to 5 (is that right? do i have an off-by-one here?). 

You do have an off-by-one here. If the global timestamp is advanced to 5 in read mode, the coord sends a close message at ts 6 for all tables (see `read_ts` where `advance_to` is set to `ts.step_forward()`. So with a 0 compaction window, the controller advances the uppers and sinces of all tables to 6.

**Comment by mjibson** [comment]
> You do have an off-by-one here.

Ah! I wonder if the correct fix for the original problem here then is to have the coordinator manually hold back compaction for all tables to the global read timestamp (practically ignoring a 0 compaction window, but kinda in a different way), which would prevent any of the correctness issues you brought up above.

**Comment by jkosh44** [comment]
> Ah! I wonder if the correct fix for the original problem here then is to have the coordinator manually hold back compaction for all tables to the global read timestamp (practically ignoring a 0 compaction window, but kinda in a different way), which would prevent any of the correctness issues you brought up above.

Yeah I think that'd be a good fix and part of the proposal for strict serializability. It does mean that we effectively ignore logical compaction windows less than 1 for tables.

**Comment by jkosh44** [comment]
@mjibson at a very low priority I'd like to revisit this PR. Not necessarily for 0ms compaction windows, I just think it would remove some unnecessary complexity if we removed `AS OF` from read-then-write statements.

**Comment by jkosh44** [comment]
Closing for now. I may revisit it when we have a more comprehensive consistency based test framework.

**Pull request closed without merging**
