### PR TITLE
ci: bounded memory: increase clusterd_memory

### PR DESCRIPTION
**Pull request by nrainer-materialize**
Discussion: https://materializeinc.slack.com/archives/C057X0NG91B/p1700053829112209

Nightly: https://buildkite.com/materialize/nightlies/builds/5236

### CODE REVIEW

**Review by def- — APPROVED** [review]
That is more than 500 MB, was it still red with 4.1 GB?

**Comment by nrainer-materialize** [comment]
> That is more than 500 MB, was it still red with 4.1 GB?

Oh, this was not intended! Will change and retest once this build completes (want to see if other scenarios also need more memory).

**Comment by philip-stoev** [comment]
Please consider associating this commit with the ticket about the underlying regression by mentioning the ticket # in the commit message.

**Comment by nrainer-materialize** [comment]
See https://github.com/MaterializeInc/materialize/issues/23175#issuecomment-1816081850.

**Pull request closed without merging**
