### PR TITLE
adapter: Add resource limit for cluster replicas

### PR DESCRIPTION
**Pull request by jkosh44**
Adds a resource limit for total cluster replicas.

### Motivation
  * This PR adds a feature that has not yet been specified.
 
### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - This release adds a resource limit for the total amount of cluster replicas.

### CODE REVIEW

**Review by andrewrodriguez-m — APPROVED** [review]
lgtm

**Review by tr0njavolta — APPROVED** [review]
Docs changes look good!

**Review by mjibson — APPROVED** [review]

**Review by benesch — COMMENTED** [review]
The code here LGTM, but we (the org, not you!) skipped an important design step here. I think we should have that design discussion before merging this, as each limit has some cognitive tax, and the fewer ways we limit cluster replicas, the better.

**Comment by benesch** [comment]
Here's the design, retroactively: https://www.notion.so/materialize/Self-guided-trial-viability-47c4b14f19b44c58a630d360a7e615a8?pvs=4#8d145b486c2442f6befce6344eb90947

**Comment by jkosh44** [comment]
Replaced by #18830

**Pull request closed without merging**
