### PR TITLE
sql: restrict `CREATE SINK` to unsafe mode

### LINKED ISSUE #12816: Mark sinks as experimental
Sinks have serious defects in Materialize Platform. In particular:

  * They are incorrectly in the compute layer rather than the storage layer.
  * They have undefined behavior when using a compute cluster.
  * They do not handle restarts of compute clusters.

I propose we mark sinks as experimental until the above deficiencies are addressed, so that users don't run into these rough edges.

cc @uce

### PR DESCRIPTION
**Pull request by benesch**
Sinks have serious defects in Materialize Cloud, so we're disabling them
for now.

Fix #12816.

### Motivation

  * This PR fixes a recognized bug.

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - n/a

### CODE REVIEW

**Review by uce — APPROVED** [review]
LGTM mod the test failure.

Afaict, `test/kafka-sasl-plain` still uses yaml-based configuration and has to set unsafe-mode manually in [mzcompose.yml](https://github.com/MaterializeInc/materialize/blob/da4de73/test/kafka-sasl-plain/mzcompose.yml#L49).

**Comment by benesch** [comment]
> LGTM mod the test failure.
> 
> Afaict, `test/kafka-sasl-plain` still uses yaml-based configuration and has to set unsafe-mode manually in [mzcompose.yml](https://github.com/MaterializeInc/materialize/blob/da4de73/test/kafka-sasl-plain/mzcompose.yml#L49) (I suspect that there are more tests using `CREATE SINK`, but they run Python-based mzcompose which enables unsafe mode by default).

Right as always! Updated.

**Comment by teskje** [comment]
The upgrade tests fail because they pass the `environment` argument to `Materialized`, which overwrites the default environment variables. This should be fixed by (not tested):

```diff
diff --git a/test/upgrade/mzcompose.py b/test/upgrade/mzcompose.py
index 519b48dd9..de80058cf 100644
--- a/test/upgrade/mzcompose.py
+++ b/test/upgrade/mzcompose.py
@@ -51,7 +51,7 @@ SERVICES = [
     Postgres(),
     Materialized(
         options=" ".join(mz_options.values()),
-        environment=[
+        environment_extra=[
             "SSL_KEY_PASSWORD=mzmzmz",
         ],
         volumes_extra=["secrets:/share/secrets"],
@@ -148,7 +148,7 @@ def test_upgrade_from_version(
                 for start_version, opt in mz_options.items()
                 if from_version[1:] >= start_version
             ),
-            environment=[
+            environment_extra=[
                 "SSL_KEY_PASSWORD=mzmzmz",
             ],
             volumes_extra=["secrets:/share/secrets"],
```

@benesch I can take over making the tests pass on this PR if you like. (My ulterior motive is getting the last box ticked in https://github.com/MaterializeInc/materialize/issues/11240 ;))

**Comment by uce** [comment]
@teskje Please feel free to bring this over the finish line! We encourage pushing to PR branches.

**Comment by benesch** [comment]
Woohoo! Thanks, @teskje! There are few things I like more than waking up to a PR that has magically gone green and merged!

**Pull request merged**
