### PR TITLE
..= in query plans

### PR DESCRIPTION
**Pull request by umanwizard**
### Motivation

`..` is confusing because in Rust, it means exclusive -- not half-open -- ranges.

### Checklist

- [N/A] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

**Review by guswynn — APPROVED** [review]
So much better!!

**Comment by aalexandrov** [comment]
> `..` is confusing because in Rust, it means inclusive -- not half-open -- ranges.

I think you might want to change the description here.

**Review by aalexandrov — APPROVED** [review]

**Review by frankmcsherry — APPROVED** [review]
This seems good to me.

**Comment by uce** [comment]
@umanwizard There is a left-over in [explain.md:201]( https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/sql/explain.md) I believe.

**Pull request merged**
