### PR TITLE
docs: Fix grammar of mat view WITH options

### PR DESCRIPTION
**Pull request by ggevay**
Fixes two issues with the grammar diagram of CREATE MATERIALIZED VIEW:
- It looked as if `WITH ()` (i.e., empty parens after `WITH`) would be possible.
- It looked as if `ASSERT NOT NULL` and `RETAIN HISTORY` can come only in this order, but actually `ASSERT NOT NULL` can be specified also after `RETAIN HISTORY` (even both before and after).

Note that the new diagram is also not perfect, because now it looks as if `RETAIN HISTORY` could be specified more than once. I think we have to accept this, because it seems impossible to exactly specify using BNF that these options can be specified in any order, and `ASSERT NOT NULL` can be specified any number of times, but `RETAIN HISTORY` can only be specified once. I think it's ok that we are not capturing certain restrictions in the grammar diagram, especially if they are handled by planning and not by parsing. (For example, it's also impossible to capture that `ASSERT NOT NULL` can't be specified for the same column twice.)

Also, the new layout seems cleaner overall, especially when I add REFRESH soon.

Note that I did not add the optional `=` for `ASSERT NOT NULL`. Started a discussion on this here:
https://materializeinc.slack.com/archives/C063H5S7NKE/p1716888019218749

Plus the commit removes a stale PrPr notice fragment for ASSERT NOT NULL.

Next I'm going to work on adding REFRESH, but I'd like to get an opinion on the above before I get too deep into the REFRESH grammar.

### Motivation

Fixes minor docs issues.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by ggevay** [comment]
Cherry-picked @arusahni's commit from [here](https://github.com/MaterializeInc/materialize/pull/26222) to make the hugo build work on newer hugo. It works for me now on hugo v0.126.3.

**Review by def- — APPROVED** [review]
No complaints from QA side

**Comment by ggevay** [comment]
CI is failing in "Lint docs" for some reason:
https://buildkite.com/materialize/test/builds/83401#018ff2fc-8d73-4f4d-8137-d6aa7a9e4a65

I've now tried to temporarily remove Aru's commit that upgrades Hugo to see if that is the reason or my commit.

**Comment by ggevay** [comment]
"Lint docs" now passed: https://buildkite.com/materialize/test/builds/83403#018ff300-cc6b-47b9-91bf-af9b01e0c43b
So it seems to be @arusahni's commit from [that I cherry-picked earlier](https://github.com/MaterializeInc/materialize/pull/27325#issuecomment-2143947620) which failed the linting. I guess that could be worked on in a separate PR, independently from this one.

**Comment by arusahni** [comment]
My recollection of that PR is coming back. The Hugo upgrade brings about a change in how they render URLs. Marta and I chatted about this and decided we probably should go for [the workaround described here](https://github.com/MaterializeInc/materialize/pull/26222#issuecomment-2015935088) as the cross reference syntax isn't desirable for our docs.

**Comment by morsapaes** [comment]
I think there was a mistake when merging the `RETAIN HISTORY` documentation, because this should use a generic diagram for `WITH` options which doesn't spell out the options you can use in the diagram itself, but just points out the generic syntax:

Screenshot 2024-06-18 at 03 18 29

The options are then laid out in the respective configuration option table:

Screenshot 2024-06-18 at 03 21 11

We should also include examples for each configuration option since these diagrams are impossible to read, anyway. 

<hr>

I'll push up a fix. Pinged @chaas because this is an issue in a lot of reference pages, and we should patch it more generally.

**Review by morsapaes — APPROVED** [review]

**Comment by ggevay** [comment]
Ok, this makes a lot of sense! Thank you!

**Comment by ggevay** [comment]
Btw. are the simplifications compared to the generic WITH option diagram from your above comment intentional? There is only `WITH with_options` on the diagram now, which doesn't show the parenthesis from the `WITH (...)` and doesn't show that there should be a comma between the options.

**Pull request merged**
