### PR TITLE
persist: exempt strings that look like ISO8601 timestamps from trimming

### PR DESCRIPTION
**Pull request by danhhz**
This fixes a bug that Chuck and Paul were hitting where a string timestamp column with a lower of "2023-08-19T12:00:00.000Z" and an upper of "2023-08-20T12:00:00.000Z" was getting truncated to "2023-08-" and "2023-08." by trimming.

### Motivation

  * This PR fixes a previously unreported bug.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by pH14 — APPROVED** [review]
Ooh lovely surgical change here. This change LGTM with one open question -- do we want to force keep stats around for anything that parses as iso8601? 

I almost wonder if that could replace our force-keep-stats logic... just always keep stats for timestamp typed columns and strings that parse as iso8601 since those are what we support for any useful amount of pushdown today

**Comment by danhhz** [comment]
I think I'd like to leave force keep around and as-is, if possible. We still would have the issue of a table with 1000 string columns, all of which are filled with timestamp-looking strings. As of the current state of this PR, the first pass of trimming would keep them all, and then the second one would keep only the force-keep ones (up to the budget).

(Also, we'd have to replace the recursive force-keep support with this string timestamp sniffing, which would decently increase the scope of this PR.)

**Review by bkirwi — APPROVED** [review]
Nice! And yeah... since part of the reason we like this change is that it's pretty low impact, agree it's worth leaving the force-keep changes out of scope for now.

**Comment by danhhz** [comment]
```'stats::tests::primitive_cost_trim_proptest' panicked at 'byte index 4 is not a char boundary; it is inside '᪫' (bytes 2..5) of `$`᪫ೞ𓑀꫞\ౙઁ3 `', src/persist-types/src/timestamp.rs:41:9```

:sad-trombone:

**Comment by danhhz** [comment]
Okay was an easy fix. TFTRs!!

**Pull request merged**
