### PR TITLE
alloc: add force-jemalloc-macos feature

### PR DESCRIPTION
**Pull request by guswynn**
Some experiments I am doing would be easier if I could turn on jemalloc stats on macos. Heap profiling doesn't work, but it appears relatively stable.

@benesch unfortunately I couldn't figure out a way to not build `tikv-jemallocator` if `force-jemalloc-macos` is off. I don't think you can AND `feature` and `platform`'s in `target.cfg()` clauses, so the cost of this is macos users have to build `tikv-jemallocator` once. One way around this is turning off `jemalloc` by default in `bin/environmentd` and adding `--features jemalloc` for `linux` users, but that seemed not worth it, because it would also mean we'd have to explicitly enable it everywhere else we build materialize.

context: https://materializeinc.slack.com/archives/C0246GEHL8N/p1715300698582579

### Motivation

  * This PR adds a known-desirable feature.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by ParkMyCar — APPROVED** [review]
To fix the problem of building `tikv_jemallocator` on macOS could you do `[target.'cfg(...)`.features]`? e.g. something like:

```
[target.'cfg(not(target_os = "macos"))'.features]
default = ["jemalloc", "workspace-hack"]
jemalloc = ["tikv-jemallocator", "mz-prof/jemalloc", "mz-prof-http/jemalloc"]

[target.'cfg(target_os = "macos")'.features]
default = ["workspace-hack"]
jemalloc = ["tikv-jemallocator"]
```

approving to clear the block if its needed!

**Comment by benesch** [comment]
Let me ponder this one today. I'd love to find a way to do this that doesn't require introducing another Cargo feature. (Although I know Cargo makes that hard with its lack of support for target-specific features.)

**Comment by guswynn** [comment]
@benesch yes I'll wait! I couldn't come up with anything, but let me know!

@ParkMyCar I don't think cargo allows that!

**Comment by benesch** [comment]
I put up https://github.com/MaterializeInc/materialize/pull/27067, which should address the issues here! AFAICT, it makes `--features=jemalloc` Just Work on macOS, while also ensuring that you never have to build jemalloc on any platform if jemalloc is disabled, either implicitly or explicitly.

**Comment by guswynn** [comment]
@benesch your replacement pr looks good!

**Pull request closed without merging**
