### PR TITLE
persist-client: fix race in sink peak metrics update

### LINKED ISSUE #27302: Negative aggregate length for persist sink correction
Sentry Issue: [DATABASE-BACKEND-3EB](https://materializeinc.sentry.io/issues/5410975934/?referrer=github_integration)

```
Negative aggregate length for persist sink correction
```

### PR DESCRIPTION
**Pull request by teskje**
The `SinkMetrics::update_sink_correction_peak_metrics` method assumed "quiescence", i.e. the temporary ceasing of updates to sink metrics while it was executing. While the method was correct under that assumption, the calling code unfortunately was not able to uphold it. Specifically, `step_or_park` is invoked per worker, so when `update_sink_correction_peak_metrics` is invoked it can only assume that the current worker won't update the sink metrics, but it cannot assume anything about other workers.

As a result of the violated assumption, "Negative aggregate length for persist sink correction" could be logged even when nothing was actually wrong with the persist sink implementation.

Stopping all workers at the same time regularly to update the sink metrics is not an option, so instead of trying to make the calling code uphold the quiescence assumption, this PR instead modifies `update_sink_correction_peak_metrics` to not require quiescence anymore. In essence this just removes the error logging, but the code is also restructured to improve readability.

### Motivation

  * This PR fixes a recognized bug.

Fixes #27302 

### Tips for reviewer

This is the simplest fix, but there might be smarter ones. We could, for example, try to make the calculated peak values more correct, or we could attempt to get rid of `update_sink_correction_peak_metrics` entirely and instead perform the update as part of `report_correction_update_deltas`. Both of these options would require more synchronization between workers and I don't have a good intuition for how that would affect `persist_sink` performance.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - N/A

### CODE REVIEW

**Review by bkirwi — COMMENTED** [review]
This looks good to me! However, I would also consider:
- I'd consider using `saturating_sub` instead of `checked_sub`. You've already accepted a possibly-slightly-inaccurate metric, and that will make the output easier to manipulate with promql.
- I'd consider getting rid of this machinery entirely, and either reporting the gauge directly when the deltas are reported or doing the math in promql. IIUC, the main appeal of doing it this way was the assumption of quiescence that we no longer make.
- I'd consider hauling these metrics out of persist client, in the case that there's somewhere else to put them, just for code-ownership reasons. (Though this isn't a big deal in case you don't have anywhere else to stash metrics handy.)

**Comment by teskje** [comment]
> using saturating_sub instead of checked_sub. You've already accepted a possibly-slightly-inaccurate metric, and that will make the output easier to manipulate with promql.

That seems reasonable!

> getting rid of this machinery entirely, and either reporting the gauge directly when the deltas are reported (as you mention) or doing the math in promql. IIUC, the main appeal of doing it this way was the assumption of quiescence that we no longer make.

Doing the math in Grafana has the defect that we won't be able to observe short-lived peaks, due to the sampling interval, similar to how the memory-usage metric doesn't tell us about the actual peak memory usage. The current way still loses super-shortlived peaks, but that's an improvement. So I think updating the peak metrics with the deltas is the way to go.

> hauling these metrics out of persist client, in the case that there's somewhere else to put them, just for code-ownership reasons. (Though this isn't a big deal in case you don't have anywhere else to stash metrics handy.)

Having the correction metrics defined in the persist crate always felt a bit off to me, but I don't know the rationale for putting them there in the first place. Perhaps @danhhz remembers?

**Comment by teskje** [comment]
> using `saturating_sub` instead of `checked_sub`. You've already accepted a possibly-slightly-inaccurate metric, and that will make the output easier to manipulate with promql.

Actually, come to think of it, how does this make any difference for promql? Whether we use `saturating_sub` or `checked_sub`, the result will be that the respective peak value will not be increased if the subtraction fails/saturates. The difference won't be user-visible, right?

**Review by antiguru — APPROVED** [review]
Looks good, but I think we should consider removing this metric entirely, or plan on doing it! I'm not worried about replacing it by something that misses short-lived spikes, because for the arrangement size logging has exactly the same issue in the end. It logs fine-grained size updates, but we certainly consolidate them the moment we first use them.

**Comment by danhhz** [comment]
> > hauling these metrics out of persist client, in the case that there's somewhere else to put them, just for code-ownership reasons. (Though this isn't a big deal in case you don't have anywhere else to stash metrics handy.)
> 
> Having the correction metrics defined in the persist crate always felt a bit off to me, but I don't know the rationale for putting them there in the first place. Perhaps @danhhz remembers?

I don't recall specifically, but my guess would be that we had the plumbing in place or something. Certainly no objection from me on moving them out.

**Comment by bkirwi** [comment]
> Actually, come to think of it, how does this make any difference for promql?

You're absolutely right - my mistake.

**Comment by teskje** [comment]
Closing in favor of #27341.

**Pull request closed without merging**
