### PR TITLE
ci: enable cluster_always_use_disk

### PR DESCRIPTION
**Pull request by nrainer-materialize**
Nightly: https://buildkite.com/materialize/nightlies/builds/5986

### CODE REVIEW

**Review by def- — COMMENTED** [review]
Your 3 PRs adding flags will all conflict and might not work in combination. I would suggest to do it one PR instead.

**Comment by nrainer-materialize** [comment]
> Your 3 PRs adding flags will all conflict and might not work in combination. I would suggest to do it one PR instead.

I know, I had planned to merge them once I have the build result.

**Comment by nrainer-materialize** [comment]
@def- (CC @antiguru): When setting param `cluster_always_use_disk` to `true` in 68abba67e23ef68cd1c04f0d0b7e65052afb083c, `test_disk_label` [will fail:](https://buildkite.com/materialize/tests/builds/73051#018d0c4e-2d71-474f-9b28-3cdde8fefa70)

```
assert '\'{"material...sk":"true"}\'' == '\'{"material...k":"false"}\''
  - '{"materialize.cloud/disk":"false"} {"materialize.cloud/disk":"false"}'
  ?                             ^^^^                               ^^^^
  + '{"materialize.cloud/disk":"true"} {"materialize.cloud/disk":"true"}'
  ?                             ^^^                               ^^^
```

Do we have a problem here that `DISK = {value}` of `"CREATE CLUSTER disk_{value} MANAGED, SIZE = '2-1', DISK = {value}"` does not override the disk-value's system parameter?

**Comment by antiguru** [comment]
(on mobile) it's not supposed to override the system-level parameter. The system-level has higher priority.

**Comment by def-** [comment]
Seems to me like an explicit `DISK = ...` in a `CREATE CLUSTER` should take priority.

**Comment by antiguru** [comment]
The context is that we'd like to remove the disk keyword and move the configuration entirely out of the user's hand eventually.

**Review by philip-stoev — APPROVED** [review]

**Comment by nrainer-materialize** [comment]
> The context is that we'd like to remove the disk keyword and move the configuration entirely out of the user's hand eventually.

Ok, got it.

**Pull request merged**
