### PR TITLE
sql: move unary operators to general framework

### PR DESCRIPTION
**Pull request by benesch**
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/3348)

### CODE REVIEW

**Comment by sploiselle** [comment]
@benesch Sure you don't need any help but I wanted to see what was up with your test failures and it looks like we have the same behavior as PG, where this is invalid:

```
CREATE TABLE tab1(pk INTEGER PRIMARY KEY, col0 INTEGER, col1 FLOAT, col2 TEXT, col3 INTEGER, col4 FLOAT, col5 TEXT);
SELECT + col2 FROM tab1 WHERE NOT ( NULL ) = NULL;
```
```
ERROR:  operator does not exist: + text
LINE 1: SELECT + col2 FROM tab1 WHERE NOT ( NULL ) = NULL;
               ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

However, this just returns `NULL` in `sqlite`.

**Comment by benesch** [comment]
Blergh, I forgot how crazy the unary plus operator is. I guess we should just stick with our current overloads. Fix incoming.

**Comment by benesch** [comment]
@sploiselle I got this working (locally at least) with the addition of a `ParamType::Any` that is like `ParamType::StringAny` but doesn't attempt to cast to any type at all. WDYT?

**Comment by sploiselle** [comment]
@benesch Yeah––that's definitely a good idea; we are just using special-cases of that [general pseudotype](https://www.postgresql.org/docs/12/datatype-pseudo.html). I believe the new logic lets you avoid casting `ParamType` to `ScalarType` for pseudotypes, as well, but that might require a little bit of dancing.

**Comment by benesch** [comment]
> I believe the new logic lets you avoid casting ParamType to ScalarType for pseudotypes, as well, but that might require a little bit of dancing.

I agree with you in principle but I'm not sure what you have in mind in particular! Do you want to take this over, or point me in a more specific direction?

**Comment by sploiselle** [comment]
Sorry for the oversight in my previous comment and commits; I hadn't realized that `From<&ParamType> for ScalarType` had been deprecated, but it looks like you figured that out. This looks great!

**Comment by benesch** [comment]
Oh, no worries at all! The way `ScalarType::Any` causes early returns in the coercion pipeline is a little weird, so definitely feel free to clean up if you have ideas! Will merge for now.

**Pull request merged**
