### PR TITLE
persist: add temporary workaround for persisted table compaction bug

### PR DESCRIPTION
**Pull request by danhhz**
When since_updates got split into index_since_updates and
source_since_updates, it looks like the ones persist was looking for
ended up in index_since_updates (the wrong one). This means the
compaction frontier for persisted tables never advances. Since we run a
background test of persist on two system tables, this means unbounded
storage (disk) usage, which is very much not correct. Putting this call
to persist back in as a workaround while we fix the bug the proper way,
which is making sure the messages end up in source_since_updates
instead.

Touches #10300

### CODE REVIEW

**Review by ruchirK — COMMENTED** [review]
this makes sense and LGTM!

**Review by ruchirK — APPROVED** [review]

**Comment by danhhz** [comment]
TFTR! gonna merge this now to unbreak main while we figure out how to do the real fix

**Comment by aljoscha** [comment]
Sorry for the inconvenience!

I think Ruchirs work on fixing how sources report their upper might help fix this. The problem is that table "sources" are not treated like real source by most of the system, but if they report an upper like all other sources and reacted to "allow compaction" messages that could allow us to get rid of the special table-index trickery we have in coord right now.

((I'm sure you have similarly helpful ideas from your quick brainstorm already... :sweat_smile:))

**Comment by aljoscha** [comment]
> Nope! Can you think of anything better than this for between now and when we have proper frontier reporting?

I'm afraid not, the fix basically restores the previous behaviour, by making sure the compaction message goes to the right structure.

**Pull request merged**
