### PR TITLE
doc/user: add documentation for source sizes

### PR DESCRIPTION
**Pull request by benesch**
### Motivation

* This PR adds missing documentation for a feature.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-protobuf` label.
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - n/a

### CODE REVIEW

**Review by morsapaes — APPROVED** [review]
Thanks again for helping out with documentation, @benesch! Pushed a few more changes to make sure we don't end up with loose ends.

**Comment by morsapaes** [comment]
Ah, one thing I forgot to mention: do we have a rough estimation of the throughput each source size is able to handle, or CPU/memory specs for each size? I imagine it's hard for users to understand which size to choose without any reference information.

**Comment by benesch** [comment]
> Ah, one thing I forgot to mention: do we have a rough estimation of the throughput each source size is able to handle, or CPU/memory specs for each size? I imagine it's hard for users to understand which size to choose without any reference information.

We do not! Somewhat by design, too, since we want to avoid making particular promises about throughput, or even about how _much_ CPU/memory a given size corresponds to. This all comes from @rjnn, by the way. I’d be curious to dig more into what sort of guidance Snowflake gives for warehouse sizing. From what I’ve seen it’s similarly vague.

The big missing piece here is the ability to easily assess CPU, memory, and ingest rate for sources. We need to get a design and implementation for that wired up stat. Not giving guidance around which source size to pick is much more palatable if we can at least tell users “go measure it on your workload and pick the size that suits.” Right now that measurement is quite difficult.

**Comment by benesch** [comment]
Thanks very much for the improvements! Merging.

**Pull request merged**
