### PR TITLE
limits test: Expand the size of the Mz instance tested

### PR DESCRIPTION
**Pull request by def-**
@philip-stoev Maybe I'm missing something, but I think it works in CI like this. Proof: https://buildkite.com/materialize/nightlies/builds/2522#01887e74-c125-46a7-b61b-abd141879005 & https://buildkite.com/materialize/nightlies/builds/2524

Description taken from https://github.com/MaterializeInc/materialize/pull/19665:

With PubSub enabled, CRDB is no longer the limiting factor, so it is possible to expand the instance-size workflow in various dimensions.

At the same time, we are reducing the number of replicas to 3 per cluster. This will match reality closer in the sense that users are expected to have two replicas for failover as well as posssibly an occasional third replica during maintenance operations such as scale-up or scale-down of the compute instance type.

### Motivation

This is needed to test the operation of PubSub at scale.

### CODE REVIEW

**Review by philip-stoev — APPROVED** [review]
Thank you so much! I was thinking that we are hitting some host-wide limits, not per-container ones. I am happy it worked.

**Comment by philip-stoev** [comment]
Wait, the Nightly job is called instance-size, let me run it first.

**Comment by philip-stoev** [comment]
No dice unfortunately, I think the Confluent stack is having issues:

```
limits-zookeeper-1        | EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /127.0.0.1:38130, session = 0x0
```
and many others.

**Review by nrainer-materialize — APPROVED** [review]

**Comment by def-** [comment]
Too bad, then I was too naive.

**Pull request closed without merging**
