### PR TITLE
Use new buildkite pipeline names

### PR DESCRIPTION
**Pull request by def-**
See https://github.com/MaterializeInc/materialize/pull/26502 for context

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by nrainer-materialize — APPROVED** [review]

**Comment by def-** [comment]
I just noticed this can't work yet since Github still waits for `buildkite/tests` instead of `buildkite/test`. I'll try to find where that is configured, but probably I can't change it.

**Comment by def-** [comment]
@benesch I guess you will have permissions to change that in https://github.com/MaterializeInc/materialize/settings (from buildkite/tests to buildkite/test) I renamed the Test pipeline back to Tests for now: https://buildkite.com/materialize/tests/settings/repository

**Comment by benesch** [comment]
Yes, I can work on this as soon as I have a free second at my computer.

**Comment by nrainer-materialize** [comment]
@def-: Rebased for your convenience to resolve conflicts introduced with the merge of https://github.com/MaterializeInc/materialize/pull/26497.

**Review by benesch — APPROVED** [review]

**Pull request merged**
