### PR TITLE
environmentd: remove vestigial default storage host size argument

### PR DESCRIPTION
**Pull request by benesch**
This argument dates from the times before cluster unification. It is no longer used.

Touches MaterializeInc/cloud#5344.

### Motivation

   * This PR removes dead code.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - n/a

### CODE REVIEW

**Review by jkosh44 — APPROVED** [review]
LGTM

**Comment by jkosh44** [comment]
I kicked off a Nightly build: https://buildkite.com/materialize/nightly/builds/8127 just in case. I've found that these types of PRs sometimes accidentally break certain upgrade tests.

**Comment by benesch** [comment]
Sweet, thanks! Optimistically merging while CI is green, but I'll circle back on the nightly job this evening and clean up any failures that may have resulted.

**Comment by benesch** [comment]
Checked nightlies. None of the failures seem related to this PR! 🎉

**Pull request merged**
