### PR TITLE
Document `ASSERT NOT NULL`

### PR DESCRIPTION
**Pull request by umanwizard**
Does what it says on the tin!

### CODE REVIEW

**Review by benesch — APPROVED** [review]
Gorgeous. Thank you!

**Comment by umanwizard** [comment]
Just realized I need to call out that this is in preview 🤦🏻‍♂️ will fix later tonight or early tomorrow.

**Comment by benesch** [comment]
> will fix later tonight or early tomorrow.

I fixed for ya and set to auto merge.

**Comment by benesch** [comment]
Oh, also, I added an example. If you have a second, please double check it!

**Comment by umanwizard** [comment]
Excellent, thank you! Example looks good.

**Pull request merged**
