### PR TITLE
Refuse to set statistics.interval.ms on RT timestamping connector

### LINKED ISSUE #6313: Memory leak when collecting stats
For nonzero values of `statistics_interval_ms`, we observe a memory leak of approximately 10 KB per kafka consumer per statistics interval.

The memory is allocated here: https://github.com/edenhill/librdkafka/blob/1a722553638bba85dbda5050455f7b9a5ef302de/src/rdkafka.c#L1606

We still aren't sure why it's never being freed.

### PR DESCRIPTION
**Pull request by umanwizard**
Previously, when we asked for statistics on a Kafka source, we were passing through that config option to the RT timestamp consumer as well, causing Kafka to generate messages which were never drained. This was causing about 10 KB in leaked memory per statistics tick interval (default 1s).

Fixes #6313

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/6315)

### CODE REVIEW

**Review by elindsey — APPROVED** [review]
Nice find!

**Comment by benesch** [comment]
Whoop, agree, nice find! I'm not sure I'm entirely sold on this fix though. So the issue is that nothing is calling `poll` on this consumer, right? That seems like it leaves the door open to other random librdkafka callbacks filling up the queue, no?

**Comment by benesch** [comment]
I guess what I'm saying is it feels like maybe we want to do this _and_ periodically poll the consumer?

**Comment by benesch** [comment]
Specifically I'm worried that log messages might pile up too. Do those go into the same queue? I feel like they would but I don't have the time to check right now.

**Comment by benesch** [comment]
Thirdly, ugh, yet more evidence we should rewrite librdkafka.

**Comment by umanwizard** [comment]
@benesch ack. Do you know if polling once will clear all of these, or if we'd need to poll in a loop?

**Comment by benesch** [comment]
Oh gosh, I'm really not sure. I think polling just once should serve all queued callbacks, but don't take my word for it.

**Comment by elindsey** [comment]
It looks like stats_cb is the only one that can be misconfigured in this way (since it has both a stats interval and stats_cb component) - the two other relevant events (error_cb and throttle_cb) are only generated if a callback is actually registered. But, still much better to poll. 🙂

**Review by elindsey — APPROVED** [review]

**Pull request merged**
