### PR TITLE
ct: fix restart bugs by sharing code

### PR DESCRIPTION
**Pull request by danhhz**
This should be enough to get Dennis's initial tests passing.

On restart, we weren't replacing the MV sink with a CT one. We also
weren't swapping out the LocalId placeholders at the right time in an
upcoming PR to add a builtin CT.

Closes database-issues#8591
Touches database-issues#8427

### Motivation

  * This PR fixes a recognized bug.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

**Comment by danhhz** [comment]
@ParkMyCar I ran out of time to finish cleaning this up today, but it should be far enough to do a quick initial scan if you want.

**Comment by danhhz** [comment]
> This should be enough to get Dennis's initial tests passing.
It is! \o/

**Review by ParkMyCar — APPROVED** [review]
Nice!

**Comment by danhhz** [comment]
TFTR!

**Pull request merged**
