### PR TITLE
dataflow: more verbose errors when creating TAILed sources fails

### PR DESCRIPTION
**Pull request by ruchirK**
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4562)

### CODE REVIEW

**Comment by ruchirK** [comment]
Not totally sure which print formatter I should use for the errors in this case so I went with the most verbose -- @benesch do you have any thoughts?

**Comment by benesch** [comment]
I think `{:#}` is preferable in log messages because it smushes everything onto one line!

**Comment by ruchirK** [comment]
done! I didn't know that thanks :)

**Review by benesch — APPROVED** [review]

**Comment by benesch** [comment]
You bet! They're covered in detail here: https://docs.rs/anyhow/1.0.33/anyhow/struct.Error.html#display-representations

The `{:#?}` is actually particularly ugly because it prints the full struct guts out.

**Pull request merged**
