### PR TITLE
doc(developer): State Python versioning policy

### PR DESCRIPTION
**Pull request by necaris**
This is useful as we have run into a few issues recently with compatibility, and we do not have an explicit policy stated (as we do for Rust).

I expect some commentary and bikeshedding on this so please don't consider it final until a consensus of teams and / or @benesch has approved!

### CODE REVIEW

**Review by umanwizard — CHANGES_REQUESTED** [review]
I'm not in favor of this, as forcing everyone on the DB team to install random third-party tools in order to keep their Python version up to date increases friction with no clear benefit. The PSF's support lifecycle is not relevant, as Ubuntu and other distros have committed to supporting the versions of Python that they ship.

**Comment by umanwizard** [comment]
Discussed in Slack: https://materializeinc.slack.com/archives/C0246GEHL8N/p1698754929610759

**Comment by umanwizard** [comment]
I'd also like to point out that this is the first thing on the "deadsnakes" page (which is listed here as the recommended way for Ubuntu users to install the latest Python versions):

> Disclaimer: there's no guarantee of timely updates in case of security problems or other issues. If you want to use them in a security-or-otherwise-critical environment (say, on a production server), you do so at your own risk.

So, if we adopted this policy, we'd be regressing in terms of support guarantees, as the version of Python in the Ubuntu repos is supported by Ubuntu, and this "deadsnakes" repo is apparently supported by no one.

**Comment by necaris** [comment]
> So, if we adopted this policy, we'd be regressing in terms of support guarantees, as the version of Python in the Ubuntu repos is supported by Ubuntu, and this "deadsnakes" repo is apparently supported by no one.

Do we make support guarantees for tooling installed on developer machines? I don't think we do, and I don't think we should if we did. We do make promises about CI (and Docker), and there we are explicitly using Ubuntu Lunar (which uses Python 3.11, as does Mantic). In the cloud repo, we use Debian Bookworm as the base, which provides the same Python version. 

> increases friction with no clear benefit

I would say there are [clear benefits to the tooling in the DB repo](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/cloudtest.md), and to [consistency with the cloud repo](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20230613_cloudtest_improvements.md). 

I think it's a reasonable alternative to require compatibility with, say, Ubuntu LTS, but we should be explicit about prioritizing compatibility over staying up to date with this toolchain.

**Comment by umanwizard** [comment]
I meant that there is no clear benefit to requiring 3.11 over 3.10, not that there is no clear benefit to using Python in our codebase at all.

**Comment by necaris** [comment]
There are a couple of new features in 3.12 I'm excited about ([typing](https://docs.python.org/3/whatsnew/3.12.html#whatsnew312-pep695) [improvements](https://docs.python.org/3/whatsnew/3.12.html#whatsnew312-pep692)) but we can live without them. Same goes for 3.13 so far, which will also be out before Ubuntu 22.04 is out of LTS. So what is the threshold of benefit to overcome the friction of an updated version? 

I don't have any objection to using Ubuntu LTS as the "minimum supported version" indicator, but why not e.g. Debian Stable? Other than that more Materialize engineers use Ubuntu than any other one distro?

**Comment by RobinClowers** [comment]
I don't really have a horse in this race, but my take is: keeping up to date with the latest versions of our core tools (yes, python is a core tool for the cloud team) is very worthwhile for security and developer experience. Having a separate python version for the materialize repo and the cloud repo would introduce significant friction for the cloud team.

I think it's important that we figure out a good way to install the latest python for linux users, but I'm not sure what the best approach is here. It's unfortunate that there doesn't seem to be a widely supported way to do this. In practice, I think relying on the deadsnakes ppa is probably good enough, though it would be nice to have something more official.

**Comment by benesch** [comment]
> and to [consistency with the cloud repo](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20230613_cloudtest_improvements.md).

> Having a separate python version for the materialize repo and the cloud repo would introduce significant friction for the cloud team.

+1 on consistency with the cloud repo being important. We have enough folks who cross between repos that I think we should aim to use the same Python version in both repos.

> I don't have any objection to using Ubuntu LTS as the "minimum supported version" indicator

I'm also +1 as tracking the most recent Ubuntu LTS's Python version as our minimum supported Python version. 

> keeping up to date with the latest versions of our core tools (yes, python is a core tool for the cloud team) is very worthwhile for security and developer experience.

> I think it's important that we figure out a good way to install the latest python for linux users, but I'm not sure what the best approach is here.

My take is that Python is used relatively equivalently by the database and cloud repositories. It's not used in any production services, but it's used to glue together a lot of production services—test frameworks, IaC definitions, developer scripts, etc. 

Empirically, though, I'm not sure I see the compelling case for keeping up with the latest release of Python. The features in new Python versions that matter to us have mostly been small quality-of-life features, like improvements to `argparse` and the ability to use `|` to more concisely describe union types. None of these features have seemed like game changers; they all seem easy to live without. I think that's generally true for any language you use as a "glue" language. The code isn't on the critical path, and so it doesn't seem urgent to get access to new features immediately. Vs Rust, where the moment `async` hit stable we could immediately simplify a lot of performance/correctness sensitive code. (I imagine there could be a similar effect with TypeScript in the console repository.)

What we _have_ seen is a number of engineers struggle to get Python 3.11 installed. I think Python is substantially worse than Rust in handling multiple versions simultaneously. Rust has a single blessed way of installing multiple Rust toolchains (rustup). Python does not. That effect is exacerbated at Materialize because we're primarily a Rust (and TypeScript) shop, not a Python shop. So it's particularly painful to fight with Python and virtualenv here, because 1) many folks are not that familiar with either of these tools, as it's not their primary development environment, and 2) you're usually running Python code while trying to do something else. It's one thing for Rust to break while you're trying to write Rust; it's much more frustrating when you've gotten your Rust code all written, you need to run some Python script that you're unfamiliar with to test that Rust code, and that Python script breaks.

On security: the PSF provides security fixes for each Python 3 version for five years. Python 3.11 will receive security fixes until mid-late 2027, for example. 

All this to say that I think: 

  1. Tracking the latest Ubuntu LTS Python release is a good balance between getting access to new features and being easy to install on a wide variety of distributions. 
  2. The disparity in policies between Rust and Python is relatively well justified because:
    a. Rust makes it easier to manage multiple versions of Rust toolchains than Python.
    b. Rust is used in more performance and correctness sensitive code where having access to the latest Rust features is more impactful.
  3. I think someday soon we should _also_ consider using older Rust versions, so that we're not the ones to discover Rust toolchain bugs. (I believe @philip-stoev would like this too.)

**Comment by umanwizard** [comment]
Is there a way we could make bin/pyactivate invoke pyenv (or similar) to
download the latest Python version, so that people who deal with Python
regularly can use the latest features, but nobody else will have to think
about managing Python versions? It occurs to me that maybe that would be a
compromise that makes everyone happy.

**Comment by umanwizard** [comment]
BTW, I realized 3.11 _is_ available in Ubuntu 22.04. It's just not installed by default, and the package is called `python3.11`, rather than `python3`. So we should probably specify whether we mean the Ubuntu LTS's default Python release, or any release available in the official repos. I'd be totally fine with the latter, so I retract my objection to using python 3.11 specifically. However, that's not the main point of this discussion (which is about what we will do w.r.t. 3.12, 3.13, and so on).

**Comment by necaris** [comment]
> Tracking the latest Ubuntu LTS Python release is a good balance between getting access to new features and being easy to install on a wide variety of distributions.

Updated the PR to say this! Thank you @benesch for articulating the policy so clearly!

**Review by arusahni — APPROVED** [review]
Thanks for pushing this forward.

**Review by benesch — APPROVED** [review]
This sounds good to me. Thanks!

**Pull request merged**
