### PR TITLE
tests: bounded memory: add MySql scenarios

### PR DESCRIPTION
**Pull request by nrainer-materialize**
Nightly: https://buildkite.com/materialize/nightlies/builds?branch=nrainer-materialize%3Atests%2Fbounded-memory-w-mysql

### CODE REVIEW

**Review by def- — COMMENTED** [review]
How close to the memory limit is this running currently?

**Comment by nrainer-materialize** [comment]
> How close to the memory limit is this running currently?

Still tuning the values right now; looks as if I can significantly decrease them.

**Comment by nrainer-materialize** [comment]
I also ported the new scenario from https://github.com/MaterializeInc/materialize/pull/26287.

**Comment by nrainer-materialize** [comment]
> How close to the memory limit is this running currently?

I will adjust all memory limits with https://github.com/MaterializeInc/materialize/pull/26312.

**Review by def- — APPROVED** [review]

**Comment by nrainer-materialize** [comment]
Scenario `mysql-cdc-large-tx` will be helpful for https://github.com/MaterializeInc/materialize/pull/26276.

**Comment by nrainer-materialize** [comment]
Hey @rjobanp,

I have trouble getting the new scenario `mysql-cdc-large-tx` to pass. I reduced the volume and increased clusterd memory to 8 Gb (though, not sure if all of that memory can be provided). It still failed in [builds/7198](https://buildkite.com/materialize/nightlies/builds/7198); therefore, I further reduced the volume. Do we have an issue here?

See also the discussion about the same workload in Postgres: https://github.com/MaterializeInc/materialize/pull/26267#issuecomment-2034550913

**Comment by rjobanp** [comment]
@nrainer-materialize yes it's possible that we have an issue with large transactions OOMing the storage cluster. Would you be able to run the same test on https://github.com/MaterializeInc/materialize/pull/26382 to see if it resolves?

**Comment by nrainer-materialize** [comment]
> @nrainer-materialize yes it's possible that we have an issue with large transactions OOMing the storage cluster. Would you be able to run the same test on #26382 to see if it resolves?

Sure!

**Comment by nrainer-materialize** [comment]
I will anyway land this PR now and disable the problematic scenario for now.

**Pull request merged**
