### PR TITLE
Stabilize pubnub sources

### PR DESCRIPTION
**Pull request by petrosagg**
This PR switches PubNub sources to use the implement `SourceReader` trait and behave for all intents and purposes similar to a File source and also removes it from the experimental state.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/6258)

### CODE REVIEW

**Comment by ruchirK** [comment]
IMO, you don't need to switch this over to `SourceReader`. `SimpleSource` is fine, and I don't think the concern was tied to "which timestamp inventing interface we are using".

I think the concern was more "different views built on PubNub sources will have really different data, and PubNub data won't be durable across restarts and we don't have a great way to tell that to other components (coordinator and sinks) primarily." 

I also think the response of "yeah, but thats how tables / kinesis / etc" work today is also fair. So, IMO, making this non-experimental should not be tied to `SourceReader` vs `SimpleSource`.

There's separate questions of:

- does the Cloud product need a non-experimental release or is the experimental version fine for now?
- Is there anything we can do to mitigate some of the nondeterminism across different PubNub source instances? The easiest thing I can think of is to force each PubNub source to be materialized. Idk how much of a user pain point that would be but its pretty easy for us to implement.

I can't think of anything else we can do in the short term. IMO, we should go ahead and make it non-experimental, without switching to `SourceReader`

**Comment by ruchirK** [comment]
I'm going to go ahead and mark this as "changes requested" to avoid triggering the review bot

**Review by ruchirK — CHANGES_REQUESTED** [review]
the comment earlier explains my position on this (github required an additional comment so this is a no-op)

**Comment by umanwizard** [comment]
@petrosagg can we mark this as draft until there is a consensus on this?

**Comment by petrosagg** [comment]
@umanwizard I'll go ahead and close this PR as I don't think it changes anything regarding the nature of the source itself

**Pull request closed without merging**
