### PR TITLE
persist: replace should_fetch_part semantics with should_filter_part

### PR DESCRIPTION
**Pull request by danhhz**
The semantics of should_fetch_part require it to turn "I don't know" into "true", which in practice has seemed to be a touch confusing. This was confirmed in the code review for #22838 where Joe encountered pushdown for the first time. Instead, flip the semantics to should_filter_part, where "I don't know" (e.g. a `None`) gets mapped to "false, which we hope will be easier to reason about when reading code.

### Motivation

   * This PR refactors existing code.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by danhhz** [comment]
@bkirwi Friendly ping! :)

**Comment by jkosh44** [comment]
> But overall I suspect `Option<bool>` may just be an insufficiently communicative type and we need something like `enum Matches { Yes, Maybe, No }` and `impl Matches { fn might_match(&self) -> bool {...} }`

FWIW, I think this would be a good idea.

**Comment by danhhz** [comment]
Hmm, it appears I'm in the minority on this, but I'm not a fan of the enum here.

I'm usually the first to jump on the enum train, but the genesis of this conversation was that I added a method that could return an `Option` to make it convenient to do the early returns for `None` instead of mapping them all to `true` or `false`. Without something like a stabilized [Try](https://doc.rust-lang.org/std/ops/trait.Try.html) trait to make it easy to early return the enum, it loses that advantage and I think the extra verbosity would cloud more than it would clarify compared to a `-> bool` signature.

That said, I might be missing something, but this all feels a bit marginal to me? I have an inclination here for either accepting this PR as-is or closing it and sticking with what we have on main.

**Comment by jkosh44** [comment]
> That said, I might be missing something, but this all feels a bit marginal to me? I have an inclination here for either accepting this PR as-is or closing it and sticking with what we have on main.

FWIW, I don't really have a strong opinion on this and would be fine with any outcome.

**Comment by danhhz** [comment]
Given that I missed a couple spots in my first version of this (the tests caught them, but still it increases my mental model of the riskiness) and that no one seems to be a strong proponent and that Ben seems to be a mild opponent, I'm going to go ahead and close this. TFTRs!

**Pull request closed without merging**
