### PR TITLE
catalog: export catalog item and compute instance names in prometheus

### PR DESCRIPTION
**Pull request by danhhz**
This allow us to display the internal id -> external name mapping in grafana, which makes debugging much easier.

Looks roughly like this

image

### Motivation

  * This PR adds a feature that has not yet been specified.

### Tips for reviewer

Marking as draft because there's a lot to figure out here.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Comment by danhhz** [comment]
Before I spend any time on this, wanted to gut check the basic idea. It's a pretty gross abuse of prometheus labels. We'll also have to be careful to propagate any naming changes to this label (ideally we could use something like a computed gauge, but as far as I know that's only for the gauge's _value_ not it's _labels_). Also, I had to format both the internal id and external name into a string, I couldn't figure out a way to keep any sort of structure there. Finally, grafana seems really hesitant to be in the business of displaying a set of labels. The official answer is a "Stat" panel with only "Name" selected, which is how I got the included screenshot, but there's not a lot of customizability (e.g. I couldn't figure out how to left justify the text, or make it a reasonable size).

**Comment by guswynn** [comment]
@danhhz i agree; its important we think about this!

I think the important thing is that this information is accessible without envd needing to be functioning, and ideally, without needing to use a tool like stash-debug. This is for convenience, but also to avoid dependencies during debugging. One of the reasons I originally suggested tagging each metrics with the name AND the id was its simplicity in comparison to needing to look up the mapping, and the fact that it luckily didnt increase the cardinality of those time series, so its unclear to me what tradeoff we want here

**Comment by benesch** [comment]
So full disclosure: we used to have something kinda like this (Prometheus metrics representing the catalog state), and I removed them (https://github.com/materializeInc/materialize/commit/d41f4ee47e0b26e7de8838e233c701dbe136145b#diff-d0183529f9b3f7d0a8a556c05ec90e95bf1610cdde02a819a9bb813860fd1d58) because they were really error-prone to keep up to date. We're already keeping three copies of the catalog state (on disk in the stash, in memory in the `Catalog`, and in the persist tables backing the user-facing catalog tables), and having to keep yet _another_ copy of the catalog state up to date as Prometheus metrics was exhausting.

That said, this (ab)use of Prometheus does seem potentially quite useful! We've been trying to run these sorts of metrics through the Prometheus SQL exporter in the cloud repository though. I think it'd be something like this:

```yml
- metric_name: mz_catalog_items
  type: gauge
  help: "mapping between internal id and external name for catalog item"
  key_labels: [label]
  values: [value]
  query: |
    SELECT
        concat(d.name, '.', s.name, '.', o.name, ': ', o.id) AS label,
        0 AS value,
    FROM mz_objects o
    JOIN mz_schemas s ON (o.schema_id = s.id)
    JOIN mz_databases d ON (s.database_id = d.id)
    WHERE o.id LIKE 'u%';
```

Big benefit is that you don't need to do anything more to keep the metrics up to date as objects get renamed or dropped.

**Comment by benesch** [comment]
> I think the important thing is that this information is accessible without envd needing to be functioning

Maybe a surprising take, but I don't think this is all that important! If `environmentd` is down, the absolute top priority is bringing `environmentd` back online, because _nothing_ works for the end user until you do! I think it is totally fine if you lose some observability into the rest of the system until you bring `environmentd` back online.

> One of the reasons I originally suggested tagging each metrics with the name AND the id was its simplicity in comparison to needing to look up the mapping, and the fact that it luckily didnt increase the cardinality of those time series, so its unclear to me what tradeoff we want here

IIUC, putting the name of the object in the metric's labels means that it'll present as a different time series if/when the object name changes? And how do you e.g. tell `storaged` when the name of the source has changed? Adding a `SQLLayerNameChanged` message to the storage protocol just to support Prometheus metrics would be a real bummer! 

What I want to avoid is adding a large amount of complexity to our code in order to facilitate a particular visualization in Grafana/Prometheus. It seems to me that the "pure" approach here—though I understand that the realities of Prometheus + Grafana may make this hard—is to always key metrics on the ID, and then perform a label value mapping _in Grafana_ that attaches human readable names to the metrics based on their IDs. That gets you exactly the behavior that you want: a metric whose identity is stable over time, but labeled with the _current_ SQL name for that metric. And all without complicating our code at all. The storage and compute layers could continue to be entirely oblivious to SQL names.

**Comment by danhhz** [comment]
> We've been trying to run these sorts of metrics through the Prometheus SQL exporter in the cloud repository though.

Ah yeah, that's much better! I'll go ahead and close this PR.

> One of the reasons I originally suggested tagging each metrics with the name AND the id

Apologies, I missed where you said that! That's indeed cleaner than the awful hack I had typed up here. :)

> and then perform a label value mapping in Grafana that attaches human readable names to the metrics based on their IDs

I did a quick search on grafana docs and didn't see a way to specify a label value mapping powered by a prom query, only ways to manually specify it. Am I missing something?

**Comment by guswynn** [comment]
> because nothing works for the end user until you do! I think it is totally fine if you lose some observability into the rest of the system until you bring environmentd back online.

This scares me because in general, you may need some of this info to be able to bring envd back up. But thats a general problem, in this case, the promsql exporter will ensure prometheus holds the historical data you may need to debug stuff, so that solution seems like a reasonable path forward?

**Comment by guswynn** [comment]
Or, we can go with tagging the metrics themselves with the names, but that will be much more soup code to add to materialize than just adding a promsql exporter metric

**Comment by benesch** [comment]
Filed https://github.com/MaterializeInc/cloud/issues/4521 to track moving this into the Prometheus SQL exporter.

**Comment by benesch** [comment]
> But thats a general problem, in this case, the promsql exporter will ensure prometheus holds the historical data you may need to debug stuff, so that solution seems like a reasonable path forward?

Right!

**Pull request closed without merging**
