### PR TITLE
storage: Batch table drops

### LINKED ISSUE #24963: sentry: panic: cannot fail to apply appends: InvalidUppers([System(446)])
Sentry Issue: [DATABASE-BACKEND-39B](https://materializeinc.sentry.io/issues/4942492039/?referrer=github_integration)

```
panic: cannot fail to apply appends: InvalidUppers([System(446)])
  File "panicking.rs", line 597, in rust_begin_unwind
  File "appends.rs", line 376, in mz_adapter::coord::Coordinator::group_commit_initiate::{closure#0}::{closure#0}::{closure#6}
  File "instrument.rs", line 272, in tracing::instrument::Instrumented<T>::poll
  File "instrument.rs", line 272, in tracing::instrument::Instrumented<T>::poll
  File "core.rs", line 334, in tokio::runtime::task::core::Core<T>::poll::{closure#0}
...
(63 additional frame(s) were not displayed)
```

ci-regexp: cannot fail to apply appends: InvalidUppers

### PR DESCRIPTION
**Pull request by jkosh44**
This commit is a followup to 3b73672dfb37ea8a35e057912f3b81fb9f97ed7e
which takes advantage of the batch table drop API to batch all table
drops into a single call.

Works towards resolving #25962
Resolves #24963

### Motivation
This PR fixes a recognized bug.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [X] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [X] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - There are no user-facing behavior changes.

### CODE REVIEW

**Comment by jkosh44** [comment]
I ended up doing a lot more copy and pasting than I wanted here because I don't know enough about this code and didn't understand some of the comments. Please give any suggestions if you have them.

**Comment by jkosh44** [comment]
@MaterializeInc/testing Can you check the Nightlies failures and see if anything is concerning? (https://buildkite.com/materialize/nightlies/builds/6933)

Also @def- I made a [new branch](https://github.com/MaterializeInc/materialize/pull/26068) that rebases [your branch](https://github.com/MaterializeInc/materialize/pull/25798). I ran the product [limit nightly test](https://buildkite.com/materialize/nightlies/builds/6932#_) and it passed. So it looks like this resolves https://github.com/MaterializeInc/materialize/issues/24963.

**Review by def- — APPROVED** [review]
Thanks!

The nightly is concerning in the sense that it has a panic, unfortunately the coredump is empty, but I guess this is https://github.com/MaterializeInc/materialize/issues/24644, but will improve the tooling.

**Comment by jkosh44** [comment]
Nightlies passed after a retry.

**Review by petrosagg — COMMENTED** [review]
I have two concerns with this PR:

First, it leaves the code in a state that it is not obvious that doing this in batch is such a load bearing property. What prevents someone from refactoring it the other way in the future?

Second, how do we prevent a user script from running a bunch of drops manually in quick succession and hitting the same issue? I feel like the solution to #25962 should cover that case too and if that was the case then I would expect we wouldn't need this PR. Am I missing something?

**Comment by jkosh44** [comment]
> Second, how do we prevent a user script from running a bunch of drops manually in quick succession and hitting the same issue? 

Each drop command corresponds to a single update to some builtin table, each update requires a new timestamp from the timestamp oracle. So `n` drop commands will increase the timestamp oracle by at least `n`. On the persist txn side the `n` drops will correspond to `n` calls to `forget` and increase the txn shard upper by exactly `n`. So it's not possible for the txn shard upper to go past the timestamp oracle which makes it not possible to hit this issue.

> I feel like the solution to https://github.com/MaterializeInc/materialize/issues/25962 should cover that case too and if that was the case then I would expect we wouldn't need this PR. Am I missing something?

I do think that my explanation above is a bit of a roundabout way of fixing the issue. Ideally a timestamp from the timestamp oracle would be plumbed through and explicitly used for each call to `forget`. However, in that scenario we'd want a single timestamp per user command, not per dropped object. So a user command that drops 1000 tables, should only use a single timestamp. So we'll have to do something like this PR to batch all forgets into a single call as pre-work. I don't plan on closing https://github.com/MaterializeInc/materialize/issues/25962 until that's done, though I wasn't planning on doing it immediately after since I think it will be a decent amount of work.

> First, it leaves the code in a state that it is not obvious that doing this in batch is such a load bearing property. What prevents someone from refactoring it the other way in the future?

Any suggestions on how to improve this? I'm not very familiar with this part of the code base and the comments implied that the current structure was fragile.

**Comment by petrosagg** [comment]
> Any suggestions on how to improve this? I'm not very familiar with this part of the code base and the comments implied that the current structure was fragile.

We're currently populating the pending compaction commands as a result of processing changes in read capabilities and by that time we have lost all information about any intent to batch things together. To do the long term solution of threading a timestamp all the way to the moment of dropping the objects an explicit drop API needs to be added to the controller that can communicate the intent that a group of objects need to be dropped as a batch and also to attach any additional metadata like a particular timestamp that the action should be performed at. I don't know if divorcing ourselves from using held capabilities to drive drops is a good thing, the current system seems quite elegant.

The other option would be to do the batching inside the component that needs it, which is the persist table worker, and explain there why it's beneficial to batch as many requests together as possible.

**Pull request closed without merging**
