### PR TITLE
Mark ReductionPushdown and ReduceElision WMR-safe

### PR DESCRIPTION
**Pull request by ggevay**
This just marks `ReductionPushdown` and `ReduceElision` to be WMR-safe, and adds slts for both. 

Note that unique key inference is not very smart yet for WMR, which is affecting `ReduceElision`, as shown by the last test in `reduce_elision.slt`. [I opened a separate issue for that](https://github.com/MaterializeInc/materialize/issues/18553), and will work on this next. But there are already some situations when both `ReductionPushdown` and `ReduceElision` kick in, so we can merge this PR in itself.

### Motivation

  * This PR adds a known-desirable feature:
    * #18170,
    * #18171

### Tips for reviewer

I suggest reviewing the test for pushdown before elision, because the elision tests are similar, but more complicated.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by aalexandrov** [comment]
Tagging @MaterializeInc/qa for a review.

**Comment by philip-stoev** [comment]
I will work on this today. Apologies for the delay.

**Review by philip-stoev — APPROVED** [review]
No wrong results or panics with WMR. The only plan changes are the removal of `Distinct`, which I guess is expected.

**Comment by ggevay** [comment]
Great, thank you very much!

**Review by aalexandrov — APPROVED** [review]
LGTM!

**Pull request merged**
