### PR TITLE
cloudtest: Migrate to kind

### PR DESCRIPTION
**Pull request by philip-stoev**
- the ability to execute SQL queries directly has been removed
  since making environmentd accessible to the outside is a tedious
  task in Kind. testdrive needs to be used instead.
### Motivation

  * This PR adds a known-desirable feature.

- #13721

### Suggestions to reviewer

"Hide whitespace" is recommended

### CODE REVIEW

**Comment by benesch** [comment]
> the ability to execute SQL queries directly has been removed
since making environmentd accessible to the outside is a tedious
task in Kind

Hm, it was easy enough to do this in cloud. Let me take a look in a bit.

**Comment by philip-stoev** [comment]
minikube I think punched an ssh tunnel when you did `minikube service --url` . `kind` requires the full Ingres shebang with a load balancer and then some more.

**Comment by necaris** [comment]
We "fix" this in the cloud repo with https://github.com/MaterializeInc/cloud/blob/main/misc/kind/cluster.yaml#L4 -- we set up the `serviceNodePortRange` and then forward _all_ ports in that range to the host. We could certainly do something similar here.

**Comment by philip-stoev** [comment]
ok will keep beating on this ...

**Comment by philip-stoev** [comment]
Thanks for the pointer! I was able to restore the ability to run SQL. Also added a documentation file .

**Review by necaris — APPROVED** [review]
This looks really great, nice work @philip-stoev !

**Pull request merged**
