### PR TITLE
doc/user: rename --logging-granularity to --introspection-frequency and document it

### LINKED ISSUE #5775: docs: --logging-granularity command-line option missing documentation
https://materialize.com/docs/cli/ seems to be missing the --logging-granularity CLI argument 

an explanation of the entire logging infrastructure would be nice to have in the documentation. No matter what I do I never get anything more than announcements about DDL statements in the log.

Internal chat: https://materializeinc.slack.com/archives/CMNT2QSBZ/p1613474317361800

### PR DESCRIPTION
**Pull request by benesch**
@frankmcsherry I didn't do a great job on the documentation. Let me know if you have better copy.

Fix #5775.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5793)

### CODE REVIEW

**Review by cirego — COMMENTED** [review]
Thank you for documenting this!

**Review by frankmcsherry — APPROVED** [review]
Looks good to me. I don't have an opinion on the tweaks to `mzcompose` files.

**Comment by benesch** [comment]
Yeah, I went to update them to use the new name, but ... none of them looked like they actually intended to configure the logging granularity. Think it just got copy/pasted around unnecessarily.

**Comment by cirego** [comment]
> Yeah, I went to update them to use the new name, but ... none of them looked like they actually intended to configure the logging granularity. Think it just got copy/pasted around unnecessarily.

Yeah, that looks like bad copy/paste.

**Pull request merged**
