### PR TITLE
*: prefer Diff over isize whenever possible

### PR DESCRIPTION
**Pull request by ruchirK**
This pr extracts the minimally intrusive set of changes from #7381 

The first commit removes the Diff redefinition in `src/dataflow/src/render/context.rs` and the second commit replaces `isize` for `Diff` in a number of places (intentionally not all) where we were using `isize` to mean "a logical diff".

### CODE REVIEW

**Review by frankmcsherry — APPROVED** [review]
Looks good to me.

**Review by mjibson — APPROVED** [review]

**Comment by mjibson** [comment]
One annoyance this has caused is that ChangeBatch hard codes i64. Is isize better for mz than i64?

**Comment by ruchirK** [comment]
> One annoyance this has caused is that ChangeBatch hard codes i64. Is isize better for mz than i64?

Just to double check Matt, does "this" here refer to "Diff is isize and not i64" and not "this PR"? I'm assuming its the former because this PR is purely a syntactic refactor but wanted to be sure.

I changed the diff type to be i64 in #7381 and ... it trades some pains for other pains? `count_total` and a few other dataflow operators hardcode the diff type to be isize and those become annoying to deal with. Plus you have to specify the Diff type every time you define the type of a collection which you didn't have to do previously.

I dunno that there's actually a pressing enough problem here to warrant doing anything other than "keep Diff as isize" but I don't have any strong opinions on this.

**Comment by mjibson** [comment]
Yes, I'm referring to the isize change. While working on tables I discovered a problem that was solved with ChangeBatch (https://github.com/MaterializeInc/materialize/pull/7263/files#diff-9fc9aab48f6290b549b1d95ea71e6aa4225ac9fa870a8a0b8aba29108694291aR2927) and was forced to convert to and then immediately from isize. It's not a huge deal, but kinda silly. My argument is maybe: since ChangeBatch uses i64, we should use that everywhere?

**Pull request merged**
