### PR TITLE
miri: Disable mz-persist-client iter::tests::consolidation

### PR DESCRIPTION
**Pull request by def-**
Required > 2400 seconds in https://buildkite.com/materialize/nightly/builds/8003
### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by nrainer-materialize** [comment]
Why do we have to disable this test (now)?
I mean the test is not new and passed until now, right? Do we know what caused it to be slower now and have we seen further instances of the timeout (annotation search does not show any)? Is it the update of timely and differential by Moritz a week ago?

**Comment by def-** [comment]
No idea, it can just be congestion with other tests running parallel by chance.

**Comment by nrainer-materialize** [comment]
I am not sure if we should disable a test just because of one single failure / timeout. What do you think?

**Comment by def-** [comment]
There are hundreds of unit tests disabled in Miri because of flakes like this. What is the alternative? I think keeping flakes and retrying is not a good solution. Bumping the timeout to 1 hour per unit test seems like a lot.

**Comment by nrainer-materialize** [comment]
I mean for me it is a difference if a test fails once every two years or twice a week. But ok... if there are already hundreds of tests handled in this way...

**Comment by nrainer-materialize** [comment]
The test is still run as a cargo test?

**Review by nrainer-materialize — APPROVED** [review]

**Comment by def-** [comment]
Yes, we ignore it only in the Miri runs.

**Pull request merged**
