### PR TITLE
docs: re add operations + migrate speed ups

### PR DESCRIPTION
**Pull request by joacoc**
### Motivation

Re-enables Materialize `Operating Materialize` sections.

Also this PR:
* Migrates the Speed Up section from the `lts` docs.
* Removes 
* Refactor the introduction.
* Hid an incompatible troubleshooting query.
* Doesn't focus on the legibility of the content. I just made two exceptions for the introduction and the subscription.

### Tips for reviewer

Does `doc/user/content/ops/_index.md` looks ok?

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Comment by morsapaes** [comment]
This needs to be rebased after #15134!

**Comment by joacoc** [comment]
@morsapaes Yes! I made the updates after it got merged. Or were there additional updates?
Anyways, I'm going to rebase and fix the lints issues.

**Review by morsapaes — APPROVED** [review]
LGTM. From a quick skim, it sounds like we might want to bring back the section on compaction at some point, but we can do that as a follow-up!

**Comment by joacoc** [comment]
@ggevay, the _speed up_ section is finally merged and ready to add the new `IN` improvements 👍

**Pull request merged**
