### PR TITLE
fix delta join test

### PR DESCRIPTION
**Pull request by ptravers**
The PR adds a third table to the test to force a three way join which triggers a delta join ensuring that the test is still accurately testing the same behaviour

### Motivation
https://github.com/MaterializeInc/materialize/issues/16478

### Tips for reviewer
N/A

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
 -->

### CODE REVIEW

**Comment by ggevay** [comment]
Hi @ptravers, the main part looks good!

Could you please remove the commit modifying the imports? I tried to build your PR locally, and it is currently not building for me, but it's building without that commit. (Maybe there was some conflict if you rebased on main.)

Also, could you squash the other two commits? 

I don't know how to make Buildkite run without you having credentials, but I'll ask someone who knows, after you remove the import commit and squash the other two.

**Comment by ggevay** [comment]
(The storage team can ignore this PR.)

**Comment by ptravers** [comment]
Sure thing! Will do a little later

**Comment by ptravers** [comment]
Sorry for the hassle there! made two changes:
1. squashed everything into one commit
2. reverted the missing imports... yet another lesson in why you don't add unrelated changes!

**Review by ggevay — APPROVED** [review]

**Comment by ggevay** [comment]
Sorry, one last thing: Could you please clean up the commit message?
- The imports and revert should be deleted.
- It should mention that it is fixing a test.

**Comment by ptravers** [comment]
Can do!

**Comment by ggevay** [comment]
Sorry, yes, there is indeed only one commit now, but what I meant is editing the commit message. The first line of the commit message is good now, but there are 4 more lines, which are mentioning things from the original commits. (I guess these lines got into the commit message when you squashed the other commits maybe.) Note that GitHub only shows the first line by default, but it will show the extra lines if you click on the ... next to the first line.

**Comment by ptravers** [comment]
ah woops, sorry!

**Comment by ptravers** [comment]
Hey! I'm sorry I had a bunch of stuff come up in my life and totally lost track of this. is it

**Comment by ggevay** [comment]
Hi!

> I'm sorry I had a bunch of stuff come up in my life and totally lost track of this.

No problem!

> I think the underlying test has been fixed?

I don't think so. It seems to still have the exact same problem as before: It's planned as a `differential` join, when the test is intended to test `delta` joins.

**Pull request closed without merging**
