### PR TITLE
Simplify and generalize `MirRelationExpr` visitor logic

### PR DESCRIPTION
**Pull request by frankmcsherry**
This PR adds enumeration methods `MirRelationExpr::{children, children_mut}` capable of enumerating references and mutable references to child expressions. These are more expressive than `visit_children` in that the lifetime bounds are the same as the argument references. Also, the four implementations for `VisitChildren` are simplified into two methods.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-protobuf` label.
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Review by aalexandrov — APPROVED** [review]
LGTM!

Introducing the `children()` iterator for `Mir~` is good in itself because it simplifies the `Visit` implementation

I changed the `VisitChildren` methods in #13757 in order to make it work for `Hir~` where the `~RelationExpr` and` `~ScalarExpr` types mutually depend on each other, but it seems that in doing that I restricted it too much. I will try to revert my change so we can go back to the more general lifetime bounds in the `visit_children` methods.

**Comment by aalexandrov** [comment]
Re-posting this (a quote @frankmcsherry from a private conversation) so I can track the original limitation that prompted this:

Using `visit_children` I get the following error:
```
69 |     let mut to_check = vec![relation];
   |         ------------ `to_check` declared here, outside of the closure body
...
98 |                 x.visit_children(|e| { to_check.push(e); });
   |                                   -    ^^^^^^^^^^^^^^^^ `e` escapes the closure body here
```

I think this is because the signatures are
```rust
    /// Apply an infallible immutable function `f` to each direct child.
    fn visit_children<F>(&self, f: F)
    where
        F: FnMut(&T);
```
rather than
```rust
    /// Apply an infallible immutable function `f` to each direct child.
    fn visit_children<'a, F>(&'a self, f: F)
    where
        F: FnMut(&'a T),
        T: 'a;
```
This seems to not work out because of the goal of having `Visit` be parametric in `T` (I'm not sure why it doesn't work out).

Anyhow, it means that `visit_children` forces one to write recursive programs, rather than iterative programs.
Like, you apparently (modulo bugs on my part) cannot write
```rust
let mut todo = vec![expr];
while let Some(expr) = !todo.pop() {
    expr.visit_children(|e| todo.push(e));
}
```

**Comment by frankmcsherry** [comment]
Thanks for the speedy look!

**Comment by aalexandrov** [comment]
Further note (I will transfer this in a separate issue next week):

With the changes from this PR, this compiles:

```rust
fn test_visitor() {
    let expr = MirRelationExpr::constant(vec![vec![]], RelationType::new(vec![]));
    let expr = expr.project(vec![0, 1]);

    let mut root = None;

    for child in expr.children() {
        if root.is_none() {
            root = Some(child);
            break;
        }
    }
}
```

but not this


```rust
fn test_visitor() {
    let expr = MirRelationExpr::constant(vec![vec![]], RelationType::new(vec![]));
    let expr = expr.project(vec![0, 1]);

    let mut root = None;

    let res = expr.visit_pre(&mut |expr| {
        if root.is_none() {
            root = Some(expr);
        }
    });
}
```

because of the same issue (the lambda argument `expr` escapes the closure body). The fact that we don't use this feature in `main` probably means that it's not absolutely critical, but it will be great to understand whether this is an inherent limitation with any traversal signature or only with the one that we have defined here.

**Pull request merged**
