### PR TITLE
compute: Document that subscribe results are sorted by time

### PR DESCRIPTION
**Pull request by andrewrodriguez-m**
Today we call consolidate_updates in send_batch which sorts the updates by time. Since consolidating needs to fundamentally group by time this guarantee seems reasonable for compute to make

### Motivation

Remove the TODO in the adapter's subscribe code that I'm deleting in this PR

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by benesch** [comment]
Neat! Requested review from @teskje specifically.

**Review by teskje — CHANGES_REQUESTED** [review]
I don't think we can make this guarantee currently in compute. At least I'm not aware of any logic that would sort subscribe updates by time.

You mention consolidation, but at least [the `consolidate_updates` function](https://dev.materialize.com/api/rust/differential_dataflow/consolidation/fn.consolidate_updates.html) does not document that it leaves the buffer sorted by time. As it turns out, it sorts by datum first, then time:

```rust
use differential_dataflow::consolidation::consolidate_updates;

fn main() {
    let mut updates = vec![('a', 1, 1), ('a', 2, 1), ('b', 1, 1)];
    consolidate_updates(&mut updates);

    assert_eq!(updates, vec![('a', 1, 1), ('a', 2, 1), ('b', 1, 1)]);
}
```

So I think the explicit sorting is in fact necessary. We could do it in compute, but I don't really see a reason to. Even if the compute protocol would provide that guarantee, adapter would still need to check that it still holds for data received from the compute controller.

**Comment by umanwizard** [comment]
@teskje The value we pass to `consolidate_updates` in subscribe.rs is of type `Vec<(Timestamp, Row, Diff)>`.

**Comment by teskje** [comment]
> The value we pass to `consolidate_updates` in subscribe.rs is of type `Vec<(Timestamp, Row, Diff)>`.

You are correct! That makes me unhappy, but I guess that's technically not a bug since the `consolidate_update` docs don't say that `D` is data and `T` is time.

So it's true that compute returns subscribe updates sorted by time and we could give that guarantee in the compute protocol. There is still the issue that a guarantee provided for the compute protocol doesn't necessarily have to hold for the output produced by the compute controller.

So I would suggest one of two things:
1. If you want to go forward with this PR, we should still have a check in the adapter asserting that the returned subscribe output is sorted.
2. Alternatively, just keep doing the sorting in the adapter. We probably don't expect subscribe batches too be huge, so that might be fine performance-wise?

**Comment by andrewrodriguez-m** [comment]
I think it's fine if this isn't a guarantee we want compute to make; I don't think this is pressing performance-wise

I don't totally grok:
> There is still the issue that a guarantee provided for the compute protocol doesn't necessarily have to hold for the output produced by the compute controller.

My understanding is that the compute protocol (in this case `SubscribeProtocol`) sits on top of the compute controller and could make that guarantee without any help from the compute controller

**Comment by teskje** [comment]
> My understanding is that the compute protocol (in this case SubscribeProtocol) sits on top of the compute controller and could make that guarantee without any help from the compute controller

There is a difference between the "compute protocol" and `SubscribeProtocol`:
* The "compute protocol" consists of `ComputeCommand`s and `ComputeResponse`s and a set of rules (written down in the doc comments of these types) that describe requirements on senders of both. It specifies how the compute controller exchanges information with the replicas. The compute controller doesn't talk directly to the replicas, there is a stack of clients in between that do things like protobuf-encoding, and splitting messages between replica processes and threads. All of these intermediary clients have to adhere to the compute protocol as well.
* `SubscribeProtocol` is an implementation detail of how replicas collect subscribe batches and declare them as ready for sending back to the compute controller.

The compute controller uses the compute protocol to exchange messages with the replicas. It also provides an API to users of COMPUTE (like adapter). Crucially, users of COMPUTE don't talk the compute protocol directly, they talk to the compute controller, which translates their requests to compute commands, if necessary. So the compute protocol is internal to COMPUTE, it's not something that is exposed to users. Which means users generally can't assume guarantees made by the compute protocol. The controller has the freedom to take responses it receives from replicas through the compute protocol and modify them in any way it sees fit before giving them to its users. You can reasonably assume that it doesn't make many of these modifications, but there is nothing guaranteeing that, and there is nothing that prevents us from making (accidental or not) breaking changes to the compute controller.

Really, what we should do is better specify/document the compute controller API. That's tracked as part of #18496.

**Comment by andrewrodriguez-m** [comment]
Ok, thanks @teskje for the explanation. I'll close this PR, keep the sorting in the adapter layer, and change the comment to link here

**Pull request closed without merging**
