### PR TITLE
coord: error on duplicate portal

### LINKED ISSUE #5543: materialized: tail transmitter failed: Cannot assign requested address
User is reporting a panic at `src/sink/tail.rs:35`:

```
tail transmitter failed: Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }
```

This appears to be some file descriptor leak.

### PR DESCRIPTION
**Pull request by mjibson**
Named portals cannot be overwritten. This fixes a file descriptor/memory
leak due to orphaned sinks being created during DECLARE TAIL.

Fixes #5543

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5753)

### CODE REVIEW

**Review by benesch — APPROVED** [review]
LGTM because I think this is a strict improvement. I'm on my way out the door and I can't figure out what makes it safe to replace the empty portal though?

**Comment by mjibson** [comment]
https://github.com/postgres/postgres/blob/ae4867ec749671dadb5eb49a1158ded9b8ca0b29/src/backend/tcop/postgres.c#L1722 is the postgres comment that describes it. Without that exception we fail some of the pgtests that already existed (since we were already doing that).

**Comment by mjibson** [comment]
https://github.com/postgres/postgres/blob/ae4867ec749671dadb5eb49a1158ded9b8ca0b29/src/backend/tcop/postgres.c#L1180 is the comment for multi statement queries.

**Comment by benesch** [comment]
No sorry I know it is desirable and correct to silently replace it! I just meant if the empty portal is currently running a tail how do we ensure we clean that tail up?

**Comment by mjibson** [comment]
Oh gotcha. Yeah thinking about that more...this isn't quite enough. Also all the tail tests are failing so I'll keep working on this. Didn't think it through enough.

**Comment by mjibson** [comment]
Merging this because, upon further research, redeclaring a portal over an existing (i.e., previous to this commit) correctly dropped the sink id of the overwritten portal. This suggests the problem might be elsewhere. Anyway, after the comm change, the only way to actually look into this bug for real is to use an older commit, so this PR isn't papering over anything that isn't already papered over.

**Pull request merged**
