### PR TITLE
doc/user: polish v0.29.0 release notes

### PR DESCRIPTION
**Pull request by morsapaes**
Flesh out the `v0.29.0` release notes. Deliberately left out:

* https://github.com/MaterializeInc/materialize/pull/15563
* https://github.com/MaterializeInc/materialize/pull/15560

These strike me as fixes for behavior that was undesired in the first place. Let me know if you disagree, and I'll work them in, @benesch!
<hr>

⏰ Reminder to merge #15550 once we merge this PR!

### CODE REVIEW

**Comment by morsapaes** [comment]
While reviewing the changes, I found it a bit confusing that indexes on introspection sources are exposed when using `SHOW INDEXES IN CLUSTER`.

```sql
SHOW INDEXES IN CLUSTER default;

                           name                            |                     on                     | cluster |                      key
-----------------------------------------------------------+--------------------------------------------+---------+------------------------------------------------
 customers_primary_idx                                     | customers                                  | default | {id,name,expenses}
 mz_active_peeks_u1_primary_idx                            | mz_active_peeks                            | default | {id,worker_id}
 mz_arrangement_batches_internal_u1_primary_idx            | mz_arrangement_batches_internal            | default | {operator_id,worker_id}
 mz_arrangement_records_internal_u1_primary_idx            | mz_arrangement_records_internal            | default | {operator_id,worker_id}
 mz_arrangement_sharing_internal_u1_primary_idx            | mz_arrangement_sharing_internal            | default | {operator_id,worker_id}

...

-- Try creating an index on a random mz_internal object, 
-- which is expected to fail
materialize=> CREATE DEFAULT INDEX ON mz_internal.mz_message_counts;
ERROR:  cannot create index with unstable dependencies
DETAIL:  The object depends on the following unstable objects:
    mz_message_counts
    
-- Try dropping a random index in mz_internal,
-- which is also expected to fail
materialize=> DROP INDEX mz_internal.mz_active_peeks_u1_primary_idx;
ERROR:  cannot drop item mz_internal.mz_active_peeks_u1_primary_idx because it is required by the database system
```

Is it wrong to expect that only indexes in `mz_catalog` objects are exposed, @jkosh44? If users can't fiddle with system objects that are part of the unstable interface, also exposing indexes in `mz_internal` seems to add a bunch of unnecessary noise.

**Review by benesch — APPROVED** [review]
LGTM!

**Comment by jkosh44** [comment]
> Is it wrong to expect that only indexes in `mz_catalog` objects are exposed, @jkosh44? If users can't fiddle with system objects that are part of the unstable interface, also exposing indexes in `mz_internal` seems to add a bunch of unnecessary noise.

I changed this in https://github.com/MaterializeInc/materialize/pull/15592. Honestly, I'm not sure what the correct behavior should be. We wanted some way to see ALL indexes in a cluster for debugging purposes when the cluster would start OOMing or use too much CPU. Though I do think showing system indexes can also end up confusing users.

Maybe we should add an additional keyword like `SHOW ALL INDEXES` that will include system indexes and `SHOW INDEXES` excludes system indexes. 

@mjibson also had some opinions on this so I'm tagging him.

**Comment by mjibson** [comment]
My opinion was that there should be some `SHOW` command that did what we expected on the introspection and system clusters. I don't care much how that is achieved.

**Comment by benesch** [comment]
+.1 from me on continuing to show system indexes. They _are_ there, after all, even though they're internal. One day the logging sources will be promoted to `mz_catalog`, and maybe we'll feel less bad about it?

**Pull request merged**
