### PR TITLE
adapter: extract an OptimizerCatalog trait

### PR DESCRIPTION
**Pull request by danhhz**
This will help with continual tasks, which need to inject an entry for
the CT itself before it exists in the catalog, but also it gets us one
step closer to pulling the optimizer into its own crate.

I also switched over a few more `adapter::optimize::*::Optimizer`
structs, but had to leave a few because it gets tricky with
`ExprPrepStyle::OneShot` and `eval_unmaterializable_func`.

Touches MaterializeInc/database-issues#8427

### Motivation

   * This PR refactors existing code.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

**Comment by danhhz** [comment]
This should be ready for review!

**Review by teskje — COMMENTED** [review]
LGTM, but leaving the approval to Gabor.

**Review by ggevay — APPROVED** [review]
LGTM!

**Review by ParkMyCar — APPROVED** [review]
Clean 👌

**Comment by danhhz** [comment]
TFTRs!

**Pull request merged**
