### PR TITLE
slt: Use tmpfs for /tmp

### PR DESCRIPTION
**Pull request by def-**
Should cause some speedup on slow disks

As discussed in https://materializeinc.slack.com/archives/C01LKF361MZ/p1702921130517769

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by mjibson — APPROVED** [review]

**Comment by benesch** [comment]
I think `RUN --mount` only applies for the build phase. I pushed up a change to mount `/tmp` as a `tmpfs` via mzcompose, which should apply during runtime. Won't have time to stick around and watch it tonight though.

**Review by nrainer-materialize — APPROVED** [review]

**Comment by def-** [comment]
Thanks Nikhil. It seems to cause no speedup in CI anyway. I compared https://buildkite.com/materialize/tests/builds/71511#_ with https://buildkite.com/materialize/tests/builds/71520#_ from main, and with tmpfs for /tmp it's even slower somehow (probably just normal variation, same c6a.2xlarge instance type). So I'd be in favor of just closing this for now.

**Comment by benesch** [comment]
Sounds good to me. We'd probably need to look at metrics/profiling to figure out whether the file blob store is actually a meaningful contributor to the slowness of SLT.

**Comment by benesch** [comment]
Wait, did you mean to close instead of merge?

**Comment by def-** [comment]
Yes, we can also merge it, but I didn't see a difference.

**Pull request merged**
