### PR TITLE
limit CPUs used to lower of physical or logical cores

### LINKED ISSUE #7583: Materialized improperly detects CPUs/RAM and spawns more workers than desired
### What version of Materialize are you using?

```
materialized v0.8.3 (3e47d2809)
```

### How did you install Materialize?
* [X] Docker image (in Materialize Cloud)

### What was the issue?
Materialized detects the wrong number of CPUs/RAM and spawns more workers than desired.

materialized startup logs:
```
os: Ubuntu 18.4.0 [64-bit]
cpus: 4 logical, 32 physical
cpu0: AMD EPYC 7571 2535MHz
memory: 536299868KB total, 21336369KB used
swap: 0KB total, 0KB used 
```
Workers:
```
materialize=> select mz_workers();
 mz_workers 
------------
         16
```

This is on a kubernetes pod with 3.75 vCPU and 30GiB RAM limits.

The worker allocation should be changed to be based on the logical cores, so that it stays within the cgroup limits.

Additionally, if we do anything based on the memory detected, that should be changed to be based on the cgroup memory limit.

### Is the issue reproducible? If so, please provide reproduction instructions.
Create an instance in Materialize Cloud.

### PR DESCRIPTION
**Pull request by alex-hunt-materialize**
If inside a cgroup with a cpu limit, the logical cores could be lower
than the physical cores.

This is especially likely when running using systemd, docker, or
kubernetes.

Resolves #7583

### CODE REVIEW

**Comment by benesch** [comment]
Here's the original context: https://github.com/MaterializeInc/materialize/pull/4407. Looping in @elindsey and @umanwizard from that PR. 

I think this is a decent default, if we have to pick just one! It's certainly a strict improvement over the current situation.

This still isn't what we want for cloud though, where I think the latest thinking is we want `NCPUS - 1`. We want to give all the cores to timely, except for one which we reserve for "everything else." One take is: that's totally fine, and we'll set `--workers=N` ourselves based on the size of the deployment. No biggie. An alternative take is: everyone who has a cgroup quota configured will want to use NCPUS-1, and we should detect if a cgroup quota is active and if so use the better formula. But that might be too complicated to be worth it.

Thoughts?

**Comment by alex-hunt-materialize** [comment]
I tried to keep the logic the same except for using a different base cpu count. Is there a reason we wouldn't want to use `NCPUS - 1` for everyone? Is that to play nicer for developers on their laptops?

Lets talk tomorrow.

**Comment by benesch** [comment]
> I tried to keep the logic the same except for using a different base cpu count. Is there a reason we wouldn't want to use `NCPUS - 1` for everyone? Is that to play nicer for developers on their laptops?

Yeah, exactly, that was the idea.

**Comment by elindsey** [comment]
>  One take is: that's totally fine, and we'll set --workers=N ourselves based on the size of the deployment. No biggie. An alternative take is: everyone who has a cgroup quota configured will want to use NCPUS-1, and we should detect if a cgroup quota is active and if so use the better formula.

Does that logic amount to "if logical < physical, use logical -1", or is there more complex logic we'd need to detect a cgroup quota?

Generally I don't want to go too far down the path of trying to make the mz binary auto tune for both desktop and server use cases today, but I'd be onboard with that change.

**Comment by benesch** [comment]
Yeah, agreed that getting too fancy is also bad. I don’t think just
watching for logical < physical is sufficient? I think, not sure, that you
could have a cgroup quota limiting you to say 6 logical CPU of a 4 physical
core machine?

**Comment by alex-hunt-materialize** [comment]
The logical CPUs reported by the num_cpus crate are correctly limited if in a cgroup (ie: it takes the limit into account). See the node on `num_cpus::get` https://docs.rs/num_cpus/1.13.0/num_cpus/fn.get.html .

The code in this PR basically just uses the lower of the numbers in place of always using the physical count. There is no need for complex logic to detect if we're in a cgroup, unless we want different tuning for desktop vs server.

In general, I'd prefer to use sane defaults for the server use case, and let desktop users manually pass in the number of workers. That is the opposite of what we have now and in this PR.

Detecting if we're in a limited cgroup may be tricky, as we'd need to do conditional compilation for Linux vs non-Linux platforms. There are also two incompatible versions of cgroups on Linux, and supporting both gets complex fairly quickly. Cgroups also aren't something you turn on/off. All applications launch in a cgroup, but the default cgroup just doesn't have limits for most things. I did a quick pass yesterday at that with the cgroups-rs crate, and hit multiple panics that should have just returned results. Looking at the code, it's full of unwraps, and I don't really trust it. There are other cgroup crates, but no others are actively maintained or as complete.

Cgroups don't really distinguish between SMT "cores" and physical "cores". They all count the same from that perspective. AFAICT, there isn't any way to set a cgroup quota limiting you to 6 logical CPU and 4 physical CPUs on a machine with 8 SMT hardware threads. It's done by CPU time, not by which device is running the code. There is a separate cpuset cgroup setting for specifying the exact cores you are allowed to run on (not affinity, that has to be configured separately too), which is totally unrelated to this problem.

**Review by elindsey — APPROVED** [review]
Yeah doesn't sound worth heading down that path of complexity right now. I'm fine with this change as-is!

Happy to keep discussing the auto-tuning for desktop vs server off this PR if you'd like

**Review by benesch — APPROVED** [review]

**Pull request merged**
