### PR TITLE
Fix replica frontier tracking in compute

### LINKED ISSUE #15426: storage: cannot serve requested as_of
### What version of Materialize are you using?

 v0.27.0 (218138173)

### How did you install Materialize?

Materialize Cloud

### What is the issue?

1. Created a Kafka source with byte-formatted keys and values
3. Created a new cluster.
4. Created two replicas with differing sizes, `medium` and `xlarge`.
2. Created a materialized view to deserialized the bytes as JSON and then structured them.
3. Explicitly set my cluster to the new cluster.
4. Explicitly set my target replica to `medium`.
5. Queried the materialized view, which succeeded.
6. Explicitly set my target replica to `xlarge`.
7. Queried the materialized view, which never completed.
8. Checked logs in Honeycomb and determined that my worker had panicked:
    ```
    thread 'tokio-runtime-worker' panicked at 'u242: cannot serve requested as_of Antichain { elements: [1665768908791] }: Since(Antichain { elements: [1665769196001] })', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0efb11835bec0ffd2-1/materialize/tests/src/storage/src/source/persist_source.rs:230:24
    ```

### Relevant log output

```source
Honeycomb produces the stack trace upside down--sorry!


compute-cluster-u8-replica-16-0	
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/pool.rs:300:13
compute-cluster-u8-replica-16-0	
  53: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/pool.rs:325:17
compute-cluster-u8-replica-16-0	
  52: tokio::runtime::blocking::pool::Inner::run
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/pool.rs:91:9
compute-cluster-u8-replica-16-0	
  51: tokio::runtime::blocking::pool::Task::run
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/mod.rs:418:9
compute-cluster-u8-replica-16-0	
  50: tokio::runtime::task::UnownedTask<S>::run
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/raw.rs:84:18
compute-cluster-u8-replica-16-0	
  49: tokio::runtime::task::raw::RawTask::poll
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:57:15
compute-cluster-u8-replica-16-0	
  48: tokio::runtime::task::harness::Harness<T,S>::poll
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:104:27
compute-cluster-u8-replica-16-0	
  47: tokio::runtime::task::harness::Harness<T,S>::poll_inner
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:468:18
compute-cluster-u8-replica-16-0	
  46: tokio::runtime::task::harness::poll_future
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
compute-cluster-u8-replica-16-0	
  45: std::panic::catch_unwind
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
compute-cluster-u8-replica-16-0	
  44: std::panicking::try
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
compute-cluster-u8-replica-16-0	
  43: std::panicking::try::do_call
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panic/unwind_safe.rs:271:9
compute-cluster-u8-replica-16-0	
  42: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:480:19
compute-cluster-u8-replica-16-0	
  41: tokio::runtime::task::harness::poll_future::{{closure}}
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:155:13
compute-cluster-u8-replica-16-0	
  40: tokio::runtime::task::core::CoreStage<T>::poll
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/loom/std/unsafe_cell.rs:14:9
compute-cluster-u8-replica-16-0	
  39: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:165:17
compute-cluster-u8-replica-16-0	
  38: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/task.rs:42:21
compute-cluster-u8-replica-16-0	
  37: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:362:45
compute-cluster-u8-replica-16-0	
  36: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:383:5
compute-cluster-u8-replica-16-0	
  35: tokio::runtime::thread_pool::worker::run
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/macros/scoped_tls.rs:61:9
compute-cluster-u8-replica-16-0	
  34: tokio::macros::scoped_tls::ScopedKey<T>::set
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:386:17
compute-cluster-u8-replica-16-0	
  33: tokio::runtime::thread_pool::worker::run::{{closure}}
compute-cluster-u8-replica-16-0	
  32: tokio::runtime::thread_pool::worker::Context::run
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:434:9
compute-cluster-u8-replica-16-0	
  31: tokio::runtime::thread_pool::worker::Context::run_task
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:72:5
compute-cluster-u8-replica-16-0	
  30: tokio::coop::budget
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:95:5
compute-cluster-u8-replica-16-0	
  29: tokio::coop::with_budget
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:421:9
compute-cluster-u8-replica-16-0	
  28: std::thread::local::LocalKey<T>::with
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:445:16
compute-cluster-u8-replica-16-0	
  27: std::thread::local::LocalKey<T>::try_with
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:102:9
compute-cluster-u8-replica-16-0	
  26: tokio::coop::with_budget::{{closure}}
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:458:21
compute-cluster-u8-replica-16-0	
  25: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/mod.rs:381:9
compute-cluster-u8-replica-16-0	
  24: tokio::runtime::task::LocalNotified<S>::run
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/raw.rs:84:18
compute-cluster-u8-replica-16-0	
  23: tokio::runtime::task::raw::RawTask::poll
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:57:15
compute-cluster-u8-replica-16-0	
  22: tokio::runtime::task::harness::Harness<T,S>::poll
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:104:27
compute-cluster-u8-replica-16-0	
  21: tokio::runtime::task::harness::Harness<T,S>::poll_inner
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:468:18
compute-cluster-u8-replica-16-0	
  20: tokio::runtime::task::harness::poll_future
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
compute-cluster-u8-replica-16-0	
  19: std::panic::catch_unwind
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
compute-cluster-u8-replica-16-0	
  18: std::panicking::try
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
compute-cluster-u8-replica-16-0	
  17: std::panicking::try::do_call
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panic/unwind_safe.rs:271:9
compute-cluster-u8-replica-16-0	
  16: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:480:19
compute-cluster-u8-replica-16-0	
  15: tokio::runtime::task::harness::poll_future::{{closure}}
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:155:13
compute-cluster-u8-replica-16-0	
  14: tokio::runtime::task::core::CoreStage<T>::poll
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/loom/std/unsafe_cell.rs:14:9
compute-cluster-u8-replica-16-0	
  13: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:165:17
compute-cluster-u8-replica-16-0	
  12: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
compute-cluster-u8-replica-16-0	
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
compute-cluster-u8-replica-16-0	
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0efb11835bec0ffd2-1/materialize/tests/src/storage/src/source/persist_source.rs:147:55
compute-cluster-u8-replica-16-0	
  10: <mz_storage::source::persist_source::DropSafeLeaseStream as core::ops::drop::Drop>::drop::{{closure}}
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.24/src/stream/stream/next.rs:32:9
compute-cluster-u8-replica-16-0	
   9: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.24/src/stream/stream/mod.rs:1626:9
compute-cluster-u8-replica-16-0	
   8: futures_util::stream::stream::StreamExt::poll_next_unpin
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.24/src/stream.rs:120:9
compute-cluster-u8-replica-16-0	
   7: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/async-stream-0.3.3/src/async_stream.rs:53:17
compute-cluster-u8-replica-16-0	
   6: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
compute-cluster-u8-replica-16-0	
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
compute-cluster-u8-replica-16-0	
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/async-stream-0.3.3/src/lib.rs:237:9
compute-cluster-u8-replica-16-0	
   4: mz_storage::source::persist_source::persist_source_core::{{closure}}
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1493:23
compute-cluster-u8-replica-16-0	
   3: core::result::Result<T,E>::unwrap_or_else
compute-cluster-u8-replica-16-0	
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0efb11835bec0ffd2-1/materialize/tests/src/storage/src/source/persist_source.rs:230:24
compute-cluster-u8-replica-16-0	
   2: mz_storage::source::persist_source::persist_source_core::{{closure}}::{{closure}}
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
compute-cluster-u8-replica-16-0	
   1: core::panicking::panic_fmt
compute-cluster-u8-replica-16-0	
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
compute-cluster-u8-replica-16-0	
   0: rust_begin_unwind
```
```

### PR DESCRIPTION
**Pull request by teskje**
This PR is an attempt at fixing the frontier tracking of compute replicas to ensure we always hold compaction of input storage collections back as far as necessary, i.e., until all replicas have reported that their dataflows have read beyond the respective times.

This is implemented by the compute controller directly maintaining storage read capabilities tracking the frontiers of each individual replicas. This is simpler than trying to keep track of a lower bound and also frees us from having to worry about the lower bound potentially going backwards when a new replica is added.

### Motivation

  * This PR fixes a recognized bug.

Fixes #15426.

### Tips for reviewer

~~This PR is based on https://github.com/MaterializeInc/materialize/pull/15610, so it includes all the commits from there, which makes the full diff useless until #15610 is merged.~~ Looking at the commits separately works though, and is maybe the better use of your time anyway. I tried to make the commits as small as possible.

### Testing

Still in progress, but these are the things I tried so far:

- [x] locally verified that storage collection sinces keep moving when:
    - [x] adding a compute collection reading from them
    - [x] dropping compute collections
    - [x] adding new replicas
    - [x] dropping all but the last replica
    - [x] restarting environmentd 
- [x] ran [Philip's reproduction](https://github.com/MaterializeInc/materialize/issues/15426#issuecomment-1280591712) and verified that it doesn't produce "cannot serve requested as_of" panics anymore
- [x] installed this version of the code in staging
    - Org ID df0c80c6-2467-41a8-9ca9-caece68c4d60
    - [x] created an auction load generator and a couple indexes and materialized views on its sources
    - [x] checked after some time that there are no errors or suspiciously increased resource usage
    - [x] [ensured no sinces get stuck](https://g-2531aff0fb.grafana-workspace.us-east-1.amazonaws.com/d/m3U1U6ZVk/persist?orgId=1&var-datasource=cloud-staging%20eu-west-1&var-env=environment-df0c80c6-2467-41a8-9ca9-caece68c4d60-0&var-pod=All&var-shard=All&editPanel=61&from=1666794600000&to=now)
        - [x] when restarting environment
        - [x] when restarting computeds 

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Comment by lluki** [comment]
Is `CollectionState::write_frontier` guaranteed to be `max(Collection::replica_write_frontiers)`, or is there any case where that wouldnt be true?

After reading through #15426 and in particular your [2nd scenario](https://github.com/MaterializeInc/materialize/issues/15426#issuecomment-1285646553), I'm a bit confused, I thought the fix for this bug would require keeping the read capabilities per replica, but this PR accounts for write frontiers per replica?

**Comment by teskje** [comment]
> Is `CollectionState::write_frontier` guaranteed to be `max(Collection::replica_write_frontiers)`, or is there any case where that wouldnt be true?

Yes, `write_frontier` is always the maximum frontier ever reported by any replica. It is only updated inside `update_write_frontiers`, which ensures the invariant.

> After reading through https://github.com/MaterializeInc/materialize/issues/15426 and in particular your https://github.com/MaterializeInc/materialize/issues/15426#issuecomment-1285646553, I'm a bit confused, I thought the fix for this bug would require keeping the read capabilities per replica, but this PR accounts for write frontiers per replica?

The compute controller has no way to directly observe how far the replicas have read from their storage inputs. It needs to use the write frontiers of the corresponding dataflow outputs as a proxy instead. If a replica reports that it has written a collection up to time _t_, then we know that the dataflow that maintains that collection must also have read from all of its storage inputs at least up to time _t_, so we can downgrade the read capabilities we hold in the storage controller to time _t_ as well.

**Comment by lluki** [comment]
Thanks, got it. So if we have `r` replicas, each collection has `r` entries in the `CollectionState::read_capabilities`, and that's true for collections maintained by ComputeController, as well as those managed by StorageController. 

In `ActiveInstance::remove_replica`, we call [`ActiveInstance::remove_write_frontiers`](https://github.com/MaterializeInc/materialize/pull/15614/files#diff-f41d2f667183ab54e90f213600633855dd765c97c69f6bb8137c7c95cfb711e1R723) which updates the storage controller read capabilities. Doesn't it also need to update the compute controller capabilities?

**Comment by teskje** [comment]
> Thanks, got it. So if we have r replicas, each collection has r entries in the CollectionState::read_capabilities, and that's true for collections maintained by ComputeController, as well as those managed by StorageController.

Not quite! Let's say we have _r_ replicas and create a dataflow maintaining a compute collection _D_ and importing one storage collection _S_ and one compute collection _C_. Creating this dataflow adds:
* In the storage controller, _r_ + 1 read capabilities for collection _S_. That is one capability for each replica, to hold the since back to the replica's write frontiers, plus one capability the compute controller installs for the dataflow output _D_ independently of any replicas. That last capability is determined by the read frontier of _D_. It is needed because we also need to hold back the compaction of _S_ when no replicas exist currently.
* In the compute controller, only one capability is added for _C_, namely the one derived from _D_'s read frontier. We don't need to maintain per-replica capabilities for compute collections (i.e. arrangements), because timely will make sure those don't get compacted more than the readers have advanced.

> In ActiveInstance::remove_replica, we call [ActiveInstance::remove_write_frontiers](https://github.com/MaterializeInc/materialize/pull/15614/files#diff-f41d2f667183ab54e90f213600633855dd765c97c69f6bb8137c7c95cfb711e1R723) which updates the storage controller read capabilities. Doesn't it also need to update the compute controller capabilities?

That is precisely because we don't install per-replica capabilities for compute dependencies of dataflows. If you check `update_write_frontiers` you will notice that there we also only install/update per-replica capabilities for the storage dependencies.

**Comment by philip-stoev** [comment]
The `cannot serve as_of` panic is no longer seen with the original Zippy test that I had that reproduced it reliably. I am now running a full Nightly.

**Review by philip-stoev — APPROVED** [review]
Nightly is also not worse than usual, so this is good to go as far as I am concerned.

**Review by lluki — APPROVED** [review]

**Pull request merged**
