### PR TITLE
Create mz_tables system table and update SHOW TABLES

### PR DESCRIPTION
**Pull request by JLDLaughlin**
Another step to completing this task: https://github.com/MaterializeInc/materialize/issues/913

This PR adds a new `mz_catalog.mz_tables` table that contains a unique row for each table in a Materialize instance. Additionally, it updates the implementation of `SHOW TABLES` to read from `mz_tables`.

The new implementation of `SHOW TABLES` leaves `SHOW EXTENDED TABLES` unimplemented, which didn't work correctly prior to this PR. Example:
```
materialize=> show tables;
 TABLES
--------
 t
(1 row)

materialize=> show extended tables;
 TABLES
--------
 t
(1 row)
```

This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4218)

### CODE REVIEW

**Review by benesch — COMMENTED** [review]
:lgtm_strong: sorry for the delay in review!

> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4218#-:-MHMT6W94UblfbiQ5Ous:b16m0rr)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @benesch)

**Review by benesch — COMMENTED** [review]
Oh hang on, missed the SQL construction. 1 second.

> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4218#-:-MHMTEkkD3jU2HZyuf9l:br4hlsx)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @benesch)

**Review by benesch — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 2 of 3 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4218)* status: all files reviewed, 4 unresolved discussions (waiting on @JLDLaughlin)

___
*[src/sql/src/plan/statement.rs, line 746 at r6](https://reviewable.io/reviews/materializeinc/materialize/4218#-MHM_0IACTryXWbXCV5j:-MHM_0IACTryXWbXCV5k:bygrqs7) ([raw file](https://github.com/materializeinc/materialize/blob/752fbedb3914d1f5a5da7a46581a6b2bb8f5c6b3/src/sql/src/plan/statement.rs#L746)):*
> ```Rust
>     };
>     let filter = match filter {
>         Some(ShowStatementFilter::Like(like)) => format!("AND tables LIKE '{}'", like),
> ```

Ah yeah, while not _quite_ SQL injection here, this will mishandle `LIKE` patterns that contain single quotes. `format!("AND tables LIKE {}", Value::String(like)` will escape things properly.
___
*[src/sql/src/plan/statement.rs, line 775 at r6](https://reviewable.io/reviews/materializeinc/materialize/4218#-MHMTYAr1Wz_X5t2Te4L:-MHMTYAr1Wz_X5t2Te4M:b-2z1c4z) ([raw file](https://github.com/materializeinc/materialize/blob/752fbedb3914d1f5a5da7a46581a6b2bb8f5c6b3/src/sql/src/plan/statement.rs#L775)):*
> ```Rust
>             mz_catalog_names.tables {};
>     ", full_projection, string_split_index, schema_name, database_equality, filter, full_order_by);
>     match parse(formatted)?.get(0).unwrap() {
> ```

`parse(formatted)?.into_element()`; should save you the clone below too.
___
*[src/sql/src/plan/statement.rs, line 779 at r6](https://reviewable.io/reviews/materializeinc/materialize/4218#-MHMTUyZ1xQBGq04plZ9:-MHMTUyZ1xQBGq04plZA:b-vk84i5) ([raw file](https://github.com/materializeinc/materialize/blob/752fbedb3914d1f5a5da7a46581a6b2bb8f5c6b3/src/sql/src/plan/statement.rs#L779)):*
> ```Rust
>             handle_computed_select(scx, *query.clone())
>         }
>         _ => unreachable!(), // Known to be valid SQL.
> ```

Comment seems weird. Maybe "Known to be Select statement."?
___
*[src/sql/src/plan/statement.rs, line 781 at r6](https://reviewable.io/reviews/materializeinc/materialize/4218#-MHMZvlu-wK90O3xoEB6:-MHMZvlu-wK90O3xoEB7:buw71ir) ([raw file](https://github.com/materializeinc/materialize/blob/752fbedb3914d1f5a5da7a46581a6b2bb8f5c6b3/src/sql/src/plan/statement.rs#L781)):*
> ```Rust
>         _ => unreachable!(), // Known to be valid SQL.
>     }
> }
> ```

So there is more complexity here than is ideal. The approach of constructing the SQL query and parsing it looks great, but I think we can make it a good bit simpler with a bit of elbow grease.

1. The extra joins to filter for the correct schema re-do the work of `resolve_schema` earlier on in the function. It's a real shame that the schema ID is _right_ there in the catalog, but then we throw it away in the return value of `resolve_schema` and return just the name. If we can instead return the schema ID from that call, we won't need the joins at all, and can just filter for the correct schema ID. Likely to be a lot less work and less error prone than constructing the filters for the database/schema names in the query.
2. Extracting the table name from `mz_catalog_names` is a bit hairy, and also is going to be wrong in the (admittedly esoteric) case of when a name contains a `.` in it. I think the best thing to do is pretend that `mz_catalog_names` does not exist and add a `name` column to the `mz_tables` table. Then you can just pull that name out directly. The philosophy I'd like to advocate is that `mz_catalog_names` is a hack around the fact that we didn't have more structured tables like `mz_databases` and `mz_tables` when it was added, and we could hypothetically remove it in favor of a query that concatenates the individual name components from `mz_databases`/`mz_schemas`/`mz_tables`.
3. Interspersing handling of full and non full makes it hard to visually "see" the SQL query that's generated. Totally makes sense given the amount of complexity involved in the query, but with (1) and (2) solved it's way more reasonable to just have two separate queries for the full/non-full cases, which makes things a lot more readable.

All together, I think the function would ideally look something like this:

```rust
    if extended {
        unsupported!("SHOW EXTENDED TABLES");
    }

    let (database_spec, schema_name) = if let Some(from) = from {
        scx.resolve_schema(from)?
    } else {
        (scx.resolve_default_database()?, "public".to_owned())
    };
    let schema_id = /* ??? */;

    let filter = match filter {
        Some(ShowStatementFilter::Like(like)) => format!("name LIKE {}", Value::String(like)),
        Some(ShowStatementFilter::Where(expr)) => expr.to_string(),
        None => "true".to_owned(),
    };

    let query = if full {
        format!(
            "SELECT name, type
            FROM mz_tables
            JOIN mz_schemas ON mz_tables.schema_id = mz_schemas.schema_id
            WHERE schema_id = {} AND {}
            ORDER BY name, type",
            schema_id, filter
        )
    } else {
        format!(
            "SELECT name FROM mz_tables WHERE schema_id = {} AND {} ORDER BY name",
            schema_id, filter
        )
    };

    match parse(query)?.into_element() {
        Statement::Select(SelectStatement { query, as_of: _ }) => {
            handle_computed_select(scx, *query)
        }
        _ => unreachable!("query known to be select statement"),
    }
```

Warning: untested! And still requires figuring out how to convert a databasespec/schema name into a schema ID—but that should just be a bit of API design/plumbing.

Does that all sound reasonable?

**Comment by JLDLaughlin** [comment]
Yes, totally reasonable! Will have an update shortly.

**Review by benesch — APPROVED** [review]
Looks amazing! Thanks!

> Reviewed 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4218#-:-MHNUsdKCRnMNiyre0i4:biw4xd9)* status: 5 of 10 files reviewed, 4 unresolved discussions (waiting on @benesch and @JLDLaughlin)

**Pull request merged**
