### PR TITLE
adapter: improve OutOfRange errors

### PR DESCRIPTION
**Pull request by ParkMyCar**
### Motivation

Makes progress towards: #16219

This PR updates the Overflow error types for floats, integers, and some time related types, to include a string representation of the value that overflowed. It also updates our sqllogictests to assert on error messages that include the overflow value.

Note: we update the protobufs in a wire compatible way ([slack](https://materializeinc.slack.com/archives/C0246GEHL8N/p1686151841772609)), but the linter complains about them. I'm going to see if I can land this without the linter passing, without breaking main.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - N/a

### CODE REVIEW

**Review by mjibson — APPROVED** [review]

**Comment by ParkMyCar** [comment]
@nrainer-materialize since the protobuf change in this PR is wire compatible, can I merge this change without breaking main? I think it should be fine based on how we check against a common commit, but I wanted to double check :)

**Comment by nrainer-materialize** [comment]
> @nrainer-materialize since the protobuf change in this PR is wire compatible, can I merge this change without breaking `main`? I think it should be fine based on how we check against a common commit, but I wanted to double check :)

I will file an issue at buf.

To ignore it for now, I suggest to add the following configuration snippet 
```
  ignore_only:
    FIELD_WIRE_COMPATIBLE_TYPE:
      - expr/src/
```
to section `breaking` in `src/buf.yaml`.

Unfortunately, it will also catch other field-type compatibility violations but I am not aware of another way allowing a more fine-grained way exclusion. The path also cannot be more specific than `expr/src/`.

Hope this suits you needs!

**Comment by ParkMyCar** [comment]
Already filed 🙂 https://github.com/bufbuild/buf/issues/2167

And sounds good, I'll make that change!

**Review by def- — COMMENTED** [review]
Nightly looked fine: https://buildkite.com/materialize/nightlies/builds/2557#_
Coverage shows some holes, but not sure how easy it is to test all these error spots: https://buildkite.com/materialize/coverage/builds/132

**Pull request merged**
