### PR TITLE
*: fix nightly unused-deps job

### PR DESCRIPTION
**Pull request by danhhz**
### Motivation

   * This PR refactors existing code.

### Tips for reviewer

This depends on https://github.com/est31/cargo-udeps/pull/147 before it will work. How do we feel about `cargo install --git https://github.com/est31/cargo-udeps --locked --rev=b84d478ef3efd7264dba8c15c31a50c6399dc5bb cargo-udeps` in the ci image builder?

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a
  companion cloud PR to account for those changes that is tagged with
  the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Review by benesch — APPROVED** [review]

**Comment by danhhz** [comment]
@benesch any feels on this Q from Tips for Reviewer?

> This depends on https://github.com/est31/cargo-udeps/pull/147 before it will work. How do we feel about `cargo install --git https://github.com/est31/cargo-udeps --locked --rev=b84d478ef3efd7264dba8c15c31a50c6399dc5bb cargo-udeps` in the ci image builder?

**Comment by philip-stoev** [comment]
Consider removing the soft-fail tag for the CI step in ci/nightly/pipeline-template.yaml

**Review by philip-stoev — APPROVED** [review]

**Review by benesch — APPROVED** [review]
I feel good about that! I feel less good about removing the soft fail—the issue that is linked that is causing us to ckntjnje to soft fail this job is still open, no?

**Comment by danhhz** [comment]
Oh, what issue? I had just been assuming soft fail was on because of workspace-hack

> Consider removing the soft-fail tag for the CI step in ci/nightly/pipeline-template.yaml

:+1: I had been planning to if Nikhil was cool with my question above about pointing at an unreleased version on github

**Comment by danhhz** [comment]
TFTRs!

> Oh, what issue? I had just been assuming soft fail was on because of workspace-hack

This turned out to be why we moved unused-deps from pre-push to nightly, where Nikhil was cool with it not being soft-fail: https://github.com/MaterializeInc/materialize/pull/15702#issuecomment-1295258488

> Consider removing the soft-fail tag for the CI step in ci/nightly/pipeline-template.yaml

Done!

**Comment by danhhz** [comment]
Uh oh. Did I break the ci builder image?

```
$ cargo nextest run --profile=ci
--
  | error: no such command: `nextest`
  |  
  | Did you mean `test`?
```

**Comment by danhhz** [comment]
Sure did 🤦

**Pull request merged**
