### PR TITLE
stash: Delete old migrations introduced <= v0.59

### PR DESCRIPTION
**Pull request by ParkMyCar**
This PR bumps the min supported stash version and deletes all of the migrations and protobuf snapshots that were introduced in v0.59 or earlier. Today we're on v0.64.

### Motivation

Deleting old migrations de-cluters our codebase, but also has meaningful impact on compile times of the `mz-stash` crate, as there are less protobuf files that need to be generated.

Build times of `mz-stash`
* `main`: 96 seconds
* this pr: 68 seconds

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - N/a

### CODE REVIEW

**Review by jkosh44 — APPROVED** [review]
LGTM

**Comment by philip-stoev** [comment]
@ParkMyCar I need to run the upgrade-related parts of Nightly first.

**Review by philip-stoev — APPROVED** [review]
I think the CI is happy, so this is good to go. Thank you!

**Comment by ParkMyCar** [comment]
Fantastic, thanks @philip-stoev!

**Pull request merged**
