### PR TITLE
coord: err instead of panic when we have a negative multiplicity in constant result

### PR DESCRIPTION
**Pull request by prcastro**
Solves #6188

### CODE REVIEW

**Comment by frankmcsherry** [comment]
Hello! Thanks for the contribution. We have to kick off the CI on our side (to prevent crypto mining cleverness), but we'll try and get on that (some folks are out for the long weekend). The change looks solid at first glance, but the question about type of error is a good one. I'll try and route it to the folks with strong opinions.

**Comment by prcastro** [comment]
@frankmcsherry any news here?

**Comment by frankmcsherry** [comment]
Sorry for dropping the ball on this. I've pinged the right person to take a formal look, but lgtm (modulo starting the CI which idk how to do T.T).

**Comment by mjibson** [comment]
Need a newline in the test file. Also can you rebase and squash these into a single commit?

**Comment by mjibson** [comment]
I pushed the above changes to your branch.

**Review by mjibson — APPROVED** [review]

**Pull request merged**
