### PR TITLE
[DNR] sql: use default cluster for sources, sinks if one not specified

### PR DESCRIPTION
**Pull request by sploiselle**
### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by sploiselle** [comment]
@MaterializeInc/testing Could you all PTAL at this [Feature benchmark (Kafka only) failure](https://buildkite.com/materialize/tests/builds/71839#018c9cc4-73b6-427f-a82d-0d75de5c8452)? Most likely the cause of this is that we're creating the source on the default cluster as of this PR (rather than its own cluster). We can solve this simply by just creating a new cluster for the sources to run on, but I wasn't sure the best way to propagate a size parameter down to the benchmark. Do you all have suggestions/bandwidth to help out with this?

**Comment by def-** [comment]
Let me try to fix it.

**Comment by def-** [comment]
Now the test error is fixed, but it shows a memory regression caused by this PR. In turn the runtime went down though, so not sure if we want to accept this?

**Comment by def-** [comment]
Done, it's green now: https://buildkite.com/materialize/tests/builds/71893#018cabc5-d32b-418c-85df-d28d053c30e8
Also triggered nightly, expecting potential new failures: https://buildkite.com/materialize/nightlies/builds/5729

**Pull request closed without merging**
