### PR TITLE
sql: Add unsigned int types

### PR DESCRIPTION
**Pull request by jkosh44**
This commit adds 16-bit, 32-bit, and 64-bit unsigned integer types to
Materialize. In addition it also adds various casts to and from the
unsigned int types.

The binary format of these types is big endian, which is the same as
every other numeric type. These types have separate OIDs from the
signed integer types so psql and other drivers don't confuse these for
signed integers.

No arithmetic operators are added for unsigned integers in this commit.
Those can be added in a follow up commit.

Works towards resolving #7629

### Motivation
This PR adds a known-desirable feature.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-protobuf` label.
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - N/A

### CODE REVIEW

**Comment by benesch** [comment]
Woohoo! I hope this isn't too much of a hassle, but IMO let's not add the goofy SQL standard names for these types (`biguint`, `smalluint`, `uinteger`). I think better just to stick with the PostgreSQL style names (`uint2`, `uint4`, `uint8`). That matches pguint AFAICT. Much easier to add aliases later than remove them.

**Comment by jkosh44** [comment]
> Woohoo! I hope this isn't too much of a hassle, but IMO let's not add the goofy SQL standard names for these types (`biguint`, `smalluint`, `uinteger`). I think better just to stick with the PostgreSQL style names (`uint2`, `uint4`, `uint8`). That matches pguint AFAICT. Much easier to add aliases later than remove them.

@benesch Shouldn't be too difficult. What about the aliases `uint` for `uint4`?

**Comment by benesch** [comment]
> @benesch Shouldn't be too difficult. What about the aliases uint for uint4?

I'd err towards leaving that one out too!

**Review by benesch — APPROVED** [review]
This is an epic PR. LGTM.

**Pull request merged**
