### PR TITLE
persist: add compaction service

### PR DESCRIPTION
**Pull request by danhhz**
### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-protobuf` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Comment by danhhz** [comment]
fyi @benesch. still lots to clean up but it's happily as simple as I thought it would be! I'm not planning to use this for anything yet, but suddenly mulling over whether I should just merge it to keep it in our back pocket (and to keep it from rotting)

**Review by benesch — COMMENTED** [review]
Sorry for taking forever to get to this. Neat! Did you want me to look at anything in particular? I took a quick skim and it seemed legit. I don't have strong feelings one way or another on whether to merge this now or later.

**Comment by danhhz** [comment]
ah, sorry, I should be more careful to have clear instructions when I tag you :). was just sharing something cool/getting it on your radar that we've proved the concept if someone starts asking about source ingest throughput being limited

**Comment by benesch** [comment]
Oh no worries at all! Just wanted to make sure this wasn't blocked on me for anything.

**Comment by danhhz** [comment]
Cleaning up old branches

**Pull request closed without merging**
