### PR TITLE
Move Debezium flattening out of special-cased logic and into planning

### PR DESCRIPTION
**Pull request by umanwizard**
Continue the project of moving functionality out of special decoding logic, and into relational expressions. In this diff, we get rid of the special logic that flattens Debezium before and after records into their contained columns.

With this change, bare Kafka/debezium sources produce rows of the shape `(before, after)`, each of which is a nullable record. The plan for converting those into the final stream of data is (for a source with fields 0..=6):

```
%0 =
| Get Bare Source for ? (u3)
| Filter !(isnull(#0))
| Map record_get[0](#0), record_get[1](#0), record_get[2](#0), record_get[3](#0), record_get[4](#0), record_get[5](#0), record_get[6](#0)
| Map -1

%1 =
| Get Bare Source for ? (u3)
| Filter !(isnull(#1))
| Map record_get[0](#1), record_get[1](#1), record_get[2](#1), record_get[3](#1), record_get[4](#1), record_get[5](#1), record_get[6](#1)
| Map 1

%2 =
| Union %0 %1
| FlatMap repeat(#9)
| | demand = (#2..#8)
| Project (#2..#8)

```

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5888)

### CODE REVIEW

**Comment by ruchirK** [comment]
im looking at this rn

**Comment by ruchirK** [comment]
havent looked the code more closely yet but in the plan output 

```
%2 =
| Union %0 %1
| FlatMap repeat(#9)
| | demand = (#2..#8)
| Project (#2..#8)
```

jumps out as strange because there are 10 columns in the input when I would have expected 8 (7 + 1 for diff) from the example (I suspect some kind of metadata) and then the two extra columns at the beginning (0 and 1) seem to get projected out which makes me wonder why they made it down to this operator in the first place. Nothing to fix rn just wanted to make a note of that strangeness for myself

**Comment by umanwizard** [comment]
There are two columns in the input: `before` and `after`. Map adds new columns; it doesn't filter out the old ones, so after the map there are 10 columns (`before`, `after`, 7 data columns, and diff). The project gets rid of the old before and after.

**Comment by ruchirK** [comment]
> There are two columns in the input: `before` and `after`. Map adds new columns; it doesn't filter out the old ones, so after the map there are 10 columns (`before`, `after`, 7 data columns, and diff). The project gets rid of the old before and after.

ah yeah sorry that makes total sense

**Review by ruchirK — APPROVED** [review]
I think this all seems reasonable to me! sorry again for delays in reviewing

**Pull request merged**
