### PR TITLE
[coord] Determine only valid timestamps

### PR DESCRIPTION
**Pull request by frankmcsherry**
This PR changes the behavior of `determine_timestamp` on `PeekWhen::Immediately` to identify query timestamps that will not pass the validity check, and to advance the timestamp to one that will pass. This should have the effect of turning error messages about invalid timestamps into query delays (the query will be executed, but at a later logical timestamp than otherwise proposed). It should have no effect on timestamps that would have been valid.

Noteworthy: this may advance timestamps chosen by `self.get_read_ts()` so as to preserve linearizability. In principle this shouldn't be a problem, as the query infrastructure is clear about the times at which a system-involved query executed. In practice, we are relying on something about the order in which we return results to the client session, which may or may not otherwise be controlled by the query timestamp. If this change does break that behavior, we might want to hoist the requirements in to some place other than this method, which doesn't understand too much about per-session pgwire guarantees.

cc @mjibson, @justinj

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4467)

### CODE REVIEW

**Review by benesch — APPROVED** [review]
This seems reasonable enough to me!

**Comment by benesch** [comment]
This would fix #3983, right?

**Review by justinj — COMMENTED** [review]
Checking my understanding: this doesn't need to ratchet up `read_lower_bound` because by the time any such query actually returns to the client, any timestamp that gets picked afterwards will be in advance of the chosen timestamp?

LGTM! Perhaps with this change we should track "time spent waiting for data" as a metric (if we do not already)?

> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4467#-:-MJSnVYX4YrrUoEjGCq9:b-gfwcoj)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by frankmcsherry** [comment]
I think probably yes on fixing #3983. There are still cases we could see the message. But, I think they would start to be darker corners, like when someone does `AS OF` or if there are no valid times to pick.

**Comment by frankmcsherry** [comment]
> Checking my understanding: this doesn't need to ratchet up read_lower_bound because by the time any such query actually returns to the client, any timestamp that gets picked afterwards will be in advance of the chosen timestamp?

I'm not certain that it doesn't need to, but if "it does need to" then I think we should probably hoist the functionality up and out of this method. My hope was that when picking a later time the session is blocked until that time passes, which has the effect of awaiting the rachet, if not effecting it directly.

> LGTM! Perhaps with this change we should track "time spent waiting for data" as a metric (if we do not already)?

We do have some peek latency stats, as well as a table containing dataflow peeks that are pending at any time.

**Review by mjibson — COMMENTED** [review]
- If a wait must occur, what is the thing that does the waiting?
- If we do wait until the `since` time, is there a guarantee that that `since` is still valid? Like, could it have been advanced (or whatever the verb is) to some other time?
- Is it possible for a future since to be chosen for this query and then a later query (in the same session) chooses a more recent since for some other query and so results are returned out-of-order?

**Comment by benesch** [comment]
> > Checking my understanding: this doesn't need to ratchet up read_lower_bound because by the time any such query actually returns to the client, any timestamp that gets picked afterwards will be in advance of the chosen timestamp?
> 
> I'm not certain that it doesn't need to, but if "it does need to" then I think we should probably hoist the functionality up and out of this method. My hope was that when picking a later time the session is blocked until that time passes, which has the effect of awaiting the rachet, if not effecting it directly.

I had the same question and came to the same conclusion, so seems like a pretty decent theory.

**Comment by frankmcsherry** [comment]
> If a wait must occur, what is the thing that does the waiting?

The waiting happens in the `dataflow` part of the world, where a delayed query timestamp means that the `Peek` request will linger longer than it would have otherwise. None of this is "waiting" in the sense of blocking; it just pushes back the moment until the dataflow layer responds with a "here are your results" message.

> If we do wait until the since time, is there a guarantee that that since is still valid? Like, could it have been advanced (or whatever the verb is) to some other time?

It should be ok, under the assumptions that 1. the coordinator provides instructions in a total order to the dataflow layer, and 2. that having determined a timestamp the coordinator immediately issues the query to the dataflow layer before issuing a "feel free to compact an arrangement" message. In the dataflow side, when a query lands with a specific timestamp the dataflow layer grabs a handle to the arrangement that ensures that compaction does not happen past the query timestamp.

> Is it possible for a future since to be chosen for this query and then a later query (in the same session) chooses a more recent since for some other query and so results are returned out-of-order?

No clue! In general yes this could happen, but in practice I think the session blocks awaiting the query results. We may end up in a state where we want a more expressive vocabulary for what times are ok. We probably don't want to forcibly ratchet up the system timestamp (one fix) because that has a potential negative effect on other users. We could imagine wanting a session-local timestamp that we ensure only goes up, and that we maybe have a `PeekWhen::AtLeast(lower_bound)` variant.

**Review by mjibson — APPROVED** [review]
After this change I didn't see anymore timestamp errors on the memory page. LGTM.

**Pull request merged**
