### PR TITLE
adapter: Prevent dangling refs in default privs

### LINKED ISSUE #20721: adapter: Default privileges may contain dangling references to deleted databases and schemas
### What version of Materialize are you using?

v0.62.0-dev

### What is the issue?

Default privileges contain optional references to databases and schemas. When we drop a database or schema, we don't check to see if there's a reference to that database or schema in the default privileges tables. This allows default privileges to contain dangling references to dropped databases and schemas.

### PR DESCRIPTION
**Pull request by jkosh44**
Default privileges contain optional references to databases and schemas. Previously, when we dropped a database or schema, we didn't check to see if there's a reference to that database or schema in the default privileges tables. That allows default privileges to contain dangling references to dropped databases and schemas.

This commit updates the DROP DATABASE and DROP SCHEMA command to revoke default privileges if they contain references to the dropped database or schema.

Fixes #20721

### Motivation
This PR fixes a recognized bug.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [X] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [X] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - Fix bug to prevent and remove dangling references in default privileges

### CODE REVIEW

**Comment by jkosh44** [comment]
This needs a migration to remove existing dangling references and the tests need to be updated.

**Comment by jkosh44** [comment]
CC @benesch

**Review by benesch — COMMENTED** [review]
Wow, you turned this around real quick. I skimmed and didn't see any cause for concern, but leaving explicit approval to someone on the team who's more familiar with this code.

**Comment by jkosh44** [comment]
I split this into two commits, one that prevents dangling references and one the removes any existing dangling references via a stash migration.

**Review by ParkMyCar — APPROVED** [review]

**Comment by ParkMyCar** [comment]
Thanks for splitting the PR into two commits!

**Pull request merged**
