### PR TITLE
sql+dataflow: sketch supporting sum_numeric

### PR DESCRIPTION
**Pull request by sploiselle**
To support aggregate functions for the new `rust-dec`-backed numeric type, we'd ideally like to aggregate into a non-integer value, which is something we haven't done for another type.

We didn't need this for the current `Decimal` type because it decomposes neatly into an `i128:` all of its values are guaranteed to be of the same scale. However, `Decimal128` (i.e. the `rust-dec`-powered numeric type) supports operations across heterogeneously scaled values natively, so does not naturally decompose into an integer value.

So, ideally, [this `match` arm that produces `datum_aggr_values`](https://github.com/MaterializeInc/materialize/compare/main...sploiselle:rdn-sum-agg#diff-1d8a1661e2a84d234a135ddf4fca18e32c15394674892cb74cbc877a7d91d36eR1127-R1140) would instead have a first tuple value of the `Decimal128`, rather than `i128` in the case of aggregate functions called on numeric values.

Of course, this isn't strictly necessary because we could continue doing what we do for decimals and homogeneously scale inputs––seems like unnecessary overhead that throws out a lot of `rust-dec`'s value, though, so wanted to see if there was a reasonable alternative.

Glad to set up a more formal chat, but figured some code was a good starting to triangulate on.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/6145)

### CODE REVIEW

**Comment by frankmcsherry** [comment]
I'm not sure what `coefficient()` does, but could you sketch how round-tripping `numeric` data through an `i128` can e.g. preserve precision below the decimal point?

**Comment by benesch** [comment]
Thanks for getting this on the table, Sean! The specific thing I had in mind here is that we'd allocate one rather massive arbitrary-precision [`Decimal`](https://docs.rs/dec/0.3.3/dec/struct.Decimal.html) for associative and commutative accumulation.

Using a `Decimal128` as the accumulator will be problematic because it is not associative/commutative once it goes inexact.

**Comment by benesch** [comment]
cc @mjibson @umanwizard who have both had decimal thoughts. Does anyone see a problem with the above proposal?

**Comment by benesch** [comment]
Oof, there's another thorny issue here, which is what to do if the numeric value is `NaN` or `Infinity`.

**Comment by sploiselle** [comment]
I believe we can treat either of those things are roughly equivalent to having overflowed. Something I'm overlooking here, @benesch?

**Comment by frankmcsherry** [comment]
It would make it non-invertible. If someone introduces a NaN into a sum and then retracts it, it will not correct itself.

**Comment by benesch** [comment]
I guess we handle those like `NULL` and accumulate them separately. I wonder what happens presently if you sum an f64 column which contains infinity/NaN.

**Comment by frankmcsherry** [comment]
It uses your favorite error-resistant Rust keyword, so I'm sure it's fine!
```
                    Datum::Float32(f) => ((f64::from(*f) * float_scale) as i128, 1),
                    Datum::Float64(f) => ((*f * float_scale) as i128, 1),
```

**Comment by benesch** [comment]
Yeah what on earth is `f64::NAN as i128`?

**Comment by benesch** [comment]
Ah, right, zero. Great. https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=487c44c021d68ac48d9540a8631bc132

**Comment by benesch** [comment]
Infinity, on the other hand, is `170141183460469231731687303715884105727`.

**Comment by frankmcsherry** [comment]
Just another random comment. Not sure what it means but: if you end up using an APD that allocates for the accumulation, it will certainly churn the allocator in accumulation, and remain as part of the accumulated/maintained state. In that case, it may be that the cost of APD is already being borne, even with lower-precision decimals in columns.

**Comment by umanwizard** [comment]
> Infinity, on the other hand, is 170141183460469231731687303715884105727.

seems legit

**Comment by ruchirK** [comment]
I think the proposal to use a `Decimal` for the accumulation sounds reasonable enough. I don't have enough context on the implementation to say whether the extra allocations (if there are any during accumulation) will be a big deal or not and I also don't have any good thoughts on how to handle infinity / NaNs

 I think in order to make this work in the existing reduce rendering code you'll have to move from a vec of i128s -> a vec of enums as the diff type. That could be a larger cost for reduce reductions -- we might also want to explore factoring numeric sums into their own separate dataflow to mitigate that.
 
 Beyond that, I'm not entirely sure how to be more helpful for this pr. Let me know if there's anything else I can do.

**Review by ruchirK — APPROVED** [review]

**Comment by ruchirK** [comment]
I would like to understand the error associated with using a 128 bit decimal a bit more though -- is there something I can read for that?

**Comment by sploiselle** [comment]
From @benesch:

> * Switch to using Decimal<13> as the type in repr::Datum::Decimal. That’ll allow for 39 digits of precision. So it won’t feel like we’re going backwards.
> * Figure out some compressed encoding scheme in Row that uses less space than Decimal<13> does. Unpack and pack into this compressed scheme in the natural place.
> * Set the emin and emax in the context to 38 and -38 or somesuch. That’ll place a strict lower and upper bound on the minimum and maximum exponents that can be stored in the decimal.
> * Accumulate into Decimal<26> or something so large that overflow basically “can’t happen” because you’d need to sum up so many maximum-valued `Decimal<13>`s.

The general idea here is to use the always-allocating decimal type with 13 declets, i.e. 39 digits of precision and enforcing the numbers themselves be within those bounds.

As for accumulating values, we'll use another very large allocating decimal and essentially make overflowing it very challenging to do..

Also from @benesch:

> There’s still the issue of handling Infinity and NaN, but you can just sum those up separately, and then at the end do some logic like:

```
if nan_count > 0 || (pos_inf_count > 0 && neg_inf_count > 0) {
    NaN
} else if pos_inf_count > 0 {
    Infinity
} else if neg_inf_count > 0 {
    -Infinity
} else {
    actual_accumulation
}
```

@frankmcsherry What do you think of this approach? Seems like it's good for keeping the same amount of precision, sensibly handles NaN/Infinity in a way that's invertible. Any other lingering concerns?

**Comment by sploiselle** [comment]
closing in favor of #6283

**Pull request closed without merging**
