### PR TITLE
feature-benchmark: fix message filtering, clusterd memory computation, ReplicaExpiration scenario

### PR DESCRIPTION
**Pull request by def-**
Seen failing in https://buildkite.com/materialize/release-qualification/builds/627#01927989-33ea-448b-af26-6ef13de7d27e

Verifying: https://buildkite.com/materialize/release-qualification/builds/628

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

**Review by nrainer-materialize — APPROVED** [review]

**Comment by antiguru** [comment]
I think the proper fix here is to store very little content in the table and use a view to explode the data. The problem with tables is that updates have to traverse through environmentd, which includes deletes. (*I hope this is not outdated!)

**Comment by def-** [comment]
I was looking into why the measurements made no sense and found out that messages and memory_clusterd measurements were entirely broken in feature-benchmark, fixed now, will verify that everything works.

**Comment by def-** [comment]
There is now a very clear improvement visible:
```
NAME                                | TYPE            |      THIS       |      OTHER      |  UNIT  | THRESHOLD  |  Regression?  | 'THIS' is
--------------------------------------------------------------------------------------------------------------------------------------------------------
ReplicaExpiration                   | wallclock       |          15.665 |          15.930 |   s    |    10%     |      no       | better:  1.7% faster
ReplicaExpiration                   | messages        |    25000168.000 |    32000176.000 |   #    |    20%     |      no       | better: 21.9% less
ReplicaExpiration                   | memory_mz       |         662.994 |         679.588 |   MB   |    20%     |      no       | better:  2.4% less
ReplicaExpiration                   | memory_clusterd |        1376.152 |        1917.839 |   MB   |    20%     |      no       | better: 28.2% less
```

**Review by nrainer-materialize — APPROVED** [review]

**Comment by antiguru** [comment]
Oh wow, thank you for fixing this!

**Comment by def-** [comment]
I didn't manage to fix the messages measurement. In some tests the messages seem to get reset to 0, in some not. I think what we need to do is measure the messages before the part to be tested (`/* A */`), and then subtract that from the part after. I'll try it in a separate PR.

**Pull request merged**
