### PR TITLE
storage/purification: Correctly error on ALTER SOURCE .. DROP SUBSOURCE statements for unsupported source types

### PR DESCRIPTION
**Pull request by rjobanp**
### Motivation

  * This PR fixes a recognized bug. Fixes https://github.com/MaterializeInc/materialize/issues/25826 and Fixes https://github.com/MaterializeInc/materialize/issues/25882

### Tips for reviewer

Context for this PR is here https://github.com/MaterializeInc/materialize/issues/25826#issuecomment-1988816031

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by nrainer-materialize** [comment]
Thank you!

I triggered a slim nightly build: https://buildkite.com/materialize/nightlies/builds/6850

**Review by nrainer-materialize — APPROVED** [review]

**Comment by rjobanp** [comment]
@nrainer-materialize the mysql-cdc-resumption test is now failing because of this DROP SUBSOURCE: https://github.com/MaterializeInc/materialize/blob/bf2dbb0c3804405e06649dd8730122f33f54216f/test/mysql-cdc-resumption/alter-mz.td#L10
but it looks like that `alter-mz` testdrive file is run in several places within `mysql-cdc-resumption`. Should I just change it to a `DROP SOURCE`?

**Comment by nrainer-materialize** [comment]
> @nrainer-materialize the mysql-cdc-resumption test is now failing because of this DROP SUBSOURCE:
> 
> https://github.com/MaterializeInc/materialize/blob/bf2dbb0c3804405e06649dd8730122f33f54216f/test/mysql-cdc-resumption/alter-mz.td#L10
> 
> but it looks like that `alter-mz` testdrive file is run in several places within `mysql-cdc-resumption`. Should I just change it to a `DROP SOURCE`?

Fine with me

**Review by guswynn — APPROVED** [review]
v nice!

**Pull request merged**
