### PR TITLE
Trigger pod replacement by hash annotation

### PR DESCRIPTION
**Pull request by alex-hunt-materialize**
Kubernetes does not always replace pods when a StatefulSet changes.

Adds an annotation to the PodTemplateSpec containing the sha256 hash of
that PodTemplateSpec. After applying the Statefulset, we get the pod.
If the pod exists but the annotation doesn't match, we delete the pod to
trigger K8S to recreate it.

### Motivation

  * This PR fixes a recognized bug.

Resolves https://github.com/MaterializeInc/cloud/issues/2635

### Tips for reviewer

Same idea as https://github.com/MaterializeInc/cloud/pull/2647

### Testing

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.

### CODE REVIEW

**Comment by alex-hunt-materialize** [comment]
@benesch What's the best way to test this?

**Comment by benesch** [comment]
Ah, you'll probably want to run [`bin/cluster-dev`], which is a little script that will build a `materialized` docker image locally and deploy it as a StatefulSet to minikube with the right flags. I recommend running `bin/cluster-reset` first to blow away your state from MaterializeInc/cloud. You could run `bin/cluster-dev` twice, editing it to pass in a different `dataflowd` image in between, and ensure that the pod is properly recreated. 

Sorry, been meaning to write docs for `cluster-dev`, and also wire up some proper integration tests. There's only the PR description that introduced them (#11339) for now.

**Comment by benesch** [comment]
The code LGTM, btw, ty!

**Comment by alex-hunt-materialize** [comment]
@benesch Tested and seems to work with my latest change.

**Pull request merged**
