### PR TITLE
ci: testdrive: fail on empty input and log number of commands

### PR DESCRIPTION
**Pull request by nrainer-materialize**
### Motivation

* Fail execution if there is no input provided.
* Log number of commands to be executed.

### CODE REVIEW

**Comment by philip-stoev** [comment]
I think this is an important safeguard. I hope all the CI errors are fixable, please ping me if any are giving you trouble.

**Review by def- — APPROVED** [review]
I probably used some conditonally empty td files in platform-checks

**Comment by nrainer-materialize** [comment]
Yeah, there are some empty and commented-out files. Including:
* `test/upsert/rehydration/04-reset.td`
* `test/testdrive/github-5668.td`
* `test/legacy-upgrade/create-in-any_version-noop.td`
* `misc/python/materialize/checks/roles.py`

I think I will introduce a `pass` command for these.

**Comment by philip-stoev** [comment]
You can use `SELECT 1` as a filler.

**Pull request merged**
