### PR TITLE
persist: cache len on SpineBatch::Fueled

### PR DESCRIPTION
**Pull request by danhhz**
This gets called in Spine::tidy_layers, which gets called in of Spine::introduce_batch. When we rehydrate a Spine from persist state, introduce_batch is called for each of the HollowBatches on the state. Combined, this resulted in an unintended and unnecessary repeated re-computation of this len. (I haven't thought through exactly, but it's possible this was `O(num_batches^2)` or something equally bad.)

This was significant enough to show up as the major factor during a high CPU event on prod. It's easy enough to cache this len, so do it.

image

### Motivation

  * This PR fixes a recognized bug.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Review by frankmcsherry — APPROVED** [review]
LGTM!

**Comment by danhhz** [comment]
TFTR!

**Review by pH14 — APPROVED** [review]
LGTM!

I think I'm slightly partial to making a fn for this to put the logic in one place, but this seems fine.

```rust
impl<T> SpineBatch<T> {
    fn fueled(desc: Description<T>, parts: Vec<HollowBatch<T>>) -> Self {
        SpineBatch::Fueled { desc, parts, len: parts.iter().map(|x| x.len).sum() }
    }
}
```

**Comment by danhhz** [comment]
> I think I'm slightly partial to making a fn for this to put the logic in one place, but this seems fine.
> 
```rust
impl<T> SpineBatch<T> {
    fn fueled(desc: Description<T>, parts: Vec<HollowBatch<T>>) -> Self {
        SpineBatch::Fueled { desc, parts, len: parts.iter().map(|x| x.len).sum() }
    }
}
```

oh whoops, had this marked for auto-merge but didn't catch it in time. I considered that, but given that everything here is currently in the same module, nothing (like a compile error) really directs anyone to use that method over manually constructing `SpineBatch::Fueled{ .. }`. I'd be for it if we moved SpineBatch down into a submodule, but that doesn't quite seem worth it to me

**Pull request merged**
