### PR TITLE
Be robust to null values in print_archive.py

### PR DESCRIPTION
**Pull request by umanwizard**
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5239)

### CODE REVIEW

**Comment by cirego** [comment]
I have a question about this! I originally had logic to handle the `null` value case but I don't understand why it's *okay* for a key or value to be `null`. What does that mean in Debezium land?

**Comment by umanwizard** [comment]
We ignore null values in Debezium mode. Debezium emits them right after a delete, to make compaction work properly.

Search "tombstone" on [this page](https://debezium.io/documentation/reference/configuration/event-flattening.html) for more info.

**Comment by cirego** [comment]
> We ignore null values in Debezium mode. Debezium emits them right after a delete, to make compaction work properly.
> 
> Search "tombstone" on [this page](https://debezium.io/documentation/reference/configuration/event-flattening.html) for more info.

Oh, those are tombstone records! Got it!

**Review by cirego — APPROVED** [review]

**Comment by cirego** [comment]
Okay, so tombstone records explains why the value can be null, but what does it mean for the key to be null?

**Comment by umanwizard** [comment]
To be clear I am not sure what it would mean for the key to be null, but I included that just in case. Keys _can_ be null in Kafka for sure, regardless of whether Debezium emits them, so this script should handle that case.

**Comment by cirego** [comment]
I did have logic for both keys and values because there are keys with null values.

**Pull request merged**
