### PR TITLE
.github: update epic issue template

### PR DESCRIPTION
**Pull request by uce**
Our existing epic template is pretty heavyweight. It has been more aspirational than operational. This change aims to make it more lightweight while aligning it with the recent changes to project management.

The overall template is modeled after the following examples:
- https://github.com/MaterializeInc/materialize/issues/17209
- https://github.com/MaterializeInc/materialize/issues/17413

The decision log section is new. The rest is mainly a restructuring and consolidation. Where possible, the template tries to be prescriptive.

The second commit adds a new "problem" template that is supposed to work well for the individual work items that make up an epic. It asks to briefly outline the problem being solved and the intended solution. This too has been modeled after the above examples. The name "problem" is not a slam dunk and I'm open to suggestions. I'd also be happy to drop the second commit in case it is controversial/distracting.

I deliberately used the old-school issue template format instead of the newer forms-based template, because I find them _too_ structured. That's a personal preference and I'm happy to change it if folks feel strongly about using a forms-based template (as we did before).

### CODE REVIEW

**Review by ggnall — COMMENTED** [review]
Looks great. 

Can we make sure these templates are available and consistent on all repos?

Agree that the the form-based approach is clunky.

**Comment by ggnall** [comment]
This looks like a good standard/default issue for anything that doesn't fit into the other category templates. I'm seeing these as standalone issues or sub-tasks.
> The name "problem" is not a slam dunk and I'm open to suggestions. I'd also be happy to drop the second commit in case it is controversial/distracting.

**Comment by uce** [comment]
> Can we make sure these templates are available and consistent on all repos?

Yes, will do once this is merged.

> This looks like a good standard/default issue for anything that doesn't fit into the other category templates.

Yeah, exactly. Let me know if you have a better name than "problem".

**Review by benesch — APPROVED** [review]
This seems like a great start. Thank you, Ufuk!

**Pull request merged**
