### PR TITLE
feature-benchmark: various updates for platform

### PR DESCRIPTION
**Pull request by mjibson**
Disable `ENVELOPE UPSERT` tests since that has been removed. Use new `CONNECTION` syntax for kafka.

### Motivation

  * This PR fixes a previously unreported bug.

### Testing

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.

### Backward compatibility

- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-protobuf` label.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - n/a

### CODE REVIEW

**Review by philip-stoev — APPROVED** [review]
Thank you!

**Comment by philip-stoev** [comment]
Huh actually, I can see no indication that ENVELOPE UPSERT is being removed from the prouduct?

**Review by philip-stoev — CHANGES_REQUESTED** [review]
So I confirmed that envelope upsert is here to stay. So those scenarios should not be  disabled

**Comment by mjibson** [comment]
Hmm so when I run `KafkaUpsert`:

```
> CREATE MATERIALIZED SOURCE s1 FROM KAFKA CONNECTION s1_conn TOPIC 'testdrive-kafka-upsert-1658016330' FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://work:8081/' ENVELOPE UPSERT

error: executing query failed: db error: ERROR: ENVELOPE UPSERT is unsupported: ERROR: ENVELOPE UPSERT is unsupported
```

I saw some commits that I thought were about this and apparently made the wrong assumption. I am very confused by this error message in that case!

**Comment by mjibson** [comment]
Updated to just have the connector changes.

**Comment by philip-stoev** [comment]
You need to run with --unsafe to get that functionality. Not sure how to do that on the cloud though.

**Comment by mjibson** [comment]
You can't (and also we probably shouldn't even let ourselves do it).

**Pull request merged**
