### PR TITLE
transform: avoid crash in InlineLet transform with very deep dataflows

### LINKED ISSUE #8387: Crash when creating view with subqueries
### What version of Materialize are you using?

```bash
$ materialized -v
materialized v0.9.5-dev (f500d4e13)
```

### How did you install Materialize?

* [ ] Docker image
* [ ] Linux release tarball
* [x] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [ ] Built from source
* [ ] Materialize Cloud

### What was the issue?
Trying to create a generated materialized view which primarily consists of sub-queries for columns. In my test-scenario this is working for <= 96 columns. Any more columns in the DDL cause materialize to crash. 

All subqueries follow a similar pattern of filtering by a timestamp, and a variable amount of jsonb entries in the source view. Pseudocode-example of such a subquery:
```sql
(SELECT max(timestamp_col)
   FROM events
  WHERE (payload->>'type' = 'foo1'
     AND category_id = origins.category_id
     AND origin_id = origins.id
     AND mz_logical_timestamp() BETWEEN (1000 * CAST(extract(epoch from timestamp_col) AS numeric)) AND (1000 * CAST(extract(epoch from timestamp_col + interval '90' days) AS numeric))
  )
) AS quz__foo1_types__max_time__90days
```
### Please attach any applicable log files.
`mzdata/materialized.log` didn't contain a stacktrace for some reason. Here is one from gdb:
[gdb.txt](https://github.com/MaterializeInc/materialize/files/7212159/gdb.txt)

### PR DESCRIPTION
**Pull request by asenac**
### Motivation

This PR fixes a recognized bug. Fixes #8387

### Description

`RelationCSE` transform replaces almost every single node in the graph with a Let operator, which leads to a long list of chained `Let`s with that many subqueries. It relies on `InlineLet` transform to clean up after it. For that cleanup, `InlineLet` unnecessarily uses `take_safely` method, which performs a recursive call for computing the type of the expression being taken.

### Checklist

- [x] This PR has adequate test coverage.
- [ ] This PR adds a release note for any user-facing behavior changes.

### CODE REVIEW

**Review by frankmcsherry — APPROVED** [review]
This looks good to me, except that I didn't look at the 5kloc test file.

**Comment by wangandi** [comment]
Would it be possible to replace the result of the 5kloc test with "<n> values hashing to <hash>" to save room? See https://github.com/MaterializeInc/materialize/blob/main/test/sqllogictest/special/memory.slt for an example.

Also, can we add a comment on the 5kloc test on what the passing criterion is? Like is it just that Materialize should not crash? Or that the plan should not exceed N nodes?

**Comment by asenac** [comment]
> Would it be possible to replace the result of the 5kloc test with " values hashing to " to save room? See https://github.com/MaterializeInc/materialize/blob/main/test/sqllogictest/special/memory.slt for an example.

Good point. Maintaining that is going to be a bit painful.

> Also, can we add a comment on the 5kloc test on what the passing criterion is? Like is it just that Materialize should not crash? Or that the plan should not exceed N nodes?

Good point! I was happy with it not leading to a crash. I guess the passing criteria would be: 1. no crashes, 2. no fixpoint issues

**Comment by philip-stoev** [comment]
@asenac  re the 5kloc test, another approach that you can consider is to do CREATE MATERIALIZED VIEW out of the SELECT followed by a SELECT COUNT(*) = 0 FROM ... = true query. This way the entire EXPLAIN will not be recorded in the .slt file but hopefully the same code paths will be exercised + maybe a bit more(?)

**Review by philip-stoev — APPROVED** [review]
Thank you for the test. Due to a couple of recent bugs and questions, I already have a task open to explore the scalability of the entire optimizer+dataflow pipeline across various dimensions. https://github.com/MaterializeInc/materialize/issues/8325 . I hope to work on it really soon.

**Comment by asenac** [comment]
One of my intentions with the test was to also exercise the EXPLAIN code with such a deep query. I guess Andi's suggestion still allows us to exercise that code, but I foresee the hash value changing too often. I wonder if there is a way of exercising EXPLAIN but discarding its output in SLT.

**Comment by asenac** [comment]
If nobody objects, I'll go with the hashing suggestion. If it becomes too painful to maintain, we can always add an option to execute but ignore the results of the query, as long as it didn't return an error.

**Comment by asenac** [comment]
> If nobody objects, I'll go with the hashing suggestion. If it becomes too painful to maintain, we can always add an option to execute but ignore the results of the query, as long as it didn't return an error.

@uce pointed out that we can just ignore the plan while still exercise the explain code by using `statement` command. So I'll go with that.

**Pull request merged**
