### PR TITLE
test analytics: index benchmark results per day

### PR DESCRIPTION
**Pull request by nrainer-materialize**
Any concerns? (The view definition is directly above the change.)

### CODE REVIEW

**Review by def- — COMMENTED** [review]
Why do we need the mv vs just an index?

**Comment by def-** [comment]
Damn, rbac is a bit annoying here. Isn't there a way to give someone admin permissions for an object?

**Review by def- — APPROVED** [review]

**Comment by nrainer-materialize** [comment]
> Damn, rbac is a bit annoying here. Isn't there a way to give someone admin permissions for an object?

Can we get this also fixed by setting the default permissions for the entire schema?

**Comment by jkosh44** [comment]
> I don't think so, but maybe @jkosh44 knows.

Unfortunately, you need to be the owner of an object to create an index on it (https://materialize.com/docs/sql/create-index/#privileges), which can't be controlled by default privileges. You could `GRANT owner_role TO some_other_role`, if you want `some_other_role` to be able to create indexes.

**Comment by def-** [comment]
That works for us. @nrainer-materialize I guess updating our .sql files to grant ownership to both of us would work.

**Pull request merged**
