### PR TITLE
Disable telemetry in CI via a new MZ_DISABLE_TELEMETRY env var

### PR DESCRIPTION
**Pull request by quodlibetor**
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5278)

### CODE REVIEW

**Comment by benesch** [comment]
Hrm. I'm not super excited about adding more environment variables because it makes it much harder to track down what configuration is in effect. I guess we will probably need to add them for end users who demand them, but I ... think we should endeavor to not use them in our CI configurations? In particular it's usually impossible to detect typos/bad values with environment variables.

It also doesn't seem to me like the environment variable will have the intended effect in many of these configurations? SLT doesn't actually boot materialized for example, so having the env var set there is misleading IMO.

I'm assuming the ask here is for a pretty foolproof solution to preventing CI from ever reporting telemetry information?

**Comment by benesch** [comment]
One other way of looking at is: should mzcompose _ever_ boot a materialized with telemetry enabled? If you're using mzcompose, that's pretty much a guarantee that you're not running a real cluster.

If the answer to the above is no, then the idea that I've been kicking around is adding special handling for materialized args to mzcompose. A lot of the mzcompose files are really irritating to use right now with `BUILD_MODE=debug` because you have to edit the mzcompose file to pass `--dev` to materialized (aside: I really dislike that feature). But if we add special support for materialized services, then we'd have a nice place to both pass `--disable-telemetry` _and_ automatically add `--dev` to the flags.

**Comment by quodlibetor** [comment]
> I'm not super excited about adding more environment variables because it makes it much harder to track down what configuration is in effect.

Oh I thought we were on the same page that all flags should have env var duals, if we're not then I agree that that makes this a much less obvious change.

> should mzcompose ever boot a materialized with telemetry enabled?

Hm, no, probably not, but I'd also contend that we should encourage all our engineers to set this env var in their shell startup file since we don't want our dev startups to be coloring our telemetry. That use case in particular seems like it needs to be set in env vars.

**Comment by quodlibetor** [comment]
I do agree that adding custom support for `materialized` would be reasonable, but for the specific case of `BUILD_MODE=debug` couldn't you just fix it by doing `BUILD_MODE=debug MZ_DEV=1`, instead of editing the config file? One of the advantages of requiring all parameters to have an env dual is this kind of operational annoyance has workarounds.

> In particular it's usually impossible to detect typos/bad values with environment variables.

One advantage of requiring `MZ_` prefix is is makes it possible to error on incorrect env vars that start with `MZ_` (with an "I know what I'm doing" override, probably.)

**Comment by quodlibetor** [comment]
> I'm assuming the ask here is for a pretty foolproof solution to preventing CI from ever reporting telemetry information?

I was just trying to reduce noise, but yeah pretty foolproof way to reduce internal mz testing from actual use would be nice.

**Comment by awang** [comment]
Feature flags and environment variables are definitely incredibly difficult to maintain, but they do have a huge benefit in allowing for rapid testing / iteration, and allow for non-engineers to apply changes

In general, I think we should bias slightly more on faster iteration, given how much about the product/market/users we are still learning, particularly around components we are likely to rewrite. Ie, refactoring of external interfaces is more likely, while refactoring of sql is less likely.

Unfortunately, I haven't seen a good off-the-shelf solution that allows for env vars while avoiding the engineering complexity. LaunchDarkly is one product, but I think they are oriented towards solving business challenges and not the technical ones described. I've also seen many in-house static analysis tools, which we're a bit early for. Maybe a good intern project :)

**Comment by mjibson** [comment]
Devs shouldn't have to do anything because telemetry is only enabled by default for release builds. I agree that it makes more sense to have mzcompose just disable telemetry by default since that's probably never what we want.

**Comment by quodlibetor** [comment]
> Devs shouldn't have to do anything because telemetry is only enabled by default for release builds.

I run release builds all the time, I'm not sure what the ratio of release to debug is, but I'd guess 20%  or more of my builds are release :-/

@awang
> Unfortunately, I haven't seen a good off-the-shelf solution that allows for env vars while avoiding the engineering complexity.

Are you referring to users *setting* env vars or developers *managing* env vars?

**Comment by benesch** [comment]
> Oh I thought we were on the same page that all flags should have env var duals, if we're not then I agree that that makes this a much less obvious change.

Yeah I grudgingly accept that supporting env var duals is reasonable for the benefit of our users! And we should probably just whip up a PR that exposes all the duals in one shot with a consistent naming scheme.  My concern is specifically with setting Materialize-specific env vars in the pipeline configs, because it results in spooky action at a distance.

> I do agree that adding custom support for `materialized` would be reasonable, but for the specific case of `BUILD_MODE=debug` couldn't you just fix it by doing `BUILD_MODE=debug MZ_DEV=1`, instead of editing the config file? One of the advantages of requiring all parameters to have an env dual is this kind of operational annoyance has workarounds.

Sadly, no, what I'm trying to run is something like

```
BUILD_MODE=debug MZ_DEV=1 ./mzcompose run python 
```

and the env vars don't propagate (for good reason).

> 
> > In particular it's usually impossible to detect typos/bad values with environment variables.
> 
> One advantage of requiring `MZ_` prefix is is makes it possible to error on incorrect env vars that start with `MZ_` (with an "I know what I'm doing" override, probably.)

That's true if we're disciplined about registering all environment variables in one place! Though what you end up with is code that looks awfully similar to command-line argument parsing.

**Comment by quodlibetor** [comment]
>  My concern is specifically with setting Materialize-specific env vars in the pipeline configs, because it results in spooky action at a distance.

Hmm I'm not sure that I feel that env vars are *more* spooky action at a distance than hard-coding a config value in the way that we run materialized. Speaking of hard-coding the way that we run materialiezed, though, it might make sense (irrespective of this) for mzcompose to print all `MZ_*` env vars any time it runs materialized, if it knows that it is running materialized. Honestly I'm not sure if that is more likely to be bug-prone than modifying the `command` of the materialized service as part of mzcompose rewriting, but at least bugs in that would just reduce information, not cause incorrect commands to be run.

> And we should probably just whip up a PR that exposes all the duals in one shot with a consistent naming scheme.

If you're on board with this I'm happy to do it, using either parsopt or switching to something that has support built-in.

> That's true if we're disciplined about registering all environment variables in one place! Though what you end up with is code that looks awfully similar to command-line argument parsing.

Yeah IMO this is best handled in arg-parsing libraries -- [clap supports it](https://docs.rs/clap/2.33.3/clap/struct.Arg.html#method.env), but gumdrop doesn't afaict.

**Comment by benesch** [comment]
Now that I'm looking at this again, I'm pretty sure this approach as-written doesn't actually propagate the `MZ_DISABLE_TELEMETRY` variable down to materialized, right? Since mzcompose is going to strip that var from the materialized container. This is exactly the kind of thing that I worry about with environment variables!

I opened #5300 with a linter that enforces that any service that uses `materialized` also pass the `--disable-telemetry` CLI arg. Let me know what you think!

**Comment by quodlibetor** [comment]
Closing because of the other work being done in this space.

**Pull request closed without merging**
