### PR TITLE
Columnation for `DataflowError`

### PR DESCRIPTION
**Pull request by antiguru**
### Motivation

This PR fixes an unreported issue. Previously `DataflowError` would simply be cloned when storing in columnation regions. This is correct but heap-allocates any referenced data, for example the box serving as the first level of indirection. With this change, we region-allocate all referenced data.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by umanwizard — APPROVED** [review]
It looks sane to me, but I'm not an expert on columnation, so it's up to you if you want to wait for someone else to review too.

**Review by vmarcos — COMMENTED** [review]
This seems fine. I would have some questions regarding documentation / validation:
1. Would it make sense to add a correctness argument / comment to the uses of `unsafe`?
2. Do any of our scenarios in the feature benchmark cover situations where we load the error arrangement with a lot of errors? If not, can we create one?
3. With this change the arrangement sizes for the error arrangement should start being closer to reality, right? Is there any way we could validate and/or write a test for that?

**Review by petrosagg — COMMENTED** [review]
The implementation of the region looks good but this change will require that every time anyone changes `DataflowError` in a non-trivial way they'll have to edit the region implementation accordingly which is very non-trivial. So there is a mental overhead cost here.

Part of the diff is deleting this comment:


> 3. We accept the performance implication of not storing the errors in a region allocator,
>    which should be similar to storing errors in vectors on the heap.

Why is this not true anymore? What motivates this change?

**Comment by teskje** [comment]
> The implementation of the region looks good but this change will require that every time anyone changes DataflowError in a non-trivial way they'll have to edit the region implementation accordingly which is very non-trivial. So there is a mental overhead cost here.

This is true but I think it's worth it to improve our (and user's) visibility into memory usage. This is one of the observability areas we currently struggle with in compute.

I think @vmarcos' suggestions can help with reducing the difficulty of implementing new error variants. In particular:

* Having good `SAFETY` documentation would make it clearer to implementers of new variants what they have to do to ensure that their implementation behaves correctly.
* Having tests would make it possible to catch incorrect implementations (or at least some classes of bugs).

I wonder if we could employ `proptest`s here. I'm thinking along the lines of generating random `DataflowError` instances, putting these into a columnation region, and then checking if they still look/behave the same.

**Comment by antiguru** [comment]
I added documentation and a proptest. Feel free to take another look!

> > We accept the performance implication of not storing the errors in a region allocator,
> > which should be similar to storing errors in vectors on the heap.
>
> Why is this not true anymore?

We've seen a situation in production where an error arrangement had a significant size of multiple GiB that we didn't surface properly.

**Review by vmarcos — APPROVED** [review]
Thanks for additional docs and tests!

**Review by teskje — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
