### PR TITLE
docs/user: document the new source statistics

### PR DESCRIPTION
**Pull request by guswynn**
To merge after: https://github.com/MaterializeInc/materialize/pull/25440

Document the statistics added in https://github.com/MaterializeInc/materialize/pull/25436 and https://github.com/MaterializeInc/materialize/pull/25440

@morsapaes these probably deserve their own top-level page, but this is just a start.

### Motivation

docs

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20240108_source_metrics_2.md
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by guswynn** [comment]
docs lint will be fixed when i rebase on top of https://github.com/MaterializeInc/materialize/pull/25440 being merged

**Comment by morsapaes** [comment]
Marked the `_raw` relations as undocumented, since what we want to expose to users is really the aggregated views. Once this work lands in the console, we can yank the explainers out into the reference documentation of each source, or the "Troubleshooting" guide for ingestion. I'll keep that in mind. Thank you, @guswynn!

**Comment by guswynn** [comment]
@morsapaes Thanks for the review!

I was thinking, should we move the main content of this pr to a new section in https://materialize.com/docs/ingest-data/troubleshooting/ ? @RobinClowers made a good point that we want to link to these as references for the new sources statistics page, and it'd be preferred not to link to an `mz_internal` page?

**Comment by morsapaes** [comment]
That's a bit of a chicken and egg problem. I'd really like to bring this to the troubleshooting guide ([see previous comment](https://github.com/MaterializeInc/materialize/pull/25445#issuecomment-1977303561)), but I'd also really like to avoid duplicating work.

Since the console feature is already available internally, we could start drafting the troubleshooting around that feature. WhatI wouldn't want to do is move the existing reference there, and then have to rewrite it to account for the console changes. Maybe something @chaas is interested in picking up this week?

**Comment by guswynn** [comment]
@morsapaes I think I can just move most of this context I added into the troubleshooting section?

**Pull request merged**
