### PR TITLE
tests: split overly long mzcompose/services into multiple files

### PR DESCRIPTION
**Pull request by nrainer-materialize**

### CODE REVIEW

**Comment by nrainer-materialize** [comment]
The testdrive failure in Nightly is unrelated.

**Review by def- — COMMENTED** [review]
This is kind of a matter of taste. I prefer to keep related classes/subclasses together in one file to make it easier to read all of them together and easily discover what other classes there are. I sometimes discovered interesting flags and subclasses just by scrolling through services.py.

In Python there seems to be no strict rule on this, but many opinions favor keeping related classes together in one file: https://softwareengineering.stackexchange.com/questions/209982/is-it-considered-pythonic-to-have-multiple-classes-defined-in-the-same-file & https://softwareengineering.stackexchange.com/questions/306486/is-it-ok-to-have-multiple-classes-in-the-same-file-in-python

Arguments I like from these discussions:
- Sorting in services.py can be grouped by topic, as separate files they are alphabetically sorted
- Inconvenient without an IDE (but I'm probably in the minority on this)
- Standard lib has precedent for this, for example collections module contains 25 classes and > 1000 lines, similar to our services.py: https://github.com/python/cpython/blob/main/Lib/_collections_abc.py

On the other hand the individual services don't have to refer to other services, so they can be isolated in separate modules. So since it's not a clear case for me in this case, I won't block this change if others think it's a net positive.

**Comment by nrainer-materialize** [comment]
> This is kind of a matter of taste. I prefer to keep related classes/subclasses together in one file to make it easier to read all of them together and easily discover what other classes there are. I sometimes discovered interesting flags and subclasses just by scrolling through services.py.
> [...]

It agree that it might be a matter of taste to some degree.

Some thoughts from my side why shorter, well encapsulated files can be beneficial:
* The file name already gives me a clue what to expect in the file.
* There are less conflicts when working on smaller files (e.g., when changing imports or when moving stuff around).
* Less scrolling and searching for line numbers is necessary. It is simpler to navigate through the file.
* The history of a class is easiert to understand. A certain class shows only up in the git history if it was indeed changed; not just because any somehow related class in the same file got changed.

**Comment by philip-stoev** [comment]
In our own codebase, all of the other parts, e.g. cloudtest, various mzcompose-based framework are "related classes per file" already. "related" meaning that e.g. that if there are multiple classes related to a single third-party service, they will be in the same file. In cloudtest, the StatefulSet and the Service will be together in a single file. In other frameworks, the `MzStart` and `MzStop` actions will be in a single file.

In that sense, services.py does not contain "related classes", they are simply subclasses of the same class.

Given the size of the change, I suggest using @benesch as the tie-breaker.

Also, I think the services should be under `materialize.mzcompose.service` , that is, `materialize.mzcompose.service.Materialized` and so forth.

**Review by def- — APPROVED** [review]
Not important enough to block for me. Feel free to submit from my perspective.

**Review by philip-stoev — APPROVED** [review]

**Pull request merged**
