### PR TITLE
wikirecent: simplify, copyedit, and port to mzworkflows.py

### PR DESCRIPTION
**Pull request by benesch**
Touches #9809. I also substantially pared down the amount of code
involved without losing any features. No need to have Python utility
scripts when `psql` and `curl` do the trick.

### Motivation

   * This PR refactors existing code.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

**Comment by benesch** [comment]
@philip-stoev would you feel better if I had @morsapaes review the demo changes in this one?

**Comment by philip-stoev** [comment]
@benesch , yes thanks, I added her as a reviewer. I will also try to run the new implementation as per the new documentation, but an extra pair of eyes trying the same thing will never hurt.

**Review by morsapaes — APPROVED** [review]
Ran the changes locally and it looks good! Made a couple of edits to the `README`, esp. since it mentions the Getting Started guide, which no longer uses the Wikimedia example.

**Comment by benesch** [comment]
Wonderful, tyvm!

**Pull request merged**
