### PR TITLE
ci: annotate when an error also occurred on main

### PR DESCRIPTION
**Pull request by nrainer-materialize**
Demo: https://buildkite.com/materialize/nightlies/builds?branch=nrainer-materialize%3Aci%2Fannotate-error-also-on-main

Bildschirmfoto 2024-02-21 um 13 44 00

### CODE REVIEW

**Review by def- — COMMENTED** [review]
I kind of wanted to do this the other way around at some point, but this is good for now.

My plan was to have a database of failures, and each buildkite run enters its final results there. Then it would be easier to see all the occurrences of a failure and whether they are still happening or how often.

**Comment by nrainer-materialize** [comment]
Some observations:
* As of now, this will only work for mzcomposed jobs because it is called from `ci/plugins/mzcompose/hooks/pre-exit` (that is, it won't work for jobs like "Unused dependencies")
* It requires a Buildkite API Access Token.

**Comment by nrainer-materialize** [comment]
If this creates too many requests, I will need to check if I can get the list of all failing build steps in "Analyze tests" at the end (instead of sending a request for each failing build step).

**Review by def- — APPROVED** [review]
This is super helpful for devs so they don't have to ask us or check main status manually, thanks!

**Pull request merged**
