### PR TITLE
dd system challenges: initial thoughts

### PR DESCRIPTION
**Pull request by antiguru**
Signed-off-by: Moritz Hoffmann <mh@materialize.com>

### CODE REVIEW

**Comment by philip-stoev** [comment]
Idle CPU consumption is also higher with a high number of threads.

**Review by uce — COMMENTED** [review]
Thanks for writing this down and the clear explanation of the experiments. I think it's great to have some numbers and in general look into memory consumption.

Note that @umanwizard has started work on performance and benchmarks. I don't know anything about the scope of that work or what the long-term goals are, but maybe this is also interesting to him. It seems like it could make sense for you to sync?

**Comment by frankmcsherry** [comment]
Would it make sense to convert this to a discussion (https://github.com/MaterializeInc/materialize/discussions)?

**Review by frankmcsherry — CHANGES_REQUESTED** [review]
I think we should move this to a discussion probably.

**Comment by antiguru** [comment]
Yep, makes sense. Closing in favor of https://github.com/MaterializeInc/materialize/discussions/7619.

**Pull request closed without merging**
