### PR TITLE
Reduce default logical compaction window to 1ms

### LINKED ISSUE #5291: UX: logical_compaction_window defaults  - make it 1ms from 60000ms
The current defaults for logical_compaction_window is 60 seconds. This results in higher resource usage which can be avoided.

Keeping a default of 1ms would meet most requirements and help improve first experience. If a customer requires time-travel, then it can increased as needed.

### PR DESCRIPTION
**Pull request by frankmcsherry**
This changes the default for `--logical-compaction-window` to `1ms`, the smallest value that does not force a delay when querying. This change increases the potential for small stalls on queries that use multiple sources (as there is more of a chance that their valid intervals do not overlap) but reduces the default memory and CPU costs associated with maintaining 60s worth of historical data about all collections.

TODO / to discuss: Revisit #4516 and make the same change to logging collections.

fixes #5291

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5335)

### CODE REVIEW

**Comment by frankmcsherry** [comment]
As a side-comment, there are lots of places in the text that we referred to the default value, and there may yet be places that we refer to it but I didn't find (I checked all occurrences of "60s" and "60 seconds"). We now have some "1ms" values that we'll need to scan if we change it again. Is there a better way to string this value through our documentation?

**Comment by frankmcsherry** [comment]
One potential downside of this is that the volume of communication between the coordinator and the workers was limited because the "compact arrangement" messages were only sent at multiples of the logical compaction window, which was larger. With this much smaller, we might expect the coordinator to send such messages each millisecond, which is a lot more spammy traffic between the coordinator and the workers.

**Review by benesch — APPROVED** [review]

**Comment by frankmcsherry** [comment]
Oops. I missed a pretty important edit. Should be better now.

**Review by benesch — APPROVED** [review]
Hah! I missed that too.

**Comment by benesch** [comment]
Uh-oh.

```
test/testdrive/avro-sinks.td:159:1: error: executing query failed: db error: ERROR: Timestamp (1) is not valid for all inputs: [(User(39), Some(Antichain { elements: [2] }))]
```

**Comment by frankmcsherry** [comment]
Yeah, looks like we found a bug that others might have already experienced!

**Comment by frankmcsherry** [comment]
I mean, it looks like it is just a bug. The consistency topic closes out timestamp 2, and then the TAIL Is `AS OF 1`, and there's no reason to expect that to be valid without holding the compaction window open.

**Comment by frankmcsherry** [comment]
I was hoping one could just 
```
# We need to hold back compaction for the next test to pass
> ALTER INDEX input_primary_idx SET (logical_compaction_window = '5ms')
ALTER INDEX
```
but unfortunately as soon as you create the materialized source, or create the index separately, there is a race and you can't catch it. Seems like we'd want a `WITH` option but it only would only apply to `CREATE MATERIALIZED ...` so perhaps best to add to `CREATE INDEX`.

This is going to bite anyone who wants to create an index that supports historical queries without setting their entire MZ instance to default to no compaction.

**Comment by frankmcsherry** [comment]
I screwed around with the test to remove the race condition, but I can't run testdrive stuff locally, so ideally 1. it works or 2. someone else picks up the intent of the fix.

**Comment by frankmcsherry** [comment]
The next failure is new and looks like a linearizability violation. The test says it is testing `AS OF` and `SNAPSHOT`, but it doesn't actually use `AS OF`, so who knows what data we are seeing.

**Comment by benesch** [comment]
Re CREATE INDEX WITH, I have a PR for that. It’s blocked on supporting
millisecond input syntax for intervals.

**Comment by benesch** [comment]
https://github.com/MaterializeInc/materialize/pull/4263 is the PR to add `CREATE INDEX ... WITH`. Seems like you didn't actually wind up needing it but nonetheless seems nice to have!

**Comment by frankmcsherry** [comment]
I worked around it by changing the test, but I think 100% this is a thing that we'll want (here, I had the ability to prevent data from landing in the source before I created the index; normal folks wont have that ability in the wild). I'll file an issue, even if the PR is not necessarily that far away!

**Comment by frankmcsherry** [comment]
This is blocked on a panic in sink creation in the test. However, it also means that starting `materialized` with `--logical-compaction-window 1ms` exposes sink creation panic in `materialized` today.

**Comment by benesch** [comment]
Going to rebase this to see if I can get it to pass now.

**Comment by benesch** [comment]
Ok, @frankmcsherry, this is ready to go if it's good with you!

**Comment by frankmcsherry** [comment]
Thanks!

**Pull request merged**
