### PR TITLE
catalog: Remove dead code

### PR DESCRIPTION
**Pull request by jkosh44**
### Motivation
This PR refactors existing code.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [X] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [X] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - There are no user-facing behavior changes.

### CODE REVIEW

**Comment by jkosh44** [comment]
@antiguru looks like you originally added this code. I couldn't figure out what it was, do we still need it?

**Comment by ParkMyCar** [comment]
Looks like it was added for https://github.com/MaterializeInc/materialize/issues/17417? We might still need this

**Comment by jkosh44** [comment]
> Looks like it was added for #17417? We might still need this

It looks like that project is on hold indefinitely. I would personally prefer to remove this code until the project is picked back up. It's simple enough, but it's impossible to test this code and it will likely rot. For example it already does not have the correct privilege checks to prevent moving objects to/from a system cluster or to prevent moving system objects.

**Review by ParkMyCar — APPROVED** [review]
Makes sense to me!

**Comment by antiguru** [comment]
Looks good to remove this code. There's a bunch of parser/planner code that we can delete, too.

**Review by antiguru — APPROVED** [review]

**Pull request merged**
