### PR TITLE
tests: fix mz E2E test

### PR DESCRIPTION
**Pull request by nrainer-materialize**
This is the suggestion by @benesch in https://github.com/MaterializeInc/materialize/issues/24901#issuecomment-1926437860.

Nightly: https://buildkite.com/materialize/nightlies/builds/6313

### CODE REVIEW

**Comment by nrainer-materialize** [comment]
Unfortunately, nightly is still failing with the same error message:
> ERROR:  Internal kafka error: [thrd:sasl_ssl://pkc-n00kk.us-east-1.aws.confluent.cloud:9092/bootstr]: sasl_ssl://pkc-n00kk.us-east-1.aws.confluent.cloud:9092/bootstrap: SASL authentication error: SaslAuthenticateRequest failed: Local: Broker handle destroyed (after 0ms in state DOWN)
Time: 10173.274 ms (00:10.173)

**Comment by benesch** [comment]
Thanks for putting this up! Rebased on the latest main, which fixes the testdrive output issue, so that I can see _which_ testdrive command is failing!

Nightly here: https://buildkite.com/materialize/nightlies/builds/6318

**Comment by benesch** [comment]
Ah, ok, I think I see the problem here. The SASL password is no longer valid, probably due to Philip's departure. But we're reporting the wrong error message. I'll take a look at improving this tonight.

**Comment by benesch** [comment]
Didn't get a chance to take a look at this tonight, but it's in my queue!

**Comment by benesch** [comment]
Pushed up an alternate fix for the bad error message. Triggered here: https://buildkite.com/materialize/nightlies/builds/6397

**Review by def- — APPROVED** [review]
The error message looks good.

**Comment by benesch** [comment]
Looking more deeply at this test, it seems to deploy the latest release of Materialize to staging ... which means that the patch here had no effect. I think we just got lucky with the latest run. (What gets built from current source is the version of `mz` used to run `mz region enable`, but that has no effect on the connection validation error message.)

Anyway, based on local testing, I now feel confident that this patch fixes the error message, so I'm going to merge it.

**Pull request merged**
