### PR TITLE
Output warning for duplicated BEGIN transaction

### PR DESCRIPTION
**Pull request by OscarTHZhang**
@JLDLaughlin My second PR 😄 
I added this warning feature and tested by building a binary to try it out. I wonder how I can add some unit test to this feature?

Thank you!

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/6220)

### CODE REVIEW

**Comment by JLDLaughlin** [comment]
Awesome @OscarTHZhang! I am not the right person to review this, but I think @mjibson might be?

**Comment by benesch** [comment]
LGTM, thanks! @mjibson you want to do the final sign off?

**Comment by benesch** [comment]
Alternatively, @justinj could chime in.

**Comment by mjibson** [comment]
The place to test this is near https://github.com/MaterializeInc/materialize/blob/3eaaf5836095a50c3fa017b93c677ef0acc40d66/test/pgtest/transactions.pt#L135, which tests an analogous situation for `COMMIT`. You could add your own test, then run `pgtest` against a real postgres server with `REWRITE=1`, then run `pgtest` again against materialize without `REWRITE` to verify it's correct. If that's too annoying, just do nothing and one of can probably take this PR over the line.

I've read the code in this PR and I need to spend some time detailed time to see if there's a better way to do this. Adding a warning state to a transaction variable makes me pause, and I wonder if there's a better way to propagate this information around.

**Comment by benesch** [comment]
Yeah, I’ve wanted for a while to have the coordinator return both an ExecuteResponse and a Vec<Notice> with any additional notices that ought to get printed out. Would be helpful in the SQL layer too. But I think this is fine for now. It’s what we do for drops when the object already exists, for example.

**Comment by benesch** [comment]
> , which tests an analogous situation for COMMIT. You could add your own test, then run pgtest against a real postgres server with REWRITE=1, then run pgtest again against materialize without REWRITE to verify it's correct. If that's too annoying, just do nothing and one of can probably take this PR over the line.

I took care of this. I also tweaked the code a bit to detect duplicate transactions in `Plan::StartTransaction`, not in `session.start_transaction`. Does that resolve your concern @mjibson? Still a little weird to have these bools in `ExecuteResponse` but I think it's ok because it's in line with what we've done before, as I mentioned above!

**Review by mjibson — APPROVED** [review]

**Pull request merged**
