### PR TITLE
ci: enable all Kafka tests in Redpanda nightly

### PR DESCRIPTION
**Pull request by benesch**
@ruf-io reports that the issue might be fixed.

### Motivation

Which of the following best describes the motivation behind this PR?

  * This PR accounts for a fix to a recognized bug: redpanda-data/redpanda#2397

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - N/A

### CODE REVIEW

**Comment by morsapaes** [comment]
It's not, there was just a leftover glitch in the 3rd Party documentation page for Redpanda!

**Comment by ruf-io** [comment]
Fake news. Sorry to get everyone's hopes up!

**Comment by benesch** [comment]
No worries! I'll leave this open so that we can merge it when the time comes.

**Comment by benesch** [comment]
Done in #11932.

**Pull request closed without merging**
