### PR TITLE
*: purge parse_duration crate from public interface

### PR DESCRIPTION
**Pull request by mjibson**

### CODE REVIEW

**Comment by mjibson** [comment]
Note in the second commit additions to datetime.rs that add support for non-standard spellings of hour, minute, and second (specifically "min" which is unsupported by DateTimeField).

**Comment by mjibson** [comment]
I don't understand the test failures. They succeed locally.

**Comment by benesch** [comment]
So, if I had to guess, there's a bug somewhere in the new parsing, and the `--timestamp-frequency` argument is no longer producing a duration of 1s, and that's causing the tests to fail.

**Comment by benesch** [comment]
(LGTM if you can find the bug.)

**Comment by benesch** [comment]
Oh, I think I see the bug. It's my fault.

**Comment by benesch** [comment]
Pushed up what I hope is a fix.

**Review by benesch — APPROVED** [review]
🎉

**Pull request merged**
