### PR TITLE
misc: reformat python file

### PR DESCRIPTION
**Pull request by sploiselle**
#6998 failed on this, so wanted to see if I could simply fix it, not sure who's truly responsible for this code so my apologies for the broadcast ping

### CODE REVIEW

**Comment by quodlibetor** [comment]
This appears to be a single extra newline? Usually we group all imports at the top of the file, IMO it'd make more sense to move the import to be with the other imports rather than add a newline if that is the intended change.

**Comment by quodlibetor** [comment]
(my question is because this is a single file, not multiple files, per PR description)

**Comment by sploiselle** [comment]
Oh, I will amend that description to express the proper plurality. ty for catching that.

**Comment by sploiselle** [comment]
ah, this is fixed in `17f9f826ce2b401ebbf70d0549fc6c85166be523`

**Pull request closed without merging**
