### PR TITLE
Move more time units to use strconv in SLT

### PR DESCRIPTION
**Pull request by lmatz**
#1526 This uses routines under `repr/strconv.rs` to convert datum values(`Date`, `Time`, `Timestamp`, `TimestampTz`, `Interval`) to their string representation. 
And update the `test/sqllogictest/dates-times.slt` to match with the new results.

### CODE REVIEW

**Comment by benesch** [comment]
Hi @lmatz, thanks for your contribution!

Unfortunately sqllogictests are a bit of a weird beast and for at least some of these data types we intentionally use a format that matches the upstream sqllogictest files, rather than Materialize's/Postgres's native output format. You may have noticed that in addition to the first-party SLTs in test/sqllogictest, we also have SLTs from SQLite and CockroachDB in test/sqllogictest/{sqlite, cockroach} respectively.

I'm not sure whether these new output formats will be compatible with the existing SQLite/CockroachDB tests. Unlike the first-party tests where we're perfectly happy to rewrite the test files, we like to keep the third-party test files as similar to their upstream counterparts as possible so that we can incorporate upstream fixes as necessary. I'll kick off a full SLT run so we can see what fallout there is, if any.

**Comment by benesch** [comment]
The testdrive failure is on us, as there's a bit of merge skew on master, so the revision you based this PR off of is a bit broken. The SLT failure looks legit, though.

I kicked off a full SLT run here: https://buildkite.com/materialize/sql-logic-tests/builds/3616. (The PR SLT runner only runs a small subset of the SLT tests.)

**Comment by lmatz** [comment]
Hi @benesch, thanks for the explanation!

I guess if there are any failures in the first-party test files, then these test files are supposed to be modified to match with the new results. If there are any failures in the third-party test files, then the `runner.rs` is supposed to detect the `mode` and format the `Datum` in the corresponding(sqlite or cockroach) way, do I understand correctly?

The page of full STL run seems to be private.

**Comment by benesch** [comment]
> If there are any failures in the third-party test files, then the runner.rs is supposed to detect the mode and format the Datum in the corresponding(sqlite or cockroach) way, do I understand correctly?

That's just about right, though unfortunately the modes do not correspond exactly with the source of the test file. Our first-party tests use both the "standard" (sqlite) mode and the cockroach mode. So when there's deviation it's not quite as simple as detecting the mode.

Fortunately SLT on sqlite and cockroach passed with flying colors, so I think we're safe. SLT on sqlite passed all tests, as expected. Cockroach SLT has known failures, but the known failures in this PR

```
unsupported=231 parse-failure=180 plan-failure=183 unexpected-plan-success=15 inference-failure=21 output-failure=65 bail=25 success=898 total=1618
```

match exactly the latest results on master (https://mtrlz.dev/civiz/), so seems like we're good here.

Can you please rebase onto master and fix the one broken test in funcs.slt? Then we should be good to merge!

**Comment by lmatz** [comment]
Fixed two additional inconsistencies in dates-times.slt and jsonb.slt's test cases added by PR #2026.

**Comment by benesch** [comment]
Great, thanks. I've triggered a new build.

**Comment by benesch** [comment]
Thanks very much, @lmatz!

**Pull request merged**
