### PR TITLE
frontegg-auth: remove dep on mz_sql

### PR DESCRIPTION
**Pull request by danhhz**
It was just here for a From impl that doesn't seem terribly necessary. Instead inline the impl where it was previously used.

### Motivation

   * This PR refactors existing code.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by danhhz** [comment]
@benesch curious for you take if this sort of thing is crazy or not

**Comment by benesch** [comment]
It's not crazy. I felt bad about the dep when I added it. At the same time, if the mapping from `ValidatedClaims` to `ExternalUserMetadata` were just a touch more complicated, we'd probably feel worse about the duplication.

Is there something in particular you're in pursuit of here? Other options for dependency edges includes:

  * Adding an `mz-auth` crate that declares `ExternalUserMetadata`, depends on `mz-frontegg-auth` and has the `From<ValidatedClaims>` impl in it.
  * Having `mz-sql` depend on `mz-frontegg-auth` and adding the `From<ValidatedClaims>` impl there.

**Comment by danhhz** [comment]
Context here is just that I've started looking at the dep graph of everything that is invalidated by mz_storage_client while waiting for compiles in my txn management prototyping and this was the easiest one to tease apart :D. I don't feel particularly motivated to get this PR merged, but by the time I figured out that there wasn't a nice place to move this conversion to, I'd already gotten this typed up and figured I'd send it out for a temp check.

I realized just now that another option is to stuff an awkward-ish `pub fn` in mz_pgwire and use that from mz_environmentd?

**Comment by benesch** [comment]
> Context here is just that I've started looking at the dep graph of everything that is invalidated by mz_storage_client while waiting for compiles in my txn management prototyping and this was the easiest one to tease apart :D. I don't feel particularly motivated to get this PR merged, but by the time I figured out that there wasn't a nice place to move this conversion to, I'd already gotten this typed up and figured I'd send it out for a temp check.
> 
> I realized just now that another option is to stuff an awkward-ish `pub fn` in mz_pgwire and use that from mz_environmentd?

Yeah I thought of that too, but that's too awkward IMO; `mz_pgwire` doesn't really want to be authoritative place where we map the standalone Frontegg authentication to the `sql` crate's take on authentication metadata.

If a crate like `mz_auth_bridge` that bridges between the `sql` crate's take and any third-party authentication providers seems like overkill for this one function (fair), this seems like the next best option to me.

**Review by benesch — APPROVED** [review]

**Comment by danhhz** [comment]
Doesn't sound like there's particular excitement about this approach (reading between the lines, I feel like maybe our common leaning is "new crate"?) and it's unlikely to be much of an immediate benefit without a batch of other deps work (in particular, I think there's something interesting in splitting out mz_storage_client::types and mz_compute_client::types). I'm going to go ahead and close this. Always happy to revisit once we've gotten some of the lower hanging fruit out of the way.

**Comment by benesch** [comment]
I'm weakly in favor of merging this PR, fwiw! Just even more strongly in favor of a new crate.

**Comment by danhhz** [comment]
wfm!

**Comment by danhhz** [comment]
It was automatic, but either way TFTR :). I _think_ "as a code owner" is a reliable indicator that it was automatic

image

**Pull request merged**
