### PR TITLE
adapter: improve GlobalMirPlan until resolution

### PR DESCRIPTION
**Pull request by mjibson**
Previously this would have triggered the as_of overflow warning:

```
create view v as select 1;
select * from v;
```

Because that's a query not on a timeline, so we use the MAX timestamp which overflows when incremented.

Instead, detect if we are in a timeline with no timestamp and don't even try to set the until.

### Motivation

   * This PR refactors existing code.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - n/a

### CODE REVIEW

**Comment by aalexandrov** [comment]
Me and @teskje were wondering what constitutes a timeline with no timestamp.

In general the next stage of the optimizer (`GlobalMirPlan<ResolvedGlobal<'s> ⇒ GlobalLirPlan`) calls `Plan::finalize_dataflow` which [attempts optimizations if `until - as_of = 1`](https://github.com/MaterializeInc/materialize/blob/bb62080f68fa7200994406829a486e50a1cccead/src/compute-types/src/plan/mod.rs#L1864-L1894).

Ideally, we should not skip those for queries without a timeline, but depending on what this class of queries contains this might not result in visible regressions.

**Comment by mjibson** [comment]
No timeline queries are queries that don't reference any sources or tables: they are known to have constant results at any timestamp. We still have to choose a timestamp for execution though, and go with MAX. If we want other optimizations to occur and we thus need a computable until, we might need to choose a lower timestamp for the as of so the until can exist.

I think you could also extend that logic to be aware that `as_of == Timestamp::MAX` can also apply those optimizations. That as of means that no changes will occur. Is that the goal of `until - as_of = 1`? I've opened https://github.com/MaterializeInc/materialize/pull/23071 to implement that.

**Comment by aalexandrov** [comment]
> I think you could also extend that logic to be aware that as_of == Timestamp::MAX can also apply those optimizations. That as of means that no changes will occur. Is that the goal of until - as_of = 1? I've opened #23071 to implement that.

I like that approach. I think we'll need to add a test to ensure that constant plans that are not reduced to a constant collection hit the `is_single_time` optimization paths. I can do that on Monday.

If the `warn!` is annoying I suggest to merge this PR or open another PR that removes the `warn!` so we don't cut a release with that code.

**Comment by mjibson** [comment]
> If the warn! is annoying I suggest to open another PR that removes the warn! so we don't cut a release with that code.

This PR achieves that goal but in, I think, a better way that also doesn't need any tests. 23071 reasonably needs a test or something else, but I think this PR is well scoped to achieve the goal of removing the `warn`.

**Review by ParkMyCar — APPROVED** [review]

**Comment by mjibson** [comment]
https://github.com/MaterializeInc/materialize/pull/23074 is a PR that only removes the warn if we want something simpler to go in.

**Review by ggevay — APPROVED** [review]
LGTM

**Pull request merged**
