### PR TITLE
scratch: add persist-benchmarking shortcut for create

### PR DESCRIPTION
**Pull request by danhhz**
I keep manually making this and then stashing the change. It's unclear
what the best instance_type for this is, but the one in dev-box.json is
definitely not powerful enough, so starting with the one used for our
release load tests. (It's also the one I've been using.)

### Motivation

  * This PR adds a feature that has not yet been specified.

### Checklist

- [N/A] This PR has adequate test coverage / QA involvement has been duly considered.
- [N/A] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

**Comment by ruchirK** [comment]
lol we both had the same idea https://github.com/MaterializeInc/materialize/pull/10133

**Review by ruchirK — APPROVED** [review]
I'm fine with this if @benesch is fine with this - I lightly would prefer to have the name be something other than persist-benchmarking because i think other folks can make use of this too? Maybe like `one-off-load-test` or something like that? I used `big-dev-box` in my version of this pr which has a childish appeal

**Comment by danhhz** [comment]
My reasoning behind the very specific name was that these are cheap (just a json file) and I don't want to have to check with other users of it if e.g. we want to change the instance type. I guess what I'm saying is I think there is value in merging both of our PRs

**Review by benesch — APPROVED** [review]

**Comment by ruchirK** [comment]
that works for me!

**Comment by danhhz** [comment]
TFTRs!

**Pull request merged**
