### PR TITLE
sql: support ANY() array comparison function

### PR DESCRIPTION
**Pull request by JLDLaughlin**
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4410)

### CODE REVIEW

**Review by benesch — COMMENTED** [review]
Looking really good! Just a few comments below.

> Reviewed 8 of 8 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4410#-:-MJ39poj-LlL4WEa0GpP:bndmcd)* status: all files reviewed, 7 unresolved discussions (waiting on @JLDLaughlin and @sploiselle)

___
*[src/expr/src/scalar/func.rs, line 18 at r1](https://reviewable.io/reviews/materializeinc/materialize/4410#-MJ381uf04iGQAKT9MZh:-MJ381uf04iGQAKT9MZi:b-6gpx1n) ([raw file](https://github.com/materializeinc/materialize/blob/77216a90126471c2465b19284d9f6db2f2432d42/src/expr/src/scalar/func.rs#L18)):*
> ```Rust
> use encoding::label::encoding_from_whatwg_label;
> use encoding::DecoderTrap;
> use itertools::{any, Itertools};
> ```

Rust convention is to avoid importing bare functions because they are usually named ambiguously. In this case it would be better to refer to `itertools::any` below.
___
*[src/expr/src/scalar/func.rs, line 1792 at r1](https://reviewable.io/reviews/materializeinc/materialize/4410#-MJ38Jtc7C3n_Rdufu9K:-MJ38Jtc7C3n_Rdufu9L:b9yidzn) ([raw file](https://github.com/materializeinc/materialize/blob/77216a90126471c2465b19284d9f6db2f2432d42/src/expr/src/scalar/func.rs#L1792)):*
> ```Rust
>     ListLengthMax { max_dim: usize },
>     ArrayContains,
>     ArrayDoesNotContain,
> ```

Having an explicit negation for a function is unusual. I would instead only have `ArrayContains`, and plan `<>` as a UnaryNot on top of `ArrayContains`.
___
*[src/expr/src/scalar/func.rs, line 3314 at r1](https://reviewable.io/reviews/materializeinc/materialize/4410#-MJ38CDz99wMNPnJFzem:-MJ38CDz99wMNPnJFzen:b6lr4f4) ([raw file](https://github.com/materializeinc/materialize/blob/77216a90126471c2465b19284d9f6db2f2432d42/src/expr/src/scalar/func.rs#L3314)):*
> ```Rust
> fn datum_in_array<'a>(a: Datum<'a>, b: Datum<'a>) -> bool {
>     let array = Datum::unwrap_array(&b);
>     any(&array.elements(), |e| e == a)
> ```

Actually, using `itertools::any` here is a bit nonstandard. I think just `array.elements().iter().any(|e| e == a)` would do the trick.
___
*[src/sql/src/plan/func.rs, line 1691 at r1](https://reviewable.io/reviews/materializeinc/materialize/4410#-MJ38W99CEKDqgi8XU3l:-MJ38W99CEKDqgi8XU3m:bjy24hc) ([raw file](https://github.com/materializeinc/materialize/blob/77216a90126471c2465b19284d9f6db2f2432d42/src/sql/src/plan/func.rs#L1691)):*
> ```Rust
>             BinaryOperator::ArrayDoesNotContain => Scalar {
>                 params!(Any, ArrayAny) => BinaryFunc::ArrayDoesNotContain
>             }
> ```

See comment below, but I think these are dead code? Also they're not going to perform type coercion correctly at the moment because we don't properly constrain polymorphic types—this could result in checking whether a text array contains an int, for example.
___
*[src/sql/src/plan/query.rs, line 1804 at r2](https://reviewable.io/reviews/materializeinc/materialize/4410#-MJ39dj24tsRTwQcpduA:-MJ39dj24tsRTwQcpduB:b-yscat) ([raw file](https://github.com/materializeinc/materialize/blob/f8f3148cb2a00414430293db874ee4a75ea0cf01/src/sql/src/plan/query.rs#L1804)):*
> ```Rust
>                 expr2: Box::new(rhs),
>             })
>         }
> ```

:raised_hands: this looks great! Though see note above about wrapping in a not rather than introducing a separate `ArrayDoesNotContain` function. (There's an example in `plan_is_null_expr` that you can follow.)
___
*[src/sql-parser/src/ast/defs/operator.rs, line 77 at r1](https://reviewable.io/reviews/materializeinc/materialize/4410#-MJ37D7k8U0149Lvm0XY:-MJ37D7k8U0149Lvm0XZ:bcsm154) ([raw file](https://github.com/materializeinc/materialize/blob/77216a90126471c2465b19284d9f6db2f2432d42/src/sql-parser/src/ast/defs/operator.rs#L77)):*
> ```Rust
>     JsonApplyPathPredicate,
>     ArrayContains,
>     ArrayDoesNotContain,
> ```

Looks like dead code to me. Like, we can't actually parse these operators, can we? (Also the array contains operators are actually the same as the JSON contains operator; the fact that we call all of those operators "JSON" operators is wrong and should be fixed—but not here!)
___
*[test/sqllogictest/arrays.slt, line 42 at r2](https://reviewable.io/reviews/materializeinc/materialize/4410#-MJ394QU3qA6ruq63RmJ:-MJ394QV-YiQd4rL72mQ:b-ddazvt) ([raw file](https://github.com/materializeinc/materialize/blob/f8f3148cb2a00414430293db874ee4a75ea0cf01/test/sqllogictest/arrays.slt#L42)):*
> ```
> true
> 
> query error SELECT clause must have type i32\[\], not type string\[\]
> ```

`SELECT clause`?

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4410)* status: all files reviewed, 7 unresolved discussions (waiting on @JLDLaughlin and @sploiselle)

___
*[test/sqllogictest/arrays.slt, line 42 at r2](https://reviewable.io/reviews/materializeinc/materialize/4410#-MJ394QU3qA6ruq63RmJ:-MJ3A6PN1x-hpgB1CLo6:bzh9zsf) ([raw file](https://github.com/materializeinc/materialize/blob/f8f3148cb2a00414430293db874ee4a75ea0cf01/test/sqllogictest/arrays.slt#L42)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

`SELECT clause`?
</blockquote></details>

I would have expected this to hit the `bail!` you added above specifically for this case. Any idea what's going on?

**Review by JLDLaughlin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4410)* status: all files reviewed, 7 unresolved discussions (waiting on @benesch, @JLDLaughlin, and @sploiselle)

___
*[test/sqllogictest/arrays.slt, line 42 at r2](https://reviewable.io/reviews/materializeinc/materialize/4410#-MJ394QU3qA6ruq63RmJ:-MJ3PJIB8yv4H0y46UNg:b-qnd5tg) ([raw file](https://github.com/materializeinc/materialize/blob/f8f3148cb2a00414430293db874ee4a75ea0cf01/test/sqllogictest/arrays.slt#L42)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I would have expected this to hit the `bail!` you added above specifically for this case. Any idea what's going on?
</blockquote></details>

Yes! This is getting hit when we try to coerce the type of the array with `type_as` (https://github.com/MaterializeInc/materialize/pull/4410/files#diff-5b8bfb4e1b5e96e747d1181b8e797d73R1769). I  don't think we can avoid this? But I can make the error message clearer - agree that it's not currently helpful!

(It's grabbing `SELECT clause` from the `ExprContext`)

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4410)* status: all files reviewed, 7 unresolved discussions (waiting on @JLDLaughlin and @sploiselle)

___
*[test/sqllogictest/arrays.slt, line 42 at r2](https://reviewable.io/reviews/materializeinc/materialize/4410#-MJ394QU3qA6ruq63RmJ:-MJ3WpBY55F3mQh68ssL:b896rdi) ([raw file](https://github.com/materializeinc/materialize/blob/f8f3148cb2a00414430293db874ee4a75ea0cf01/test/sqllogictest/arrays.slt#L42)):*
<details><summary><i>Previously, JLDLaughlin (Jessica Laughlin) wrote…</i></summary><blockquote>

Yes! This is getting hit when we try to coerce the type of the array with `type_as` (https://github.com/MaterializeInc/materialize/pull/4410/files#diff-5b8bfb4e1b5e96e747d1181b8e797d73R1769). I  don't think we can avoid this? But I can make the error message clearer - agree that it's not currently helpful!

(It's grabbing `SELECT clause` from the `ExprContext`)
</blockquote></details>

Ahh, ok, that's totally fine then! Just a quick `ecx.with_name("ANY operand")` will do the trick!

**Review by benesch — APPROVED** [review]
:lgtm_strong: 

> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4410#-:-MJ3aoVf-GBojmL7YWWZ:b-uwkowd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sploiselle)

**Pull request merged**
