### PR TITLE
persist: remove some short-lived allocations under Trace::push_batch

### PR DESCRIPTION
**Pull request by danhhz**
trace/push_batch/5000   time:   [119.33 ms 119.44 ms 119.52 ms]
                            change: [-95.359% -95.082% -94.843%] (p = 0.00 < 0.05)
                            Performance has improved.

Specifically:
- Pre-size the Vec in FuelingMerge::done
- Wrap HollowBatch in an Arc within persist Trace. This might be a small
  pessimization for the common case in prod of a steady state shard.
  However, for the problematic case of deserializing a State with a
  single non-empty batch followed by many empty batches, the allocations
  of cloning all the Antichains transitively involved in the
  FueledMergeReqs just to throw the merge req away are extremely costly.
  Ideally, we'd do what differential_dataflow does and use Rc, but until
  https://github.com/MaterializeInc/materialize/pull/17150 these need to be Send+Sync.

These allocations were costly enough that they were the overwhelming
result of cpu profiling. Also sneak in a tweak to use the pre-computed
lens of b1 and b2 in FuelingMerge::done, which was also showing up on
cpu profiles.

Touches #17214

### Motivation

  * This PR fixes a recognized bug.

### Tips for reviewer

This is still quadratic, but that's going to be a much more involved fix. This was straightforward and 20x faster means that maybe we'd have avoided the issues that led to #17214, so I wanted to be sure to get it into next week's release.

(I'm still working on understanding enough of details of the quadratic behavior that I can coherently explain it. The very rough sketch is that all empty batches gets the empty-batch optimization. All non-empty batches get arranged nicely into tiers by spine. One non-empty followed by a bunch of empty means that we repeatedly generate merge requests with a linearly increasing number of inputs.)

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a
  companion cloud PR to account for those changes that is tagged with
  the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Review by bkirwi — APPROVED** [review]
A compelling benchmark!

Would be a little sad about the `Arc`s (especially given that under the hood the antichain we're no longer cloning is isomorphic to `Option<u64>`) but it sounds like the other stuff we have in flight should take care of it.

**Comment by bkirwi** [comment]
And the feature bench should tell us if we've regressed the common case, of course.

**Comment by danhhz** [comment]
Yeah, I'm sad about the Arc, too. I think we could also probably avoid it if Antichain internally used SmallVec, but IIRC the last time that idea came up, there was some reason not to do it.

Nightlies: https://buildkite.com/materialize/nightlies/builds/1692

**Comment by danhhz** [comment]
Hmm, I wonder if this is real?

```
FinishOrderByLimit        |       0.313 |       0.275 |    !!YES!!    | 13.8 pct   slower
```

**Comment by danhhz** [comment]
Possible that it was noise. Running it locally I got
```
NAME                      |    THIS     |    OTHER    |  Regression?  | 'THIS' is:
----------------------------------------------------------------------------------------------------
FinishOrderByLimit        |       0.564 |       0.607 |      no       | 7.2 pct   faster

THIS
Measurement 1: 0.7092466354370117
Measurement 2: 0.6712007522583008
Measurement 3: 0.5945322513580322
Measurement 4: 0.6511826515197754
Measurement 5: 0.6538522243499756
Measurement 6: 0.6006815433502197
Measurement 7: 0.7009038925170898
Measurement 8: 0.5637493133544922
Measurement 9: 0.5768008232116699
Measurement 10: 0.6346907615661621
Measurement 11: 0.6034832000732422
Measurement 12: 0.7092678546905518
Measurement 13: 0.6827569007873535
Measurement 14: 0.7197144031524658

OTHER
Measurement 1: 0.7236311435699463
Measurement 2: 0.6071794033050537
Measurement 3: 0.8098206520080566
Measurement 4: 0.8073956966400146
Measurement 5: 0.7499632835388184
Measurement 6: 0.711963415145874
```

**Comment by danhhz** [comment]
Tried it again with a local hack to increase the feature benchmark threshold so I'd get more runs in. I did check out the last few runs in buildkite and it doesn't seem flaky, though...

```
NAME                      |    THIS     |    OTHER    |  Regression?  | 'THIS' is:
----------------------------------------------------------------------------------------------------
FinishOrderByLimit        |       0.530 |       0.539 |      no       | 1.8 pct   faster

THIS
Measurement 1: 0.5296735763549805
Measurement 2: 0.6340649127960205
Measurement 3: 0.5683856010437012
Measurement 4: 0.5800127983093262
Measurement 5: 0.5595133304595947
Measurement 6: 0.6185023784637451
Measurement 7: 0.5916342735290527
Measurement 8: 0.5698292255401611
Measurement 9: 0.7018246650695801
Measurement 10: 0.5713191032409668
Measurement 11: 0.5612571239471436
Measurement 12: 0.5728554725646973
Measurement 13: 0.6162917613983154
Measurement 14: 0.6227419376373291
Measurement 15: 0.620513916015625
Measurement 16: 0.5795347690582275
Measurement 17: 0.5797054767608643
Measurement 18: 0.589224100112915
Measurement 19: 0.5673439502716064
Measurement 20: 0.5411179065704346
Measurement 21: 0.5825290679931641
Measurement 22: 0.6140422821044922
Measurement 23: 0.5394833087921143
Measurement 24: 0.553858757019043
Measurement 25: 0.5408811569213867
Measurement 26: 0.599785566329956

OTHER
Measurement 1: 0.5439667701721191
Measurement 2: 0.7102572917938232
Measurement 3: 0.553330659866333
Measurement 4: 0.5765814781188965
Measurement 5: 0.5512709617614746
Measurement 6: 0.6324729919433594
Measurement 7: 0.6479229927062988
Measurement 8: 0.6748287677764893
Measurement 9: 0.5571749210357666
Measurement 10: 0.7020108699798584
Measurement 11: 0.6438913345336914
Measurement 12: 0.677997350692749
Measurement 13: 0.5619277954101562
Measurement 14: 0.6556320190429688
Measurement 15: 0.5983576774597168
Measurement 16: 0.5808994770050049
Measurement 17: 0.6370155811309814
Measurement 18: 0.5394346714019775
Measurement 19: 0.7375161647796631
Measurement 20: 0.6087169647216797
Measurement 21: 0.5743756294250488
Measurement 22: 0.6292757987976074
Measurement 23: 0.6033141613006592
Measurement 24: 0.8249740600585938
Measurement 25: 0.7095201015472412
Measurement 26: 0.656531572341919
```

**Comment by danhhz** [comment]
Oh, just noticed that feature benchmark retries the ones that regressed a few times to see if they stick around. I probably just have to be patient then :)

**Comment by danhhz** [comment]
Yup, it was happy on the second cycle. TFTR!

**Comment by pH14** [comment]
🚤

**Pull request merged**
