### PR TITLE
Helper script to build perf from source on Ubuntu

### PR DESCRIPTION
**Pull request by cirego**
Add script to build and install perf from source
    
Finding instructions on how to build perf from source are not easy, so
let's write a little script to help people know which dependencies need
to be installed.
    
Set the appropriate sysctl values so that perf will actually work.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4427)

### CODE REVIEW

**Comment by ruchirK** [comment]
Could you add a little bit more detail around why building perf from source is required? I've used the perf binary that comes in some flavor of `linux-tools` package on aws boxes to record perf events and do perf top and everything seemed to work fine

**Comment by cirego** [comment]
> Could you add a little bit more detail around why building perf from source is required? I've used the perf binary that comes in some flavor of `linux-tools` package on aws boxes to record perf events and do perf top and everything seemed to work fine

This was PR in response to following the instructions here: https://github.com/MaterializeInc/wiki/wiki/CPU-profiling-tips. In particular, `perf report` can be very slow on Rust binaries. @umanwizard, do you have any experience running perf on our AWS VMs? Does `perf report` run acceptably on AWS VMs or should we also compile from source there?

**Comment by umanwizard** [comment]
@ruchirK in my experience, running the default Ubuntu `perf report` or `perf top` on Rust binaries with stack trace profiles is incredibly slow (takes minutes or hours to symbolicate all the traces), unless you turn off support for inlined frames. Was that not your experience?

**Comment by ruchirK** [comment]
I've used perf with call graph features on the materialize binary and IIRC, it took longer than i expected to show the report, but it was on the order of a minute or two, not hours? I'm happy to try again today to confirm

**Comment by cirego** [comment]
> I've used perf with call graph features on the materialize binary and IIRC, it took longer than i expected to show the report, but it was on the order of a minute or two, not hours? I'm happy to try again today to confirm

Did you end up trying this again? I'd like to either merge this PR or abandon it. Happy either way.

**Pull request merged**
