### PR TITLE
doc/user: improve guides by removing stale mentions

### LINKED ISSUE #25687: Postgres guides: remove reference to ingest_postgres cluster
### Documentation request

I have come around full circle on this. A recent user has stumbled enough in confusion between quickstart and ingest_postgres clusters that I think we should not name clusters in the Postgres guide. That way, the natural progression will be for all work to be done in the quickstart cluster, thanks to cluster unification.

At most, we could have a note that mentions IN CLUSTER and points to the reference documentation.

Cluster strategy / separation of concerns is an important topic, but I am now convinced it deserves its own discussion totally separate from the Postgres guide.

### Affected Pages

Postgres guides

_No response_

### Related work

_No response_

### PR DESCRIPTION
**Pull request by morsapaes**
This PR updates our integrations guides to match the current state of Materialize:

* Remove `IN CLUSTER` from the `CREATE SOURCE` command for all webhook guides, as a follow-up to #25398.
* Add a note about the default behavior of `CREATE SOURCE` to all guides:
   > By default, the source will be created in the active cluster; to use a different cluster, use the `IN CLUSTER` clause.
* Make cluster creation an optional step in all guides. Refrained from completely removing the step because, in the end, we still recommend using multiple clusters for resource isolation. Added a note to that effect:
   > {{< note >}}
   > If you are prototyping and already have a cluster to host your PostgreSQL
   > source (e.g. `quickstart`), **you can skip this step**. For production
   > scenarios, we recommend separating your workloads into multiple clusters for
   > [resource isolation](https://materialize.com/docs/sql/create-cluster/#resource-isolation).
   > {{< /note >}}
* Replace mentions to `psql` with:
   > In the [SQL Shell](https://console.materialize.com/), or your preferred SQL client connected to Materialize,

Fixes #25687.

### CODE REVIEW

**Comment by morsapaes** [comment]
There's some work left to do to make the guides more maintainable and consistent, but...small steps.

**Review by chuck-alt-delete — APPROVED** [review]
I would still prefer defaulting to the quickstart cluster and using the note as an escape hatch if they want a different cluster. However, this is overall a welcome improvement, so I’ll go ahead and approve.

One other non blocking note is if they do use the quickstart cluster for Postgres, they skip the step to size it up for the snapshot. That’s probably fine but just wanted to call it out. It would be a little awkward because the resize command requires ALTER CLUSTER <name>

**Comment by morsapaes** [comment]
I don't like this as the final state; just think it's a quick way to improve the current situation without completely redoing the guides.

> One other non blocking note is if they do use the quickstart cluster for Postgres, they skip the step to size it up for the snapshot.

This crossed my mind, too. Making these guides more amenable to cluster unification while providing guidance around best practices requires a bigger reshuffle that I don't have time for today. I'll do it as a follow-up, since the state of the integration guides has been bothering me for a while.

**Comment by benesch** [comment]
Don't wait for my review!

**Comment by morsapaes** [comment]
No worries, @benesch; you were my escape hatch for a quick ✅!

**Pull request merged**
