### PR TITLE
debezium: Test sink based on debezium source

### PR DESCRIPTION
**Pull request by antiguru**
WIP for #6834 

Running the test: From `test/debezium-avro`, run `./mzcompose down -v ; env TD_TEST=92-sink.td ./mzcompose run debezium-avro`

Signed-off-by: Moritz Hoffmann <mh@materialize.com>

### CODE REVIEW

**Comment by antiguru** [comment]
This currently fails in an unexpected way: I get the following output, and then it stops:
```
==> 92-sink.td
Running test 1 time(s) ... 
Run 1 ...
> DROP SOURCE IF EXISTS s2 CASCADE
> DROP SOURCE IF EXISTS s1 CASCADE
Executing queries against PostgreSQL server at postgres://postgres:postgres@postgres...
>> CREATE TABLE t1 (f1 INTEGER);
>> INSERT INTO t1 VALUES (123), (234);
> CREATE MATERIALIZED SOURCE s1 FROM KAFKA BROKER 'kafka:9092' TOPIC 'post...
rows match; continuing
> SELECT * FROM s1;
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 112ms 169ms 253ms 380ms 570ms
rows match; continuing
> CREATE SINK sink1 FROM s1 INTO KAFKA BROKER 'kafka:9092' TOPIC 'sink1' W...
rows match; continuing
Executing queries against PostgreSQL server at postgres://postgres:postgres@postgres...
>> INSERT INTO t1 VALUES (345), (456);
> SELECT * FROM s1;
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 112ms 169ms 
```

**Comment by antiguru** [comment]
call stack of all threads:
[gdb.txt](https://github.com/MaterializeInc/materialize/files/6638936/gdb.txt)

**Comment by antiguru** [comment]
It seems to be stick in kafka:
```
Thread 17 (LWP 515217 "timely:work-0"):
#0  0x00007f92cf7319f3 in pthread_cond_wait@@GLIBC_2.3.2 () from target:/lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00005653c717c2c9 in cnd_wait (cond=<optimized out>, mtx=<optimized out>) at /cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/b4ec50e/rdkafka-sys/librdkafka/src/tinycthread.c:442
#2  0x00005653c717c545 in cnd_timedwait_abs (cnd=cnd@entry=0x7f92bf6b0528, mtx=mtx@entry=0x7f92bf6b0500, tspec=tspec@entry=0x7f92c5878300) at /cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/b4ec50e/rdkafka-sys/librdkafka/src/tinycthread_extra.c:99
#3  0x00005653c7105adf in rd_kafka_q_pop_serve (rkq=rkq@entry=0x7f92bf6b0500, timeout_us=<optimized out>, version=version@entry=0, cb_type=cb_type@entry=RD_KAFKA_Q_CB_RETURN, callback=callback@entry=0x0, opaque=opaque@entry=0x0) at /cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/b4ec50e/rdkafka-sys/librdkafka/src/rdkafka_queue.c:404
#4  0x00005653c7105b70 in rd_kafka_q_pop (rkq=rkq@entry=0x7f92bf6b0500, timeout_us=<optimized out>, version=version@entry=0) at /cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/b4ec50e/rdkafka-sys/librdkafka/src/rdkafka_queue.c:428
#5  0x00005653c70fb8a3 in rd_kafka_op_req0 (destq=<optimized out>, recvq=recvq@entry=0x7f92bf6b0500, rko=rko@entry=0x7f92b46294c0, timeout_ms=timeout_ms@entry=-1) at /cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/b4ec50e/rdkafka-sys/librdkafka/src/rdkafka_op.c:612
#6  0x00005653c71440be in rd_kafka_txn_curr_api_req (rk=rk@entry=0x7f92c392c000, name=<optimized out>, name@entry=0x5653c4cc68b0 <__FUNCTION__.10> "rd_kafka_init_transactions", rko=0x7f92b46294c0, timeout_ms=timeout_ms@entry=5000, flags=flags@entry=6) at /cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/b4ec50e/rdkafka-sys/librdkafka/src/rdkafka_txnmgr.c:1229
#7  0x00005653c7146272 in rd_kafka_init_transactions (rk=0x7f92c392c000, timeout_ms=5000) at /cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/b4ec50e/rdkafka-sys/librdkafka/src/rdkafka_txnmgr.c:1371
#8  0x00005653c6c6e5f7 in rdkafka::producer::base_producer::{{impl}}::init_transactions<dataflow::sink::kafka::SinkProducerContext,core::time::Duration> () at /cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/b4ec50e/src/producer/base_producer.rs:398
#9  rdkafka::producer::base_producer::{{impl}}::init_transactions<dataflow::sink::kafka::SinkProducerContext,core::time::Duration> () at /cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/b4ec50e/src/producer/base_producer.rs:594
#10 0x00005653c6512818 in dataflow::sink::kafka::produce_to_kafka::{{closure}}<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, u64>, u64>> () at /var/lib/buildkite-agent/builds/buildkite-builders-i-00b64917792acc05f-1/materialize/tests/src/dataflow/src/sink/kafka.rs:471
#11 dataflow::sink::kafka::produce_to_kafka::{{closure}}::{{closure}}<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, u64>, u64>> () at /var/lib/buildkite-agent/builds/buildkite-builders-i-00b64917792acc05f-1/materialize/tests/src/dataflow/src/sink/kafka.rs:639
#12 timely::dataflow::operators::generic::builder_rc::{{impl}}::build_reschedule::{{closure}}<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, u64>, u64>,closure-2,closure-0> () at /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/d14afd6/timely/src/dataflow/operators/generic/builder_rc.rs:161
```

**Comment by elindsey** [comment]
Okay I know what's going on now:

You can enable logging by setting `MZ_LOG=debug,librdkafka=debug` and checking `docker logs debezium-avro_materialized_1`, that shows that we're repeatedly timing out when trying to init transactions with Kafka.

That timeout is slowly eating through the operator's fuel, so leads to a loss of interactivity which is why the select hangs. Not a full deadlock, but we starve all other work from the system as we slowly timeout up to some very high amount of time.

The reason we time out is because the Kafka cluster is unhealthy and doesn't have enough members to support a txn coordinator. It looks like librdkafka doesn't give us a good error in this case, instead timing out the blocking txn init call. I would've expected the FindCoordinator response to include an error code and for that to be presented as the return of init_transactions, instead this is all we get:
```
librdkafka: RECV [thrd:kafka:9092/bootstrap]: kafka:9092/1001: Received FindCoordinatorResponse (v2, 27 bytes, CorrId 3, rtt 2.25ms)
ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u3 in state Init at time 1623429931599 : Transaction error: Failed to initialize Producer ID: Local: Timed out  
```

The fix for this test is to set `KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1` in the env of the Kafka docker image (mzcompose.yml) so that a healthy txn coordinator can exist in this single host test cluster. But there seem to be a lot of rough edges here we need to fix.

**Comment by antiguru** [comment]
The current status of the PR is that sinks produce `data_collections` modeled after what we're ingesting and what other Debezium connectors are supposed to produce. Bear in mind there isn't much documentation around the expectations of the `data_collections` schema, so it might still have bugs.

This leads me to the next problem I'm tackling: I believe the pull request should have good testability, which would mean that ideally we can ingest our own sinks, looping them through Kafka. Unfortunately, this is hard at the moment. Our sinks turn the specified `topic` into a unique name, also encoding the dataflow ID, Materialize's startup time, and a nonce. This information is available from the catalog, where in theory we could look it up and use the name to create sources later on.

The complication arises that the test framework currently requires all statements (built-ins, sql, etc.) to be fully expanded before the first one is executed. Only variables known before running any statement can be expanded. A reason for this is that some statements are first undone in order to clean the underlying database. This approach conflicts with determining names at run time. As a result, the topic to create a source from needs to be known ahead of time, before creating the sink.

Going forward, we have several options to resolve the problem. I'm listing my ideas here, but as I'm not very familiar with the internals of Materialize, I can't tell if there are obvious roadblocks.
1. When creating a source, look up the fully-qualified source name in the catalog. If we know it, use the full name, otherwise pass the prefix to Kafka and let Kafka figure it out. This has the downside that we might connect to an unexpected topic if both the topic from our source and an unrelated one exist in Kafka. Also, it would mean we have to execute a SQL statement during planning/pre execution, and I couldn't figure out where to plug it in.
1. Add a custom command to  testdrive to delay evaluating some variables, and add a command to look-up the sink's topic. This conflicts with testdrive's undo mechanism, but creating/reading topics cannot be undone, so the risk is limited. It still delays validating the SQL statement until it is executed.
1. Manually test the integration by running the test outside testdrive. We have all flexibility we want but it doesn't reuse the infrastructure we have. Would prefer not to follow this approach.

I think options 1 and 2 make most sense. Option 2 does not require changes to the core, which might be a plus.

**Comment by antiguru** [comment]
Quick sync with @aljoscha and @uce 
* Use testdrive's seed to create unique topics
* patch topic name generation to use prefix as topic name
* See where ingestion works/fails

**Comment by antiguru** [comment]
Keeping note of how to to a stack trace on all threads:
```
sudo gdb -q --batch -p $(pgrep materialized) -ex "thread apply all bt" > /tmp/gdb.txt
```

**Comment by antiguru** [comment]
I made some progress on this and got the sinks to write expected data to their topic. Ingesting this data still fails. I updated the PR to reflect the latest state.

The PR uses the topic's name as-is for exactly-once sinks. This way we know the name of the topic later for creating a new source. I'm using `test/testdrive/kafka-avro-debezium-sinks-reingest.td` as my primary test case at the moment.

The PR is still in a very much WIP state with debug output all over the place.

Current failure: When reading the data from Kafka, we get a parse failure as below.

Materialized output:
```
2021-06-17T13:13:37.983492Z  WARN interchange::avro::decode: Record with unrecognized source coordinates in materialize.public.input2_primary_idx. You might be using an unsupported upstream database.
```

testdrive output:
```
SELECT * FROM input2;
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 112ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 1s
test/testdrive/kafka-avro-debezium-sinks-reingest.td:184:1: error: executing query failed: db error: ERROR: Decode error: Text: Unexpected bytes remaining for decoded value: [49]
```

**Comment by ruchirK** [comment]
I'm not sure what the WARN log is exactly but I've seen that line before and its spurious. you might have better luck if you specify `WITH (deduplication='none')` - I think the default codepath expects some other debezium fields that the sink doesn't emit. at least, I ran into that here https://github.com/MaterializeInc/materialize/blob/main/test/kafka-exactly-once/before-restart.td#L143-L150

**Pull request closed without merging**
