### PR TITLE
adapter: restore optimize lir and fix read holds

### PR DESCRIPTION
**Pull request by mjibson**
Restore optimize lir and fix read hold acquiring.

### Motivation

  * This PR fixes a recognized bug.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - n/a

### CODE REVIEW

**Comment by mjibson** [comment]
Might need to revert #24703 for this.

**Review by aalexandrov — APPROVED** [review]
Thank you, Matt! The code changes look good, but there are still some tests failing. I'm not sure whether these indicate further errors or things test assumptions that are no longer valid.

Once the tests are fixed it would be good to run a couple of nightly builds with at least [the stages selected here](https://buildkite.com/materialize/nightlies/builds/6174) using https://trigger-ci.dev.materialize.com/ in order to ensure that this the fix works as expected.

**Review by ParkMyCar — APPROVED** [review]
Fantastic!

**Comment by mjibson** [comment]
My commit was overzealous and removed more checking than intended. Reworked and is much simpler now (mostly a removed if statement).

**Comment by mjibson** [comment]
Running nightlies at https://buildkite.com/materialize/nightlies/builds/6218

**Pull request merged**
