### PR TITLE
ci: save docker stats as artifact

### PR DESCRIPTION
**Pull request by nrainer-materialize**
Not sure yet if this is helpful as it is.

Future work:
* We should collect the stream (instead of the snapshot at the end) in a proper way.
* Furthermore, we might want to trigger this directly from the bounded-memory check to capture data per scenario.
* Moritz suggested to read the `max-rss` property.

### CODE REVIEW

**Review by bobbyiliev — APPROVED** [review]

**Comment by def-** [comment]
For the max-rss the end should be fine-ish? (Modulo restarts)

For continuous collection we can run it in the command instead of post-command, in the background (`&` and without `--no-stream`), and then upload the final result after killing it. I'll try implementing this now.

**Comment by def-** [comment]
Actually, what is the use case for this? For bounded-memory tests I found using the continuous memory profiling in trigger-ci to be more useful

**Comment by nrainer-materialize** [comment]
> continuous memory profiling

This is something we actively need to enable, right? I thought this approach would be a quick win for bounded-memory and other OOMs.

**Comment by def-** [comment]
Currently yes, but with some more effort I think I could auto-enable it in all runs without too much spam.

**Pull request merged**
