### PR TITLE
storage: remove unneeded feedback in persist_source

### PR DESCRIPTION
**Pull request by teskje**
This PR removes an unneeded feedback operator from `persist_source` by pulling up a probe instantiation instead.

### Motivation

   * This PR refactors existing code.

### Tips for reviewer

There are a bunch of other feedback operators in the persist source (in `shard_source_desc` and the granular backpressure implementation). Their existence confused me at first because apparently there aren't actually any dataflow cycles in this code. Instead the feedback operators seem to be used to help conveniently structure the code. I bet it wouldn't be too hard to remove them all, but it's not clear this would have enough of a benefit to justify the readability impact.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - N/A

### CODE REVIEW

**Comment by danhhz** [comment]
Change seems good to me on scan, but I'd love to know the history here

**Review by guswynn — APPROVED** [review]
This was probably just a misunderstanding of mine!

**Comment by teskje** [comment]
Wait, @danhhz didn't you introduce this feedback in https://github.com/MaterializeInc/materialize/pull/22549? 😅

**Comment by danhhz** [comment]
> Wait, @danhhz didn't you introduce this feedback in #22549? 😅

Yeah, but that PR was entirely me cargo cult-ing the usage in storage https://github.com/MaterializeInc/materialize/blob/410e7f4bc85070cdf25c50f8badf3f09f42b0bba/src/storage/src/render/sources.rs#L391-L447. I understand how the backpressure works at a conceptual level, but I've never gotten around to wrapping my head around how the code works. That's all Gus and Petros

**Pull request merged**
