### PR TITLE
tests: materialized-view-refresh-options.td: add sleep

### PR DESCRIPTION
**Pull request by nrainer-materialize**
Trying to address the flake in https://buildkite.com/materialize/nightlies/builds/6862#018e33b8-1805-417b-beb4-07da35e9c0b2.

### CODE REVIEW

**Review by def- — APPROVED** [review]

**Comment by ggevay** [comment]
Hmm, but even without the sleep, Testdrive should retry many times and wait quite a long time for the rows to match up, right? Tens of seconds maybe? So I'm a bit worried that there is a bug somewhere that sometimes causes the MV to get into a permanently bad state, in which case no amount of sleeping would help it.

Btw. it's running in release mode, right?

**Comment by ggevay** [comment]
How many CPU cores does the test have access to? I.e., when the test creates 3 replicas, will they be able to run on separate CPU cores?

Also, are the CPUs similar to production CPUs, or can they be of an older generation?

**Comment by ggevay** [comment]
What would be Testdrive's error msg if the first few query attempts return wrong results, but then some subsequent query attempt blocks forever, i.e., doesn't return at all? Is it possible that this is what is happening and Testdrive somehow prints `got:` and then the results from the first few attempts that didn't block?

**Comment by nrainer-materialize** [comment]
Yes, I think this might not have been sensible. Looks as if the failure might be the consequence of an OOM: https://buildkite.com/materialize/nightlies/builds/6862#annotation-018e36c9-6d82-421e-ae32-e6aa07661577-error

**Comment by def-** [comment]
Correct, I opened https://github.com/MaterializeInc/materialize/issues/25983

**Comment by ggevay** [comment]
Thanks! I'll look into the OOM!
So, what might have happened here is that the clusterd crashing caused so much delay that Testdrive timed out in its retry attempts?

**Comment by nrainer-materialize** [comment]
Sounds plausible!

**Pull request merged**
