### PR TITLE
test: remove idle_arrangement_merge_effort.td

### PR DESCRIPTION
**Pull request by teskje**
This PR removes the `IDLE ARRANGEMENT MERGE EFFORT` test.

This test was flaky because it can happen that the `INSERT` that is supposed to trigger the consolidation of the previous insert + retraction arrives at the replica before the index's since has advanced beyond the time of the retraction. In that case, DD cannot merge the retraction into the previous insert, as it has to maintain the historical detail, and no consolidation is triggered.

Setting a logical compaction window of 1ms was supposed to avoid this scenario, but obviously it is not enough. The only way I can think of to ensure that the since has advanced far enough before sending the final `INSERT` is to sleep, which does not seem like a robust solution either.

### Motivation

  * This PR fixes a previously unreported bug.

`idle_arrangement_merge_effort.td` is flaky:

```
> SELECT records, batches FROM mz_internal.mz_arrangement_sizes
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 113ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 22s
^^^ +++
idle_arrangement_merge_effort.td:42:1: error: non-matching rows: expected:
[["1", "1"]]
got:
[["201", "2"]]
Poor diff:
- 1 1
+ 201 2
```

### Tips for reviewer

Let me know if you can think of another way to test that the `IDLE ARRANGEMENT MERGE EFFORT` config option is indeed applied to the replica. The only way I can think of is writing a dedicated mzcompose test to inspect the debug logging of that replica, which feels quite unclean to me.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a
  companion cloud PR to account for those changes that is tagged with
  the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - N/A

### CODE REVIEW

**Review by philip-stoev — APPROVED** [review]
If you would like to keep the test, I think sleeping would be justified in this situation ... you could also mess with failpoints and such, but that would be too much to ask for such a simple test.

**Comment by teskje** [comment]
I'm a bit worried that sleeping could introduce timing-based flakiness. But maybe it would also be fine. We could test it out, but let's wait what @vmarcos thinks of this!

**Review by vmarcos — APPROVED** [review]
I agree with @philip-stoev here that it would be OK to add a sleep if you'd like to keep the test active. To avoid flakiness, the issue is setting a high enough sleep time, in the seconds, by the argument that something would be really wrong if nothing happened in such a large interval. That has the disadvantage of costing waiting time in CI, so I am not sure how bad that is.

Another option is to change a bit the predicates being asserted at the end of the test. It sounds like you can observe the arrangement sizes of the cluster without idle merge effort without having to wait. Then, you could observe the other cluster and assert instead that the records in arrangements there are a smaller value than in the cluster without idle merge effort (i.e., _some_ merging occurred, not necessarily enough merging to get to the minimal size). Together with perhaps adding a bit more data, this might do the trick with very small sleep times or even no sleep times in the test at all. Note that to "save" the value you observed for the cluster without idle merge effort, you could insert it as a row in a test-specific table, for example.

Would any of these options be reasonable or would it be preferable instead to remove the test?

**Comment by teskje** [comment]
Thanks Marcos! I'll give it another look tomorrow, but let's merge this now to stop the flaking for everyone!

**Pull request merged**
