### PR TITLE
Add support for MySQL in testdrive and mzcompose

### PR DESCRIPTION
**Pull request by philip-stoev**
Which of the following best describes the motivation behind this PR?

  * This PR adds a feature that has not yet been specified.

Support for MySQL in testdrive and mzcompose is needed in order to have a functional end-to end test for MySQL+Debezium+Materialize using the `test/debezium-avro` approach that is already used for testing Postgres and SQL Server. 

The actual mzworkflows.py and test content will come in a separate PR.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/9825)

### CODE REVIEW

**Comment by benesch** [comment]
The testdrive stuff LGTM but we've got some duplicate dependencies to fight. I think if we get `mysql_common` to upgrade to the latest version of `sha2` and `bindgen`, that'll cover most of it. We also need Tokio itself to upgrade to `mio` v0.8, but that just merged, so hopefully we'll get a release of Tokio with that bump soon.

**Comment by benesch** [comment]
I'm happy to help with making those dependency bump PRs upstream, if you'd like!

**Comment by benesch** [comment]
I sent https://github.com/blackbeam/rust_mysql_common/pull/55 upstream. That eliminates all the duplicate dependencies except for mio v0.8. We're waiting on Tokio v1.16 to upgrade to mio v0.8, but that should drop hopefully sometime in the next few weeks. They release about once a month, and it's been 20 days since their last release.

**Comment by philip-stoev** [comment]
@benesch Thanks a lot ! I will wait for all the ducks to line up before I merge.

**Comment by benesch** [comment]
Just to be clear the only blocker is Tokio; depending on a non-stable Tokio release is kind of scary. But we can totally point at a fork of the mysql library since it's not clear when the PR will be merged.

**Comment by philip-stoev** [comment]
The  blackbeam/rust_mysql_common#55  PR has been merged

**Comment by philip-stoev** [comment]
@benesch can I point rust_mysql_common to a specific SHA? They seem to only release once every couple of months, and I would like to move MySQL+Debezium testing along.

**Comment by benesch** [comment]
Yep, that's no problem at all! We'll still have to figure out what to do with the lack of a Tokio release, but I'd say point at the latest master for mysql_common and we'll see what `cargo deny` complains about.

By the way, no need to pin at a particular SHA explicitly. If you just point at the Git repo in Cargo.toml, then Cargo.lock will do the work of actually writing down the full SHA that it picked (and you can use `cargo update -p mysql_common --precise BLAH` if it picks the wrong one).

**Comment by philip-stoev** [comment]
@benesch: With mysql_common taken from HEAD of their git repository, we are down to only the `mio` warning  . However, tokio-rs have reverted their move to mio 0.8.0:

**Comment by benesch** [comment]
I saw that. Too bad! Let’s just allow the duplicated mio dependency in
deny.toml for now.

**Comment by philip-stoev** [comment]
@benesch if you can review the cargo bits that I added that would be much appreciated!

**Comment by philip-stoev** [comment]
I am going to apply the principle of silent consent here and merge this before it has suffered any bit rot.

**Pull request merged**
