### PR TITLE
compute: move `mz_dataflow_initial_output_duration_seconds` metric to the controller

### PR DESCRIPTION
**Pull request by teskje**
This PR moves the `mz_dataflow_initial_output_duration_seconds` metric from being a replica export to a controller export. The main benefit we get from this is that the `worker_id` label is removed, which both makes the metric easier to use and greatly reduces its cardinality.

As part of this change, this PR:
* Removes the infrastructure for per-collection metrics from the replica code, as it would be unused otherwise. This mostly reverts https://github.com/MaterializeInc/materialize/pull/20126 (sorry for the churn!).
* Adds an mzcompose test for the controller-exposed metrics.

### Motivation

  * This PR adds a known-desirable feature.

Part of https://github.com/MaterializeInc/materialize/issues/18745.
Design doc: https://github.com/MaterializeInc/materialize/pull/19717.

### Tips for reviewer

Look at the commits separately!

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - N/A

### CODE REVIEW

**Review by vmarcos — APPROVED** [review]
Looks fine to me, thanks!

**Review by def- — APPROVED** [review]
Based on https://buildkite.com/materialize/coverage/builds/214 seems to be covered in tests. Edit: Actually let me rerun, I think there was a problem.

**Comment by teskje** [comment]
> Actually let me rerun, I think there was a problem.

Looks like it finished, but I'm not sure how to interpret the results.

**Comment by def-** [comment]
Rerun seems fine: https://buildkite.com/materialize/coverage/builds/219

**Comment by teskje** [comment]
TFTRs!

**Pull request merged**
