### PR TITLE
catalog: Fix item AST migrations

### PR DESCRIPTION
**Pull request by jkosh44**
Previously, after migrating item ASTs, we would load a temporary catalog with unmigrated items instead of the migrated items. This commit fixes the issue by loading a temporary catalog with the migrated items.

### Motivation
This PR fixes a previously unreported bug.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [X] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [X] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - There are no user-facing behavior changes.

### CODE REVIEW

**Review by ParkMyCar — APPROVED** [review]
Out of curiosity how did we catch this? Is there a regression test we can add?

**Comment by jkosh44** [comment]
> Out of curiosity how did we catch this?

@rjobanp found it when he added a migration here: https://github.com/MaterializeInc/materialize/pull/28493

> Is there a regression test we can add?

Probably not because it requires migrations to exist.

---

@rjobanp, I decided to merge this separately because I'm afraid I'm going to forget about it. Unless you plan on merging your PR soon, then I can close this.

**Comment by rjobanp** [comment]
@jkosh44 waiting for another round of CI on my PR but after that I plan to merge today!

**Comment by jkosh44** [comment]
> @jkosh44 waiting for another round of CI on my PR but after that I plan to merge today!

Ok, I'll hold off on merging this in that case.

**Pull request merged**
