### PR TITLE
version consistency: test explain plans

### PR DESCRIPTION
**Pull request by nrainer-materialize**
### Commits
ed46f617e8 output consistency: query template: extract db_object_name determination
2f0d05b4bd output consistency: output printer: rename variable
5d6e64ee99 output consistency: explain plan: add test support
067a091dd4 output consistency: explain plan: allow configuring
36a83845f6 output consistency: explain plan: result comparator
d05e303752 output consistency: explain plan: ignore filter
a264585ea2 version consistency: fix name in args parser
de2c41e712 version consistency: explain plan: add entry point
b5dd08ce23 version consistency: explain plan: README
a3346019cd version consistency: explain plan: add ignore
3cf9267a64 version consistency: support EXPLAIN PHYSICAL as well

### Nightly
https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Aversion-consistency%2Fexplain-plans

### CODE REVIEW

**Comment by nrainer-materialize** [comment]
The reported issue is likely https://github.com/MaterializeInc/materialize/pull/28144#issuecomment-2232764474 and needs to be ignored.

**Review by def- — COMMENTED** [review]
I think this will be extremely difficult to maintain. Plans will change every time the optimizer changes, what will we do then?

**Comment by nrainer-materialize** [comment]
> I think this will be extremely difficult to maintain. Plans will change every time the optimizer changes, what will we do then?

I will need to get some experience how often this happens in practice. This test should also help us identify unexpected plan changes.
If there are mismatches, we can easily add (coarse-) grained ignores for certain versions. Furthermore, if beneficial, we can normalize explain plans (e.g., remove arity information).

**Comment by nrainer-materialize** [comment]
TODO: also support `EXPLAIN PHYSICAL PLAN`

**Comment by ggevay** [comment]
> I think this will be extremely difficult to maintain. Plans will change every time the optimizer changes, what will we do then?

I have the same concern.

> This test should also help us identify unexpected plan changes.

You mean catching those situations when a PR is not intending to make any plan changes or EXPLAIN changes, but are making them due to a bug? I think those situations are quite rare, because the optimizer / EXPLAIN code is somewhat isolated from the rest of the codebase, so surprising interactions are rare.

So, it's not just how often plans change, but the concern is that the false positive rate divided by the true positive rate might be quite high: Some PRs are not intended to make plan or EXPLAIN changes, but some do, and
- those that do intend to make plan or EXPLAIN changes will almost always be flagged by a randomized testing (lots of false positives);
- those that are not intended to make plan or EXPLAIN changes probably won't make them by mistake either (few true positives).

There is one situation where I can imagine this to yield true positives: When making a pure refactoring of the optimizer or EXPLAIN, so there are code changes in the optimizer or EXPLAIN but no plans should be changing. How about just running the new randomized EXPLAIN testing manually in such cases, instead of always running it in CI?

**Comment by nrainer-materialize** [comment]
Ok, we can do that. I will remove it from CI.

**Comment by nrainer-materialize** [comment]
Conducted changes since previous review:
* removed from CI
* added support for physical explain plans

**Review by def- — APPROVED** [review]
Fine if not in CI. This is then similar to what Philip was doing with RQG before.

**Pull request merged**
