### PR TITLE
resume ingestions using as_of rather than upper

### PR DESCRIPTION
**Pull request by sploiselle**
### Motivation

refactors the notion of resumption frontiers to be based on an as_of rather than an upper.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by petrosagg — COMMENTED** [review]
From an initial read this doesn't look right. For every ingestion we need to calculate:

* The ingestion-wide `as_of`, defined as the `meet({(upper - 1).advance_by(since) for all exports})`
  * Note that this is unconditional and is the same regardless of the ingestion shape (i.e we shouldn't have any `always_min` flag)
* The per-subsource resumption frontier which is just the upper of the corresponding shard and there isn't any actual calculation needed here.

The code on `main` calls the ingestion-wide `as_of` `resumption_frontier` and the `ResumptionFrontierCalculator` is being used to calculate both. [Here](https://github.com/MaterializeInc/materialize/blob/main/src/storage/src/storage_state/async_storage_worker.rs#L194-L197) you can see the two being conflated. 

This PR changes the calculator to an `AsOfCalculator` but it still carries a `get_uppers` method. This is confusing because uppers are not related to as of frontiers and I didn't follow what happens to the frontiers we report back.

I suggest the following:

1. Get rid of the calculator trait, it doesn't abstract anything and is only adding noise.
2. Rename `AsyncStorageWorkerCommand::CalculateResumeFrontier` to `AsyncStorageWorkerCommand::UpdateFrontiers` and change its handling code to:
    1. Update the ingestion `as_of` based on the  `meet({(upper - 1).advance_by(since) for all exports})` formula
    2. Update the per export resumption frontier to just be the shard upper (perhaps reclocked to the native time domain)
3. Change the `resumption_operator` to take a `ReclockFollower` and to simply reclock the observed uppers to native uppers.

**Comment by petrosagg** [comment]
> The per-subsource resumption frontier which is just the upper of the corresponding shard and there isn't any actual calculation 
needed here.

One detail regarding this point and the `always_min` flag. When we calculate the per-export resume upper this is the moment to set it to the minimum *if* the ingestion dataflow requires a snapshot. In other words it's the per-export upper that gets affected by whether or not the pipeline needs a snapshot

**Comment by sploiselle** [comment]
@petrosagg I had originally opened this to ask for your take on [these lines of
code](https://github.com/MaterializeInc/materialize/pull/20168/files#diff-c5d8a101f2456a4d94e6d40ea2b4132957e7d83f2d0f4e062eafbb95a36f2386R74-R88);
I know you dislike any kind of special-casing of frontiers, so am trying to
determine if the substance of this change is acceptable or not.

Because we need to understand how much of the remap shard we need to load, we
have to consolidate all of the collection uppers into some value--if it's the
meet, we need to filter our minimum values; if it's the join we need to filter
out closed shards.

My thought is that making it the join is preferable because it's more intutive:
we need to know the offset for each export we plan to ingest and we don't plan
to ingest anything from closed subsources.

If we want to make ithe meet, we will need to do work when generating the
per-subsource exports, as well, to cap them all, which is essentially
pre-computing the meet and then applying it...which is the thing we've been
trying to work around.

**Comment by sploiselle** [comment]
I also did not get to refactoring the `resumption_operator`--I have code for that locally but do not want to tie up this review with a change not directly related to the feature at hand.

**Review by def- — COMMENTED** [review]
I'll give this the nightly + coverage treatment:
https://buildkite.com/materialize/nightlies/builds/2668 Edit: Nightly is fine
https://buildkite.com/materialize/coverage/builds/162

**Pull request closed without merging**
