### PR TITLE
Correct type in reachability source

### PR DESCRIPTION
**Pull request by frankmcsherry**
The type was incorrectly set to be a signed integer, and should be unsigned instead.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Review by jkosh44 — APPROVED** [review]

**Comment by teskje** [comment]
The upgrade tests fail because log migration is unimplemented:

```
upgrade-materialized-1  | thread 'main' panicked at 'Log migration is unimplemented', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c00d2f2e4acce022-1/materialize/tests/src/adapter/src/catalog.rs:2724:21
upgrade-materialized-1  | stack backtrace:
upgrade-materialized-1  |    0: rust_begin_unwind
upgrade-materialized-1  |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
upgrade-materialized-1  |    1: core::panicking::panic_fmt
upgrade-materialized-1  |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
upgrade-materialized-1  |    2: mz_adapter::catalog::Catalog<S>::generate_builtin_migration_metadata::{{closure}}
upgrade-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c00d2f2e4acce022-1/materialize/tests/src/adapter/src/catalog.rs:2724:21
upgrade-materialized-1  |    3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
upgrade-materialized-1  |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
upgrade-materialized-1  |    4: mz_adapter::catalog::Catalog<S>::open::{{closure}}::{{closure}}
upgrade-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c00d2f2e4acce022-1/materialize/tests/src/adapter/src/catalog.rs:2384:68
upgrade-materialized-1  |    5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
upgrade-materialized-1  |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
upgrade-materialized-1  |    6: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
upgrade-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
upgrade-materialized-1  |    7: mz_adapter::catalog::Catalog<S>::open::{{closure}}
upgrade-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c00d2f2e4acce022-1/materialize/tests/src/adapter/src/catalog.rs:1968:5
upgrade-materialized-1  |    8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
upgrade-materialized-1  |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
upgrade-materialized-1  |    9: mz_adapter::coord::serve::{{closure}}
upgrade-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c00d2f2e4acce022-1/materialize/tests/src/adapter/src/coord.rs:1041:11
upgrade-materialized-1  |   10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
upgrade-materialized-1  |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
upgrade-materialized-1  |   11: mz_environmentd::serve::{{closure}}
upgrade-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c00d2f2e4acce022-1/materialize/tests/src/environmentd/src/lib.rs:301:7
upgrade-materialized-1  |   12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
upgrade-materialized-1  |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
upgrade-materialized-1  |   13: tokio::park::thread::CachedParkThread::block_on::{{closure}}
upgrade-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/park/thread.rs:263:54
upgrade-materialized-1  |   14: tokio::coop::with_budget::{{closure}}
upgrade-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:102:9
upgrade-materialized-1  |   15: std::thread::local::LocalKey<T>::try_with
upgrade-materialized-1  |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:445:16
upgrade-materialized-1  |   16: std::thread::local::LocalKey<T>::with
upgrade-materialized-1  |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:421:9
upgrade-materialized-1  |   17: tokio::coop::with_budget
upgrade-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:95:5
upgrade-materialized-1  |   18: tokio::coop::budget
upgrade-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:72:5
upgrade-materialized-1  |   19: tokio::park::thread::CachedParkThread::block_on
upgrade-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/park/thread.rs:263:31
upgrade-materialized-1  |   20: tokio::runtime::enter::Enter::block_on
upgrade-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/enter.rs:152:13
upgrade-materialized-1  |   21: tokio::runtime::thread_pool::ThreadPool::block_on
upgrade-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/mod.rs:90:9
upgrade-materialized-1  |   22: tokio::runtime::Runtime::block_on
upgrade-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/mod.rs:484:43
upgrade-materialized-1  |   23: environmentd::run
upgrade-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c00d2f2e4acce022-1/materialize/tests/src/environmentd/src/bin/environmentd/main.rs:715:18
upgrade-materialized-1  |   24: environmentd::main
upgrade-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c00d2f2e4acce022-1/materialize/tests/src/environmentd/src/bin/environmentd/main.rs:424:23
upgrade-materialized-1  |   25: core::ops::function::FnOnce::call_once
upgrade-materialized-1  |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
```

@jkosh44 Any idea what to do about this?

**Comment by philip-stoev** [comment]
The binary itself is panicking as shown above, the test is not doing anything related to mz_internal, it just restarts a new-version binary over an old-version binary. I believe the same panic will happen in production as well. The solution would be to fix the binary by making it not panic in first place.

**Comment by jkosh44** [comment]
Yeah maybe this wasn't fully thought through originally. Even though this is in the internal schema the migration framework still sees that it's changed and tries to migrate it. Then panics when it sees that it's an introspection source.

We could just ignore items in the internal catalog and skip migration for them, but we still need to update the catalog from the old item to the new item.

**Comment by chaas** [comment]
Ah yeah that makes sense, well in that case it's a good thing the upgrade tests caught it :)

**Comment by frankmcsherry** [comment]
I pushed another visible type change, correcting an incorrect `UInt64` which should have been an `Int64`. However, in the process I switched it to be `MzTimestamp` which is the actual type (it was cast from a `mz_repr::Timestamp` to an integer). I'm sure various other stability things churned at the same time, but figured it was good to bundle these changes together (esp as it was still broken without this change).

**Comment by jkosh44** [comment]
@frankmcsherry I opened up a PR against this branch which should fix the issue: https://github.com/frankmcsherry/materialize/pull/2

Normally I would think they should go in separate PRs, but there's no way to test the new migration without a PR like this, so it makes sense to combine them.

**Comment by jkosh44** [comment]
> @frankmcsherry I opened up a PR against this branch which should fix the issue: [frankmcsherry#2](https://github.com/frankmcsherry/materialize/pull/2)
> 
> Normally I would think they should go in separate PRs, but there's no way to test the new migration without a PR like this, so it makes sense to combine them.

Actually I think I will open a separate PR, so there's more eyes on it. https://github.com/MaterializeInc/materialize/pull/15976

**Comment by frankmcsherry** [comment]
Thanks @jkosh44!

**Pull request merged**
