### PR TITLE
[persist] Minor codec/schema cleanups from a branch

### PR DESCRIPTION
**Pull request by bkirwi**
### Motivation

Small fixes found or invented while working on the new columnar format; PRed separately so they don't get lost.

### Tips for reviewer

The first commit adds a new bound to an existing trait, which may be controversial? Otherwise I think these are pretty straightforward.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by danhhz — COMMENTED** [review]
Commits 2 and 3 LGTM.

We've been intentionally avoiding the `Default` bound on `Codec`. I think at some point maybe `SourceData` didn't even impl `Default` (apparently it does now given that this passes CI). I'm still inclined slightly against adding it, but I agree that it certainly makes some things more ergonomic, so I could be convinced if you feel strongly.

**Comment by bkirwi** [comment]
Here is why adding the bound felt good to me:
- Unlike `Codec`, the columnar decoders don't offer a way to get a `T` out of the decoder without having one already: `fn decode(&self, idx: usize, val: &mut T);`. This sort of API is very difficult to use without a default bound!
- Many other Persist APIs are effectively impossible to use without a default bound. For example: while `FetchedPart` itself has no such bound, all the APIs that allow you to get data out of the part _do_, which means that any real-world usage of `shard_source` would require it.

And if the bound is de-facto required, I'd rather tag it on the trait and save some typing! (But if that's not immediately convincing, I'll rebase it out!)

**Comment by ParkMyCar** [comment]
FWIW I'm +1 to adding the `Default` bound on `Codec`, it's been tricky at times (e.g. re-using allocations in `encode_updates(...)`) to work around not having it

**Review by danhhz — APPROVED** [review]
On one hand, the pedant in me wants to point out that the `Default` bound is not _required_ for something like shard_source (and I find "very difficult" to be a bit hyperbolic). It just needs to be able to cough up a `K` and a `V` and they could just as easily be passed in as arguments. Also, from a "strong abstraction boundaries" perspective, persist exists to write down Collections of `K` and `V`, and that shouldn't really require that `K` and `V` implement `Default`.

That said, as I mentioned above, I'm sympathetic to the ergonomics argument! It sounds like the two of you indeed feel strongly about it, so merge away!

**Comment by bkirwi** [comment]
> `Default` bound is not required for something like shard_source

Like, conceptually, I agree - but as far as I can tell it seems true for today's shard_source; that emits `FetchedPart`, and all the data-extracting methods on `FetchedPart` have the bound.

I'm sympathetic to the idea that we should add `decode_owned` to the schema traits, then change `FetchedPart` etc. to not require it! But for now I will merge this and leave that to a potential followup...

**Pull request merged**
