### PR TITLE
feature-benchmark: Add scenario for measuring startup performance

### PR DESCRIPTION
**Pull request by philip-stoev**
A new scenario is hereby added that creates various Mz objects and
then checks the time between restarting Mz and the objects becoming
queryable.

By default 100 materialized sources, 100 sinks , 100 tables and
100 3-table materialized views are created.

In addition:
- it is now possible to have mzcompose operations as part of the workload
  being benchmarked, not just in the init() or before() phases as it was previously.
- the feature-benchmark has been extended to operate on timestamps
rather than measurements. This way, one part of the workload can provide
the start timestamp and another part can provide the end timestamp.
The framework will then calculate the elapsed time.
- the measurement_source.py no longer supports an Iterator interface
- various dead code and debugging aides have been removed

### Testing

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Comment by benesch** [comment]
🎉 

Would it be hard to also have a scenario variant that installs _nothing_, and measures the time until the first `SELECT 1` succeeds?

**Comment by philip-stoev** [comment]
I have force-pushed a change that has 2 scenarios. The new commit message is as follows:

```
     feature-benchmark: Add scenario for measuring startup performance
    
    New scenarios are hereby added that checks the elapsed duration between
    the return of the `docker-compose up` command that is used to start Mz
    and the time Mz begins servicing queries.
    
    The `StartupEmpty` scenario creates no database objects and considers the
    database to be up as soon as SELECT 1 returns.
    
    The `StartupLoaded` scenario creates 100 materialized sources, 100 sinks ,
    100 tables and 100 3-table materialized views. It considers Mz to be up
    once the sources and views start returning at least one row. Tables
    are expected to return 0 or 1 row, as this depends on whether persistence
    is in effect.
    
    In addition:
    - it is now possible to have mzcompose operations as part of the workload
      being benchmarked, not just in the init() or before() phases as it was previously.
    - the feature-benchmark has been extended to operate on timestamps
    rather than measurements. This way, one part of the workload can provide
    the start timestamp and another part can provide the end timestamp.
    The framework will then calculate the elapsed time.
    - the measurement_source.py no longer supports an Iterator interface
    - various dead code has been removed
```

**Comment by philip-stoev** [comment]
@benesch

**Review by benesch — APPROVED** [review]
Am I crazy or is there no `StartupEmpty` scenario? Everything in here LGTM though!

**Comment by philip-stoev** [comment]
@benesch thanks for noticing. I had to force push again. I blame the GitHub outage from yesterday :-)

**Review by benesch — APPROVED** [review]
Awesome!

**Pull request merged**
