### PR TITLE
doc/user: remove preview annotations for promoted features

### PR DESCRIPTION
**Pull request by morsapaes**
Promote stable features marked as { Private | Public } Preview to GA in the user-facing documentation. See [this Notion page](https://www.notion.so/materialize/Private-Preview-PrPr-Public-Preview-PuPR-334538ed627e4760bd485b5e5da7999c) for context.

The corresponding feature flags will be removed as a follow-up.

### CODE REVIEW

**Review by benesch — APPROVED** [review]
LGTM. Have you twiddled the LD flags already? If not we should do that before merging.

**Comment by morsapaes** [comment]
Just did. We should be good to go — thank you!

**Review by benesch — APPROVED** [review]
:shipit:

**Comment by chaas** [comment]
Is it possible this PR accidentally removed `alter_system_set_stmt` and `alter_system_reset_stmt` from sql-grammar.bnf? Looks like those RR diagrams are still used in doc/user/content/sql/alter-system-set.md

**Comment by benesch** [comment]
There was a bit of skew at some point around `alter_system_set_stmt` but I believe it's all been fixed on main?

**Comment by chaas** [comment]
I think those ones are still missing from `sql-grammar.bnf`, but I'm adding them back in https://github.com/MaterializeInc/materialize/pull/26623 (happened to notice when rebasing that PR on main)

**Pull request merged**
