### PR TITLE
feature benchmark: fix regression reporting

### PR DESCRIPTION
**Pull request by nrainer-materialize**
This fault was introduced with 36123b02 on July 24th. It caused no regressions to be reported since then.

### CODE REVIEW

**Review by def- — APPROVED** [review]

**Comment by def-** [comment]
That's not great. I'll trigger a test run of current Materialize against a few versions ago, we might have to open some issues.

**Comment by nrainer-materialize** [comment]
> That's not great. I'll trigger a test run of current Materialize against a few versions ago, we might have to open some issues: https://buildkite.com/materialize/nightly/builds/9571

Yeah, I wanted to discuss this in today's QA sync.

**Comment by nrainer-materialize** [comment]
Though,

> It caused no regressions to be reported since then.

is not correct. It caused not all regressions to be reported.

**Comment by def-** [comment]
These two look serious:
```
NAME                                | TYPE            |      THIS       |      OTHER      |  UNIT  | THRESHOLD  |  Regression?  | 'THIS' is
--------------------------------------------------------------------------------------------------------------------------------------------------------
MySqlInitialLoad                    | wallclock       |           4.379 |           2.397 |   s    |    10%     |    !!YES!!    | worse:  82.7% slower
PgCdcInitialLoad                    | wallclock       |           2.197 |           1.406 |   s    |    10%     |    !!YES!!    | worse:  56.3% slower
```
I guess they have the same root cause, so I'll just bisect it.

**Comment by def-** [comment]
I have managed to bisect it, will open an issue

**Pull request merged**
