### PR TITLE
Update to Rust 1.80

### PR DESCRIPTION
**Pull request by antiguru**
Update to Rust 1.80

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by jkosh44 — APPROVED** [review]
Nice!

**Review by ParkMyCar — APPROVED** [review]
woohoo! thanks for changing the version Bazel uses too :)

**Review by benesch — APPROVED** [review]

**Review by def- — APPROVED** [review]
Build looks fast enough (on aarch64 at least). Please trigger nightly before submitting or ping me when the entire build is green.

**Comment by benesch** [comment]
This one looks legit:

```
error[E0635]: unknown feature `stdarch_arm_crc32`
  --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/crc32c-0.6.5/src/lib.rs:23:60
   |
23 | #![cfg_attr(all(target_arch = "aarch64", nightly), feature(stdarch_arm_crc32))]
```

Maybe something fixable by bumping the crc32c verison?

**Pull request merged**
