### PR TITLE
coord,dataflow: allow control of librdkafka debug logs with MZ_LOG

### PR DESCRIPTION
**Pull request by benesch**
When MZ_LOG=librdkafka=debug, we enable the `debug` option for
librdkafka, so that we can get greater insight into what librdkafka is
doing.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/3070)

### CODE REVIEW

**Comment by wangandi** [comment]
@ruchirK had mentioned to me before that you could see specifically Kafka logs with MZ_LOG="librdkafka=trace,rdkafka=trace,info". What is the difference between "librdkafka=trace" vs "librdkafka=debug"?

**Comment by benesch** [comment]
I believe you needed to manually edit the Kafka source to set the debug parameter to "all", unless there is a secret feature that I'm not aware of.

**Comment by benesch** [comment]
Ruchir has confirmed. `MZ_LOG=librdkafka=trace,info` means "log all messages from librdkafka whose level is trace or higher." librdkafka never logs anything at trace. By default it won't log anything at debug, either, but if you set `debug=all` it will. Previously you had to edit the source code to set `debug=all`. Now we autodetect if you've requested the debug (or trace) log level for librdkafka via MZ_LOG, and if so set `debug=all` automatically, so that you actually get to see the logs you wanted to.

**Comment by ruchirK** [comment]
+2 :) thanks for pushing this out

**Comment by benesch** [comment]
Awesome thanks for the review!

**Pull request merged**
