### PR TITLE
Fold permutations into MFPs; determine which arrangement to use during planning rather than implicitly during rendering.

### LINKED ISSUE #8932: Push permutations into MFPs
Push projections into MFPs that wrap access to arranged data. There are some moments where we access arranged data without an MFP, but imo this should be considered a smell (copying entire rows, without first filtering and projecting them down).

This is a follow-up from #6672 and #8718.

### PR DESCRIPTION
**Pull request by umanwizard**
Fixes #8932.

The basic idea is to push permutations into MFPs during planning, rather than during rendering as is done now.

This requires us to know at planning time which arrangement will ultimately be read from (in order to apply the proper permutation).

A few caveats apply:

* A few operators (Union, Negate, Threshold, TopK) access their inputs without an MFP, so we need to create a new MFP node during LIR planning just to apply the permutation. This causes the dataflow graphs to become slightly bigger -- now the de-permuting happens in a dataflow operator, not just a function call. Other than that, the same amount of overall work is being done as before.

* In a few cases (for example, the ArrangeBy operator) we create a set of output arrangements from a set of input arrangements -- these need to perform permutations; the corresponding logic now lives in `CollectionBundle::as_unthinned_collection` which is called by `ensure_arrangements`. Four calls to the latter function exist currently; as a follow-up we can try to see if they can be removed.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/9806)

### CODE REVIEW

**Comment by umanwizard** [comment]
The SLT failure is because I'm not permuting ready_equivalences when building a join closure. Will fix today.

**Review by antiguru — APPROVED** [review]
On a first look, this looks good! I left some minor comments.

The change raises some follow-up work where all operators should be able to absorb MFPs to avoid the additional dataflow operator.

**Comment by philip-stoev** [comment]
@umanwizard had a slip of the tongue and mentioned that this is "intricate". Therefore I am adding myself to this PR for some randomized testing.

**Comment by umanwizard** [comment]
@philip-stoev that would be appreciated !

**Comment by philip-stoev** [comment]
@umanwizard you should not attend a Zoom call without your layer present :-) Never talk to the FBI, even if it is just about clearing up this small misunderstanding ...

Item No 1:

```
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

CREATE TABLE t1 (f1 INTEGER, f2 INTEGER);
CREATE TABLE t2  (f1 INTEGER, f2 INTEGER);

SELECT 1 FROM t1  RIGHT  JOIN (  SELECT 1 FROM t2  )  ON  NULL  WHERE f2  IN (  9  ,  0  )  OR  0  <  ALL (  SELECT agg1  NULL FROM (  SELECT MAX(  3  ) agg1  FROM (  SELECT  FROM t1  )  GROUP  BY  TRUE  )  )  GROUP  BY  TRUE;
```

Produces:

```
2022-01-06T10:02:01.922551Z ERROR panic: Arrangement alarmingly absent!: 1, []
thread: timely:work-0
location: src/dataflow/src/render/join/delta_join.rs:73:37
version: 0.14.1-dev (71865c20c7d6e13f5de6723c468604933a28666b)
backtrace:
   0: materialized::handle_panic
   1: core::ops::function::Fn::call
   2: std::panicking::rust_panic_with_hook
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:628:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:521:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
   5: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   6: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   7: dataflow::render::join::delta_join::<impl dataflow::render::context::Context<G,repr::row::Row,u64>>::render_delta_join::{{closure}}::{{closure}}::{{closure}}
   8: alloc::collections::btree::map::entry::Entry<K,V>::or_insert_with
   9: dataflow::render::join::delta_join::<impl dataflow::render::context::Context<G,repr::row::Row,u64>>::render_delta_join::{{closure}}
  10: timely::dataflow::scopes::Scope::region_named
  11: dataflow::render::join::delta_join::<impl dataflow::render::context::Context<G,repr::row::Row,u64>>::render_delta_join
  12: dataflow::render::<impl dataflow::render::context::Context<G,repr::row::Row,u64>>::render_plan
  13: dataflow::render::<impl dataflow::render::context::Context<timely::dataflow::scopes::child::Child<G,<G as timely::dataflow::scopes::ScopeParent>::Timestamp>,repr::row::Row,u64>>::build_object
  14: timely::dataflow::scopes::Scope::region_named
  15: timely::worker::Worker<A>::dataflow_core
  16: dataflow::render::build_dataflow
  17: dataflow::server::Worker<A>::handle_command
  18: dataflow::server::Worker<A>::run
  19: std::sys_common::backtrace::__rust_begin_short_backtrace
  20: core::ops::function::FnOnce::call_once{{vtable.shim}}
  21: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys/unix/thread.rs:106:17
  22: start_thread
             at /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477:8
  23: clone

```

**Comment by philip-stoev** [comment]
Item No 2. I am not sure if this is the expected outcome of this PR, but the dataflow graph of this query:

```
create materialized view v1 as select  f1, count(*) from t1 group by f1 order by f1;
```

still shows 3 indexes being brought in to answer it, even though only one can possibly be used, due to the lack of joins or any other complication in the query.

Screenshot from 2022-01-06 13-05-16

**Comment by philip-stoev** [comment]
Item No 3. With this dataset:

```
DROP TABLE t1;
CREATE TABLE t1 (f1 INTEGER, f2 INTEGER);
CREATE INDEX t1i1 ON t1(f1);
CREATE INDEX t1i2 ON t1(f2);
```

I get the following difference in the physical plans between this PR and the prior commit:

```
EXPLAIN PHYSICAL PLAN
   FOR SELECT *
  FROM t1
 WHERE f2 = 1;

--- 6875.out	2022-01-06 12:46:48.225399899 +0100
+++ 16875.out	2022-01-06 12:46:48.261400568 +0100
@@ -16,12 +16,12 @@
       "expressions": [],
       "predicates": [
         [
-          1,
+          2,
           {
             "CallBinary": {
               "func": "Eq",
               "expr1": {
-                "Column": 0
+                "Column": 1
               },
               "expr2": {
                 "Literal": [
@@ -47,8 +47,8 @@
         ]
       ],
       "projection": [
-        1,
-        0
+        0,
+        1
       ],
       "input_arity": 2
     },
```

This diff is safe, right? Even though it was previously Column: 1 and is now Column: 0 ?

**Comment by philip-stoev** [comment]
Item No 4. This PR has no dedicated tests -- it is only because we had couple of unrelated ```EXPLAIN PHYSICAL PLAN``` statements in our SLT that it shows as a difference in the tests. I think it is important to have a targeted tests with the physical plans manually validated for correctness. Since the physical plans are quite verbose, maybe a rust unit test that can probe for the desired fragements of the plan would be more suited than SLT?

**Review by philip-stoev — APPROVED** [review]
So:

- the panic reported appears to affect only queries with scalar subqueries with ANY or ALL
- no other panics
- no wrong results
- the product limits test, which involves many-table, many-index and many-column queries passes
- the feature benchmark does not report any regressions

**Comment by umanwizard** [comment]
@philip-stoev TYVM for the help -- I will look into that crashing query. Next time if I have something this "intricate" I will engage you sooner. (it's better to cooperate with the FBI early, rather than take one's case to trial)

**Comment by umanwizard** [comment]
@philip-stoev Actually, that query you found is failing even on origin/main for me. Can you confirm?

**Comment by philip-stoev** [comment]
@umanwizard many apologies for not verifying the panic against main. I sort of saw a new panic around arrangements and naively assumed it is specific to this PR, as the same test (same RQG grammar but not the same PRNG seed) has been run against main many times in the past without this panic.

Apologies for nerd-sniping you on this and thanks for the discussion/fix.

**Comment by umanwizard** [comment]
Sorry for the long delay in publishing this; @frankmcsherry it should be ready for another look.

I've refactored it in the following ways:

1. Permuting maps are always generated at the same point as thinning
   expressions, to ensure that if we refactor the relevant function,
   the logic will not get out of sync. There is a caveat; see below
   for details.

2. We know, without exception, know during LIR planning which "form" of a collection should be used.
   "Form" means either the raw, unarranged collection, or a collection arranged by
   a particular key and requiring a particular permutation to access it.
   I have invented the terminology "collection form" here and am happy to change it
   if a better term is discovered.

3. We now explicitly track the information of whether the "raw" form is available,
   rather than implicitly assuming it is available whenever no arranged keys are available.
   Thus in LIR planning we pass around a an `AvailableCollections` object representing
   a set of forms rather than simply a `Vec` of keys.

4. We now never create arrangements during rendering if they are not explicitly named in LIR.
   Instead, we create them by creating the necessary ArrangeBy node during LIR planning;
   i.e., we do for every operator that relies on an unplanned arrangement
   what was done in https://github.com/MaterializeInc/materialize/pull/10021
   for delta joins.
   The exception is arrangements that can't be named in LIR, currently just the
   arrangement of the `stream` collection for joins.

5. `ArrangeBy` can now turn an arbitrary set of forms into another arbitrary set of forms.
   To put that more concretely: it is now able to form the raw collection from an arranged
   collection, and not just the other way around. Perhaps we could come up with some
   more accurate name for it than `ArrangeBy`.

## Caveats:

1. We don't communicate the permutation/thinning information across different
   acts of building dataflows.
   If we export an index with a given key from one dataflow, we only save the key,
   and then re-form the permutation when we import it into another dataflow.
   This would break if, for example, we come up with some other function that creates
   permutations in some other way, and only use it for some dataflows, but forget to
   account for that at the site where we re-form the permutation. This seems unlikely
   to cause problems in the foreseeable future, but it should still be fixed for reasons of
   code elegance/clarity; doing so will probably require storing the permutations in
   the catalog and DataflowDescription.

2. We are still passing around a column permutation `HashMap`, rather than a `MapFilterProject`
   as I had hoped we could do. The reason we can't do so is because there are a few cases where
   we need to permute something that isn't an MFP. For example, we need to permute each of
   a `FlatMap`'s input expressions.

3. I haven't yet attempted to fix the internal logging dataflows, so they still use
   the otherwise-irrelevant `make_thinning_expression` function,
   but I will do so as a quick follow-up (hopefully before landing this PR)

**Review by frankmcsherry — APPROVED** [review]
This sounds great; thanks very much!

**Comment by umanwizard** [comment]
I will wait for the full SLT run to finish before landing this: https://buildkite.com/materialize/sql-logic-tests/builds/5155

**Pull request merged**
