### PR TITLE
[optimizer] Signal a typechecking error when Dummy escapes MIR

### PR DESCRIPTION
**Pull request by mgree**
Following up on https://github.com/MaterializeInc/materialize/pull/30851, the final `Typecheck` pass (at the end of the physical optimizer) will signal error if any `Dummy` values have persisted.

NB that errors in `Typecheck` do _not_ prevent running the query itself, but will simply mean logging an error.

The test run is green, with no evidence of the error firing in sqllogictest or the testdrive tests. Watching for this error will let us identify the queries that have been having `Dummy` values---or, at least, those queries that are going through the main MIR optimizer.

### Motivation

  * This PR fixes a recognized bug.

https://github.com/MaterializeInc/database-issues/issues/8837
https://github.com/MaterializeInc/database-issues/issues/6471

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

**Review by ggevay — APPROVED** [review]
Thank you!

> The test run is green, with no evidence of the error firing in sqllogictest or the testdrive tests. 

What is a good way to know whether this happened in a CI run? Even the `severe` version of `type_error` seems to just log an error (rather than e.g. `soft_panic!`ing), so it probably wouldn't fail a CI run.

**Review by ggevay — COMMENTED** [review]
Wait, actually, I tried this now with a dummy, and I can't find any log msg from this.

**Comment by ggevay** [comment]
So, what I did, is to comment out the call to `ProjectionPushdown` in `src/transform/src/lib.rs`, and then start the system locally and give it the query from `demand.slt:34`. I'm not seeing any log msg that is coming from the typechecking.

**Comment by ggevay** [comment]
Ok, I know what the problem is: The new code is checking for dummies only in `MRE::Constant`, but it usually appears in stuff like `Map` exprs, e.g. for the above repro:
```
                               Optimized Plan                               
----------------------------------------------------------------------------
 Explained Query:                                                          +
   Finish limit=43 output=[#0..=#3]                                        +
     Return                                                                +
       Project (#1..=#4)                                                   +
         Map (833564499, null, null, 2024-12-18 12:54:29.994 UTC)          +
           TopK limit=90                                                   +
             Union                                                         +
               Map (dummy)                                                 +
                 Get l0                                                    +
               Map (null)                                                  +
                 Union                                                     +
                   Negate                                                  +
                     Get l0                                                +
                   Constant                                                +
                     - ()                                                  +
     With                                                                  +
       cte l0 =                                                            +
         Distinct project=[]                                               +
           TopK limit=13                                                   +
             Project ()                                                    +
               Filter error("timestamp out of range")                      +
                 ReadIndex on=mz_columns mz_columns_ind=[*** full scan ***]+
                                                                           +
 Used Indexes:                                                             +
   - mz_catalog.mz_columns_ind (*** full scan ***)                         +
```

**Review by ggevay — CHANGES_REQUESTED** [review]
see above

**Comment by ggevay** [comment]
You could instead call `MRE::visit_scalars`, and then in each scalar look for `MSE::Literal` involving a dummy.

**Comment by mgree** [comment]
Oh! Good point. Revised to be much more thorough---correctly catches the case you pointed out.

**Review by ggevay — APPROVED** [review]
Thank you!

**Pull request merged**
