### PR TITLE
Downgrade capabilities after sending Kinesis data

### PR DESCRIPTION
**Pull request by JLDLaughlin**
Found another bug testing!

### The Issue
I was downgrading the Kinesis source operator's capabilities before sending its data, resulting in views' data always being one capability behind real-time results.

Caught this testing locally, confirmed fix locally.

I've also added a preemptive call to `downgrade_capability` in Kinesis' `tick` closure. For the purpose of potential joins, it seems important that we continue to update the capability of this source. Would love extra eyes on that part, though!

### CODE REVIEW

**Comment by frankmcsherry** [comment]
Random comment / question: 

You should be able to downgrade the capability once per invocation, at the end of the closure. Doing so more frequently in the body doesn't get communicated outward any more frequently (timely observes the current value when the closure returns).

If it is important to produce different timestamps for each record, the repeated downgrades do something semantically meaningful, but I bet folks would be plenty happy with just using the original value of the capability as the time and then a single downgrade at the end.

**Comment by JLDLaughlin** [comment]
Thanks, @frankmcsherry! I hadn't realized this part:

> Doing so more frequently in the body doesn't get communicated outward any more frequently (timely observes the current value when the closure returns).

I will change the code to do that for now, but will keep the alternative in mind moving forward.

**Comment by frankmcsherry** [comment]
It seems like it is also possible that `downgrade_capabilities` will not actually downgrade a capability (because milliseconds have not advanced) and in that case the data will be stalled for .. maybe 200ms or so. It should be possible to reactivate more promptly in that case.

**Comment by JLDLaughlin** [comment]
> It seems like it is also possible that downgrade_capabilities will not actually downgrade a capability (because milliseconds have not advanced)

Even if I only call it once per tick?

**Comment by JLDLaughlin** [comment]
For posterity, @frankmcsherry has more thoughts about the construction of this source that I will address in additional PRs.

**Pull request merged**
