### PR TITLE
persist: avoid overwriting meta in storage with exactly the same bytes

### PR DESCRIPTION
**Pull request by danhhz**
This introduces a performance and write amplification optimization
that avoids writing out to META if what we're writing matches what's
already in storage.

    indexed_write_drain/file_sorted/23000000
                            time:   [171.36 ms 172.77 ms 173.90 ms]
                            thrpt:  [126.14 MiB/s 126.96 MiB/s 128.00 MiB/s]
                     change:
                            time:   [-23.877% -22.099% -20.431%] (p = 0.00 < 0.05)
                            thrpt:  [+25.677% +28.368% +31.367%]
                            Performance has improved.

    indexed_write_drain/file_unsorted/23000000
                            time:   [185.01 ms 190.43 ms 197.72 ms]
                            thrpt:  [110.94 MiB/s 115.18 MiB/s 118.56 MiB/s]
                     change:
                            time:   [-22.737% -19.014% -15.377%] (p = 0.00 < 0.05)
                            thrpt:  [+18.171% +23.478% +29.428%]
                            Performance has improved.

### Motivation

  * This PR adds a feature that has not yet been specified.

### Tips for reviewer

I ran the background persisted system tables test with and without this change. Initially I didn't see much of a difference, but Ruchir reminded me in the PR comments that the need_step logic we have in RuntimeImpl is a workaround for exactly this issue. With the following diff applied (which more simply runs drain_pending and drain_unsealed each time though the runtime loop, but leaves compaction behind need_step since it's still overaggressive without it) we see much different results. After a few minutes of running the test:

Before this commit:
mz_persist_blob_meta_write_bytes 363620704
mz_server_metadata_seconds{...} 701.15673625
363620704 bytes / 701.15673625 s = 518 kBps

With this commit:
mz_persist_blob_meta_write_bytes 108652344
mz_server_metadata_seconds{...} 796.781403208
108652344 bytes / 796.781403208 s = 136 kBps

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [N/A] This PR adds a release note for any
  [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

**Review by ruchirK — APPROVED** [review]
LGTM!

re: it not showing up as a perf improvement in mz -- it possible that its being covered up by the `need_step` optimization in runtime?

**Comment by ruchirK** [comment]
Also, I'm a little bit surprised by the improvement in the benchmarks because the benchmarks just call `write` and then `drain_pending` in a loop -- so it seems like the `try_set_meta` call inside `drain_pending` should always have real work to do (because we minted new unsealed batches), so it shouldn't be hitting this optimization?

wdyt am i missing something?

**Comment by danhhz** [comment]
> re: it not showing up as a perf improvement in mz -- it possible that its being covered up by the need_step optimization in runtime?

**Comment by danhhz** [comment]
Okay sanity checked my benchmark results by closing a bunch of open stuff on my laptop and running them again. Got similar results.

Looked at the code and it seems that the indexed_* benchmarks are calling `write` within `block_on_drain`, which internally calls `step` (not just a bare`drain_pending`). Given that the writes are never sealed, the `drain_unsealed` and `compact` parts of `step` have nothing to do. I _think_ we were doing the right thing in `compact` before this PR, but `drain_unsealed` is certainly becoming a no-op on each of those calls now, whereas before it was indeed overwriting an identical META.

Also, anecdotally, if I apply the following diff, then `cargo test -p persist --bench writer -- indexed` hits the panic and crashes out.

```diff
diff --git a/src/persist/src/indexed/mod.rs b/src/persist/src/indexed/mod.rs
index 81fe4a18e..b3ca112c4 100644
--- a/src/persist/src/indexed/mod.rs
+++ b/src/persist/src/indexed/mod.rs
@@ -269,7 +269,7 @@ impl<L: Log, B: Blob> Indexed<L, B> {
             // those checks would be difficult to maintain (and bugs in them
             // would surface as either unnecessary storage usage or correctness
             // issues).
-            return Ok(());
+            panic!("boom");
         }
         if let Err(e) = self.blob.set_meta(&new_meta) {
             // We were unable to durably commit the in-memory state. Revert back to the
```

**Comment by danhhz** [comment]
TFTR!

**Comment by ruchirK** [comment]
That makes total sense, thanks for double checking! I forgot that the benchmarks call `step`.

**Pull request merged**
