### PR TITLE
materialized: memory visualization page

### LINKED ISSUE #4226: Graphical UX for dataflows
Materialize produces raw tabular data about the dataflow graphs that it manages, their structure, and resources associated with each of the operators. These data are valuable, but hard to consume in their raw form. 

Materialize would likely benefit from a more graphical navigable interface to this information. For example, we could present the list of running dataflows with their accumulated resource uses, with the ability to expand out dataflow to their constituent operators and nested regions. We could also present dataflow graphs for each of the dataflows, perhaps annotated with resource usage, or progress frontiers, or other useful information.

There is some design work to do to determine what facets are useful, but it feels like several of these options would be excellent starting points even if we quickly conclude they should be improved.

---

Information about dataflow structure can be found in the `mz_catalog` sources:
```
mz_dataflow_channels
mz_dataflow_operator_addresses
mz_dataflow_operators
```
The `_operators` and `_channels` collections name operators and the edges between them. The `_addresses` relation describes the hierarchical relationship these share. There are some idiosyncrasies, mainly that dataflow edges that cross levels of the hierarchy go through a phantom "operator zero" in each scope, whose inputs and outputs correspond to the outputs and inputs (respectively) of the containing scope.

---

For prior work on graph drawing timely dataflow graphs, consider https://github.com/TimelyDataflow/diagnostics

### PR DESCRIPTION
**Pull request by mjibson**
This is a rudimentary but useful memory visualization page. It easily
lists indexes and can graphviz them with record counts per operator. UI
and feature improvements will come over time.

Closes #4226

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4420)

### CODE REVIEW

**Review by benesch — APPROVED** [review]
Seems like a great place to start! :lgtm_strong:

I do wonder if long-term we'll want to use something more purpose built for the web to do the rendering (e.g. D3) rather than this WASMified version of graphviz, but that seems like a problem for alter for sure.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4420#-:-MJ5b6JLE-8kNv_ZOj6T:bz3rz4x)* status: all files reviewed, 3 unresolved discussions (waiting on @mjibson)

___
*[src/materialized/src/http/static/js/memory.jsx, line 31 at r1](https://reviewable.io/reviews/materializeinc/materialize/4420#-MJ5NI2w7fmZbiK2ifSU:-MJ5NI2w7fmZbiK2ifSV:b-p0c0z) ([raw file](https://github.com/materializeinc/materialize/blob/19741b75bd01f323f549bcdcfd85df31e38561aa/src/materialized/src/http/static/js/memory.jsx#L31)):*
> ```JSX
> 			': ' +
> 			text
> 		);
> ```

Seems like an ideal moment for a template string?
___
*[src/materialized/src/http/static/js/memory.jsx, line 434 at r1](https://reviewable.io/reviews/materializeinc/materialize/4420#-MJ5acr57WFQDhV1fEi_:-MJ5acr57WFQDhV1fEia:bep3rwv) ([raw file](https://github.com/materializeinc/materialize/blob/19741b75bd01f323f549bcdcfd85df31e38561aa/src/materialized/src/http/static/js/memory.jsx#L434)):*
> ```JSX
> 
> const content = document.getElementById('content');
> ReactDOM.render(<Views />, content);
> ```

nit: can you rewrite this file and the CSS file to use spaces instead of tabs for consistency with the other JS/CSS Files? I'd say there's probably some plugin you could install to read these sorts of settings out of the .editorconfig in the root of the repository, but if you're still using ACME... then there's probably not.
___
*[src/materialized/src/http/templates/memory.html, line 13 at r1](https://reviewable.io/reviews/materializeinc/materialize/4420#-MJ5JvSQ3nR9uD6XMx6d:-MJ5JvSRCBe0dhp_uYkU:bkcfy2x) ([raw file](https://github.com/materializeinc/materialize/blob/19741b75bd01f323f549bcdcfd85df31e38561aa/src/materialized/src/http/templates/memory.html#L13)):*
> ```HTML
> <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
> 
> <script src="https://unpkg.com/@hpcc-js/wasm@0.3/dist/index.min.js"></script>
> ```

We're using jscdn in flamegraph. I don't particularly care which we use (unpkg seems nice), but we should use either one or the other.

On an unrelated note, I'd like to embed the JS in the binary eventually (see https://github.com/MaterializeInc/materialize/issues/3860), but Brennan has been trying to convince me that using CDNs is okay. Now that you're the third person at Materialize to write some admin UI JS, I'd be curious to hear your take on the matter.

**Review by mjibson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4420)* status: all files reviewed, 2 unresolved discussions (waiting on @benesch)

___
*[src/materialized/src/http/static/js/memory.jsx, line 31 at r1](https://reviewable.io/reviews/materializeinc/materialize/4420#-MJ5NI2w7fmZbiK2ifSU:-MJ80te3E-prjyOC6f3H:b-896fix) ([raw file](https://github.com/materializeinc/materialize/blob/19741b75bd01f323f549bcdcfd85df31e38561aa/src/materialized/src/http/static/js/memory.jsx#L31)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Seems like an ideal moment for a template string?
</blockquote></details>

Done.
___
*[src/materialized/src/http/static/js/memory.jsx, line 434 at r1](https://reviewable.io/reviews/materializeinc/materialize/4420#-MJ5acr57WFQDhV1fEi_:-MJ80Puy6tlxKHQOgHkG:b3oz6pd) ([raw file](https://github.com/materializeinc/materialize/blob/19741b75bd01f323f549bcdcfd85df31e38561aa/src/materialized/src/http/static/js/memory.jsx#L434)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

nit: can you rewrite this file and the CSS file to use spaces instead of tabs for consistency with the other JS/CSS Files? I'd say there's probably some plugin you could install to read these sorts of settings out of the .editorconfig in the root of the repository, but if you're still using ACME... then there's probably not.
</blockquote></details>

Done. I have a configurable little autoformatter thing. I just had to tell prettier to override any CLI config with .editorconfig. Easy!
___
*[src/materialized/src/http/templates/memory.html, line 13 at r1](https://reviewable.io/reviews/materializeinc/materialize/4420#-MJ5JvSQ3nR9uD6XMx6d:-MJ81l7X-edakDCsN5Ll:b-c0toi2) ([raw file](https://github.com/materializeinc/materialize/blob/19741b75bd01f323f549bcdcfd85df31e38561aa/src/materialized/src/http/templates/memory.html#L13)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

We're using jscdn in flamegraph. I don't particularly care which we use (unpkg seems nice), but we should use either one or the other.

On an unrelated note, I'd like to embed the JS in the binary eventually (see https://github.com/MaterializeInc/materialize/issues/3860), but Brennan has been trying to convince me that using CDNs is okay. Now that you're the third person at Materialize to write some admin UI JS, I'd be curious to hear your take on the matter.
</blockquote></details>

Changed to that CDN.

I am generally in favor of embedding JS instead of using a CDN. I am interested in hearing the arguments for not embedding. I think the strongest reasons for us to embed are that it is a much stronger guarantee that any corporate firewall will not prevent the loading of the assets.

I'm also really ok with not changing anything until we can identify a specific problem that would be solved by the solution. Like, sure, maybe a corporate firewall will block an asset. But we are small enough now that it might be a better use of our time to not care until a user reports a problem.

**Review by benesch — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4420)* status: all files reviewed, 1 unresolved discussion (waiting on @mjibson)

___
*[src/materialized/src/http/templates/memory.html, line 13 at r1](https://reviewable.io/reviews/materializeinc/materialize/4420#-MJ5JvSQ3nR9uD6XMx6d:-MJ8UCy17dyaECajKJsK:b8uu1zc) ([raw file](https://github.com/materializeinc/materialize/blob/19741b75bd01f323f549bcdcfd85df31e38561aa/src/materialized/src/http/templates/memory.html#L13)):*
> I am interested in hearing the arguments for not embedding.

The arguments are convenience, mostly. We're neither manually copy/pasting a bunch of JS junk into source control, nor are we introducing NPM/Yarn into the build process.

On a meta-level my philosophies include:

  1. The binary should not depend on external resources like CDNs
  2. Source control should not contain generated code

Copying/pasting a bunch of minified JS into the repository fixes (1) at the expense of (2). Using NPM/Yarn would fix both (1) and (2), but would probably annoy everyone trying to build Materialize.

> I'm also really ok with not changing anything until we can identify a specific problem that would be solved by the solution. Like, sure, maybe a corporate firewall will block an asset. But we are small enough now that it might be a better use of our time to not care until a user reports a problem.

This sounds like a fairly solid approach for now.

**Review by benesch — APPROVED** [review]
Womp, sorry, Reviewable fail. This is very much approved.

> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4420#-:-MJ8V76Y99c-A0_w9mcp:bqchneh)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
