### PR TITLE
persist-txn: Add scenarios around the `lazy` setting

### PR DESCRIPTION
**Pull request by philip-stoev**
Switch between `off`, `eager` and `lazy` either randomly or in this particular order.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by philip-stoev** [comment]
@danhhz all of the persist-txn-related tests seem to work with both `lazy` and `eager`. Should I merge this PR so that some CI jobs start to run with `lazy` in CI?

Note that this does not change the mzcompose-wide default that applies to the entire CI.

**Review by def- — APPROVED** [review]

**Comment by danhhz** [comment]
> @danhhz all of the persist-txn-related tests seem to work with both `lazy` and `eager`. Should I merge this PR so that some CI jobs start to run with `lazy` in CI?
> 
> Note that this does not change the mzcompose-wide default that applies to the entire CI.

I would love to start getting some coverage of lazy in CI! One thing that gives me pause though is that we're still tracking down a hang that seems to repro in nightlies with lazy. So far, nothing is pointing at it being unique to a particular test that only runs in nightlies, so much as something that's always possible but happens to get tickled there more often. So, my worry is that we'll end up with one of these hangs and spend cycles tracking down a known issue.

@aljoscha has been helping me look into the hang while I try to polish up some other last bits of the impl, and has more details than I do at this point about where that investigation is at. I'm happy to leave the judgement call to him on whether it's worth trying to turn on some small bits of coverage or just wait until we're ready to turn it on everywhere

**Review by nrainer-materialize — APPROVED** [review]

**Comment by philip-stoev** [comment]
@aljoscha can you deliver your opinion on the issue above?

**Comment by aljoscha** [comment]
I'd wait until we merge this because of the known hanging issue (which only shows up in nightly, and is hard to reproduce). We figured out the problem now, so it shouldn't take long to deploy a fix.

**Comment by danhhz** [comment]
The fix for the hang was merged earlier today, so I think this is good to go!

**Pull request merged**
