### PR TITLE
sql: store ServerVar default as Owned instead of &'static

### PR DESCRIPTION
**Pull request by danhhz**
Based on a comment, this appears have been added originally to avoid some cloning. But it's somewhat restrictive of how you got the default value and the currently avoided cloning doesn't happen enough in practice to move the needle.

I've got an upcoming PR that reduces LD boilerplate and it isn't able to produce a &'static ref. I was hoping to use that to motivate this commit, but I spent 1/4 of my skunkworks today just rebasing this commit, so pulling it out early. Plus, it looks like Joe also wanted to do this at some point, so it's not just me :).

### Motivation

   * This PR refactors existing code.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by jkosh44 — APPROVED** [review]

**Comment by jkosh44** [comment]
CC @ParkMyCar, you'll probably have some merge conflicts with https://github.com/MaterializeInc/materialize/pull/23903.

**Comment by jkosh44** [comment]
For the record, the reason I was interested in doing this is that certain session variables have default values that cannot be determined at compile time. For example `role` has a default value of the role that initiated the connection.

**Comment by benesch** [comment]
> For the record, the reason I was interested in doing this is that certain session variables have default values that cannot be determined at compile time. For example `role` has a default value of the role that initiated the connection.

I've lost track of the chronology here, but `SessionVar` now has a `default_value` that overrides the compiled-in default. Possibly that postdates the last time you bumped into this, @jkosh44.

**Review by benesch — APPROVED** [review]
Seems like a good change!

**Comment by benesch** [comment]
> I was hoping to use that to motivate this commit, but I spent 1/4 of my skunkworks today just rebasing this commit, so pulling it out early.

Given the high potential for merge conflicts here, I'm going to take the liberty of pressing merge while it's green!

**Comment by danhhz** [comment]
TFTRs and for the merge!

**Pull request merged**
