### PR TITLE
*: deny various *-types deps on mz-persist-client 

### PR DESCRIPTION
**Pull request by danhhz**
Types crates are meant to only depend on other types crates. Context:
https://materializeinc.slack.com/archives/C01CFKM1QRF/p1710871811332209

### Motivation

   * This PR refactors existing code.

### Tips for reviewer

Should be straightforward-ish to go commit-by-commit.

I would remove the `pub use` in persist-txn, but I'd want to merge this with the `pub use` in persist-client. I dislike pub use, but the latter would be a pretty tremendous refactor. We could always do it in a followup.

Moving `ShardId` and `PersistLocation` to persist-types feels fine to me, but moving the persist-txn stuff less so. persist-txn could get its own -types crate, but that feels pretty silly. Curious how others feel on this.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by mjibson — COMMENTED** [review]
Looks reasonable to me!

**Review by bkirwi — APPROVED** [review]
LGTM!

**Comment by danhhz** [comment]
TFTRs!

**Comment by danhhz** [comment]
@MaterializeInc/testing Feel free to ignore the bot here. This PR is just code movement

**Pull request merged**
