### PR TITLE
python: Remove unnecessary f-strings

### PR DESCRIPTION
**Pull request by def-**
We could also enable something like pylint's f-string-without-interpolation / W1309

https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/f-string-without-interpolation.html

### Motivation

   * This PR refactors existing code.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by dehume — APPROVED** [review]

**Review by nrainer-materialize — APPROVED** [review]

**Comment by nrainer-materialize** [comment]
+1 for enabling the linter rule

**Review by philip-stoev — APPROVED** [review]
Yes please enable the linter rule -- if you felt strong enough about this to go through the existing codebase and fix stuff, then we should keep enforcing it going forward.

**Comment by def-** [comment]
It was just a quick grep after I noticed it a few times randomly before.

**Comment by def-** [comment]
New commit with the linter rule added.

**Review by nrainer-materialize — APPROVED** [review]

**Pull request merged**
