### PR TITLE
Add source/sink status_es_ views

### LINKED ISSUE #16584: mz_source|sink_status uses a window function
### What version of Materialize are you using?

v0.35.0-dev

### How did you install Materialize?

Docker image

### What is the issue?

As @frankmcsherry observed, the mz_source|sink views use a window function. This may not be very performant and there is a general drive to disallow window functions until they are fixed.

The canonical way to do the same calulcation would be to use the `SELECT DISTINCT ON (col_name) ... FROM table_name ORDER BY timestamp_col DESC` which will result in an optimized dataflow.

@bkirwi FYI

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by bkirwi**
This changes the plural form of 'status' to the more widely beloved 'statuses', and uses a more efficient encoding of the max-time-per-status query.

### Motivation

Fixes #16584.
First step of #16550 -- I'll need to follow up and delete the old versions once the frontend has caught up with the naming.

(Normally I wouldn't bundle these together, but if I'm adding new views I might as well get the definition right up front.)

### Tips for reviewer

I think the motive is well covered by the linked tickets, but let me know if anything seems obscure.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - Add `mz_{source,sink}_statuses` views to replace the recently-added `mz_{source,sink}_status` views with a more efficient query.

### CODE REVIEW

**Comment by bkirwi** [comment]
The cloudtest failure seems unrelated, FWIW.

**Review by aljoscha — APPROVED** [review]
The view definitions look good! It feels like there is still some discussion about the naming scheme for our internal tables so we might want to wait until that settles down? Also, we might want to change the tests that use `mz_..._status` to the new view?

**Comment by ggnall** [comment]
Ongoing conversation consolidated here: https://github.com/MaterializeInc/materialize/pull/16630/commits/98d4da8d7d563078acea404707c9b7f517aeed3d Based on how that shakes out we may actually keep the original table name (...`status`, but in singular form). Sorry for making a mess here!

> It feels like there is still some discussion about the naming scheme for our internal tables so we might want to wait until that settles down?

**Comment by bkirwi** [comment]
Ah interesting! I'll hold this for now then.

Link to the PR for the curious: https://github.com/MaterializeInc/materialize/pull/16630

And yeah... I was going to follow up with the test changes but if this is blocked I might start sooner.

**Comment by bkirwi** [comment]
It seems like we're probably still going to want `statuses` in the end! I've updated the tests, and also switched to a better filter for "real sources/sinks" that [was discussed in slack](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1670970797953089).

**Pull request merged**
