### PR TITLE
[persist] Use key lower to block on fewer parts in consolidation

### PR DESCRIPTION
**Pull request by bkirwi**
This:
- collects lower-bound stats on keys for even non-consolidated shards;
- uses the lower-bound stats to make consolidation block less: we now block on just the minimum number of parts we need to make progress.

### Motivation

Epic: #21265.

### Tips for reviewer

I've kicked off a nightly run, mostly to check for any performance regressions.

Otherwise: the consolidating iter is well-covered by existing tests and this should only affect performance, so I feel good about the overall test converage.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by bkirwi** [comment]
The nightly failures both exist on `main`, so I think this looks good to CI!

**Comment by danhhz** [comment]
I got about 75% through this today, will circle back tomorrow

**Review by danhhz — APPROVED** [review]
LGTM, just a few suggestions on things I had to think about while loading this up

now that we have a key_lower on everything, is there a world in which we could put all the runs in a heap (by the key_lower) and use that for determining which to fetch next?  now that I type that out, I think it's equivalent to what you've done here except getting the next part(s) is `O(log(n))` instead of `O(n)`, which doesn't feel worth the complexity given the expected size of `n`

**Review by bkirwi — COMMENTED** [review]
Thanks for the review! Applied all requested changes, though one question I answered inline.

> now that we have a key_lower on everything, is there a world in which we could put all the runs in a heap (by the key_lower) and use that for determining which to fetch next?

Yeah, this does seem possible. My only hesitation is that we don't guarantee the lower bounds are tight yet (partially because they default to `""` for historical data, partly because they're a bit lossy...) so it's not quite equivalent yet. But it does seem like there's probably some point where they're close enough and we can simplify...

**Pull request merged**
