### PR TITLE
Improve tracing

### PR DESCRIPTION
**Pull request by edude03**
- add a few instrument statements
- set the default service name
- set the span type to server for easy filtering

### Motivation
See https://github.com/MaterializeInc/materialize/issues/11361

### Testing

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - 

 I tested this locally using [uptrace](https://github.com/uptrace/uptrace) and I can commit the test setup if that's desirable 

Here are some screenshots to dem
Screen Shot 2022-03-24 at 11 19 31 AM
Screen Shot 2022-03-24 at 11 19 23 AM
o the functionality:

### CODE REVIEW

**Comment by benesch** [comment]
That was fast! @guswynn can you take this one?

**Comment by guswynn** [comment]
@edude03 thanks for the pr!

The tracer setup looks great!

As for the instrumentation, because they are at `debug/trace` level, its pretty harmless to just accept, but I think @mjibson should take a look, they have the most context on where in `coord.rs` we actually wait for statements to be executed

**Review by guswynn — CHANGES_REQUESTED** [review]
ok, @edude03, after talking this through, I think we should 
1. merge the change to the tracer setup (`service.name`)
2. not add the `#[instrument]` calls yet. The way that queries work in the coordinator is fairly complex; it involves an internal request-response flow that will be fairly subtle to implement. The good news is we want to do this thoroughly, soon, as part of other projects!

**Comment by edude03** [comment]
@guswynn Addressed #1 in https://github.com/sproutfi/materialize/pull/1 

for 2, I think since it add some value and is of the same quality as the existing tracing stuff, there is no harm in adding it now, and replacing it when the other projects come around. Otherwise if there is some work I could do to align this PR with the future work let me know and I'd be happy to implement it.

**Comment by benesch** [comment]
> for 2, I think since it add some value and is of the same quality as the existing tracing stuff, there is no harm in adding it now, and replacing it when the other projects come around. Otherwise if there is some work I could do to align this PR with the future work let me know and I'd be happy to implement it.

So my concern is that if we add this as-is, folks will use it as a model for adding additional trace spans, when I think the model here is a bit misaligned with the objective! I assume the goal is to be able to trace the life of a query end-to-end, yeah? From the moment the query hits the pgwire server to the moment that the response is returned? As written I think you're just going to see how long it takes to prepare the execute request, not how long it takes for the execute response to come back.

So, ISTM that we want to introduce a span in the pgwire protocol server whenever we accept a new connection that includes the connection ID and username. Then the communication between the pgwire protocol and coordinator can pass that context over the mpsc channel, so that any work the coordinator does on behalf of servicing that request gets associated with the connection's context.

I don't think this is more than an afternoon of work (for me), but I don't want to commit to any timelines! I'm not personally familiar with the distributed tracing ecosystem in Rust—my experience is in Go, and a few years out of date—so if the above description makes sense to you, and you want to take a stab at it first, that'd be hugely informative for me.

**Comment by edude03** [comment]
> So my concern is that if we add this as-is, folks will use it as a model for adding additional trace spans, when I think the model here is a bit misaligned with the objective!

Yep, makes sense

> I assume the goal is to be able to trace the life of a query end-to-end, yeah? From the moment the query hits the pgwire server to the moment that the response is returned?

Yep, that's the goal - although I'm probably misunderstanding how materialize (or even pg) works. From my understanding the connection stays open until one side closes it, then messages are passed back and forth over that connection. It looks like `message_command` in `coord.rs` is essentially the "entry point" - the point where messages are handled once they're send from the client(?). If that's correct, I think `message_command` -> `handle_execute` are the two main places that'd let us see the the entire execution of a command, but again I'm probably wrong 😆 

If my understanding is correct however, the complication is more so separating a "session" (a client holding a connection) from an "execution" (the client asking materialized to do something) because other than `tail` queries, I don't think there is a case where we want a trace that lasts the entire time of the connection - is that correct?

**Comment by benesch** [comment]
> > So my concern is that if we add this as-is, folks will use it as a model for adding additional trace spans, when I think the model here is a bit misaligned with the objective!
> 
> Yep, makes sense
> 
> > I assume the goal is to be able to trace the life of a query end-to-end, yeah? From the moment the query hits the pgwire server to the moment that the response is returned?
> 
> Yep, that's the goal - although I'm probably misunderstanding how materialize (or even pg) works. From my understanding the connection stays open until one side closes it, then messages are passed back and forth over that connection. It looks like `message_command` in `coord.rs` is essentially the "entry point" - the point where messages are handled once they're send from the client(?). If that's correct, I think `message_command` -> `handle_execute` are the two main places that'd let us see the the entire execution of a command, but again I'm probably wrong 😆

This is about right! I contend you want to start the tracing _even earlier_, in the pgwire protocol server: https://github.com/MaterializeInc/materialize/blob/02b221503346d0c182bafe9af35c44a407458368/src/pgwire/src/protocol.rs#L327-L330

That's the moment the execution request lands from the end user. (The end user is the client of the pgwire protocol server; the pgwire protocol server is the client of the coordinator; the coordinator is the client of the dataflow server.) To understand the flow of an execution end to end, you'll want to start the trace in the protocol server, somehow ship the context to the coordinator, and then somehow ship the context to the dataflow server. I think it's fine not to plumb it all the way down, but I think it'd be good to get the root of our tracing infrastructure in place from the start. Easier to add more leaves to a trace than to change the root, is my sense.

> If my understanding is correct however, the complication is more so separating a "session" (a client holding a connection) from an "execution" (the client asking materialized to do something) because other than `tail` queries, I don't think there is a case where we want a trace that lasts the entire time of the connection - is that correct?

I can believe that you won't find such a trace interesting! But I believe it is a fundamentally sane thing for Materialize to have a root span for each client connection? And then we just start a child span when the query execution begins.

**Comment by edude03** [comment]
> But I believe it is a fundamentally sane thing for Materialize to have a root span for each client connection? And then we just start a child span when the query execution begins.

So this is something in tracing in general I'm not sure what the best practices are - my experience with tracing is always request - response things like http (1) - where the root span starts when the request is made, then it ends when the response is returned. 

I do think though, at least the way most tools work (Datadog, Jaeger, Zipkin) the trace doesn't show up until it's finished, so if a client connects, and keeps the connection open for days (like our services do, because of connection pooling) then you won't see the trace until the service restarts, and by then it would contain hundreds (or thousands) of child spans. 

Thinking out loud, I wonder if there is a way to get both behaviours, root spans that start when the connection starts, and root spans that start when query begins?

**Comment by mjibson** [comment]
I'm mostly a bystander here and don't know much about tracing, but wanted to note some non-obvious parts of how the pg protocol works so we don't make some wrong assumptions. We have misnamed some of our API, specifically "execute query", which isn't "run this query until it's done". The specific things that do happen are 1) starting a sql statement on a portal and 2) retrieving result rows from a portal. There can be multiple portals open at the same time, and clients do not have to fetch all rows from a portal at once, so you can have an interleaved thing where you get some rows from one query (portal), then some from another, then more from the first, etc. So whatever we use here needs to handle this kind of overlappingness.

**Pull request closed without merging**
