### PR TITLE
storage: fix rustfmt in various mz_storage::source modules

### PR DESCRIPTION
**Pull request by guswynn**
Just formatting

had to make some strings multilined

### Motivation

  * This PR adds a known-desirable feature.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by petrosagg** [comment]
Probably worth waiting for https://github.com/MaterializeInc/materialize/pull/24565 to land since fixing the conflicts on this side is far easier

**Comment by guswynn** [comment]
@petrosagg How soon do we expect that to land? @rjobanp I would love to be able to merge this and not have to maintain a cherry-picked version in my branch im working on, do you mind working around it?

**Comment by petrosagg** [comment]
Up to Roshan. If you're working on another branch on top of this one then another option is to not touch the mysql files. We can fix rustfmt in them in Roshan's PR independently

**Comment by rjobanp** [comment]
I should hopefully be able to address all comments / merge today. But I'm curious how you got rustfmt to work on it -- when I run `bin/fmt` it seems like it's still silently failing

**Review by rjobanp — APPROVED** [review]

**Pull request merged**
