### PR TITLE
compute,storage: abort communication tasks on drop

### LINKED ISSUE #13668: compute: tasks for failed replicas are not dropped
@antiguru observes that since #13525, the `ReplicaTask` associated with a compute replica is not shut down if the replica never manages a successful connection: https://github.com/MaterializeInc/materialize/pull/13525#discussion_r921246983.

### PR DESCRIPTION
**Pull request by benesch**
While a storage host or compute replica is connecting, it cannot listen
for channel close events that indicate that the storage host or compute
replica has been dropped.

This commit fixes that by holding onto a reference to the communication
task that is aborted when the storage host or compute replica is
dropped.

Fixes #13668.
Alternative to and therefore would close #13846.

### Motivation

  * This PR fixes a recognized bug.

### Tips for reviewer

@antiguru I have not actually tested this.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-protobuf` label.
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - n/a

### CODE REVIEW

**Review by antiguru — APPROVED** [review]
Thanks, this looks simpler than my PR!

**Comment by benesch** [comment]
I haven't actually tested it! Not going to have time to do that testing for a minute.

**Comment by benesch** [comment]
Which is to say, if you have the time, @antiguru, please go for it!

**Comment by antiguru** [comment]
I tested it and can confirm that the task gets cancelled!

**Comment by benesch** [comment]
Wonderful, ty!

**Pull request merged**
