### PR TITLE
tests: mysql-cdc-resumption with replicas

### PR DESCRIPTION
**Pull request by nrainer-materialize**
### Commits
4ced7f0877 tests: mysql-cdc-resumption: refactor initialization
7c159aa9d6 tests: mysql-cdc-resumption: make host configurable
18a3ea95cf tests: mysql-cdc-resumption: add workflow "master-changes"
c3f6368d6b tests: mysql-cdc-resumption: add workflow "switch-to-replica-and-kill-master"
60d3509590 tests: mysql-cdc-resumption: add workflow "switch-to-lagging-replica"
ff00446c2b tests: mysql-cdc-resumption: give replica some time

### CODE REVIEW

**Review by def- — COMMENTED** [review]
Everything worked in the end? Test failed though: https://buildkite.com/materialize/tests/builds/77837#018e18a6-d9d4-4e4d-857e-368a01a4fc4c

**Comment by nrainer-materialize** [comment]
I had it working locally. Let me check

**Comment by nrainer-materialize** [comment]
> I had it working locally. Let me check

The individual checks work (locally). I added logic to reset the replicas before each workflow. Let's see if this fixes the problem.

**Review by def- — APPROVED** [review]

**Comment by nrainer-materialize** [comment]
Should be working now in CI as well...

**Pull request merged**
