### PR TITLE
persist: replace Abomonation with serde+bincode

### PR DESCRIPTION
**Pull request by danhhz**
bincode isn't really a long term answer to our storage formats, but this
was easy and there were some concerns internally about using
Abomonation.

The performance regression is unfortunate, but not unexpected given how
little Abomonation actually had to do in the hot paths. We'll get all of
this back and more when we switch to using a columnar encoding for trace
and unsealed batches.

Before

    end_to_end/end_to_end_4b_keys
                            time:   [441.78 ms 443.93 ms 445.50 ms]
                            thrpt:  [22.447 MiB/s 22.526 MiB/s 22.635 MiB/s]
    end_to_end/end_to_end_4kb_keys
                            time:   [244.75 ms 245.27 ms 245.87 ms]
                            thrpt:  [40.671 MiB/s 40.772 MiB/s 40.859 MiB/s]
    end_to_end/end_to_end_100b_keys
                            time:   [244.18 ms 244.63 ms 245.06 ms]
                            thrpt:  [40.806 MiB/s 40.879 MiB/s 40.953 MiB/s]
    mem_unsealed_snapshot   time:   [28.079 ms 28.310 ms 28.533 ms]
    mem_trace_snapshot      time:   [28.738 ms 28.972 ms 29.189 ms]
    file_unsealed_snapshot  time:   [46.351 ms 46.783 ms 47.181 ms]
    file_trace_snapshot     time:   [47.693 ms 48.670 ms 49.672 ms]
    mem_write_sync          time:   [30.027 ns 30.182 ns 30.339 ns]
    file_write_sync         time:   [18.032 ms 18.212 ms 18.441 ms]
    indexed_write_drain     time:   [336.08 ms 337.22 ms 338.33 ms]
    indexed_write_drain_sorted
                            time:   [193.77 ms 194.83 ms 195.90 ms]

After

    end_to_end/end_to_end_4b_keys
                            time:   [443.18 ms 444.24 ms 445.30 ms]
                            thrpt:  [22.457 MiB/s 22.511 MiB/s 22.564 MiB/s]
                     change:
                            time:   [-1.2815% -0.4797% +0.2789%] (p = 0.28 > 0.05)
                            thrpt:  [-0.2782% +0.4820% +1.2981%]
                            No change in performance detected.
    end_to_end/end_to_end_4kb_keys
                            time:   [244.45 ms 245.04 ms 245.61 ms]
                            thrpt:  [40.716 MiB/s 40.810 MiB/s 40.909 MiB/s]
                     change:
                            time:   [-0.4210% +0.1634% +1.1124%] (p = 0.77 > 0.05)
                            thrpt:  [-1.1002% -0.1632% +0.4228%]
                            No change in performance detected.
    end_to_end/end_to_end_100b_keys
                            time:   [297.84 ms 302.01 ms 306.72 ms]
                            thrpt:  [32.603 MiB/s 33.112 MiB/s 33.575 MiB/s]
                     change:
                            time:   [+21.249% +22.825% +24.359%] (p = 0.00 < 0.05)
                            thrpt:  [-19.588% -18.583% -17.525%]
                            Performance has regressed.
    mem_unsealed_snapshot   time:   [28.075 ms 28.313 ms 28.542 ms]
                            change: [-1.0683% +0.0097% +1.0881%] (p = 0.99 > 0.05)
                            No change in performance detected.
    mem_trace_snapshot      time:   [28.583 ms 28.879 ms 29.184 ms]
                            change: [-1.6319% -0.3222% +0.9535%] (p = 0.63 > 0.05)
                            No change in performance detected.
    file_unsealed_snapshot  time:   [47.343 ms 47.626 ms 47.922 ms]
                            change: [+0.7467% +1.8011% +2.9477%] (p = 0.00 < 0.05)
                            Change within noise threshold.
    file_trace_snapshot     time:   [48.374 ms 48.756 ms 49.201 ms]
                            change: [-1.9911% +0.1774% +2.3542%] (p = 0.88 > 0.05)
                            No change in performance detected.
    mem_write_sync          time:   [30.055 ns 30.373 ns 30.847 ns]
                            change: [-13.544% +1.5000% +22.014%] (p = 0.87 > 0.05)
                            No change in performance detected.
    file_write_sync         time:   [18.055 ms 18.258 ms 18.509 ms]
                            change: [-1.4850% +0.2542% +1.9496%] (p = 0.78 > 0.05)
                            No change in performance detected.
    indexed_write_drain     time:   [341.91 ms 343.32 ms 344.82 ms]
                            change: [+1.2797% +1.8099% +2.3598%] (p = 0.00 < 0.05)
                            Performance has regressed.
    indexed_write_drain_sorted
                            time:   [202.51 ms 204.83 ms 207.35 ms]
                            change: [+3.8126% +5.1292% +6.6317%] (p = 0.00 < 0.05)
                            Performance has regressed.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR adds a release note for any
  [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

**Comment by danhhz** [comment]
Note that the golden_test and the persist upgrade tests are expected to fail until we can bump the BlobMeta version.

**Comment by danhhz** [comment]
@ruchirK I went to update the benchmarks for this with your new ones but I'm getting an error that seems to reproduce at origin/main's HEAD.

```
$ git checkout 17b496784d6c9446588d56e5ea06e61122daf6b1
$ cargo bench -p persist -- blob_set/mem/7000000
...
     Running unittests (/tmp/target/release/deps/writer-9ad885949a465882)
WARNING: HTML report generation will become a non-default optional feature in Criterion.rs 0.4.0.
This feature is being moved to cargo-criterion (https://github.com/bheisler/cargo-criterion) and will be optional in a future version of Criterion.rs. To silence this warning, either switch to cargo-criterion or enable the 'html_reports' feature in your Cargo.toml.

Gnuplot not found, using plotters backend
Benchmarking blob_set/mem/7000000: Collecting 100 samples in estimated 5.3386 s (1500 iterations)error: process didn't exit successfully: `/tmp/target/release/deps/writer-9ad885949a465882 blob_set/mem/7000000 --bench` (signal: 9, SIGKILL: kill)
```

Any ideas before I dig into this? I tried a `cargo test --benches -p persist -- blob_set/mem/7000000` and it seemed to hang

**Comment by ruchirK** [comment]
No ideas offhand lemme run it on main and see. I didn't do anything besides what i thought was a simple conflict resolution to change future -> pfuture

**Comment by ruchirK** [comment]
It's moving slowly because some of the benchmarks take 30 seconds but doing

```
cargo bench --benches writer
```

from within `src/persist` seems to work for me (at least `blob_set/mem/7000000` and a lot of the benches after it seem to work). When it finishes I'll try running from the repo toplevel

**Comment by ruchirK** [comment]
It seems to work from the repo toplevel as well for me:

```
altaria-2:materialize Test$ cargo bench -p persist -- blob_set/mem/7000000
warning: unused import: `HashSet`
  --> src/persist/src/indexed/mod.rs:22:43
   |
22 | use std::collections::{BTreeMap, HashMap, HashSet};
   |                                           ^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

   Compiling persist v0.0.0 (/Users/Test/github/materialize/src/persist)
warning: `persist` (lib) generated 1 warning
    Finished bench [optimized] target(s) in 35.00s
     Running unittests (target/release/deps/persist-b44f37356fbd715e)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 70 filtered out; finished in 0.00s

     Running unittests (target/release/deps/end_to_end-92b1b2f124a5def0)
WARNING: HTML report generation will become a non-default optional feature in Criterion.rs 0.4.0.
This feature is being moved to cargo-criterion (https://github.com/bheisler/cargo-criterion) and will be optional in a future version of Criterion.rs. To silence this warning, either switch to cargo-criterion or enable the 'html_reports' feature in your Cargo.toml.

Gnuplot not found, using plotters backend

     Running unittests (target/release/deps/snapshot-29a04297a206741b)
WARNING: HTML report generation will become a non-default optional feature in Criterion.rs 0.4.0.
This feature is being moved to cargo-criterion (https://github.com/bheisler/cargo-criterion) and will be optional in a future version of Criterion.rs. To silence this warning, either switch to cargo-criterion or enable the 'html_reports' feature in your Cargo.toml.

Gnuplot not found, using plotters backend
     Running unittests (target/release/deps/writer-a6d4db66eafc8ffd)
WARNING: HTML report generation will become a non-default optional feature in Criterion.rs 0.4.0.
This feature is being moved to cargo-criterion (https://github.com/bheisler/cargo-criterion) and will be optional in a future version of Criterion.rs. To silence this warning, either switch to cargo-criterion or enable the 'html_reports' feature in your Cargo.toml.

Gnuplot not found, using plotters backend
blob_set/mem/7000000    time:   [2.9954 ms 3.0282 ms 3.0665 ms]
                        thrpt:  [2.1260 GiB/s 2.1529 GiB/s 2.1765 GiB/s]
                 change:
                        time:   [-65.231% -57.458% -46.647%] (p = 0.00 < 0.05)
                        thrpt:  [+87.430% +135.06% +187.61%]
                        Performance has improved.
Found 5 outliers among 100 measurements (5.00%)
  2 (2.00%) high mild
  3 (3.00%) high severe

```

**Comment by ruchirK** [comment]
I have one observation and maybe one theory for why it crashed for you?

Observation: the tests seem kind of slow between benchmark groups - I _think_ that's because its spending time freeing memory and deleting the tempdir.

Theory: the in-memory blob / indexed tests are pretty ram hungry - it looked like the in-memory `set_unsealed_batch` benchmarks were using upwards for 15 gb for a bit --- maybe something is got oom killed? It's strange because the `blob_set` tests actually use a lot less ram than the others so it shouldn't happen when you only run that. Let me retry a few times to see if I can repro what you're getting.

**Comment by ruchirK** [comment]
@danhhz I reran `cargo bench -p persist -- blob_set/mem/7000000` several times -- it seems like its spiking up to 15 or gb of ram usage _after_ the text summary is printed to screen. I have no earthly idea what its spending that much ram on (this test only writes 7mb blobs), but after running it about 6 or 7 times I was unable to reproduce the crash you saw. Is it happening fairly regularly for you?

**Comment by danhhz** [comment]
How odd. It's extremely regular for me, I've never seen it succeed :)

**Comment by danhhz** [comment]
Wow mine spiked up to 33GB of ram

**Comment by danhhz** [comment]
Okay well we definitely need to sort this benchmark thing out, but the other ones that do run have similar diffs to what was already in the commit/PR message, so it doesn't need to block merging this. TFTR!

**Comment by ruchirK** [comment]
I think I figured it out. Criterion is somehow doing way more inserts than I expect, even based on what they're reporting. Criterion says they're taking 100 samples (1800 iterations) -- the only way I know how to interpret that is -- "we're benchmarking your function by running it a varying number of iterations. We'll do this 100 times, and run 1800 iterations total". But 1800 iterations x 7 mb is ~11 GB, and not 20ish which is what it seems to spike up to on my laptop. High level picture - criterion gets 5 seconds to do what it wants by default and it tries to fill that time with benchmarking, and maybe Dan your laptop is more powerful than mine such that criterion can literally do 2x the inserts, and oom itself.

But something like this diff seems to cut short the amount of time criterion gets to benchmark, which then reduces the peak mem usage

```
diff --git a/src/persist/benches/writer.rs b/src/persist/benches/writer.rs
index 18623391a..31034c8e6 100644
--- a/src/persist/benches/writer.rs
+++ b/src/persist/benches/writer.rs
@@ -11,7 +11,7 @@

 use std::path::Path;
 use std::sync::Arc;
-use std::time::Instant;
+use std::time::{Duration, Instant};

 use criterion::measurement::WallTime;
 use criterion::{
@@ -88,14 +88,14 @@ fn bench_set<B: Blob>(writer: &mut B, data: Vec<u8>, b: &mut Bencher) {
     // many times as part of a warmup, and if we deterministically use the same
     // keys we will overwrite.
     let mut rng = rand::thread_rng();
-    b.iter(|| {
-        futures_executor::block_on(writer.set(
-            &format!("{}", rng.gen::<usize>()),
-            data.clone(),
-            false,
-        ))
-        .expect("failed to write data");
-    })
+    b.iter_batched(
+        || data.clone(),
+        |data| {
+            futures_executor::block_on(writer.set(&format!("{}", rng.gen::<usize>()), data, false))
+                .expect("failed to write data");
+        },
+        criterion::BatchSize::LargeInput,
+    )
 }

 pub fn bench_writes_log(c: &mut Criterion) {
@@ -118,6 +118,9 @@ pub fn bench_writes_log(c: &mut Criterion) {

 pub fn bench_writes_blob(c: &mut Criterion) {
     let mut group = c.benchmark_group("blob_set");
+    group.warm_up_time(Duration::from_secs(1));
+    group.measurement_time(Duration::from_secs(1));
+
     let mut data = vec![];
```

The criterion docs are confusing and the relationship between samples, batches and iterations is not clear to me yet, but this seems like the path to fixing.

**Comment by danhhz** [comment]
The above seems fine to me. I'm also happy just deleting the mem version of this benchmark, given that it's basically just measuring a mutex lock + hashmap insert. the symmetry of having mem equivalents of all of them is nice, but also we've got a _lot_ of benchmarks now

**Pull request merged**
