### PR TITLE
feature-benchmark: Reduce scale for ManySmallUpdates

### PR DESCRIPTION
**Pull request by def-**
Thanks to @bkirwi for noticing

Verification in https://buildkite.com/materialize/nightly/builds/8061

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by nrainer-materialize — CHANGES_REQUESTED** [review]
I believe this is exactly a case where this scenario will produce a different result after the change. Therefore, its version should be increased. This is done by overriding
```
    def version(self) -> ScenarioVersion:
```

**Review by nrainer-materialize — APPROVED** [review]
Thank you

**Comment by nrainer-materialize** [comment]
(I think the rebase went wrong so that the commit message does not fit)

**Comment by def-** [comment]
Oops, didn't notice that locally.

**Pull request merged**
