### PR TITLE
doc: tail warnings

### PR DESCRIPTION
**Pull request by mjibson**
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/6005)

### CODE REVIEW

**Review by benesch — COMMENTED** [review]
Thanks very much for getting this done! I feel like the warning is a bit obtuse though. What do you think about something like this?

```
diff --git a/src/pgwire/src/protocol.rs b/src/pgwire/src/protocol.rs
index 645c5c5a7..5b590a50d 100644
--- a/src/pgwire/src/protocol.rs
+++ b/src/pgwire/src/protocol.rs
@@ -1040,10 +1040,13 @@ where
             }
             ExecuteResponse::Tailing { rx } => {
                 if fetch_portal_name.is_none() {
-                    let msg = ErrorResponse::notice(
+                    let mut msg = ErrorResponse::notice(
                         SqlState::WARNING,
-                        "streaming TAIL rows: ensure your client is unbuffered, use COPY, or use FETCH",
+                        "streaming TAIL rows directly requires a client that does not buffer output",
                     );
+                    if self.coord_client.session().vars().application_name() == "psql" {
+                        msg.hint = Some("Wrap your TAIL statement in `COPY (TAIL ...) TO STDOUT`.".into())
+                    }
                     self.conn.send(msg).await?;
                     self.conn.flush().await?;
                 }

```

Basically, I like the idea of giving very explicit instructions if we can detect that the user is using psql. And since we're in the pgwire protocol we can leverage the additional hint/detail fields.

**Comment by mjibson** [comment]
Done.

**Comment by mjibson** [comment]
(I made the assumption that your intention was to Approve with a comment. Please correct me if wrong.)

**Comment by benesch** [comment]
It was! Sorry for being unclear. Vacation struggles.

**Pull request merged**
