### PR TITLE
wip: add memory visualization framework

### PR DESCRIPTION
**Pull request by mjibson**
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4408)

### CODE REVIEW

**Comment by mjibson** [comment]
PR here so people can start to look at general ideas.

This includes the ability to execute arbitrary SELECT statements over SQL, which I'm fairly dubious of. Do we think that's ok, or should these queries be hardcoded in the http server and results given directly to the JS?

**Comment by mjibson** [comment]
[link to example graph](https://mz-graphviz.netlify.app/?graph=digraph+%7B%0A%09%09%09%0Asubgraph+%22cluster_16%2C+1%22+%7B%0A_443%3B%0A_409%3B%0A_410%3B%0A_411%3B%0A_413%3B%0A_415%3B%0A_417%3B%0A_420%3B%0A_422%3B%0A_424%3B%0A_426%3B%0A_428%3B%0A_431%3B%0A_433%3B%0A_436%3B%0A_438%3B%0A_440%3B%0A%7D%0A%09%09%09%0A_410+-%3E+_411%3B%0A_411+-%3E+_413%3B%0A_413+-%3E+_415%3B%0A_409+-%3E+_417%3B%0A_415+-%3E+_417%3B%0A_411+-%3E+_420%3B%0A_420+-%3E+_422%3B%0A_417+-%3E+_424%3B%0A_422+-%3E+_426%3B%0A_424+-%3E+_428%3B%0A_426+-%3E+_428%3B%0A_426+-%3E+_431%3B%0A_428+-%3E+_433%3B%0A_431+-%3E+_433%3B%0A_431+-%3E+_436%3B%0A_433+-%3E+_438%3B%0A_438+-%3E+_440%3B%0A%09%09%09%0A%0A_409+%5Blabel%3D%22Empty+%28id%3A+409%29%22%5D%0A_410+%5Blabel%3D%22kafka-u2%2F16+%28id%3A+410%29%22%5D%0A_411+%5Blabel%3D%22MapFallible+%28id%3A+411%29%22%5D%0A_413+%5Blabel%3D%22Map+%28id%3A+413%29%22%5D%0A_415+%5Blabel%3D%22source-errors+%28id%3A+415%29%22%5D%0A_417+%5Blabel%3D%22Concatenate+%28id%3A+417%29%22%5D%0A_420+%5Blabel%3D%22ProtobufDecode+%28id%3A+420%29%22%5D%0A_422+%5Blabel%3D%22MapInPlace+%28id%3A+422%29%22%5D%0A_424+%5Blabel%3D%22MapInPlace+%28id%3A+424%29%22%5D%0A_426+%5Blabel%3D%22FilterFallible+%28id%3A+426%29%22%5D%0A_428+%5Blabel%3D%22Concatenate+%28id%3A+428%29%22%5D%0A_431+%5Blabel%3D%22MapFallible+%28id%3A+431%29%22%5D%0A_433+%5Blabel%3D%22Concatenate+%28id%3A+433%29%22%5D%0A_436+%5Blabel%3D%22Arrange+%281000+records%29+%28id%3A+436%29%22%2Cstyle%3Dfilled%2Ccolor%3Dred%2Cfillcolor%3D%22%23ff0000ff%22%5D%0A_438+%5Blabel%3D%22Map+%28id%3A+438%29%22%5D%0A_440+%5Blabel%3D%22Arrange-errors+%280+records%29+%28id%3A+440%29%22%2Cstyle%3Dfilled%2Ccolor%3Dred%2Cfillcolor%3D%22%23ff00000%22%5D%0A_443+%5Blabel%3D%22Region+%28id%3A+443%29%22%5D%0A%09%09%7D)

**Comment by benesch** [comment]
This is absolutely fantastic! If you want to split the coordinator/HTTP API changes out into another PR I think those could land ASAP.  

> This includes the ability to execute arbitrary SELECT statements over SQL, which I'm fairly dubious of. Do we think that's ok, or should these queries be hardcoded in the http server and results given directly to the JS?

I'm 💯 ok with this. Materialize today doesn't have any sort of access control, so no reason that HTTP over 6875 needs to prevent arbitrary SQL when pgwire over 6875 lets you run whatever query you want.

**Review by ruchirK — APPROVED** [review]
LGTM! I only reviewed the Rust changes (I haven't written a lot of JS so I don't think I'm the best person to leave suggestions there :D )

**Review by benesch — CHANGES_REQUESTED** [review]
Just to be clear I’d like to give the Rust code a closer look in its own PR.

**Pull request closed without merging**
