### PR TITLE
sql: polymorphic types

### PR DESCRIPTION
**Pull request by sploiselle**
This PR lays the groundwork for supporting list concatenation by introducing polymorphic types. I wanted to see if I could slightly reduce the size of this diff by not including the actual list concat work, so will add that as a fast-follow once this gets merged.

Note that the first commit is just noisy code movement, but I tried to split everything else up into reasonable commits.

Glad to walk through this in more detail; know that there's a lot going on here.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4582)

### CODE REVIEW

**Review by benesch — COMMENTED** [review]
I haven't fully grokked the meat of the changes (the stuff in r5), but the stuff up to there looks great and the stuff in r5 looked good on a quick skim.

I left you some comments on the stuff I've reviewed so far. The most substantial issue is the change to CoercibleScalarExpr::typ, which seem to be working around an error in how we type lists/arrays. 

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4582#-:-MKI_6IM0Gcnats2P241:b-dhgb1e)* status: all files reviewed, 7 unresolved discussions (waiting on @JLDLaughlin and @sploiselle)

___
*[src/repr/src/scalar.rs, line 773 at r5](https://reviewable.io/reviews/materializeinc/materialize/4582#-MKIU_Cx9xUGdedGmVHX:-MKIU_Cx9xUGdedGmVHY:b-90c2) ([raw file](https://github.com/materializeinc/materialize/blob/764b5411858f53bd067a35f8022d1ff9ce2da4b0/src/repr/src/scalar.rs#L773)):*
> ```Rust
> 
>         pg_array_type
>     }
> ```

Hmm, this function shouldn't need to exist. It is an error to construct a `ScalarType::Array` whose inner type is itself an array type. (This is documented on the definition of the variant, but since enum variant fields are always public, there is no way to enforce this unfortunately.) So anywhere you _would_ use this function, it should be correct to just elide it.
___
*[src/sql/src/plan/expr.rs, line 268 at r4](https://reviewable.io/reviews/materializeinc/materialize/4582#-MKIYH7E1ayDR-eBx4jt:-MKIYH7E1ayDR-eBx4ju:b-fpx1h) ([raw file](https://github.com/materializeinc/materialize/blob/f8d256a03c812689741cd834cfac763a2b343102/src/sql/src/plan/expr.rs#L268)):*
> ```Rust
>                 Some(e) => Some(ScalarType::List(Box::new(e.scalar_type)).nullable(e.nullable)),
>                 None => Some(ScalarType::List(Box::new(ScalarType::String)).nullable(true)),
>             },
> ```

This indicates that something is wrong with our coercion strategy for lists/arrays. I don't like the idea of this function returning `Some` for anything besides `Coerced`. Either a type is coerced or it's not; if this function returns `Some` for a non-coerced type that's just a very hard concept to explain. It's, like, a semi-coerced type? 

I think the fundamental problem here is that we shouldn't be considering lists/arrays to be coercible at all. My fault. Let me gnaw on this for a bit.
___
*[src/sql/src/plan/func.rs, line 439 at r1](https://reviewable.io/reviews/materializeinc/materialize/4582#-MKIVwww5WyMT5NNRE5w:-MKIVwww5WyMT5NNRE5x:b4hhedc) ([raw file](https://github.com/materializeinc/materialize/blob/8b9d42565fa9000c91d9172df29d4f7317e4e684/src/sql/src/plan/func.rs#L439)):*
> ```Rust
>             .finish()
>     }
> }
> ```

This change seems strange to me. Deriving `Debug` on this struct seems to still work fine?
___
*[src/sql/src/plan/func.rs, line 322 at r3](https://reviewable.io/reviews/materializeinc/materialize/4582#-MKIWMYI3Jx0eDSfM80_:-MKIWMYJEQK5ps51egwA:bx3jr5x) ([raw file](https://github.com/materializeinc/materialize/blob/5ac8c55bc35f302de741568df70425eebf7953a3/src/sql/src/plan/func.rs#L322)):*
> ```Rust
>     /// A pseudotype permitting a `ScalarType::List` of any element type.
>     ListAny,
>     /// A pseudotype permitting all types, with more limitations than `Any`.
> ```

minor nit: can we call these "constraints" instead? Limitations sound like problems, when in fact these "constraints" are actually often useful to solve problems.
___
*[src/sql/src/plan/func.rs, line 422 at r3](https://reviewable.io/reviews/materializeinc/materialize/4582#-MKIWhKj6GIaERj5et8P:-MKIWhKj6GIaERj5et8Q:b7c2mjb) ([raw file](https://github.com/materializeinc/materialize/blob/5ac8c55bc35f302de741568df70425eebf7953a3/src/sql/src/plan/func.rs#L422)):*
> ```Rust
>             ListAny if matches!(arg_type, List(..)) => CastTo::Implicit(arg_type.clone()),
>             // `NonVecAny` is only used to convert non-list elements to text
>             // for concatenation.
> ```

This seems like a muddling of concerns. One can certainly imagine more functions in the future that will do something else with a `NonVecAny` argument, e.g. user-defined functions. Can this not be `CastTo::Implicit(arg_type.clone())` like its friends `Any` and `ListElementAny`?
___
*[test/sqllogictest/arrays.slt, line 23 at r5](https://reviewable.io/reviews/materializeinc/materialize/4582#-MKIU7buDnIxcuWoZnTJ:-MKIU7buDnIxcuWoZnTK:bzbuvhj) ([raw file](https://github.com/materializeinc/materialize/blob/764b5411858f53bd067a35f8022d1ff9ce2da4b0/test/sqllogictest/arrays.slt#L23)):*
> ```
> 
> query error Cannot call function array_to_string\(unknown, unknown\): arguments cannot be implicitly cast to any implementation's parameters; try providing explicit casts
> SELECT array_to_string(NULL, ','), array_to_string(NULL, 'foo', 'zerp')
> ```

Huh! This is what PostgreSQL does, so definitely right, but can you add back the test case as 

```sql
SELECT array_to_string(NULL::text[], ','), array_to_string(NULL::text[], 'foo', 'zerp')
```

so we don't lose the test of the input array being null?
___
*[test/sqllogictest/funcs.slt, line 583 at r5](https://reviewable.io/reviews/materializeinc/materialize/4582#-MKIUMHl4ncg59N2XLN5:-MKIUMHm4wv9lkWKE8hJ:br8q850) ([raw file](https://github.com/materializeinc/materialize/blob/764b5411858f53bd067a35f8022d1ff9ce2da4b0/test/sqllogictest/funcs.slt#L583)):*
> ```
> 
> query error Cannot call function array_upper\(unknown, i32\): arguments cannot be implicitly cast to any implementation's parameters; try providing explicit casts
> SELECT array_upper(NULL, 1)
> ```

Ditto here. Can you add this back with an explicit cast on the first argument?

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4582)* status: all files reviewed, 7 unresolved discussions (waiting on @JLDLaughlin and @sploiselle)

___
*[src/sql/src/plan/expr.rs, line 268 at r4](https://reviewable.io/reviews/materializeinc/materialize/4582#-MKIYH7E1ayDR-eBx4jt:-MKIr1753sUTpLg0uKzK:b-viugwx) ([raw file](https://github.com/materializeinc/materialize/blob/f8d256a03c812689741cd834cfac763a2b343102/src/sql/src/plan/expr.rs#L268)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This indicates that something is wrong with our coercion strategy for lists/arrays. I don't like the idea of this function returning `Some` for anything besides `Coerced`. Either a type is coerced or it's not; if this function returns `Some` for a non-coerced type that's just a very hard concept to explain. It's, like, a semi-coerced type? 

I think the fundamental problem here is that we shouldn't be considering lists/arrays to be coercible at all. My fault. Let me gnaw on this for a bit.
</blockquote></details>

Here's my proposal! https://github.com/MaterializeInc/materialize/pull/4589

If I understood the issue correctly, if we land that PR, then you won't need to change this function at all here.

**Review by JLDLaughlin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4582)* status: all files reviewed, 8 unresolved discussions (waiting on @benesch and @sploiselle)

___
*[src/repr/src/scalar.rs, line 773 at r5](https://reviewable.io/reviews/materializeinc/materialize/4582#-MKIU_Cx9xUGdedGmVHX:-MKLuPrr2kpmyhhLJAF1:b-9dc61e) ([raw file](https://github.com/materializeinc/materialize/blob/764b5411858f53bd067a35f8022d1ff9ce2da4b0/src/repr/src/scalar.rs#L773)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Hmm, this function shouldn't need to exist. It is an error to construct a `ScalarType::Array` whose inner type is itself an array type. (This is documented on the definition of the variant, but since enum variant fields are always public, there is no way to enforce this unfortunately.) So anywhere you _would_ use this function, it should be correct to just elide it.
</blockquote></details>

To clarify, isn't this an example of a `ScalarType::Array` whose inner type is itself an array type?
```
materialize=> select array[array[1]];
 array
-------
 {{1}}
(1 row)
```
___
*[src/sql/src/plan/func.rs, line 71 at r1](https://reviewable.io/reviews/materializeinc/materialize/4582#-MKLupIb2fzFisTORYJ1:-MKLupIb2fzFisTORYJ2:b-4e08og) ([raw file](https://github.com/materializeinc/materialize/blob/8b9d42565fa9000c91d9172df29d4f7317e4e684/src/sql/src/plan/func.rs#L71)):*
> ```Rust
>     fn from_type(typ: &ScalarType) -> Self {
>         match typ {
>             ScalarType::Array(..) => Self::Array,
> ```

Super basic question that I've failed to Google: what's the difference between `(_)` and `(..)`?

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4582)* status: all files reviewed, 8 unresolved discussions (waiting on @JLDLaughlin and @sploiselle)

___
*[src/repr/src/scalar.rs, line 773 at r5](https://reviewable.io/reviews/materializeinc/materialize/4582#-MKIU_Cx9xUGdedGmVHX:-MKM-Hly8PjLrYa96ttK:b-2dtait) ([raw file](https://github.com/materializeinc/materialize/blob/764b5411858f53bd067a35f8022d1ff9ce2da4b0/src/repr/src/scalar.rs#L773)):*
<details><summary><i>Previously, JLDLaughlin (Jessica Laughlin) wrote…</i></summary><blockquote>

To clarify, isn't this an example of a `ScalarType::Array` whose inner type is itself an array type?
```
materialize=> select array[array[1]];
 array
-------
 {{1}}
(1 row)
```
</blockquote></details>

Nope, that's exactly the weird thing about arrays. `ARRAY[1]` has type `int[]`, and `ARRAY[ARRAY[1]]` has type `int[]`, and `ARRAY[ARRAY[ARRAY[1]]]` has type `int[]`...
___
*[src/sql/src/plan/func.rs, line 71 at r1](https://reviewable.io/reviews/materializeinc/materialize/4582#-MKLupIb2fzFisTORYJ1:-MKLx5hk5Tz_LMnO3zE9:b9ylstj) ([raw file](https://github.com/materializeinc/materialize/blob/8b9d42565fa9000c91d9172df29d4f7317e4e684/src/sql/src/plan/func.rs#L71)):*
<details><summary><i>Previously, JLDLaughlin (Jessica Laughlin) wrote…</i></summary><blockquote>

Super basic question that I've failed to Google: what's the difference between `(_)` and `(..)`?
</blockquote></details>

`..` is a more general form of `_`. The former can match any number of missing elements in a tuple struct, while the latter can only match one.

**Review by sploiselle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4582)* status: all files reviewed, 7 unresolved discussions (waiting on @benesch and @JLDLaughlin)

___
*[src/repr/src/scalar.rs, line 773 at r5](https://reviewable.io/reviews/materializeinc/materialize/4582#-MKIU_Cx9xUGdedGmVHX:-MKNkqa77slQJTyYxPVv:bdewngj) ([raw file](https://github.com/materializeinc/materialize/blob/764b5411858f53bd067a35f8022d1ff9ce2da4b0/src/repr/src/scalar.rs#L773)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Nope, that's exactly the weird thing about arrays. `ARRAY[1]` has type `int[]`, and `ARRAY[ARRAY[1]]` has type `int[]`, and `ARRAY[ARRAY[ARRAY[1]]]` has type `int[]`...
</blockquote></details>

Ah, this was an inadvertent leftover from a brief moment in time when I had mangled this "feature" of array types! Thanks for catching this.
___
*[src/sql/src/plan/expr.rs, line 268 at r4](https://reviewable.io/reviews/materializeinc/materialize/4582#-MKIYH7E1ayDR-eBx4jt:-MKIyPaK1x_aFdkQz8c9:b-soq1yr) ([raw file](https://github.com/materializeinc/materialize/blob/f8d256a03c812689741cd834cfac763a2b343102/src/sql/src/plan/expr.rs#L268)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Here's my proposal! https://github.com/MaterializeInc/materialize/pull/4589

If I understood the issue correctly, if we land that PR, then you won't need to change this function at all here.
</blockquote></details>

Incredible. This wholly solved my issue.
___
*[src/sql/src/plan/func.rs, line 439 at r1](https://reviewable.io/reviews/materializeinc/materialize/4582#-MKIVwww5WyMT5NNRE5w:-MKImpEw-0oqFEOZEBg0:b-eldf5t) ([raw file](https://github.com/materializeinc/materialize/blob/8b9d42565fa9000c91d9172df29d4f7317e4e684/src/sql/src/plan/func.rs#L439)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This change seems strange to me. Deriving `Debug` on this struct seems to still work fine?
</blockquote></details>

Weird. Deriving debug does not work on my system because of the generic parameter.

```
#[derive(Clone, Debug)]
/// Tracks candidate implementations.
pub struct Candidate<'a, R> {
    /// The implementation under consideration.
    fimpl: &'a FuncImpl<R>,
    exact_matches: usize,
    preferred_types: usize,
}
....
        for c in candidates {
            println!("candidate {:?}", c);
        }
```

Gives me:

```
$ cargo check
    Checking sql v0.1.0 (/home/sean/github/sploiselle/materialize-pull/materialize/src/sql)
error[E0277]: `R` doesn't implement `std::fmt::Debug`
   --> src/sql/src/plan/func.rs:747:40
    |
747 |             println!("candidate {:?}", c);
    |                                        ^ `R` cannot be formatted using `{:?}` because it doesn't implement `std::fmt::Debug`
    |
    = note: required because of the requirements on the impl of `std::fmt::Debug` for `plan::func::Candidate<'_, R>`
    = note: required by `std::fmt::Debug::fmt`
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider restricting type parameter `R`
    |
677 |     fn find_match<'b, R: std::fmt::Debug>(
    |                        ^^^^^^^^^^^^^^^^^
```

Sounds like this is not the case for you?
___
*[src/sql/src/plan/func.rs, line 422 at r3](https://reviewable.io/reviews/materializeinc/materialize/4582#-MKIWhKj6GIaERj5et8P:-MKIihPG5VUM0UBntPn-:b-tpnee0) ([raw file](https://github.com/materializeinc/materialize/blob/5ac8c55bc35f302de741568df70425eebf7953a3/src/sql/src/plan/func.rs#L422)):*
Great catch on this. I re-read the polymorphic type docs and had originally missed this line:

> Note that `anynonarray` and `anyenum` do not represent separate type variables; they are the same type as `anyelement`, just with an additional constraint. 

This means that they must perform the cast inside the function, rather than while typing. And that `NonVecAny` actually needs to be treated polymorphically, obviating the need to express its `CastTo` at all.
___
*[test/sqllogictest/arrays.slt, line 23 at r5](https://reviewable.io/reviews/materializeinc/materialize/4582#-MKIU7buDnIxcuWoZnTJ:-MKNn8pw2THwG2_PQnzC:b-896fix) ([raw file](https://github.com/materializeinc/materialize/blob/764b5411858f53bd067a35f8022d1ff9ce2da4b0/test/sqllogictest/arrays.slt#L23)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Huh! This is what PostgreSQL does, so definitely right, but can you add back the test case as 

```sql
SELECT array_to_string(NULL::text[], ','), array_to_string(NULL::text[], 'foo', 'zerp')
```

so we don't lose the test of the input array being null?
</blockquote></details>

Done.
___
*[test/sqllogictest/funcs.slt, line 583 at r5](https://reviewable.io/reviews/materializeinc/materialize/4582#-MKIUMHl4ncg59N2XLN5:-MKNn6RQ8JVAaqrnFSP4:b-896fix) ([raw file](https://github.com/materializeinc/materialize/blob/764b5411858f53bd067a35f8022d1ff9ce2da4b0/test/sqllogictest/funcs.slt#L583)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Ditto here. Can you add this back with an explicit cast on the first argument?
</blockquote></details>

Done.

**Review by benesch — APPROVED** [review]
:lgtm_strong: This is so awesome! Totally psyched about this.

> Reviewed 6 of 6 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, 4 of 4 files at r9, 1 of 1 files at r10.
> Dismissed @JLDLaughlin from a discussion.
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4582#-:-MKTKRIqEvTBQuyLlGQ5:bo82hwj)* status: all files reviewed, 3 unresolved discussions (waiting on @sploiselle)

___
*[misc/python/tests/test_git.py, line 39 at r10](https://reviewable.io/reviews/materializeinc/materialize/4582#-MKTJjNK7RkhivtWHcMX:-MKTJjNK7RkhivtWHcMY:b7nd3sp) ([raw file](https://github.com/materializeinc/materialize/blob/5b4d96f6663f48a71f8b0dbdcca8e30d503727b2/misc/python/tests/test_git.py#L39)):*
> ```Python
>         )
>         if prev.prerelease and tag.prerelease:
>             assert prev.patch > tag.patch or prev.prerelease >= tag.prerelease
> ```

I'm not sure this is a valid change to this test This used to test something about the contiguousness about prereleases, but it no longer does. 

Personally I think this test is more trouble than it is worth and it would be better to just delete it. I don't think it is really appropriate to be asserting things about the state of the local Git repository in a unit test. But that's a discussion for another day. Anyway, could you split this change out and assign Brandon, so he has a chance to weigh in? Alternatively, if you don't want to deal with it, I bet you could just delete the tags that cause this test to fail from your local Git repository.
___
*[src/repr/src/scalar.rs, line 773 at r9](https://reviewable.io/reviews/materializeinc/materialize/4582#-MKTG1bG6Pxq81M6Al-Q:-MKTG1bHBCo2ZgYnO3ct:b-wjs4bp) ([raw file](https://github.com/materializeinc/materialize/blob/dac4a0066661be11fdd00022c299d656fa0aa5f0/src/repr/src/scalar.rs#L773)):*
> ```Rust
> 
>         pg_array_type
>     }
> ```

I think this is dead code now that can be deleted!
___
*[src/sql/src/plan/func.rs, line 439 at r1](https://reviewable.io/reviews/materializeinc/materialize/4582#-MKIVwww5WyMT5NNRE5w:-MKTIbtEA6UVc320rUX6:bsekvmm) ([raw file](https://github.com/materializeinc/materialize/blob/8b9d42565fa9000c91d9172df29d4f7317e4e684/src/sql/src/plan/func.rs#L439)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

Weird. Deriving debug does not work on my system because of the generic parameter.

```
#[derive(Clone, Debug)]
/// Tracks candidate implementations.
pub struct Candidate<'a, R> {
    /// The implementation under consideration.
    fimpl: &'a FuncImpl<R>,
    exact_matches: usize,
    preferred_types: usize,
}
....
        for c in candidates {
            println!("candidate {:?}", c);
        }
```

Gives me:

```
$ cargo check
    Checking sql v0.1.0 (/home/sean/github/sploiselle/materialize-pull/materialize/src/sql)
error[E0277]: `R` doesn't implement `std::fmt::Debug`
   --> src/sql/src/plan/func.rs:747:40
    |
747 |             println!("candidate {:?}", c);
    |                                        ^ `R` cannot be formatted using `{:?}` because it doesn't implement `std::fmt::Debug`
    |
    = note: required because of the requirements on the impl of `std::fmt::Debug` for `plan::func::Candidate<'_, R>`
    = note: required by `std::fmt::Debug::fmt`
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider restricting type parameter `R`
    |
677 |     fn find_match<'b, R: std::fmt::Debug>(
    |                        ^^^^^^^^^^^^^^^^^
```

Sounds like this is not the case for you?
</blockquote></details>

Ah, of course, rust-lang/rust#26925 strikes again. I'd recommend just plumbing some `Debug` bounds around like so:

```diff
--- a/src/sql/src/plan/func.rs
+++ b/src/sql/src/plan/func.rs
@@ -601,7 +601,7 @@ impl From<ScalarType> for ParamType {
     }
 }
 
-#[derive(Clone)]
+#[derive(Clone, Debug)]
 /// Tracks candidate implementations.
 pub struct Candidate<'a, R> {
     /// The implementation under consideration.
@@ -610,16 +610,6 @@ pub struct Candidate<'a, R> {
     preferred_types: usize,
 }
 
-impl<'a, R> fmt::Debug for Candidate<'a, R> {
-    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
-        f.debug_struct("Candidate")
-            .field("fimpl", &self.fimpl)
-            .field("exact_matches", &self.exact_matches)
-            .field("preferred_types", &self.preferred_types)
-            .finish()
-    }
-}
-
 #[derive(Clone, Debug)]
 /// Determines best implementation to use given some user-provided arguments.
 /// For more detail, see `ArgImplementationMatcher::select_implementation`.
@@ -648,7 +638,10 @@ impl<'a> ArgImplementationMatcher<'a> {
         ecx: &'a ExprContext<'a>,
         impls: &[FuncImpl<R>],
         cexprs: Vec<CoercibleScalarExpr>,
-    ) -> Result<R, anyhow::Error> {
+    ) -> Result<R, anyhow::Error>
+    where
+        R: fmt::Debug,
+    {
         let m = Self { ident, ecx };
 
         let types: Vec<_> = cexprs.iter().map(|e| ecx.scalar_type(e)).collect();
@@ -688,7 +681,10 @@ impl<'a> ArgImplementationMatcher<'a> {
         &self,
         types: &[Option<ScalarType>],
         impls: Vec<&'b FuncImpl<R>>,
-    ) -> Result<&'b FuncImpl<R>, anyhow::Error> {
+    ) -> Result<&'b FuncImpl<R>, anyhow::Error>
+    where
+        R: fmt::Debug,
+    {
         let all_types_known = types.iter().all(|t| t.is_some());
 
         // Check for exact match.
@@ -939,6 +935,7 @@ macro_rules! builtins {
     }};
 }
 
+#[derive(Debug)]
 pub struct TableFuncPlan {
     pub func: TableFunc,
     pub exprs: Vec<ScalarExpr>,
@@ -1556,7 +1553,10 @@ pub fn select_impl<R>(
     name: &PartialName,
     impls: &[FuncImpl<R>],
     args: &[Expr],
-) -> Result<R, anyhow::Error> {
+) -> Result<R, anyhow::Error>
+where
+    R: fmt::Debug,
+{
     let mut cexprs = Vec::new();
     for arg in args {
         let cexpr = query::plan_expr(ecx, arg)?;

```

It's definitely a slightly more irritating solution, but from experience manually-written debug impls get out of sync eventually with nearly 100% probability (usually when you add new fields and forget to update the debug impl), which can result in some brutal debugging sessions.
___
*[src/sql/src/plan/func.rs, line 1601 at r8](https://reviewable.io/reviews/materializeinc/materialize/4582#-MKTEhdd6afqIsdMdh3u:-MKTEhde2I9gRZZP6uwm:b-q46epw) ([raw file](https://github.com/materializeinc/materialize/blob/a4584e575cc00c7e98b7822cfd5169d38b8c822f/src/sql/src/plan/func.rs#L1601)):*
> ```Rust
>                     )?;
>                     Ok(lhs.call_binary(rhs, TextConcat))
>                 }),
> ```

:+1: this seems great!

**Review by sploiselle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4582)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @benesch)

___
*[misc/python/tests/test_git.py, line 39 at r10](https://reviewable.io/reviews/materializeinc/materialize/4582#-MKTJjNK7RkhivtWHcMX:-MKW27UqAloBb0DtkeLp:b-896fix) ([raw file](https://github.com/materializeinc/materialize/blob/5b4d96f6663f48a71f8b0dbdcca8e30d503727b2/misc/python/tests/test_git.py#L39)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I'm not sure this is a valid change to this test This used to test something about the contiguousness about prereleases, but it no longer does. 

Personally I think this test is more trouble than it is worth and it would be better to just delete it. I don't think it is really appropriate to be asserting things about the state of the local Git repository in a unit test. But that's a discussion for another day. Anyway, could you split this change out and assign Brandon, so he has a chance to weigh in? Alternatively, if you don't want to deal with it, I bet you could just delete the tags that cause this test to fail from your local Git repository.
</blockquote></details>

Done.
___
*[src/repr/src/scalar.rs, line 773 at r9](https://reviewable.io/reviews/materializeinc/materialize/4582#-MKTG1bG6Pxq81M6Al-Q:-MKW7bQ716zB7HfThl3g:b-896fix) ([raw file](https://github.com/materializeinc/materialize/blob/dac4a0066661be11fdd00022c299d656fa0aa5f0/src/repr/src/scalar.rs#L773)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I think this is dead code now that can be deleted!
</blockquote></details>

Done.
___
*[src/sql/src/plan/func.rs, line 439 at r1](https://reviewable.io/reviews/materializeinc/materialize/4582#-MKIVwww5WyMT5NNRE5w:-MKW6dHHABZ5P3cNZ0WD:b-896fix) ([raw file](https://github.com/materializeinc/materialize/blob/8b9d42565fa9000c91d9172df29d4f7317e4e684/src/sql/src/plan/func.rs#L439)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Ah, of course, rust-lang/rust#26925 strikes again. I'd recommend just plumbing some `Debug` bounds around like so:

```diff
--- a/src/sql/src/plan/func.rs
+++ b/src/sql/src/plan/func.rs
@@ -601,7 +601,7 @@ impl From<ScalarType> for ParamType {
     }
 }
 
-#[derive(Clone)]
+#[derive(Clone, Debug)]
 /// Tracks candidate implementations.
 pub struct Candidate<'a, R> {
     /// The implementation under consideration.
@@ -610,16 +610,6 @@ pub struct Candidate<'a, R> {
     preferred_types: usize,
 }
 
-impl<'a, R> fmt::Debug for Candidate<'a, R> {
-    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
-        f.debug_struct("Candidate")
-            .field("fimpl", &self.fimpl)
-            .field("exact_matches", &self.exact_matches)
-            .field("preferred_types", &self.preferred_types)
-            .finish()
-    }
-}
-
 #[derive(Clone, Debug)]
 /// Determines best implementation to use given some user-provided arguments.
 /// For more detail, see `ArgImplementationMatcher::select_implementation`.
@@ -648,7 +638,10 @@ impl<'a> ArgImplementationMatcher<'a> {
         ecx: &'a ExprContext<'a>,
         impls: &[FuncImpl<R>],
         cexprs: Vec<CoercibleScalarExpr>,
-    ) -> Result<R, anyhow::Error> {
+    ) -> Result<R, anyhow::Error>
+    where
+        R: fmt::Debug,
+    {
         let m = Self { ident, ecx };
 
         let types: Vec<_> = cexprs.iter().map(|e| ecx.scalar_type(e)).collect();
@@ -688,7 +681,10 @@ impl<'a> ArgImplementationMatcher<'a> {
         &self,
         types: &[Option<ScalarType>],
         impls: Vec<&'b FuncImpl<R>>,
-    ) -> Result<&'b FuncImpl<R>, anyhow::Error> {
+    ) -> Result<&'b FuncImpl<R>, anyhow::Error>
+    where
+        R: fmt::Debug,
+    {
         let all_types_known = types.iter().all(|t| t.is_some());
 
         // Check for exact match.
@@ -939,6 +935,7 @@ macro_rules! builtins {
     }};
 }
 
+#[derive(Debug)]
 pub struct TableFuncPlan {
     pub func: TableFunc,
     pub exprs: Vec<ScalarExpr>,
@@ -1556,7 +1553,10 @@ pub fn select_impl<R>(
     name: &PartialName,
     impls: &[FuncImpl<R>],
     args: &[Expr],
-) -> Result<R, anyhow::Error> {
+) -> Result<R, anyhow::Error>
+where
+    R: fmt::Debug,
+{
     let mut cexprs = Vec::new();
     for arg in args {
         let cexpr = query::plan_expr(ecx, arg)?;

```

It's definitely a slightly more irritating solution, but from experience manually-written debug impls get out of sync eventually with nearly 100% probability (usually when you add new fields and forget to update the debug impl), which can result in some brutal debugging sessions.
</blockquote></details>

Done.

**Pull request merged**
