### PR TITLE
storage: Support updating the `WriteHandle`/`RelationDesc` for a table owned by txn-wal

### PR DESCRIPTION
**Pull request by ParkMyCar**
This PR adds a new method, `alter_table_desc(...)` to the `StorageController` and `StorageCollections` to support updating the `RelationDesc` of a table. It also implements a `todo!(...)` in `txn-wal` to support updating the `WriteHandle` for a managed collection. 

### Motivation

Progress towards: https://github.com/MaterializeInc/materialize/issues/28082

### Tips for reviewer

Two things I'm unsure about and would love feedback on:
1. How does this fit with Pv2? I saw there is a "can_write" when creating collections that I didn't consider here.
2. How do the timestamps for forgetting and registering in txn-wal look? It's easy enough to plumb in another timestamp if necessary.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - N/a

### CODE REVIEW

**Comment by jkosh44** [comment]
> How do the timestamps for forgetting and registering in txn-wal look? It's easy enough to plumb in another timestamp if necessary.

From the txn-wal perspective, it's fine. However, the caller (probably the adapter) will have to look something like this:

```Rust
let forget_ts = oracle.write_ts();
// a
contoller.alter_table_desc(table_id, new_desc, forget_ts)?;
// b
oracle.apply_write(register_ts);
```

How the caller knows what `register_ts` is is the tricky part. Some options:

1. `alter_table_desc` returns it.
2. The caller executes `let register_ts = forget_ts.step_forward()` at (b). This IMO would be a leaky abstraction as it requires the caller to know how `alter_table_desc` is implemented.
3. As you suggested, the caller generates a second timestamp `let register_ts = oracle.write_ts();` at (a) and passes that in as an argument.

Personally I prefer approach (3).

**Comment by jkosh44** [comment]
> > How do the timestamps for forgetting and registering in txn-wal look? It's easy enough to plumb in another timestamp if necessary.
> 
> From the txn-wal perspective, it's fine. However, the caller (probably the adapter) will have to look something like this:
> 
> ```rust
> let forget_ts = oracle.write_ts();
> // a
> contoller.alter_table_desc(table_id, new_desc, forget_ts)?;
> // b
> oracle.apply_write(register_ts);
> ```
> 
> How the caller knows what `register_ts` is is the tricky part. Some options:
> 
>     1. `alter_table_desc` returns it.
> 
>     2. The caller executes `let register_ts = forget_ts.step_forward()` at (b). This IMO would be a leaky abstraction as it requires the caller to know how `alter_table_desc` is implemented.
> 
>     3. As you suggested, the caller generates a second timestamp `let register_ts = oracle.write_ts();` at (a) and passes that in as an argument.
> 
> 
> Personally I prefer approach (3).

It's theoretically possible for `txn-wal` to allow a user to atomically register and forget shards at a single timestamp which would resolve this too, but it's also probably not worth the effort.

**Comment by ParkMyCar** [comment]
This all makes sense to me! Just pushed an update that takes approach 3

**Review by jkosh44 — APPROVED** [review]
LGTM

**Pull request merged**
