### PR TITLE
[WIP]: CREATE CLUSTER

### PR DESCRIPTION
**Pull request by sploiselle**
Better details in newer comments.

### CODE REVIEW

**Comment by sploiselle** [comment]
@benesch @frankmcsherry @antiguru Nikhil mentioned y'all might have interest in tinkering on this over the weekend, so I got things to a state where you can create clusters and place indexes on them. Right now, though, the only way to change things to work with anything other than the default cluster you have to change [this line](https://github.com/MaterializeInc/materialize/pull/11029/files#diff-8d6d43630f95caa511152105e7e444bd04ef41fa01aa9365e76d179845d48a91R63) to the other cluster's name. ¯\\\_(ツ)\_/¯

Crucially, I have not yet rebuilt the `coord.indexes`, so indexes on non-default clusters have the wrong frontiers. So I don't expect this to be very fruitful, but maybe there's something y'all could move forward with?

Note that lots of things don't work and panics abound. For instance, I can create indexes on tables in non-default clusters, but my writes don't seem to make it into the index; assume that's related to the wrong frontiers.

**Comment by frankmcsherry** [comment]
Thanks @sploiselle! We'll take a peek, and appreciate the early look. In related news, I am exploding `coord.indexes` in another PR, and while we might eventually have a struggle to merge the two, I think it cleans up several of the issues you might be having (e.g. all frontiers are managed in `Controller`, who groks the instance stuff).

We'll see though; it is also on fire. :D

**Comment by benesch** [comment]
This is going to conflict badly with #11019, but I offer myself up to do that painful rebase!

**Comment by sploiselle** [comment]
@benesch I'm looking forward to the rebase as a means to understand the coordinator's new shape. I'll reach out if I reach a massive sticking point, though.

**Comment by benesch** [comment]
So sorry, but did not manage to get to the rebase this weekend. Going as fast as we can!

A bunch of stuff landed this weekend that was informed by this work!

 * #11045 tees logging sources up to have per-cluster indexes.
 * #11042 has plumbed a lot of the compute instance IDs into the right places
 * #11066 deleted a bunch of confusing code paths from the dataflow builder
 * #11069 will remove `determine_frontier`
 * 60c6834a5 refactored timedomain handling

@frankmcsherry has a PR out to get `nearest_indexes` out of the catalog (#11067), and I've got a forthcoming PR to hoist `enabled_indexes` out of the catalog too. I think it makes the most sense not to try to rebase until that work goes in. It should all wire up quite a bit more smoothly with those last few changes in place!

**Comment by benesch** [comment]
> I've got a forthcoming PR to hoist `enabled_indexes` out of the catalog too. 

Specifically, I'm hoping to address #8318!

**Comment by benesch** [comment]
#11092 is the promised PR. As soon as that goes in, I'll see about giving this a rebase!

**Comment by benesch** [comment]
Ok, rebase here! https://github.com/MaterializeInc/materialize/compare/main...benesch:create-cluster-2

Didn't want to push directly at your branch to avoid blowing away important state. The branch I linked builds, runs, and executes basic SQL, but didn't test it belong that!

**Comment by benesch** [comment]
Whew, ok, pushed up a bunch more work at my branch, which grafts on some of the changes to coord.rs I missed in the initial rebase, plus support for `DROP CLUSTER`.

It seems to me that the best plan of attack is to start shaving off bite-sized PRs that are ready for review + merge. Here's a candidate splitting. I think this is roughly topologically sorted:

  1. Adding a `compute_instance` field to `catalog::Index` and `catalog::Sink` that is always initialized to `DEFAULT_INSTANCE_INDEX_ID`. That'll allow us to put the rest of the coordinator in terms of `index.compute_instance` and `sink.compute_instance`.
  2. Adding the `compute_instances_by_id`, `compute_instances_by_name`, and `compute_instances()` methods to the catalog, but without actually adding the SQLite backing. (Instead, just initializing the structs when the catalog loads with one hardcoded compute cluster.) That'll let us shake out the complexity around the builtin logs; we'll be able to get [this loop](https://github.com/MaterializeInc/materialize/compare/MaterializeInc:d115ec9...benesch:c3eaa4d#) in a PR in relative isolation.
  3. Adding `CREATE CLUSTER` and `DROP CLUSTER` parsing and planning support, but letting them bottom out at the end of planning.
  4. Adding the `cluster` variable in readonly mode and using it to determine what cluster to use in `sequence_peek` and `sequence_tail` in the coordinator.
  5. Teaching `CREATE CLUSTER` to install a new cluster in the catalog. 
  6. Allowing `CREATE INDEX` and `CREATE SINK` to target a particular cluster. (This one's a bit complicated, because we want to refer to clusters by _id_ and not by name in the SQL we store on disk, so that we can safely rename clusters.)
  7. Teaching `DROP CLUSTER` to remove a cluster from the catalog. (This needs to be careful not to allow dropping a cluster with active indexes unless `CASCADE` is specified.)

Thoughts, @sploiselle? I'd love to divvy up this work with you! It seems like I could do 3 while you do 1 + 2, or vice-versa?

**Comment by benesch** [comment]
I'm going to very optimistically call this done! The last piece of this is in #11126, I think, and I filed #11131 to track the outstanding work.

**Pull request closed without merging**
