### PR TITLE
output consistency: add pg_size_pretty

### PR DESCRIPTION
**Pull request by nrainer-materialize**
This extends test coverage for https://github.com/MaterializeInc/materialize/pull/28205.

### Nightly
https://buildkite.com/materialize/nightly/builds/8606

### CODE REVIEW

**Comment by nrainer-materialize** [comment]
@sthm: The [comparison with Postgres](https://buildkite.com/materialize/nightly/builds/8580) showed the following classes of errors. Let me know what you think about them, and whether you want to address or ignore them:

### Different unit
Example:
```
ValidationErrorType.CONTENT_MISMATCH: Value differs at row index 0, column index 1 ('pg_size_pretty(int8_neg_max)').
  Value 1 (Materialize evaluation): '-8192 PB' (type: <class 'str'>)
  Value 2 (Postgres evaluation): '-9223372036854775808 bytes' (type: <class 'str'>)
  Query 1: SELECT bit_length(bytea_val_1), pg_size_pretty(int8_neg_max), (btrim(char_6_val_1, varchar_8_val_4) ILIKE 'a%b'), jsonb_typeof(jsonb_empty_arr), (jsonb_val_5 -> 2), (int2_one - int8_one), (jsonb_val_4 <@ jsonb_val_1c), (int4range_empty && int4range_closed), atan(int2_zero) FROM t_dfr_horiz;
  Query 2: SELECT bit_length(bytea_val_1), pg_size_pretty(int8_neg_max), (btrim(char_6_val_1, varchar_8_val_4) ILIKE 'a%b'), jsonb_typeof(jsonb_empty_arr), (jsonb_val_5 -> 2), (int2_one - int8_one), (jsonb_val_4 <@ jsonb_val_1c), (int4range_empty && int4range_closed), atan(int2_zero) FROM t_pg_horiz;
```
simplified to
```
SELECT pg_size_pretty((-9223372036854775808)::INT8);
```

### Different presentation with decimal input
Example:
```
ValidationErrorType.CONTENT_MISMATCH: Value differs at row index 0, column index 1 ('pg_size_pretty(decimal_39_8_zero)').
  Value 1 (Materialize evaluation): '0 bytes' (type: <class 'str'>)
  Value 2 (Postgres evaluation): '0.00000000 bytes' (type: <class 'str'>)
  Query 1: SELECT (char_length(text_val_w_spaces) - decimal_39_0_null), pg_size_pretty(decimal_39_8_zero), (varchar_8_empty ILIKE ''), convert_from(bytea_null, 'utf8'), sha256(bytea_null), (timestamp_min_val > timestamptz_null), array_upper(timestamptz_array_null, 0), asin(atan(int4_one)), (int8_neg_max & int8_one) FROM t_dfr_horiz;
  Query 2: SELECT (char_length(text_val_w_spaces) - decimal_39_0_null), pg_size_pretty(decimal_39_8_zero), (varchar_8_empty ILIKE ''), convert_from(bytea_null, 'utf8'), sha256(bytea_null), (timestamp_min_val > timestamptz_null), array_upper(timestamptz_array_null, 0), asin(atan(int4_one)), (int8_neg_max & int8_one) FROM t_pg_horiz;
```
simplified to
```
SELECT pg_size_pretty(0::DECIMAL(39, 8));

###   Postgres fails with: 'function pg_size_pretty(integer) is not unique` but mz succeeds
Example:
```
ValidationErrorType.SUCCESS_MISMATCH: Outcome differs.
  Value 1 (Materialize evaluation): 'QueryResult' (type: <class 'str'>)
  Value 2 (Postgres evaluation): 'QueryFailure' (type: <class 'str'>)
  Error 2: 'function pg_size_pretty(integer) is not unique (Could not choose a best candidate function. You might need to add explicit type casts.)'
  Query 1: SELECT char_length(pg_size_pretty(char_length(bpchar_8_val_1))) FROM t_dfr_horiz;
  Query 2: SELECT char_length(pg_size_pretty(char_length(bpchar_8_val_1))) FROM t_pg_horiz;
```
simplified to
```
SELECT pg_size_pretty(0::INT4);
```

Are you aware of a reason why Postgres behaves like this? Do we want to ignore this?

**Comment by nrainer-materialize** [comment]
As discussed with @sthm:

> ### 1) Different unit

This happens only for the maximum negative value and might be an issue in Postgres. We ignore it.


> ### 2) Different presentation with decimal input

This is unrelated to this functionality and a consequence of https://github.com/MaterializeInc/materialize/issues/25723.

> ### 3) Postgres fails with: 'function pg_size_pretty(integer) is not unique` but mz succeeds

This is because we do not implement all overloadings of this function as of now. It's okay.

**Comment by jkosh44** [comment]
> As discussed with @sthm:
> 
> > ### 1) Different unit
> 
> This happens only for the maximum negative value and might be an issue in Postgres. We ignore it.

FWIW, this is now fixed in PG versions 15 and above.

https://github.com/postgres/postgres/commit/b181062aa5727a013c96b64476f884c992b5068d

**Comment by nrainer-materialize** [comment]
> FWIW, this is now fixed in PG versions 15 and above.

Thanks Joe for fixing it! 🎉

**Comment by jkosh44** [comment]
> Do you have any idea when this fix will be shipped?

Unfortunately I do not. It should be included in the next 15 and 16 minor versions as well as 17.

**Pull request merged**
