### PR TITLE
Prevent user from calling `current` functions with parentheses

### PR DESCRIPTION
**Pull request by OscarTHZhang**
Prevent user from calling `current_role()`, `current_user()`, `current_schema`, and `session_user()` with trailing parentheses to align with PostgreSQL. 

### Motivation
This PR fixes a recognized bug: https://github.com/MaterializeInc/materialize/issues/18824

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - `current_user`, `current_role`, `current_schema`, and `session_user` are now called only without trailing parentheses.

### CODE REVIEW

**Comment by mjibson** [comment]
Thanks for this contribution! Unfortunately this is not a feature for which we are able to devote appropriate review resources at the moment.

**Comment by mjibson** [comment]
I closed this a bit hastily. We still might not be able to review soon, but it can at least stay in the queue.

**Comment by jkosh44** [comment]
Hi @OscarTHZhang, thanks for the contribution! As @mjibson said we don't have the review resources right now to give this a full review, but here's some notes from a quick skim.

- You have some failed tests in CI: https://buildkite.com/materialize/tests/builds/59759#018968b4-de4e-43c1-b2df-c49b3eace245. My guess is that we may have been using these functions with parenthesis and need to update our usage.
- We're going to need some new tests associated with this change. You can refer to our guide here: https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-testing.md for instructions on adding and running tests. I think this change should be tested with a `sqllogictest`.

**Comment by OscarTHZhang** [comment]
> Hi @OscarTHZhang, thanks for the contribution! As @mjibson said we don't have the review resources right now to give this a full review, but here's some notes from a quick skim.
> 
> * You have some failed tests in CI: https://buildkite.com/materialize/tests/builds/59759#018968b4-de4e-43c1-b2df-c49b3eace245. My guess is that we may have been using these functions with parenthesis and need to update our usage.
> * We're going to need some new tests associated with this change. You can refer to our guide here: https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-testing.md for instructions on adding and running tests. I think this change should be tested with a `sqllogictest`.

Sure, I will make according changes to this PR

**Comment by jkosh44** [comment]
As a side note, this is a breaking change so we'll probably have to write a migration and an upgrade test.

**Comment by benesch** [comment]
Hi @OscarTHZhang, so sorry for the whiplash here, but after further discussion I think we want to move in the opposite direction with this and actually allow calling _all_ of these special functions with parenthesis. Have updated the original issue accordingly. Thanks again for the PR! It helped us to realize how painful it would be to ban calling these functions without parentheses.

**Pull request closed without merging**
