### PR TITLE
repr,expr: tweak protobuf structure

### PR DESCRIPTION
**Pull request by benesch**
This commit makes four changes to the structure of the protobufization
work (#11735):

  1. Protobuf files use their crate name as their package name. For
     example, the global_id.proto file in mz_repr reports its package as
     mz_repr.global_id.

     This makes it easier to identify where a type lives when reading a
     protobuf file. This will also become necessary when multiple crates
     contain a protobuf message of the same name.

  2. Protobufs use an import path relative to `$ROOT/src`, rather than
     adding each crate root to the import path. This will be important
     when multiple crates contain a protobuf file with the same name;
     the only way to disambiguate is by using a path that includes the
     crate name.

  3. Protobuf files are stored alongside the Rust modules they
     correspond to, rather than living in a separate `proto` module that
     mirrors the module structure. The conversion to/from a Proto$T type
     lives alongside the $T type.

     I find this to be a substantial increase in readability, as you
     don't need to jump between three separate files in two separate
     directories to understand the $T -> Proto$T conversion. Instead you
     need only look at foo.rs and foo.proto, and the two files are side
     by side in the same directory.

  4. The Arbitrary trait is always derived. Conditionally deriving the
     trait only in tests seems like more trouble than it is worth, as it
     is difficult to read through the conditional compilation
     attributes. The extra code will be eliminated from release builds
     via dead code elimination, so there should be no runtime cost to
     the extra trait derivation. There may be a minor increase in
     compilation time, but I suspect it is negligible; it certainly was
     not noticeable while I was developing.

### Motivation

   * This PR refactors existing code.

### Tips for reviewer

This commit is pure code movement. No intended functional change.

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - n/a

### CODE REVIEW

**Review by antiguru — APPROVED** [review]

**Comment by lluki** [comment]
I just had a quick look on my mobile, it looks good to me! I had another proposal for the include! structure here: #11661 maybe it's worth considering this in the context of this PR.

**Review by teskje — APPROVED** [review]
I can confirm that there are no noticeable differences in compilation time when doing a clean build of the `expr` crate. Depending on how many more types we are going to derive `Arbitrary` on, this might change in the future, but it's not an issue now.

**Comment by aalexandrov** [comment]
As as side-effect of (3), we can restrict back the visibility of some fields in the `$T` types that had to be changed to `pub(crate)`.

**Review by aalexandrov — APPROVED** [review]
Looks good. I will try to merge this to unblock all other open PRs in this effort.

**Pull request merged**
