### PR TITLE
tests: mysql-cdc resumption: explicitly list tables

### PR DESCRIPTION
**Pull request by nrainer-materialize**
Nightly: https://buildkite.com/materialize/test/builds?branch=nrainer-materialize%3Atests%2Fmysql-cdc-resumption-explicitly-list-tables

### CODE REVIEW

**Comment by nrainer-materialize** [comment]
@rjobanp, when working on https://github.com/MaterializeInc/materialize/pull/27789, I stumble upon this and I don't understand it.

This change causes

```
^^^ +++
create-source.td:22:1: error: executing query failed: db error: ERROR: reference to public.t2 not found in source: ERROR: reference to public.t2 not found in source
     |
  10 | > DROP SECRET IF EXI ... [rest of line truncated for security]
  13 | > CREATE SECRET mysq ... [rest of line truncated for security]
  17 |     PASSWORD SECRET  ... [rest of line truncated for security]
  21 | 
  22 | > CREATE SOURCE mz_source
     | ^
+++ !!! Error Report
1 errors were encountered during execution
```

and

```
alter-mz.td:10:1: error: executing query failed: db error: ERROR: unknown catalog item 't0': ERROR: unknown catalog item 't0'
     |
   9 | 
  10 | > DROP SOURCE t0;
     | ^
+++ !!! Error Report
1 errors were encountered during execution
```

I might miss something but I don't get why this change is causing any issues. For example, I am not aware that we drop table `t2` anywhere (except directly before its creation). Can you see the issue?

**Comment by nrainer-materialize** [comment]
More logs on `public.t2` not found in workflow `master-changes`:
```
_bk;t=1718961529668$ docker compose up --detach --scale testdrive=0 testdrive
_bk;t=1718961529724$ docker compose run testdrive --var=mysql-root-password=p@ssw0rd --var=mysql-host=mysql configure-toxiproxy.td configure-mysql.td populate-tables.td configure-materialize.td
_bk;t=1718961530209--- configure-toxiproxy.td
_bk;t=1718961530242$ http-request POST http://toxiproxy:8474/proxies
_bk;t=1718961530242{
_bk;t=1718961530242  "name": "mysql",
_bk;t=1718961530242  "listen": "0.0.0.0:3306",
_bk;t=1718961530242  "upstream": "mysql:3306",
_bk;t=1718961530242  "enabled": true
_bk;t=1718961530242}
_bk;t=1718961530247201 Created
_bk;t=1718961530247{"name":"mysql","listen":"[::]:3306","upstream":"mysql:3306","enabled":true,"Logger":{},"toxics":[]}
_bk;t=1718961530542--- configure-mysql.td
_bk;t=1718961530581>> DROP DATABASE IF EXISTS public;
_bk;t=1718961530583>> CREATE DATABASE public;
_bk;t=1718961530587>> USE public;
_bk;t=1718961530587>> CREATE USER materialize IDENTIFIED BY 'materialize';
_bk;t=1718961530593>> GRANT ALL ON public.* TO materialize;
_bk;t=1718961530880--- populate-tables.td
_bk;t=1718961530916>> USE public;
_bk;t=1718961530916>> DROP TABLE IF EXISTS ten;
_bk;t=1718961530919>> CREATE TABLE ten (f1 INTEGER);
_bk;t=1718961530938>> INSERT INTO ten VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10);
_bk;t=1718961530942>> DROP TABLE IF EXISTS t0;
_bk;t=1718961530946>> CREATE TABLE t0 (f1 INTEGER, f2 TEXT);
_bk;t=1718961530962>> DROP TABLE IF EXISTS t1;
_bk;t=1718961530963>> CREATE TABLE t1 (f1 INTEGER, f2 TEXT);
_bk;t=1718961530979>> INSERT INTO t1 SELECT a1.f1 + a6.f1 , 'abc\nxyz' FROM ten AS a1, ten AS a2, ten AS a3, ten AS a4, ten AS a5, ten AS a6;
_bk;t=1718961534630>> DROP TABLE IF EXISTS t2;
_bk;t=1718961534635>> CREATE TABLE t2 (f1 INTEGER, f2 TEXT);
_bk;t=1718961534655>> INSERT INTO t2 SELECT a1.f1 + a6.f1 , 'abc\nxyz' FROM ten AS a1, ten AS a2, ten AS a3, ten AS a4, ten AS a5, ten AS a6;
_bk;t=1718961538254>> DROP TABLE IF EXISTS alter_fail_drop_col;
_bk;t=1718961538259>> CREATE TABLE alter_fail_drop_col (f1 INTEGER, f2 INTEGER);
_bk;t=1718961538274>> INSERT INTO alter_fail_drop_col VALUES (1, 1);
_bk;t=1718961538277>> DROP TABLE IF EXISTS alter_fail_drop_constraint;
_bk;t=1718961538279>> CREATE TABLE alter_fail_drop_constraint (f1 INTEGER NOT NULL);
_bk;t=1718961538296>> INSERT INTO alter_fail_drop_constraint VALUES (1);
_bk;t=1718961538620--- configure-materialize.td
_bk;t=1718961538680Connecting to PostgreSQL server at postgres://mz_system:materialize@materialized:6877...
_bk;t=1718961538680>> ALTER SYSTEM SET enable_mysql_source = true
_bk;t=1718961539234$ docker compose up --detach --wait mysql-replica-1 mysql-replica-2
_bk;t=1718961539284Container mysql-cdc-resumption-mysql-replica-2-1  Creating
_bk;t=1718961539284Container mysql-cdc-resumption-mysql-replica-1-1  Creating
_bk;t=1718961539307Container mysql-cdc-resumption-mysql-replica-2-1  Created
_bk;t=1718961539308Container mysql-cdc-resumption-mysql-replica-1-1  Created
_bk;t=1718961539308Container mysql-cdc-resumption-mysql-replica-1-1  Starting
_bk;t=1718961539308Container mysql-cdc-resumption-mysql-replica-2-1  Starting
_bk;t=1718961539831Container mysql-cdc-resumption-mysql-replica-1-1  Started
_bk;t=1718961539831Container mysql-cdc-resumption-mysql-replica-2-1  Started
_bk;t=1718961539831Container mysql-cdc-resumption-mysql-replica-1-1  Waiting
_bk;t=1718961539831Container mysql-cdc-resumption-mysql-replica-2-1  Waiting
_bk;t=1718961550831Container mysql-cdc-resumption-mysql-replica-1-1  Healthy
_bk;t=1718961550831Container mysql-cdc-resumption-mysql-replica-2-1  Healthy
_bk;t=1718961550834$ docker compose up --detach --scale testdrive=0 testdrive
_bk;t=1718961550894$ docker compose run testdrive --var=mysql-root-password=p@ssw0rd --var=mysql-host=mysql-replica-1 --var=mysql-replication-master-host=mysql configure-replica.td
_bk;t=1718961551322--- configure-replica.td
_bk;t=1718961551356>> STOP REPLICA;
_bk;t=1718961551356>> CHANGE REPLICATION SOURCE TO SOURCE_HOST='mysql', SOURCE_PORT=3306, SOURCE_USER='root', SOURCE_PASSWORD='p@ssw0rd', SOURCE_AUTO_POSITION=1;
_bk;t=1718961551378>> START REPLICA;
_bk;t=1718961552075$ docker compose up --detach --scale testdrive=0 testdrive
_bk;t=1718961552131$ docker compose run testdrive --var=mysql-root-password=p@ssw0rd --var=mysql-host=mysql-replica-2 --var=mysql-replication-master-host=mysql configure-replica.td
_bk;t=1718961552551--- configure-replica.td
_bk;t=1718961552593>> STOP REPLICA;
_bk;t=1718961552593>> CHANGE REPLICATION SOURCE TO SOURCE_HOST='mysql', SOURCE_PORT=3306, SOURCE_USER='root', SOURCE_PASSWORD='p@ssw0rd', SOURCE_AUTO_POSITION=1;
_bk;t=1718961552616>> START REPLICA;
_bk;t=1718961553331$ docker compose up --detach --scale testdrive=0 testdrive
_bk;t=1718961553410$ docker compose run testdrive --var=mysql-root-password=p@ssw0rd --var=mysql-host=mysql --var=mysql-source-host=mysql-replica-2 create-source.td
_bk;t=1718961553921--- create-source.td
_bk;t=1718961553963> DROP SECRET IF EXISTS mysqlpass CASCADE;
_bk;t=1718961554037rows match; continuing at ts 1718961554.036643
_bk;t=1718961554037> DROP CONNECTION IF EXISTS mysql_conn CASCADE;
_bk;t=1718961554081rows match; continuing at ts 1718961554.0809057
_bk;t=1718961554081> CREATE SECRET [query truncated on purpose so as to not reveal the secret in the log]
_bk;t=1718961554137rows match; continuing at ts 1718961554.1370351
_bk;t=1718961554137> CREATE CONNECTION mysql_conn TO MYSQL (
_bk;t=1718961554137  HOST "mysql-replica-2",
_bk;t=1718961554137  USER root,
_bk;t=1718961554137  PASSWORD SECRET mysqlpass
_bk;t=1718961554137)
_bk;t=1718961554195rows match; continuing at ts 1718961554.1944304
_bk;t=1718961554195> DROP SOURCE IF EXISTS mz_source CASCADE;
_bk;t=1718961554235rows match; continuing at ts 1718961554.2350273
_bk;t=1718961554235> CREATE SOURCE mz_source
_bk;t=1718961554235FROM MYSQL CONNECTION mysql_conn
_bk;t=1718961554235FOR TABLES (public.t1, public.t2, public.alter_fail_drop_constraint, public.alter_fail_drop_col);
_bk;t=1718961554254
_bk;t=1718961554665^^^ +++
_bk;t=1718961554665create-source.td:22:1: error: executing query failed: db error: ERROR: reference to public.t2 not found in source: ERROR: reference to public.t2 not found in source
_bk;t=1718961554665     |
_bk;t=1718961554665  10 | > DROP SECRET IF EXI ... [rest of line truncated for security]
_bk;t=1718961554665  13 | > CREATE SECRET mysq ... [rest of line truncated for security]
_bk;t=1718961554665  17 |     PASSWORD SECRET  ... [rest of line truncated for security]
_bk;t=1718961554665  21 | 
_bk;t=1718961554665  22 | > CREATE SOURCE mz_source
_bk;t=1718961554665     | ^
```

[test_build_84308_mysql-cdc-resumption-tests-2.log](https://github.com/user-attachments/files/15925708/test_build_84308_mysql-cdc-resumption-tests-2.log)

**Comment by rjobanp** [comment]
The `DROP SOURCE t0` failure is because you are not including the `t0` table in the source `FOR TABLES` option (when it was `FOR ALL TABLES` it would find the `t0` table and use it:
image


And I think the `public.t2` failure is because `CREATE SOURCE` is called twice with the same set of tables without dropping the source in-between:
image

but I am confused as to how this worked before, and why that is the specific error it returns in this scenario. It should complain that there is already an object called `mz_source`....

**Comment by nrainer-materialize** [comment]
> The `DROP SOURCE t0` failure is because you are not including the `t0` table in the source `FOR TABLES` option (when it was `FOR ALL TABLES` it would find the `t0` table and use it:

True. Fixed that!

> And I think the `public.t2` failure is because `CREATE SOURCE` is called twice with the same set of tables without dropping the source in-between.

No, I don't think so... 

There is a `DROP SOURCE` before.

```
_bk;t=1719213028792> DROP SOURCE IF EXISTS mz_source CASCADE;
_bk;t=1719213028820rows match; continuing at ts 1719213028.8197823
_bk;t=1719213028820> CREATE SOURCE mz_source
_bk;t=1719213028820FROM MYSQL CONNECTION mysql_conn
_bk;t=1719213028820FOR TABLES (public.t0, public.t1, public.t2, public.alter_fail_drop_constraint, public.alter_fail_drop_col);
```

```
_bk;t=1719213101037> DROP SOURCE IF EXISTS mz_source CASCADE;
_bk;t=1719213101082rows match; continuing at ts 1719213101.0814822
_bk;t=1719213101082> CREATE SOURCE mz_source
_bk;t=1719213101082FROM MYSQL CONNECTION mysql_conn
_bk;t=1719213101082FOR TABLES (public.t0, public.t1, public.t2, public.alter_fail_drop_constraint, public.alter_fail_drop_col);
```

> but I am confused as to how this worked before, and why that is the specific error it returns in this scenario.

It confuses me too. Do you want to look into it? Can I support you in any way?

**Comment by nrainer-materialize** [comment]
Got it, thank you!

**Review by rjobanp — APPROVED** [review]

**Pull request merged**
