### PR TITLE
adapter: Fix mz_sessions retractions

### LINKED ISSUE #18607: `mz_internal.mz_sessions` produces invalid retractions
### What version of Materialize are you using?

v0.50.0-dev (16933ddef)

### How did you install Materialize?

Built from source

### What is the issue?

The built-in table `mz_internal.mz_sessions` produces invalid retractions. This is because the code uses the system time when retracting, thus retracting a row that is different from the one that was originally recorded: https://github.com/MaterializeInc/materialize/blob/b3a70feb3ce991a2867326d00a3e2dacc2eb6065/src/adapter/src/catalog/builtin_table_updates.rs#L1185-L1206

@def- You may see some of these in recent nightly output: https://buildkite.com/materialize/nightlies/builds/2150#_.

To reproduce, you need to generate a few sessions in the internal table. This can be done by logging in and out of `psql` twice as follows:
```
sol:materialize vmarcos$ psql -U materialize -h 127.0.0.1 -p 6875 materialize
psql (14.7 (Homebrew), server 9.5.0)
Type "help" for help.

materialize=> select * from mz_internal.mz_sessions;
 id | role_id |        connected_at        
----+---------+----------------------------
 1  | u2      | 2023-04-05 16:05:58.741+00
(1 row)

materialize=> \q
sol:materialize vmarcos$ psql -U materialize -h 127.0.0.1 -p 6875 materialize
psql (14.7 (Homebrew), server 9.5.0)
Type "help" for help.

materialize=> select * from mz_internal.mz_sessions;
ERROR:  Invalid data in source, saw retractions (1) for row that does not exist: [UInt32(1), String("u2"), TimestampTz(CheckedTimestamp { t: 2023-04-05T16:06:07.836Z })]
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jkosh44**
One of the columns in the `mz_sessions` system table is the time at which the session connected. We were generating this timestamp at the same time that we generated the update to the table. As a consequence the addition update and the retraction update would have different timestamps causing invalid retractions.

This commit fixes this issue by saving the timestamp as metadata with each connection and passing in the timestamp to the row update function. It also switches to using deterministic timestamps instead of hard-coding in the system clock.

Fixes #18607

### Motivation
This PR fixes a recognized bug.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by mjibson — COMMENTED** [review]
What do you think about having connect_time be right on the Session itself, and then pack_session_update takes a `&Session`? Sessions are created by ConnClients, which have an adapter Client, which have a now_fn already, so we already know how to make a now without talking to the coordinator.

**Comment by jkosh44** [comment]
> > What do you think about having connect_time be right on the Session itself, and then pack_session_update takes a `&Session`? Sessions are created by ConnClients, which have an adapter Client, which have a now_fn already, so we already know how to make a now without talking to the coordinator.
> 
> I think that's a good idea, I'll push the change shortly.

Done

**Review by mjibson — APPROVED** [review]
LGTM, though if you feel inclined, I think passing a `&Session` to pack_session_update directly is a better choice instead of unwrapping the 3 fields in 2 places. Don't care too hard though.

**Comment by jkosh44** [comment]
> LGTM, though if you feel inclined, I think passing a `&Session` to pack_session_update directly is a better choice instead of unwrapping the 3 fields in 2 places. Don't care too hard though.

Oh sorry, I agree. That completely slipped my mind when updating.

**Pull request merged**
