### PR TITLE
infra: Upgrade Docker images to Ubuntu 24.04

### PR DESCRIPTION
**Pull request by ParkMyCar**
This PR upgrades our base Docker images to Ubuntu 24.04 and then applies a few fixes on top of them.

### Motivation

Keep our images up-to-date, but also fix a bug we were running into with LLVM's `libunwind`, `glibc`, and `jemalloc`.

### Tips for reviewer

I'm not sure if changing the groupid and userid is okay to do and if maybe things in Cloud rely on it.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

**Review by def- — COMMENTED** [review]
If nightly is happy, I'm happy.

**Review by def- — CHANGES_REQUESTED** [review]
`legacy-upgrade-materialized2-1    | environmentd: fatal: creating process orchestrator: setting secrets directory permissions: Operation not permitted (os error 1)`
This might be AppArmor? We could just disable it if we don't care to fix it properly.

**Comment by ParkMyCar** [comment]
> `legacy-upgrade-materialized2-1 | environmentd: fatal: creating process orchestrator: setting secrets directory permissions: Operation not permitted (os error 1)` This might be AppArmor? We could just disable it if we don't care to fix it properly. Alternatively maybe it's the 999->888 switch or something selinux-related on the hosts.

Just switched it back to using groupid and userid 999. It was `ssh` that created a group named 'systemd-journal' with groupid 999. If we create our group first then `ssh` creates 'systemd-journal' with gid 998, we'll see if it works 🤷‍♂️

**Comment by ParkMyCar** [comment]
Also thanks for pushing up additional fixes @def-!

**Review by benesch — APPROVED** [review]
Looks good. Thanks very much!

**Review by def- — APPROVED** [review]
lgtm, the txn wal fencing error (https://buildkite.com/materialize/nightly/builds/9463#0191ce0c-ac19-4087-9df5-399f1d64b107) is https://github.com/MaterializeInc/materialize/issues/29432

**Pull request merged**
