### PR TITLE
sql: remove branch key optimization

### PR DESCRIPTION
**Pull request by benesch**
@frankmcsherry had a hypothesis that this was impeding optimization. The
plans look a lot worse to my eye, but perhaps there is now an easy
transformation to write that makes them look even better than before.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/2944)

### CODE REVIEW

**Comment by frankmcsherry** [comment]
Thanks for doing this! I think the plans are going to look grotty without a few other bits of movement, but if it's ok I'm going to study this and try to sort out which ones we are missing and whether they resolve things. No need to merge this before I put that work in.

**Comment by frankmcsherry** [comment]
One nice thing is that this PR does immediately repair a defective query in `joins.slt`, namely
```
SELECT l1.la, l1.lb
FROM l as l1
WHERE l1.la IN (
    SELECT l2.la + 1
    FROM l AS l2
    WHERE l2.la IN (
        SELECT l3.la + 1
        FROM l as l3
    )
)
```
In master this results in a cross join between `l1` and `l2` when they are introduced to seed the subquery related to `l3` (we are unable to push down the equivalence between their columns, as the `l1.la` column is reduced away). 

Many of the other plans are much less pleasant to look at, but I haven't found any yet that are worse in the sense that they produce *more* rows, rather than just *wider* rows. I'll try and sort out if this is actually the case, and whether the irrelevant columns can be stripped off as part of physical planning (it seems like we need to pass along "will distinct by" to indicate that multiplicities are irrelevant other than in some columns).

**Review by jamii — APPROVED** [review]
:shipit: :rocket:

**Comment by benesch** [comment]
Closing as stale.

**Pull request closed without merging**
