### PR TITLE
Introduce shard refresh rate

### PR DESCRIPTION
**Pull request by JLDLaughlin**
### Background & Problem
Our newest testdrive test ([ci-only/kinesis.td](https://github.com/MaterializeInc/materialize/blob/master/test/testdrive/ci-only/kinesis.td)) has repeatedly hit the Kinesis `ListShards` rate limit: https://github.com/MaterializeInc/materialize/issues/2694.

### Solution
The PR introduces a new `KINESIS_SHARD_REFRESH_RATE` constant. Moving forward, we will only hit the `ListShards` API if it's been longer than 60 seconds (an initial guess at what a reasonable rate would be). This should avoid the rate limit issue and improve Kinesis source performance overall.

NOTE: I am going to start performance testing our Kinesis source this week, so I'll keep an eye on if this seems reasonable and helpful.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/2712)

### CODE REVIEW

**Comment by benesch** [comment]
Hey, sorry, you caught an mzbuild bug in this branch so the tests might not actually be passing on this branch! Can you rebase this on the latest master?

**Comment by JLDLaughlin** [comment]
Awesome! I'm pretty confident this should solve our testing issue -- what should be our criteria from taking the `ci-only` test out of test purgatory?

**Comment by benesch** [comment]
Maybe if it passes on several builds in a row on master? It's unfortunately still failing in this PR, though! Maybe it's because it now takes a full 60s for the new shards to be detected, and so the default timeout of ~12s is way too low? https://buildkite.com/materialize/tests/builds/7033#a4c78546-935f-40b1-a888-2418ebcfad51

**Comment by benesch** [comment]
Feel free to merge without fixing that, though!

**Pull request merged**
