### PR TITLE
sql: better plan for single table function in scalar position

### PR DESCRIPTION
**Pull request by andrioni**
Table functions (set-returning functions) in scalar position are
currently planned as if they were inside a `ROWS FROM` lateral join,
as Postgres does. The issue fixed in this work arises when there is
a single function, which is indistinguishable from a regular lateral
join, but still used to be planned as if using `ROWS FROM`, which
involves adding ordinality information via `row_number()`, which
unfortunately was quite expensive computationally.

More context in #10801.

### Motivation

  * This PR fixes a recognized bug: #10801

### Testing

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - N/A

### CODE REVIEW

**Comment by andrioni** [comment]
The plans in #10801 are now identical after this PR:
```
materialize=> explain select jsonb_object_keys(data) from srf_json;
              Optimized Plan
------------------------------------------
 Source materialize.public.srf_json (u2):+
 | Project (#0)                          +
                                         +
 Query:                                  +
 %0 =                                    +
 | Get materialize.public.srf_json (u2)  +
 | FlatMap jsonb_object_keys(#0)         +
 | Project (#1)                          +

(1 row)

materialize=> explain select key from srf_json, jsonb_object_keys(data) key;
              Optimized Plan
------------------------------------------
 Source materialize.public.srf_json (u2):+
 | Project (#0)                          +
                                         +
 Query:                                  +
 %0 =                                    +
 | Get materialize.public.srf_json (u2)  +
 | FlatMap jsonb_object_keys(#0)         +
 | Project (#1)                          +

(1 row)
```

**Comment by andrioni** [comment]
Ah, I messed up handling table functions that return records, lemme look into it.

**Comment by andrioni** [comment]
OK, tests fixed, just pushed a new commit to make CLA re-run.

**Review by mjibson — APPROVED** [review]

**Comment by philip-stoev** [comment]
@andrioni I am afraid my infrastructure for randomized testing was negatively impacted by the move to Platform so I will need some time to bring it back to shape. Can you wait merging until Monday?

In the meantime, this PR does not have any SLT or testdrive tests, e.g. the query plan from the original ticket itself. Do you mind adding some, or you prefer that I do that?

**Comment by andrioni** [comment]
@philip-stoev no need to rush, this is not urgent!

I can add a couple of tests for the new query plan, no problem at all. I didn't add more tests for correctness because the basic behavior is already covered by current tests, and I don't have a good idea on what to test for the parts that could potentially break (e.g. scoping rules).

**Comment by philip-stoev** [comment]
@andrioni please do add a test for the plan at least so that the plan is locked and a test will fail in case there is a regression. I will test correctness as part of my randomized test.

**Review by philip-stoev — APPROVED** [review]
I am able to see this optimization in action with a randomized workload. There are no wrong results or branch-specific panics or error messages.

**Pull request merged**
