### PR TITLE
persist: call maybe_heartbeat_reader in next_listen_batch loop

### LINKED ISSUE #15396: persist: persist_source does not heartbeat ReadHandle periodically
We recently fixed an issue in `persist_sink` where we did not heartbeat our `WriteHandles` periodically. This was leading to lease timeouts when the sinked collection had a very large initial snapshot, meaning it would take a lot of time before we would start writing and interact with the `Writehandle`. See https://github.com/MaterializeInc/materialize/pull/15198.

A similar issue exists in `persist_source`, where the `ReadHandle` can time out when we don't see new batches for a long time. See this comment:

https://github.com/MaterializeInc/materialize/blob/83bc683394dfcb20dff73075e402310469501b1f/src/persist-client/src/read.rs#L238

### PR DESCRIPTION
**Pull request by danhhz**
There might be some holdup in the next batch being produced. Perhaps we've quiesced a table or maybe a dataflow is taking a long time to start up because it has to read a lot of data. Heartbeat ourself so we don't accidentally lose our lease while we wait for things to resume.

We think this was the cause of some expired reader panics seen in production.

Closes #15396

### Motivation

  * This PR fixes a recognized bug.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Review by pH14 — APPROVED** [review]
⚡

**Comment by pH14** [comment]
LGTM, seems like it should do the trick for the `persist_source` panic

**Comment by aljoscha** [comment]
that was zippy!

**Comment by danhhz** [comment]
TFTRs!

**Comment by danhhz** [comment]
The "Checks + DROP/CREATE replica" failure is #15046. The "Kafka Persistence" one is probably 15026

**Pull request merged**
