### PR TITLE
scalability framework: add diagram explanations

### PR DESCRIPTION
**Pull request by nrainer-materialize**

### CODE REVIEW

**Comment by nrainer-materialize** [comment]
Unrelated: I believe that the current data in the boxplots is not well suited for any explanations. It includes measurements of different operations (for example, union of `InsertDefaultValues` and `SelectCount` operations when running `InsertAndSelectCountWorkload`); this does not make sense. I will need to merge these operations.

**Review by def- — APPROVED** [review]
Maybe show the boxplots inline in the other graph? Then it's easier to compare them

**Comment by nrainer-materialize** [comment]
> Maybe show the boxplots inline in the other graph? Then it's easier to compare them

Not sure if I understand. What do you mean?

**Comment by def-** [comment]
Something like this: https://en.wikipedia.org/wiki/Box_plot#/media/File:Michelsonmorley-boxplot.svg
So you can see all the boxplots in one place and compare their values and skew visually.

**Comment by nrainer-materialize** [comment]
> Something like this: https://en.wikipedia.org/wiki/Box_plot#/media/File:Michelsonmorley-boxplot.svg So you can see all the boxplots in one place and compare their values and skew visually.

Well...
I do plot multiple boxplots _of different endpoints_ with the same settings within the same diagram. For example, boxplots with the same workload and the same number of concurrent connections will be in the same diagram. This is also what one will want to compare.
I am not sure if comparisons with different settings are useful / sensible.

Bildschirmfoto 2023-11-03 um 12 01 27

**Comment by def-** [comment]
I think it makes sense to compare different settings too, but maybe I misunderstand something.

**Comment by nrainer-materialize** [comment]
> I think it makes sense to compare different settings too, but maybe I misunderstand something.

I will need to think about it and experiment a bit. Possible changes are subject to a follow-up PR.

**Comment by nrainer-materialize** [comment]
> > I think it makes sense to compare different settings too, but maybe I misunderstand something.
> 
> I will need to think about it and experiment a bit. Possible changes are subject to a follow-up PR.

This is a boxplot from CI:
latency_InsertWorkload

It obviously does not make sense to press everything into a single boxplot. Though, I can imagine adding additional plots that _group by endpoint_ instead of grouping by connection concurrency. The above figure would then include two plots (one for `v.0.76.0` and one for `v0.77.0-dev`) with all respective connections.

**Comment by nrainer-materialize** [comment]
> I think it makes sense to compare different settings too, but maybe I misunderstand something.

Addressed with https://github.com/MaterializeInc/materialize/pull/22929.

**Pull request merged**
