### PR TITLE
compute: make as-of back-stepping a soft constraint

### PR DESCRIPTION
**Pull request by teskje**
Stepping back the as-of for dataflows with persisted outputs relies on the compute controller holding back input collections for these dataflows accordingly. This is currently not guaranteed during a release upgrade, as the holding-back was introduced at the same time as the stepping-back in as-of selection.

To avoid panicking in upgrade tests, this PR makes the stepping-back a soft as-of constraint. It is still required for the correctness of CTs so we need to revert this PR in a follow-up. This should be safe to do after at least one Mz version was released with the new holding-back behavior, and will definitely be safe to do once the old holding-back behavior has rotated out of our upgrade tests.

### Motivation

  * This PR fixes a recognized bug.

Fixes https://github.com/MaterializeInc/database-issues/issues/8718

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

**Comment by teskje** [comment]
The upgrade checks seem happy with this: https://buildkite.com/materialize/nightly/builds/10224#_

Not sure about the failure in "Checks 0dt upgrade, whole-Mz restart", but it doesn't have a panic in its logs afaict.

**Review by danhhz — APPROVED** [review]

**Comment by danhhz** [comment]
> Not sure about the failure in "Checks 0dt upgrade, whole-Mz restart"

Looks like the CREATE MV ran while we had an envd in read-only mode, and hung. I recall there's some gotchas around DDL and 0dt right now, but not the specifics. Otoh, this PR does touch the as_of selection for MVs

```
platform-checks-mz_2-1              | environmentd: 2024-10-31T12:13:25.055033Z  INFO coord::handle_message{kind="command-execute"}:handle_message:message_command:coord::handle_execute{session="80165465-97c7-443c-9f13-534d2da3661b"}:coord::handle_execute_inner{stmt="CREATE MATERIALIZED VIEW sink_partition_by_debezium_view2 AS SELECT count(*) AS c1, count(f1) AS c2, count(DISTINCT f1) AS c3, min(f1), max(f1) FROM (SELECT (before).f1, (before).f2 FROM
platform-checks-mz_3-1              | environmentd: 2024-10-31T12:13:25.312500Z  INFO mz_adapter::coord: not advancing timelines in read-only mode
```

**Review by def- — APPROVED** [review]
The timeout in nightly is a known flake, feel free to ignore.

**Comment by teskje** [comment]
Cool, thanks for checking!

**Pull request merged**
