### PR TITLE
storage-controller: detach spawned tasks from current span

### PR DESCRIPTION
**Pull request by mjibson**
Mark the otel context as a parent (so the spawns show up in tracing) but not as trace children, so that the spawns don't display as blocking the parent span.

### Motivation

  * This PR fixes a previously unreported bug.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - n/a

### CODE REVIEW

**Review by danhhz — COMMENTED** [review]
Wow I think your tracing knowledge is already starting to surpass mine. I didn't even realize that there was a difference between having a span as a parent and attaching a parent manually via otel ctx.

I hate to ask to you recompile envd, but any chance you could put in a screenshot of what this looks like in Tempo for something like an `INSERT` which _does_ want to block on this work?

**Comment by mjibson** [comment]
Here's a `CREATE TABLE`. You can see the `PersistTableWriteWorkerInner::send` span outlives the actual request span, which is visually correct since it doesn't block the response to anything, but still was doing work.

All of this is from Gus. He told me what to type and I typed it.

image

**Comment by mjibson** [comment]
And here's the `INSERT`, which does block as expected?

image

**Review by danhhz — APPROVED** [review]
:100:

**Pull request merged**
