### PR TITLE
adapter: Add debug log for statements in parser

### PR DESCRIPTION
**Pull request by jkosh44**
This commit adds a debug log that logs all statements given to the parser.

### Motivation
This PR adds a feature that has not yet been specified.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [X] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [X] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - There are no user-facing behavior changes.

### CODE REVIEW

**Comment by mjibson** [comment]
Not opposed to this, but would like to note that pgwire already has bunches of traces that log various pgwire messages. Maybe some of those need to be bumped up to debug. Would that have helped, or was the problem over http?

**Comment by jkosh44** [comment]
> Not opposed to this, but would like to note that pgwire already has bunches of traces that log various pgwire messages. Maybe some of those need to be bumped up to debug. Would that have helped, or was the problem over http?

I don't really have a strong opinion on this other than I thought it would be easy to implement. I doubt the problem was over HTTP, but the idea is that it would be helpful to get a log of all the queries hitting envd during an incident.

**Review by mjibson — APPROVED** [review]
Seeing that it's off by default and can be enabled per module, probably worth it?

**Comment by jkosh44** [comment]
@pH14 Do the observability folks think this trade-off is worth it? If so I'll merge.

**Review by pH14 — APPROVED** [review]
LGTM. I think this would be very helpful to have, and in the past during investigations folks have either not known about the pgwire logs or gotten overwhelmed by them

**Pull request merged**
