### PR TITLE
cloudtest: Clarify shared code approach in design

### PR DESCRIPTION
**Pull request by necaris**
### Motivation

   * This PR refactors existing code.

### Tips for reviewer

Please comment with suggested solutions & we can iterate!

### CODE REVIEW

**Comment by nrainer-materialize** [comment]
Thanks a lot for writing this down, @necaris!

My thoughts on the approaches:

**1) Change update process**
* ➕ probably lowest effort to set up (assuming the commits to be reviewed can be identified efficiently)
* ➖ all (Python) code from the mz repo is included (not just test frameworks but also tests), which seems less clean

**2) Own cloudtest repo**
* ➕ clear boundary
* ➖ some overhead due to handling a further repo
* ➖ mz repo also needs to include a submodule (but does also already have one with sqllogictests)

**3) Bounded module**
* ➕ clear boundary
* ➕ versioning included
* ➖ probably setup more effort than 1)
* One way could be to internally publish a wheel and to include that.
* Solution can be combined with 2).

I have a slight preference towards 2) or 3).

**Comment by philip-stoev** [comment]
The problem with having cloudtest in a separate repo is that the HEAD of this repo must always be compatible with the latest HEADs of cloud and mz, as well as some set of older tags of those two repositories. This will be more difficult to ensure v.s. having cloudtest in one of the two main repositories.

How about a third option:
- have the cloud repository have the Mz repository twice as a submodule
- once submodule is used for cloudtest only, and can be incremented at will
- the other (the existing submodule) is used for all other purposes and is incremented according to the existing rules.


I think we need @benesch's input here.

**Comment by necaris** [comment]
> The problem with having cloudtest in a separate repo is that the HEAD of this repo must always be compatible with the latest HEADs of cloud and mz, as well as some set of older tags of those two repositories. 

Can you help me understand why this is necessary -- why `HEAD` must be compatible? It's not immediately clear to me.
 
> How about a third option:
> 
> * have the cloud repository have the Mz repository twice as a submodule
> * once submodule is used for cloudtest only, and can be incremented at will
> * the other (the existing submodule) is used for all other purposes and is incremented according to the existing rules.

My concern with this is the need to now manage _two_ submodules! One can be confusing enough IMHO. I would strongly prefer another option over this.

There are a couple of other "hidden" options here:

1. In the cloud repo, using the `cloudtest` dependency [from GitHub rather than the submodule](https://pip.pypa.io/en/latest/topics/vcs-support/#git), which would allow us to use a specific commit (which may not match the submodule). This adds some friction to cloud development (needing to push commits and re-install the dependency to see changes), but it's not too much.
2. In the cloud repo, using a local wrapper module rather than using the cloudtest functions directly, so that we can patch existing functionality as needed during development. Python's dynamic nature lets us take this quite far, so it should be sufficient.

> I think we need @benesch's input here.

@nrainer-materialize @doy-materialize and I are talking about this live later, and will update with any conclusions.

**Comment by nrainer-materialize** [comment]
A short update about the discussion with @doy-materialize and @necaris:
* We would like to proceed with approach 1), which is about updating cloud team processes to allow more frequent submodule syncs. @necaris will trigger this.
* We will adjust the PR template in mz repo to reference cloud tests as well as orchestration. In addition, the cloud team shall be added as code owners to the shared cloudtest logic. This will be addressed with https://github.com/MaterializeInc/materialize/pull/21004.

**Comment by necaris** [comment]
After our conversation, @nrainer-materialize @doy-materialize and I agreed we'd _strongly_ prefer process changes that allow us bump the submodule at will. We also agreed we'd need to ensure further coordination whenever we change test code, as bumping the submodule is sometimes non-trivial. I've filed https://github.com/MaterializeInc/materialize/pull/21004 to help with those process changes, but otherwise I believe our options are:

1. Require reviews on PRs in this repository. (I'd like this too we're not the only stakeholders -- i.e. above our pay grade :wink:)
1. Add a script in the Cloud repo to orchestrate the process of bumping the submodule, including finding all unreviewed commits, so that we can mark each as appropriately reviewed in that step.

**Comment by necaris** [comment]
Superseded by #21004

**Pull request closed without merging**
