### PR TITLE
*: plumb PersistClientCache to everywhere it's needed

### PR DESCRIPTION
**Pull request by danhhz**
We need a singleton PersistClientCache so that it can internally share
postgres/aurora connections. It also needs to have access to a
MetricsRegistry so persist can internally hook up its metrics, which
this static singleton workaround introduced in 12216 doesn't. So,
replace the workaround with instantiating it once at storaged/computed
startup and explictly plumbing it everywhere it needs to go.

### Motivation

  * This PR adds a feature that has not yet been specified.

### Tips for reviewer

I'm about to start hooking up metrics internally in persist and we need this to get it all working end-to-end. The PRs are mechanically pretty independent, though.

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - N/A

### CODE REVIEW

**Comment by benesch** [comment]
I think you need @petrosagg for this one. I'm out of commission all tomorrow and I wasn't able to immediately develop an opinion here!

**Comment by danhhz** [comment]
@petrosagg any thoughts on this?

**Review by benesch — APPROVED** [review]
This looks good to me!

**Comment by danhhz** [comment]
TFTR!

**Pull request merged**
