### PR TITLE
sql: allow casting mz_timestamp to timestamp

### PR DESCRIPTION
**Pull request by maddyblue**
We are improving ergonomics around mz_now() by allowing it to be more easily interacted with as a timestamp.

### Motivation

  * This PR adds a feature that has not yet been specified.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - Allow `mz_now()` and `mz_timestamp` types to be casted to `timestamp` and `timestamptz`.

### CODE REVIEW

**Review by jkosh44 — APPROVED** [review]

**Comment by benesch** [comment]
Works for me, but I certainly don't have my head around all the implications. Who are the right ~compute~ cluster folks to loop in?

**Comment by maddyblue** [comment]
Dunno! @ggevay could you chime in or triage to another?

**Comment by ggevay** [comment]
There is a comment at the top of `mz_timestamp.rs`:
```
// Conversions to MzTimestamp, and a single conversion from MzTimestamp to
// String. In general we want to make MzTimestamp a more opaque type, so we
// easily support casting things to it but not from it.
```

Maybe we wanted to make it an opaque type because of the plans to make our timestamps multidimensional at some point? But even in that case, the cast could just drop the extra dimension(s), so maybe it's still fine to have it? It would be a lossy cast, like float to integer. Maybe @frankmcsherry knows what is the current thinking on this.

A less esoteric reason that I sometimes heard for not having this cast originally is to steer away users from trying to write a temporal filter with the arithmetic on the "wrong" side in a one-off select, and then be surprised when the same thing doesn't work in a long-running dataflow. Before this PR:
```
create table t1(t timestamp, x int);

-- allowed
select * from t1 where t + interval '1 day' > mz_now();

-- not allowed
select * from t1 where t > mz_now() - interval '1 day';

-- explicit cast also not allowed
select * from t1 where t > mz_now()::timestamp - interval '1 day';
```
After this PR:
```
create table t1(t timestamp, x int);

-- allowed
select * from t1 where t + interval '1 day' > mz_now();

-- not allowed
select * from t1 where t > mz_now() - interval '1 day';

-- explicit cast allowed
select * from t1 where t > mz_now()::timestamp - interval '1 day';
```
However, creating a long-running dataflow with the arithmetic on the "wrong" side is still not allowed even after this PR:
```
materialize=> create materialized view mv1 as select * from t1 where t > mz_now()::timestamp - interval '1 day';
ERROR:  internal error: Unsupported temporal predicate. Note: `mz_now()` must be directly compared to a mz_timestamp-castable expression. Expression found: (#0 > (mz_timestamp_to_timestamp(mz_now()) - 1 day))
```
This might be somewhat undesirable, because we might want to minimize those situations where something is allowed in a one-off select, but not in a long-running dataflow. But if I understand correctly, https://github.com/MaterializeInc/materialize/pull/27001 is intended to make this work even in a long-running dataflow? Btw. is that work going to be scheduled in the near term? In any case, I'd say this is a SQL Council question. 

My 2 cents are that having this as an explicit cast is fine, but it would be great to add a sentence to
https://materialize.com/docs/sql/types/mz_timestamp/ 
about how to use it in temporal filters and/or point to the temporal filters doc page.

(Btw. I have several tests where I was hacking around not having this cast, where [I wanted an MV that is refreshed a few seconds after its creation, rather than precisely at its creation](https://github.com/MaterializeInc/materialize/blob/3214463db5b1714055fcc6fe874ace88fb6a1407/test/sqllogictest/materialized_views.slt#L1206). But this was just a test thing, I wouldn't expect this to be a common thing for users.)

**Comment by maddyblue** [comment]
Thanks for the thoughts! I've changed the source code comment to reflect our new outlook on this type. More context about why we think this can be found in the [notion braindump](https://www.notion.so/materialize/mz_now-braindump-3acde85e02d84cb09808d7c63dab009a). We had a meeting and came to the conclusion to increase ergonomics around this type by explicitly going with "mz timestamp always means unix epoch milliseconds". The temporal filter and dataflow stuff you bring up is very slowly being discussed at https://github.com/MaterializeInc/materialize/pull/27001.

It sounds like, from a cluster perspective, there's no blockers on this issue?

**Comment by ggevay** [comment]
Thanks for the links!

> It sounds like, from a cluster perspective, there's no blockers on this issue?

Indeed, I don't see any blockers from the Cluster side.

**Comment by frankmcsherry** [comment]
> ... we might want to minimize those situations where something is allowed in a one-off select, but not in a long-running dataflow.

I think this is the main reason to be concerned, and that this change is a trapdoor change that we cannot undo. I think we don't have strong product thought about "if I develop `SELECT` queries, can I make them into dataflows?" and this moves farther away from "yes, of course". I do think that is a product glitch, and it would help to find the product owner for that dimension.

**Pull request merged**
