### PR TITLE
feature benchmark: fix ExactlyOnce scenario

### PR DESCRIPTION
**Pull request by nrainer-materialize**
Nightly: https://buildkite.com/materialize/nightlies/builds/5961

### CODE REVIEW

**Comment by nrainer-materialize** [comment]
@sploiselle: Does this make sense, is this what you had intended? If you want to re-create `source_cluster` here, we need to drop it first since it is already in the scenario's `init` method. Furthermore, we would need to recreate `source1` in this case. However, this does not seem to succeed if we create `sink1_check` in the same cluster, is this expected?

**Review by def- — APPROVED** [review]

**Comment by sploiselle** [comment]
Yes that should work! We are creating more clusters now than we were before so bumping the limit also makes sense.

**Comment by nrainer-materialize** [comment]
> Yes that should work! We are creating more clusters now than we were before so bumping the limit also makes sense.

Thanks for the feedback! I will merge it once the nightly builds completes / succeeds.

**Comment by nrainer-materialize** [comment]
Build is green, merging now since the commit for the release has already been chosen.

**Pull request merged**
