### PR TITLE
persist: use arrow for record encoding

### PR DESCRIPTION
**Pull request by danhhz**
Wow umm, the encoded size of this is way bigger than I expected.

### CODE REVIEW

**Comment by ruchirK** [comment]
Didn't review this in depth - let me know if I should. Just curious -- is there a point where the columnar encoding starts to be smaller or is it always ~ 20x bigger?

**Comment by danhhz** [comment]
Nah nothing for you to look at here yet, just an FYI on what this might look like given that you're still poking around in ColumnarRecord.

> Just curious -- is there a point where the columnar encoding starts to be smaller or is it always ~ 20x bigger?

XD 20x is just the arrow file format having an absurd amount of per-file overhead and these tests being a worst case tiny amount of data. Arrow is targeted at in-mem usage and has totally different trade offs (as little cpu usage as possible, everything is directly usable with no decoding, etc), so now that I think about it, I realized it was never a good fit for us. Parquet is the on-disk companion to Arrow and is better (~500 bytes out of the box), but the metadata bits of that are pretty bloated (each column's schema is stored 12x for... reasons). The Parquet spec is surprisingly under-documented (or I'm missing something) so still wrapping my head around how much of that is required vs optional redundancy (I've gotten it down to ~300 bytes by eliminating a couple of them -- and there's more fat to trim -- but zero idea if that's allowed by the spec). IIUC Parquet is basically the Google Dremel paper: https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/36632.pdf.

Anyway, to answer your direct question, columnar disk formats absolutely end up being much much smaller than non-columnar for any non-trivial amount of data because of how much compression you can get out of e.g. an array of 8-byte isizes that are each a dataflow diff (so in practice probably 1 or -1). Key-offset and val-offset are ideally suited for (I forget what it's called) the one where you store each thing in the column as a diff from the last one. Key-data and val-data will both probably be okay with snappy/gzip. No idea what to expect from timestamps, might be few enough values that dict will work well.

This is certainly not exhaustive but I googled for "parquet compression results" and this is the first article I found: https://blog.cloudera.com/benchmarking-apache-parquet-the-allstate-experience/

> The final test, disk space results, are quite impressive for both formats: With Parquet, the 194GB CSV file was compressed to 4.7GB; and with Avro, to 16.9GB. That reflects an amazing 97.56% compression ratio for Parquet and an equally impressive 91.24% compression ratio for Avro.

**Comment by ruchirK** [comment]
>  Key-offset and val-offset are ideally suited for (I forget what it's called) the one where you store each thing in the column as a diff from the last one.

ive heard that called differential encoding and delta encoding

**Comment by danhhz** [comment]
ah! delta was what I was thinking of

**Comment by danhhz** [comment]
https://github.com/apache/parquet-format/blob/master/Encodings.md

**Comment by danhhz** [comment]
Replaced by #9701

**Pull request closed without merging**
