### PR TITLE
testdrive: minor refactorings

### PR DESCRIPTION
**Pull request by nrainer-materialize**
### Commits
9fbacdb33b testdrive: extract MaterializeState
9699caa22f testdrive: move materialize_state declaration up
d50fefad99 testdrive: extract create_materialize_connection

### CODE REVIEW

**Comment by nrainer-materialize** [comment]
This is the PR in which I was about to reconnect to mz on statement timeouts to address [this comment.](https://github.com/MaterializeInc/materialize/pull/26496#pullrequestreview-1992412899) We figured out that reconnecting will no longer be necessary. This PR contains some preparatory refactorings, which we anyway may or may not want to merge if they look good.
Commit-wise reviewed recommended. It compiles but tests are apparently not happy yet. I am least confident about the last commit.

**Review by guswynn — APPROVED** [review]
looks great!!

**Comment by nrainer-materialize** [comment]
Well, the tests are rather unhappy. @guswynn, do you have an idea what might go wrong?

**Review by guswynn — COMMENTED** [review]
@nrainer-materialize nothing obviously wrong with the code to me, which probably means something subtle changed; maybe a variable being shadowed somewhere, and some config being set wrong?

**Comment by nrainer-materialize** [comment]
> @nrainer-materialize nothing obviously wrong with the code to me, which probably means something subtle changed; maybe a variable being shadowed somewhere, and some config being set wrong?

Thanks. I had another look at it today. I know that d50fefad99a60b0eeefb23bcfb28888690fa827a, the last commit, is the problematic one; builds on other commits pass. I compared the config and <s>did not spot any differences.</s> found now something: `create_materialize_state` already uses the `pgclient` but is now invoked before `task::spawn(|| "pgconn_task", pgconn)`. Let me reorder these two statements...

**Comment by nrainer-materialize** [comment]
Build passes now 😀

**Comment by guswynn** [comment]
nice catch @nrainer-materialize !!

**Pull request merged**
