### PR TITLE
expr,sql: support distinct explicit and implicit casts

### PR DESCRIPTION
**Pull request by benesch**
Casting between certain data types has different behavior depending on
whether the cast is explicitly requested by the user (i.e., via CAST or
the :: operator) or implicitly selected by a function or operator.
Generalize that notion and thread it through our sql and expr crates.

So far this only impacts the `concat` function, but having it as a
generalizable form of cast behavior paves the way for the other data
types that have different explicit and implicit casting behavior.

### CODE REVIEW

**Comment by benesch** [comment]
Pushed up another commit to add support for the `||` operator, since I was in the area.

**Comment by sploiselle** [comment]
@benesch could you throw a quick description of this in [the operator docs](https://materialize.io/docs/sql/functions/#operators)? I naively assume this means adding a String section, as well, but acknowledge that the existing structure is probably flawed in some way that makes that onerous.

**Comment by benesch** [comment]
Separate PR for the docs to avoid expensive CI: https://github.com/MaterializeInc/materialize/pull/2231

**Comment by benesch** [comment]
👍 makes sense. Filed #2232 to track. Thanks for taking a look at this!

**Pull request merged**
