### PR TITLE
sql: hoist non-byte equality into SQL planning

### PR DESCRIPTION
**Pull request by sploiselle**
### Motivation

This PR adds a known-desirable feature, or at least the preconditions for it. #7613

### Description

_**NOTE:** This might qualify for a design doc, but I adapted this from one of
@benesch's PRs (spawned in response to a design doc) #7572, so hoping to bypass
that effort given some of the start-stopping on this solution._

Rows require byte equality, but not all types support naive byte equality––e.g.
`numeric` and `char.`

Materialize currently handles this by ensuring only one canonical representation
for a value is ever packed into a row. For example, "reducing" all `numeric`
values by trimming all trailing insignificant zereoes from the values. This
approach works for `numeric` because the bits lost in canonicalization are
semantically insignificant.

However, for `char` data, the bits that are insignificant for equality have
semantic differences for functions that take `char` arguments. This means we
take care to "uncanonicalize" data getting passed to functions that take `char`
arguments, but this requires that we track the original width of the value to
resaturate it in appropriate contexts.

This approach is insufficient to handle `char list` and `char[]`, though,
because it is possible to create composite values whose elements' widths differ,
e.g. in PG:

```sql
SELECT ARRAY['a'::char(2), 'a'::char(3), 'a'::char(4)];
```
```
{"a ","a  ","a   "}
```

Because there are multiple values, it isn't possible to track the amount of
blank padding you should resaturate after canonicalizing the value.

For more discussion, see #7569, #7572.

The approach taken in this PR instead hoists the requirement for handling
non-byte equality into the SQL layer in all situations where equality matters,
i.e. distinct, joins, group by, order by, and calls to equality functions. This
way we can pack non-canonicalized datums into rows when possible, and only rely
on canonicalizing values where it's necessary. This will let `char list`
non-destructively store non-canonicalized values (i.e. those of differening
widths).

The advantage of this approach is that it lets the SQL layer have total control
over which data gets presented to the dataflow layer without changing the
performance users experience when not using these data types.

The downside of this approach is currently that operations that invoke
canonicalization can only return canonicalized data to users. This is an
improvement over the current situation (which unilaterally canonicalizes
values), but is a shortcoming nonetheless. It's possible to mitigate this in
some circumstances at some point in the future where we resaturate values after
performing equality operations on them, but that work is outside of the scope of
this PR.

### Tips for reviewer

@asenac pinging you because this bleeds over into `RelationExpr` and will,
ostensibly, need to be included in your upcoming refactor.

### Checklist

- [x] This PR has adequate test coverage.
- [docs will be incoming if this is approved] This PR adds a release note for any user-facing behavior changes.

### CODE REVIEW

**Review by frankmcsherry — COMMENTED** [review]
I'm not sure I understand the implications of all of this, so I wanted to talk through them. If I have a collection with a numeric column, and I build an index on it using that column, my sense is that this index will not be useful for join planning because it will need to have been an index on the canonicalization of that column. Are there other examples where previously useful assets are likely to break? Should we expect to carry around both the canonical and non-canonical version of each field, because one needs to later call `canonicalize` on the non-canonical version?

There is a related design, lmk what you think, where you use *types* to express whether a thing is canonical or not, rather than expressions. These types could coerce to each other, and you would always be clear in the output whether your type was canonical or not (vs somewhat ambiguous about whether you are seeing a mangled number). It would probably (?) make it a lot easier to diagnose why certain queries are planning badly when types don't line up.

In the same vein, we have different types for ints and floats and such, rather casting functions wrapped around `numeric`, for example.

A different way of saying something similar: this seems to be "not zero cost" in that it imposes a cost on people who do not want or plan to use non-canonical decimals. They are unable to opt out of canonicalization, and have to do the tap dance with inserting it in their indexes, and potentially other expressions if they want to avoid carrying redundant data.

**Review by mjibson — COMMENTED** [review]
I have a concern that a programmer must happen to know that they need to do this when writing planning logic for some sql operations, and we will have some long tail of silent bugs where we missed adding in this canonicalization step and do the wrong thing until a user notices and tells us. For example I'm not sure if the things done here are demonstrably all of the places we need to do this. I am not opposed to us deciding we'll be careful and attempt to find all the places, but I'm interested in a solution that enforces correctness instead of making it opt in.

**Comment by frankmcsherry** [comment]
> and we will have some long tail of silent bugs where we missed adding in this canonicalization step and do the wrong thing until a user notices and tells us.

That's a good point. Examples of things to watch for, but idk include: subquery `ORDER BY .. LIMIT` expressions that turn in to `TopK` and need their correlated variable canonicalized (my guess is that we will correlate on the columns, not expressions of the column, and be correlated with non-canonical records).

**Comment by asenac** [comment]
Thanks for the heads-up. I'm OK with this approach although I'd probably have kept the SQL semantics implicit in the `Hir` and would have made them explicit during lowering. It's essentially the same issue as with the semantics around NULL. The high level representation would have all SQL semantics implicit, making SQL-to-SQL transformations easier, and lowering would be responsible for making explicit those semantics in the lower-level representation that provides other lower-level primitives with different semantics.

**Comment by frankmcsherry** [comment]
Turning this a bit into a design spitball, but: lowering does in principle seem like a place where one could slot in the extra column I'm so excited about, rewriting "non-canonical" data as a pair of "canonical data" and "rehydration data", with equality only considering first columns, and grouping explicitly projecting away the second column (unless someone really wants to put a `agg(rehydraition)` in there, at non-trivial dataflow cost).

**Comment by sploiselle** [comment]
There have been a number of suggestions here and rather than address each at
length, I'll begin by saying that the juice is not worth the squeeze with this
PR. No one is desperately vying for `char list`, and collated strings are still
unplanned work, so this seems like the wrong time to reshape a bunch of code
that is currently sufficient.

For more color: it seems possible to put the canonicalization code within
lowering by relying on a pseudo-visitor, `HirRelationExpr::typ`, and some
fastidious bookkeeping about which expressions need to be rewritten into a
canonicalized form. I think this assuages concerns about having the
canonicalization code strewn about the SQL planner.

However, @frankmcsherry's concerns around generating arrangements on
non-canonicalized data are well taken. The solution for keeping two columns of
data and using them sometimes but projecting them away others is something I
haven't been able to make much progress toward, though. I chatted
with @asenac and @benesch about this and both agreed it's challenging with the
current lowering code or something adjacent. I believe with more time or more
experience with handling arrangements, this could be feasible, but the value of
the features this immediately unlocks doesn't seem worth the investment.

@frankmcsherry if this implementation excites you or seems eminently doable from
your perspective, glad to either put in the elbow grease on a sketch you might
supply, or come to office hours to have a chat.

**Comment by frankmcsherry** [comment]
> @frankmcsherry if this implementation excites you or seems eminently doable from
your perspective, glad to either put in the elbow grease on a sketch you might
supply, or come to office hours to have a chat.

I'm happy to discuss it, but it isn't something I would want to force anyone in to doing. It seems to line up best with my understanding of what we want to express post-lowering, but I can imagine that along the way lowering will make many sads.

**Pull request closed without merging**
