### PR TITLE
System tables: make all id columns suffixed with `_id`

### PR DESCRIPTION
**Pull request by chaas**
Be consistent in using the _id suffix for all columns that represent an identifier.
Columns updated:

Across multiple tables:
* worker -> worker_id
* operator -> operator_id

mz_dataflow_channels:
* channel -> channel_id
* source_node & source_port -> from_index & from_port
* target_node & target_port -> to_index & to_port

mz_message_counts:
* source_worker -> from_worker_id
* target_worker -> to_worker_id

mz_materialization_dependencies:
* dataflow -> export_id (also tackles #14397)
* source -> import_id

mz_materialization_frontiers & mz_worker_materialization_source_frontiers:
* source -> source_id
_note: I'm still not sure what to do with this one. The table uses the term source in it directly, but it's a confusing b/c it's a storage source for the dataflow, which corresponds to either `mz_sources.id`, `mz_tables.id`, or `mz_materialized_views.id`._

### Motivation

   * This PR refactors existing code. #14398

### Tips for reviewer

Sanity check that these new ids all make sense. There was a lot of conversation on  #14398 and I believe I captured the final state.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-protobuf` label.
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
The release will rename system table columns that represent identifiers to be suffixed with `id`.

### CODE REVIEW

**Review by benesch — APPROVED** [review]
This looks good to me. Thank you for updating all the troubleshooting queries, too! I didn't go through this with a fine-toothed comb, FYI—but I'm in favor of merging sooner rather than later. This kind of PR will rot quickly. If there does turn out to be a misnamed column, it's easy enough to fix it in a later PR.

**Comment by benesch** [comment]
> mz_materialization_frontiers & mz_worker_materialization_source_frontiers:
> * source -> source_id
> _note: I'm still not sure what to do with this one. The table uses the term source in it directly, but it's a confusing b/c it's a storage source for the dataflow, which corresponds to either `mz_sources.id`, `mz_tables.id`, or `mz_materialized_views.id`._

Can we use the same trick of using "import"? `mz_materialization_import_frontiers` reads great to me! And it'll read even better if we rename `materialization` to `compute`, or somesuch, as in `mz_compute_import_frontiers`.

**Review by vmarcos — COMMENTED** [review]
I am in agreement here with Nikhil that `mz_compute_import_frontiers` would be a much improved name for `mz_materialization_source_frontiers`. For consistency, we should then:

- Ensure that `mz_worker_materialization_source_frontiers` is renamed to `mz_worker_compute_import_frontiers`.
- Ensure that `mz_materialization_dependencies` is renamed to `mz_compute_dependencies`.
- Ensure that `mz_materialization_frontiers` and `mz_worker_materialization_frontiers` are renamed to `mz_compute_frontiers` and `mz_worker_compute_frontiers`.
- Ensure that `mz_worker_materialization_delays` is renamed to `mz_worker_compute_delays` or alternatively to `mz_compute_delays`.
- Ensure in all of the above that `source_id` is renamed to `import_id` and that `global_id` are renamed as `export_id`.

I am not sure what to do about `mz_materializations`, though. Perhaps call it `mz_compute_exports`?

If people think that the set of changes above would be too much for one PR, I am totally happy to move forward with the current set of changes and address the above in a separate PR.
 
@chaas  @benesch What do you think?

**Comment by chaas** [comment]
Yeah the idea was to tackle `_materialization` -> `_compute` as part of https://github.com/MaterializeInc/materialize/issues/14313. Was thinking it'll be cleaner to have that as a separate PR. I can leave this as `source_id` for now then I guess, and do the table rename as part of the next wave.

Also `global_id`->`export_id` change conflicts with this original PR to rename `global_id` -> `object_id` https://github.com/MaterializeInc/materialize/pull/14701. Do you think I should scrap that PR and use `export_id` in all of those cases instead?

**Comment by vmarcos** [comment]
> Yeah the idea was to tackle `_materialization` -> `_compute` as part of #14313. Was thinking it'll be cleaner to have that as a separate PR. I can leave this as `source_id` for now then I guess, and do the table rename as part of the next wave.
>

This sounds very reasonable to me, so no objections from my side to merge the current round of changes.
 
> Also `global_id`->`export_id` change conflicts with this original PR to rename `global_id` -> `object_id` #14701. Do you think I should scrap that PR and use `export_id` in all of those cases instead?

This is an interesting point. In the currently named `mz_*materialization_*` relations, the `global_id` refers to a `global_id` in `mz_materializations`, i.e., we are talking about the ID of an index or of a materialized view. In the compute layer, these are export IDs of a dataflow. So we are referring only to a specific subset of `global_id` values that might appear in `mz_objects`. In my opinion, it would be thus more elegant to keep `mz_materializations` (e.g., in the form of `mz_compute_exports`) and rename the `global_id` columns there and in other `mz_*materialization_*` relations to `export_id`. Not sure what others think, but this could be an input for discussion in the context of #14313.

**Review by vmarcos — APPROVED** [review]

**Pull request merged**
