### PR TITLE
compute-types: perform lowering within a `Context`

### PR DESCRIPTION
**Pull request by teskje**
This PR introduces a `lowering::Context` type within which MIR-to-LIR lowering is performed. The advantage of doing so is that context information, such as the current bindings and feature flags, don't need to be passed around as parameters through all recursive method calls anymore. This will also make it easier to add additional pieces of context in the future, like a counter that keeps track of allocated LIR node IDs.

### Motivation

  * This PR adds a known-desirable feature.

Part of #24636: The `Context` makes it easier to keep track of the state required to assign LIR node IDs.

   * This PR refactors existing code.

### Tips for reviewer

The first commit is pure code movement and doesn't change anything about the touched code. Focus the review on the second commit!

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - N/A

### CODE REVIEW

**Review by aalexandrov — APPROVED** [review]
I like that, especially because we can use `Context` to pass other things that might be affected by MIR ⇒ LIR lowering side effects in the future (`MetricsRegistry`, `DataflowDescription`).

Let's check with @frankmcsherry whether he is OK with the refactor before we merge this.

**Comment by aalexandrov** [comment]
Things that can be done as a follow up:

1. Call
	```rust
	let context = lowering::Context::new(
	    desc.debug_name.clone(),
	    enable_specialized_arrangements,
	    enable_reduce_mfp_fusion,
	);
	let dataflow = context.lower(desc)?;
	```
	in the `Optimize` implementations in `adapter/src/optimize`.
2. Change `Plan::finalize_dataflow` to `Plan::optimize_dataflow` which accepts 
    ```rust
    desc: DataflowDescription<Self>,
    ```
    instead of `DataflowDescription<OptimizedMirRelationExpr>`. I think this might somewhat the addition of new fields to `lowering::Context` in the future, as we won't have to pass them as extra parameters in `Plan::finalize_dataflow`.
3. Fix the span path where the `EXPLAIN PHYSICAL PLAN` will be located.

**Comment by teskje** [comment]
> Fix the span path where the `EXPLAIN PHYSICAL PLAN` will be located.

Can you elaborate on this part?

**Review by antiguru — APPROVED** [review]
Seems reasonable!

**Comment by aalexandrov** [comment]
> > Fix the span path where the `EXPLAIN PHYSICAL PLAN` will be located.
> 
> Can you elaborate on this part?

Discussed offline, but in order to tie loose ends:

1. Every `ExplainStage` except `Trace` is [associated with a path](https://github.com/MaterializeInc/materialize/blob/4f9eaebc09d0ac4ec27bf110e967f88ddea27fa9/src/sql-parser/src/ast/defs/statement.rs#L3378-L3389) which represents the sequence of spans under which `trace_plan(&plan)` with the corresponding plan is going to be called.
2. If we change the method chain under which we find the result of an `ExplainChange` we should reflect this in the `fn path(&self)` result.
3. However, I was wrong above in that the refactor I suggest is not changing the path of the `OPTIMIZED PLAN` (it will continue to be `optimize/finalize_dataflow` because the plan reported at the end of the `finalize_dataflow` method is still going to represent the "physical plan".

**Comment by teskje** [comment]
TFTRs!

**Pull request merged**
