### PR TITLE
sql-parser: improve clarity of CREATE CONNECTION syntax

### PR DESCRIPTION
**Pull request by benesch**
Add a strategic pair of parenthesis to CREATE CONNECTION to improve clarity, separating the name of the connection type from the options.

Old:

    CREATE CONNECTION ... FOR KAFKA BROKER ..., PROGRESS TOPIC ...;

New:

    CREATE CONNECTION ... TO KAFKA (BROKER ..., PROGRESS TOPIC ...);

This will make it easier to visually distinguish connection types like AWS vs AWS PRIVATELINK SERVICE.

The old syntax is still supported, in keeping with our backwards compatibility guarantee. Documentation is updated, as are all tests that are not explicitly testing the upgrade path from the old syntax. The goal is to make it as hard as possible to find out about the old syntax.

We're early enough that we might yet be able to transition all of our users to the new syntax, and eventually remove the old syntax entirely, even though it is technically a breaking change.

### Motivation

   * This PR refactors syntax as discussed [on Slack](https://materializeinc.slack.com/archives/CU7ELJ6E9/p1665468168425209) and in the [AWS PrivateLink connection design](https://www.notion.so/materialize/CONNECTION-objects-for-Private-Link-7eb2975bac8c48a094f32d1c5b0d6d62?d=04e274061879454eaaec5d5ea3668d84#6de295738cd5415c964add9e0b3a3f13).

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - Introduce a clearer syntax for `CREATE CONNECTION`. The `FROM` keyword is replaced with `TO`, and the option list must be enclosed in parenthesis. The old syntax is still supported for backwards compatibility but its use is discouraged. <include syntax example from above>

### CODE REVIEW

**Review by sploiselle — APPROVED** [review]
@benesch 🙇 ; I'll take this over and shepherd through CI

**Review by morsapaes — APPROVED** [review]
This makes things so much cleaner. Thanks, @benesch! 🙇‍♀️

**Comment by benesch** [comment]
Thanks for the very speedy reviews! I just pushed up a quick fix for a few of the test failures I saw.

**Comment by chaas** [comment]
Wow, thanks @benesch !

**Pull request merged**
