### PR TITLE
Replace some uses of HashMap with BTreeMap

### PR DESCRIPTION
**Pull request by teskje**
This PR replaces some existing uses of `HashMap`s with `BTreeMap`s, in an effort to remove sources of non-determinism from our code.

### Motivation

   * This PR refactors existing code.

Advances #14587.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a
  companion cloud PR to account for those changes that is tagged with
  the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - N/A

### CODE REVIEW

**Review by aalexandrov — APPROVED** [review]
LGTM.

It's not clear to me why the changes in the Orchestrator implementations are required. How are the changed of these structs affecting `ComputeCommand` or `Plan` generation?

**Comment by teskje** [comment]
> It's not clear to me why the changes in the Orchestrator implementations are required.

I more or less arbitrarily picked `HashMap` instances to convert, there is not necessarily a relationship between them. I figured that we need to start somewhere, but there is no obvious best place to start.

(The reason I ended up making the orchestrator change is that I grepped through the compute-client code and one of the first `HashMap` instances I found was the one that passes the `labels` to the orchestrator.)

**Comment by umanwizard** [comment]
LGTM.

**Comment by teskje** [comment]
TFTR!

**Pull request merged**
