### PR TITLE
optbench: move ` src/transform/benches/mzbench_opt` to `misc/python/materialize/optbench`

### PR DESCRIPTION
**Pull request by aalexandrov**
Addressing [change requests](https://github.com/MaterializeInc/materialize/pull/9445#pullrequestreview-825425117) from @benesch which were posted shortly before the auto-merge of #9445.

### Motivation

* This PR refactors existing code [as requested](https://github.com/MaterializeInc/materialize/pull/9445#pullrequestreview-825425117).

### Tips for reviewer

1. 18e7d2f55 Auto-rebuild `ci-builder` Docker image when python dependencies change.
1. af4d7bf48: This PR refactors existing code [as requested](https://github.com/MaterializeInc/materialize/pull/9445#pullrequestreview-825425117).
    1. Moves the Python code from `src/transform/benches/mzbench_opt` to `misc/python/materialize/optbench`.
    1. Moves the `mzbench-opt` CLI from `src/transform/benches/mzbench_opt/cli.py` to `misc/python/materialize/cli/optbench.py`.
    1. Replaces setuptools-based `mzbench-opt` CLI with `bin/optbench` script which initializes the virtualenv and delegates to the above.
1. 757add17d replaces typer (which itself is a thin wrapper around click) with click in `optbench.py`.
2. 0efbbbe9f fixes typing errors reported by `mypy`.

Note that due to (1.3) we no longer have autocomplete support (see the `README.md` diff in b8edf673). Also, the type definition logic after (2) is a bit more repetitive (see the diff 38d789b3 where CLI method types are now replaced by `@click.argument` and `@click.option` decorators).

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

**Comment by aalexandrov** [comment]
It seems that the changes in `requirements-dev.txt` are not immediately reflected in buildkite builds.

I am running `bin/pyactivate --dev -m pip list` as part of the build, but I am not seeing the newly added libraries (`numpy`, `pandas`, ...)

@benesch I would appreciate some pointers.

**Comment by aalexandrov** [comment]
I guess I'll have to re-build the image with `bin/ci-builder` and then re-deploy.

**Comment by aalexandrov** [comment]
I cherry-picked the fix from #9485 in this PR and am now testing to see if this will fix the issue.

**Comment by aalexandrov** [comment]
OK, after some back and forth I think this is ready for review @benesch.

**Review by benesch — APPROVED** [review]
This looks fantastic! Thanks very much!

**Pull request merged**
