### PR TITLE
adapter: eagerly validate max replicas limit for managed clusters

### LINKED ISSUE #20195: Managed cluster with a huge replication factor not rejected immediately, causes 100% CRDB CPU usage
### What version of Materialize are you using?

5a96695985ec0613459321fa24d57c61e9b1f206

### What is the issue?

@jkosh44 This is a follow-up from one of the issues raised in the "Managed Clusters" PR. 

This statement:

```
CREATE CLUSTER foo SIZE '1', replication factor 99999;
```

Should fail immediately with a `ERROR:  creating cluster replica would violate max_replicas_per_cluster limit` error. Instead, it causes a prolonged 100% CRDB usage until it fails eventually with the expected message.

I suspect the `max_replicas_per_cluster` check is misplaced in the code as it should trigger and fail immediately without a delay. Maybe the check is performed for every replica, rather than just once for the entire `CREATE CLUSTER` statement?  

This has the potential to (D)DoS our CRDB instance as any trial user could run the statement in question.

### PR DESCRIPTION
**Pull request by benesch**
Otherwise we'll attempt to allocate replica IDs for as many replicas as the user requested before checking whether that number of replicas is acceptable. This allows users to place unbounded load on CockroachDB.

Fix #20195.

@philip-stoev is there a good way to test this? 

### Motivation

  * This PR fixes a recognized bug.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - n/a

### CODE REVIEW

**Review by philip-stoev — APPROVED** [review]
@benesch I pushed a test, so this is good to go.

**Comment by philip-stoev** [comment]
@benesch note however that this check does not cover the non-managed case, that is, a `CREATE CLUSTER REPLICAS` statement generated by the following script:

```
print("CREATE CLUSTER c1 REPLICAS (")
print(",".join([f"r{i} (SIZE = '1')" for i in range (0,9999)]))
print(")")
```

will still cause a hang. Do you think this is a separate issue for me to file or a single, more universal check can handle both cases within the context of this PR?

**Review by antiguru — APPROVED** [review]
LGTM. Thank you!

**Comment by benesch** [comment]
> Do you think this is a separate issue for me to file or a single, more universal check can handle both cases within the context of this PR?

Ugh, good catch. I pushed up a fix for that case too.

**Review by jkosh44 — APPROVED** [review]
I think this resolves the issue, however there's a couple alternative approaches that I think may have a better outcome:

1. We have the ability to allocate multiple IDs at once:
https://github.com/MaterializeInc/materialize/blob/301e9926a425e4d97767053c08a6451028f0302f/src/adapter/src/catalog/storage.rs#L663-L667
https://github.com/MaterializeInc/materialize/blob/301e9926a425e4d97767053c08a6451028f0302f/src/adapter/src/catalog/storage.rs#L687-L690
Refactoring replica ID allocation to allocate all IDs at once would resolve the issue and make replica ID allocation faster even when it doesn't exceed the resource limit.

2. This would be a bigger refactor, but we could move id allocation into the catalog transaction itself. This would avoid burning through IDs on failed statements and reduce our Cockroach usage to a single transaction per DDL.

**Comment by benesch** [comment]
Yeah, this was a bit of a quick fix. I like the sound of (2) more than (1). (1) would result in us leaking a bunch of replica IDs, which feels a little bad.

**Comment by benesch** [comment]
Ah, hm, but the reason we don't do (2) is because other catalog ops often need to construct two objects where one depends on the other, and how do you do that without allocating IDs up front?

**Comment by benesch** [comment]
> > Ah, hm, but the reason we don't do (2) is because other catalog ops often need to construct two objects where one depends on the other, and how do you do that without allocating IDs up front?
> 
> I was thinking the same thing. There's probably something clever we can do here with transient IDs, which I'm assuming don't get persisted to CRDB but I'm not actually sure. We can use transient IDs to reference dependencies before the catalog transaction and then replace the transient IDs with real IDs during the catalog transaction.

Good idea! I filed https://github.com/MaterializeInc/materialize/issues/20282 to keep track.

**Pull request merged**
