### PR TITLE
test/testdrive: add a smoke test verifying results from unmat sources…

### PR DESCRIPTION
**Pull request by ruchirK**
… don't regress

Touches #10587

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

**Comment by ruchirK** [comment]
My personal threshold for this is -- if this test fails at least 1 in 4 runs on an ec2 instance without the commit that fixes the issue then I think its sufficient as a smoke test

**Review by philip-stoev — APPROVED** [review]
He he, good trick with `$ set-sql-timeout duration=0s` . I was brainstorming on how to provide the same functionality using some dedicated testdrive syntax ...

The only problem I forsee is that when I was running those queries manually, I was also getting sporadic "no complete timestamps yet" errors. But if you do not see any such errors with your .td test, then I think we are good to merge. Thanks!

**Comment by benesch** [comment]
I think this got forgotten! I gave it a rebase, since it's pretty out of date and I wanted to watch for any new regressions. Assuming it's green, I'm gonna give it a merge.

**Comment by ruchirK** [comment]
Sorry - I wasn't sure about merging this earlier because it seemed like we might still get the "timestamp <FOO> not valid for all inputs errors". Did those go away in a recent coord change?

**Comment by benesch** [comment]
No idea! Adding the test seemed like a good way to find out.

**Pull request merged**
