### PR TITLE
Intercept SIGINT/SIGTERM and exit cleanly.

### PR DESCRIPTION
**Pull request by philip-stoev**
This is required in order for code coverage to be captured properly.

### CODE REVIEW

**Comment by petrosagg** [comment]
Are we not handling these signals already? When I control+C my local instance it correctly exits.

Also, `process::exit(0)` doesn't run any destructors so if we have any cleanup logic in those it will be skipped https://doc.rust-lang.org/std/process/fn.exit.html

**Comment by petrosagg** [comment]
I'll make a wild guess that you're running a materialize binary inside a docker container as PID 1. In this case glibc's signal handler does special things as you generally don't want to stop PID 1. The solution is to run `tini` as PID 1, see this PR that solved the same issue for the docker images we run in the cloud product https://github.com/MaterializeInc/materialize/pull/6051

**Comment by philip-stoev** [comment]
I am running this on bare metal. Without this patch, no code coverage can be measured -- I think the information from memory is not flushed to disk. If ```process::exit``` is not the right call, how can I exit gently? Basically I want to generally fall out of ```main``` .

**Comment by petrosagg** [comment]
What behaviour are you seeing without this patch? Does the process ignore the signal or exits in an unclean way?

**Comment by philip-stoev** [comment]
Without this patch, code coverage after running materialize idle for 10 seconds before hitting Ctrl+C is reported as 0.02% or thereabout. With this patch, the coverage reported is 22%, which is much more realistic.

Basically it seems you need to give the instrumentation an opportunity to flush the coverage information to disk. Without this patch, this does not happen.

To answer your specific question, prior to this patch I do not think we were handling Ctrl+C at all, so the default handler was called. At least in C++, the default handler is ```_exit``` which does not flush buffers.

**Comment by benesch** [comment]
Right, so the implementation of the profiler runtime in LLVM can be viewed here:

https://github.com/llvm/llvm-project/blob/812a9061338dad80a3e9725db95f67590bc54dcd/compiler-rt/lib/profile/InstrProfilingFile.c#L1153-L1166

And, indeed, it looks like the function that writes the profile file to disk is registered as an `atexit` handler, which will only be called on "normal program termination", which is either a return from `main` or a call to `exit`. That doesn't happen with `SIGINT` or `SIGTERM` because the default handler for those is to abnormally terminate the process. Just as @philip-stoev describes.

> Also, `process::exit(0)` doesn't run any destructors so if we have any cleanup logic in those it will be skipped

True, but no worse than the current situation. In neither case do `Drop` implementations get called. The difference is only whether `atexit` handlers get called or not.

So, @philip-stoev, I think the idea here is fundamentally sound. I have one quibble with the implementation though. I think it is minorly incorrect for `SIGINT` and `SIGTERM` to result in a clean shutdown. I would rather `materialized` still exit with an unclean status code indicating the signal received. The GNU libc docs describe the approach here: https://www.gnu.org/software/libc/manual/html_node/Termination-in-Handler.html

It'll be a bit tricky, because we'll need to call `__llvm_profile_write_file` manually from the SIGINT/SIGTERM handler, but only if the profiler runtime is linked in. That last bit is the hard part. I'm happy to take a stab at that.

**Comment by benesch** [comment]
Ok, I pushed a commit that modifies things as proposed above, @philip-stoev! Could you verify that coverage still works for you? I tested to the best of my ability but I don't have the whole suite of coverage tools wired up.

**Comment by philip-stoev** [comment]
@benesch yes thanks, code coverage is now properly dumped on termination.

**Comment by benesch** [comment]
🎉 thanks very much for tracking this down!

**Pull request merged**
