### PR TITLE
upgrade: port the upgrade test to Python

### PR DESCRIPTION
**Pull request by philip-stoev**
### Motivation

   * This PR refactors existing code.

The existing YAML upgrade tests were truly a pain to work with. Refactor the entire thing in Python

### Description

- move the existing CSV-related upgrade tests to run only from version 0.9.2 and higher, due to
  an 'internal error' being thrown at CREATE SOURCE time with previous versions
- add a "csv-basic" test to cover versions prior to 0.9.2
- make 0.8.0 the oldest version being tested as testdrive's catalog checking functionality
  does not seem to work with prior versions
- add a pull workflow Step that runs 'docker pull'. This is to ensure that
  materialize/materialized:latest is indeed the latest released version
- remove the machinery from mkrelease.py that was editing the upgrade YAML file in-place
- update README.md to reflect the new reality

### Checklist

- [x] This PR has adequate test coverage.
- [ ] This PR adds a release note for any user-facing behavior changes.

### CODE REVIEW

**Comment by philip-stoev** [comment]
I was thining of adding a linter that confirms that all the .td files in the directory are named properly and accounted for, but this will go in a new PR, as this one is already quite long.

**Comment by philip-stoev** [comment]
After discusssion with @benesch , the ability to test against "materialize:latest" has been removed along with the associated code.

**Review by benesch — APPROVED** [review]
🎉🎉🎉

**Comment by quodlibetor** [comment]
> the ability to test against "materialize:latest" has been removed along with the associated code.

Is the rationale here because we will always test against the latest release because we are now testing _every_ released version?

**Comment by philip-stoev** [comment]
> Is the rationale here because we will always test against the latest release because we are now testing every released version?

Yes, now that we are explicitly consulting the list of actual git tags rather than having it embeded in the .yaml file means that we should be implictly testing the "latest" release as well, even if we do not reference it as "materialized:latest", but rather as its "v" tag.

**Pull request merged**
