### PR TITLE
test: fix and enable stash tests to restart

### PR DESCRIPTION
**Pull request by mjibson**
The stash directory was not actually being tested. Move these to restart
which are.

Fix the broken cli argument name.

### Motivation

  * This PR fixes a previously unreported bug.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-protobuf` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - n/a

### CODE REVIEW

**Review by philip-stoev — APPROVED** [review]
Thank you.

**Comment by mjibson** [comment]
I've been debugging this locally for a few hours and am *really* confused. The test is failing complaining about the `CREATE DEFAULT INDEX` in `workflow_audit_log`, and indeed that syntax doesn't work in postgres. So I added a `print(c.sql_query("select version()"))` right before the `CREATE DEFAULT INDEX` which prints

`(['PostgreSQL 14.4 (Ubuntu 14.4-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0, 64-bit'],)`

So ok it's actually connecting to a postgres server? But which one, the new one from the `Postgres(image="postgres:14.4")` (even though that's specified as an override so shouldn't even matter, or the postgres in the materialized image? If I change the `image` version in this file to 14.3, I still see 14.4 printed, which means it's postgres from the mz image.

I have no clue why this is happening. I've added a bunch of prints to `invoke()`, `sql_cursor()`, `default_ports()`, `port()` and they all seem maybe ok? Might be misreading one but...something is amiss and I'm not sure what.

**Comment by philip-stoev** [comment]
Let me clone your branch and run locally ...

**Comment by philip-stoev** [comment]
The panic in CI is ```
restart-materialized-1  | thread 'tokio:work-12' panicked at 'cannot append updates: InvalidBounds { lower: Antichain { elements: [1659588103363] }, upper: Antichain { elements: [1] } }', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-01d8d995b711b0876-1/materialize/tests/src/storage/src/controller.rs:1483:42
```

**Comment by philip-stoev** [comment]
Ok so:

1. I am unable to reproduce the `CREATE DEFAULT INDEX` thing you have experienced. My only explanation is that the ports in mzcompose got messed up somehow and the `default_port()` function returned the port of the Postgres container even though it is given a `materialize` argument. I do not see a code path that could cause that to happen. Maybe `mzcompose down -v` will clear this up?

2. With respect to the panic in CI, what is happening is that the `c.override()` , while replacing the Mz container with the one using your desired command-line option, does not cause the `mzdata` directory to be cleaned up. So your Mz instance starts with a populated mzdata directory and a fresh stash , which I think is what is causing the panic. The following patch fixed it for me:
```
 def workflow_stash(c: Composition) -> None:
+    c.kill("testdrive", "materialized")
+    c.rm(
+            "testdrive",
+            "materialized",
+            stop=True, destroy_volumes=True,
+        )
+    c.rm_volumes("mzdata", "pgdata", force=True)
+
     materialized = Materialized(
         options=["--adapter-stash-url", "postgres://postgres:postgres@postgres"],
     )
```
At least one of those steps may be redundant, but better safe than sorry. `testdrive` also needs to cleaned up because it also holds a reference to the `mzdata` volume which in turn prevents proper complete removal.

I hope this helps. Let me know if there is anything else I can do.

**Comment by mjibson** [comment]
Thanks for the help!

**Pull request merged**
