### PR TITLE
Fix various slt failures

### PR DESCRIPTION
**Pull request by jamii**

### CODE REVIEW

**Comment by benesch** [comment]
Looks great so far!

**Comment by benesch** [comment]
Kicked off a full run here: https://buildkite.com/materialize/sql-logic-tests/builds/4224

**Comment by jamii** [comment]
@benesch Do you know what happened to the [previous run](https://buildkite.com/materialize/sql-logic-tests/builds/4223)? It looked like it was doing fine and then it died overnight with no error message.

**Comment by benesch** [comment]
Oh, weird I didn't see that. I think that just... successfully completed though?

**Comment by benesch** [comment]
Successful in that the runner ran to completion. But you changed the script to make it a hard error if non-Cockroach SLT failed, so that's why the output looks the way it does.

**Comment by jamii** [comment]
Oh, I didn't notice the sqlite failure. Guess I'll look at that next.

**Comment by benesch** [comment]
We agree with Postgres on the several queries I've spot checked that they should be returning division by zero errors, so I think there's nothing to be done but rewriting the expected results.

**Comment by jamii** [comment]
I checked them all. Most I edited to match postgres. A few were weird - https://github.com/MaterializeInc/materialize/issues/2418. 

We also had a bunch of new precision errors, which is weird because those tests should have been failing before. I think I fixed a bug when I was messing with the parser that would skip the entire file on hitting `skipif postgresql` instead of just the next record.

**Comment by jamii** [comment]
Doesn't seem like we have a consensus yet on https://github.com/MaterializeInc/materialize/issues/2418 so I'm going to merge the rest as is and we'll still have a couple of failures.

**Pull request merged**
