### PR TITLE
Revert "persist: wrap all pg consensus ops in txns (#12534)"

### LINKED ISSUE #12487: persist: upper bound too high for truncate
Now that we've switched to postgres for persist's consensus impl in CI/dev, we're seeing a ton of `upper bound too high for truncate` errors in CI runs of #12216. I added a bit of debugging info to the error message and saw that the head it's getting is less than the `seqno` given to truncate.

```
indeterminate: upper bound too high for truncate: Some(SeqNo(28)) vs SeqNo(29)
```

I read the only non-test callsite of `truncate` pretty closely, and it seems(?) fairly obviously correct to my eyes. A compare_and_set is done from `expected` to `new` and on success, truncate is immediately called with `new.seqno`.

https://github.com/MaterializeInc/materialize/blob/main/src/persist-client/src/impl/machine.rs#L248-L263

My current leading theory is that the `head` that we're getting back from postgres is somehow not serializable with the compare_and_set query that just finished. We do request serializable when initializing PostgresConsensus, but perhaps somehow it's not applying here. A shot in the dark: maybe it doesn't apply to read-only txns?

https://github.com/MaterializeInc/materialize/blob/c7e70fb59cddeae461123ebba8032d51d5abd467/src/persist/src/postgres.rs#L28

Something to dig into here for sure.

### PR DESCRIPTION
**Pull request by benesch**
This reverts commit 60cf8fdebf4088f1e18571e66978d41b8abbdb9b.

The bug this worked around was actually a bug in tokio-postgres for which
we'd forgotten to pick up the fix (#8738). Now that we've picked up the fix, we can
go back to the original implementation, which we believe will be a bit
faster in production because it does not involve network roundtrips.

Fixes #12487.

### Motivation

  * This PR removes a bugfix now that that bug has been fixed a different way.

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - n/a

### CODE REVIEW

**Comment by benesch** [comment]
> LGTM, thanks for figuring this out! Please toss a Fixes 12487 in here.

Done.

> Would you mind typing up an explanation here of how #8738 was biting us in the old impl but not the new? I can't say I know enough of the pgwire protocol to connect the dots on the specifics.

It's really funny. It was biting us on the opposite end. It was queries against _Materialize_ that were returning an error that tokio-postgres was then dropping on the floor, rather than queries that Materialize was making against PostgreSQL.

The core problem is that there are two ways for an `INSERT` to return an error. Here are the flows at the protocol layer:

```
SEND Query("INSERT ...")
RECV ErrorResponse("Your INSERT is bad")
```

```
SEND Query("INSERT ...")
RECV CommandComplete("INSERT 0 1")
RECV ErrorResponse("Oh te noes txn commit failure!")
```

The problem was that tokio-postgres was dropping the error response in the second flow on the floor, and claiming that the query succeeded. And, well, the query _had_ succeeded... it's just that the implicit commit that happens after every query not in a transaction had not.

Philip had observed this with the old version of persist because his testdrive scripts were causing errors to be reported at commit time rather than query time, and tokio-postgres was dropping those errors on the floor.

> I have a mild preference for holding this until after 12216 merges, in the interest of not unnecessarily messing with anything that we know is working right now.

👍🏽

**Comment by danhhz** [comment]
and why did adding explicit txns around all the stuff in PostgresConsensus work around the bug?

**Comment by benesch** [comment]
It changes the protocol flow. Postgres holds back the ErrorResponse until you issue a COMMIT query, at which point tokio-postgres sees flow one:

```
SEND Query(“INSERT …”)
RECV CommandComplete(“INSERT 0 1”)
SEND Query(“COMMIT”)
RECV ErrorResponse(“serialization failure”)
```

**Comment by danhhz** [comment]
aha! tyty

**Review by ruchirK — APPROVED** [review]
LGTM! I already told you this in person but thanks for figuring this one out Nikhil it was driving me crazy!!

**Pull request merged**
