### PR TITLE
Less verbosity when adding vars

### PR DESCRIPTION
**Pull request by bkirwi**
Adding a new var to `SystemVars` involves adding a new branch to a number of different if-else chains... a bit tedious but also fairly error prone, since it's easy to miss one and the compiler can't check it.

This PR changes `SystemVars` to store a single collection of vars instead of many fields. This increases the cost of accessing a single var somewhat, but reduces code size rather dramatically.

I also did a small amount of cleanup on the trait bounds, since I was fussing with them for this change anyways; some of them were redundant, and others were not strictly necessary.

### Motivation

Refactoring! As storage has started making more use of feature flags / the vars system, we've hit some of the pain points that this change is meant to help resolve.

### Tips for reviewer

Storing the system vars as `Box<dyn ...>` required a new object-safe trait with a couple forwarding methods to keep things object-safe. I wasn't able to simplify that trait further, but happy for suggestions if you have them.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by bkirwi** [comment]
cc maybe @mjibson, who I know looked at a recent storage PR to add a system var. I took a quick stab at this for skunkworks last week... does this look viable enough that it's worth tidying up into a proper PR?

**Review by mjibson — APPROVED** [review]
LGTM, but maybe have @benesch give it a thumbs up on the approach first in case I'm missing some context about why this doesn't work.

I'm very in favor of moving all these to a Map and we should not care about a perf hit there. I'm unaware of a reason they can't be like that, although there certainly may be one.

**Comment by benesch** [comment]
No concerns. I think this structure just evolved organically. Am also pro moving to a map. The only things to be careful about with the map are 1) preserving the accessor methods that return the native Rust type of the variable (`&dyn Var` only lets you get the variable’s value as a string) and 2) preserving case insensitive var name lookup.

**Comment by bkirwi** [comment]
Great, thanks for the feedback! Will follow up with a map sometime this week.

**Comment by bkirwi** [comment]
Updated with the `BTreeMap` idea! A little wrestling with the `VarMut` trait but overall happy with how the structure works out, and I think I've addressed the mentioned concerns.

The (often indirect) test coverage for this code seems pretty good, but happy to add more tests if something specific needs it.

**Review by benesch — APPROVED** [review]
This looks great! Thanks so much for cleaning this up.

**Comment by bkirwi** [comment]
Thanks all for the reviews!

**Comment by jkosh44** [comment]
Thanks, I'll play around with it this week. I think the custom setter logic will be the most challenging part, but hopefully it can just go right before we call set on the value in the map.

**Pull request merged**
