### PR TITLE
testdrive: use a useful Postgres default image

### PR DESCRIPTION
**Pull request by mjibson**
mzcompose's default Postgres image uses postgres 10 due to some mzbuild stuff that seems unused now. Remove the mzbuild stuff for Postgres and just make it always use a recent version.

### Motivation

  * This PR fixes a previously unreported bug.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-protobuf` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - n/a

### CODE REVIEW

**Comment by mjibson** [comment]
`SET WITH OIDS` has apparently gone away, and I'm not sure what it was trying to do or how I should fix it:

> As oid system columns cannot be added anymore, this never has an effect.

https://www.postgresql.org/docs/14/sql-altertable.html

**Comment by mjibson** [comment]
Hard coding an older postgres for pg-cdc which seems to have needed it until someone else can look at the specifics.

**Comment by mjibson** [comment]
That fixed a few errors. Not sure about the conflict_schema stuff. Might look more later.

**Review by philip-stoev — APPROVED** [review]

**Comment by philip-stoev** [comment]
If we are no longer using mzbuild with Postgres we should also remove `misc/images/psql` to avoid any confusion.

**Pull request closed without merging**
