### PR TITLE
[persist] Minor structured-data fixes and improvements

### PR DESCRIPTION
**Pull request by bkirwi**
Bundling together some small fixups - see the individual commits & code comments for motivation.

### Motivation

A few minor things as part of the rollout of: https://github.com/MaterializeInc/database-issues/issues/7411

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

**Review by danhhz — APPROVED** [review]
I'm not sure I have the context to have an opinion on the "Remove incorrect assertions from test" commit. In particular, we definitely haven't ever guaranteed this order, but it's not obvious to me that it's "Better to delete those assertions than convert them over."

The other three commits LGTM!

**Comment by bkirwi** [comment]
To unpack a bit: I was comfortable deleting those assertions because they overspecify the behaviour (ie. a correct impl can fail them) and because coverage remains good (so I'd expect multiplicity bugs to still fail this suite and many others). But if anyone feels strongly I can revisit!

**Comment by danhhz** [comment]
> coverage remains good (so I'd expect multiplicity bugs to still fail this suite and many others)

Yeah, this is the part that I'm not sure of my ability to validate (at least without a lot of legwork). But if you're confidant that this doesn't meaningfully reduce coverage of multiplicity, I say go ahead and merge

**Comment by bkirwi** [comment]
Fairly sure, but I've tagged our resident adapter expert in case he has an opinion! Will shoot to get this in for the release in any case.

**Review by ParkMyCar — COMMENTED** [review]
You're totally right, we've never guaranteed an order and according to the Postgres spec we don't need to. I would prefer to keep the tests and update them to include an `ORDER BY` because they exercise how `LIMIT` and `OFFSET` work

**Comment by bkirwi** [comment]
Cool! That file still has cases that exercise the same functionality with an `ORDER BY` applied, so I think we're good to go.

**Comment by ParkMyCar** [comment]
> Cool! That file still has cases that exercise the same functionality with an `ORDER BY` applied, so I think we're good to go.

Ah perfect!

**Pull request merged**
