### PR TITLE
storage: put server components behind cargo feature

### PR DESCRIPTION
**Pull request by petrosagg**
### Motivation

The intent is to reduce compile times for users of storage that only want to use its client facilities by putting all the server components behind a feature flag.

An additional crate is introduced that enables the optional feature in order to build the binary.

This is an alternative approach to #11962 that avoid triggering orphan rules and allows `mz-storage` to have types with private members.

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### CODE REVIEW

**Review by benesch — APPROVED** [review]
So the tradeoff here is we take on a bit more conditional compilation complexity in exchange for not fighting the orphan rule? Seems like exactly the kind of decision that the STORAGE team gets to own!

Btw, @petrosagg, have you seen that Niko is thinking about ways to weaken the orphan rule? http://smallcultfollowing.com/babysteps//blog/2022/04/17/coherence-and-crate-level-where-clauses/

**Review by antiguru — APPROVED** [review]
Thanks!

**Comment by petrosagg** [comment]
@benesch it's for the orphan rule and also private fields on structs. I've seen it but haven't read it in too much detail. Is he proposing something that would make the `crate`/`crate-types` pattern compatible with the orphan rule?

**Comment by benesch** [comment]
> @benesch it's for the orphan rule and also private fields on structs. I've seen it but haven't read it in too much detail. Is he proposing something that would make the `crate`/`crate-types` pattern compatible with the orphan rule?

Yes!

> The next part of the idea would be to allow crates to implement foreign traits for foreign impls. I think I would convert the orphan check into a “deny by default” lint. The lint text would explain that these impls are not permitted because they may cause linker errors, but a crate could mark the impl with #[allow(orphan_impls]) to ignore that warning. Best practice would be to put orphan impls into their own crate that others can use.

**Pull request merged**
