### PR TITLE
persist: small cleanups

### PR DESCRIPTION
**Pull request by danhhz**
See individual commits for details.

### Motivation

   * This PR refactors existing code.

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - N/A

### CODE REVIEW

**Review by ruchirK — APPROVED** [review]
LGTM!

**Comment by danhhz** [comment]
TFTR! snuck in one last commit that I just thought of if you want to take a quick look at it

**Comment by ruchirK** [comment]
I like that one too!

**Comment by danhhz** [comment]
\o/ tyty merging on green!

**Pull request merged**
