### PR TITLE
sql: implement ALTER RETAIN HISTORY

### PR DESCRIPTION
**Pull request by mjibson**
Add a new plan variant for alter retain history that the various statement types can use commonly. This does mean that RETAIN HISTORY cannot be used with any other option, but as most things don't have other options this is not a practical problem. We can remove this later if needed.

### Motivation

  * This PR adds a known-desirable feature.

### Tips for reviewer

    * Although this will be squashed, viewing each commit may ease the review work.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - n/a

### CODE REVIEW

**Comment by mjibson** [comment]
After I get CI tests to pass I will have QA do a pass. The SLT tests here verify that the catalog changes occur, but don't verify that the read holds have been adjusted.

**Review by ParkMyCar — APPROVED** [review]
Nice!

**Comment by nrainer-materialize** [comment]
> After I get CI tests to pass I will have QA do a pass. The SLT tests here verify that the catalog changes occur, but don't verify that the read holds have been adjusted.

I added a test with c66114aea2e0ce86d56369e8791055b57a4e889d. Let me know what you think.

**Comment by nrainer-materialize** [comment]
> > After I get CI tests to pass I will have QA do a pass. The SLT tests here verify that the catalog changes occur, but don't verify that the read holds have been adjusted.
> 
> I added a test with [c66114a](https://github.com/MaterializeInc/materialize/commit/c66114aea2e0ce86d56369e8791055b57a4e889d). Let me know what you think.

@mjibson: Did this get lost due to a force push?

**Comment by mjibson** [comment]
Oops, yes, will restore. I forgot to pull first.

**Comment by mjibson** [comment]
Fixes to make 0 mean disable and reset mean default added. Testdrive consistency checker found those, phew! And for the archives, a discussion about 0 meaning disabled instead of 0: https://materializeinc.slack.com/archives/C02PPB50ZHS/p1706724617968509

**Review by ParkMyCar — APPROVED** [review]
Nice! Good catch with setting to 0

**Pull request merged**
