### PR TITLE
dbt-materialize: add macro for `CREATE VIEWS` step in the Postgres source

### LINKED ISSUE #12781: dbt-materialize: natively support `CREATE VIEWS` step for the Postgres source
### Feature request

As is, we don't natively support [the step](https://materialize.com/docs/sql/create-source/postgres/#creating-replication-views) of breaking down a Postgres source into replication views in the `dbt-materialize` adapter. There is also no guidance in the documentation on how to handle this.

My first hunch is that, from a user perspective, this step could look like:

```sql
{{
  config({
    "materialized":"source",
    "post-hook": [
      "{{ materialize.create_views(...
                                  ...) }}"
    ]
  })
}}

CREATE SOURCE mz_source
FROM POSTGRES
  CONNECTION 'host=example.com port=5432 user=host dbname=postgres sslmode=require'
  PUBLICATION 'mz_source';
```

, where view creation is handled through a `post-hook` using a `create_views` macro that is smart enough to configure whatever replication views are created downstream as dbt models that can then be `ref()`ed as normal. Thoughts, @ahelium?

### PR DESCRIPTION
**Pull request by morsapaes**
🚧 **WIP**

Fixes #12781.

Right now, this adds a pretty basic macro to natively support the `CREATE VIEWS` step using a `post-hook` on Postgres source models.

@benesch, I fiddled around with `mz_compose.py` to use the Postgres service, but can't tell if it's sleep creeping in or if it's actually kind of hard to add a test for this. Is there a way to reuse some existing step from the test suite to boot Postgres for logical replication?

<hr>

## Open questions

@ahelium, you'll probably have some better ideas here.

### Referencing multiplexed views

The problem with `CREATE VIEWS` is that it creates multiple views in Materialize, but there is no easy way to pull these into the dbt context. The current workflow is to manually create a bunch of `.yml` and `.sql` files manually to piece things together (see the example in [`gouda-vibes-dbt`](https://github.com/MaterializeInc/materialize-training/tree/main/exercises/gouda-vibes-dbt)).

Some approaches I was hopeful about, but that don't seem doable:

* https://github.com/dbt-labs/dbt-core/discussions/5100
* https://github.com/dbt-labs/dbt-core/discussions/5101
* https://github.com/dbt-labs/dbt-core/issues/2716
* It isn't possible to hack the DAG using the [graph](https://docs.getdbt.com/reference/dbt-jinja-functions/graph) context variable, either.

### Automatic schema creation
One annoyance that could be worked around with dbt is automatically creating schemas that don't exist in Materialize (unless explicitly renamed, Materialize will attempt to create the views in the same schema as upstream, and fail if the schema doesn't exist). I'm not sure this is desired behavior, though; it's just kind of annoying when replicating from schemas other than `target_schema`. ~AFAIK there also isn't a way to know which schemas are contained in the publication upfront (in a way that is tractable to dbt)~ -> this should be possible after #10121.

### CODE REVIEW

**Comment by benesch** [comment]
>  if it's actually kind of hard to add a test for this

Probably this! Our existing tests for PostgreSQL CDC are in test/pg-cdc. I'd start by checking out test/pg-cdc/mzcompose.py and test/pg-cdc/pg-cdc.td.

**Comment by morsapaes** [comment]
Wanted to push the test changes in, even though the workflow is not working yet. There's something strange going on that prevents the post-hook from correctly referencing the relation. I'd expect `{{ this }}` to work (and it does work in a normal dbt project, outside of testing), but hit:

```nofmt
12:41:54.614510 [info ] [MainThread]: Completed with 1 error and 0 warnings:
12:41:54.614598 [info ] [MainThread]:
12:41:54.614665 [error] [MainThread]: Database Error in model test_source_views (models/test_source_views.sql)
12:41:54.614765 [error] [MainThread]:   unknown catalog item 'materialize.dbt_test_220721123819617852630854.test_source_views'
12:41:54.614856 [info ] [MainThread]:
```

I also tried creating the Postgres source on its own, and that brings up a different set of compilation problems that I still need to grok. Out of ideas for now, but will come back to it tomorrow.

<hr>

Ah! Also replacing the Kafka services with Redpanda, so things runs a little faster.

**Comment by benesch** [comment]
Welp, maybe we don't need this if we do #14016? Or, rather, we need something different? Somehow we'll need to tell dbt that there are a whole bunch of magically created materialized views from a single PostgreSQL source.

**Comment by morsapaes** [comment]
Exactly; same problem, but different.

**Comment by morsapaes** [comment]
@teej mentioned that he's stuck in a similar situation for the Snowflake adapter, so I'll pull him in for a chat to try and come up with something that works for both adapters.

**Comment by morsapaes** [comment]
Closing after #14016 landed, and `CREATE VIEWS` is no longer supported syntax. We'll still need to figure out how to pull subsources into the dbt context.

**Pull request closed without merging**
