### PR TITLE
Add a simple Python compilation check to the lints

### PR DESCRIPTION
**Pull request by quodlibetor**
With Python syntax errors mypy is capable of giving very bad error messages, I suppose
specifically with things in f-strings.

With this change, error messages may get duplicated, but they also may provide actual
information. Specifically, this makes the error from the mzconduct intro go from:

    misc/python/bin/mzconduct.py:1: error: invalid syntax
        # Copyright Materialize, Inc. All rights reserved.
               ^
    Found 1 error in 1 file (checked 22 source files)

To:

    misc/python/bin/mzconduct.py:1: error: invalid syntax
        # Copyright Materialize, Inc. All rights reserved.
               ^
    Found 1 error in 1 file (checked 22 source files)
    *** Error compiling 'misc/python/bin/mzconduct.py'...
      File "<fstring>", line 1
        (error=)
              ^
    SyntaxError: invalid syntax

It's not perfect, but it's not completely incorrect anymore, and it at least includes
something you can search for.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/3024)

### CODE REVIEW

**Comment by quodlibetor** [comment]
@benesch I also considered only running this check if mypy failed, but this seemed slightly more robust, but also verbose.

**Comment by benesch** [comment]
Haven't thought very hard, but is it crazy to think we should just do this
as the first step in bin/mypy?

**Comment by quodlibetor** [comment]
> Haven't thought very hard, but is it crazy to think we should just do this as the first step in bin/mypy?

I considered that! the only thing that pushed me away from it is that then it's not really a `mypy` check. I think the user experience of that is better in the bad cases though so I'll try it and we can revert if it fails.

(I also think it should be the second step in `bin/mypy`, just aesthetically, mypy gives a good "I've finished" message, and python's `compileall` does not.)

**Comment by benesch** [comment]
👍 sgtm! We could rename that script too, to `pycheck`. It's intended to be the equivalent of `cargo check`, and this certainly is in line with that goal.

**Comment by quodlibetor** [comment]
image

**Pull request merged**
