### PR TITLE
coord,sql: remove mz_workers

### PR DESCRIPTION
**Pull request by benesch**
mz_workers doesn't make sense in a world where the coordinator can
manage multiple dataflow clusters of different sizes.

### Motivation

  * This PR fixes a previously unreported bug.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR adds a release note for any
  [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

**Review by mjibson — APPROVED** [review]
LGTM.

This does make that specific piece of info not discoverable from SQL, which is the opposite direction we've been going. But I'll guess that we will add more worker introspection in the future and this will come back.

**Review by frankmcsherry — APPROVED** [review]
Looks good to me.

**Comment by mjibson** [comment]
Folks could run something like `select count(*) from (select distinct worker from mz_worker_materialization_frontiers);` to get this though, so I think I was wrong above, and users can still get this info.

**Review by andrioni — APPROVED** [review]
LGTM from a telemetry point of view.

**Pull request merged**
