### PR TITLE
ci: enable "enable_try_parse_monotonic_iso8601_timestamp" for tests

### PR DESCRIPTION
**Pull request by nrainer-materialize**

### CODE REVIEW

**Review by def- — APPROVED** [review]

**Comment by nrainer-materialize** [comment]
@danhhz: After enabling this flag, a sqllogictest is failing. It does not really seem related at first glance, but the failure is reproducible; I triggered two retries on an earlier version before rebasing on main.
Any idea how this could be related to your changes?

```
==> test/sqllogictest/cockroach/aggregate.slt
    SELECT count(*), count(k), count(kv.v) FROM kv
    Warning:test/sqllogictest/cockroach/aggregate.slt:513 InconsistentViewOutcome:test/sqllogictest/cockroach/aggregate.slt:513
            expected from query: Success
            actually from indexed view: PlanFailure { error: db error: ERROR: column "count" specified more than once
    
    Caused by:
        ERROR: column "count" specified more than once
    
    Stack backtrace:
       0: <mz_sqllogictest::runner::RunnerInner>::execute_view_inner::{closure#0}
       1: <mz_sqllogictest::runner::RunnerInner>::execute_view::{closure#0}
       2: <mz_sqllogictest::runner::RunnerInner>::run_record::{closure#0}
       3: <mz_sqllogictest::runner::Runner>::run_record::{closure#0}
       4: sqllogictest::main::{closure#0}
       5: <tokio::runtime::park::CachedParkThread>::block_on::<sqllogictest::main::{closure#0}>
       6: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<sqllogictest::main::{closure#0}>
       7: <tokio::runtime::runtime::Runtime>::block_on::<sqllogictest::main::{closure#0}>
       8: sqllogictest::main
       9: std::sys_common::backtrace::__rust_begin_short_backtrace::<fn() -> std::process::ExitCode, std::process::ExitCode>
      10: std::rt::lang_start::<std::process::ExitCode>::{closure#0}
      11: std::rt::lang_start_internal
      12: main
      13: <unknown>
      14: __libc_start_main
      15: _start, location: Location { file: "test/sqllogictest/cockroach/aggregate.slt", line: 513 } }
```

Could you have a look, please?

**Comment by danhhz** [comment]
I took a look but I also can't imagine how that would be related to my change

**Comment by danhhz** [comment]
i'll see if i can repro locally

**Comment by danhhz** [comment]
hmm I checked out your branch and the failure does not seem to repro locally

**Comment by danhhz** [comment]
aha! the `test/sqllogictest/cockroach/aggregate.slt` is a Warning and a red herring. the real failure is that this assertion fails with the param on by default https://github.com/MaterializeInc/materialize/blob/main/test/sqllogictest/try_parse_monotonic_iso8601_timestamp.slt#L12-L19. we could either remove that assertion or manually set the value to false at the top of the file, either is fine by me

**Review by philip-stoev — APPROVED** [review]

**Comment by nrainer-materialize** [comment]
> aha! the `test/sqllogictest/cockroach/aggregate.slt` is a Warning and a red herring. the real failure is that this assertion fails with the param on by default https://github.com/MaterializeInc/materialize/blob/main/test/sqllogictest/try_parse_monotonic_iso8601_timestamp.slt#L12-L19. we could either remove that assertion or manually set the value to false at the top of the file, either is fine by me

Oh, yes, you are right! Thanks, I will take care of that.

**Pull request merged**
