### PR TITLE
storage/copy-to-s3: Require format option

### PR DESCRIPTION
**Pull request by rjobanp**
### Motivation

  * This PR fixes a recognized bug. Fixes https://github.com/MaterializeInc/materialize/issues/27101

### Tips for reviewer

This leaves the default as TEXT for all other COPY statements, but requires the FORMAT option is provided for the copy-to-expr statement.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by maddyblue — COMMENTED** [review]
Hmm not sure how I feel about this from a SQL perspective because it differs from the postgres default. Maybe instead of defaulting to CSV for that variant, require that it be set to something (i.e., no default)? SQL council should weigh in.

**Comment by morsapaes** [comment]
+1 making it a required option when the `AWS CONNECTION` option is specified.

**Comment by benesch** [comment]
> +1 making it a required option when the `AWS CONNECTION` option is specified.

+1 from me too.

**Comment by rjobanp** [comment]
Updated to make required instead of defaulted for `COPY TO <expr>`

**Comment by rjobanp** [comment]
@maddyblue mind a quick re-review?

**Review by maddyblue — APPROVED** [review]

**Pull request merged**
