### PR TITLE
Extract arrangement frontier state

### PR DESCRIPTION
**Pull request by frankmcsherry**
This PR extracts from the coordinator logic related to managing the frontier state of arrangements. These methods were previously member methods of the coordinator, rather than restricted to the index they act on. This is part of a progressive thinning out of tasks from the coordinator and in to comprehensible modules.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/2826)

### CODE REVIEW

**Comment by frankmcsherry** [comment]
@wangandi If you don't mind could you take a peek at the `get_imports` and `get_imports_inner` replacements. The two methods seemed to be separable into methods that didn't get signaled by an optional argument. I also changed the logic of the `_inner` replacement to avoid exponential blow-up in the case of a trellis-like dag.

**Comment by frankmcsherry** [comment]
There is some additional cruft in here related to `as_of` refactoring that led me to this. I can either back that out or we can agree that it is harmless. Let me review what I did there.

**Comment by wangandi** [comment]
The new `get_imports` replacements LGTM.

**Comment by frankmcsherry** [comment]
@wangandi I'm wrong about the comment, actually. It is used in a different crate!

@justinj I think we should keep it away from the coordinator, as this is fast changing soft state that doesn't reflect non-deterministic choices made by the users or the system.

I'll try and change the name around a bit.

**Comment by frankmcsherry** [comment]
> sorry if this is a dumb q but why are we inserting (min, n_workers) here? my understanding from the MutableAntichain docs is that now we will have (min) stored in the antichain w/ a count of n_workers -- is the right intuition that we are storing a separate upper frontier per worker?

Each worker is going to report its frontier progress independently, and the coordinator is tracking their lower bound. To do that, we start out with the sum of all of the lower bounds of workers, and expect that each will communicate with us.

> this is a super minor thing but the "upper bound of since frontiers" here is the least upper bound of since frontiers right?

Yes

**Comment by frankmcsherry** [comment]
Thanks for the reviews folks. Happy to follow on with any additional clarity (the code being factored puts it in a more explainable state, where we can now impose some requirements).

**Pull request merged**
