### PR TITLE
Simple unit test for table persistence

### PR DESCRIPTION
**Pull request by ruchirK**
Bringing this test back now that we have table persistence again.

TODO: I dunno what else might have changed between when this test was merged and now - sanity check that.

### CODE REVIEW

**Comment by ruchirK** [comment]
I'm running into the following error:

```
altaria-2:persistent-tables Test$ ./mzcompose run persistent-tables
==> Collecting mzbuild dependencies
materialize/materialized:mzbuild-5LJWHYP7U5Y63XXMLXRPZUDABXISNBCA
materialize/testdrive:mzbuild-SDNE4NGJYD2HIBWQOKB73ULE56I7KORF
==> Already built materialize/materialized:mzbuild-5LJWHYP7U5Y63XXMLXRPZUDABXISNBCA
==> Already built materialize/testdrive:mzbuild-SDNE4NGJYD2HIBWQOKB73ULE56I7KORF
Docker Compose is now in the Docker CLI, try `docker compose up`

Starting persistent-tables_materialized_1 ... done
Failed! Unable to unambiguously determine port for materialized, found ports:
altaria-2:persistent-tables Test$
```

that I don't currently know how to debug without adding printfs to the mzcompose python code. has anyone run into this before?

**Comment by danhhz** [comment]
Seems good to me but I don't have much context on the various test frameworks available for this. I suggest you ask @philip-stoev to be the reviewer.

Any ideas on why we're getting a duplicate row in the test failure? Is that a real bug?

```
after-restart.td:14:1: error: non-matching rows: expected:
--
  | [["2011-11-11 11:11:11", "\\x124"], ["<null>", "<null>"]]
  | got:
  | [["2011-11-11 11:11:11", "\\x124"], ["2011-11-11 11:11:11", "\\x124"], ["<null>", "<null>"]]
  | Diff:
  | extra row: ["2011-11-11 11:11:11", "\\x124"]
```

**Comment by ruchirK** [comment]
> Any ideas on why we're getting a duplicate row in the test failure? Is that a real bug?

Nope, I can't get this to reproduce on my laptop when not running on Docker. Tried running with multiple workers and `--persistent-system-tables` on as well I still see the expected results.

This does reproduce on Docker however.

**Comment by ruchirK** [comment]
Marking this as draft for now and am going to figure out this duplicate row issue after we figure out batching up the writes and all of that. Right now debugging is frustrating and slow because `select`s take almost a minute to respond

**Comment by philip-stoev** [comment]
I am abandoning this PR in favor of a new one -- I will write the test in the new, yaml-free style and will add more content.

**Pull request closed without merging**
