### PR TITLE
Fix warnings generated by clippy for Rust 1.59

### PR DESCRIPTION
**Pull request by antiguru**
### Motivation

This PR refactors existing code: it fixes warnings reported by Clippy for Rust 1.59.

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Comment by benesch** [comment]
Unfortunately fixing these warnings breaks clippy on Rust 1.58. Sigh. Let’s bump the MSRV to 1.59?

**Comment by benesch** [comment]
Oh, you did. I wonder why CI didn’t rebuild a new builder image with Rust 1.59.

**Comment by antiguru** [comment]
> Oh, you did. I wonder why CI didn’t rebuild a new builder image with Rust 1.59.

I was trying to figure out where the Rust version comes from and couldn't. If you know, tell me and I'll make sure to get this working.

**Comment by benesch** [comment]
Oh, I see, the `bin/ci-builder` script isn't correctly putting the Rust version into the hash. I'll push up a fix.

**Review by benesch — APPROVED** [review]

**Comment by benesch** [comment]
Seems to have correctly re-triggered the image build, at least. We'll know in a bit.

**Pull request merged**
