### PR TITLE
chbench: remove custom schema-registry container

### PR DESCRIPTION
**Pull request by benesch**
flush-tables is now run by the chbench container. Plus this avoids
depending on a weirdly flaky `apt-get install` command; something about
the Confluent images breaks APT.

@quodlibetor and/or @umanwizard can you double check that this is accurate? I'm struggling to trace the history of this dependency.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/2781)

### CODE REVIEW

**Comment by nacrooks** [comment]
This might be a very stupid question, but do we still need flush-tables at all?

**Comment by cuongdo** [comment]
I don't believe we need flush-tables now, because we have RT consistency. I'd consider needing flush-tables to be a product deficiency.

**Comment by benesch** [comment]
Yeah definitely we _shouldn't_ need it, but grepping for `flush-tables` indicates it's still used in the chbench container, and I'm worried removing it will cause the chbench demo to break, if only because it is expecting the script to exist, not because it is actually important to the functioning of the demo.

**Comment by quodlibetor** [comment]
I can't see us passing the `flushSleepTime` parameter to chBenchmark, which I think means that this won't break anything?

**Comment by quodlibetor** [comment]
oh nevermind we are passing it, it's got a different name

**Comment by benesch** [comment]
Note that this does not remove the flush-tables script in the chbench container: https://github.com/MaterializeInc/materialize/blob/master/demo/chbench/chbench/flush-tables

**Comment by quodlibetor** [comment]
oh right, okay.

**Pull request merged**
