### PR TITLE
materialized: Stop child proc locking pid file

### LINKED ISSUE #11961: "another materialized process (PID 3923891) is running with the same data directory" not compatible with Cluster
### What version of Materialize are you using?

v0.26.1-dev (85be487e3)

### How did you install Materialize?

Built from source

### What was the issue?

If https://github.com/MaterializeInc/materialize/issues/11793 is triggered, all daemons exit but then it is not possible to restart mz:

```
pstoev@Ubuntu-2004-focal-64-minimal:~/materialize$ MZ_SOFT_ASSERTIONS=1 target/release/materialized  --experimental
materialized: another materialized process (PID 3923891) is running with the same data directory
data directory: /home/pstoev/materialize/mzdata
```

The PID in question does not exist in `ps` 

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jkosh44**
When a process is forked, the default behavior is for the child process
to inherit all open file descriptors from their parent.
Previously, when materialized forked storaged and computed using the
process orchestrator, storaged and computed would have open file
descriptors to the materialized.pid pid file. Therefore, whenever
materialized was restarted independently of computed/storaged, the
new materialized would mistakenly think that an old materialized was
still running, due to the open file descriptors.

This commit makes sure to set the FD_CLOEXEC flag on all pid files
after opening them, so that their children don't inherit open file
descriptors to pid files.

Fixes #11961

### Motivation
This PR fixes a recognized bug.

### Tips for reviewer
* `flopen.c` has the following snippet of code in the function `vflopenat`
```C
		/*
		 * The following change is provided as a specific example to
		 * avoid.
		 */
#if 0
		if (fcntl(fd, F_SETFD, FD_CLOEXEC) != 0) {
			serrno = errno;
			(void)close(fd);
			errno = serrno;
			return (-1);
		}
#endif
```
Also at the top of that function it says
```C
/*
 * Reliably open and lock a file.
 *
 * Please do not modify this code without first reading the revision history
 * and discussing your changes with <des@freebsd.org>.  Don't be fooled by the
 * code's apparent simplicity; there would be no need for this function if it
 * was easy to get right.
 */
```
Now, that's a little scary because it's saying to avoid exactly what this PR is trying to do. So I am probably being fooled by the code's apparent simplicity. However, 
1. It doesn't say why to avoid it.
2. I found the revision history and it is really not very illuminating: https://gitlab.freedesktop.org/libbsd/libbsd/-/commits/main/src/flopen.c
3. I'm sort of hoping that since we let `pidfile_open` return before calling `fcntl`, that it somehow makes it ok and safe. Though honestly it's mostly wishful thinking.

So I guess in opening this PR I'm hoping someone with more knowledge of the libbsd code can either comment on the safety of this or suggest an alternative approach.

### Testing

- [X] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - There are no user-facing behavior changes.

### CODE REVIEW

**Comment by benesch** [comment]
Ah, so the commit history to look at is actually FreeBSD's, which is where this code was copy/pasted into libbsd from: https://github.com/freebsd/freebsd-src/commit/4e2825545b5ee4db644ad01531044b278b58e4bd

**Comment by umanwizard** [comment]
I have no clue (and am definitely not a BSD expert 😂 ), but why not email that guy and ask?

**Comment by jkosh44** [comment]
> I have no clue (and am definitely not a BSD expert joy ), but why not email that guy and ask?

I think I am going to do that.

**Review by philip-stoev — APPROVED** [review]
Thanks. It fixes the particular issue that I had, so it is all good as far as I am concerned.

I think `FD_CLOEXEC` is the right thing to do, but I am not qualified to comment on the actual code.

**Comment by jkosh44** [comment]
I sent an email last night and am waiting for a response. If there's no response by EOD then I think I'm just going to merge it.

I also have been thinking and have thought of a plausible explanation for that block of code. `vflopenat` is a generic method used throught the FreeBSD code base. Some callers probably want their children to inherit the locks while some callers probably don't want their children to inherit the locks. Adding `fcntl` to `vflopenat` forces that decision on all callers and changes the default behavior of files. I'm guessing that adding that may even cause some known bugs in some of the callers. So instead of adding it directly into `vflopenat`, the callers themselves should use `fcntl` if they want to change the behavior. 

That's one guess anyways.

**Comment by benesch** [comment]
> I also have been thinking and have thought of a plausible explanation for that block of code. `vflopenat` is a generic method used throught the FreeBSD code base. Some callers probably want their children to inherit the locks while some callers probably don't want their children to inherit the locks. Adding `fcntl` to `vflopenat` forces that decision on all callers and changes the default behavior of files. I'm guessing that adding that may even cause some known bugs in some of the callers. So instead of adding it directly into `vflopenat`, the callers themselves should use `fcntl` if they want to change the behavior.

This was my hypothesis too! 

> If there's no response by EOD then I think I'm just going to merge it.

👍🏽

**Comment by jkosh44** [comment]
Ok, I've actually convinced myself that this is fine to do and am going to merge it now. If we find out differently later then we can fix it then.

Here's an alternate implementation of `pidfile_open` that explicitly calls `fcntl` with `FD_CLOEXEC`: https://github.com/freebsd/freebsd-src/blob/373ffc62c158e52cde86a5b934ab4a51307f9f2e/contrib/openbsm/compat/pidfile.h#L96-L183

Here's a couple of usages of `flopen` (which uses `vflopenat` under the hood) which passes the `FD_CLOEXEC` flag:
https://github.com/freebsd/freebsd-src/blob/373ffc62c158e52cde86a5b934ab4a51307f9f2e/lib/libutil/gr_util.c#L106
https://github.com/freebsd/freebsd-src/blob/373ffc62c158e52cde86a5b934ab4a51307f9f2e/lib/libutil/pw_util.c#L179

**Comment by umanwizard** [comment]
Let us know if he gets back to you, just out of curiosity.

**Pull request merged**
