### PR TITLE
sinks: relax UPSERT key checking, improve error message and warning

### PR DESCRIPTION
**Pull request by aljoscha**
In #6709 we introduced strict checks for the specified upsert sink key.
It turns out those checks are too strict because the optimizer currently
cannot (or will not) figure out the key for some views/collections where
it is clear for a user to see that there is a valid upsert key.

Side note, a valid upsert key must be a primary key of the sinked
collection.

Some thoughts on the situation and what we could (and/or should do):
 - merging this will re-open https://github.com/MaterializeInc/materialize/issues/5826, but the error message now more clearly describes why this happens
 - on sink creation we now log a warning that warns that the runtime panic could happen
 - I think warnings are easy to ignore by users, so probably not that useful, especially if we often have false negatives for the check
 - panicking because of a single misconfigured sink doesn't seem very user friendly
 - we are panicking in the sink because we would otherwise produce non-deterministic output, that's bad for some of our future work requirements
 - if possible, we should log an error instead of panicking and take that one sink offline (need to see how feasible that is)
 - long term, we should enable the stricter check on sink creation again, but only if we are sure that we are as smart as users about what makes a valid key

Also, sorry for the back-and-forth on this issue. 🙈

### CODE REVIEW

**Comment by aljoscha** [comment]
@nmeagan11 and/or @awang Is there any guidance on failure behaviour? Panicking is not good, but I feel it's better than logging a warning and continuing, because we would otherwise produce potentially non-deterministic output. Users probably aren't worrying about this because they don't understand the implications. So hard to judge.

cc @krishmanoh2

**Comment by awang** [comment]
How difficult would it be to allow users to choose for themselves, ideally at the source/sink/view level?  At the Materialized-level also works if it's easier. I can think of a few options:

1. Panic when non-sensical input is seen.  This is the least-useful option in my opinion, as I imagine this will be only used in production scenarios where the upstream sources are expected to be pre-processed by something with strong guarantees, such as a database.  This could also be used in development/testing to validate that the inputs are as expected.

2. Flag the result, but continue processing:
  a. Error stream: allow inputs that couldn't be processed to be redirected to an "error" sink
  b. Error message: log an error (if it's a Kafka source, include the offset / partition, etc as well) 

3. We could also put the source/sink in an "error" state and halt processing (but not panic). We might need the ability to create a error sink or error view (which could be TAILed), so users can get a callback notification when the error occurs.

In my opinion, if we had to go with a single option, Option 2 seems to most useful.  However, there are reasonable arguments for all 3 options, so I suspect over the grand scheme of things (over several years), we will get requests for all 3 error handling mechanisms.

**Comment by aljoscha** [comment]
Thanks, that's a good summary!

In the case of https://github.com/MaterializeInc/materialize/issues/5826, option 2. would not work, because it's not just a single invalid input. The fact that this error condition occurs makes us realize that the sink is misconfigured as an UPSERT sink.

I think for the short term we will panic. Until we find a way to more gracefully handle errors in sinks and report them to users, i.e. option 3.

**Comment by umanwizard** [comment]
@aljoscha  , do you have any examples of when the primary key was not correctly detected? It would be good to check with the optimizer team whether they can be fixed easily...

**Comment by aljoscha** [comment]
I'm afraid even basic things don't work. This is a simple example:

```
$ set upsert-keyschema={
    "type": "record",
    "name": "Key",
    "fields": [
        {"name": "key1", "type": "long"}
    ]
  }

$ set upsert-schema={
        "type" : "record",
        "name" : "test",
        "fields" : [
            {"name":"f1", "type":"string"},
            {"name":"f2", "type":"long"}
        ]
    }

$ kafka-create-topic topic=upsert-avro

$ kafka-ingest format=avro topic=upsert-avro key-format=avro key-schema=${upsert-keyschema} schema=${upsert-schema} publish=true
{"key1": 2} {"f1": "fish", "f2": 1000}
{"key1": 42} {"f1": "fish", "f2": 1000}

> CREATE MATERIALIZED SOURCE upsert_input
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC
  'testdrive-upsert-avro-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
  ENVELOPE UPSERT

> CREATE MATERIALIZED SOURCE upsert_input_2
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC
  'testdrive-upsert-avro-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
  ENVELOPE UPSERT

# works!

> CREATE MATERIALIZED VIEW joined_inputs AS select input2.key1, input.f1, input.f2 from upsert_input input, upsert_input_2 input2 where input.key1  = input2.key1

> CREATE SINK joined_sink_that_works FROM joined_inputs
  INTO KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'joined2-upsert-input-sink'
  KEY (key1)
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}' ENVELOPE UPSERT


# does not work!

> CREATE MATERIALIZED VIEW user_data (id, name) AS VALUES (0, 'hello'), (1, 'ciao'), (42, 'yes!')

> CREATE MATERIALIZED VIEW joined_to_view AS select input.key1, input.f1, input.f2 from user_data as users, upsert_input input where users.id  = input.key1

> CREATE SINK joined_to_view_doesnt_work FROM joined_to_view
  INTO KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'joined-upsert-input-sink'
  KEY (key1)
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}' ENVELOPE UPSERT
```
@wangandi or maybe also @asenac Do you have an idea why the catalog knows that `key1` is a key from `joined_inputs` but not for `joined_to_view`? For reference, the check where this information is used is here: https://github.com/MaterializeInc/materialize/blob/main/src/sql/src/plan/statement/ddl.rs#L1369. Apologies if you're not the right people to ask about this.

**Comment by wangandi** [comment]
The short answer is that Materialize does not yet detect that the values in `user_data.id` are unique. This is a TODO:  
https://github.com/MaterializeInc/materialize/blob/0d66b5c7689bca819653a7649aa28c8de6305a06/src/expr/src/relation/mod.rs#L253

Because it does not yet detect that the values in `user_data.id` are unique, it does not know that the values in `joined_to_view.key1` are unique.

**Comment by asenac** [comment]
As a workaround you could pass the constant values through a group by operator:

```materialize=> CREATE MATERIALIZED VIEW user_data (id, name) AS with b(id, name) as (VALUES (0, 'hello'), (1, 'ciao'), (42, 'yes!')) select id, name from b group by id, name;
CREATE VIEW
materialize=> explain typed plan for select * from user_data;
               Optimized Plan               
--------------------------------------------
 %0 =                                      +
 | Get materialize.public.user_data (u604)+
 | | types = (integer, text)               +
 | | keys = ((#0, #1))                     +
 
(1 row)

materialize=> 
```

**Comment by umanwizard** [comment]
I think something like this would fix that example. PR incoming, unless Frank/Andi/Andres object.

```
diff --git a/src/expr/src/relation/mod.rs b/src/expr/src/relation/mod.rs
index 1da2f1d23..e6af4f498 100644
--- a/src/expr/src/relation/mod.rs
+++ b/src/expr/src/relation/mod.rs
@@ -10,6 +10,7 @@
 #![deny(missing_docs)]
 
 use std::cmp::Ordering;
+use std::collections::HashSet;
 use std::fmt;
 
 use itertools::Itertools;
@@ -234,8 +235,13 @@ impl MirRelationExpr {
         match self {
             MirRelationExpr::Constant { rows, typ } => {
                 if let Ok(rows) = rows {
+                    let n_cols = typ.arity();
+                    // If the `i`th entry is `Some`, then we have not yet observed non-uniqueness in the `i`th column.
+                    let mut unique_values_per_col = vec![Some(HashSet::<Datum>::default()); n_cols];
                     for (row, _diff) in rows {
-                        for (datum, column_typ) in row.iter().zip(typ.column_types.iter()) {
+                        for (i, (datum, column_typ)) in
+                            row.iter().zip(typ.column_types.iter()).enumerate()
+                        {
                             // If the record will be observed, we should validate its type.
                             if datum != Datum::Dummy {
                                 assert!(
@@ -244,15 +250,27 @@ impl MirRelationExpr {
                                     column_typ,
                                     datum
                                 );
+                                if let Some(unique_vals) = &mut unique_values_per_col[i] {
+                                    let is_dupe = !unique_vals.insert(datum);
+                                    if is_dupe {
+                                        unique_values_per_col[i] = None;
+                                    }
+                                }
                             }
                         }
                     }
+                    let keyless_typ = RelationType::new(typ.column_types.clone());
                     if rows.len() == 0 || (rows.len() == 1 && rows[0].1 == 1) {
-                        RelationType::new(typ.column_types.clone()).with_key(vec![])
+                        keyless_typ.with_key(vec![])
                     } else {
-                        // TODO: Have the keys of the constant be the columns
-                        // containing unique values
-                        typ.clone()
+                        keyless_typ.with_keys(
+                            unique_values_per_col
+                                .into_iter()
+                                .enumerate()
+                                .filter(|(_idx, unique_vals)| unique_vals.is_some())
+                                .map(|(idx, _)| vec![idx])
+                                .collect(),
+                        )
                     }
                 } else {
                     typ.clone()
```

**Comment by umanwizard** [comment]
@wangandi Does the above look sane to you? (If so, I will add tests and make it into an official PR)

**Comment by umanwizard** [comment]
(Of course, that doesn't detect possible multi-column unique keys, but I think doing that would have exponential complexity)

**Comment by wangandi** [comment]
> @wangandi Does the above look sane to you? (If so, I will add tests and make it into an official PR)

Yes, it looks sane.

> (Of course, that doesn't detect possible multi-column unique keys, but I think doing that would have exponential complexity)

Indeed, I don't think we ought to be concerned about detecting multi-column unique keys.

**Comment by aljoscha** [comment]
But that just fixes it for this specific case of joining with a pre-computed VIEW of VALUES, right? That was just a stand-in. The real thing I wanted to show was the join itself: from looking at it, and from the fields that are used, `key1` should still be a unique key after the join.

In the real-world example where @krishmanoh2 observed this, the thing that was joined with was not a VIEW like that but some other source that didn't have keys.

This is the more complicated query I got from @krishmanoh2 :
```
create  view mv_items_inventory_status as 
select sold_items, inventory, sold_items*100/inventory as perc_sold, item_id, item_name 
from 
(select count(1) as sold_items, item_id from v_user_behavior_buy group by item_id) u 
join v_item_inventory_dim k on u.item_id = k.item_id 
join v_item_dim i on i.item_id = u.item_id;

create sink "mv_items_inventory_status_sink" from "mv_items_inventory_status" INTO kafka broker '172.31.19.147:9092'  topic 'mv_items_inventory_status_sink' key(item_id) with (consistency = true) format avro using confluent schema registry 'http://172.31.19.147:8081' ;
```

It's grouping by `item_id` and then joining some things to it, but `item_id` would be unique  from this.

Sorry I wasn't more clear about this!

**Comment by umanwizard** [comment]
What is `v_item_dim` there? Is its `item_id` field itself a primary key?

**Comment by aljoscha** [comment]
Ah true, I wasn't thinking straight, if `item_id` is not a primary key for `v_item_inventory` and `v_item_dim` as well it will not be a primary key of the join result. It might be that this check is good after all.

@krishmanoh2 Could you comment on whether `item_id` is a primary key that is known to materialize for the other inputs to the join? If they are sources the source definition would help. Might be that we have to continue this discussion somewhere else if it's sensitive information, though.

**Comment by krishmanoh2** [comment]
> Ah true, I wasn't thinking straight, if `item_id` is not a primary key for `v_item_inventory` and `v_item_dim` as well it will not be a primary key of the join result. It might be that this check is good after all.
> 
> @krishmanoh2 Could you comment on whether `item_id` is a primary key that is known to materialize for the other inputs to the join? If they are sources the source definition would help. Might be that we have to continue this discussion somewhere else if it's sensitive information, though.

item_id is a primary key (known to the user) but not defined in the source.

**Comment by umanwizard** [comment]
How is the source defined? Is there any way we could have figured out the primary key at source creation time?

**Comment by aljoscha** [comment]
Krishna mentioned that it's a CSV source, where we cannot currently define a key. He also reminded me of how Flink deals with this: on sources you can specify a `NOT ENFORCED` key (which is a SQL thing). Could be useful for us as well, but a potential footgun.

**Comment by umanwizard** [comment]
We have a way to do this in the system (`RelationExpr::DeclareKey`), but it's indeed a footgun.

**Comment by aljoscha** [comment]
Hmm, but it's not exposed in DDL. I could imagine something like an UPSERT csv source, but ordering seems harder than for Kafka...

**Comment by aljoscha** [comment]
I added https://github.com/MaterializeInc/materialize/issues/6985 as the proper solution for this.

**Pull request closed without merging**
