### PR TITLE
QGM: Lower outer join boxes

### LINKED ISSUE #9134: HIR ⇒ QGM ⇒ MIR support for `Join`

### PR DESCRIPTION
**Pull request by wangandi**
Closes #9134.

### Tips for reviewer

The first commit is the same as #10752.
The second commit copies over general join lowering. 
The third commit separates out a common method to be shared between QGM equijoin lowering and HIR equijoin lowering.
The fourth commit 1) copies over equijoin lowering 2) attempts to refactor equijoin lowering into something more comprehensible. 

Originally, the last commit also attempted to canonicalize predicates before equijoin checking so that a predicate like `lhs.id = rhs.id and true` gets properly detected as a equijoin, but more investigation into the sqllogictest result changes is needed.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

**Comment by philip-stoev** [comment]
I will try to run some experiments on this branch.

**Comment by philip-stoev** [comment]
Item No 1. This panic is triggered on `main` but not on this branch . As discussed with Alexander this should have returned an error to the user and not panicked.

```
fd9d0d896f src/sql/src/query_model/lowering.rs (Andres Senac         2021-10-27 12:45:26 +0200 218)             _ => panic!(),
```

query:
```
EXPLAIN  WITH cte_f1_f2_f3 AS ( SELECT * FROM table_f1_f2_f3 AS a1 ) SELECT COUNT(*) FROM cte_f1_f2_f3 , ( ( table_f4_f5 AS a2 INNER JOIN table_f5_f6 USING (f5) ) LEFT JOIN table_f5_f6 AS a3 USING ( f5 , f6 ) ) WHERE f1 >= f2 AND f6 <= 1 OR f5 IS  NULL;
```

**Comment by philip-stoev** [comment]
Item No 2. Another panic that should have been an error:

```
2022-02-21T08:33:36.454782Z ERROR panic: correlated joins are not supported yet
thread: coordinator
location: src/sql/src/query_model/mir.rs:108:21
```

**Comment by philip-stoev** [comment]
Item No 3 . I am not sure if this is actionable at this time, but in this branch some relatively degenerate queries could not be folded all the way to `Constant` whereas a non-QGM execution would do that:

```
# 2022-02-21T10:40:34 Simplified query:  EXPLAIN  SELECT * FROM t1 a1  LEFT  JOIN t1 a2  ON  TRUE  AND a1 .f1  = a2 .f1  LEFT  JOIN t2  ON  TRUE  WHERE a1 .f1  = a2 .f1  AND a2 .f2  =  5  AND a2 .f1  < a1 .f2  AND a2 .f1  = a1 .f2  AND a2 .f2  = a1 .f1   ;
# 2022-02-21T10:40:34 Result set diff:
# 2022-02-21T10:40:34 --- /tmp//randgen3514078-1645436434-server0.dump	2022-02-21 10:40:34.464090271 +0100
# 2022-02-21T10:40:34 +++ /tmp//randgen3514078-1645436434-server1.dump	2022-02-21 10:40:34.464090271 +0100
# 2022-02-21T10:40:34 @@ -1,19 +1,3 @@
# 2022-02-21T10:40:34  %0 =
# 2022-02-21T10:40:34 -| Get materialize.public.t1 (<U>)
# 2022-02-21T10:40:34 -| Filter (<#> = 5),(<#> = 5),(5 < <#>)
# 2022-02-21T10:40:34 -| ArrangeBy ()
# 2022-02-21T10:40:34 -
# 2022-02-21T10:40:34 -%1 =
# 2022-02-21T10:40:34 -| Get materialize.public.t1 (<U>)
# 2022-02-21T10:40:34 -| Filter (<#> = 5),(<#> = 5)
# 2022-02-21T10:40:34 -| Project (<#>)
# 2022-02-21T10:40:34 -| ArrangeBy ()
# 2022-02-21T10:40:34 -
# 2022-02-21T10:40:34 -%2 =
# 2022-02-21T10:40:34 -| Get materialize.public.t2 (<U>)
# 2022-02-21T10:40:34 -
# 2022-02-21T10:40:34 -%3 =
# 2022-02-21T10:40:34 -| Join %0 %1 %2
# 2022-02-21T10:40:34 -| | implementation = Differential %2 %0.() %1.()
# 2022-02-21T10:40:34 -| Project (<#>,<#>,<#>,<#>..<#>)
# 2022-02-21T10:40:34 +| Constant
```

The schema is:
```
CREATE TABLE t1 (f1 DOUBLE PRECISION, f2 DOUBLE PRECISION NOT NULL);
CREATE TABLE t2 (f1 DOUBLE PRECISION, f2 DOUBLE PRECISION NOT NULL);
```

I would say this is more of a random implementation artifact -- our `Constant` story is not 100% complete and non-QGM fails to detect a lot of much simpler constant queries. Furthermore, the presence of unrelated or unnecessary predicates, such as `TRUE AND xxx` influences the situation in suprising ways.

**Comment by philip-stoev** [comment]
Item No 4. Here is a win for QGM and this branch, as compared to the non-QGM execution. In `main`, the presence of `AND TRUE` prevents this outer join from being converted to an inner join:

```
materialize=>  EXPLAIN  SELECT  FROM orders  RIGHT  JOIN customer  ON  TRUE  WHERE o_orderdate  = ' 7 MONTH ' AND TRUE ;
                                           Optimized Plan                                           
----------------------------------------------------------------------------------------------------
 %0 =                                                                                              +
 | Get materialize.public.orders (u712)                                                            +
 | Project ()                                                                                      +
 | ArrangeBy ()                                                                                    +
                                                                                                   +
 %1 =                                                                                              +
 | Get materialize.public.customer (u708)                                                          +
 | Project ()                                                                                      +
                                                                                                   +
 %2 =                                                                                              +
 | Join %0 %1                                                                                      +
 | | implementation = Differential %1 %0.()                                                        +
 | Filter (err: invalid input syntax for type date: YEAR, MONTH, DAY are all required: " 7 MONTH ")+
```

I guess this proves the larger scope of this approach, as I can imagine a more complex, realistic clause at the place of the `AND TRUE`. Some ORM frameworks would also not hesitate to put random `AND 1=1`  in the resulting query, which is another case where the new code does better.

**Comment by philip-stoev** [comment]
Item No 5. For this slightly degenerate query, the QGM approach fails to push into both sides of the join:

```
materialize=> EXPLAIN SELECT * FROM orders FULL OUTER JOIN customer ON ( c_acctbal = o_totalprice ) WHERE  c_acctbal + o_totalprice = 123 AND c_acctbal = o_totalprice ;
                Optimized Plan                
----------------------------------------------
 %0 =                                        +
 | Get materialize.public.orders (u712)      +
 | Filter (123 = (#3 + #3))                  +
 | ArrangeBy (#3)                            +
                                             +
 %1 =                                        +
 | Get materialize.public.customer (u708)    +
 | Filter (123 = (#5 + #5))                  + <- only if QGM is offf
                                             +
 %2 =                                        +
 | Join %0 %1 (= #3 #14)                     +
 | | implementation = Differential %1 %0.(#3)+
 | Project (#0..#13, #3, #15, #16)           +
```

**Comment by philip-stoev** [comment]
Item No 6. With QGM, there is a an extra `Project`, which seems to be doing nothing in this particular case:

```
materialize=> EXPLAIN  SELECT * FROM table_f4_f5  RIGHT  JOIN table_f5_f6  USING ( f5  )  WHERE  TRUE  AND f5  = f4   ;
                Optimized Plan                
----------------------------------------------
 %0 =                                        +
 | Get materialize.public.table_f4_f5 (u1591)+
 | Filter (#0 = #1)                          +
 | Project (#0)                              + <- only with QGM
 | ArrangeBy (#0)                            +
                                             +
 %1 =                                        +
 | Get materialize.public.table_f5_f6 (u1593)+
 | Filter !(isnull(#0))                      +
                                             +
 %2 =                                        +
 | Join %0 %1 (= #0 #1)                      +
 | | implementation = Differential %1 %0.(#0)+
 | Project (#0, #0, #2)                      +
```

schema:

```
CREATE TABLE table_f4_f5 (f4 integer, f5 integer);
CREATE TABLE table_f5_f6 (f5 integer, f6 integer);
```

**Comment by philip-stoev** [comment]
Item No 7. This one is curious -- in a `USING` situation, QGM elects to take the values from the column from one of the participating tables wheres non-QGM takes the same column from the other table that has it. I could not think of a situation where that would be a problem. Strictly speaking I guess you probably want to take the value from the shorter of the two tables, but in the absence of table statistics this would not be possible:

```
materialize=>  EXPLAIN  SELECT * FROM table_f1_f2_f3  LEFT  JOIN ( table_f3_f4_f5  RIGHT  JOIN table_f5_f6  USING ( f5  )  )  USING ( f3  )  WHERE  TRUE  AND f5  =  0   ;
                   Optimized Plan                   
----------------------------------------------------
 %0 =                                              +
 | Get materialize.public.table_f1_f2_f3 (u1599)   +
 | Filter !(isnull(#2))                            +
 | ArrangeBy ()                                    +
                                                   +
 %1 =                                              +
 | Get materialize.public.table_f3_f4_f5 (u1601)   +
 | Filter (#2 = 0), !(isnull(#0))                  +
 | ArrangeBy (#0)                                  + <- f5 taken from here without QGM
                                                   +
 %2 =                                              +
 | Get materialize.public.table_f5_f6 (u1603)      +
 | Filter (#0 = 0)                                 +
 | Project (#1)                                    + <f5 taken from here with QGM
                                                   +
 %3 =                                              +
 | Join %0 %1 %2 (= #2 #3)                         +
 | | implementation = Differential %2 %0.() %1.(#0)+
 | Project (#2, #0, #1, #5, #4, #6)                +
```

**Review by philip-stoev — APPROVED** [review]
I am able to see this optimization in action, though not in isolation from the MIR optimizations that perform identical work. For quite a lot of queries the plans are the same, even though this optimization is able to convert more joins.

There were no wrong results. From the dozens upon dozens of query plans that I examined, the cases where the plan's change was negative or "sideways" have been listed in the comments. The rest of the cases the plans were positively better, with entire sections of outer join machinery eliminated.

**Comment by philip-stoev** [comment]
I also filed two separate issues with QGM which appeared to be disconnected from the task at hand https://github.com/MaterializeInc/materialize/issues/10799 - panic with CTEs and https://github.com/MaterializeInc/materialize/issues/10800 - wrong dataflow with aggregates.

**Comment by aalexandrov** [comment]
Item no. 5 is a manifestation of some form of fragility in the MIR optimizer.

```sql
SELECT
  *
FROM
  orders 
  FULL OUTER JOIN customer ON ( c_acctbal = o_totalprice )
WHERE
  c_acctbal + o_totalprice = 123 AND
  c_acctbal = o_totalprice
```

and

```sql
SELECT
  *
FROM
  orders, 
  customer
WHERE
  c_acctbal + o_totalprice = 123 AND
  c_acctbal = o_totalprice
```

are equivalent to the original query, and both result in the plan observed with QGM enabled. For some reason predicate propagation for this query works only when the inputs are connected with an outer join.

**Comment by aalexandrov** [comment]
I tried tackling Item no 5 with dec9ddef3e05d538503f022b93647e3cf3b10b9a, but this didn't help. I am including my changes here for completeness, we might want to do this in this PR.

**Review by aalexandrov — APPROVED** [review]
The only thing that I am suspicious is the 

```rust
assert!(!box_struct.predicates.is_empty());
```

call, but I think we discussed that we want to eliminate these calls next. Feel free to take or leave the last two commits that I appended to the PR.

**Pull request merged**
