### PR TITLE
Update RocksDB version

### PR DESCRIPTION
**Pull request by ggevay**
The current main is not building for me on an up-to-date Arch Linux, because I have gcc 13, which is not supported by our current RocksDB. This update includes
https://github.com/facebook/rocksdb/commit/88edfbfb5e1cac228f7cc31fbec24bb637fe54b1
through
https://github.com/rust-rocksdb/rust-rocksdb/commit/d44de09925c16757480e0676832c7123a86c7216
and it fixes the build on my machine.

See
https://materializeinc.slack.com/archives/CM7ATT65S/p1684318187564809

### Motivation

  * This PR fixes a previously unreported bug.

### Tips for reviewer

Btw. is it ok that the set of features specified when importing RocksDB is different in the different importing crates? I think cargo unions these sets, but maybe it's still better to make them the same? (I'm really not an expert on these things, so just asking.)

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by petrosagg** [comment]
> is it ok that the set of features specified when importing RocksDB is different in the different importing crates?

The correct thing to do is for each crate to only include the features that we use. However this can lead to extra build times when a specific crate is built which is why we have the `workspace-hack` crate which explicitly enables the union of all the needed features and is a dependency of all the crates in the workspace.

**Review by petrosagg — APPROVED** [review]
Thanks for fixing this!

**Comment by ggevay** [comment]
Unfortunately, there are several lint problems. One of them is the following version conflict:
`prettyplease` is being referenced in two different versions: `prost-build` and `tonic` wants v0.1.9, while the new rocksdb wants v0.2.4. I tried updating `tonic` and `prost-build` also, but our `prost-build` is already at the newest version. What can we do with this situation? Do we have to wait until they have newer versions, or is there some trick to solve this?

**Comment by ggevay** [comment]
Thanks a lot Brennan for fixing this!

Feel free to merge the PR without me when ready, because I'll be OOO in the next few hours until late evening.

**Comment by guswynn** [comment]
Thanks for handling this!!

**Pull request merged**
