### PR TITLE
Disable spuriously failing MySqlInitialLoad feature-benchmark scenario

### PR DESCRIPTION
**Pull request by rjobanp**
### Motivation

  * This PR fixes a previously unreported bug.

https://buildkite.com/materialize/release-qualification/builds/428#018daf74-d96d-4583-92c0-04c7db281b1f

This feature-benchmark scenario was failing due to the release qualification build for 0.88.0. This PR is to disable the test to unblock the release qual until we can diagnose what went wrong.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by sploiselle** [comment]
@MaterializeInc/testing Can y'all PTAL?

**Review by def- — APPROVED** [review]

**Comment by def-** [comment]
I'd prefer to have an issue associated with this (and linked in the comment), but ok

**Comment by nrainer-materialize** [comment]
```
_bk;t=1708047262508> SELECT count(*) FROM pk_table
_bk;t=1708047262508  /* B */
_bk;t=170804726250810000000
_bk;t=1708047262508
_bk;t=1708049063177^^^ +++
_bk;t=170804906317717:1: error: non-matching rows: expected:
_bk;t=1708049063177[["10000000"]]
_bk;t=1708049063177got:
_bk;t=1708049063177[["3200521"]]
_bk;t=1708049063177Poor diff:
_bk;t=1708049063177- 10000000
_bk;t=1708049063177+ 3200521
```

@rjobanp: Do we assume the cause is the same as for the `MySqlStreaming` scenario?

**Comment by rjobanp** [comment]
@nrainer-materialize haven't had time to look yet -- I just opened this PR since I thought we were trying to unblock the release late last night

**Comment by rjobanp** [comment]
It doesn't appear to be related since there is no concurrent inserting happening while the source is snapshotting, which afaik can cause the other failure

**Comment by rjobanp** [comment]
updated the PR and linked this issue https://github.com/MaterializeInc/materialize/issues/25323

**Comment by nrainer-materialize** [comment]
> It doesn't appear to be related since there is no concurrent inserting happening while the source is snapshotting, which afaik can cause the other failure

Yes, and it is off in the other direction. We get to few rows instead of duplicate rows.

**Review by nrainer-materialize — APPROVED** [review]

**Review by nrainer-materialize — APPROVED** [review]

**Pull request merged**
