### PR TITLE
sql: disallow FOR TABLES in load generators

### LINKED ISSUE #21163: Load generator sources crash if not all tables are selected
### What version of Materialize are you using?

main

### What is the issue?

Load generators that export multiple tables crash if they were not creates with `FOR ALL TABLES` but specific tables are selected instead.

For example:

```sql
CREATE SOURCE lg FROM LOAD GENERATOR AUCTION FOR TABLES (users) WITH (SIZE = '1');
```
... makes the source cluster crash with:
```
thread 'timely:work-0' panicked at 'index out of bounds: the len is 3 but the index is 3', /Users/jan/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/timely/src/dataflow/operators/partition.rs:52:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_bounds_check
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:162:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index_mut
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/slice/index.rs:264:14
   4: core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/slice/index.rs:29:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::IndexMut<I>>::index_mut
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/alloc/src/vec/mod.rs:2702:9
   6: <timely::dataflow::stream::StreamCore<G,alloc::vec::Vec<D>> as timely::dataflow::operators::partition::Partition<G,D,D2,F>>::partition::{{closure}}::{{closure}}::{{closure}}
             at /Users/jan/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/timely/src/dataflow/operators/partition.rs:52:25
   7: timely::dataflow::operators::generic::handles::InputHandleCore<T,D,P>::for_each
             at /Users/jan/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/timely/src/dataflow/operators/generic/handles.rs:94:13
   8: <timely::dataflow::stream::StreamCore<G,alloc::vec::Vec<D>> as timely::dataflow::operators::partition::Partition<G,D,D2,F>>::partition::{{closure}}::{{closure}}
             at /Users/jan/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/timely/src/dataflow/operators/partition.rs:46:17
   9: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build::{{closure}}::{{closure}}
             at /Users/jan/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/timely/src/dataflow/operators/generic/builder_rc.rs:133:31
  10: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
             at /Users/jan/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/timely/src/dataflow/operators/generic/builder_rc.rs:172:26
  11: <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
             at /Users/jan/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/timely/src/dataflow/operators/generic/builder_raw.rs:204:9
  12: timely::progress::subgraph::PerOperatorState<T>::schedule
             at /Users/jan/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/timely/src/progress/subgraph.rs:699:30
  13: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at /Users/jan/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/timely/src/progress/subgraph.rs:346:26
  14: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at /Users/jan/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/timely/src/progress/subgraph.rs:312:17
  15: timely::progress::subgraph::PerOperatorState<T>::schedule
             at /Users/jan/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/timely/src/progress/subgraph.rs:699:30
  16: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at /Users/jan/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/timely/src/progress/subgraph.rs:346:26
  17: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at /Users/jan/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/timely/src/progress/subgraph.rs:312:17
  18: timely::worker::Wrapper::step::{{closure}}
             at /Users/jan/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/timely/src/worker.rs:754:57
  19: core::option::Option<T>::map
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/option.rs:1075:29
  20: timely::worker::Wrapper::step
             at /Users/jan/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/timely/src/worker.rs:754:26
  21: timely::worker::Worker<A>::step_or_park
             at /Users/jan/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/timely/src/worker.rs:396:38
  22: mz_storage::storage_state::Worker<A>::run_client
             at ./src/storage/src/storage_state.rs:522:17
  23: mz_storage::storage_state::Worker<A>::run
             at ./src/storage/src/storage_state.rs:472:21
  24: <mz_storage::server::Config as mz_cluster::types::AsRunnableWorker<mz_storage_client::client::StorageCommand,mz_storage_client::client::StorageResponse>>::build_and_run
             at ./src/storage/src/server.rs:109:9
  25: mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<C,R,<Worker as mz_cluster::types::AsRunnableWorker<C,R>>::Activatable>,C,R>,Worker,C,R>::build_timely::{{closure}}::{{closure}}
             at ./src/cluster/src/server.rs:188:13
  26: timely::execute::execute_from::{{closure}}
             at /Users/jan/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/timely/src/execute.rs:388:22
  27: timely_communication::initialize::initialize_from::{{closure}}
             at /Users/jan/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/communication/src/initialize.rs:316:33
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I tested this also with the TPCH load generator, which produces the same crash.

-------

AFAICT what happens here is that specifying `FOR TABLES (...)` limits the number of source outputs, but the event stream generated by the load generator remains unchanged. So when we try to `partition` the event stream into the individual source streams some of the events map to outputs that don't exist.

### PR DESCRIPTION
**Pull request by mjibson**
They always produce all tables, so we don't allow subsets.

Fixes #21163

### Motivation

  * This PR fixes a recognized bug.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - n/a

### CODE REVIEW

**Comment by mjibson** [comment]
A user *could* have typed this and it'd be persisted to their catalog and auto crash forever. So presumably that didn't happen because we would have heard about it.

**Review by ParkMyCar — APPROVED** [review]

**Comment by mjibson** [comment]
Ugh: this was actually working for SOME sources, so a user could have typed it and it's running, and so this PR will break their envd on start. I'm inclined to move along anyway. Maybe I'll figure out a query we could run, but I'm so doubtful anyone actually has this in their env.

**Comment by mjibson** [comment]
Current status: source_with_schema.slt uses FOR TABLES with a load generator to test putting subsources in different schemas. That test needs to be move to testdrive so it can use a postgres source. Not working on figuring that out right now.

**Comment by mjibson** [comment]
@MaterializeInc/qa are one of you available to move the source with schema test into testdrive?

**Comment by philip-stoev** [comment]
The offending test has been replaced.

**Comment by mjibson** [comment]
Thank you!

**Review by nrainer-materialize — APPROVED** [review]

**Pull request merged**
