### PR TITLE
tests: disable failing SLT test

### PR DESCRIPTION
**Pull request by nrainer-materialize**
https://buildkite.com/materialize/slt/builds/5958

### CODE REVIEW

**Review by bobbyiliev — APPROVED** [review]

**Comment by jkosh44** [comment]
If possible it would be better just to exclude this from the auto-index select tests instead of commenting it out all together.

**Comment by nrainer-materialize** [comment]
> If possible it would be better just to exclude this from the auto-index select tests instead of commenting it out all together.

I am not sure if that's possible (with reasonable efforts).

**Comment by ggevay** [comment]
I think it would be also fine to just remove the entire `map.slt` from auto-index selects.

**Comment by nrainer-materialize** [comment]
> I think it would be also fine to just remove the entire `map.slt` from auto-index selects.

Ah, okay, I can do that

**Pull request merged**
