### PR TITLE
tests: SLT: rework mzcompose-based test entry point, add possibility to specify test

### PR DESCRIPTION
**Pull request by nrainer-materialize**
SLT: https://buildkite.com/materialize/sql-logic-tests/builds/5826

### CODE REVIEW

**Comment by nrainer-materialize** [comment]
@def-: Still a draft, but does the general design seem sound?

**Review by def- — COMMENTED** [review]
The general design looks reasonable to me!

**Comment by nrainer-materialize** [comment]
Ready for review.

✅ I compared the commands that are generated to make sure that the set of files for each command is still the same.

**Comment by nrainer-materialize** [comment]
`stdbuf` with `tee` [does not end up in the right place,](https://buildkite.com/materialize/sql-logic-tests/builds/5825) disabling that.

**Comment by nrainer-materialize** [comment]
✅ SLT pipeline is green with disabled tee.

**Review by def- — APPROVED** [review]
Nice cleanup!

**Pull request merged**
