### PR TITLE
persist: signal to tokio that we're entering a blocking sqlite call 

### PR DESCRIPTION
**Pull request by petrosagg**
### Motivation

I changed #12452 to use `tokio::task::block_in_place` which allows us to provide a closure that can borrow from the stack, so we can avoid cloning the arguments, and doesn't generate an extra error variant to take care of.

### CODE REVIEW

**Comment by guswynn** [comment]
Did you measure this being significantly more performant then just cloning in https://github.com/MaterializeInc/materialize/pull/12452 ? As I understand it, `block_in_place` comes at a heavy cost: it spins up a thread, just like `spawn_blocking`, moves the `tokio` runtime `Core` structure onto that thread, and then moves it all back after the `block_in_place` is done

additionally, the extra error variant can be made to match the behavior of this change by using https://docs.rs/tokio/latest/tokio/task/struct.JoinError.html#method.into_panic

**Comment by petrosagg** [comment]
@guswynn what is the cost associated with moving the runtime to another thread? My understanding is that nothing actually moves. The reason I like `block_in_place` because it captures the intent better, `spawn` methods don't make a lot of sense if you immediately await them

**Comment by guswynn** [comment]
@petrosagg I am not an expert, but around last year I debugged porting some code from cpp to rust, and wrote this https://rust-lang.github.io/wg-async/vision/submitted_stories/status_quo/barbara_bridges_sync_and_async.html

The discussion: https://github.com/rust-lang/wg-async/pull/144 talks about the subtleties of `block_in_place` around that time, I don't think its materially changed. I think the best conclusion I can come up with is: `block_in_place` is probably about as costly as `spawn_blocking`, MAY move other waiting tasks to a different thread and back, and can be harder to reason about. If we are okay with those tradeoffs over `clone + spawn`, then after this I can add `block_in_place` to `mz_ore::task` and write some docs on it

**Comment by petrosagg** [comment]
Interesting, I didn't know about that. I didn't suggest it for performance reasons and I think the nicer syntax would outweigh any performance gains in this case (because I expect them to be negligible).

But the last point of alice from the forum that it cannot be used in within-task concurrency structures is a deal breaker because who knows where the future returned will end up. I agree we should use `spawn_blocking`, thanks for pointing that out!

**Comment by petrosagg** [comment]
@danhhz do you want me to update this PR to use `spawn_blocking` or close it and go with yours?

**Pull request closed without merging**
