### PR TITLE
adapter: adjust error codes based on severity

### LINKED ISSUE #23313: SQL: Fix notice error codes
### What version of Materialize are you using?

v0.78.0-dev

### What is the issue?

The majority of our error codes for notices are set to `SqlState::WARNING`.

https://github.com/MaterializeInc/materialize/blob/c244ed46a11b91953523343bbdd81d31358d904e/src/adapter/src/notice.rs#L223-L264

In PostgreSQL, if an error code isn't explicitly set in an error, then the default error code depends on the error severity level:

https://github.com/postgres/postgres/blob/3650e7a3933166b40f7f9043bd91f45d3467c74d/src/backend/utils/error/elog.c#L452-L458

https://github.com/postgres/postgres/blob/3650e7a3933166b40f7f9043bd91f45d3467c74d/src/include/utils/elog.h#L25-L56

Based on that, any message with a severity of `NOTICE`, which most of our notices have, and no explicit error code, should have a default error code of `SqlState::SUCCESSFUL_COMPLETION`.

https://github.com/MaterializeInc/materialize/blob/c244ed46a11b91953523343bbdd81d31358d904e/src/adapter/src/notice.rs#L138-L183

For all of our notices that indicate the successful completion of a statement, and that there isn't an explicit error code from PostgreSQL, we should update the error code to `SqlState::SUCCESSFUL_COMPLETION`.

NOTE: To find if an error has an explicit error code in PostgreSQL, it's usually helpful to search for the error message in the PostgreSQL repository. For example:

https://github.com/postgres/postgres/blob/3650e7a3933166b40f7f9043bd91f45d3467c74d/src/backend/catalog/aclchk.c#L380-L384

### PR DESCRIPTION
**Pull request by sdht0**
`notice` and higher severity should emit `SUCCESSFUL_COMPLETION` instead of `WARNING`.

Fixes #23313.

### Motivation

This ensures the emitted error codes match the behavior in PostgreSQL, as per #23313.

### Tips for reviewer

The linked issue mentions that some of the warnings correspond to explicit error codes in PostgreSQL. However, I did not manage to find such codes apart from `CannotRevoke`, which was already mentioned in the issue. Maybe I missed others?

I'm also not sure if this change needs tests. I didn't see any existing ones at least.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by maddyblue** [comment]
Thanks for this contribution! From first look, I'm not convinced the right way to do this is to hard code `SUCCESSFUL_COMPLETION`. We may be better served changing `code()` to return an `Option<SqlState>` so that we can have a central place that mimics the postgres error code defaults, and then change these places to return `None`. `code()` exists in various places, so this might not be a small change.

**Comment by sdht0** [comment]
Thanks for the feedback @maddyblue.

I can see that the `code` is serialized directly, for instance at: https://github.com/MaterializeInc/materialize/blob/9ebe2787cb794726bc2ddfa7204f49c82010c2e0/src/pgwire/src/codec.rs#L356

Keeping the default state centralized is probably better. As an alternative, how about merging all these arms into a default `_ => SqlState::SUCCESSFUL_COMPLETION`?

**Comment by maddyblue** [comment]
There's two big `code()` impls (here, and adapter/src/errors.rs), so merging all of the arms still feels like not a full solution unfortunately.

**Comment by sdht0** [comment]
Ah I see.

I'm missing something. When you say `Option<SqlState>`, which conditions will results in a `None`? The ones emitting `SUCCESSFUL_COMPLETION` here? And how about the ones in `errors.rs`?

In general, what is the flow of errors codes in both these files that you have in mind? I can put in the work to implement that.

**Comment by maddyblue** [comment]
Yes, the ones that were changed to emit `SUCCESSFUL_COMPLETION` would emit `None`. I haven't read the postgres code closely, but the snippet linked in the issue suggests that there's a default error code based on severity, and then I would guess that any error can apply a more specific code if needed. It is possible we have discovered this is not a great first issue because that's a larger change.

**Comment by sdht0** [comment]
Alright, so from what I understand, `notice.rs` and `error.rs` should emit only non-default error codes and some new centralized logic should set the defaults, mimicking https://github.com/postgres/postgres/blob/3650e7a3933166b40f7f9043bd91f45d3467c74d/src/backend/utils/error/elog.c#L452-L458. Is this what you have in mind?

Also, do you think this PR still makes the status-quo better and can still be merged while we wait for the larger refactor?

**Comment by maddyblue** [comment]
Yes, it certainly makes it better, and would be an easy point to refactor later. I believe I've enabled the test run.

**Comment by sdht0** [comment]
Looks like there _are_ tests which rely on the error code. Will go through them and update as needed.

**Comment by maddyblue** [comment]
You need to rebase main to fix the persist lint. Then run `REWRITE=true bin/cargo-test -p mz-environmentd --test server test_http_sql` which should auto rewrite the tests for you. The other failures look like flakes to me.

**Comment by sdht0** [comment]
Thanks for suggesting `REWRITE`! I had read about that and promptly forgot.

The suggested command needs connection to cockroachdb as well, like so: `REWRITE=true COCKROACH_URL=postgres://root@localhost:26257 bin/cargo-test -p mz-environmentd --test server test_http_sql`. Just the one change it seems.

**Comment by maddyblue** [comment]
Ah yes! I have that env var set in a test script so I don't realize when it's required. Clicked rebuild and auto merge, maybe it'll work?

**Comment by maddyblue** [comment]
Rebuilding! We'll get there.

**Comment by sdht0** [comment]
Yeah, one more test had output changes. Hopefully now...

**Comment by sdht0** [comment]
Works! Needs a PR approval and this can get in. Thanks a lot for your time reviewing this!

**Review by maddyblue — APPROVED** [review]

**Pull request merged**
