### PR TITLE
Qualify all references issue numbers in the materialize repo

### PR DESCRIPTION
**Pull request by chaas**
Do this by adding the `materialize#` prefix to the issue number.
E.g. Make `TODO(#1234)` instead `TODO(materialize#1234)`.
This is in preparation for making github issues private. The old links will still work and redirect to the correct issue in the new repo, but the issues will have different ids in the new repo after the migration, so the TODOs should be clear about which repo the number is referring to.

### Motivation

This PR refactors existing code. In service of the plans to make Github issues private, and use Github discussions for public tracking instead.

### Tips for reviewer

Are there other potential variants of this that I may have missed?

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

**Review by jkosh44 — APPROVED** [review]

**Review by def- — APPROVED** [review]

**Comment by def-** [comment]
> Are there other potential variants of this that I may have missed?

We have files ending on `.gh<id>` to disable them because of an issue. Since they are testdrive files, we can instead use this pattern at the top of the file:
```
# TODO: Reenable when materialize#<id> is fixed
$ skip-if
SELECT true
```

**Review by nrainer-materialize — CHANGES_REQUESTED** [review]
There are many occurrences that are not caught. I will try to add some more.

**Review by nrainer-materialize — APPROVED** [review]

**Comment by nrainer-materialize** [comment]
Rebased and replaced further matches.

**Comment by nrainer-materialize** [comment]
@def-: I am sure I still did not catch all of them. Can we emit warnings in the ci-issue-detector when it detects non-qualified issue numbers?

**Comment by def-** [comment]
Sure, will add it.

**Comment by chaas** [comment]
Thank you so much for the help @def- and @nrainer-materialize .
You're right, searching for the regex `(\(| )#[0-9]{4}` produces a bunch more results, mostly in test files, and many like `# Regression test for #9657`.
I can open another PR to change all of them as well, since this one's already quite big.

**Pull request merged**
