### PR TITLE
sqllogictest: enable persist PubSub in SLT

### LINKED ISSUE #23980: sqllogictest has become twice as slow
### What version of Materialize are you using?

a8e68c5959

### What is the issue?

I'm investigating. Last good version: https://buildkite.com/materialize/sql-logic-tests/builds/5765#_
First bad version: https://buildkite.com/materialize/sql-logic-tests/builds/5767#018c6d75-4bb5-41d9-bbd3-65f833b791a2

### PR DESCRIPTION
**Pull request by benesch**
Fix #23980.

### Motivation

  * This PR adds a known-desirable feature.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - n/a

### CODE REVIEW

**Review by def- — APPROVED** [review]
Did you just write that up during the meeting? I'll check locally what this does with SLT runtimes!

**Comment by benesch** [comment]
> Did you just write that up during the meeting?

Yessir!

> I'll check locally what this does with SLT runtimes! Also triggering long SLT in CI.

This is substantially better, right?

image

**Comment by def-** [comment]
This seems to bring us back to the runtimes from before the pubsub default config value changes. Still waiting for the long tests: https://buildkite.com/materialize/sql-logic-tests/builds/5772 Then I have a small change I'd like to append to this PR before submitting it:
```diff
diff --git a/ci/slt/pipeline.template.yml b/ci/slt/pipeline.template.yml
index 030898b30d..c827e8d159 100644
--- a/ci/slt/pipeline.template.yml
+++ b/ci/slt/pipeline.template.yml
@@ -19,7 +19,7 @@ steps:

   - id: sqllogictest
     label: ":bulb: SQL logic tests %N"
-    timeout_in_minutes: 360 # TODO(def-) Turn back to 180 when #23980 is fixed
+    timeout_in_minutes: 180
     parallelism: 10
     artifact_paths: junit_*.xml
     agents:
@@ -31,7 +31,7 @@ steps:

   - id: sqllogictest-1-replica
     label: ":bulb: SQL logic tests 1 replica %N"
-    timeout_in_minutes: 360 # TODO(def-) Turn back to 180 when #23980 is fixed
+    timeout_in_minutes: 180
     parallelism: 10
     artifact_paths: junit_*.xml
     agents:
@@ -41,6 +41,7 @@ steps:
           composition: sqllogictest
           run: sqllogictest
           args: [--replicas=1]
+    skip: "Too expensive, didn't find anything interesting yet"

   - wait: ~
     continue_on_failure: true
```

**Comment by benesch** [comment]
Beautiful! Please feel free to push at this PR and merge as you see fit.

**Review by danhhz — APPROVED** [review]
hell yes

**Review by ParkMyCar — APPROVED** [review]

**Pull request merged**
