### PR TITLE
Reorganize transforms in "Logical planning".

### PR DESCRIPTION
**Pull request by wangandi**
Hopefully I have not mixed up "physical" and "logical" planning.

Comes with a bonus regression test for #6072.

### CODE REVIEW

**Comment by philip-stoev** [comment]
I would like to test this, but I am not working this or next week. So please do push if you can not wait that long. Thanks.

**Review by asenac — APPROVED** [review]

**Review by frankmcsherry — APPROVED** [review]
The organization looks good. The only comment I have is:

> Hopefully I have not mixed up "physical" and "logical" planning.

I think it is different from what I had in mind. At least, it seems that you have physical as the first class of optimizations and logical as the second class. Maybe this means that the names aren't as great as I thought.

A goal was to start with some transformations that are close to the "semantic" transforms that @asenac might think of: optimizations meant to clarify and simplify the algebraic representation of the query (simplify joins, prune branches, fuse operators). This may then be followed by optimizations related to the structure of the AST: for example moving projections around, filters maybe (though we like to do those early in the process, they seem to be physical transforms). These second optimizations are meant to be "now that we see the query we meant to evaluate, let us optimize the structure we will use". Anyhow, I was thinking of these as logical and physical respectively, though .. again maybe we should find clearer names. :D

**Comment by asenac** [comment]
The only difference between logical transforms and the semantic transforms I was talking about is the set of operators we deal with in each of them: logical operators that represent how to get the stuff done in the conceptual world vs. semantic operators that represent what you want to get. Most query engines don't make that distinction, arguing that some transforms like predicate pushdown are needed later in the compilation process and it is better to have a single implementation of the transformation rule dealing with a unified representation of the query, which is a fair point. What they do is to convert the AST into a "logical" plan, that is first simplified and then iteratively converted into a "physical" plan, deciding what physical implementation of a given logical operator should be used on each case, ie. things like logical Joins get converted into actual HashJoin, NLJ, SortMergeJoin operators.

My mental model is the following:

- AST - how you express what you want to get
- semantic representation/plan - what you really want to get. You can think of it as a richer version of the AST, which shape is not driven by how you have structured your parser or what tool you have used to implement it, and it's free of all the syntactic sugar SQL has.
- logical plan - how you get what you want in a conceptual world with infinite resources; the algebraic representation.
- physical plan - how you actually get what you want; a plan that is executable in the real world.

I think that some transformations (moving predicates around, pruning unused columns, converting an outer into an inner join, constant propagation, removing constants from grouping keys, removing unnecessary order properties) are easier to reason about with a "semantic plan", but as I've said, I understand the argument in favor of a unified representation used by all transformations.

**Comment by philip-stoev** [comment]
In this branch I am getting the crash above. It is reproducible 100% , but unfortunately only within the randomized test framework -- if I run the same queries through the psql client, I can not get it to crash. Would it be possible to debug and fix this based on the message below alone?

```
materialized v0.7.3-dev (77145e684) listening on 0.0.0.0:6875...
2021-05-10T13:08:37.721684Z ERROR panic: called `Result::unwrap()` on an `Err` value: "Can\'t union types: Record { fields: [(ColumnName(\"f1\"), ColumnType { nullable: false, scalar_type: Float64 }), (ColumnName(\"f2\"), ColumnType { nullable: false, scalar_type: Float64 })], custom_oid: None, custom_name: None } and Record { fields: [(ColumnName(\"f1\"), ColumnType { nullable: true, scalar_type: Float64 }), (ColumnName(\"f2\"), ColumnType { nullable: false, scalar_type: Float64 })], custom_oid: None, custom_name: None }\nIn Union {\n    base: Constant {\n        rows: Ok(\n            [],\n        ),\n        typ: RelationType {\n            column_types: [\n                ColumnType {\n                    nullable: false,\n                    scalar_type: Float64,\n                },\n                ColumnType {\n                    nullable: false,\n                    scalar_type: Float64,\n                },\n                ColumnType {\n                    nullable: false,\n                    scalar_type: Record {\n                        fields: [\n                            (\n                                ColumnName(\n                                    \"f1\",\n                                ),\n                                ColumnType {\n                                    nullable: false,\n                                    scalar_type: Float64,\n                                },\n                            ),\n                            (\n                                ColumnName(\n                                    \"f2\",\n                                ),\n                                ColumnType {\n                                    nullable: false,\n                                    scalar_type: Float64,\n                                },\n                            ),\n                        ],\n                        custom_oid: None,\n                        custom_name: None,\n                    },\n                },\n                ColumnType {\n                    nullable: false,\n                    scalar_type: Int64,\n                },\n            ],\n            keys: [\n                [],\n            ],\n        },\n    },\n    inputs: [\n        Join {\n            inputs: [\n                Project {\n                    input: Join {\n                        inputs: [\n                            Union {\n                                base: Negate {\n                                    input: Reduce {\n                                        input: Constant {\n                                            rows: Ok(\n                                                [],\n                                            ),\n                                            typ: RelationType {\n                                                column_types: [\n                                                    ColumnType {\n                                                        nullable: false,\n                                                        scalar_type: Float64,\n                                                    },\n                                                    ColumnType {\n                                                        nullable: false,\n                                                        scalar_type: Float64,\n                                                    },\n                                                    ColumnType {\n                                                        nullable: false,\n                                                        scalar_type: Record {\n                                                            fields: [\n                                                                (\n                                                                    ColumnName(\n                                                                        \"f1\",\n                                                                    ),\n                                                                    ColumnType {\n                                                                        nullable: false,\n                                                                        scalar_type: Float64,\n                                                                    },\n                                                                ),\n                                                                (\n                                                                    ColumnName(\n                                                                        \"f2\",\n                                                                    ),\n                                                                    ColumnType {\n                                                                        nullable: false,\n                                                                        scalar_type: Float64,\n                                                                    },\n                                                                ),\n                                                            ],\n                                                            custom_oid: None,\n                                                            custom_name: None,\n                                                        },\n                                                    },\n                                                    ColumnType {\n                                                        nullable: false,\n                                                        scalar_type: Int64,\n                                                    },\n                                                ],\n                                                keys: [\n                                                    [],\n                                                ],\n                                            },\n                                        },\n                                        group_key: [\n                                            Column(\n                                                0,\n                                            ),\n                                            Column(\n                                                1,\n                                            ),\n                                        ],\n                                        aggregates: [],\n                                        monotonic: false,\n                                        expected_group_size: None,\n                                    },\n                                },\n                                inputs: [\n                                    Reduce {\n                                        input: Get {\n                                            id: Local(\n                                                LocalId(\n                                                    5,\n                                                ),\n                                            ),\n                                            typ: RelationType {\n                                                column_types: [\n                                                    ColumnType {\n                                                        nullable: true,\n                                                        scalar_type: Float64,\n                                                    },\n                                                    ColumnType {\n                                                        nullable: true,\n                                                        scalar_type: Float64,\n                                                    },\n                                                ],\n                                                keys: [],\n                                            },\n                                        },\n                                        group_key: [\n                                            Column(\n                                                0,\n                                            ),\n                                            Column(\n                                                1,\n                                            ),\n                                        ],\n                                        aggregates: [],\n                                        monotonic: false,\n                                        expected_group_size: None,\n                                    },\n                                ],\n                            },\n                            Get {\n                                id: Local(\n                                    LocalId(\n                                        5,\n                                    ),\n                                ),\n                                typ: RelationType {\n                                    column_types: [\n                                        ColumnType {\n                                            nullable: true,\n                                            scalar_type: Float64,\n                                        },\n                                        ColumnType {\n                                            nullable: true,\n                                            scalar_type: Float64,\n                                        },\n                                    ],\n                                    keys: [],\n                                },\n                            },\n                        ],\n                        equivalences: [\n                            [\n                                Column(\n                                    0,\n                                ),\n                                Column(\n                                    2,\n                                ),\n                            ],\n                            [\n                                Column(\n                                    1,\n                                ),\n                                Column(\n                                    3,\n                                ),\n                            ],\n                        ],\n                        demand: None,\n                        implementation: Unimplemented,\n                    },\n                    outputs: [\n                        0,\n                        1,\n                    ],\n                },\n                Constant {\n                    rows: Ok(\n                        [\n                            (\n                                Row{[\n                                    Null,\n                                    Null,\n                                ]},\n                                1,\n                            ),\n                        ],\n                    ),\n                    typ: RelationType {\n                        column_types: [\n                            ColumnType {\n                                nullable: true,\n                                scalar_type: Record {\n                                    fields: [\n                                        (\n                                            ColumnName(\n                                                \"f1\",\n                                            ),\n                                            ColumnType {\n                                                nullable: true,\n                                                scalar_type: Float64,\n                                            },\n                                        ),\n                                        (\n                                            ColumnName(\n                                                \"f2\",\n                                            ),\n                                            ColumnType {\n                                                nullable: false,\n                                                scalar_type: Float64,\n                                            },\n                                        ),\n                                    ],\n                                    custom_oid: None,\n                                    custom_name: None,\n                                },\n                            },\n                            ColumnType {\n                                nullable: true,\n                                scalar_type: Int64,\n                            },\n                        ],\n                        keys: [],\n                    },\n                },\n            ],\n            equivalences: [],\n            demand: None,\n            implementation: Unimplemented,\n        },\n    ],\n}"
thread: <unnamed>
location: src/expr/src/relation/mod.rs:484:30
version: 0.7.3-dev (77145e6847b885eedc8aa40c5bae486f62a3fd20)
backtrace:
   0: materialized::handle_panic
             at src/materialized/src/bin/materialized/main.rs:710:21
   1: core::ops::function::Fn::call
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:70:5
   2: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
   5: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   6: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   7: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   8: core::result::Result<T,E>::unwrap
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/result.rs:1037:23
      expr::relation::MirRelationExpr::typ
             at src/expr/src/relation/mod.rs:481:37
   9: expr::relation::MirRelationExpr::typ
             at src/expr/src/relation/mod.rs:283:31
  10: expr::relation::MirRelationExpr::typ
             at src/expr/src/relation/mod.rs:416:33
  11: expr::relation::MirRelationExpr::take_safely
             at src/expr/src/relation/mod.rs:1169:19
  12: transform::inline_let::InlineLet::action
             at src/transform/src/inline_let.rs:78:25
  13: transform::inline_let::InlineLet::action
             at src/transform/src/inline_let.rs:80:13
  14: transform::inline_let::InlineLet::action
             at src/transform/src/inline_let.rs:80:13
  15: transform::inline_let::InlineLet::action
             at src/transform/src/inline_let.rs:80:13
  16: transform::inline_let::InlineLet::action
             at src/transform/src/inline_let.rs:80:13
  17: <transform::inline_let::InlineLet as transform::Transform>::transform
             at src/transform/src/inline_let.rs:31:9
  18: <transform::Fixpoint as transform::Transform>::transform
             at src/transform/src/lib.rs:114:17
  19: transform::Optimizer::transform
             at src/transform/src/lib.rs:166:13
      transform::Optimizer::optimize
             at src/transform/src/lib.rs:262:9
  20: coord::coord::Coordinator::prep_relation_expr
             at src/coord/src/coord.rs:2720:16
  21: coord::coord::Coordinator::sequence_explain_plan
             at src/coord/src/coord.rs:2458:21
  22: coord::coord::Coordinator::sequence_plan::{{closure}}
             at src/coord/src/coord.rs:1359:17
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/future/mod.rs:80:19
      coord::coord::Coordinator::message_statement_ready::{{closure}}
             at src/coord/src/coord.rs:551:32
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/future/mod.rs:80:19
      coord::coord::Coordinator::serve::{{closure}}
             at src/coord/src/coord.rs:470:51
  24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/future/mod.rs:80:19
      tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/pstoev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/park/thread.rs:263:54
      tokio::coop::with_budget::{{closure}}
             at /home/pstoev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/coop.rs:106:9
      std::thread::local::LocalKey<T>::try_with
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/local.rs:272:16
      std::thread::local::LocalKey<T>::with
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/local.rs:248:9
      tokio::coop::with_budget
             at /home/pstoev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/coop.rs:99:5
      tokio::coop::budget
             at /home/pstoev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/coop.rs:76:5
      tokio::park::thread::CachedParkThread::block_on
             at /home/pstoev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/park/thread.rs:263:31
  25: tokio::runtime::enter::Enter::block_on
             at /home/pstoev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/enter.rs:151:13
      tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/pstoev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/thread_pool/mod.rs:71:9
  26: tokio::runtime::Runtime::block_on
             at /home/pstoev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/mod.rs:452:43
  27: coord::coord::serve::{{closure}}::{{closure}}
             at src/coord/src/coord.rs:3056:9
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:125:18
  28: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/mod.rs:474:17
      <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:344:9
      std::panicking::try::do_call
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:379:40
      std::panicking::try
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:343:19
      std::panic::catch_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:431:14
      std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/mod.rs:473:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:227:5
  29: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
  30: start_thread
  31: clone
```

**Comment by wangandi** [comment]
@philip-stoev The crash is resulting from a type mismatch, likely because some prior transform simplified something without properly preserving the nullability of the type. What is the query that is causing the crash? Even if sending it through the psql client does not result in a crash, seeing what the query looks like unsimplified would help narrow down where the problem might be.

**Comment by philip-stoev** [comment]
For this query:

```
materialize=> EXPLAIN  SELECT l_suppkey  FROM lineitem  JOIN orders  ON ( l_orderkey  = o_orderkey  )  RIGHT  JOIN customer  ON ( o_custkey  = c_custkey  )  WHERE o_custkey  BETWEEN  20  AND  67  AND l_extendedprice  =  MOD ( o_totalprice  ,  5  )  AND l_extendedprice  BETWEEN  6201088  AND  212   ;
                                                              Optimized Plan                                                               
-------------------------------------------------------------------------------------------------------------------------------------------
 %0 =                                                                                                                                     +
 | Get materialize.public.lineitem (u36)                                                                                                  +
 | Filter (#5 <= 21200dec), (#5 >= 620108800dec)                                                                                          +
 | ArrangeBy (#0, #5)                                                                                                                     +
                                                                                                                                          +
 %1 =                                                                                                                                     +
 | Get materialize.public.orders (u32)                                                                                                    +
 | ArrangeBy (#1)                                                                                                                         +
                                                                                                                                          +
 %2 =                                                                                                                                     +
 | Get materialize.public.customer (u28)                                                                                                  +
 | ArrangeBy (#0)                                                                                                                         +
                                                                                                                                          +
 %3 =                                                                                                                                     +
 | Join %0 %1 %2 (= #0 #16) (= #5 (#19 % 500dec)) (= #17 #25)                                                                             +
 | | implementation = Differential %2.(#0) %1.(#1) %0.(#0, #5)                                                                            +
 | | demand = (#2, #5, #17, #19)                                                                                                          +
 | Filter (#5 <= 21200dec), (#17 <= 67), ((#19 % 500dec) <= 21200dec), (#5 >= 620108800dec), (#17 >= 20), ((#19 % 500dec) >= 620108800dec)+
 | Project (#2)                                                                                                                           +
 
```

The ```Filter``` below the join is much more complex in this branch as compared to the prior commit and duplicates conditions that are validated upstream (downstream) in the plan. In the prior commit, the Filter of the join is just this:

```
 | Filter (#17 <= 67), (#17 >= 20)                            +
```

**Review by philip-stoev — APPROVED** [review]
Quite a few plans were different during randomized testing, so it is weird that only a couple of queires changed in our tests. I guess this is yet another manifestation of the sympthom that we do not have enough tests to reliably trigger on any change in the code.

There were no wrong results. I visually examined a bazillion plans and put the ones that are obviously worse as comments. There were various other plans where I currently do not have the tools to evaluate if the plan regressed or improved, e.g. the column on ArrangeBy is different or some Filter has moved from one place in the plan to another.

**Comment by wangandi** [comment]
> The Filter below the join is much more complex in this branch as compared to the prior commit and duplicates conditions that are validated upstream (downstream) in the plan.

The duplicate condition is due to an interesting sequence of events:
1) First all the conditions get pushed down to each input. This is good.
```
%0 =
| Get ? (u2)
| Filter !(isnull(#0)), !(isnull(#5)), (#5 <= 21200dec), (#5 >= 620108800dec)

%1 =
| Get ? (u8)
| Filter !(isnull(#0)), !(isnull(#1)), !(isnull(#3)), (#1 <= 67), ((#3 % 500dec) <= 21200dec), (#1 >= 20), ((#3 % 500dec) >= 620108800dec)

%2 =
| Get ? (u4)
| Filter !(isnull(#0)), (#0 <= 67), (#0 >= 20)

%3 =
| Join %0 %1 %2 (= #0 #16) (= #5 (#19 % 500dec)) (= #17 #25)
| | implementation = Unimplemented
| Project (#2)
```
2) Then during join planning, some of the filters get lifted in order to use pre-existing arrangements.
```
%0 =
| Get ? (u2)
| Filter !(isnull(#0)), !(isnull(#5)), (#5 <= 21200dec), (#5 >= 620108800dec)
| ArrangeBy (#0, #5)

%1 =
| Get ? (u8)
| ArrangeBy (#1)

%2 =
| Get ? (u4)
| ArrangeBy (#0)

%3 =
| Join %0 %1 %2 (= #0 #16) (= #5 (#19 % 500dec)) (= #17 #25)
| | implementation = Differential %2.(#0) %1.(#1) %0.(#0, #5)
| Filter !(isnull(#16)), !(isnull(#17)), !(isnull(#19)), (#17 <= 67), ((#19 % 500dec) <= 21200dec), (#17 >= 20), ((#19 % 500dec) >= 620108800dec), !(isnull(#25)), (#25 <= 67), (#25 >= 20)
| Project (#2)
```
It is unnecessary for the filters `((#19 % 500dec) <= 21200dec)` and `((#19 % 500dec) >= 620108800dec)` to be around. I have filed issue #6746 on this.

3a) Our optimization stack needlessly runs twice, which is a known issue.
https://github.com/MaterializeInc/materialize/blob/761881ced18e55be2b15456e0bca825987e2c3df/src/transform/src/dataflow.rs#L145

This pushes the filters `((#19 % 500dec) <= 21200dec)` and `((#19 % 500dec) >= 620108800dec)` back down to all relevant inputs. Because the arrangements have already been locked in by join planning in the first round of optimization, the new filters don't get pushed down past the `ArrangeBy` operator, so they never get deduplicated.
```
%0 =
| Get ? (u2)
| Filter !(isnull(#0)), !(isnull(#5)), (#5 <= 21200dec), (#5 >= 620108800dec)
| ArrangeBy (#0, #5)
| Filter (#5 <= 21200dec), (#5 >= 620108800dec)

%1 =
| Get ? (u8)
| ArrangeBy (#1)
| Filter !(isnull(#1)), !(isnull(#3)), (#1 <= 67), ((#3 % 500dec) <= 21200dec), (#1 >= 20), ((#3 % 500dec) >= 620108800dec)

%2 =
| Get ? (u4)
| ArrangeBy (#0)
| Filter !(isnull(#0)), (#0 <= 67), (#0 >= 20)

%3 =
| Join %0 %1 %2 (= #0 #16) (= #5 (#19 % 500dec)) (= #17 #25)
| | implementation = Unimplemented
| Project (#2)
```

3b) Then during the second join planning, the pushed down filters get lifted back up again.
```
%0 =
| Get ? (u2)
| Filter !(isnull(#0)), !(isnull(#5)), (#5 <= 21200dec), (#5 >= 620108800dec)
| ArrangeBy (#0, #5)

%1 =
| Get ? (u8)
| ArrangeBy (#1)

%2 =
| Get ? (u4)
| ArrangeBy (#0)

%3 =
| Join %0 %1 %2 (= #0 #16) (= #5 (#19 % 500dec)) (= #17 #25)
| | implementation = Differential %2.(#0) %1.(#1) %0.(#0, #5)
| Filter (#5 <= 21200dec), (#5 >= 620108800dec), !(isnull(#17)), !(isnull(#19)), (#17 <= 67), ((#19 % 500dec) <= 21200dec), (#17 >= 20), ((#19 % 500dec) >= 620108800dec), !(isnull(#25)), (#25 <= 67), (#25 >= 20)
| Project (#2)
```

**Comment by wangandi** [comment]
> In this branch I am getting the crash above. It is reproducible 100% , but unfortunately only within the randomized test framework -- if I run the same queries through the psql client, I can not get it to crash. Would it be possible to debug and fix this based on the message below alone?

I take back my previous statement back regarding this crash. It seems that we are unnecessarily considering records not-unionable if their nullabilities are different. I have filed an issue about this: #6750

> There is an extra join in this branch for this query as compared to the prior commit.

This seems to be part of a general problem that `RedundantJoin` and `PredicatePushdown` work against each other, for which I have filed an issue here: #6748. I can, however, fix the particular extra join.

**Comment by wangandi** [comment]
Extra join has been fixed. Created issues for the other things that Philip noticed.

**Pull request merged**
