### PR TITLE
timestamp-oracle: trace timeline operations

### PR DESCRIPTION
**Pull request by mjibson**
We've observed `advance_timelines` take 2h. Adding traces here should help us understand what's going on.

Bump up the retry debug to an info so we get trace events and know how many retries there were.

### Motivation

  * This PR adds a feature that has not yet been specified.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - n/a

### CODE REVIEW

**Comment by mjibson** [comment]
Example trace on a personal stack:

image

**Review by aljoscha — APPROVED** [review]
Looks good! The `fallible_foo` methods already have debug tracing, maybe you also want to bump these to info?

**Review by aljoscha — APPROVED** [review]
Looks good! The `fallible_foo` methods already have debug tracing, maybe you also want to bump these to info?

**Comment by mjibson** [comment]
Changed the fallible_foo methods to info.

**Pull request merged**
