### PR TITLE
ct: add initial `mz_cluster_replica_metrics_history_ct` builtin

### PR DESCRIPTION
**Pull request by danhhz**
Incrementally roll out CTs by starting with a builtin responsible for the retention history of `mz_cluster_replica_metrics_history`. This is modeled as a CT that uses it as an input to maintain a truncated `mz_cluster_replica_metrics_history_ct` object.

Put the creation of this CT on boot behind a dyncfg, so we can roll it out slowly and turn it off if anything surprising happens. This means that we maintain `mz_cluster_replica_metrics_history_ct` but nothing reads it yet.

We'll want to do an audit of `TODO(ct)`s before turning this on anywhere important.

Touches materializeinc/database-issues#8427

### Motivation

  * This PR adds a known-desirable feature.

### Tips for reviewer

Any thoughts on where to put the dyncfg?

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

**Review by ParkMyCar — APPROVED** [review]
Other than the dyncfg question this looks good! Woohoo!

**Comment by danhhz** [comment]
@jkosh44 Mind reviewing the last commit? I couldn't make the `apply_updates_inner` approach work that we discussed yesterday. It ended up hitting another panic in `add_new_remove_old_builtin_items_migration`

**Comment by jkosh44** [comment]
> @jkosh44 Mind reviewing the last commit? I couldn't make the `apply_updates_inner` approach work that we discussed yesterday. It ended up hitting another panic in `add_new_remove_old_builtin_items_migration`

One consequence of this approach is that if you do something like the following:

1. Start MZ with continual tasks turned on.
2. Disable continual tasks.
3. Restart MZ.

Then in step (3) we'll remove the continual task from the durable catalog. IMO that's fine because we'll just add it back in whenever we re-enable it. It's probably worth running through manually to check that nothing explodes though.

Assuming you're OK with that, then LGTM.

**Comment by danhhz** [comment]
Yeah, that sounds like the ideal behavior to me, actually. I'll run through it locally and make sure that everything works, thanks!

**Comment by danhhz** [comment]
TFTRs!

**Pull request merged**
