### PR TITLE
tests: mysql-cdc: transactions

### PR DESCRIPTION
**Pull request by nrainer-materialize**
Add tests with transactions as requested in https://github.com/MaterializeInc/materialize/pull/26223.

### CODE REVIEW

**Review by rjobanp — APPROVED** [review]
this is great, thanks for whipping it up so quickly!

**Review by def- — APPROVED** [review]
Do we have these kinds of tests in pg-cdc or should we port that over to pg-cdc too?

**Comment by nrainer-materialize** [comment]
> Do we have these kinds of tests in pg-cdc or should we port that over to pg-cdc too?

We don't, I can port them.

**Comment by def-** [comment]
Thanks! Seems like we don't have much with transactions:
```
$ git grep BEGIN **/pg-cdc
test/pg-cdc/correctness-property-2.td:> BEGIN
test/pg-cdc/pg-cdc.td:BEGIN;
```

**Pull request merged**
