### PR TITLE
sql: parsing of ALTER MATERIALIZED VIEW RETAIN HISTORY

### PR DESCRIPTION
**Pull request by mjibson**
See https://github.com/MaterializeInc/materialize/issues/16701

### Motivation

  * This PR adds a known-desirable feature.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - n/a

### CODE REVIEW

**Review by ParkMyCar — APPROVED** [review]
exciting!

**Comment by nrainer-materialize** [comment]
Please notify QA when changes are ready and the test pipeline passes 😀

**Comment by mjibson** [comment]
This is ready for logic testing! I added a not useful test to mzcompose as a starter point.

**Comment by mjibson** [comment]
Edit: this PR has been changed to be just the parsing changes previously approved. Will merge this then open a new PR with the rest for testing.

**Pull request merged**
