### PR TITLE
Updating docs to mention `hint` could be present

### PR DESCRIPTION
**Pull request by moulimukherjee**
Updating the docs to mention that `hint` could be populated in certain error scenarios. 
(Currently it's only populated for one scenario though https://github.com/MaterializeInc/materialize/pull/18009)

### Motivation
A follow up from https://github.com/MaterializeInc/materialize/pull/18009#discussion_r1136001186

### Tips for reviewer
Happy to update the wording!

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by guswynn** [comment]
@morsapaes, Mouli and I have another docs question: if we have an error message that we want to elaborate on in the docs (say that a certain error can be troubleshooted many different ways), where can we add a troubleshooting page we can link to from the error the user sees in sql?

**Comment by tr0njavolta** [comment]
Hi @guswynn, I would advise against creating a new page for troubleshooting and would recommend either:

* A subheader under the object with an anchor link in the error message

```
### `mz_sink_status_history`
...
#### Error Troubleshooting
```

* A new H2 section to the bottom of the file with an anchor link in the error message

```
### `mz_sink_status_history`
...

## Error Troubleshooting

```

If the troubleshooting options take up a significant amount of screen real-estate or you intend to add error troubleshooting for multiple objects, I would opt for the new section. 

@morsapaes, feel free to weigh in since the above is an opinion and I may not have a good grasp on how questions like this have been handled in the past. Thanks!

**Comment by guswynn** [comment]
@tr0njavolta so we'd link to that sub-section from the error?

**Review by morsapaes — APPROVED** [review]
Thanks for covering the docs changes, @moulimukherjee! 🙇‍♀️ The `_statuses` views are based on these tables, so the edit also applies there. Pushed a commit to save you the trouble, and also took the chance to patch a missing link!

@guswynn, your question goes back to the discussion in #16937, where we ended up transferring troubleshooting details to the existing [Troubleshooting](https://materialize.com/docs/ops/troubleshooting/) page. 

From [this commit](https://github.com/MaterializeInc/materialize/pull/16937/commits/490b006081abec4a019453b02c6f24b67a4869ac):

> We've kept the system catalog documentation as reference-y as possible:
focused on hard facts, rather than advice. This commit pares down to
`mz_source_statistics` documentation to follow that philosophy.  The
removed advice is great, and will be reintroduced elsewhere in a future
commit.

So, troubleshooting-specific advice should be added to the guide in the right context, rather than buried in reference documentation. 

@tr0njavolta, there's definitely room to improve how we organize all this information; it'd be great if we could make catalog documentation more useful (_e.g._ group system objects according to their purpose rather than present them as a huge list + add example queries on how to combine them in useful ways ([example](https://materialize.com/docs/releases/v0.39/))). The same goes for the Troubleshooting page, which has grown wild as we extend system observability. It might be more productive to include troubleshooting directly in the source and sink pages, for example.

**Pull request merged**
