### PR TITLE
adapter: remove the old index optimization paths

### PR DESCRIPTION
**Pull request by teskje**
This PR removes the old index optimization paths, leaving only the new ones using the unified optmizer API. Dead code is pruned at the same time.

### Motivation

   * This PR refactors existing code.

Remove the old code after the new one baked for one week in production as prescribed in the design doc from https://github.com/MaterializeInc/materialize/pull/20569.

### Tips for reviewer

@aalexandrov Apologies if you have this already lined up somewhere! I'm pushing this because it simplifies working on a fix on https://github.com/MaterializeInc/cloud/issues/7998. 

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - N/A

### CODE REVIEW

**Review by philip-stoev — APPROVED** [review]
@aalexandrov I believe the entire CI is running with the new code paths enabled, right? If so, no action needed from the QA team, this has been beaten enough.

**Comment by aalexandrov** [comment]
> I believe the entire CI is running with the new code paths enabled, right?

Yes, because the `default` value of `enable_unified_optimizer_api` in `feature_flags!` is `true`.

**Review by aalexandrov — APPROVED** [review]
Can you also remove the last paragraph from the comment on top of `async fn explain_create_index_optimizer_pipeline` in `inner.rs`?

**Review by ParkMyCar — APPROVED** [review]

**Comment by teskje** [comment]
TFTRs!

**Pull request merged**
