### PR TITLE
Disable column knowledge

### PR DESCRIPTION
**Pull request by frankmcsherry**
This PR disables the `column_knowledge.rs` transformation, which propagated information "known" to be true about columns, e.g. non-nullability and equality to constant values. Because there are no rules about filter movement, almost all of these rules are unsound: filters might temporarily be before some expression, but then move after them once the expression is simplified. An expression surrounding a join could use the implicit `col1 = col2` filter of the join, but then simplify and be pushed through the join. In each case, expressions like `if <check> then <something scary>` could go from never-erroring to potentially erroring.

This PR is first to check the fallout in plans, and see if any of the good things that we lose are things that we expect to work in the first place, and perhaps why.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/6141)

### CODE REVIEW

**Comment by frankmcsherry** [comment]
Another option is to move this sort of transformation to an optimization phase that no longer moves expressions around, and instead does in-place simplification based on the presented structure. The `transform` crate doesn't have this level of discipline at the moment, but it probably should.

**Comment by philip-stoev** [comment]
@frankmcsherry I will give this a try tomorrow with a randomized workload.

**Comment by frankmcsherry** [comment]
Sweet! For bonus points, we should be able to figure out an incorrect query that is currently wrong on `main`.

**Comment by frankmcsherry** [comment]
The changes seem to be pretty much just `IsNull(...)` filter predicates, all pretty local. There is only one place that I saw where a new operator existed, and it looked like probably because some additional tests meant that a column had to be held longer, and so some output wasn't good enough idk.

I think we could consider disabling this, and following with a clearer separation into logical and physical optimization (or "SQL" and "DD" optimization, where the latter happens only just before deployment).

**Comment by philip-stoev** [comment]
> The changes seem to be pretty much just IsNull(...) filter predicates, all pretty local

I guess this is what you meant, right?

```
materialize=> EXPLAIN  SELECT * FROM t2  AS a1  JOIN t1  AS a2  ON ( a1 .f1  = a2 .f2  )   ;
                Optimized Plan                
----------------------------------------------
 %0 =                                        +
 | Get materialize.public.t2 (u13)           +
 | ArrangeBy (#0)                            +
                                             +
 %1 =                                        +
 | Get materialize.public.t1 (u9)            +
                                             +
 %2 =                                        +
 | Join %0 %1 (= #0 #3)                      +
 | | implementation = Differential %1 %0.(#0)+
 | | demand = (#0..#2)                       +
 | Filter !(isnull(#0))                      + <- extra Filter predicate in this branch
 | Project (#0..#2, #0)                      +
```

a2.f2 is declared as ```NOT NULL``` and the commit prior to this branch does not have that ```Filter``` (But on the other hand, various queries in the prior commit *do* have such a Filter even though it is an inner join and the ON condition would never evaluate to TRUE if any argument is a ```NULL``` )

**Comment by philip-stoev** [comment]
@frankmcsherry here is a more interesting one. In this branch, this predicate is not judged to be impossible to satisfy, where the prior commit is able to determine that:

```
CREATE TABLE t1 (f1 DOUBLE PRECISION, f2 DOUBLE PRECISION NOT NULL);
CREATE TABLE t2 (f1 DOUBLE PRECISION, f2 DOUBLE PRECISION NOT NULL);
EXPLAIN  SELECT a2  FROM t1  AS a1  RIGHT  JOIN t2  AS a2  ON a1 .f1  IS NOT NULL  WHERE a1 .f1  > a1 .f1  AND a1 .f1  IS  NULL  ;
                Optimized Plan                 
-----------------------------------------------
 %0 =                                         +
 | Get materialize.public.t1 (u33)            +
 | Filter !(isnull(#0)), isnull(#0), (#0 > #0)+
 | ArrangeBy ()                               +
                                              +
 %1 =                                         +
 | Get materialize.public.t2 (u35)            +
                                              +
 %2 =                                         +
 | Join %0 %1                                 +
 | | implementation = Differential %1 %0.()   +
 | | demand = (#2, #3)                        +
 | Map record_create(#2, #3)                  +
 | Project (#4)                               +
```

At the same time , even the prior commit has difficulty detecting other, even simpler, impossible conditions (e.g. ones not involving a join at all).

**Comment by philip-stoev** [comment]
This branch does a group by over two columns, but the prior commit groups by a column and a constant:

```
materialize=> explain SELECT * FROM t2  AS a1  RIGHT  JOIN t2  AS a2  ON  NULL  WHERE  0  = a2 .f2   ;
          Optimized Plan           
-----------------------------------
 %0 =                             +
 | Get materialize.public.t2 (u41)+
 | Filter (#1 = 0)                +
 | Distinct group=(#0, #1)        + <- the prior commit has group=(#0, 0) here
 | ArrangeBy (#0, #1)             +
                                  +
 %1 =                             +
 | Get materialize.public.t2 (u41)+
 | ArrangeBy (#1, #0)             +
                                  +
 %2 =                             +
 | Join %0 %1 (= #0 #2) (= #1 #3) +
 | | implementation = DeltaQuery  +
 | |   delta %0 %1.(#1, #0)       +
 | |   delta %1 %0.(#0, #1)       +
 | | demand = (#0, #1)            +
 | Filter (#1 = 0)                +
 | Map null, null                 +
 | Project (#4, #5, #0, #1)       +
 
(1 row)
```

Since there is a Filter against the same constant just above the group I would say the two plans are functionally equivalent (memory and processing-wise).

**Comment by philip-stoev** [comment]
How expensive is ```record_create``` ?. This branch does it for the following truly degenerate query:

```
materialize=> explain SELECT  a2 FROM t1  LEFT  JOIN t1  AS a2  ON  FALSE  ;
             Optimized Plan              
-----------------------------------------
 %0 =                                   +
 | Get materialize.public.t1 (u37)      +
 | Map null, null, record_create(#2, #3)+
 | Project (#4)
 ```
The prior commit has:

```
materialize=> explain SELECT  a2 FROM t1  LEFT  JOIN t1  AS a2  ON  FALSE  ;
          Optimized Plan           
-----------------------------------
 %0 =                             +
 | Get materialize.public.t1 (u29)+
 | Map null, null, [null, null]   +
 | Project (#4)                   +
```

**Comment by philip-stoev** [comment]
This semi-plausible query has a full-blown outer join plan in this branch, but the prior commit is able to reduce it to a simple join:

```
materialize=> EXPLAIN  SELECT  FROM t1  AS a1  LEFT  JOIN t1  ON ( a1 .f2  = a1 .f1  )  WHERE   a1 .f1  IS  NULL   ;
                  Optimized Plan                  
--------------------------------------------------
 %0 =                                            +
 | Get materialize.public.t1 (u37)               +
 | Filter !(isnull(#0)), (#0 = #1)               +
 | ArrangeBy ()                                  +
                                                 +
 %1 =                                            +
 | Get materialize.public.t1 (u37)               +
                                                 +
 %2 = Let l0 =                                   +
 | Join %0 %1                                    +
 | | implementation = Differential %1 %0.()      +
 | | demand = (#0, #1)                           +
                                                 +
 %3 =                                            +
 | Get %2 (l0)                                   +
 | Filter isnull(#0)                             +
                                                 +
 %4 =                                            +
 | Get %2 (l0)                                   +
 | Filter isnull(#0)                             +
 | Distinct group=(#0, #1)                       +
 | Negate                                        +
                                                 +
 %5 =                                            +
 | Get materialize.public.t1 (u37)               +
 | Filter isnull(#0)                             +
 | Distinct group=(#0, #1)                       +
                                                 +
 %6 =                                            +
 | Union %4 %5                                   +
                                                 +
 %7 =                                            +
 | Get materialize.public.t1 (u37)               +
 | ArrangeBy (#1, #0)                            +
                                                 +
 %8 =                                            +
 | Join %6 %7 (= #0 #2) (= #1 #3)                +
 | | implementation = Differential %6 %7.(#1, #0)+
 | | demand = (#0)                               +
 | Filter isnull(#0)                             +
 | Map null, null                                +
 | Project (#0, #1, #4, #5)                      +
                                                 +
 %9 =                                            +
 | Union %3 %8                                   +
 | Project ()                                    +
```

**Comment by frankmcsherry** [comment]
> How expensive is `record_create` ?. This branch does it for the following truly degenerate query:

I have no idea what `record_create` is. :) Are the inputs tables, or views that contain some other logic in them?

**Comment by philip-stoev** [comment]
@frankmcsherry all inputs are tables in those examples.

**Comment by frankmcsherry** [comment]
> `EXPLAIN  SELECT * FROM t2  AS a1  JOIN t1  AS a2  ON ( a1 .f1  = a2 .f2  )   ;`

This case is unable to determine that `f2` being non-null means that `f1` will be non-null, because that join equality constraint *could* move arbitrarily. There surely is some reasoning that would allow us to conclude that, but it is not strictly speaking correct to do what we did previously and simplify the predicate. For example, it might be safe to always do "simplify, but not through `If` expressions".

> EXPLAIN  SELECT a2  FROM t1  AS a1  RIGHT  JOIN t2  AS a2  ON a1 .f1  IS NOT NULL  WHERE a1 .f1  > a1 .f1  AND a1 .f1  IS  NULL  ;

Same thing, ish. The `IS NULL` constraint could move around arbitrarily, and so making the local simplification of "not possible" could be incorrect if we are allow to move that condition around afterwards. At least, we don't reason about what would make it correct (e.g. perhaps, "if the set of records to which we apply expressions does not increase, is still safe", but idk at the moment).

> others, similar I think

I think one conclusion here is that we should not just drop `column_knowledge.rs`, but think about how to use it correctly. For example, only applying it, and perhaps other sensitive transformations, just prior to rendering.

**Pull request closed without merging**
