### PR TITLE
adapter: correctly compute dependencies for materialized views

### LINKED ISSUE #20315: `DROP VIEW` can cause catalog corruption
### What version of Materialize are you using?

v0.58.0

### What is the issue?

The adapter does not track all view dependencies correctly, which means that a `DROP VIEW` statement can cause catalog corruption by dropping a view that is still depended upon by other views. This was the root cause of incident 56.

Here is a very simple reproduction, courtesy of @jkosh44:

```sql
CREATE VIEW v AS SELECT 1 AS c;
CREATE MATERIALIZED VIEW mv AS SELECT * FROM v WHERE c IS NULL;
DROP VIEW v;
```

The bug was introduced by https://github.com/MaterializeInc/materialize/pull/19648 in the service of fixing another bug. Current hypothesis is that we should essentially revert #19648 and instead fix the root cause (https://github.com/MaterializeInc/materialize/issues/19080)—which we currently believe is that the SQL planner does not correctly report dependencies introduced by a function implemented with `sql_op!`.

Details in the (internal) incident 56 tracking issue: https://github.com/MaterializeInc/cloud/issues/6814

### PR DESCRIPTION
**Pull request by benesch**
This commit fixes a bug introduced by #19648, in which we stopped tracking the dependencies of a materialized view correctly.

The root cause was that there are two notions of dependencies tracked by the system:

  1. An object required while planning an `mz_sql_parser::ast::Statement`.
  2. An object required to determine the timestamp of a `MirRelationExpr` in a plan.

Pre PR #19648, the code used (1) in a place where (2) was expected. Post PR #19648, the code used (2) in a place where (1) was expected. This commit uses (1) where (1) is expected and (2) where (2) is expected.

A future commit will make this easier to understand.

Fix #20315.

### Motivation

  * This PR fixes a recognized bug.

### Tips for reviewer

Future commit coming with clarity-enhancing improvements.

@philip-stoev perhaps you would like to throw some more test cases at this PR?

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - n/a

### CODE REVIEW

**Comment by philip-stoev** [comment]
Yes, I am on it, thanks.

**Comment by philip-stoev** [comment]
Item No 1. This may be outside of the scope of this PR, but still it seems that the "same timedomain" protection does not cover tables that were optimized away. I took the SLT test from `github-8241.slt` and modified it to use a view that is folded to a constant:

```
statement ok
CREATE TABLE t1 (f1 INTEGER, f2 INTEGER);

statement ok
CREATE INDEX i1 ON t1 (f2);

statement ok
CREATE VIEW v2 AS SELECT * FROM t1 WHERE FALSE;

simple conn=conn1
BEGIN;
SELECT * FROM v2;
----
COMPLETE 0
COMPLETE 0

statement ok
CREATE INDEX i2 ON t1 (f2);

simple conn=conn1
SELECT * FROM v2;
----
```
The final statement completes successfully rather than erroring out, as it does in `github-8241.slt`

**Review by philip-stoev — APPROVED** [review]
I pushed a bunch of tests , please take those along for the ride. The protection works as expected regardless why a particular dependency was optimized away.

**Review by jkosh44 — APPROVED** [review]
LGTM

**Comment by benesch** [comment]
Thank you both! @philip-stoev, I'm going to move your additional test to #20319.

**Pull request merged**
