### PR TITLE
dependencies: handle dependency reported as unused

### PR DESCRIPTION
**Pull request by nrainer-materialize**
Trying to fix https://buildkite.com/materialize/nightlies/builds/3590#018a403d-444e-4a2d-a6ff-45a5ae370067.

[Removing the dependency failed,](https://buildkite.com/materialize/tests/builds/62594#018a408a-14df-4a08-9c0d-262db38ee732) so I assume this is a false positive.

### CODE REVIEW

**Comment by joacoc** [comment]
@nrainer-materialize You can safely remove `postgres-protocol` from the dependencies. I'm also identifying a few more that are now obsolete. I will do a clean up after this PR gets merged and the issue fixed.

**Comment by nrainer-materialize** [comment]
> @nrainer-materialize You can safely remove `postgres-protocol` from the dependencies. I'm also identifying a few more that are now obsolete. I will do a clean up after this PR gets merged and the issue fixed.

Well, when removing the dependency with https://github.com/MaterializeInc/materialize/pull/21442/commits/d7e4e6df2e064e4c9cccb17982e6d928a4bb5b83, I got a [build error in "Lint Dependencies".](https://buildkite.com/materialize/tests/builds/62594)

**Comment by joacoc** [comment]
@nrainer-materialize Oh, I see. Is it possible that only the dependency in `Cargo.lock` is removed by the commit https://github.com/MaterializeInc/materialize/commit/d7e4e6df2e064e4c9cccb17982e6d928a4bb5b83, while the dependency in `src/mz/Cargo.toml` remains? (Causing the lint problem to arise)

**Comment by nrainer-materialize** [comment]
> @nrainer-materialize Oh, I see. Is it possible that only the dependency in `Cargo.lock` is removed by the commit [d7e4e6d](https://github.com/MaterializeInc/materialize/commit/d7e4e6df2e064e4c9cccb17982e6d928a4bb5b83), while the dependency in `src/mz/Cargo.toml` remains? (Causing the lint problem to arise)

Absolutely. Then, let me try to remove that as well. => https://github.com/MaterializeInc/materialize/pull/21442/commits/353628e62dd5b41e22174bbe7be66925783b86de with Nightly https://buildkite.com/materialize/nightlies/builds/3604

**Review by joacoc — APPROVED** [review]

**Pull request merged**
