### PR TITLE
fix typo in tb README

### PR DESCRIPTION
**Pull request by shamrin**
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5354)

### CODE REVIEW

**Comment by shamrin** [comment]
I don't want to sign CLA for such a trivial change. Consider this PR as a bug report.

**Comment by cirego** [comment]
Hi @shamrin, thanks for the bug report! I'll go ahead and get this merged!

**Comment by shamrin** [comment]
@cirego thank you!

By the way, have you considered releasing `tb` with a more permissive license? It seems to be independent from the rest of Materialize and should be very useful on its own.

**Comment by cirego** [comment]
> @cirego thank you!
> 
> By the way, have you considered releasing `tb` with a more permissive license? It seems to be independent from the rest of Materialize and should be very useful on its own.

Hi @shamrin, glad to help and thanks for reporting this!

Currently, `tb` falls under the "prototype" category and has not seen much development recently (but that could change based on customer requests!). What license would you prefer to see for `tb`? Our BSL should be fairly permissive for most use cases.

**Comment by shamrin** [comment]
@cirego Thank you for your answer! I would prefer Apache or MIT license for `tb`. BSL is nice, but it prevents `tb` from being used in some places. I'm speculating here, but it probably couldn't be part of Debezium distribution.

Personally, I would like to play with `tb` to learn about Change Data Capture as part of the little experiment I'm doing. I don't have patience to set up Kafka :) I don't know yet what direction my experiment would go. It could be anything from traditional open source project, to a commercial product. Some of these directions are unfortunately not compatible with BSL.

`tb` is small and probably easy to redo from scratch if necessary. But it still seems wasteful, given that `tb` is nowhere near the core of Materialize awesome magic :)

**Pull request closed without merging**
