### PR TITLE
docs: add minimum required Postgres version for sources

### PR DESCRIPTION
**Pull request by JLDLaughlin**
See the [short Slack chat](https://materializeinc.slack.com/archives/CPNFV9CVB/p1624998978020600) for confirmation.

### CODE REVIEW

**Review by uce — COMMENTED** [review]
LGTM.

Note that the `pg-cdc` testdrive tests only run with Postgres 11. We might want to run them with multiple versions or the minimum supported version.

**Comment by JLDLaughlin** [comment]
Great point, @uce! I've updated the Postgres versions for the `pg-cdc` tests... let's see if they pass!

**Comment by JLDLaughlin** [comment]
So interestingly Postgres 10 doesn't have a `postgresql.conf` file automatically in `$PGDATA`, causing our tests to fail:
```
jessicalaughlin@Jessicas-MacBook-Pro ~ % docker run -it postgres:10 /bin/bash
root@1daede1fefa9:/# echo $PGDATA
/var/lib/postgresql/data
root@1daede1fefa9:/# cd /var/lib/postgresql/data
root@1daede1fefa9:/var/lib/postgresql/data# ls
root@1daede1fefa9:/var/lib/postgresql/data#
```

**Comment by JLDLaughlin** [comment]
So interestingly our `pg-cdc` tests are failing because switching from Postgres 11.4 -> 10 breaks how we initialize the Postgres container with certs. Using Postgres 11.4:
```
jessicalaughlin@Jessicas-MacBook-Pro ~ % docker logs pg-cdc_postgres_1
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default timezone ... Etc/UTC
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok

syncing data to disk ... ok
WARNING: enabling "trust" authentication for local connections

You can change this by editing pg_hba.conf or using the option -A, or
Success. You can now start the database server using:
--auth-local and --auth-host, the next time you run initdb.

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2021-06-30 21:37:51.802 UTC [44] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-06-30 21:37:51.814 UTC [45] LOG:  database system was shut down at 2021-06-30 21:37:51 UTC
2021-06-30 21:37:51.819 UTC [44] LOG:  database system is ready to accept connections
 done
server started

/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/setup-postgres.sh
```

Using Postgres 10:
```
jessicalaughlin@Jessicas-MacBook-Pro pg-cdc % docker logs pg-cdc_postgres_1
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default timezone ... Etc/UTC
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
syncing data to disk ... ok

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2021-06-30 21:41:10.033 UTC [47] FATAL:  could not load server certificate file "server.crt": No such file or directory
2021-06-30 21:41:10.033 UTC [47] LOG:  database system is shut down
```

**Review by msudberg — APPROVED** [review]

**Comment by uce** [comment]
@JLDLaughlin Ha! I was really confused about this and it turns out that the Docker image we currently use `postgres:11.4` is quite old and our configuration does not work with newer image versions (including a more recent `postgres:11`).

Our configuration via the `-c` options in `mzcompose.yml` assumes that the initialization in `setup-postgres.sh` was executed which is not true anymore with newer images (which results in us enabling ssl via `-c ssl=on` but having no cert in place).

**Comment by uce** [comment]
Whops! This part of the message got somehow lost:

---

Let me quickly try to fix it and post a patch.

**Comment by uce** [comment]
a54e7c8 addresses the Postgres setup by moving everything into the Docker image. I've kept the base image at `postgres:11`, because tests fail with `postgres:10`.

Here's the test output with `postgres:10`: [pg10.txt](https://github.com/MaterializeInc/materialize/files/6757043/pg10.txt)

**Comment by JLDLaughlin** [comment]
Thanks @uce ! It turns out [`TRUNCATE` commands aren't replicated](https://www.postgresql.org/docs/10/logical-replication-restrictions.html) in Postgres 10. I've updated the test and added a note to the docs.

**Review by philip-stoev — APPROVED** [review]

**Pull request merged**
