### PR TITLE
Add more than one index per collection

### PR DESCRIPTION
**Pull request by frankmcsherry**
Mysteriously, we have perhaps for some time only ever imported one index for each collection. It's hard to imagine, but certainly *at the moment* we only import one index for each collection. This means that e.g. delta joins would form their own arrangements privately, at some cost. This has the potential to substantially reduce the memory and compute costs for these queries.

### Tips for reviewer

@umanwizard I'm trying to grok where we should have panicked / `error!`d / etc when it turned out we were not provided the indexes we were promised. Any thoughts? I didn't do that checking here, just fixed the index addition.

### Testing

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Review by benesch — APPROVED** [review]
Ty!

**Comment by frankmcsherry** [comment]
Evidence. On main TPCH Q8 (an eight-way delta join) the shipped command looks like
Screen Shot 2022-03-07 at 19 22 10

whereas with the PR it looks like
Screen Shot 2022-03-07 at 19 22 17

**Comment by umanwizard** [comment]
LGTM. Feel free to land, but assigning to myself to check how this wasn't showing up in tests; it certainly should have unless I'm confused.

**Comment by frankmcsherry** [comment]
I took some casual measurements, TPCH Q1-10, on this PR and main, and saw (not scientifically):
```
    PR        main      delta join
6076.880    6063.932    NA
  48.509     366.814    YES
2257.223    2664.062    YES
 915.962     964.655    YES
2180.140    2652.684    NO
 397.282     490.965    NA
6870.211    7311.583    YES
5493.056    5888.107    YES
8956.189    7597.483    YES
2374.142    2977.001    YES
```
The Q2 change is great and makes sense. The others are middling, which might mean that much of the work is actually munching data (or that we have poor join orders). The regression for Q9 could be a flake, but the slow time for Q2 on main is not (at least, it repeats).

**Pull request merged**
