### PR TITLE
Turn off stats by default (hopefully temporarily)

### PR DESCRIPTION
**Pull request by umanwizard**
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/6312)

### CODE REVIEW

**Review by cirego — COMMENTED** [review]
Thanks for posting this PR! A heads up, a number of testdrive test cases are going to start failing, as well as a test case in catalog/compat.

**Review by benesch — APPROVED** [review]
LGTM but can you file a tracking issue for this?

**Comment by umanwizard** [comment]
Yes @benesch I'm in the process of doing so now.

@cirego that'd be great, if you already know how to fix the failing tests off the top of your head feel free to take it over.

**Comment by umanwizard** [comment]
Issue filed: #6313

**Comment by cirego** [comment]
> Yes @benesch I'm in the process of doing so now.
> 
> @cirego that'd be great, if you already know how to fix the failing tests off the top of your head feel free to take it over.

I pushed a commit that should fixup all of the tests. Will watch the results and see if I missed anything.

**Comment by umanwizard** [comment]
let's hold off on landing this because I think I might have a fix for the underlying issue

**Comment by umanwizard** [comment]
@cirego #6315 seems to be the proper fix. Closing this out -- sorry for the wasted effort on your part.

**Comment by cirego** [comment]
> @cirego #6315 seems to be the proper fix. Closing this out -- sorry for the wasted effort on your part.

No need to apologize -- I'm glad we found the underlying issue!

**Pull request closed without merging**
