### PR TITLE
storage,test: verify that broker/schema-registry errors are reported on source creation

### LINKED ISSUE #4607: dataflow: invalid kafka sources should error out at creation time
Currently, it looks like materialize allows you to create a source without validating the source ( as in IP address, file location etc). 

If we are able to validate the source at create time, it would be helpful in preventing other problems down the line. This would be helpful for developers to catch problems at the onset.

For example - Kafka source with a broken IP address - selecting from source returns no errors. Here the IP address is not valid. There is no such host.

materialize=> CREATE SOURCE "materialize"."public"."jtest2" FROM KAFKA BROKER '192.168.1.252:9092' TOPIC 'user_behavior' FORMAT BYTES;
CREATE SOURCE

materialize=> select * from jtest2 limit 10 as of now();
 data | mz_offset 
------+-----------
(0 rows)

It was surprising that it did not error out. In my experience with other similar products, the engine rejects a source if not accessible. This helps correct the problem during create time.

With a csv source, the error was different -

Broken source does not  report where/what/why it is broken

materialize=> select * from category as of now();
ERROR:  Source error: File IO: Is a directory (os error 21)

Both the cases, I was able to create the source without any issues. 

@rjnn

### PR DESCRIPTION
**Pull request by aljoscha**
### Motivation

Adds some minimal test coverage that locks our current behaviour in place.

Closes #4607 

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by philip-stoev — COMMENTED** [review]
Thank you. What about authentication errors? At what stage are those expected to be caught?

**Comment by aljoscha** [comment]
I think at the same state. Do we have any tests that have authenticated brokers/schema registry?

**Comment by aljoscha** [comment]
There are some tests in the `kafka-ssl`/`kafka-sasl` that test errors with certificates, at least.

**Comment by aljoscha** [comment]
Merging this one for now. The point was to add basic tests that ensure the existence of an early feedback/error reporting hook. There are also some pre-existing tests in the `kafka-ssl`/`kafka-sasl` tests, that test specific scenarios of authentication failures. But we can expand these if need be. We probably will never cover all of these. 🙈

**Pull request merged**
