### PR TITLE
ci: annotate-errors as mzcompose

### PR DESCRIPTION
**Pull request by nrainer-materialize**
This allows to have a `Composition` in annotate-errors, which is needed to fetch the cloud's host name (for uploading results to the test-analytics database).

### Demo
https://buildkite.com/materialize/test/builds?branch=nrainer-materialize%3Aci%2Fannotations-as-mzcompose-demo

### CODE REVIEW

**Comment by nrainer-materialize** [comment]
@def-: After changing it to mzcompose, I [got the error](https://buildkite.com/materialize/test/builds/83393) that the `buildkite-agent` cannot be invoked.

```
PermissionError: [Errno 13] Permission denied: 'buildkite-agent'
202 {"id":"6389f2fb-391c-4898-acc7-cd2cbebfbf9f","run_id":"943d5fd0-c408-8ec5-9138-b0336dd59415","queued":1,"skipped":0,"errors":[],"run_url":"https://buildkite.com/organizations/materialize/analytics/suites/mzcompose/runs/943d5fd0-c408-8ec5-9138-b0336dd59415"}
```

Any ideas?

**Comment by def-** [comment]
I see, didn't think about that before. I thought the reason is that we use `bin/ci-builder`, but locally `bin/ci-builder run stable buildkite-agent` works fine. Another idea: Try invoking /usr/local/bin/buildkite-agent (with the full path), maybe that works.

Another problem we might run into is that not all environment variables required for buildkite-agent might get passed through in bin/ci-builder, those could be extended. This is all a bit finicky.

**Comment by nrainer-materialize** [comment]
> Another idea: Try invoking /usr/local/bin/buildkite-agent (with the full path), maybe that works.

This does unfortunately not solve the issue: https://buildkite.com/materialize/test/builds/83480#019000f6-0951-4db5-8a37-822bbb3e6433

Do you have another idea? If not, should we consider running mzcompose just for fetching the cloud hostname and then continue with the original script?

**Comment by def-** [comment]
That's a bit awkward, but ok. Currently I don't have another idea of why it fails.

**Pull request closed without merging**
