### PR TITLE
Arc cached plans in the catalog

### PR DESCRIPTION
**Pull request by antiguru**
Most of the cost of cloning the catalog come from cloning the HIR and MIR
plans for (materialized) views. To avoid the cost, we wrap them in an Arc.

Part of #28720.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

**Review by jkosh44 — APPROVED** [review]
LGTM

As an aside, is there any indication of where/why we are cloning the catalog? My understanding is that we're only meant to clone the catalog for concurrent DDL, which I'd assume is not a very common workload. However, I've found many instances where we're accidentally cloning the catalog because we're holding on to a reference to an `Arc` that we thought we'd dropped. It can be useful to find those places and eliminate the clones all together.

**Comment by antiguru** [comment]
> As an aside, is there any indication of where/why we are cloning the catalog? My understanding is that we're only meant to clone the catalog for concurrent DDL, which I'd assume is not a very common workload. However, I've found many instances where we're accidentally cloning the catalog because we're holding on to a reference to an Arc that we thought we'd dropped. It can be useful to find those places and eliminate the clones all together.

I've observed most of the clones in `handle_startup`, which needs to write the catalog. This is in some sense an artifact of the benchmark, which creates additional connections if there's more work that can be handled by the current connections. I think what happens is that there are many concurrent requests that have a pointer to the catalog, in which case each new connection needs to clone the catalog. For handling peeks, we pass an optimizer around, which has a `Arc<Catalog>`, so as long as there is any outstanding peek, a new connection needs to clone the catalog.

**Comment by jkosh44** [comment]
> I've observed most of the clones in `handle_startup`, which needs to write the catalog. This is in some sense an artifact of the benchmark, which creates additional connections if there's more work that can be handled by the current connections. I think what happens is that there are many concurrent requests that have a pointer to the catalog, in which case each new connection needs to clone the catalog. For handling peeks, we pass an optimizer around, which has a `Arc<Catalog>`, so as long as there is any outstanding peek, a new connection needs to clone the catalog.

Ah right, the temporary schemas. For future work, we might want to consider moving the temporary schema and items out of the catalog and maybe into the session itself or into something outside of `Catalog`. They are only visible to a single session so it feels a little wasteful to store them in this massively shared object. Then modifying the temporary objects in memory won't cause any unnecessary clones.

**Comment by ggevay** [comment]
> For handling peeks, we pass an optimizer around, which has a Arc<Catalog>, so as long as there is any outstanding peek, a new connection needs to clone the catalog.

We could put some effort into holding on to that `Arc<Catalog>` for a shorter time:
- `peek_finish` uses only a small part of the `optimizer` (`cluster_id()` and `finishing()`), and doesn't use the `Arc` anymore, so we could just pass that part of the `optimizer` into `peek_finish` that it actually needs.
- We could reconsider merging https://github.com/MaterializeInc/materialize/pull/28715, to spend less time optimizing.

**Pull request merged**
