### PR TITLE
catalog: Ensure versions can't go backwards

### LINKED ISSUE #29026: 0dt/m1: ensure versions can't go backwards on startup
Since persist became forwards compatible (by one version), we no longer crash loudly if we accidentally regress versions (e.g., downgrading from v0.112.2 to v0.111.3), even though we don't support that. This can lead to subtle issues that are hard to realize are the result of downgrading.

Proposal is to build something in/around/on top of catalog fencing to check for accidental version downgrades and clearly reject them.

Additional context: https://www.notion.so/materialize/Platform-v2-Weekly-sync-34777d32c90741cc891198efd06b1b40?pvs=4#946c640bff99408db3678de0a7a8d13b

### PR DESCRIPTION
**Pull request by jkosh44**
This commit prevents a binary from opening the catalog if the semantic version of that binary is lower than the most recent version to open the catalog.

Resolves #29026

### Motivation
This PR adds a known-desirable feature.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [X] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [X] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

**Review by ParkMyCar — APPROVED** [review]
To make sure I understand, previously did we rely on Persist to prevent opening the Catalog shard with a version that is greater than (current + 1)?

Otherwise LGTM!

**Comment by jkosh44** [comment]
> To make sure I understand, previously did we rely on Persist to prevent opening the Catalog shard with a version that is greater than (current + 1)?
> 
> Otherwise LGTM!

That also happens in the catalog actually, right here: https://github.com/MaterializeInc/materialize/blob/131b51f4117fd15b9a1e5cf593ff2542b4c6dcf1/src/catalog/src/durable/persist.rs#L753-L776

**Comment by jkosh44** [comment]
I'm seeing a lot of failures like this in Nightly:

`environmentd: fatal: incompatible persist version 0.113.0, current: 0.113.0-dev, make sure to upgrade the catalog one version forward at a time`

That implies that some of the tests are first starting Materialize with v0.113.0 and then starting Materialize with v0.113.0-dev. That is technically going backwards in versions and disallowed by this PR. @MaterializeInc/testing do you know where in the tests we do that?

**Comment by def-** [comment]
I'll check.

**Comment by def-** [comment]
I believe to have a fix, nightly for it: https://buildkite.com/materialize/nightly/builds/9141

**Comment by jkosh44** [comment]
> I believe to have a fix, nightly for it: https://buildkite.com/materialize/nightly/builds/9141

Thank you!

**Comment by def-** [comment]
Didn't work, checking again

**Review by def- — APPROVED** [review]

**Comment by def-** [comment]
The nightly failures are fixed on main (and the legacy upgrade failure by https://github.com/MaterializeInc/i2/pull/2098 hopefully)

**Comment by benesch** [comment]
Well that was fast. Thanks, Joe!

**Comment by def-** [comment]
I think the Legacy Upgrade test might be creating lots of core dumps and that is causing the problems for servers with going out of disk. I haven't investigated further though.

**Pull request merged**
