### PR TITLE
adapter: Fix mz_introspection cluster migration

### PR DESCRIPTION
**Pull request by jkosh44**
A previous commit added a migration to grant the mz_introspection role USAGE privileges on all existing clusters. It set the grantor of this privilege to mz_system. This was incorrect, the grantor should have been, the owner of the cluster. This commit fixes the migration to be the owner of the cluster.

### Motivation
This PR fixes a previously unreported bug.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [X] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [X] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - There are no user-facing behavior changes.

### CODE REVIEW

**Review by def- — APPROVED** [review]
I have triggered nightly, fine by me if it succeeds: https://buildkite.com/materialize/nightlies/builds/2663

**Comment by jkosh44** [comment]
> I have triggered nightly, fine by me if it succeeds: https://buildkite.com/materialize/nightlies/builds/2663

@def- Is the failure that's happening an expected one?

**Comment by jkosh44** [comment]
I'm going to merge this because it's strictly better. If there's still more issues we can fix them in a followup.

**Comment by def-** [comment]
Yes, unfortunately a known flake.

**Pull request merged**
