### PR TITLE
parallel workload: feature-flag flips

### PR DESCRIPTION
**Pull request by nrainer-materialize**
Extension to https://github.com/MaterializeInc/materialize/pull/26837.

Nightly: https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Aparallel-workload%2Ffeature-flag-flips

### CODE REVIEW

**Comment by nrainer-materialize** [comment]
Nightly passed: https://buildkite.com/materialize/nightly/builds/7640
Though, triggering a further retry to gain more confidence.

**Comment by bkirwi** [comment]
I've checked through the logs and confirmed that the flag updates are taking effect as expected.

I've also kicked off a nightly here, after reverting a bugfix for a bug that we'd hope a test like this would catch: https://buildkite.com/materialize/nightly/builds/7657

(That isn't totally guaranteed to fail if this is working as expected, since the failure is nondeterministic... but if it does fail that is a very good sign!)

**Review by bkirwi — APPROVED** [review]
The other nightly run failed - very good!

Thanks for working through this one with us... I think this is going to give us a lot more confidence in our flag-based rollouts.

**Comment by nrainer-materialize** [comment]
Awesome!

**Comment by def-** [comment]
lgtm, thanks!

**Pull request merged**
