### PR TITLE
sql: add AS OF AT LEAST, remove AS OF now()

### LINKED ISSUE #8390: Introduce `AS OF AT LEAST <timestamp>` or equivalent
Our `AS OF <timestamp>` modifier to `SELECT` provides the instruction that a query should be executed at a specific logical time. This can be a bit too specific for folks who want to execute a query at any available time at least `<timestamp>`, without needing to name the specific time. "The first available time at least `<timestamp>`" for example. 

Having to name a specific timestamp can be frustrating, and the best recommendation we have at the moment is to `SELECT .. AS OF ..` and respond to "data no longer available" errors with a `SELECT ..` query.

@mjibson had the take that `AS OF` could be repurposed to just mean this, which I'm personally less excited about, but if no users have bound to this yet that could be available (the term "as of" applies to e.g. as-of joins, appears in SQL specs on temporal queries, and .. either does or doesn't have some baggage attached to it).

### LINKED ISSUE #11188: Spec out the behavior of `AS OF now()`
Forked from "item 2" in #10587.

It is not clear what the behavior of `AS OF now()` should be. Here is an example of a defect in the current behavior, courtesy of @philip-stoev:

```
materialize=> SELECT now(), count(*) FROM s0 AS OF NOW();
            now            | count  
---------------------------+--------
 2022-02-10 12:59:04.72+00 | 100000
...
materialize=> SELECT now(), count(*) FROM s0 AS OF NOW();
ERROR:  Timestamp (1644497944988) is not valid for all inputs: [Antichain { elements: [1644497944999] }]
```

Thoughts from @frankmcsherry:

> This is "in spec" at the moment, but we should be able to fix it. Imo the coordinator should probably not compact things past now() rendering them invalid at the moment. Afaict, the only way to get the "is not valid for all inputs" is to have a query that prescribes a query time, and unfortunately if inputs have been compacted past that time we cannot pick a new time to catch up to (without violating the AS OF constraint). But we can prevent the coordinator from compacting past now().

Additional Slack discussion: https://materializeinc.slack.com/archives/CMHDK0DK8/p1647096901970989

### PR DESCRIPTION
**Pull request by mjibson**
Teach AS OF about AT LEAST, to allow users to specify a timestamp they require to be included in the results. Remove `now()` from AS OF because it doesn't do anything useful, and is actively wrong is some cases.

Fixes #8390
Fixes #11188

### Motivation

  * This PR adds a known-desirable feature. #8390 #11188

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - Add `AS OF AT LEAST` to improve timestamp selection in `SELECT` and `TAIL`.
  - *Breaking change* Remove `now()` support in `AS OF`, which no longer does what many users expect it to.

### CODE REVIEW

**Review by frankmcsherry — APPROVED** [review]
Seems good! I recommend socializing with @philip-stoev as this will possibly be a surprise for him. But I think it all checks out.

**Comment by philip-stoev** [comment]
Item No 1 . Going forward, what would be the canonical way of asking Mz to return data as it was at some previous point in time? Assuming I have set my retention interval my `--logical-compaction-window` to say 24h, how can I see the data as it was 1 hour ago? Will I need to create a materialized view with a `WHERE` clause to get that functionality?

**Comment by philip-stoev** [comment]
Item No 2. This panics:

```
materialize=> select 1 as of at least null::timestamp;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

```
2022-05-02T11:49:36.847848Z ERROR panic: Datum::unwrap_timestamp called on Null
thread: coordinator
location: src/coord/src/coord.rs:3415:49
version: 0.26.1-dev (6d7ebd526eee3d6986797fffe38c02dd7232e2cf)
backtrace:
   0: materialized::handle_panic
   1: core::ops::function::Fn::call
   2: std::panicking::rust_panic_with_hook
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:702:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
   5: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   6: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   7: mz_repr::scalar::Datum::unwrap_timestamp
   8: mz_coord::coord::Coordinator::determine_timestamp
   9: mz_coord::coord::Coordinator::sequence_peek::{{closure}}
  10: mz_coord::coord::Coordinator::sequence_plan::{{closure}}
  11: mz_coord::coord::Coordinator::message_command::{{closure}}
  12: mz_coord::coord::Coordinator::serve::{{closure}}
  13: tokio::park::thread::CachedParkThread::block_on
  14: std::sys_common::backtrace::__rust_begin_short_backtrace
  15: core::ops::function::FnOnce::call_once{{vtable.shim}}
  16: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys/unix/thread.rs:108:17
  17: start_thread
             at /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477:8
  18: clone
```

**Comment by philip-stoev** [comment]
Item No 3. What syntax should be used going forward to do the following thing:

1. In my application, I insert / ingest a record in Kafka, Postgres or some other Mz source
2. In the same application, I do a `SELECT` in Mz and expect that the record I just inserted in Step No 1 will be there.

 How can I formulate a `SELECT` in Step 2 that provides the desired behavior?

**Comment by frankmcsherry** [comment]
> Item No 3. What syntax should be used going forward to do the following thing:
> 
> 1. In my application, I insert / ingest a record in Kafka, Postgres or some other Mz source
> 2. In the same application, I do a `SELECT` in Mz and expect that the record I just inserted in Step No 1 will be there.
> 
> How can I formulate a `SELECT` in Step 2 that provides the desired behavior?

This is ["real time recency"](https://github.com/MaterializeInc/materialize/issues/11531) a property that we hope to support, but which MZ does not currently (nor has it ever) supported.

**Comment by frankmcsherry** [comment]
> Item No 1 . Going forward, what would be the canonical way of asking Mz to return data as it was at some previous point in time? Assuming I have set my retention interval my `--logical-compaction-window` to say 24h, how can I see the data as it was 1 hour ago? Will I need to create a materialized view with a `WHERE` clause to get that functionality?

Pretty sure `AS OF <then>` should work. You'll need to specify the time you want, subtract an hour from it, and convert it to milliseconds though. My understanding from @mjibson is that you may need to do this as a different statement (i.e. not an expression), though I bet we could negotiate on that (e.g. I'd be fine if we just don't convert `now()` to integer milliseconds magically, but allow an arbitrary expression that can include `now()` in it).

**Comment by philip-stoev** [comment]
> You'll need to specify the time you want, subtract an hour from it, and convert it to milliseconds though. My understanding from @mjibson is that you may need to do this as a different statement (i.e. not an expression)

Given that we do not support variables or stored procedures in SQL or any other syntax that would allow this calculation to happen entirely in SQL, I think relaxing the prohibition on `NOW()` would be in order .

**Comment by frankmcsherry** [comment]
One additional Q for @mjibson: is there advice on when to you `AS OF AT LEAST 0` as opposed to not using `AS OF` at all? It would seem that both of them select an unknown valid timestamp, and I can't distinguish the properties or use cases they might have.

**Comment by mjibson** [comment]
> is there advice on when to you AS OF AT LEAST 0 as opposed to not using AS OF at all

`AS OF AT LEAST 0` is useful for exactly one reason: it escapes the timestamp selected for other statements in a transaction. It will probably only ever be used in tests, and we don't expect a user to ever use 0. https://github.com/MaterializeInc/materialize/pull/12140 adds documentation (with non 0 AT LEAST times) that demonstrate cases where users want the AT LEAST syntax, but they probably will never use 0.

> Going forward, what would be the canonical way of asking Mz to return data as it was at some previous point in time?

What does "some previous point in time" mean?
- Does it mean "roughly an hour ago idk"? You can have your application look at its system clock (which may be a few seconds off of mz's clock), subtract an hour, and send that over where it's already computed the milliseconds for AS OF. This is exactly as inaccurate as saying `AS OF now() - '1 hour'::interval` because in that case you also didn't know which data were assigned which timestamps, so the timestamp coming from your application is not worse.
- Does it mean "exactly at this time previously reported by materialize via a TAIL timestamp or mz_logical_timestamp()"? Then you can compute the specific timestamp you want and send that over.
- Does it mean "I have a timestamp field in my data and would like to care about how my data looked as of that timestamp in the past"? That's a temporal filter, not AS OF.

The first use case there is essentially what I have removed support for, and I think that's good because it didn't mean anything exact, and my argument is that we are now exposing that inexactness to the user and forcing them to make a decision about either resolving the inexactness (which would convert them to one of the two other use cases listed), or embracing the inexactness and generating some semi meaningless timestamp on their end.

**Comment by mjibson** [comment]
FWIW, I've tried to document this in https://github.com/MaterializeInc/materialize/pull/12140/files#diff-7773d5b721721a2c49524cec4acfb664f0336d0c77395b881ff44a36bd2e05d8R33:

> Unmaterializable functions](/sql/functions#unmaterializable-functions) are not supported in `timestamp_expression`.
> This includes `now()` and `current_timestamp()`, which may seem like useful functions in order to reflect the most recent data in a query.
> However due to how Materialize assigns timestamps to data, those functions do not achieve that goal.
> Instead, it is best to not specify `AS OF` at all, allowing Materialize to choose a correct and recent timestamp on its own.

**Comment by benesch** [comment]
> > is there advice on when to you AS OF AT LEAST 0 as opposed to not using AS OF at all
> 
> `AS OF AT LEAST 0` is useful for exactly one reason: it escapes the timestamp selected for other statements in a transaction. It will probably only ever be used in tests, and we don't expect a user to ever use 0. #12140 adds documentation (with non 0 AT LEAST times) that demonstrate cases where users want the AT LEAST syntax, but they probably will never use 0.
> 
> > Going forward, what would be the canonical way of asking Mz to return data as it was at some previous point in time?
> 
> What does "some previous point in time" mean?
> 
> * Does it mean "roughly an hour ago idk"? You can have your application look at its system clock (which may be a few seconds off of mz's clock), subtract an hour, and send that over where it's already computed the milliseconds for AS OF. This is exactly as inaccurate as saying `AS OF now() - '1 hour'::interval` because in that case you also didn't know which data were assigned which timestamps, so the timestamp coming from your application is not worse.
> * Does it mean "exactly at this time previously reported by materialize via a TAIL timestamp or mz_logical_timestamp()"? Then you can compute the specific timestamp you want and send that over.
> * Does it mean "I have a timestamp field in my data and would like to care about how my data looked as of that timestamp in the past"? That's a temporal filter, not AS OF.
> 
> The first use case there is essentially what I have removed support for, and I think that's good because it didn't mean anything exact, and my argument is that we are now exposing that inexactness to the user and forcing them to make a decision about either resolving the inexactness (which would convert them to one of the two other use cases listed), or embracing the inexactness and generating some semi meaningless timestamp on their end.

This framing seems superb to me. I am generally a big fan of erring on the side of removing features that are confusing. If there is demand for `AS OF now() - '1 hour'`, we can add it back, and it will be an exciting feature. But if we do the reverse (leave it in), and it continues to trip users up, it will be much harder to remove later.

**Pull request merged**
