### PR TITLE
repr: add golden tests for Row decode and encode

### PR DESCRIPTION
**Pull request by danhhz**
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/7676)

### CODE REVIEW

**Comment by danhhz** [comment]
@wangandi I finally got back to this if you have any early thoughts on how I'm using the repr_test_util stuff. Looks like there's some duplication with code in repr_test_util/tests/test_runner.rs. I tried extracting it but the string unquote lifetime makes things hard. I'd actually rather specify a row instead of a single datum (which I think solves the lifetime issue), dunno how much overlap that has with the Constant stuff you have in expr_test_util.

**Comment by wangandi** [comment]
> I tried extracting it but the string unquote lifetime makes things hard. I'd actually rather specify a row instead of a single datum (which I think solves the lifetime issue), dunno how much overlap that has with the Constant stuff you have in expr_test_util.

Good point that specifying a row would fix the lifetime issue. I think changing a  "specify a single datum using a &str and a ScalarType" to "specify a row using `Iterator<Item=(&str, ScalarType)>`" should work fine with `expr_test_util`. I can change the interface if you like, or you can do it, and I can push the corresponding changes to `expr_test_util`.

**Comment by danhhz** [comment]
Yeah that interface sounds good to me! I'm happy to wait for that change if you think you'll get to it anytime soon

**Comment by danhhz** [comment]
we have new ways of testing our proto and Codec stuff now!

**Pull request closed without merging**
