### PR TITLE
Save plan hashes in `Fixpoint` rather than full plans

### PR DESCRIPTION
**Pull request by ggevay**
https://github.com/MaterializeInc/materialize/pull/27977 introduced a memory regression, which turned out to be non-trivial: https://github.com/MaterializeInc/materialize/issues/28244

This PR makes `Fixpoint` save the hashes of plans rather than the full plans.

Additionally, I factored out the limit of FoldConstants in a constant, in case we want to change it in the future (and for experimentation with changing it). I haven't actually changed the limit, though. 

### Motivation

  * This PR fixes a recognized bug: https://github.com/MaterializeInc/materialize/issues/28244

   * This PR refactors existing code: The limit of FoldConstants was given 4 times, making it annoying to experiment with different values. This PR factors it out.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by frankmcsherry — CHANGES_REQUESTED** [review]
The structure looks great, but I recommend we swap out DD's `hashed` method for something less likely to collide, so as to avoid surprising false positive matches on hashes. For example, I think this could be as simple as
```rust 
{
    let mut hasher = DefaultHasher::new();
    relation.hash(&mut foo);
    foo.finish()
}
```
This is longer than `relation.hashed()` but ..

**Comment by ggevay** [comment]
@frankmcsherry, could you please check again?

I've
- Added a precise check for hash collisions.
- Changed the Hasher to Rust's default.

Additionally, I'm doing two experiments to see whether we have any hash collisions, where I changed the collision detection code path to panic (running normal CI, Nightly, and full slt):
- `DefaultHasher`: https://github.com/MaterializeInc/materialize/pull/28274
- `FnvHasher`: https://github.com/MaterializeInc/materialize/pull/28275

**Review by frankmcsherry — APPROVED** [review]
It all seems plausible, but also no spec about what it is meant to do. If it works for you, great!

**Comment by ggevay** [comment]
Update: There were no hash collisions in either of my above experiments, either with fnv or the default hasher.

**Pull request merged**
