### PR TITLE
Move timely-specific code out of dataflow/

### PR DESCRIPTION
**Pull request by guswynn**
### Motivation

as part of my work to move `dataflow::sources/render::sources` (and `sinks`) out of `dataflow`, I first need to move some things around. Mostly `dataflow::logging`, which should be its own crate, that depends on `mz-dataflow-types` and `mz-timely-util`

This pr moves timely-specifc-but-not-dataflow-specific stuff out of `dataflow` into `mz-timely-util` if its generic, and into `dataflow-types` if it depends on `mz_repr/dataflow-types`, which will later allow me to move `mz-logging` out of `dataflow`

   * This PR refactors existing code.

## Overview of why things are moved to where they are:

I am starting with the goal of moving just `mz_dataflow::sources` out of `mz_dataflow`. That module primarily depends on things like this
```
mz_dataflow::sources -> mz_logging ------------> mz_dataflow::arrangement, mz_dataflow::replay, and mz_dataflow::activator
   |                     |
  \/                    \/
   mz_dataflow_types + other small modules to deal with in later prs
 ```
 
 `mz_dataflow::replay` and `mz_dataflow::activator` are dep-free, pure extensions to `timely`, and slot well into `mz-timely-util`, which didn't exist when they were written
 
 `mz_dataflow::arrangement` is extensions to `timely` + `differential-dataflow`, that are parameterized on types from `mz_repr` and `mz_expr` (also they use `metrics` stuff from `mz_ore`. The way I think of the dep tree in `materialized/` is:
 ```
 mz_ore (no mz deps)                              mz_timely_util (only depends on timely and maybe dd)
 |                                                                       |
 |                                                                     ..... (anything)
mz_repr  (purely row representations, but also unfortunately Diff and Timestamp)
|
mz_expr (relations/globalid/etc)        other libs like ccsr,interchange kafka,etc
|                                                              |
mz_dataflow_types (common types for ALL of `materialize/` that ONLY depends on repr, expr, and dep free libs
```

`mz_dataflow_types` is the HIGHEST library that speaks ALL the common languages of libraries like: ore, repr, expr, timely-util, timely, dd, ccsr/kafka/other upstream deps, interchange, etc (as well as `mz_persist` curiously). I think it is poorly named, but I think its the right place for `dataflow::arrangement`, which wants to exist as high in the dep tree as possible (like anything), but needs `expr` and `repr`.
 

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [N/A] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

**Comment by benesch** [comment]
I'm not the right person to do the actual review, but I think probably we want to move these into the existing [`mz-timely-util`](https://dev.materialize.com/api/rust/mz_timely_util/index.html) crate?

**Comment by guswynn** [comment]
@benesch that would make `stash` depend on mz_repr, mz_ore, and mz_ezpr. I think timely-util, whether it is renamed or not, should remain a dep-free set of timely extension

**Comment by benesch** [comment]
Yeah I definitely don't think it makes sense to have _both_ `mz-timely` and `mz-timely-util`. That distinction is not something I want us to be in the business of explaining.

So, it looks like the `activator` and `replay` modules are much slimmer, and can move into `mz-timely-util` without any additional fuss or deps. I think we should do that to start! Then we can consider separately the question of the `arrangement` module. One take is that the `arrangement` module could become generic over the key/value/timestamp/ID types. Maybe @frankmcsherry has something to suggest there.

**Comment by guswynn** [comment]
@benesch `activator` and `replay` going into `timely-util` is a good idea! as for arrangement, yah, i'd love to know what @frankmcsherry thinks!

**Comment by benesch** [comment]
FWIW, the things that `arrangement` depends on in `repr` are things that probably ought to have never been put in `repr` in the first place:

https://github.com/MaterializeInc/materialize/blob/ae8e5e607ac9c79122571cc8847c56bc2138234b/src/repr/src/lib.rs#L42-L68

**Comment by guswynn** [comment]
@benesch it also depends on `mz_ore::metrics` and `mz_expr::GlobalId`

`ore` really is usually the top of the dep tree so thats fine, I could see `GlobalId`, `Diff`, and `Timestamp` moved to ore (and re-exported in original crates to make the refactor not horrible)

**Comment by benesch** [comment]
> `ore` really is usually the top of the dep tree so thats fine, I could see `GlobalId`, `Diff`, and `Timestamp` moved to ore (and re-exported in original crates to make the refactor not horrible)

Ah, so `ore` is only meant to contain things that would go in the stdlib in other languages. It's not meant to contain anything that's particularly Materialize-specific. The test to apply is: if we released `mz-ore` to crates.io, would this type/function be useful? `GlobalId`, `Diff`, and `Timestamp` would all fail that test. 

But yes, as a result it's always fine for a crate in our tree to depend on `ore`, because we think of `ore` as an extension of the stdlib!

**Comment by benesch** [comment]
Actually, I think `arrangement` can just go in `dataflow-types`?

**Comment by guswynn** [comment]
@frankmcsherry  Add some context to the discussion on placement of things, but arguably, `arrangement` could be its own crate that depends on `mz_expr`, `mz_ore`, and `mz_repr`

**Comment by frankmcsherry** [comment]
> Actually, I think `arrangement` can just go in `dataflow-types`?

I'm looking at it, and this looks a bit clumsy. Afaict, logging depends only on a few typedefs at the top of `manager.rs`, and we can certainly hoist those out (e.g. what types do we put inside a trace). The `TraceManager` type is not referenced other than by `server.rs` and `compute_state.rs`, and I don't think we need to hoist that out.

I've lost a bit of the thread here. I can see wanting to move `sources` out, but I think one take on that should be "let's see what surface area that forcibly exposes" and if it is rough let's not do it. I can't exactly tell how sources depends on `logging`, which I thought was a source-independent thing.

Ok, I just read a bunch, and it looks like primarily the dependence is due to the variant `MaterializedEvent::SourceInfo` which records our "kinda, but not really" timestamp bindings. I think if we make legit timestamp bindings, we just delete this, and potentially un-rip apart all of the crates. At the very least, I think we can just hoist the `*Event` types and the `Logger` type out of logging, rather than e.g. all the dataflow building and such.

**Comment by guswynn** [comment]
@frankmcsherry the more I look at it, the more I think https://github.com/MaterializeInc/materialize/blob/b2723a2c2f7f2300ae18ab6964ae01ae9a30e3a2/src/dataflow/src/logging/materialized.rs#L35-L75 could be reasonably lifted out of `mz-dataflow` into at least `mz-expr`. Does that seem reasonable?

**Comment by frankmcsherry** [comment]
If you mean `MaterializedEvent` that seems reasonable. The logging *structs* seem fine to hoist up (at least, I don't see the downside, and I can understand the argument for exposing them). Ideally we leave behind the "dataflow built to processes these structs" though!

**Comment by guswynn** [comment]
@frankmcsherry what do you mean by "dataflow built to processes these structs"?

**Comment by frankmcsherry** [comment]
I believe this has been accomplished at this point. Thanks for the groundwork, and apologies for stomping all over this PR.

**Comment by guswynn** [comment]
@frankmcsherry yes! It is cleaner than I thought possible now!

Thanks!

**Pull request closed without merging**
