### PR TITLE
stash: Remove serde traits

### PR DESCRIPTION
**Pull request by jkosh44**
### Motivation
This PR refactors existing code.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [X] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [X] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - There are no user-facing behavior changes.

### CODE REVIEW

**Comment by mjibson** [comment]
Those traits were added in https://github.com/MaterializeInc/materialize/pull/20384 so that stash-debug could use a JSON interface. I'm very confused how you can remove those and all the tests pass. I would have expected compilation of stash-debug to fail.

**Comment by mjibson** [comment]
Specifically: https://github.com/MaterializeInc/materialize/blob/main/src/stash-debug/src/main.rs#L374 uses `TypedCollection.iter` which returns a `Vec<((K, V), Timestamp, Diff)`, then stash-debug calls: https://github.com/MaterializeInc/materialize/blob/d1ea617be72393cc6afdf74ddcd05b6afb234fb6/src/stash-debug/src/main.rs#L378 which I thought needs to have the Serialize trait?

**Comment by mjibson** [comment]
Oh it's because https://github.com/MaterializeInc/materialize/blob/d1ea617be72393cc6afdf74ddcd05b6afb234fb6/src/stash/build.rs#L188 always adds it to the concrete K and V types. This change would make it so that the stash doesn't require it, but stash-debug does. I think there's value in having the `Data` trait require it, otherwise users will still get the same compile errors but they might be more confusing because stash-debug is the only thing complaining.

**Comment by jkosh44** [comment]
> Oh it's because
> 
> https://github.com/MaterializeInc/materialize/blob/d1ea617be72393cc6afdf74ddcd05b6afb234fb6/src/stash/build.rs#L188
> always adds it to the concrete K and V types. This change would make it so that the stash doesn't require it, but stash-debug does. I think there's value in having the `Data` trait require it, otherwise users will still get the same compile errors but they might be more confusing because stash-debug is the only thing complaining.

Ah ok, that makes sense.

> What's the motivation to remove?

I just thought it was left-over code from the JSON stash era and didn't realize that it was used by stash-debug. I agree that it's worth keeping around in that case.

**Pull request closed without merging**
