### PR TITLE
Have `Equivalences::minimize` take `Option<Slice>`

### PR DESCRIPTION
**Pull request by frankmcsherry**
The `minimize` function for `Equivalences` took an `&Option<Vec<T>>`, which made sense in several initial call sites, but has led to the need to clone various things just to get an option around a vector. This PR changes the argument to be `Option<&[T]>`, which one can arrive at without cloning. The downside is a bit more chatter converting the optional vector to an optional slice, but .. just better practice anyhow.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

**Review by ggevay — APPROVED** [review]
LGTM

Btw. `minimize` calls `to_vec`, which is similar to a clone. So maybe an alternative would be to make minimize take `Option<&Vec<ColumnType>>`? I think this would be the same amount of cloning as in the PR (because then the caller would do a clone, but `minimize` wouldn't have to clone), but the code would be simpler, as there would be no need to do the slice conversions at various places.

**Comment by frankmcsherry** [comment]
> So maybe an alternative would be to make minimize take `Option<&Vec<ColumnType>>`?

Could do, but .. tbh I'm ok at the moment with the more explicit, and more general form, just to avoid the future moment where someone has a slice rather than a vec and we need to change this again. But also happy to revisit if we end up hating this.

**Comment by ggevay** [comment]
Ok, I'm also fine with the version that is proposed in the PR.

**Review by mgree — APPROVED** [review]
Seems totally reasonable to me. Slice interfaces are the most versatile, and it seems nice to push the cloning into the function rather than the clients.

**Pull request merged**
