### PR TITLE
pg-cdc: fix logic bug with COPY iterator

### LINKED ISSUE #10981: v0.20.0/0.21.0 makes data after a nullable column null
### What version of Materialize are you using?

v0.20.0/v0.21.0

### How did you install Materialize?

APT package

### What was the issue?

I've been running Materialize for several months without issues. I'm using a direct Postgres source. After upgrading to 0.20.0, if there's null data, all subsequent columns in that row become null too.

E.g. here's the data in the source Postgres table:
Capture

In 0.19.0 and earlier, the view in Materialize would look exactly the same. In v0.20.0, it becomes:
Capture2

I tried reinstalling Materialize and Postgres several times and deleting the data folders. There's no errors in the error log. After downgrading to 0.19.0, it works again. I don't think I have any unusual Postgres settings.

The view was created according to the Postgres CDC guide:

```
Postgres:
ALTER TABLE __test__ REPLICA IDENTITY FULL');
CREATE PUBLICATION mz_source_test FOR TABLE __test__

Materialize:
CREATE MATERIALIZED SOURCE mz_source_test
FROM POSTGRES
CONNECTION 'host=127.0.0.1 port=5432 user= password= dbname= sslmode=require'
PUBLICATION 'mz_source_test';
CREATE VIEWS FROM SOURCE mz_source_test (__test__);
```

In addition, whenever I update one of the rows containing null in Postgres, then select from Materialize, I get:

```
materialize=> select * from __test__;
ERROR:  Invalid data in source, saw retractions (1) for row that does not exist: [Int32(99525), List([String("1"), Null, String("1")]), Int64(1), Null, Int64(1)]
```

Nothing in the release notes seemed related, any ideas?

### Versions

Postgres: 14.2
OS: Ubuntu 20.04 on WSL 2

### PR DESCRIPTION
**Pull request by petrosagg**
The implementation of `RawIterator` relied on the implementation of the
protocol parser which when asked to parse a column from the input buffer
returns a `Result<Option<&[u8]>, Error>` where the Option in the Ok case
is used to signal whether the current column contains some bytes or is
null.

The previous implementation of `RawIterator` transposed that result into
an `Option<Result<&[u8], Error>>` changing the semantics in a subtle but
imporant way, because now a `None` value signaled the end of the
iterator.

This resulted with the ingestion pipeline early returning when consuming
the COPY data and omitting all column data after encountering one with a
NULL.

This PR fixes the problem by making the iterator return
`Option<Result<Option<&[u8], Error>>` where the outer option signals the
end of the Iterator and the inner option singal the presence or not of a
NULL in the column.

Fixes #10981

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

Fix data loss bug of direct postgres replication sources introduced in version 0.20.0. Github issue #10981

### CODE REVIEW

**Comment by philip-stoev** [comment]
Thank you for the test. Can we have an assertion/source error somewhere that the number of columns we get back from COPY processing is identical to the number of columns we expect? Seems arbitrary that we decided that that the rest of the rows after the premature termination are to be considered filled with nulls.

**Review by philip-stoev — APPROVED** [review]

**Comment by petrosagg** [comment]
> Can we have an assertion/source error somewhere that the number of columns we get back from COPY processing is identical to the number of columns we expect?

I also thought about that and I'm up for ideas. The transformation of the raw replication relation into per-table views is done in SQL with queries like this one:

```sql
-------------------------------

CREATE VIEW materialize.public.__test__ (
    id,
    name,
    id2
) AS
    SELECT
        (
            row_data[1]
        )::pg_catalog.int4
            AS id,
        (
            row_data[2]
        )::pg_catalog.text
            AS name,
        (
            row_data[3]
        )::pg_catalog.int4
            AS id2
    FROM
        materialize.public.mz_source_test
    WHERE
        oid = 16384;
```

It looks like indexing a list beyond its end results in null instead of an EvalError. Do you know of another way to write this query that will produce an error if the list is indexed beyond its end?

**Comment by philip-stoev** [comment]
If we had a `RAISE EXCEPTION` function as Postgres does, you could incorporate the check in the `CREATE VIEW`  code itself.

**Comment by pH14** [comment]
🙇 thank you so much for the quick fix! Looks great

**Pull request merged**
