### PR TITLE
dataflow: factor out total field in reduce accumulator

### PR DESCRIPTION
**Pull request by benesch**
Per discussion in #6217. I'm not sure whether this actually makes things
clearer, but wanted to submit for evaluation.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/6230)

### CODE REVIEW

**Comment by benesch** [comment]
I sound less enthusiastic than I meant to in the PR description. I'm really truly 100% ambivalent on whether this is better than the current code. @frankmcsherry and @ruchirK, if you find this clearer, then great!

**Comment by frankmcsherry** [comment]
I do find it clearer (net -45 loc!). If you want to go further, I believe `struct Accum` is functionally equivalent to a `(AccumInner, isize)`. But at this point I could see reasonable people disagreeing.

**Comment by benesch** [comment]
> If you want to go further, I believe `struct Accum` is functionally equivalent to a `(AccumInner, isize)`. But at this point I could see reasonable people disagreeing.

Yeah I thought it was nice to be able to explicitly call that field out as the total, with some docs!

**Comment by benesch** [comment]
Added a few more docs about the `is_zero` gotcha!

**Review by ruchirK — APPROVED** [review]
I like this!

**Pull request merged**
