### PR TITLE
[docs] Note about cargo check target dir in rust-analyzer

### PR DESCRIPTION
**Pull request by cjubb39**
### Motivation
I asked this question in slack and it was suggested I add to the repo

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - n/a

### CODE REVIEW

**Review by benesch — APPROVED** [review]
Thank you

**Review by umanwizard — CHANGES_REQUESTED** [review]
Can we please hold off on this until we come to a conclusion [here](https://materializeinc.slack.com/archives/CMH6PG4CW/p1649442540921589?thread_ts=1649440408.409279&cid=CMH6PG4CW)

**Review by umanwizard — APPROVED** [review]
OK, now that I understand Nikhil's point better, this is fine, but you (probably unintentionally) put it in the vim- and emacs-specific section, rather than applying to all editors including VSCode!

**Comment by cjubb39** [comment]
I did whoops. thanks!

**Pull request merged**
