### PR TITLE
*: remove PubNub sources

### PR DESCRIPTION
**Pull request by benesch**
The PubNub source type existed essentialy only for demos. Now that we
have load generator sources for demos, we no longer need PubNub sources.

Benefits include:

  * Avoiding a dependency on the abandoned Rust PubNub library.
  * Avoiding user confusion about whether we support GCP "PubSub".

### Motivation

* This PR removes a feature that has been obsoleted.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-protobuf` label.
- [x] This PR includes a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

### CODE REVIEW

**Review by morsapaes — APPROVED** [review]
🤩 (Petros will be elated when he comes back from vacation!)

Thanks for patching the docs! We'll have to redo the Get Started guide as a follow-up of all this work (#13760); I'll comb through all the pages that used the PubNub source then, too, since using a different source invalidates a bunch of queries that follow the source creation.

**Comment by sjwiesman** [comment]
Massive +1

the load generator source is marked unsafe. We need to prioritize making it safe if we drop pubnub

**Comment by morsapaes** [comment]
@sjwiesman: https://github.com/MaterializeInc/materialize/commit/717fffb7f14cbd4462d8d21d973455ab914f3b48

**Comment by sjwiesman** [comment]
Thanks for reading my mind!

**Comment by mjibson** [comment]
> the load generator source is marked unsafe. We need to prioritize making it safe if we drop pubnub

Got marked safe last night! https://github.com/MaterializeInc/materialize/pull/13866

**Comment by heeringa** [comment]
LGTM!

**Review by heeringa — APPROVED** [review]

**Comment by benesch** [comment]
> Thanks for patching the docs! 

Was not my finest work. Oops. Thanks for all the corrections.

> We'll have to redo the Get Started guide as a follow-up of all this work (https://github.com/MaterializeInc/materialize/issues/13760); I'll comb through all the pages that used the PubNub source then, too, since using a different source invalidates a bunch of queries that follow the source creation (and we'll probably want to use the AUCTION generator for all).

🙇🏽 that sounds wonderful, thank you!

**Comment by benesch** [comment]
@nmeagan11, giving you a ping on this for when you're back from vacation!

**Pull request merged**
