### PR TITLE
persist-txn: make "lazy" the default in CI

### PR DESCRIPTION
**Pull request by danhhz**
Touches #22173

### CODE REVIEW

**Comment by danhhz** [comment]
Whoops, indeed I broke lazy in the unrelated #24597. Fix should be easy, will get it up in between meetings at some point today

**Comment by danhhz** [comment]
Fix is up in https://github.com/MaterializeInc/materialize/pull/24621. I pushed it here, too, so I can get an early read on CI, but will rebase it out before merging this.

**Review by jkosh44 — APPROVED** [review]

**Review by def- — APPROVED** [review]

**Review by aljoscha — APPROVED** [review]
👍

**Comment by danhhz** [comment]
I haven't gotten a clean nightlies run yet, but I've rebased it a few times, gotten a mostly different set of failures each time, and those failures were also happening elsewhere. So, thinking I'll go ahead and merge this, but after the release candidate gets cut today, so if anything unexpected happens, it doesn't delay that process

**Comment by def-** [comment]
The current nightly failures look unrelated to this PR to me.

**Pull request merged**
