### PR TITLE
doc: add 'last modified' info (from last Git commit) to pages

### PR DESCRIPTION
**Pull request by sys3175**
This adds a 'last modified' line to the doc pages. The date automatically reflects the latest Git commit affecting the page (see https://gohugo.io/variables/git/). To keep things simple and reusable, I decided to insert the line into a partial that is included in every page. I experimented with the *sidebar*, *breadcrumbs*, *toc*, and *footer* partials and found the location in the *toc* partial most satisfying (for pages with a toc), and the location in the *footer* partial seems fitting for pages w/o toc.

This change, while working, contains no styling, this should be decided after confirming the desired location of the 'last modified' line. Because of this, **the change still needs work** after discussing the best location and the necessary styling.

### Motivation

  * This PR adds a known-desirable feature. [(https://github.com/MaterializeInc/materialize/issues/8524)]

### Tips for reviewer
   * The location of the 'last modified' line is my personal taste, but I think that it's a good choice given the constraint that it should be included in a partial.
   * I decided not to change the front matter (see https://gohugo.io/getting-started/configuration/#configure-dates), because I didn't see the need of a fallback (the Git commit date should always be available).

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR adds a release note for any
  [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

**Comment by msudberg** [comment]
Thanks for getting started on this, @sys3175! I agree that the styling on this should be simple. I think, though, that we will want to put this under the title heading for most pages, and suppress it entirely for index/_index pages.

(On another note, @morsapaes or @antiguru should be reaching out to set up a call.)

**Comment by sys3175** [comment]
> Thanks for getting started on this, @sys3175! I agree that the styling on this should be simple. I think, though, that we will want to put this under the title heading for most pages, and suppress it entirely for index/_index pages.

So I looked a bit further into the inner workings of hugo, and found a way to easily move it under the main heading. For this, I had to move the ```<h1>{{.Title}}</h1>``` part out of the *single* and *list* templates and put it into a partial of its own, ```heading.html``` (which I find actually preferable because it deduplicates code).

In the next step, I still have to look into a way to suppress it on [_]index pages. For now, it doesn't appear on pages that have *disable_toc* set (I don't know if that fulfills the requirement, or is too broad).

> (On another note, @morsapaes or @antiguru should be reaching out to set up a call.)

Thanks for the heads-up, I'll reach back out to them.

**Comment by sys3175** [comment]
Ok, so I checked, and most of the index pages have *disable_toc* set (except the ``CLI`` and ``katacoda`` pages). So this should work, but I think it should be documented somewhere what *disable_toc* does (other than disabling the TOC), or the param should be renamed to reflect its scope.

**Comment by morsapaes** [comment]
Closing (see [#9661](https://github.com/MaterializeInc/materialize/pull/9661#issuecomment-997299929)).

**Pull request closed without merging**
