### PR TITLE
testdrive: Add prometheus test actions and some tests

### PR DESCRIPTION
**Pull request by quodlibetor**
Putting this up for review now, but I intend to go through and add a few
more tests to verify more labels.

In particular this would have cought a couple times where we've
accidentally changed label names.

### CODE REVIEW

**Comment by benesch** [comment]
Testing this seems good, but I'm not sold on having our own Prometheus metrics parser and DSL. That's a _lot_ of code for just a few assertions. Can we instead use the new SQL interface @antifuchs added to make these assertions with no new testdrive features? E.g.

```sql
> SELECT labels, value FROM mz_metrics
  WHERE metric = 'mz_partition_offset_received' AND labels->>'topic' = '${testdrive.seed}'
  ORDER BY time DESC LIMIT 1
4
```

**Comment by quodlibetor** [comment]
> That's a lot of code for just a few assertions.

Hopefully the number of assertions grows! But also it's basically one afternoon's worth of code that hopefully shouldn't need much updating, if it becomes a maintenance burden I agree that it would be worth getting rid of it.

> Can we instead use the new SQL interface

I considered that, but I was concerned about two things:

* I would like to verify that our prometheus interface itself is correct
* Being possibly affected by `--introspection-frequency`, either leading to weird flakiness or testdrive slowdowns.
* Sort of in counterpoint to that: having a dedicated API allows us to verify that the prometheus api matches the sql api down the line, without us needing to change testdrive tests, if we want that.

**Comment by benesch** [comment]
In the future I think we should talk through these sorts of tradeoffs re: testdrive before you spend too much time on them! Just a quick chat on Slack or something. I would definitely have advocated for the very quick solution in this case:

```diff
diff --git a/test/testdrive/kafka-stats.td b/test/testdrive/kafka-stats.td
index 14c476e2b..28d9c7506 100644
--- a/test/testdrive/kafka-stats.td
+++ b/test/testdrive/kafka-stats.td
@@ -102,6 +102,16 @@ count
 -----
 1
 
+> SELECT value FROM mz_metrics
+  WHERE metric = 'mz_kafka_partition_offset_max' AND labels->>'topic' = 'testdrive-data-${testdrive.seed}'
+  ORDER BY time DESC LIMIT 1
+0
+
+> SELECT value FROM mz_metrics
+  WHERE metric = 'mz_partition_offset_received' AND labels->>'topic' = 'testdrive-data-${testdrive.seed}'
+  ORDER BY time DESC LIMIT 1
+4
+
 # Drop the sources and verify that metrics have been removed
 > DROP VIEW test1
 
diff --git a/test/testdrive/prometheus.td b/test/testdrive/prometheus.td
index 2d4725eae..bfb43fd7c 100644
--- a/test/testdrive/prometheus.td
+++ b/test/testdrive/prometheus.td
@@ -10,6 +10,22 @@
 # This test validates that prometheus logs make it to testdrive, and that they get retained
 # correctly.
 
+# Some prometheus metrics should always exist
+
+> SELECT value > 0 AND labels ? 'os' FROM mz_metrics WHERE metric = 'mz_server_metadata_seconds'
+  ORDER BY time DESC LIMIT 1
+true
+
+> SELECT value FROM mz_metrics WHERE metric = 'mz_worker_pending_peeks_queue_size'
+  ORDER BY time DESC LIMIT 1
+0
+
+> SELECT count(*) > 0 FROM mz_metrics WHERE metric = 'mz_worker_command_queue_size'
+true
+
+> SELECT count(*) > 0 FROM mz_metrics WHERE metric = 'mz_arrangement_maintenance_active_info'
+true
+
 # Ensure we retain metrics:
 > CREATE MATERIALIZED VIEW metric_stats AS SELECT count(*) as total, max(time) as youngest, min(time) as oldest FROM mz_metrics;
 > SELECT oldest<=youngest FROM metric_stats;

```

The actual assertions are a bit more verbose, but on the plus side any arbitrarily complex SQL expression can be used as an assertion without requiring additional changes to testdrive. 

> Hopefully the number of assertions grows! But also it's basically one afternoon's worth of code that hopefully shouldn't need much updating, if it becomes a maintenance burden I agree that it would be worth getting rid of it.

There's already a cost though, because someone needs to review it for correctness. I don't have time to look into the parser in depth right now, but it looks like it doesn't correctly handle labels values with nested quotes. 

> > That's a lot of code for just a few assertions.

> I considered that, but I was concerned about two things:
> 
> * I would like to verify that our prometheus interface itself is correct

I definitely understand the desire here, but I feel like in practice this part of the system is already well covered by our load tests which exercise the `/metrics` endpoint using actual Prometheus, which is an even better integration test than testdrive can offer.

> * Being possibly affected by `--introspection-frequency`, either leading to weird flakiness or testdrive slowdowns.

Using SQL will work fine because of the way testdrive retries SQL queries until they succeed. In fact the code as written doesn't have a retry loop, so I think it's subject to race conditions because there's no guarantee that the metrics will be created in any sort of time frame.

> Sort of in counterpoint to that: having a dedicated API allows us to verify that the prometheus api matches the sql api down the line, without us needing to change testdrive tests, if we want that.

This seems like mostly a theoretical concern right now though. I can't really imagine a bug where we presented a metric in the SQL interface but _not_ the HTTP interface.

**Comment by benesch** [comment]
So, concretely, my preference would be to just merge the SQL assertions version for now, with the option of merging something like the `verify-prometheus` action in the future if deficiencies with the approach become clear.

If you feel strongly that we need something like `verify-prometheus` then perhaps there is someone else who'd be up for reviewing the metrics parser. Like I mentioned earlier I'm just not convinced the cost-benefit ratio here is in our favor. But if you rope someone who is not me into sharing responsibility for it then that's fine. (Also, FWIW the parser will probably come out much simpler if you use an `ore::lex::LexBuf`.)

**Comment by quodlibetor** [comment]
> just merge the SQL assertions version for now

Will do this.

> There's already a cost though, because someone needs to review it for correctness. I don't have time to look into the parser in depth right now, but it looks like it doesn't correctly handle labels values with nested quotes.

Right, it doesn't do that, but it also doesn't need to because we'd need to introduce double-quoted label values which would be weird. A parser that needs to handle possibly hostile data would need to be more robust, this one we can trust will only support test data that we've supplied.

> our load tests ... is an even better integration test than testdrive can offer.

This is emphatically not the case, we have had unintentional API-breakage twice in 2021 because people didn't happen to look at the specific panels that relied on APIs that changed. In order for our load tests to cover everything we'd need to ensure that we have alerts configured on every panel, which isn't possible in Grafana because you can't configure alerts on any queries that use Grafana-level variables. It also wouldn't catch API changes until the nightly load test, instead of blocking unintentional changes as part of CI.

> This seems like mostly a theoretical concern right now though. I can't really imagine a bug where we presented a metric in the SQL interface but *not* the HTTP interface.

Aren't all non-present bugs sort of theoretical concerns? I am slightly more concerned with drift between the two. With the current structure of the code it'd be hard to manage to introduce a bug, but I assume that we will change that code over time.

**Comment by quodlibetor** [comment]
To be clear I responded to lay out my thinking for the fullness of history, not because I am going to refuse to use the SQL interface.

**Comment by quodlibetor** [comment]
Interestingly the testdrive failure comes from the fact that the `mz_metrics` table doesn't start getting populated until the `http://<host>:6875/metrics` endpoint (not just any old http endpoint) is pinged at least once. I'm investigating, but it's a bit surprising.

**Comment by benesch** [comment]
> > There's already a cost though, because someone needs to review it for correctness. I don't have time to look into the parser in depth right now, but it looks like it doesn't correctly handle labels values with nested quotes.
> 
> Right, it doesn't do that, but it also doesn't need to because we'd need to introduce double-quoted label values which would be weird. A parser that needs to handle possibly hostile data would need to be more robust, this one we can trust will only support test data that we've supplied.

If we add a parser for the Prometheus text format to the codebase I feel strongly that it needs to either follow the [spec](https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md#text-format-details), or clearly document where it deviates and why. (In this case supporting escaped label values seems straightforward enough, so doesn't seem worth avoiding.) Otherwise whoever adds a label value that needs escaping is going to get stuck debugging the metrics parser. I don't think a label value that needs escaping is all that weird; I can definitely imagine some user data like an object name creeping into a label value, and then all bets are off, especially considering we've got tests that explicitly create objects with funny names.

> > our load tests ... is an even better integration test than testdrive can offer.
> 
> This is emphatically not the case, we have had unintentional API-breakage twice in 2021 because people didn't happen to look at the specific panels that relied on APIs that changed. In order for our load tests to cover everything we'd need to ensure that we have alerts configured on every panel, which isn't possible in Grafana because you can't configure alerts on any queries that use Grafana-level variables. It also wouldn't catch API changes until the nightly load test, instead of blocking unintentional changes as part of CI.

I think you misunderstood the point I was making! I agree that having tests to make sure metric and label names don't get changed inadvertently is important. My point was that the additional safety you get by making those assertions over HTTP instead of SQL are minimal, because we've got the load tests to exercise nearly all the HTTP-specific code. E.g., if `/metrics` were to start 500-ing, or if a new version of the rust-prometheus crate emitted malformatted junk, we'd 100% catch that via the load tests. And those load tests are a better test of the HTTP interface than testdrive could ever be because they use actual Prometheus. For example, if actual Prometheus sets some weird header that causes `/metrics` to fail to render, testdrive couldn't possibly catch that, but the load tests would!

Plus, to date we have never broken the actual metrics HTTP interface, so it seems fine to only catch breakage there in releases rather than in every PR.

> > This seems like mostly a theoretical concern right now though. I can't really imagine a bug where we presented a metric in the SQL interface but _not_ the HTTP interface.
> 
> Aren't all non-present bugs sort of theoretical concerns? I am slightly more concerned with drift between the two. With the current structure of the code it'd be hard to manage to introduce a bug, but I assume that we will change that code over time.

Right, I'm trying to get at the tradeoff here. This particular bug seems unlikely enough that it doesn't seem quite worth it to me to write a Prometheus parser to protect against it, is all.

**Comment by benesch** [comment]
> Interestingly the testdrive failure comes from the fact that the `mz_metrics` table doesn't start getting populated until the `http://<host>:6875/metrics` endpoint (not just any old http endpoint) is pinged at least once. I'm investigating, but it's a bit surprising.

Looks like that's because that metric doesn't get set until `load_prom_metrics` is called, which only happens if you hit the HTTP endpoint (or if telemetry is enabled, which it's not in CI). See:

https://github.com/MaterializeInc/materialize/blob/973a2588cd006ee60c1d2cc2c0a99a85fc19b0cf/src/materialized/src/server_metrics.rs#L81

**Comment by quodlibetor** [comment]
Yeah. Because of the sheer amount of global information that we've stuck in the `materialized` crate moving the metric to coord doesn't make sense. 

Two obvious alternatives (which would be separate PRs) to resolve the fact that we do have divergence between the two metrics sources would be:

* populate the metric in a separate tokio task, in a loop
* create a new metrics crate where we can share the implementation between the two places

The task seems pretty lightweight and would resolve the divergence.

**Review by benesch — APPROVED** [review]

**Pull request merged**
