### PR TITLE
repr: sort nulls last

### LINKED ISSUE #5982: ORDER BY defaults to NULLS FIRST in Materialize, NULLS LAST in Postgresql
### What version of Materialize are you using?

```
v0.7.2-dev (c355c88ad)
```

### What was the issue?

Materialize sorts NULLs first whereas Postgresql sorts them last.

I believe that both are valid under the SQL standard, however I think people will be unpleasantly suprised if MZ does it differently from Postgresql.

Alternatively, Materialize can implement the syntax to specify ```NULLS FIRST``` or ```NULLS LAST``` in the ```ORDER BY``` clause.

### Is the issue reproducible? If so, please provide reproduction instructions.

In Materialize:

```
materialize=> CREATE TABLE nulls (f1 INTEGER);
CREATE TABLE
materialize=> INSERT INTO nulls VALUES (1), (NULL);
INSERT 0 2
materialize=> SELECT * FROM nulls ORDER BY f1;
 f1 
----
            < The NULL is sorted first
  1
```

contrast with Postgresql:

```
pstoev=# SELECT * FROM nulls ORDER BY f1;
 f1 
----
  1
         <- The NULL is sorted last
```

### PR DESCRIPTION
**Pull request by benesch**
Fix #5982.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/6144)

### CODE REVIEW

**Comment by philip-stoev** [comment]
@frankmcsherry had a PR out that used the exact same approach https://github.com/MaterializeInc/materialize/pull/5998 .  I assume yours is going to live on, as it also contains adjustments to the tests, etc.

**Comment by benesch** [comment]
D’oh! Thanks for the heads up.

**Comment by frankmcsherry** [comment]
I'm fine landing either one, but it would be nice if we could commit to sorting NULLs last, as there are some optimizations blocked on not knowing. I'm not sure where in the repo we "commit" to things, and maybe we really don't want to and in that case fair enough and we can skip the optimizations.

**Comment by benesch** [comment]
Sorry, @frankmcsherry, I don't follow at all. What do you mean by "committing"?

**Comment by frankmcsherry** [comment]
Well, this PR changes the order in which NULLs sort. I could imagine we change it back again (ok, probably not, but who knows). If we commit (publicly, privately) to a certain order then other parts of the system can do a few more things, and may silently break if anyone changes things back again.

**Comment by benesch** [comment]
Oh, I see. Yeah, I mean, SQL allows you to say `NULLS FIRST` or `NULLS LAST` as you like, so... I'd personally be nervous about making any commitments about the order in which nulls sort.

**Comment by philip-stoev** [comment]
For ease of randomized testing, our default NULL ordering  should match Postgres' , which is what this change accomplishes.

**Review by philip-stoev — APPROVED** [review]
This change was tested when I tested Frank's PR and it seems to bring our behavior in alignment with Postgres. 

As there are existing tests that show the change in action, there is nothing more for me to add here.

**Comment by philip-stoev** [comment]
Regarding this error:

```

github-5984.td:32:1: error: non-matching rows: expected:
--
  | [["0"]]
  | got:
  | [["1"]]
  | Diff:
  | row missing: ["0"]
  | extra row: ["1"]
  |  
  | \|
  | 31 \|
  | 32 \| > SELECT COUNT(*) FROM t1 WHERE f1 = ( SELECT t2 . f1 FROM t3 LEFT JOIN t2 ON ( t3 . f1 = t1.f1 ) ORDER BY 1 LIMIT 1);
  | \| ^

```

The new result is correct and expected.

**Review by uce — COMMENTED** [review]
LGTM mod test failures.

@benesch I ran into the problem while working on #6402, e.g. it also affects things like

```
postgres=# SELECT ARRAY[1] > ARRAY[NULL]::int[];
 ?column?
----------
 f

vs.

materialize=# SELECT ARRAY[1] > ARRAY[NULL]::int[];
 ?column?
----------
 t
```

If you are busy, I'm happy to take this over and update the failing tests.

**Comment by benesch** [comment]
@uce, that would be fantastic!

**Comment by benesch** [comment]
@uce got this merged as #6809.

**Comment by uce** [comment]
Sorry for the left-over!

**Comment by benesch** [comment]
Oh my gosh, no, thank you for doing the hard work of actually making it mergeable! I'll take this deal every day of the week.

**Pull request closed without merging**
