### PR TITLE
persist: implement FromStr for ShardId

### PR DESCRIPTION
**Pull request by aljoscha**
This will allow writing down and later restoring shard ids.

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### CODE REVIEW

**Comment by danhhz** [comment]
LOL looks like we raced :) https://github.com/MaterializeInc/materialize/pull/11758

**Comment by aljoscha** [comment]
😂 
I'm happy to close mine because yours seems more thorough/complete.

**Comment by danhhz** [comment]
i think it's fine either way, but i'm happy to reopen mine if you prefer

**Comment by aljoscha** [comment]
Closed in favour of #11758

**Pull request closed without merging**
