### PR TITLE
Fail with a nicer error message when building outside a git repo

### PR DESCRIPTION
**Pull request by umanwizard**

### CODE REVIEW

**Comment by ruchirK** [comment]
Amazing

**Comment by quodlibetor** [comment]
So we did do this intentionally and consciously, and I'd currently rather say that we don't support building outside of the git repo than support accidentally building without this info.

**Comment by quodlibetor** [comment]
Instead of doing this you are intended to build by explicitly setting the `MZ_BUILD_SHA` variable, I believe.

**Comment by benesch** [comment]
Can we not just echo to stderr here? Lemme see.

**Comment by umanwizard** [comment]
This doesn't actually work, see commit message in 8ec395dfb9c529a05421c91085c6af1858d4268f

**Pull request closed without merging**
