### PR TITLE
docs: document unqualified delete as a workaround to truncation

### PR DESCRIPTION
**Pull request by sjwiesman**

### CODE REVIEW

**Review by petrosagg — APPROVED** [review]

**Comment by morsapaes** [comment]
`DELETE` logs an entry in the transaction log for each deleted row; do you foresee possible implications downstream in Materialize for very large tables, @petrosagg? Not against documenting this as a workaround, but there are some implications also for the upstream database that might make it a non-viable option for users.

**Comment by sjwiesman** [comment]
@petrosagg please correct me if I’m wrong, but it should be exactly the same in mz as the initial snapshot, just deletes instead of inserts

**Comment by sjwiesman** [comment]
> From my experience, it's also normal to truncate certain tables e.g. on a daily basis, but you don't necessarily want to retract the state downstream (and instead continue incrementing on it).

i think this is currently out of spec? We currently error on unsupported commands today, because the source intends to perfectly reflect the upstream db. Ignoring certain operations, and getting out of sync, feels like a bigger product question

**Comment by morsapaes** [comment]
Oh, I totally meant that what I'd prefer to see here is a link to an issue with the product spec for `TRUNCATE` events (which is a DDL operation). Just pointing out that it's a common operation and I'm not sure to what extent `DELETE` is interchangeable for all use cases; if so far you see users mostly truncating tables upstream for testing purposes, and truncating tables isn't a routine operation in their production environments, then 🖖 .

**Pull request merged**
