### PR TITLE
dataflow,expr: change bigint sums to output numerics

### PR DESCRIPTION
**Pull request by ruchirK**
Touches #5218

Previously, sums over bigints would return bigints as output. These sums could
overflow in simple examples. This commit changes the behavior to match Postgres
precedent and return numerics, which are a wider accumulator.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5281)

### CODE REVIEW

**Comment by ruchirK** [comment]
This pr still needs:

documentation + release notes.

It's also likely to have performance impacts due to https://github.com/MaterializeInc/materialize/issues/4171 and i am pretty sure its a backwards compatibility breaking change for the catalog

**Review by frankmcsherry — APPROVED** [review]
I can confirm that `reduce.rs` looks great to me. The other changes look good too, but I have less confidence in the totality of their coverage!

**Comment by ruchirK** [comment]
@frankmcsherry and / or @benesch: whats our policy for handling catalog backwards incompatibility and potential perf regressions from changes like this? For the catalog backwards incompatibility do I need to do anything other than note the change in the release notes?

For the perf regression - I'm not sure the best place to tell users "consider casting your sums to int8s if you're not stress testing mz"

**Review by benesch — APPROVED** [review]
🎉

**Comment by benesch** [comment]
Yeah, adding the warning to the release note like that is perfect. I don't think we need to do anything else.

**Pull request merged**
