### PR TITLE
Optimize outer equijoin planning

### PR DESCRIPTION
**Pull request by frankmcsherry**
This PR introduces a new plan for outer equijoins that can use substantially less memory than our general plan. For a detailed discussion of the differences, consult #2732. This PR plans outer joins using the second technique there, which I'll sketch here (the code should be improved and commented well enough to make this entirely clear).

In addition to computing the inner join of `left` and `right`, we determine those key columns in `left` that are not present in `right`, and vice versa. For each, we perform another join that picks out of `left` those rows whose key columns are not present in `right` (by matching an element in the above set) and vice versa, and then extend each with null values as appropriate.

This is still very preliminary, and is mostly me bringing some old code up to date. We will want to stitch this in to the join planning, optionally if conditions are met, and also double and triple check its correctness, and that it produces not-insane plans.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4047)

### CODE REVIEW

**Comment by benesch** [comment]
Seems reasonable to me! Let's wire it up and see what breaks!

**Comment by frankmcsherry** [comment]
The planning is now stitched in. It is almost certainly wrong, because I realize that I did nothing special about the case where we find `null` in the equality test, and at the least that shouldn't match, but actually I have no clue what it does. Maybe it just means they need to be filtered out.

**Comment by frankmcsherry** [comment]
Starting up a full SLT build to see if we can learn a bit about this.

**Comment by wangandi** [comment]
We have no tests containing `explain plan for ...` queries whose results have changed as a result of this change?

**Comment by frankmcsherry** [comment]
It seems like maybe we do not. I was expecting Q15 to break, for example. Will investigate!

**Comment by frankmcsherry** [comment]
Ah, Q13 has a weird join condition and so does not benefit from the new planning. 
```
            customer LEFT OUTER JOIN orders ON
                c_custkey = o_custkey
                AND o_comment NOT LIKE '%special%requests%'
```
So, even though we could eventually push `o_comment NOT LIKE '%special%requests%'` down in to `orders`, we cannot do it at the time that we turn the outer join in to an inner join plus parts.

**Comment by benesch** [comment]
> Ah, Q13 has a weird join condition and so does not benefit from the new planning.
> 
> ```
>             customer LEFT OUTER JOIN orders ON
>                 c_custkey = o_custkey
>                 AND o_comment NOT LIKE '%special%requests%'
> ```
> 
> So, even though we could eventually push `o_comment NOT LIKE '%special%requests%'` down in to `orders`, we cannot do it at the time that we turn the outer join in to an inner join plus parts.

Yeah, this strikes me as perfect example of why it would be great to have outer joins representable in `expr::RelationExpr`.

**Comment by frankmcsherry** [comment]
That's I think a more complicated discussion. Outer joins are different enough from inner joins that life becomes hard for many things. I can understand wanting to have `sql::RelationExpr` represent them, and admit optimizations, but they are sufficiently removed from the properties of differential dataflow operators to make their manipulation and optimizations frustrating.

**Comment by benesch** [comment]
> they are sufficiently removed from the properties of differential dataflow operators to make their manipulation and optimizations frustrating

They don't strike me as so bad. It seems like most of the optimizations in the `transform` crate on joins would be immediately applicable. But I agree that there is a class of physical optimization that doesn't want to think about outer joins.

Anyway, I just wanted to surface that we are reaching the point where someone needs to sit down and rigorously define the stages of our optimization pipeline. There are optimizations that apply during planning, optimizations that apply after planning but before decorrelation, optimizations that apply during decorrelation, optimizations that apply to a single RelationExpr in the transform crate, some whole-dataflow optimizations in the transform crate, and then ad-hoc optimizations that occur during render time. It's pretty hard to reason about.

**Comment by frankmcsherry** [comment]
Full SLT looks clean. https://buildkite.com/materialize/sql-logic-tests/builds/4868

I'm going to add some planning tests for outer joins, in part so we can see what they look like.

**Pull request merged**
