### PR TITLE
persist-txn: Simplify data_listen_next

### PR DESCRIPTION
**Pull request by jkosh44**
This commit simplifies data_listen_next so that it directly outputs data remap entries, instead of operators translating it's output to data remap entries.

Touches #22173

### Motivation
This PR refactors existing code.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [X] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [X] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - There are no user-facing behavior changes.

### CODE REVIEW

**Comment by jkosh44** [comment]
@danhhz If we want to move forward with this, then it'd be nice to get it into the release today. I'm not 100% sold that this ended up much simpler than the current approach, but I also don't have very strong feelings and am fine merging it.

**Comment by jkosh44** [comment]
One of my main concerns is that with the current approach, `data_listen_next` can sometimes return the wrong result. Specifically if the phyiscal upper corresponds to a write that has been applied and tidied, it will mistakenly give back the wrong physical upper. It's up to the caller to resolve this issue, which is a little scary. The previous approach does not have this issue.

**Comment by jkosh44** [comment]
Another approach I've been playing around with is something like the following pseudo code:

```Rust
impl TxnCache {
  pub fn data_physical_upper(&self, data_id: &ShardId, logical_upper: &T) -> T {
    let data_times = self.datas.get(data_id);
    if data_timest.latest_reg().forget_ts.is_some() {
      // Shard is not registered.
      self.progress_exclusive.clone();
    } else {
      data_times..latest_physical_ts().clone();
    }
  }
}

fn txn_progress_source_operator() {
  // ...
  let subscribe = ... ;
  loop {
    let progress = txns_cache.update_gt(&subscribe.remap.logical_upper).await;
    cap.downgrade(&subscribe.remap.logical_upper);
    subscribe.remap.logical_upper = progress.clone();
    let physical_upper =
        txns_cache.data_physical_upper(&subscribe.data_id, &subscribe.remap.logical_upper);
    if physical_upper > subscribe.remap.physical_upper {
        subscribe.remap.physical_upper = physical_upper;
        remap_output.give(&cap, subscribe.remap.clone()).await;
    }
  }
}
```

This suffers from the same problem of potentially giving the wrong answer though.

For now I'll close this PR and when the txn shard starts tracking the latest write for all shards we can revisit.

**Comment by danhhz** [comment]
Sgtm!

**Pull request closed without merging**
