### PR TITLE
sql: Have `CastStringToList` actually propagate nulls

### PR DESCRIPTION
**Pull request by ParkMyCar**
**_work in progress_**

### Motivation

Fixes https://github.com/MaterializeInc/database-issues/issues/7802

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by benesch — COMMENTED** [review]
This looks good to me! Thank you! I think this is good to merge if tests pass and you toss in the reproduction example as a SLT.

**Comment by sploiselle** [comment]
I introduced this bug [here](https://github.com/MaterializeInc/materialize/pull/7315/files#diff-6803539c802e2aee474fb1c0fab29db55cfb9e4d4bd3797509b7f18971f1480bR4097-R4100). I think there might also be some other casts that are in a similar situation––will pull these changes down and verify.

**Comment by sploiselle** [comment]
I included a potential fix for the inability to cast multiple `NULL` literals to different types. tbd if that wreak havoc on planning or is an isolated fix.

**Comment by sploiselle** [comment]
This change makes some minor differences to a few plans. Gonna run nightlies and see if anything more dramatic shakes out.

**Review by mjibson — APPROVED** [review]

**Comment by sploiselle** [comment]
@MaterializeInc/testing This PG output inconsistency is due to the way Rust vs. Postgres perform ordering operations.

MZ

```
materialize=> select '0'::text::text < '-1'::text;
 ?column? 
----------
 f
(1 row)

materialize=> select '0'::text::text < '-'::text;
 ?column? 
----------
 f
(1 row)
```

PG:

```

postgres=# select '0'::text::text < '-1'::text;
 ?column? 
----------
 t
(1 row)

postgres=# select '0'::text::text < '-'::text;
 ?column? 
----------
 f
(1 row)
```

Is this a known issue? Can only assume so. And can one of y'all help me understanding `misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py` so that I can ignore this failure?

**Comment by nrainer-materialize** [comment]
> Is this a known issue? Can only assume so. And can one of y'all help me understanding `misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py` so that I can ignore this failure?

I will take that over!

**Comment by nrainer-materialize** [comment]
> This PG output inconsistency is due to the way Rust vs. Postgres perform ordering operations.

I was not aware of this particular case but it is somewhat related to https://github.com/MaterializeInc/materialize/issues/22002.

**Comment by nrainer-materialize** [comment]
> This PG output inconsistency is due to the way Rust vs. Postgres perform ordering operations.

@sploiselle: By the way, where did you spot this one? I noticed that the framework does not use this operator yet (but I will add it now).

**Pull request merged**
