### PR TITLE
sql-parser: fix merge skew

### PR DESCRIPTION
**Pull request by aljoscha**

### CODE REVIEW

**Review by uce — APPROVED** [review]
LGTM.

The renaming was done in https://github.com/MaterializeInc/materialize/commit/4149bc1dd3cf80abcddcb8fe3583d30f2726c23a.

**Comment by aljoscha** [comment]
Pushed some more changes because the first one didn't catch all of it. @benesch Is this still the intended change?

**Review by guswynn — APPROVED** [review]
No idea how this skew happened, but yeah, #14423 changed `INTROSPECTION GRANULARITY` to `INTROSPECTION INTERVAL`, and we want timestamp's language to match

**Review by benesch — APPROVED** [review]
Whooops! Something went very wrong here. Thank you very much! This looks great.

**Pull request merged**
