### PR TITLE
Revert "Merge pull request #14704 from danhhz/persist_empty_antichain"

### PR DESCRIPTION
**Pull request by benesch**
Testing a theory about the nightly failures. Will trigger a nightly build on this branch.

### CODE REVIEW

**Comment by benesch** [comment]
Nightly build: https://buildkite.com/materialize/nightlies/builds/1521

**Comment by benesch** [comment]
So, turns out this _was_ the cause of the nightly failures. @danhhz leaving it up to you whether you'd like to merge this as is, or take a stab at fixing it. We can consider the question of whether to backport into the release vs skipping the release separately!

**Comment by danhhz** [comment]
Let's revert. It's easy enough to unrevert and then the time pressure is off

**Comment by benesch** [comment]
Sounds great. Done!

**Pull request merged**
