### PR TITLE
Use timestamp zero for tails of unmaterialized sources/views

### LINKED ISSUE #2519: TAIL ad hoc SELECT queries
TAIL currently is only possible on materialized views. A prospect asks if we could add support for TAILing ad hoc SELECT queries.

### PR DESCRIPTION
**Pull request by frankmcsherry**
This PR changes the behavior on TAIL requests for collections that are not materialized. Previously, we would error as we could not determine a time to tail *from*. Now, we use zero as the time.

This PR isn't ready to land, for reasons including it isn't clear that we want to do this (probably fine), and there aren't any tests yet (will have to skill up on the right way to test TAIL; I'm sure there are examples I can read!).

fixes #2519

### CODE REVIEW

**Comment by frankmcsherry** [comment]
This PR is wrong at the moment because tail uses `less_than` rather than `less_equal`. I'm not sure about the motivation for that, especially as it is provided with the `upper` timestamp from the materialized trace, which is the next time to be produced (not the most recent time produced). That's probably been a non-issue before, with streaming data and not a particular spec, but probably the right thing to do is use a frontier and report things greater_equal the frontier?

Any thoughts @umanwizard?

**Comment by benesch** [comment]
Tail tests are Rust integration tests in the materialized create: https://github.com/MaterializeInc/materialize/blob/68222a04c28029ca9816e0abf3f3ac3204abcb72/src/materialized/tests/sql.rs#L101-L154

They get much simpler after #2518, which is why I linked you to the post-#2518 world above.

Regarding this point:

> This PR is wrong at the moment because tail uses `less_than` rather than `less_equal`. I'm not sure about the motivation for that, especially as it is provided with the `upper` timestamp from the materialized trace, which is the next time to be produced (not the most recent time produced). That's probably been a non-issue before, with streaming data and no particular spec, but probably the right thing to do is use a frontier and report things greater_equal the frontier?

I think I can answer this question with your comment from six months ago:

> I strongly recommend `t.less_than` here, for two reasons:
> 
> 1. The `PartialOrder` trait is the reference way to compare timestamps. For partially ordered timestamps (not what we have, I know) using Rust's operators produces the wrong answer (long story; they are bad).
> 2. Peek currently accumulates "less equal", and if we want Tail to complement it we should pick up complementary updates.

https://github.com/MaterializeInc/materialize/pull/427#discussion_r321417174

**Comment by frankmcsherry** [comment]
> I think I can answer this question with your comment from six months ago:
 
Oh ho! :D

Some things have definitely changed, I think. Peek currently accumulates "less than" as we subtract one from times before using them. Either one probably works, but it leaves us in a weird spot at the moment that if you do both Peek and Tail, you'll just miss updates exactly at `upper` because it is not strictly greater than the time we pick for tail, nor less equal the time picked for peek.

I'll try to write something up putting these two in sane positions relative to each other. I think the constraints should probably be that they span all updates, and that peeks can return immediately. That means either change to `less_equal` for tail or subtract one from its timestamp. Await further transmissions!

**Comment by frankmcsherry** [comment]
I've just gone and changed TAIL to use `less_equal`, which I think is most sane. With `less_than`, you would not see updates that occur at the present `upper`, which is still in the future for the stream. This also makes it line up with PEEK, and allows one to TAIL non-materialized sources and views.

Still not tested, though.

**Comment by frankmcsherry** [comment]
I'm not certain how best to test this (if we have existing TAIL tests I'd be happy to add them in). It seems that `TAIL` commands cause testdrive to error out with unexpected responses.

What I did verify was that
```
materialize=> create view test as select true;
CREATE VIEW
materialize=> tail test;
t       Diff: 1 at 0
materialize=> 
```
which is a tail of a non-materialized thing. It would previously error with a complaint about tailing a non-materialized item, and now just produces a reasonable output.

**Comment by benesch** [comment]
> Tail tests are Rust integration tests in the `materialized` crate:
> 
> https://github.com/MaterializeInc/materialize/blob/be3aab363d17bda72db07d02ee5dde6191d57588/src/materialized/tests/sql.rs#L101-L154

@frankmcsherry could you add a test in that vicinity? Testdrive doesn't want to be in the business of testing TAIL, since it's complicated. (Not clear when you want to abort the tail, specifically.)

**Comment by frankmcsherry** [comment]
Will do

**Pull request merged**
