### PR TITLE
dev: Update .cargo/config to reserve 1 CPU core

### PR DESCRIPTION
**Pull request by parker-timmerman**
### Motivation
Not a necessary change, but something I thought would be nice :)

Setting `jobs = -1` in our `.cargo/config` file will limit the number of threads Cargo uses to `num_cpus() - 1`, this way when doing a ton of compilation we don't totally max our our CPU and can still do other things with less disruption than would be today.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by benesch** [comment]
Makes sense to me, but is there a way to not do this in CI, since we want to use all available cores there?

**Comment by benesch** [comment]
(Maybe setting `CARGO_NUM_JOBS` in the Buildkite build job?)

**Comment by parker-timmerman** [comment]
Great call on CI, we could set the `CARGO_NUM_JOBS` env variable, but I'm not sure what we'd set it to since there's no way to set it back to the "default" value. Setting it to 0 would cause cargo to hang, and setting it to something arbitrarily high like 64 or 128 results in cargo actually starting that many jobs on parallel, which could impact filesystem resources (too many open handles).

A somewhat hacky approach could be to do `export CARGO_NUM_JOBS="$(getconf _NPROCESSORS_ONLN)"` which will set the number of jobs back to the num cpus?

Setting back to the default feels like something cargo should support, so I opened https://github.com/rust-lang/cargo/issues/11816 and we'll see what folks think

**Review by benesch — APPROVED** [review]
Gotcha! Since it's hard to undo this in CI, I think it's fine to roll with it as is. Probably compiling is noisy enough that we won't really notice.

**Comment by parker-timmerman** [comment]
Sounds good to me! If we're ever able to land a feature in cargo to undo the setting, I'll come back to the PR

**Pull request merged**
