### PR TITLE
persist: impl Codec64 for Product<u32, u32>

### PR DESCRIPTION
**Pull request by danhhz**
Given that we've been talking about persist's handling of partial orders recently, seems like a reasonable thing to have around for tests and such.

All credit to Petros for the idea and impl.
https://github.com/petrosagg/materialize/commit/0145c428f59b4888b5370c531e256458310dfc70

### Motivation

  * This PR adds a feature that has not yet been specified.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by bkirwi — COMMENTED** [review]
IIUC this is more or less equivalent to: https://github.com/MaterializeInc/materialize/blob/a8f645065f2534f422524d0078b36c832d2b7cfd/src/persist-client/src/lib.rs#L690

I think I prefer what you have here, but it would be nice to dedup in either case!

**Review by petrosagg — APPROVED** [review]
Nice! Agreed with Ben on deduplicating

**Comment by danhhz** [comment]
Ha! Okay I'd thought that we had something for testing partial orders in persist. I feel less crazy now.

Duplication removed. TFTRs!

**Review by bkirwi — APPROVED** [review]
Beautiful, thanks!

**Comment by danhhz** [comment]
TFTRs!

**Pull request merged**
