### PR TITLE
test: Several small test fixes to get nightly green

### PR DESCRIPTION
**Pull request by ParkMyCar**
Before cutting the `v0.80` release we want to get Nightly green

Included is a hack to get a previously unstable, now totally deleted, Kafka connection config option working. We used to support writing `TOPIC METADATA REFRESH INTERVAL MS 500` now we support only `TOPIC METADATA REFRESH INTERVAL = '500ms'`. To get environments that might have had the old syntax (it was an unstable option so there shouldn't be any) we support parsing the `MS` keyword and then in a Catalog migration swap from a number `500` to the string `500ms`.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - N/a test only fixes

### CODE REVIEW

**Comment by jkosh44** [comment]
I don't know if this has already been discussed at length, but I would vote to delete/update the tests to not test `TOPIC METADATA REFRESH INTERVAL MS 500` instead of adding hacks to the code to get the tests passing. Especially considering that this option never existed in prod.

**Comment by ParkMyCar** [comment]
That works for me, but I'm also unfamiliar with how likely it is someone might have this option enabled. Any thoughts @benesch or @sploiselle?

**Comment by sploiselle** [comment]
😱 I did not realize this was never available in prod--if so we should just delete these tests (ehhh) or only run them on versions >= 0.80.0-dev w/ the new strings. I can do this tonight if someone else doesn't claim the work.

**Comment by sploiselle** [comment]
Ok--starting in on this.

**Comment by jkosh44** [comment]
Just to double check, can anyone here say definitively if it's possible that this was enabled in prod or not? 

I am not familiar enough with this to be able to say that.

**Comment by sploiselle** [comment]
@jkosh44 yes; this is from LD's prod feature flag section

Screenshot 2023-12-14 at 7 55 41 PM

**Comment by benesch** [comment]
Oh, definitely don't delete them! The tests aren't actually interested in testing the behavior of TOPIC METADATA REFRESH INTERVAL. They're interested in testing the behavior of adding parts to Kafka topics. But the default topic metadata refresh interval of 5m is fine in prod but excruciating in tests. So the tests turn the refresh interval way down in order to complete in a reasonable amount of time.

**Comment by ParkMyCar** [comment]
@sploiselle your changes to the `multiple_partitions.py` test look good to me, thanks for adding that! We retain the test but only run it for new versions to avoid the problem of the changing syntax 👍

I also just pushed up two more fixes:

1. We were hitting a WARN that was tripping CI. We already had an exception for this WARN, but it was too restrictive, I relaxed it.
2. I removed the check for `SHOW CREATE SINK upgrade_kafka_sink;` from the legacy upgrade tests for versions >= v0.80, as-is this we can never get this check to pass. The reason being, the new syntax we check for `LEGACY IDS = true` will only get added if we run through the Catalog migration, but this only happens for versions <= 0.79. AFAIU the legacy upgrade framework will also test v0.80 -> main, in which case the check would fail because we wouldn't run the Catalog migration to add that bit of syntax.

I'll kick off another Nightly and if it passes cut the build!

**Review by jkosh44 — APPROVED** [review]

**Comment by nrainer-materialize** [comment]
Thanks for continuing this, @ParkMyCar!

**Pull request merged**
