### PR TITLE
Implement constant folding for TopK operators

### PR DESCRIPTION
**Pull request by aalexandrov**
### Motivation

  * This PR adds a known-desirable feature. [#7339]

### Description

See commit messages for details.

### Tips for reviewer

The main part to be reviewed is the new `FoldConstsants::fold_topk_constant` method in `reduction.rs`. We need to ensure that the corner-case semantics of the compile-time implementation and the DD operator coincide. In particular:

- The `fold_topk_constant` implementation is not well-defined if `order_key` is empty.
- We need to ensure that we are producing errors in all cases that the DD operator will as well (e.g. for records with negative `diff`).

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] ~This PR adds a release note for any user-facing behavior changes.~ (not needed)

### CODE REVIEW

**Comment by aalexandrov** [comment]
I will migrate [the queries from this Google doc](https://docs.google.com/spreadsheets/d/1O6oQ0q8XqYL5Mz7dvXw3GQ40u6yq-Y61jm4cQOn4ARU/edit?usp=sharing) as test cases tomorrow. Note that the results of Q1 and Q5 do not coincide with Postgres due to the missing explicit `ORDER BY` clause.

**Comment by philip-stoev** [comment]
Item #1. Panic in this branch:

```
aterialized v0.9.9-dev (01f5e2f47) listening on 0.0.0.0:6875...
2021-10-17T14:12:17.779756Z ERROR panic: constant folding encountered reduce on collection with non-positive multiplicities
thread: coordinator
location: src/transform/src/reduction.rs:438:13
version: 0.9.9-dev (01f5e2f4729a817d63160ef9f8714282114939f4)
backtrace:
```

test case:

```

CREATE VIEW t1 (f1, f2) AS (VALUES (NULL, 0), (1, 1), (1, 1), (2, 2),  (2, 2), (3, 3), (4, 4), (5, 5), (6, 6),(7, 7),(8, 8));

CREATE VIEW t2 (f1, f2) AS (VALUES (NULL, 0),(NULL, 0),(1, 1),(2, 2), (2, 2),(4, 4), (5, 5),(6, 6),(7, 7),(8, 8));

SELECT  FROM (  SELECT  FROM t2 a1  RIGHT JOIN t1 a2  ON a1 .f1  = a2 .f2  ) group by true; 
```

The `TRUE` predicate was originally much more complex, but after automatic simplification it turns out that `TRUE` is enough. LEFT JOIN and inner joins not affected.

**Comment by philip-stoev** [comment]
Item No2. Panic in this branch:

```
2021-10-17T14:16:37.948943Z ERROR panic: index out of bounds: the len is 2 but the index is 2
thread: coordinator
location: src/transform/src/map_lifting.rs:160:46
version: 0.9.9-dev (01f5e2f4729a817d63160ef9f8714282114939f4)
```
Query:
```
SELECT  TRUE  , a1  , a2  FROM t2 a1  LEFT  JOIN (  SELECT  8 f1  , f1 f2  FROM t2  ) a2  ON a2 .f2  + a2 .f1  <  9  GROUP  BY  2  ,  3  ```

**Comment by philip-stoev** [comment]
ItemNo3. Same panic as above, but without an outer join and without derived tables:

```
SELECT  TRUE  , a1  , a2  FROM t2 a1  JOIN t2 a2  ON  TRUE  WHERE  TRUE  AND  NOT a2 .f1  +  4  NOT  IN (  8  ,  7  )  GROUP  BY  2  ,  3   : 
```

**Comment by philip-stoev** [comment]
Item No3. This is actually *fixed* in this branch. In the prior commit, the GROUP BY was not properly applied and the end result set contained duplicates:

```
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
CREATE VIEW t1 (f1, f2) AS (VALUES (NULL, 0), (1, 1), (1, 1), (2, 2),  (2, 2));
CREATE VIEW t2 (f1, f2) AS (VALUES (NULL, 0),(NULL, 0),(1, 1),(2, 2), (2, 2));

SELECT f2  FROM t2  RIGHT  JOIN (  SELECT  TRUE  )  as r ON  TRUE  WHERE  TRUE  OR  4  < (  SELECT c2  FROM (  SELECT f2 c2  FROM t1  ) as a1  LIMIT  1  ) GROUP  BY  1;
```

**Pull request merged**
