### PR TITLE
storage/copy-to-s3: Get deterministic ordered-stream of consolidated updates

### PR DESCRIPTION
**Pull request by rjobanp**
### Motivation

  * This PR adds a known-desirable feature. Fixes https://github.com/MaterializeInc/materialize/issues/25835

Addresses this comment on the copy-to-s3 multiworker PR https://github.com/MaterializeInc/materialize/pull/25785#discussion_r1515381757

### Tips for reviewer

The diff is much smaller if viewed with whitespace hidden, there were a few formatting changes that make it look larger than it is.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by antiguru** [comment]
If this can wait, I'd like to give it a thorough review once I'm back next week. The change introduces additional allocations in the non-raw path which we have to be careful with. While the PR clearly fixes a problem of relying on undefined behavior, the behavior is in fact fifo for pipeline streams, so there doesn't seem to be any urgency to land this change. Please correct me if I'm wrong.

**Comment by rjobanp** [comment]
Correct, no urgency! Just addressing your feedback on the last PR. This can wait till it can be reviewed more thoroughly

**Review by petrosagg — COMMENTED** [review]
deferring my review to Moritz

**Comment by rjobanp** [comment]
chatted with @antiguru and @frankmcsherry offline -- we've decided to close this PR since it doubles the memory required for the consolidated collection (due to the extra `filter_map` in `consolidate_pact`). Instead, we'll live with the assumption that Pipeline edges are FIFO for now, even though this is not technically guaranteed. We'll also try to add an assert in the copy-to-s3 operator that rows are sorted, which should allow us to detect any regression in this behavior in the future.

**Pull request closed without merging**
