### PR TITLE
render: optimize topk when limit=1 and input is monotonic (append-only)

### LINKED ISSUE #5996: Optimize `LIMIT 1` for append-only collections
When we apply `TopK` with a limit of one, we can at least use the semigroup rendering tricks we use for `min` and `max` to avoid constructing feedback loops for garbage collection. Top1 is a not-uncommon idiom for programming "upsert"-like fragments, and shaving off the factor of 8x the hierarchical reduction imposes is worth doing.

cc: @ruchirK

### PR DESCRIPTION
**Pull request by danhhz**
If the input to a TopK is monotonic (aka append-only aka no retractions)
then we don't have to worry about keeping every row we've seen around
forever. Instead, the reduce can incrementally compute a new answer by
looking at just the old TopK for a key and the incremental data. We do
an identical optimization for MIN and MAX of monotonic sources.

This optimization generalizes to any TopK over a monotonic source, but
we special case only TopK with offset=0 and limit=1 (aka Top1) for now.
This is because (1) Top1 can merge in each incremental row in constant
space and time while the generalized solution needs something like a
priority queue and (2) we expect Top1 will be a common pattern used to
turn a Kafka source's "upsert" semantics into differential's semantics.
(2) is especially interesting because Kafka is monotonic with an
ENVELOPE of NONE, which is the default for ENVELOPE in Materialize and
commonly used by users.

Closes #5996

### CODE REVIEW

**Comment by philip-stoev** [comment]
I will try to test this a little bit if you do not mind. Hence I am adding myself as a reviewer, will hit "Approve" as soon as I am done. Thank you.

**Review by philip-stoev — APPROVED** [review]
I must admit I achieved exactly zero understanding about how this optimization works, but I did the following:

- added a ```println!``` to make sure that it gets triggered in first place, as there is no way to otherwise to observe that. This is a persistent problem that afflicts a lot of optimizations in the code.
- 
- pushed a testdrive test that uses materialized views against kafka sources, in contrast with the SLT test that does SELECTS against a VALUES view. I hope the two tests are thus complimentary. If you do a force push to the branch, please do not forget about the commit that has the test.
- manually borked the ```optimize_dataflow_monotonic``` function so that standard tables are considered monothonic sources (which they currently actually are, since we only allow INSERTS against them), and then ran a randomized workload with randomly-generated materialized views in the face of random insertions. No wrong results were observed.

**Review by ruchirK — APPROVED** [review]
These changes look good to me! I think trying to cache the unpacked version of the top element makes sense.

I have a larger question about the way we do topk which is - I don't understand why we keep the topk computation as a local collection where we keep the reduce computations as local arrangements. this is obviously out of scope for this pr but I think it means that if say, we wanted to join the results of a topk with something else we would need to make another arrangement?

**Review by danhhz — COMMENTED** [review]
Thanks for the tests @philip-stoev!

> These changes look good to me! I think trying to cache the unpacked version of the top element makes sense.

As discussed offline, the lifetime on Datum makes this hard. Left it as a followup if we see it in benchmarks.

> I have a larger question about the way we do topk which is - I don't understand why we keep the topk computation as a local collection where we keep the reduce computations as local arrangements. this is obviously out of scope for this pr but I think it means that if say, we wanted to join the results of a topk with something else we would need to make another arrangement?

Makes sense at a high level, but i don't understand enough of the specifics yet to have an opinion. Lets follow up on this.

> added a println! to make sure that it gets triggered in first place, as there is no way to otherwise to observe that. This is a persistent problem that afflicts a lot of optimizations in the code.

I'm 100% with you on this. I've already pitched a couple people on the idea of a data-driven  test for mir->dataflow like the sql logic stuff stuff. Regardless of the specific outcome, I agree there's something to be done here. I'll file an issue

> manually borked the optimize_dataflow_monotonic function so that standard tables are considered monothonic sources (which they currently actually are, since we only allow INSERTS against them), and then ran a randomized workload with randomly-generated materialized views in the face of random insertions. No wrong results were observed.

Exactly, because TABLES don't yet support DELETE or UPDATE, we're actually fine without the check. If we comment out the `*monotonic` in the optimization check and simulate adding DELETE/UPDATE support to materialize by using the postgres passthrough mode of sqllogictest, then we can trigger the `diff > 0` assertion in the code I added.

```mode cockroach

statement ok
CREATE TABLE cities (
    name text NOT NULL,
    state text NOT NULL,
    pop int NOT NULL
)

statement ok
INSERT INTO cities VALUES
    ('Los_Angeles', 'CA', 3979576),
    ('San_Francisco', 'CA', 881549)

statement ok
CREATE MATERIALIZED VIEW topk AS SELECT state, name FROM
    (SELECT DISTINCT state FROM cities) grp,
    LATERAL (SELECT name FROM cities WHERE state = grp.state ORDER BY pop DESC LIMIT 1);

mode cockroach

query TT rowsort
SELECT * FROM topk;
----
CA  Los_Angeles

statement ok
DELETE FROM cities WHERE name = 'Los_Angeles';

query TT rowsort
SELECT * FROM topk;
----
CA  San_Francisco
```

**Review by ruchirK — APPROVED** [review]
this all looks great and ready to merge!

**Comment by ruchirK** [comment]
> I must admit I achieved exactly zero understanding about how this optimization works, but I did the following:

We can talk about it more but at a high level differential keeps around

`(data, time, diff)` triples for all the data, and accumulates various updates at various other times into a single `diff` (so e.g. if at `time2` you received `(data, time2, diff2)` and then at `time3` you received `(data, time3, diff3)` then if you queried the system at `time3` you would see

`(data, time3, diff plus diff2 plus diff3)`

Normally, the `diff`s are integers corresponding to the multiplicity of the data, and `plus` is just normal signed integer addition so `diff plus diff2 plus diff3` represents "the multiplicity or count of `data` at `time3`".

But `diff` doesn't have to be an integer and `plus` doesn't have to be integer addition. These changes make it so that `diff` represents "potential rows where we want the top row according to some order" and `plus` represents "comparison based on that order" so that `diff plus diff2 plus diff3` represents "the top row at `time3`"

I hope that at least partially helps!

**Comment by danhhz** [comment]
Thanks for the reviews!

**Comment by danhhz** [comment]
> I've already pitched a couple people on the idea of a data-driven test for mir->dataflow like the sql logic stuff stuff. Regardless of the specific outcome, I agree there's something to be done here. I'll file an issue

@philip-stoev Filed this as #6482

**Pull request merged**
