### PR TITLE
add feature flag to always enable disk on kube replicas

### PR DESCRIPTION
**Pull request by pH14**
Adds a quick feature flag, `cluster_always_use_disk` that informs the KubernetesOrchestrator to always provision a cluster with disk, even without the `DISK` option. This will make it easier to roll out `lgalloc`, though we'll want to be mindful of how it impacts upsert sources, since they switch to using spill2disk if they detect the scratch directory.

I'm not 100% sure I grok all the implications of forcing disk within the Orchestrator, rather than doing it within the catalog. Would appreciate if someone could double check that it's reasonable to do!

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by antiguru** [comment]
qq: How does this relate to `disk_cluster_replicas_default`? I think `disk_cluster_replicas_default` instructs the parser to produce the `DISK` option if not specified, correct?

**Review by def- — COMMENTED** [review]
Does this mean cloudtest will also run with lgalloc everywhere now? (I'm not sure if this was the case before, I just know Philip enabled lgalloc for mzcompose-based tests) We should do that before rolling it out further.

**Comment by pH14** [comment]
> qq: How does this relate to disk_cluster_replicas_default? I think disk_cluster_replicas_default instructs the parser to produce the DISK option if not specified, correct?

This is a good question! That seems like it might be the right path forward, and in retrospect, I probably don't have the bandwidth to see this one all the way through. Will close out this PR and let others drive

**Comment by benesch** [comment]
I don't think we want `disk_cluster_replicas_default`! That won't let us opt the _existing_ non-disked replicas to start using disk. I think we really do want an override here which force enables disk across the board, regardless of what value the `DISK` parameter has.

**Comment by benesch** [comment]
This PR looks right to me! @pH14 mind putting the branch back in place? I can take over driving.

**Comment by pH14** [comment]
@benesch all set, feel free to push changes here directly

**Review by benesch — APPROVED** [review]

**Comment by benesch** [comment]
> > qq: How does this relate to disk_cluster_replicas_default? I think disk_cluster_replicas_default instructs the parser to produce the DISK option if not specified, correct?
> 
> This is a good question! That seems like it might be the right path forward, and in retrospect, I probably don't have the bandwidth to see this one all the way through. Will close out this PR and let others drive

`disk_cluster_replicas_default` determines whether to use disk if the user hasn't expressed a preference. `cluster_always_use_disk` forces clusters to use disks even if the user said `DISK = false`. The latter is the tool we need here, because we _don't_ want to respect what the user requested, and instead want to give everyone disk.

> Does this mean cloudtest will also run with lgalloc everywhere now? (I'm not sure if this was the case before, I just know Philip enabled lgalloc for mzcompose-based tests) We should do that before rolling it out further.

I'll address this in a follow up PR.

----

This PR looks right to me, so I'm going to 🚢.

**Comment by benesch** [comment]
> I'm not 100% sure I grok all the implications of forcing disk within the Orchestrator, rather than doing it within the catalog. Would appreciate if someone could double check that it's reasonable to do!

I can't see anything that goes wrong with this approach, vs forcing `DISK = true` in the planner. One upside to this approach is that the `disk` column in `mz_cluster_replicas` still reflects what the user asked for.

> This seems like a good route to me, as long as we pass an additional flag/parameter to clusterd's that have the `DISK` option on (instead of just intuiting it from `--scratch-directory`

Wait, but the point is that when this flag is true all replicas that are created will behave _exactly_ as if `DISK = true` was specified—and inferring diskness from the `--scratch-directory` flag as we currently do seems A-OK! Let me know if I'm misunderstanding, but AFAICT this PR did exactly the right thing as written.

**Pull request merged**
