### PR TITLE
cargo tests: decrease parallelism

### PR DESCRIPTION
**Pull request by nrainer-materialize**
See https://materializeinc.slack.com/archives/C01LKF361MZ/p1718702899996089.

### Verification
* https://buildkite.com/materialize/test/builds/84125
* https://buildkite.com/materialize/test/builds/84126
* https://buildkite.com/materialize/test/builds/84127
* https://buildkite.com/materialize/test/builds/84128
* https://buildkite.com/materialize/test/builds/84129

### CODE REVIEW

**Review by def- — CHANGES_REQUESTED** [review]
This is the opposite. We should require more threads to reduce parallelism.

Assuming this fails relatively reliably, I'd suggest running cargo test a few times to see if the proposed workarounds work

**Review by def- — APPROVED** [review]
Are all the failing tests actually in the mz-environmentd package?

**Comment by nrainer-materialize** [comment]
> Are all the failing tests actually in the mz-environmentd package?

I'll need to double-check.

**Comment by nrainer-materialize** [comment]
Likely caused by https://github.com/MaterializeInc/materialize/blob/7deffbded0a26a2e44936fda2f4e5adfa573d9d4/src/orchestrator-process/src/lib.rs#L474-L479 so that this is not the appropriate fix.

**Pull request closed without merging**
