### PR TITLE
ci: enable sccache

### PR DESCRIPTION
**Pull request by benesch**
Word on the street is that sccache has been improved in recent years.
See if it makes CI any faster.

### Motivation

* CI is slow.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

**Comment by benesch** [comment]
@umanwizard any interest in debugging this one? :D

**Comment by umanwizard** [comment]
@benesch Yes I do have interest, but more as a skunkworks or weekend project, not high-pri. Let’s mark this as draft until I get around to it. I’ll take a look while on my flight or something maybe.

**Comment by benesch** [comment]
I figured it out. sccache insists on a stable absolute path to the build directory across CI agents, but our CI agents were configured to include the instance ID in the working directory.

**Comment by benesch** [comment]
A few minutes at best. Either sccache doesn't work very well or we haven't configured it right.

**Pull request merged**
