### PR TITLE
postgres consistency: compare timezone definitions with postgres

### PR DESCRIPTION
**Pull request by nrainer-materialize**
### Based on
* https://github.com/MaterializeInc/materialize/pull/26523
* https://github.com/MaterializeInc/materialize/pull/26524
* https://github.com/MaterializeInc/materialize/pull/26526

### Commits
ebd73bf51a output consistency: assign some operation definitions to variables
f19cc2eee2 postgres consistency: add predefined queries regarding timezones
bd7f98b8f8 tests: trim pg_catalog_timezone_names.slt and pg_catalog_timezone_names.slt

### Nightly
https://buildkite.com/materialize/nightlies/builds/7280

### Issues
* https://github.com/MaterializeInc/materialize/issues/26521

### CODE REVIEW

**Review by def- — COMMENTED** [review]
So we are actually having the exact same entries as Postgres? I was a bit worried about that.

**Comment by nrainer-materialize** [comment]
> So we are actually having the exact same entries as Postgres? I was a bit worried about that.

Yes, mostly. A few don't match, need to investigate further...

**Comment by nrainer-materialize** [comment]
> So we are actually having the exact same entries as Postgres? I was a bit worried about that.

There are a few entries that differ: https://github.com/MaterializeInc/materialize/issues/26521

**Review by def- — APPROVED** [review]
Very cool!

**Pull request merged**
