### PR TITLE
Do not merge: wiring the billing demo to send messages into a kerberized cluster

### PR DESCRIPTION
**Pull request by wangandi**
Mildly hacky setup to artificially generate 30M row topic with a kerberized cluster.

Commented out all the sink stuff since I did not want to deal with kerberizing the schema-registry.

Currently investigating why I can't get the krb5 smoke test running.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/3461)

### CODE REVIEW

**Comment by wangandi** [comment]
I can successfully authenticate the client with kafka, as evidenced by the message in the kafka logs:
```
[2020-06-24 22:38:11,502] INFO Successfully authenticated client: authenticationID=billing-demo@CI.MATERIALIZE.IO; authorizationID=billing-demo@CI.MATERIALIZE.IO. (org.apache.kafka.common.security.authenticator.SaslServerCallbackHandler)
```

But I can't create a topic in Kafka with the billing demo yet. The last several lines in the billing demo log before exiting look like this:
```
[2020-06-24T22:38:11Z WARN  rdkafka::client] librdkafka: BROKER [thrd:app]: Broker name "SASL_PLAINTEXT://kafka:9092" parse error: protocol "SASL_PLAINTEXT" does not match security.protocol setting "plaintext"
[2020-06-24T22:38:11Z INFO  rdkafka::client] librdkafka: LIBSASL [thrd:sasl_plaintext://kafka:9092/bootstrap]: sasl_plaintext://kafka:9092/bootstrap: GSSAPI client step 1
[2020-06-24T22:38:11Z INFO  rdkafka::client] librdkafka: LIBSASL [thrd:sasl_plaintext://kafka:9092/bootstrap]: sasl_plaintext://kafka:9092/bootstrap: GSSAPI client step 1
[2020-06-24T22:38:11Z INFO  rdkafka::client] librdkafka: LIBSASL [thrd:sasl_plaintext://kafka:9092/bootstrap]: sasl_plaintext://kafka:9092/bootstrap: GSSAPI client step 2
ERROR: Admin operation error: OperationTimedOut (Local: Timed out)
```

**Comment by sploiselle** [comment]
This looks like Kafka isn't running with the config you provided, i.e. it's not actually running with `SASL_PLAINTEXT`. That authentication is likely coming from KDC. Can you shell into the Kafka container and see if the config files you're placing there are actually there? There might be some more elegant command to return the currently running Kafka process' security protocol, but idk. I can also check on this in the morning.

**Comment by ruchirK** [comment]
should we close this btw? not sure if this was ever intended to eventually merge

**Comment by wangandi** [comment]
closed but not deleting the branch from my repo in case there is the need again to run this experiment.

**Pull request closed without merging**
