### PR TITLE
test: better mzcompose tests for SSH connections

### PR DESCRIPTION
**Pull request by andrioni**
Including a full end-to-end test workflow, as well as tests validating that the state stays correct after restarts, since this requires some unique interactions with the secrets store that no other catalog object does.

### Motivation

   * This PR refactors existing code: it adds better tests for SSH tunnel connections.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-protobuf` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - N/A

### CODE REVIEW

**Comment by philip-stoev** [comment]
Give me until tomorrow to wrap my head around this.

**Comment by andrioni** [comment]
Sure, no need to rush!

**Review by philip-stoev — APPROVED** [review]
Thank you, this is all very much appreciated!

Question -- will anything be different when running inside K8s? In other words, does it make sense to test this in cloudtest too (as a separate task)?

**Comment by andrioni** [comment]
>Question -- will anything be different when running inside K8s? In other words, does it make sense to test this in cloudtest too (as a separate task)?

It does make sense! The tests should work as they are, but it's good to test just in case because the secrets store used in k8s is different than the one used in local mode.

**Pull request merged**
