### PR TITLE
Optimization: Fix crash when a filter references output column of a TableFunc

### LINKED ISSUE #5520: panic when trying to join jsonb_each_text into query
### What version of Materialize are you using?

```
$ materialized -v
materialized v0.6.1 (3247686f8)
```

### How did you install Materialize?

* [x] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [ ] Built from source

### What was the issue?
Query below causes the server to panic and shutdown:

```sql
CREATE VIEW IF NOT EXISTS test AS
    SELECT 
        service.id AS service_id, 
        lgd.value AS r_value 
    FROM service
    INNER JOIN log_data ON service.id = log_data.service_id
    INNER JOIN jsonb_each_text(to_jsonb(log_data.data)) AS lgd(key, value) ON lgd.key = service.r_log_data_key;
```

### Log

I don't have a log file, but here's the panic message

```
materialize_1  | 2021-01-31T08:36:43.629149Z ERROR panic: <unnamed>: index out of bounds: the len is 37 but the index is 37
materialize_1  |    0: materialized::handle_panic
materialize_1  |              at var/lib/buildkite-agent/builds/buildkite-builders-i-0886d71176418a61b-1/materialize/tests/src/materialized/src/bin/materialized/main.rs:594:65
materialize_1  |    1: core::ops::function::Fn::call
materialize_1  |              at usr/local/lib/rustlib/src/rust/library/core/src/ops/function.rs:70:5
materialize_1  |    2: std::panicking::rust_panic_with_hook
materialize_1  |              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:581:17
materialize_1  |    3: std::panicking::begin_panic_handler::{{closure}}
materialize_1  |              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484:9
materialize_1  |    4: std::sys_common::backtrace::__rust_end_short_backtrace
materialize_1  |              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153:18
materialize_1  |    5: rust_begin_unwind
materialize_1  |              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483:5
materialize_1  |    6: core::panicking::panic_fmt
materialize_1  |              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85:14
materialize_1  |    7: core::panicking::panic_bounds_check
materialize_1  |              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:62:5
materialize_1  |    8: <usize as core::slice::index::SliceIndex<[T]>>::index
materialize_1  |              at usr/local/lib/rustlib/src/rust/library/core/src/slice/index.rs:255:10
materialize_1  |       core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
materialize_1  |              at usr/local/lib/rustlib/src/rust/library/core/src/slice/index.rs:15:9
materialize_1  |       <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
materialize_1  |              at usr/local/lib/rustlib/src/rust/library/alloc/src/vec.rs:1982:9
materialize_1  |       expr::relation::join_input_mapper::JoinInputMapper::map_column_to_local
materialize_1  |              at var/lib/buildkite-agent/builds/buildkite-builders-i-0886d71176418a61b-1/materialize/tests/src/expr/src/relation/join_input_mapper.rs:190:21
materialize_1  |       expr::relation::join_input_mapper::JoinInputMapper::split_column_set_by_input
materialize_1  |              at var/lib/buildkite-agent/builds/buildkite-builders-i-0886d71176418a61b-1/materialize/tests/src/expr/src/relation/join_input_mapper.rs:205:36
materialize_1  |    9: transform::nonnull_requirements::NonNullRequirements::action
materialize_1  |              at var/lib/buildkite-agent/builds/buildkite-builders-i-0886d71176418a61b-1/materialize/tests/src/transform/src/nonnull_requirements.rs:138:39
materialize_1  |   10: transform::nonnull_requirements::NonNullRequirements::action
materialize_1  |              at var/lib/buildkite-agent/builds/buildkite-builders-i-0886d71176418a61b-1/materialize/tests/src/transform/src/nonnull_requirements.rs:127:17
materialize_1  |   11: transform::nonnull_requirements::NonNullRequirements::action
materialize_1  |              at var/lib/buildkite-agent/builds/buildkite-builders-i-0886d71176418a61b-1/materialize/tests/src/transform/src/nonnull_requirements.rs:120:17
materialize_1  |   12: transform::nonnull_requirements::NonNullRequirements::action
materialize_1  |              at var/lib/buildkite-agent/builds/buildkite-builders-i-0886d71176418a61b-1/materialize/tests/src/transform/src/nonnull_requirements.rs:127:17
materialize_1  |   13: transform::nonnull_requirements::NonNullRequirements::action
materialize_1  |              at var/lib/buildkite-agent/builds/buildkite-builders-i-0886d71176418a61b-1/materialize/tests/src/transform/src/nonnull_requirements.rs:80:17
materialize_1  |   14: <transform::nonnull_requirements::NonNullRequirements as transform::Transform>::transform
materialize_1  |              at var/lib/buildkite-agent/builds/buildkite-builders-i-0886d71176418a61b-1/materialize/tests/src/transform/src/nonnull_requirements.rs:40:9
materialize_1  |   15: <transform::Fixpoint as transform::Transform>::transform
materialize_1  |              at var/lib/buildkite-agent/builds/buildkite-builders-i-0886d71176418a61b-1/materialize/tests/src/transform/src/lib.rs:124:17
materialize_1  |   16: transform::Optimizer::transform
materialize_1  |              at var/lib/buildkite-agent/builds/buildkite-builders-i-0886d71176418a61b-1/materialize/tests/src/transform/src/lib.rs:176:13
materialize_1  |       transform::Optimizer::optimize
materialize_1  |              at var/lib/buildkite-agent/builds/buildkite-builders-i-0886d71176418a61b-1/materialize/tests/src/transform/src/lib.rs:278:9
materialize_1  |   17: coord::coord::Coordinator<C>::prep_relation_expr
materialize_1  |              at var/lib/buildkite-agent/builds/buildkite-builders-i-0886d71176418a61b-1/materialize/tests/src/coord/src/coord.rs:2863:12
materialize_1  |   18: coord::coord::Coordinator<C>::sequence_create_view::{{closure}}
materialize_1  |              at var/lib/buildkite-agent/builds/buildkite-builders-i-0886d71176418a61b-1/materialize/tests/src/coord/src/coord.rs:1814:30
materialize_1  |       <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
materialize_1  |              at usr/local/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
materialize_1  |       coord::coord::Coordinator<C>::sequence_plan::{{closure}}
materialize_1  |              at var/lib/buildkite-agent/builds/buildkite-builders-i-0886d71176418a61b-1/materialize/tests/src/coord/src/coord.rs:1359:17
materialize_1  |   19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
materialize_1  |              at usr/local/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
materialize_1  |       coord::coord::Coordinator<C>::message_statement_ready::{{closure}}
materialize_1  |              at var/lib/buildkite-agent/builds/buildkite-builders-i-0886d71176418a61b-1/materialize/tests/src/coord/src/coord.rs:495:17
materialize_1  |       <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
materialize_1  |              at usr/local/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
materialize_1  |       coord::coord::Coordinator<C>::serve::{{closure}}
materialize_1  |              at var/lib/buildkite-agent/builds/buildkite-builders-i-0886d71176418a61b-1/materialize/tests/src/coord/src/coord.rs:397:21
materialize_1  |   20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
materialize_1  |              at usr/local/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
materialize_1  |       tokio::park::thread::CachedParkThread::block_on::{{closure}}
materialize_1  |              at cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.0.2/src/park/thread.rs:263:54
materialize_1  |       tokio::coop::with_budget::{{closure}}
materialize_1  |              at cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.0.2/src/coop.rs:121:9
materialize_1  |       std::thread::local::LocalKey<T>::try_with
materialize_1  |              at usr/local/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
materialize_1  |       std::thread::local::LocalKey<T>::with
materialize_1  |              at usr/local/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
materialize_1  |       tokio::coop::with_budget
materialize_1  |              at cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.0.2/src/coop.rs:114:5
materialize_1  |       tokio::coop::budget
materialize_1  |              at cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.0.2/src/coop.rs:98:5
materialize_1  |       tokio::park::thread::CachedParkThread::block_on
materialize_1  |              at cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.0.2/src/park/thread.rs:263:31
materialize_1  |   21: tokio::runtime::enter::Enter::block_on
materialize_1  |              at cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.0.2/src/runtime/enter.rs:151:13
materialize_1  |       tokio::runtime::thread_pool::ThreadPool::block_on
materialize_1  |              at cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.0.2/src/runtime/thread_pool/mod.rs:71:9
materialize_1  |   22: tokio::runtime::Runtime::block_on
materialize_1  |              at cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.0.2/src/runtime/mod.rs:452:43
materialize_1  |   23: coord::coord::serve::{{closure}}::{{closure}}
materialize_1  |              at var/lib/buildkite-agent/builds/buildkite-builders-i-0886d71176418a61b-1/materialize/tests/src/coord/src/coord.rs:3164:31
materialize_1  |       std::sys_common::backtrace::__rust_begin_short_backtrace
materialize_1  |              at usr/local/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137:18
materialize_1  |   24: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
materialize_1  |              at usr/local/lib/rustlib/src/rust/library/std/src/thread/mod.rs:464:17
materialize_1  |       <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
materialize_1  |              at usr/local/lib/rustlib/src/rust/library/std/src/panic.rs:308:9
materialize_1  |       std::panicking::try::do_call
materialize_1  |              at usr/local/lib/rustlib/src/rust/library/std/src/panicking.rs:381:40
materialize_1  |       std::panicking::try
materialize_1  |              at usr/local/lib/rustlib/src/rust/library/std/src/panicking.rs:345:19
materialize_1  |       std::panic::catch_unwind
materialize_1  |              at usr/local/lib/rustlib/src/rust/library/std/src/panic.rs:382:14
materialize_1  |       std::thread::Builder::spawn_unchecked::{{closure}}
materialize_1  |              at usr/local/lib/rustlib/src/rust/library/std/src/thread/mod.rs:463:30
materialize_1  |       core::ops::function::FnOnce::call_once{{vtable.shim}}
materialize_1  |              at usr/local/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
materialize_1  |   25: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
materialize_1  |              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042:9
materialize_1  |       <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
materialize_1  |              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042:9
materialize_1  |       std::sys::unix::thread::Thread::new::thread_start
materialize_1  |              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/unix/thread.rs:87:17
materialize_1  |   26: start_thread
materialize_1  |   27: __clone
materialize_1  |     
materialize_1  | materialized encountered an internal error and crashed.
materialize_1  | 
materialize_1  | We rely on bug reports to diagnose and fix these errors. Please
materialize_1  | copy and paste the above details and file a report at:
materialize_1  | 
materialize_1  |     https://materialize.com/s/bug
materialize_1  | 
materialize_1  | To protect your privacy, we do not collect crash reports automatically.
```

No materialized.log file was generated in my /mzdata folder (mapped from docker).

### PR DESCRIPTION
**Pull request by wangandi**
Resolves #5520.

My understanding of the bug:
Take this example query (which you can also find in the regression test in the PR): 
`SELECT * FROM x x1, x x2, generate_series(x1.a, x2.b) AS x3(b) WHERE x1.b = x2.b AND x1.a = x3.b` 

Here, `x` has two columns. The plan looks like roughly this:
```
%0 =
| Get materialize.public.x (u3)
| ArrangeBy ()

%1 =
| Get materialize.public.x (u3)

%2 =
| Join %0 %1
| | implementation = Differential %1 %0.()
| | demand = (#0..#3)
| FlatMap generate_series(#0, #3)
| | demand = (#0..#4)
| Filter (#0 = #4), (#1 = #3)
```

My understanding of what `NonNullRequirements` does is this:
In SQL when you have a filter "foo.a = bar.a" not only does it imply that a rule that foo.a must be equal to bar.a, but it also implies that a rule that `foo.a is not null and bar.a is not null`. `NonNullRequirements` takes the `foo.a is not null and bar.a is not null` information and pushes it down, hoping to proactively remove parts of the `MirRelationExpr` where `foo.a` or `bar.a` would always evaluate to null and replace them with a no-row Constant. 

So in the example query, `NonNullRequirements` looks at the outermost filter and determines that the set of "columns where we can proactive filter out null values" is {0, 1, 3, 4}. This set in its entirety gets pushed down to `FlatMap` and then `Join`. The problem is that the "4" references a column created by the `FlatMap`. So Materialize crashes when the `Join` tries to figure out which input "4" belongs to.

Note that pushing down column 4 in this case is not a good idea even if the `FlatMap` were around something other than a `Join`. It's just that the `Join` is one of the few places where we verify the columns being pushed down. I think this bug will also cause a crash if the FlatMap were around a Map, but I'll add a test of this after posting the PR. 

The obvious solution in this case is to take the "4" out of the "columns that cannot be null" set that gets pushed down from `FlatMap` to the `Join`, which is what this PR does.

The open question is "does the fact we can proactively filter rows where column '4' is null imply anything about whether or not we proactively filter out null input arguments to the TableFunc?"
* If a TableFunc returns no rows if any input is null (all TableFuncs do this right now), we can proactively filter out all null input arguments anyway. Whether or not column 4 is in the set of "columns where we can proactive filter out null values" does not matter.
* If a TableFunc can return at least one row if any input is null, then I'm not sure what to do. I have decided to just leave TODO and warning comments for whomever adds the first TableFunc like this. Tell me if I should add an additional assert statement/panic due to unsupported-ness. I figure the person who adds the TableFunc is likely to be more qualified as to what to do in this case, and it would be a difficult-to-track-down correctness issue if I pass a wrong instruction to remove rows from an input where a particular column is null.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5565)

### CODE REVIEW

**Review by benesch — APPROVED** [review]
This looks great, @wangandi! Thanks very much for the detailed explanation—that made the review quite a bit quicker. LGTM.

**Comment by benesch** [comment]
re the unit test: seems like it could be a good time to use @justinj's transform testing framework? https://github.com/MaterializeInc/materialize/blob/main/src/transform/tests/testdata/join-implementation

**Comment by wangandi** [comment]
> re the unit test: seems like it could be a good time to use @justinj's transform testing framework? https://github.com/MaterializeInc/materialize/blob/main/src/transform/tests/testdata/join-implementation

That was my first approach, but a couple of hours later, I figured that it is better to fix this earlier with a regression test in the file than to hold up the merge due to adding design discussions and a new round of reviews for changes to the testing framework.

The problem is that if you look at https://github.com/MaterializeInc/materialize/blob/main/src/transform/tests/test_runner.rs there are several components missing:
* `build_rel` does not support `FlatMap` or `Reduce`. In both of these, you specify a function name, and Materialize picks a more relevant function based on what the type of the column is.
* `build_scalar` does not support parsing the `null` literal.
* `build_scalar` does not support parsing anything other than `MirScalarExpr::Column` and `MirScalarExpr::Literal`, whereas I need `MirScalarExpr::CallBinary(BinaryFunc::Eq, ...)` for the test.

There's a TODO in the file that reads: 
> // TODO(justin): is there some way to re-use the sql parser/builder for this?

I consider this the ideal solution, and I looked into this.
* The text -> sql tokens part is easy: `sql-parser::parse_expr`
* The `HirScalarExpr` -> `MirScalarExpr` part is also easy: one calls `HirScalarExpr::lower_uncorrelated`.
* The sql token -> `HirScalarExpr` part is non-trivial: the translation function is `plan_expr`, and I'd need to construct `ExprContext`, `QueryContext`, and `StatementContext`. I figured this part requires a longer discussion with you to discuss how to do it right, and whether or not I need to make `Dummy<thing>Context`s given the fact that `MirScalarExpr` are way simpler than `HirScalarExpr`. (If I have to make `Dummy<thing>Context`s, that's likely to require disruptive changes in the SQL layer. I think `DummyStatementContext` can be avoided if I just pass `StatementContext` something that implements the `Catalog` trait)

If the ideal solution is not feasible, then I figured it would still trigger a new round of reviews/design discussions as to what the new syntax should be.

**Comment by benesch** [comment]
Makes sense! I'll start a discussion in Slack.

**Pull request merged**
