### PR TITLE
Enable specifying a key schema in kgen

### PR DESCRIPTION
**Pull request by cirego**
This is more of a debugging commit to try and figure out why the
distribution of data appears to cause issues with ingest.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5515)

### CODE REVIEW

**Comment by cirego** [comment]
I put together this PR because I wanted to try and see decode the messages that we're writing during the Avro upsert test. However, even after writing the key schema to the Schema Registry, I'm getting the following error when attempting to decode the AVRO messages using kafkacat:

```
[chris-work:~/materialize/materialize/test/benchmark/avro_upsert:(kgen-generate-key-schema[|])] kafkacat -C -b localhost:9093 -t upsertavrotest -s value=avro -r http://localhost:8081 -c 1
{"BookId": 34, "SecurityId": 59451, "Exposure": {"Current": {"Long2": {"Exposure": 12930}, "Short2": {"Exposure": 62945}}, "Target": {"Long": {"Exposure": 5156}, "Short": {"Exposure": 62950}}}}
[chris-work:~/materialize/materialize/test/benchmark/avro_upsert:(kgen-generate-key-schema[|])] kafkacat -C -b localhost:9093 -t upsertavrotest -s avro -r http://localhost:8081 -c 1
% ERROR: Failed to format message in upsertavrotest [0] at offset 0: Avro/Schema-registry key deserialization: REST request failed (code 404): {"error_code":40403,"message":"Schema 0 not found"} : terminating
```

**Comment by cirego** [comment]
What's interesting is that we see a different error when using the previous load generator:

```
[chris-work:~/materialize/materialize:(upsert-benchmark-record-ingest[|]*)] kafkacat -C -b localhost:9093 -t upsertavrotest -s key=avro -r http://localhost:8081 -c 1
% ERROR: Failed to format message in upsertavrotest [0] at offset 0: Avro/Schema-registry key deserialization: Invalid CP1 magic byte 54, expected 0: message not produced with Schema-Registry Avro framing : terminating
``

However, more interestingly, it appears that running the `-s value=avro` version of the command *shows the key*:

```
[chris-work:~/materialize/materialize:(upsert-benchmark-record-ingest[|]*)] kafkacat -C -b localhost:9093 -t upsertavrotest -s value=avro -r http://localhost:8081 -o 5 -c 1
42-31473{"BookId": 42, "SecurityId": 31473, "Exposure": {"Current": {"Long2": {"Exposure": 140388}, "Short2": {"Exposure": 150407}}, "Target": {"Long": {"Exposure": 140561}, "Short": {"Exposure": 160909}}}}
```

Perhaps we're not actually producing a key in `kgen`? Could this be why we're seeing uneven ingestion when using the `kgen` generator?

**Comment by ruchirK** [comment]
looking at the kgen code -- Kgen doesnt actually use the passed in `avro-key-schema` - it instead assigns integer keys either from [0, num_messages) or sampling from a specified distribution. I can patch the code to actually use the key schema to create a avro formatted key rn

**Comment by cirego** [comment]
> ly use the passed in `avro-key-schema` - it instead assigns integer keys either from [0, num_messages) or sampling from a specified distribution. I can patch the code to actually use the key schema to create a avro formatted key rn

I patched the code to have `kgen` insert the key schema into Confluent's Schema registry. Having `kgen` use the `key-schema` and take a `key-distribution` would be fantastic, thank you!

**Comment by umanwizard** [comment]
Does this actually do anything other than put the schema into CSR ? It seems fine so far, but you'd need to do more work to actually get kgen to write keys with that schema.

**Comment by ruchirK** [comment]
I've already done the patch to actually use key schemas and annotations -- im playing around with it rn and will push it up for review later

**Comment by ruchirK** [comment]
```
diff --git a/src/kafka-util/src/bin/kgen.rs b/src/kafka-util/src/bin/kgen.rs
index b2a000ab8..1ca17ad48 100644
--- a/src/kafka-util/src/bin/kgen.rs
+++ b/src/kafka-util/src/bin/kgen.rs
@@ -581,7 +581,7 @@ async fn main() -> anyhow::Result<()> {
             let ccsr =
                 ccsr::ClientConfig::new(Url::parse("http://localhost:8081").unwrap()).build();
             let key_schema_id = ccsr
-                .publish_schema(&format!("{}-value", topic), key_schema)
+                .publish_schema(&format!("{}-key", topic), key_schema)
                 .await?;
             _key_schema_holder = Some(Schema::parse_str(key_schema)?);
             let key_schema = _key_schema_holder.as_ref().unwrap();
@@ -617,20 +617,18 @@ async fn main() -> anyhow::Result<()> {
             eprintln!("Generating message {}", i);
         }
         value_gen.next_value(&mut buf);
-        let key = if let Some(key_dist) = key_dist.as_ref() {
-            key_dist.sample(&mut rng).to_be_bytes().to_vec()
-        } else if let Some(key_gen) = key_gen.as_mut() {
+        let key = if let Some(key_gen) = key_gen.as_mut() {
             // TODO: shitty
             let mut key_buf = vec![];
             key_gen.next_value(&mut key_buf);
             key_buf
+        } else if let Some(key_dist) = key_dist.as_ref() {
+            key_dist.sample(&mut rng).to_be_bytes().to_vec()
         } else {
             (i as u64).to_be_bytes().to_vec()
         };
-        let mut rec = BaseRecord::to(topic)
-            .key(&key)
-            .payload(&buf)
-            .partition((i % partitions) as i32);
+        let mut rec = BaseRecord::to(topic).key(&key).payload(&buf);
+
         loop {
             match producer.send(rec) {
                 Ok(()) => break,
```

this diff patches kgen to accept key schemas and distribution and actually uses those.

This diff doesnt play nicely with the other command line arguments for handling keys / partitions (as you can see I'm just ignoring the partitions arg now) and for some reason I need to wrap the key field in a record like so:

```
altaria-2:kafka-util Test$ cat key-schema.json
{
    "name": "upsertavrotestkey",
    "type" : "record",
    "namespace": "com.acme.avro",
    "fields": [
     {
       "name": "RecordKey",
       "type": "long"
     }
    ]
}
```

in order for kgen to respect annotations on it. Not entirely sure why.

Finally, I can't get `kafkacat` to actually parse the avro key with schema registry, but Materialize is able to parse it just fine with the following command

```
CREATE SOURCE source_upsertavrotest
FROM KAFKA BROKER 'localhost:9092'
TOPIC 'upsertavrotest4'
FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://localhost:8081'
ENVELOPE UPSERT
FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://localhost:8081';
```

**Comment by umanwizard** [comment]
> I need to wrap the key field in a record like so:

It's because there is no way to refer to the type of a bare long/string/etc. that is not in a record. Records are "named types" in Avro, whereas the primitive types are not.

Don't worry, records are tightly packed in Avro binary encoding; i.e., the encoding of a record with exactly one field of type `long` is identical to the encoding of a bare `long`.

**Comment by ruchirK** [comment]
looking more closely at the users schemas it seems like the key is meant to be a string representation of 2 fields in the value  -- note that my change does not support that because it renders the keys and the values totally independently --- i think for a load test we could probably hack around this somehow by having the keys be two ints that get placed into the correct column by MZ

**Comment by umanwizard** [comment]
We could give a CLI flag that makes the key be a subset of the fields from the value

**Comment by ruchirK** [comment]
> We could give a CLI flag that makes the key be a subset of the fields from the value

yeah for sure I just wanted to call out that my diff doesnt do anything like that / has no correspondence btw generated keys and vals

**Comment by cirego** [comment]
> > We could give a CLI flag that makes the key be a subset of the fields from the value
> 
> yeah for sure I just wanted to call out that my diff doesnt do anything like that / has no correspondence btw generated keys and vals

Thanks for iterating on this! I think having the keys be linked to the values, on the generator side, is important for accurately reproducing this workload.

**Comment by cirego** [comment]
@ruchirK, did you want to go ahead and take over this PR?

**Comment by ruchirK** [comment]
>  I think having the keys be linked to the values, on the generator side, is important for accurately reproducing this workload.

Ok gave this a bit more thought and I don't think this is true. We can move the key fields to the key schema and in the value schema we can just have dummy versions of the same fields that pull from the same underlying distributions, and then when we create the view we can just throw the dummy fields. As it stands anyone with duplicate columns in the key and value will have to throw one of them away anyway. This way, we still simulate the computational work of decoding those fields without having to complicate `kgen` and generate the same data across 2 records.

I'll send you the proposed key / val schemas over slack

**Comment by cirego** [comment]
Going to close this out in favor of #5548.

**Pull request closed without merging**
