### PR TITLE
version consistency: add ignore for changed order of array_agg and string_agg

### PR DESCRIPTION
**Pull request by nrainer-materialize**
This addresses https://buildkite.com/materialize/nightly/builds/9456#0191c9b1-a3fa-44b9-a589-baeecb4e4723 and other builds caused by https://github.com/MaterializeInc/materialize/pull/29422.

### CODE REVIEW

**Comment by ggevay** [comment]
Thanks for jumping on this!

There are also `list_agg`, jsonb_agg`, `jsonb_object_agg`, `map_agg`, which have the same problem.

Also, would it be possible to put an `ORDER BY` into each of the ordered aggregate function calls? Without that, the same issue might happen again, if Datum ordering changes for any reason, because the default ordering is not specified by the SQL standard. Some calls already have `ORDER BY`, for example, there is 
```
jsonb_object_agg(timestamptz_list_val, justify_days(time_val) ORDER BY row_index, timestamptz_list_val)
```
in the linked build. The important thing is that if two rows agree on the `ORDER BY` columns, then they should also agree on all the other arguments of function call (`timestamptz_list_val` and `justify_days(time_val)` above). For example, if the `ORDER BY` simply has the same expressions as all the other arguments, that's good. Alternatively, if `row_index` is always unique, then that one by itself should be good too.

**Comment by ggevay** [comment]
Also note that with `ORDER BY`s, we could also be comparing to Postgres.

**Comment by nrainer-materialize** [comment]
> Also, would it be possible to put an `ORDER BY` into each of the ordered aggregate function calls?

I am actually doing that for all `_agg` functions (except for `list_agg` but I will change that). 😀
I am testing two overloadings of `string_agg` and `array_agg` (with and without ordering); @ggevay, is there any point in doing so or should I remove the one without ordering?

> There are also `list_agg`, `jsonb_agg`, `jsonb_object_agg`, `map_agg`, which have the same problem.

These (except for `list_agg`) are only run with ordering.

> Alternatively, if `row_index` is always unique, then that one by itself should be good too.

`row_index` is always unique.

**Comment by ggevay** [comment]
> I am testing two overloadings of string_agg and array_agg (with and without ordering); @ggevay, is there any point in doing so or should I remove the one without ordering?

Great! The one without ordering should be removed, because the sort order is not guaranteed in that case, so it might randomly change between versions due to various reasons.

> row_index is always unique.

Ok, then having that in the `ORDER BY` is enough. (But having additional other things in the `ORDER BY` doesn't hurt either.)

**Comment by ggevay** [comment]
> row_index is always unique.

But see https://github.com/MaterializeInc/materialize/issues/29143#issuecomment-2337556298
The problem there is that a table function call can make `row_index` not unique. I'm not sure if that can occur also here, or that's a separate test.

**Comment by nrainer-materialize** [comment]
> Great! The one without ordering should be removed

Ok! => https://github.com/MaterializeInc/materialize/pull/29446

> except for list_agg but I will change that
Separate PR to test that change. => https://github.com/MaterializeInc/materialize/pull/29447

>  The problem there is that a table function call can make row_index not unique. I'm not sure if that can occur also here, or that's a separate test.

Oh, that's unfortunately true. It might also get more frequent with the recent introduction of joins.
Though, it will be a little bit difficult to incorporate that in here. I will keep this in mind and suggest to await how much of a problem this will be.

**Comment by nrainer-materialize** [comment]
Replaced by https://github.com/MaterializeInc/materialize/pull/29446.

**Comment by ggevay** [comment]
>> The problem there is that a table function call can make row_index not unique. I'm not sure if that can occur also here, or that's a separate test.

> Oh, that's unfortunately true. It might also get more frequent with the recent introduction of joins.
Though, it will be a little bit difficult to incorporate that in here. I will keep this in mind and suggest to await how much of a problem this will be.

Then I'd suggest to just keep adding also the other arguments of the aggregation function call. E.g., the following should be fine, even with a non-unique `row_index`:
```
array_agg($ ORDER BY row_index, $)
```

**Pull request closed without merging**
