### PR TITLE
Fix Array Containment Operator Mapping and pgcompat Issue

### LINKED ISSUE #28035: panic: Datum::unwrap_list called on Array when using contains operator
### What version of Materialize are you using?

b13130b882899fed9f671a6fed12f3a758a69cf9

### What is the issue?

The following code panics:
```
CREATE TABLE t (row_index int, multi_dim_text_array_empty TEXT[][], multi_dim_text_array_two_elem TEXT[][]);
INSERT INTO t SELECT 0, '{}'::TEXT[][], '{{a, b}, {a, A}}'::TEXT[][];

SELECT ((multi_dim_text_array_null) @> (multi_dim_text_array_two_elem))
FROM t;
```

(Note that `SELECT (('{}'::TEXT[][]) @> ('{{a, b}, {a, A}}'::TEXT[][]));` succeeds.)

```
thread 'timely:work-0' panicked at src/expr/src/scalar/func.rs:1630:15:
Datum::unwrap_list called on Array(Array { elements: [], dims: [] })
```

```
   0: rust_begin_unwind
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: <mz_repr::scalar::Datum>::unwrap_list
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0c0ab7040c21be300-1/materialize/test/src/repr/src/scalar.rs:861:18
   3: mz_expr::scalar::func::list_contains_list
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0c0ab7040c21be300-1/materialize/test/src/expr/src/scalar/func.rs:1630:13
   4: <mz_expr::scalar::func::BinaryFunc>::eval
   5: <mz_expr::linear::plan::SafeMfpPlan>::evaluate_inner
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0c0ab7040c21be300-1/materialize/test/src/expr/src/linear.rs:1606:29
   6: <mz_expr::linear::plan::MfpPlan>::evaluate::<mz_storage_types::errors::DataflowError, <mz_storage_operators::persist_source::PendingWork>::do_work<timely::dataflow::channels::pushers::tee::Tee<(mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime), alloc::vec::Vec<(core::result::Result<mz_repr::row::Row, mz_storage_types::errors::DataflowError>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime), i64)>>, mz_storage_operators::persist_source::decode_and_mfp<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::{closure#1}::{closure#0}::{closure#1}>::{closure#2}>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0c0ab7040c21be300-1/materialize/test/src/expr/src/linear.rs:1849:19
   7: <mz_storage_operators::persist_source::PendingWork>::do_work::<timely::dataflow::channels::pushers::tee::Tee<(mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime), alloc::vec::Vec<(core::result::Result<mz_repr::row::Row, mz_storage_types::errors::DataflowError>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime), i64)>>, mz_storage_operators::persist_source::decode_and_mfp<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::{closure#1}::{closure#0}::{closure#1}>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0c0ab7040c21be300-1/materialize/test/src/storage-operators/src/persist_source.rs:603:39
   8: mz_storage_operators::persist_source::decode_and_mfp::<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::{closure#1}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0c0ab7040c21be300-1/materialize/test/src/storage-operators/src/persist_source.rs:472:28
   9: <timely::dataflow::operators::generic::builder_rc::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>>::build::<mz_storage_operators::persist_source::decode_and_mfp<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::{closure#1}, mz_storage_operators::persist_source::decode_and_mfp<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::{closure#1}::{closure#0}>::{closure#0}::{closure#0}
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/0c26e5e/timely/src/dataflow/operators/generic/builder_rc.rs:140:31
  10: <timely::dataflow::operators::generic::builder_rc::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>>::build_reschedule::<<timely::dataflow::operators::generic::builder_rc::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>>::build<mz_storage_operators::persist_source::decode_and_mfp<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::{closure#1}, mz_storage_operators::persist_source::decode_and_mfp<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::{closure#1}::{closure#0}>::{closure#0}, <timely::dataflow::operators::generic::builder_rc::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>>::build<mz_storage_operators::persist_source::decode_and_mfp<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::{closure#1}, mz_storage_operators::persist_source::decode_and_mfp<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::{closure#1}::{closure#0}>::{closure#0}::{closure#0}>::{closure#0}
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/0c26e5e/timely/src/dataflow/operators/generic/builder_rc.rs:179:26
  11: <timely::dataflow::operators::generic::builder_raw::OperatorCore<(mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime), <timely::dataflow::operators::generic::builder_rc::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>>::build_reschedule<<timely::dataflow::operators::generic::builder_rc::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>>::build<mz_storage_operators::persist_source::decode_and_mfp<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::{closure#1}, mz_storage_operators::persist_source::decode_and_mfp<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::{closure#1}::{closure#0}>::{closure#0}, <timely::dataflow::operators::generic::builder_rc::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>>::build<mz_storage_operators::persist_source::decode_and_mfp<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::{closure#1}, mz_storage_operators::persist_source::decode_and_mfp<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::{closure#1}::{closure#0}>::{closure#0}::{closure#0}>::{closure#0}> as timely::scheduling::Schedule>::schedule
```

This was introduced with b13130b882899fed9f671a6fed12f3a758a69cf9. This operation was not possible before.

```
CREATE TABLE
INSERT 0 1
ERROR:  operator does not exist: text[] @> text[]
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
```

### PR DESCRIPTION
**Pull request by sthm**
closes #28035

### CODE REVIEW

**Review by nrainer-materialize — APPROVED** [review]
Thanks for the fix and additional test cases!

**Comment by nrainer-materialize** [comment]
Rebased on main and added 00a67231d6b7eb4dd8721ed71dc2ac9d9d812308, which reverts 533aba1d3734e5c9893428cc85130abf50e3912a.

**Comment by nrainer-materialize** [comment]
Nightly build for the re-enabled contains operator in the output-consistency framework: https://buildkite.com/materialize/nightly/builds/8366

**Comment by sthm** [comment]
This is a minimal repro which returns true with the current implementation but false in Postgres.
```
SELECT '{NULL}'::numeric[] @> '{NULL}'::numeric[];
```
I suspect this happens because the implementation is checking `NULL == NULL` in Rust, which returns true.

**Comment by sthm** [comment]
Nightly is still hitting this panic:
```
2024-07-08 09:54:12 thread 'timely:work-1' panicked at src/expr/src/scalar/func.rs:1630:15:
2024-07-08 09:54:12 Datum::unwrap_list called on Array(Array { elements: [String("a"), String("b"), String("a"), String("b")], dims: [ArrayDimension { lower_bound: 1, length: 2 }, ArrayDimension { lower_bound: 1, length: 2 }] })
```

**Comment by sthm** [comment]
For some reason, the panic does not reproduce in a local build.
```
localhost > SELECT ((multi_dim_text_array_one_elem || multi_dim_text_array_one_elem) @> multi_dim_text_array_empty), (text_val_3 !~* '.*'), ((timestamp_max_val - time_max_val))::TEXT FROM t_dfr_2_v0_108_0_dev_horiz;
 ?column? | ?column? |            text
----------+----------+-----------------------------
 t        | f        | 99999-12-30 23:59:59.000001
(1 row)
```
with
```
localhost > SELECT multi_dim_text_array_one_elem, multi_dim_text_array_empty, text_val_3, timestamp_max_val, time_max_val FROM t_dfr_2_v0_108_0_dev_horiz;
 multi_dim_text_array_one_elem | multi_dim_text_array_empty | text_val_3 |  timestamp_max_val   |  time_max_val
-------------------------------+----------------------------+------------+----------------------+-----------------
 {{a,b}}                       | {}                         | xAAx       | 99999-12-31 23:59:59 | 23:59:59.999999
(1 row)
```
```

**Comment by nrainer-materialize** [comment]
> For some reason, the panic does not reproduce in a local build.
> 
> ```
> localhost > SELECT ((multi_dim_text_array_one_elem || multi_dim_text_array_one_elem) @> multi_dim_text_array_empty), (text_val_3 !~* '.*'), ((timestamp_max_val - time_max_val))::TEXT FROM t_dfr_2_v0_108_0_dev_horiz;
>  ?column? | ?column? |            text
> ----------+----------+-----------------------------
>  t        | f        | 99999-12-30 23:59:59.000001
> (1 row)
> ```
> 
> with
> 
> ```
> localhost > SELECT multi_dim_text_array_one_elem, multi_dim_text_array_empty, text_val_3, timestamp_max_val, time_max_val FROM t_dfr_2_v0_108_0_dev_horiz;
>  multi_dim_text_array_one_elem | multi_dim_text_array_empty | text_val_3 |  timestamp_max_val   |  time_max_val
> -------------------------------+----------------------------+------------+----------------------+-----------------
>  {{a,b}}                       | {}                         | xAAx       | 99999-12-31 23:59:59 | 23:59:59.999999
> (1 row)
> ```

The failure in the nightly build occurs in the version-consistency build step. This build step compares the current version against its ancestor. In this case, the current version will be compared against the merge base, which is the commit from which this branch branched off. Since that earlier version contained the fault causing a panic, **it is expected for this build to fail** (it exercises the earlier version as well).
On main, the comparison will be conducted against the previous release. Therefore, there should be no build failure if the fix manages to get into the same release as the fault. (Otherwise, we have means to address this if we want to.)
As discussed with @sthm, the feature was introduced in v0.107.0. **I suggest to backport the fix to v0.107.x.** Failures of version-consistency on builds of v0.107.1+ are to be expected. I expect no failures on builds of main in this case.

=> TLDR: Failure of version-consistency is expected. Good from QA side.

**Review by ParkMyCar — APPROVED** [review]

**Pull request merged**
