### PR TITLE
sql: Remove catalog migrations and upgrade tests

### PR DESCRIPTION
**Pull request by jkosh44**
Due to the work towards platform, Materialize versions greater than
v0.26.X will no longer maintain backwards compatibility with versions
less than or equal to v0.26.X. Therefore this commit removes all
catalog migrations that would create backwards compatibility.

Removing the migrations helps reduce complexity and speed up ADAPTER
startup.

The infrastructure for migrations is left in place, because it will be
needed to support migrations for all versions greater than v0.26.X.

Additionally all upgrade tests have been updated to only test versions
greater than V0.26.X because we no longer want to test backwards
compatibility with earlier versions.

### Motivation
This PR refactors existing code.

### Notes for Reviewer
* `orms.slt` was moved to `orms.td` because it was hardcoding system IDs in the results. 

### Testing

- [X] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - This commit breaks all backwards compatibility with versions v0.26.X and earlier.

### CODE REVIEW

**Comment by jkosh44** [comment]
I'll take a look at the upgrade failure tomorrow, but let me know if anyone has thoughts. I'm not exactly sure what the error is about.

**Comment by benesch** [comment]
Yeah, it's hard to see, but that means `materialized` crashed. Details are in the `services.log` file that gets uploaded under the "Artifacts" tab. Here's the relevant error:

```
materialized_1     | booting server
materialized_1     | materialized v0.26.1-dev (97fd50139)
materialized_1     | OpenSSL 1.1.1n  15 Mar 2022
materialized_1     | librdkafka v1.8.2
materialized_1     | invoked as: MZ_DEV=1 materialized '--log-file=stderr' '--listen-addr=0.0.0.0:6875' '--data-directory=/share/mzdata' --listen-addr 0.0.0.0:6875 --disable-telemetry --experimental --timestamp-frequency 100ms --introspection-frequency 100ms --retain-prometheus-metrics 1s --persistent-user-tables
materialized_1     | os: Ubuntu 20.4.0 [64-bit]
materialized_1     | cpus: 8 logical, 4 physical, 4 useful
materialized_1     | cpu0: Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz 3564MHz
materialized_1     | memory: 16331345KB total, 1918371KB used, 9007199254740988KiB limit
materialized_1     | swap: 0KB total, 0KB used, 0KiB limit
materialized_1     | dataflow workers: 2
materialized_1     | max log level: info
materialized_1     | materialized: sqlite error: no such table: system_gid_mapping
```

**Comment by benesch** [comment]
@philip-stoev can you confirm you are okay with temporarily making the upgrade test only test the upgrade from current source to current source?

**Comment by philip-stoev** [comment]
If we are no longer supporting those upgrades, then we have no other choice I guess ...

**Review by philip-stoev — APPROVED** [review]
The upgrade tests as currently written are unlikely to be able to support the full matrix of rolling upgrades we would like to support in Platform. So a new framework will be put in place, hopefully reusing the SQL testdrive content that has accumulated so far.

**Comment by jkosh44** [comment]
Ah thanks for the help. The issue was that even no-op upgrade tests won't work for versions <= 0.26.X because a database that was started in an earlier version won't have the correct SQLite tables, and the current version removes all migrations scripts to create the SQLite tables.

I just switched the pipeline template to use `--most-recent 0` as an arg to the upgrade tests.

I'll wait for an explicit approval from @benesch before merging to triple check that you're OK with clobbering all these catalog migrations.

**Pull request merged**
