### PR TITLE
Refer to the process of rewriting a HirRelationExpr into a MirRelationExpr as "lowering", not "decorrelation", since it can in fact involve transformations other than decorrelation.

### PR DESCRIPTION
**Pull request by umanwizard**
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5510)

### CODE REVIEW

**Review by frankmcsherry — APPROVED** [review]
This looks good to me.

**Review by benesch — APPROVED** [review]
Eh, I guess. I think we’ll still colloquially refer to this as “decorrelating” so having the code call it something else is not ideal, but I guess we can try it.

**Comment by frankmcsherry** [comment]
Maybe another option is to extract out the non-decorrelation lowering, for example outer join planning, keyless reduce planning, stuff like that. I think these are the main weird cases that aren't well described by decorrelation. The outer join planning in particular is the sort of thing an arbitrary amount of code could be sunk onto.

**Comment by benesch** [comment]
I think it’s hard to avoid doing it all in one shot though because of the types involved. I’m really ok with this! I think it’ll just take a smidge of getting used to and I’m willing to try it for a while!

**Comment by umanwizard** [comment]
>  I think we’ll still colloquially refer to this as “decorrelating”

@benesch why, though? Isn't that just... wrong?

**Comment by benesch** [comment]
> > I think we’ll still colloquially refer to this as “decorrelating”
> 
> @benesch why, though? Isn't that just... wrong?

Sure, if you were trying to write up an IEEE standard or something, but, idk, English isn't precise, and this thing is like 95% decorrelation and a little bit the other stuff.

**Pull request merged**
