### PR TITLE
[persist] Make Persist's feature-flag machinery handle more than booleans

### PR DESCRIPTION
**Pull request by bkirwi**
### Motivation

This PR refactors existing code. This is inspired by [@danhhz's branch](https://github.com/MaterializeInc/materialize/compare/main...danhhz:materialize:flag), but without the `inventory` crate, using our existing flags as a base, and finishing the wiring-up to system vars. (We could use `inventory` in the future if we want - this approach should be compatible with that; just starting with the more minimal version for now.)

Personally I am motivated because I find it very annoying to do this wiring manually. I've only converted a single flag so far, to show how it looks, but it looks like this should pay for itself in LOC terms with a couple more flags.

### Tips for reviewer

Naming is mostly stolen from the other branch; generally happy to take suggestions.

Changes mostly follow commit-by-commit, but there's a little sloppiness early on that gets cleaned up later. I plan to squash before merging.

This is a noop. I think Testing has been pinged as a code owner because of the vars change, but in practice no "actual" vars are changing here.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by danhhz** [comment]
Uh oh, I've still been pushing my branch forward in bits and pieces. We should consolidate our efforts!

**Comment by bkirwi** [comment]
Cool! If you want to point me at a branch I can probably do some integrating - keen to get something rolling so I don't have to add a bunch of new flags the hard way. 😅

**Comment by danhhz** [comment]
I was actually already planning to work on this for skunkworks this week! Mine's pretty close, so I'll see how far I can get tomorrow

**Comment by nrainer-materialize** [comment]
[Nightly](https://buildkite.com/materialize/nightlies/builds/5938) looks good, failure in RQG is expected.

**Comment by nrainer-materialize** [comment]
The [coverage build](https://buildkite.com/materialize/coverage/builds/341) also looks good. 👍

**Comment by bkirwi** [comment]
Closing in favour of: https://github.com/MaterializeInc/materialize/pull/24416

**Pull request closed without merging**
