### PR TITLE
Use AHash to speed up the hashmap in the Upsert operator

### PR DESCRIPTION
**Pull request by quodlibetor**
AHash is a less-dos-resistant but much faster hash algorithm. Upsert perf is
currently an issue, so this seems worth benchmarking.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5589)

### CODE REVIEW

**Comment by quodlibetor** [comment]
@cirego how hard is it to benchmark something like this?

**Comment by cirego** [comment]
@quodlibetor it takes me about 10 minutes to run an experiment like this.

**Comment by ruchirK** [comment]
i dunno what the perf difference is between this and regular hashmap but maybe this is also worth using in @wangandi 's upsert impl

**Comment by cirego** [comment]
Performance appears to be about the same -- 12 minutes to ingest 400M rows.

**Comment by quodlibetor** [comment]
Oh well. It's probably not worth deviating from std if there isn't an obvious way to verify that this is in fact an improvement, but it might be worth reconsidering in the future.

**Pull request closed without merging**
