### PR TITLE
Update released versions to include v0.16.0

### PR DESCRIPTION
**Pull request by ruchirK**
### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

**Comment by ruchirK** [comment]
I believe this is the only change I need to make after pushing the v0.16.0 tag, as we've already merged a commit updating the next phase of development to `0.16.1-dev`

**Comment by benesch** [comment]
LGTM. I'll take care of #9993 because we need to move one of the relnotes for the backported fix around.

**Comment by ruchirK** [comment]
thanks Nikhil! merging this one on green

**Comment by benesch** [comment]
I think this needs another rebase?

**Comment by ruchirK** [comment]
this one should do the trick. mindlessly forgot to fetch from upstream before rebasing :)

**Review by benesch — APPROVED** [review]
🎉

**Pull request merged**
