### PR TITLE
Improve feature benchmark experience in Buildkite

### PR DESCRIPTION
**Pull request by quodlibetor**
This makes the output less than thousands of lines in the buildkite UI.

Each scenario gets its own collapsed section, which both makes it easier to
scan the scenarios and to view the per-scenario report, since it will be at the
end of a section, with only collapsed sections afterwards.

Additionally, if the benchark completes without being OOM- or timeout-killed it
generates a default expanded section with just the report. If there are any
regressions it becomes easy to view the scenario-specific details by expanding
their specific sections.

### Motivation

* This PR adds a feature that has not yet been specified.

### Checklist

- [n/a] This PR has adequate test coverage / QA involvement has been duly considered.
- [n/a] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

**Review by ruchirK — APPROVED** [review]
this seems good to me!

**Review by philip-stoev — CHANGES_REQUESTED** [review]
No, I am afraid the current placement was by design:
- if the benchmark fails for any reason whatsoever, including OOMs, being force-killed by the CI, etc, you will still get at least a partial report
- you can observe how things are going as the benchmark runs and may decide to cancel it manually.


I would very much like to keep the current setup, at least until we have some storage of benchmark results in place. At the very least, the print of the benchmark report should be under a try+finally block so that it always gets run, even on Ctrl+Cs.

**Comment by quodlibetor** [comment]
@philip-stoev that makes sense! I've changed this PR to report at the end of each scenario and again at the end of the full run. Does that work for you?

**Review by philip-stoev — APPROVED** [review]
Thanks a lot!

**Pull request merged**
