### PR TITLE
persist: safely return snapshot leases on drop

### PR DESCRIPTION
**Pull request by sploiselle**
If a Subscribe were abruptly dropped while holding leases from a
snapshot, it would panic. Instead, safely return the leases to
prevent the panic.

### Motivation

This PR fixes a previously unreported bug. There is a chance this caused CI flakiness seen [here](https://buildkite.com/materialize/tests/builds/40785#0182fdb5-511e-48ac-81ae-46bb28c89c38/155-536).

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-protobuf` label.
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - there are no user-facing behavior changes

### CODE REVIEW

**Review by frankmcsherry — APPROVED** [review]
This looks very credible to me, but I don't know enough about `Subscribe` to want to be the one to OK it! But I've certainly read the PR and it all makes sense.

**Review by danhhz — APPROVED** [review]
LGTM thanks for the fix 🙌 !

it'd be nice to have a regression test, seems like it should be pretty straightforward? write some data, call subscribe, and then drop it

**Comment by sploiselle** [comment]
@danhhz added a test

**Comment by danhhz** [comment]
test LGTM tyty!

**Pull request merged**
