### PR TITLE
sql: support rounding functions for apd

### PR DESCRIPTION
**Pull request by sploiselle**

### CODE REVIEW

**Review by benesch — APPROVED** [review]
Again didn't review in depth for correctness but structure lgtm.

**Comment by philip-stoev** [comment]
This is ```NaN``` in this branch and ```0``` in postgres. It is an extreme example though, so I am not sure if it is worth sweating over -- I am putting it in here just for completeness:

```
materialize=>  SELECT ROUND ( '-0.10212864 '::APD , -900 ) ;
 round 
-------
 NaN
(1 row)
```

**Comment by philip-stoev** [comment]
```CEIL``` on negative numbers is a ```-0``` in  this branch, ```0``` in Postgres:

```
materialize=> SELECT CEIL ( '-0.6'::APD  );
 ceil 
------
 -0
(1 row)
```

**Review by philip-stoev — APPROVED** [review]
Thank you, the randomized test is otherwise happy, so the edge cases ```round_apt_binary``` is about appear to be handled correctly.

**Comment by sploiselle** [comment]
@philip-stoev great catches on both of those issues

Fixed `SELECT ROUND ( '-0.10212864 '::APD , -900 ) ;` by clamping `b`'s value to one more than the max precision. The problem was that large values generated an invalid operation.

Fixed `SELECT CEIL ( '-0.6'::APD  );` by checking for `-0` outputs and fixing them (this is one of `munge_apd`'s few purposes).

**Pull request merged**
