### PR TITLE
doc: CDCv2 requires that there be at most one diff for each (data, time) pair

### PR DESCRIPTION
**Pull request by msudberg**

### CODE REVIEW

**Review by frankmcsherry — APPROVED** [review]
This seems good, but if it is possible, it would be great to keep clear that duplication is permitted. So, in the sense of *duplication* it is ok if a `(data, time)` occurs multiple times, but there needs to be only one `diff` value associated with all of them.

Perhaps text like "For each `(data, time)` pair there should be exactly one `diff` value associated with the pair. The pair can occur multiple times, owing to duplication, but on ingestion those repetitions will be *deduplicated* rather than accumulated."

Does that concern make sense? Maybe it doesn't in this context.

**Comment by msudberg** [comment]
Does this work as a replacement for the second paragraph?

> There should be at most one diff for each `(data, time)` pair.  Identical `(data, time)` pairs with different `diff`s will produce an error. In effect, the data must be pre-consolidated before it is transmitted to Materialize.
If there are multiple identical `(data, time, diff)` triples, this will be treated as a duplication, and only one update will be recorded.

**Comment by frankmcsherry** [comment]
> Identical (data, time) pairs with different diffs will produce an error. 

This is not the case. They may produce an error, but they may also produce a "this time has passed, and we didn't retain enough information to determine if this was a duplicate or an inconsistency" .. event. That event is not an error, because it could just be duplication, and that is fine (and we can't tell the difference any more at this point).

**Comment by msudberg** [comment]
> > Identical (data, time) pairs with different diffs will produce an error.
> 
> This is not the case. They may produce an error, but they may also produce a "this time has passed, and we didn't retain enough information to determine if this was a duplicate or an inconsistency" .. event. That event is not an error, because it could just be duplication, and that is fine (and we can't tell the difference any more at this point).

I want to make sure we're giving explicit enough information to prevent the error the issues we saw before, so maybe this?

> There should be at most one diff value for each `(data, time)` pair. That is, if a stream has updates `(data1, time1, -1)` and `(data1, time1, 1)`, these should be combined and expressed as `(data1, time1, 0)` (and then suppressed).  In effect, the data must be pre-consolidated before it is transmitted to Materialize. There can be multiple identical `(data, time, diff)` triples, but they will be treated as duplications, and only one update will be recorded.

**Comment by frankmcsherry** [comment]
Could work! If it were me, I would maybe wordsmith "That is, if a stream has updates ..." to be more "That is, if a stream would have updates ..." to avoid the idea that the stream should ever have those updates.

**Pull request merged**
