### PR TITLE
[persist] Fix nullability in DatumColumnEncoder

### PR DESCRIPTION
**Pull request by bkirwi**
Currently, we set the `nullability` of the field in a struct array based on whether / not the array contains any nulls. This means that two arrays generated by the same encoder may not have the same type, which limits our ability to eg. concatenate / consolidate them together later. (And concretely, this causes problems for the new consolidation code, which calls `interleave`, which expects all arrays to have the same type.)

Two ideas for fixes in separate commits:
- Third commit: we could just say every column is nullable. AFAICT this is fine and causes no problems. 
- Last commit: we could thread the nullability info from the RelationDesc through to the individual field.

Either seems basically fine to me, but I suspect the last commit is slightly more in line with the rest of our approach.

### Motivation

Addresses Zippy failures in such tests as: https://buildkite.com/materialize/nightly/builds/9038

### Tips for reviewer

Separately, we've presumably already encoded data with the bad nullability information in Staging. Will discuss what to do there with the team and follow up separately.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

**Comment by bkirwi** [comment]
Confirmed this fixes the nighly zippy failures when`both_v2` is enabled: https://buildkite.com/materialize/nightly/builds/9052

**Review by danhhz — APPROVED** [review]
> Third commit: we could just say every column is nullable. AFAICT this is fine and causes no problems.
> Last commit: we could thread the nullability info from the RelationDesc through to the individual field.

I like the latter and am vaguely uncomfortable with the former, even if it seems fine in practice [^1]. Looks like you're structured the PR such that the last commit overwrites the third one? Assuming that's correct LGTM

[^1]: Though the more we work with arrow/parquet, the more I realize I maybe need to just give up on them having the semantics I want, shrug

**Comment by bkirwi** [comment]
> Assuming that's correct LGTM

Yep that's right! I've rebased out the third commit so the history's not confusing.

**Comment by ParkMyCar** [comment]
+1 to threading through the nullability of the `RelationDesc`!

**Pull request merged**
