### PR TITLE
persist: truncate String and Vec<u8> stats to a maximum byte length

### PR DESCRIPTION
**Pull request by danhhz**
These stats are inclusive lower and upper bounds, so we can (carefully) truncate almost any String or Vec<u8> value to produce one that's smaller but still a relatively tight bound.

There is TONS of stats pruning left to do (including given the ProtoDatum and Json stats the same treatment), but this is enough to get CI (which sometimes inserts 100MiB strings) to pass with the stats collection ff on, so it seems like a nice start.

Touches #12684

### Motivation

  * This PR adds a known-desirable feature.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by bkirwi — APPROVED** [review]
LGTM!

(I think it would probably be okay to just not write stats for columns like this. But this is of course even better!)

**Comment by danhhz** [comment]
yeah, I think we want a general mechanism for pruning stats for a column, but it's not clear to me yet exactly what the heuristics for that should be (I'm tempted to say that's probably something to be vetted during the design doc process, which it seems about time to circle back to), whereas this felt like a straightforward win. TFTR!

**Review by pH14 — COMMENTED** [review]
The logic to get an upper bound from a UTF8 string actually reads much simpler than I expected, very nice!

Wouldn't mind a proptest that generates strings/Vec<u8> and verifies the lower and upper bounds work as intended over a myriad of inputs

**Comment by danhhz** [comment]
> The logic to get an upper bound from a UTF8 string actually reads much simpler than I expected, very nice!

lol that took me 7 hours to write

**Comment by danhhz** [comment]
> Wouldn't mind a proptest that generates strings/Vec and verifies the lower and upper bounds work as intended over a myriad of inputs
done! https://github.com/MaterializeInc/materialize/pull/18805

**Pull request merged**
