### PR TITLE
Fix self-hosted pgwire cancellation

### PR DESCRIPTION
**Pull request by alex-hunt-materialize**
Fix self-hosted pgwire cancellation.

We previously did not sent cancellation requests if we didn't have a directory containing mappings from suffixes to DNS addresses.

We now require that the cancellation directory is provided or that we are using a static resolver, and we also use that same static resolver for cancellation requests.

### Motivation

  * This PR fixes a previously unreported bug.
Cancellation was broken in self-hosted.
https://materializeinc.slack.com/archives/C07PN7KSB0T/p1733935678308619

### Tips for reviewer

This is much easier to review with whitespace changes suppressed (`?w=1`).

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

**Review by doy-materialize — APPROVED** [review]

**Comment by def-** [comment]
I have added a regression test for this. I'll try rerunning it now. On my previous attempt (old code state) it failed:
```
error: The following required arguments were not provided:
    --cancellation-resolver-dir </path/to/configmap/dir/>

USAGE:
    balancerd service --pgwire-listen-addr <HOST:PORT> --https-listen-addr <HOST:PORT> --internal-http-listen-addr <HOST:PORT> --https-resolver-template <HOST.{}.NAME:PORT> --static-resolver-addr <HOST:PORT> --tls-mode <MODE> --cancellation-resolver-dir </path/to/configmap/dir/>
```
Just in case: Do I still need to pass in some parameter?

**Comment by alex-hunt-materialize** [comment]
> Just in case: Do I still need to pass in some parameter?

There are two modes here. Either static resolver for both by passing `--static-resolver-addr`, or frontegg resolver and cancellation resolver dir by passing `--frontegg-resolver-template` and `--cancellation-resolver-dir`.

We now require you to pass exactly one set of those options. You cannot pass `--static-resolver-addr` with either of the other two args, and both of the others are required if either are passed.

**Comment by def-** [comment]
How do I pass those in through the helm chart?

**Comment by alex-hunt-materialize** [comment]
> How do I pass those in through the helm chart?

The helm chart should use `--static-resolver-addr` by default.

**Pull request merged**
