### PR TITLE
Use passed in AWS external ID as a prefix

### PR DESCRIPTION
**Pull request by alex-hunt-materialize**
Instead of using the external ID as passed in, use it as a prefix with
the source or sink ID appended.

This should play nicer with RBAC, in case customers want to allow only
certain sources or sinks to assume their AWS role.

Part 1 of https://github.com/MaterializeInc/cloud/issues/2837

### Motivation

  * This PR adds a known-desirable feature.

Part 1 of https://github.com/MaterializeInc/cloud/issues/2837

### Testing

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Review by benesch — APPROVED** [review]
This looks great!

**Review by benesch — APPROVED** [review]
The last commit LGTM too!

**Comment by alex-hunt-materialize** [comment]
@benesch What is a good way to test this?

**Comment by alex-hunt-materialize** [comment]
I think I'll handle tests for this in the cloud repo, by updating the S3 bucket test there.

**Pull request merged**
