### PR TITLE
Add SIZE Parameter to CREATE SINK

### LINKED ISSUE #15214: Support `CREATE SOURCE ... WITH (SIZE = 'size')`
### Feature request

Part of #13889, issue to specifically track the core feature in SQL. When this issue is closed, it will be possible to define the size used in each sink (but not alter it).

Work items:
* Add parser and planner support for `WITH (SIZE)` parameter
* Plumb `SIZE` parameter through to storage host configuration to the storage controller
* Update `mz_sinks` with an extra column including the size
* Update `SHOW SINKS` to show the size

### PR DESCRIPTION
**Pull request by andrioni**
The sink-equivalent of #13891. Mostly straight-forward, due to reusing all the logic added in that PR, since both are just processes/pods provisioned via the storage controller.

No breaking changes are expected from this PR. Due to not really including any new logic, I'm not gating it behind unsafe mode, but that's easy to change if we want to.

Closes #15214.

### Motivation

  * This PR adds a known-desirable feature: #15214

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - Add `SIZE` parameter to `CREATE SINK`, with the same behavior and set of valid sizes as the one from `CREATE SOURCE`.

### CODE REVIEW

**Comment by benesch** [comment]
Nice! @andrioni could I also talk you into doing the equivalent of #15092 for sinks? I.e., adding a `size` column to `mz_sinks` and to the output of `SHOW SINKS`.

**Comment by andrioni** [comment]
Sure, sounds good!

**Review by bkirwi — APPROVED** [review]
This seems good!

I suspect it's worth setting a source size in testdrive, even though we don't really expect it to change behaviour, just to exercise the code path.

If we're not going to gate this behind unsafe mode, we should update the ticket!

**Comment by andrioni** [comment]
Tests added, going to tackle the other items in separate PRs!

**Review by aljoscha — APPROVED** [review]
Looks good! I'm guessing you're doing `ALTER SINK` or something related next?

**Comment by andrioni** [comment]
Yep, I plan to tackle all the items in #13889 today and next week.

**Pull request merged**
