### PR TITLE
avro: add UUID support

### LINKED ISSUE #3577: support Avro UUID logical types
See title.

### PR DESCRIPTION
**Pull request by mjibson**
Fixes #3577

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4166)

### CODE REVIEW

**Review by ruchirK — APPROVED** [review]
this looks good to me!

**Review by umanwizard — COMMENTED** [review]
Note that in order to properly handle UUIDs in Avro, we also need to add support for recognizing them in schemas.

Check out how `fn parse_string`, `fn parse_long` etc. work in `schema.rs` - for a physical string type, we need to check whether `logicalType` is equal to `UUID` and if so, return a `SchemaPiece::Uuid` instead of `String`.

**Comment by mjibson** [comment]
Can you describe a test that would fail due to lack of schema support?

**Comment by umanwizard** [comment]
given the schema

```
{
    "type": "record",
    "name": "MyData",
    "fields": [{
        "name": "a",
        "type": {
            "type": "string",
            "logicalType": "uuid"
        }]
}
```

ingesting this into materialize will produce a source with one field (`a`) of type `text`, as opposed to type UUID.

**Comment by umanwizard** [comment]
After running `uuid.td` for example:

```
materialize=> show columns from data_view;
 Field | Nullable | Type 
-------+----------+------
 u     | NO       | text
```

**Comment by mjibson** [comment]
Schema support and decoding fixed. RFAL.

**Review by umanwizard — APPROVED** [review]
LGTM, thanks! And sorry the API was so hard to grok - I'll work on implementing the changes we had discussed.

**Pull request merged**
