### PR TITLE
dbt-materialize: patch cluster privilege copy

### PR DESCRIPTION
**Pull request by morsapaes**
See [Slack thread](https://materializeinc.slack.com/archives/C06SXUZ77QF/p1730242003602489).

### CODE REVIEW

**Review by matthelm — APPROVED** [review]
Looks good! Local testing confirms the fix works as expected.

**Review by benesch — COMMENTED** [review]
I'm surprised this didn't get caught by any tests. What are we missing in our test harness that this doesn't get noticed? Are we always using clusters and schemas with the same name, or something?

**Comment by bobbyiliev** [comment]
> I'm surprised this didn't get caught by any tests. What are we missing in our test harness that this doesn't get noticed? Are we always using clusters and schemas with the same name, or something?

The problem with the test seems to be that we only have a test for the `internal_copy_cluster_grants` macro itself:

https://github.com/MaterializeInc/materialize/blob/111df307a8835bd5fd7ff227fccf247c0b101611/misc/dbt-materialize/tests/adapter/test_deploy.py#L126-L133

Testing the macro itself worked fine as it essentially just accepts an old and a new name as the parameters. But we don't have any grants tests in the `TestEndToEndDeployment` test which would have caught that problem.

I will add those.

**Comment by benesch** [comment]
> I will add those.

Fantastic, thanks, Bobby!

**Review by benesch — APPROVED** [review]
LGTM, thanks, Bobby!

**Comment by morsapaes** [comment]
Thanks for adding the tests, @bobbyiliev! 🫶

**Pull request merged**
