### PR TITLE
dataflow: grow the stack in from_mir

### PR DESCRIPTION
**Pull request by mjibson**
### Motivation

  * This PR fixes a recognized bug. #9121

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR adds a release note for any
  [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

**Comment by mjibson** [comment]
I have not been able to verify that this is an actual fix to the linked issue. I've tried, and there's something overflowing the stack in my debug build, and I'm not sure if it's from_mir or not.

**Comment by mjibson** [comment]
I had to bump the stack red zone to 128KiB and then a debug build passes, so I think this does indeed fix the issue.

**Review by frankmcsherry — COMMENTED** [review]
Fwiw, this code is moving in #9186. It will also eventually be removed (per discussion on flattening LIR to support iterative rather than recursive traversal). Happy to land it in the interim after #9186 lands.

**Comment by mjibson** [comment]
Ok. I'll wait on #9186 if we decide to merge this in the mean time.

**Comment by frankmcsherry** [comment]
#9186 landed; I'm happy to rebase this for you (the same changes apply, but just to a different location (`dataflow_types::plan::Plan`).

**Comment by frankmcsherry** [comment]
Well, I did a rebase but cannot push at the branch (looks like I have your remote set up as a URL rather than SSL). It's pretty easy though; lmk if you have questions.

**Comment by mjibson** [comment]
Thanks for the nudge. Rebased.

**Comment by mjibson** [comment]
Can someone approve/comment on this? It fixes crashes during some dev queries.

**Review by umanwizard — APPROVED** [review]

**Comment by mjibson** [comment]
Thanks!

**Pull request merged**
