### PR TITLE
tests: add advent-of-code 2023 puzzles

### PR DESCRIPTION
**Pull request by nrainer-materialize**
This adds the SQL solutions from https://github.com/MaterializeInc/advent-of-code-2023. It will increase our test coverage with respect to WMR.

The original **input data was replaced with custom generated data** or removed in some cases because it is not allowed to use the original data. Input data size was also reduced so that the **execution of all additional SLT files takes about 2.5 minutes** in the test pipeline.

SLT: https://buildkite.com/materialize/slt/builds?branch=nrainer-materialize%3Atests%2Faoc ✅

### CODE REVIEW

**Review by def- — COMMENTED** [review]
This is a lot of code! How much execution time does it add to our CI?

**Comment by nrainer-materialize** [comment]
> This is a lot of code! How much execution time does it add to our CI?

Most tests are fast. Six test files are rather slow (a few minutes each); I moved those to the SLT pipeline. I disabled two files because they are too slow (50+ mins).

**Comment by ggevay** [comment]
This is great! But we need to decide a few things:

EXPLAINS:
This is a lot of new EXPLAINs, and some of these files are pretty slow to run (even ones that are not in the "slow" dir). I'm a bit worried that @frankmcsherry will not like looking at all the new EXPLAIN changes when changing the optimizer. Personally, I'm leaning towards:
- Definitely not having EXPLAINs in those slts that are in the "slow" dir. (If I understand correctly, these are not run in normal CI, but only once a day, so people would forget to rewrite these all the time.)
- Similarly for "too-slow".
- But we could have EXPLAINs in the fast ones, i.e., those that are not in "slow" or "too-slow".
- Some of the fast ones seem not so fast. We could move some of these to "slow".

And the new tests might have already found a bug: I'm getting a test failure when running `test/sqllogictest/advent-of-code/2023/aoc_1203.slt`:
```
    OutputFailure:test/sqllogictest/advent-of-code/2023/aoc_1203.slt:162
            expected: Values(["536277", "79844424"])
            actually: Values(["535235", "79844424"])
```
My command:
```
RUST_BACKTRACE=1 bin/sqllogictest -- -v test/sqllogictest/advent-of-code/2023/aoc_1203.slt
```
@nrainer-materialize, How did you run this when it gave you the result that is currently in the file?

**Comment by ggevay** [comment]
Ok, running all the "fast" ones in release mode on my laptop takes about ~40 seconds, which sounds fine!

**Comment by nrainer-materialize** [comment]
See also: https://materializeinc.slack.com/archives/C01LKF361MZ/p1723469646499059

**Comment by nrainer-materialize** [comment]
The plan is to
* get rid of slow ones
* remove the input of most puzzles and stick to the explain plan of those
* manually create a fast and simple input for some puzzles (due to copyright reasons)

Does this address your concerns, @ggevay?

**Comment by ggevay** [comment]
> Does this address your concerns, @ggevay?

(I responded in the slack discussion.)

**Review by def- — APPROVED** [review]

**Comment by nrainer-materialize** [comment]
Performance:

```
2024-10-15T09:37:16.592083Z  WARN mz_service::grpc: no host provided; request destination host checking is disabled
--- test/sqllogictest/advent-of-code/2023/aoc_1201.slt
--- test/sqllogictest/advent-of-code/2023/aoc_1202.slt
--- test/sqllogictest/advent-of-code/2023/aoc_1203.slt
2024-10-15T09:37:26.299188Z  WARN mz_sql::optimizer_metrics: optimizer took more than 500ms object_type="peek:slow_path" duration="575ms"
2024-10-15T09:37:27.296165Z  WARN mz_sql::optimizer_metrics: optimizer took more than 500ms object_type="peek:slow_path" duration="577ms"
--- test/sqllogictest/advent-of-code/2023/aoc_1204.slt
--- test/sqllogictest/advent-of-code/2023/aoc_1205.slt
--- test/sqllogictest/advent-of-code/2023/aoc_1206.slt
--- test/sqllogictest/advent-of-code/2023/aoc_1207.slt
2024-10-15T09:37:38.270089Z  WARN mz_sql::optimizer_metrics: optimizer took more than 500ms object_type="peek:slow_path" duration="1171ms"
2024-10-15T09:37:40.023705Z  WARN mz_sql::optimizer_metrics: optimizer took more than 500ms object_type="peek:slow_path" duration="1149ms"
--- test/sqllogictest/advent-of-code/2023/aoc_1208.slt
--- test/sqllogictest/advent-of-code/2023/aoc_1209.slt
--- test/sqllogictest/advent-of-code/2023/aoc_1210.slt
2024-10-15T09:37:45.826796Z  WARN mz_sql::optimizer_metrics: optimizer took more than 500ms object_type="peek:slow_path" duration="530ms"
2024-10-15T09:37:50.203721Z  WARN mz_sql::optimizer_metrics: optimizer took more than 500ms object_type="peek:slow_path" duration="526ms"
--- test/sqllogictest/advent-of-code/2023/aoc_1211.slt
--- test/sqllogictest/advent-of-code/2023/aoc_1212.slt
--- test/sqllogictest/advent-of-code/2023/aoc_1213.slt
--- test/sqllogictest/advent-of-code/2023/aoc_1214.slt
--- test/sqllogictest/advent-of-code/2023/aoc_1215.slt
2024-10-15T09:38:35.950817Z  WARN mz_sql::optimizer_metrics: optimizer took more than 500ms object_type="peek:slow_path" duration="510ms"
--- test/sqllogictest/advent-of-code/2023/aoc_1216.slt
--- test/sqllogictest/advent-of-code/2023/aoc_1217.slt
--- test/sqllogictest/advent-of-code/2023/aoc_1218.slt
--- test/sqllogictest/advent-of-code/2023/aoc_1219.slt
--- test/sqllogictest/advent-of-code/2023/aoc_1220.slt
--- test/sqllogictest/advent-of-code/2023/aoc_1221.slt
--- test/sqllogictest/advent-of-code/2023/aoc_1222.slt
--- test/sqllogictest/advent-of-code/2023/aoc_1223.slt
2024-10-15T09:39:35.527378Z  WARN mz_sql::optimizer_metrics: optimizer took more than 500ms object_type="peek:slow_path" duration="751ms"
2024-10-15T09:39:43.671138Z  WARN mz_sql::optimizer_metrics: optimizer took more than 500ms object_type="peek:slow_path" duration="754ms"
--- test/sqllogictest/advent-of-code/2023/aoc_1224.slt
--- test/sqllogictest/advent-of-code/2023/aoc_1225.slt
2024-10-15T09:39:48.840176Z  WARN mz_persist_client::rpc: pubsub connection err: status: Unknown, message: "h2 protocol error: error reading a body from connection", details: [], metadata: MetadataMap { headers: {} }
```

**Comment by def-** [comment]
@ggevay I also noticed a bunch of `2024-10-15T09:37:26.299188Z  WARN mz_sql::optimizer_metrics: optimizer took more than 500ms object_type="peek:slow_path" duration="575ms"` in other tests. Is this warning useful or should we silence it in tests?

**Comment by ggevay** [comment]
Thank you, this looks great!

> I also noticed a bunch of 2024-10-15T09:37:26.299188Z  WARN mz_sql::optimizer_metrics: optimizer took more than 500ms object_type="peek:slow_path" duration="575ms" in other tests. Is this warning useful or should we silence it in tests?

I think we can disable it in tests for now. At some point, when we decide that we want to improve optimizer performance, we'll probably want to gather examples of tests where this warning is happening, but we can do that by temporarily re-enabling it locally. @mgree, what do you think?

**Review by ggevay — APPROVED** [review]

**Comment by mgree** [comment]
I think we should certainly ignore it in tests, at least for now. I'm fine having it silenced.

We should have some (more meaningful) notices from production soon, but until then it may be worth taking a quick look at where it's firing here to understand which queries are optimizing slowly.

**Pull request merged**
