### PR TITLE
coordtest: selectively enable persistent user tables

### PR DESCRIPTION
**Pull request by danhhz**
This plumbing is pretty gross, but here's an example of how this might work

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/8480)

### CODE REVIEW

**Comment by mjibson** [comment]
Our current thought is that we will wait on implementing this in coordtest until persist booting is better handled and doesn't have this plumbing. This isn't high on the priority list so will wait.

**Comment by mjibson** [comment]
I pushed a test to this that appears to work. LGTM.

**Comment by mjibson** [comment]
This is currently failing due to the cancel.ct test on the await-sql line.

**Comment by danhhz** [comment]
cleaning up old branches

**Pull request closed without merging**
