### PR TITLE
Unrevert permutations

### PR DESCRIPTION
**Pull request by umanwizard**
The first commit is a rehash of #9806 . 

The second commit fixes an issue where we were planning an MFP node and discarding arrangements unnecessarily in certain cases. During LIR planning, we checked whether the left-over MFP was _logically_ trivial, and if so, didn't plan it. However, we should also check if it's _physically_ trivial after applying the permutation to it -- if so, we can avoid planning it and discarding arrangements.

The third commit fixes an issue where we were re-creating the raw collection in `CollectionBundle` every time it was demanded, rather than only once. This was handled correctly in the previous code before the permutations PR was landed, but somehow I accidentally got rid of the check.

### Motivation

Fixes the performance regressions that forced us to revert #9806 in #10356 .

### Tips for reviewer

* There are three commits. The first is just re-applying the old permutations PR that has already been reviewed. The next two are the actually interesting ones that fix performance regressions.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
CC @philip-stoev.

The `Dataflow` suite is now equal or faster across the board:
```
NAME                      |    THIS     |    OTHER    |  Regression?  | 'THIS' is:                                                                                   
----------------------------------------------------------------------------------------------------                                                                 
OrderBy                   |       2.598 |       3.310 |      no       | 21.5 pct   faster                                                                            
CountDistinct             |       0.353 |       0.378 |      no       | 6.6 pct   faster                                                                             
MinMax                    |       0.992 |       1.013 |      no       | 2.1 pct   faster                                                                             
GroupBy                   |       2.906 |       2.980 |      no       | 2.5 pct   faster                                                                             
CrossJoin                 |       1.472 |       1.573 |      no       | 6.4 pct   faster                                                                             
Retraction                |       1.480 |       3.785 |      no       | 2.6 times faster                                                                             
CreateIndex               |       0.102 |       0.109 |      no       | 6.4 pct   faster                                                                             
DeltaJoin                 |       0.123 |       0.133 |      no       | 7.6 pct   faster                                                                             
DifferentialJoin          |       0.249 |       0.255 |      no       | 2.1 pct   faster                                                                             
```

I will try nightlies and full SLT on this PR before landing. Let me know if there is anything else you suggest.
 
- [N/A] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

**Comment by umanwizard** [comment]
Nightlies: https://buildkite.com/materialize/nightlies/builds/617 (Only failures are already existing problems on main)

**Review by frankmcsherry — APPROVED** [review]
These look good to me. Thanks very much!

**Comment by umanwizard** [comment]
Full SLT passed: https://buildkite.com/materialize/sql-logic-tests/builds?branch=47e471b5a9831932e32001859ae7692f1f17113d

**Comment by umanwizard** [comment]
@philip-stoev , do you have any further tests you want to run on this before we land? Nightlies and Full SLT are green (except for known flaky tests on the nightlies)

**Comment by umanwizard** [comment]
I will wait until Sofia working hours at least before I land this, so Philip can comment.

**Comment by philip-stoev** [comment]
Just for the record, there is a residual performance regression with the Create Index test, but only at scales 7 and 8:

```
NAME                      |    THIS     |    OTHER    |  Regression?  | 'THIS' is:
----------------------------------------------------------------------------------------------------
CreateIndex               |      16.583 |      15.450 |      no       | 7.3 pct   slower
```

I do not want to move the goalposts here while the PR is open, and we are talking about indexing 100M records in 16 seconds, which I think is acceptable. So I am mentioning this just for the record, no action necessary.

**Review by philip-stoev — APPROVED** [review]
A quick RQG run revealed no panics or wrong results, so I think this is good to go.

**Comment by umanwizard** [comment]
@philip-stoev that might be related to the TODO I left in the code. If you're sure it's not noise, I will follow up.

**Comment by umanwizard** [comment]
(Merging because the benchmarks show a 2x improvement on another metric, so it seems like a worthwhile tradeoff to have this in main now)

**Pull request merged**
