### PR TITLE
python: use 3.10+ import style for list, set, ...

### PR DESCRIPTION
**Pull request by nrainer-materialize**
### Motivation

As discussed in https://materializeinc.slack.com/archives/C0542UGTLAV/p1692014536645429, point 3: Use the 3.10+ import style.

* Their use is the suggested way; importing these types from `typing` is deprecated.
* They don't require imports.
* This is the style used in the cloud repo.

### References
* https://stackoverflow.com/a/68199246/584532
* https://peps.python.org/pep-0585/#implementation

### CODE REVIEW

**Review by philip-stoev — APPROVED** [review]
Thank you. I wonder if we can disallow the use of the ones with a starting capital letter.

**Comment by nrainer-materialize** [comment]
> Thank you. I wonder if we can disallow the use of the ones with a starting capital letter.

That would be great. I will research if I can find anything.
@necaris wrote in the discussion:
> We should definitely also enforce this through the linter, although I don't see an immediate rule for it.

**Comment by necaris** [comment]
@nrainer-materialize there are lint rules in `ruff` (the linter we use in the cloud repo): 
 - https://beta.ruff.rs/docs/rules/non-pep585-annotation/

...and also:
 - https://beta.ruff.rs/docs/rules/non-pep604-annotation/
 - https://beta.ruff.rs/docs/rules/quoted-annotation/

But I don't know the setup in the materialize repo well enough. I'd recommend moving to `ruff` in this repo as well, FWIW, and can come up with a PR for it.

**Comment by nrainer-materialize** [comment]
TODO: `dbt-materialize tests` is failing.

**Comment by necaris** [comment]
@nrainer-materialize added #21402 to enforce this by changing linters :smile:

**Comment by nrainer-materialize** [comment]
> @nrainer-materialize added #21402 to enforce this by changing linters 😄

Thank you for adding this, @necaris!

**Pull request merged**
