### PR TITLE
ci: Disable fast-path peeks again

### PR DESCRIPTION
**Pull request by def-**
See discussion in https://github.com/MaterializeInc/materialize/pull/23353

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by def-** [comment]
@bkirwi Seems not so easy to undo, lots of `Explained Query (fast path)`. Do you think this still makes sense?

**Review by nrainer-materialize — APPROVED** [review]

**Comment by bkirwi** [comment]
Ah - it looks like there are tests as part of https://github.com/MaterializeInc/materialize/pull/22060 that depend on the explain output.

I'll push up a commit with that disabled and see what y'all think!

**Review by def- — COMMENTED** [review]
Ok for me, assuming this is the only problem. I'll trigger nightly.

**Comment by bkirwi** [comment]
Thanks! I'm hoping to finally be able to focus on this over the next week or two (though it's not the first time I think this 😓) so ideally we won't have to have it flagged off for long...

**Pull request merged**
