### PR TITLE
persist: remove the old persist integration.

### PR DESCRIPTION
**Pull request by ruchirK**
### Motivation

This PR removes all external uses of the mz-persist crate. We're going to be building a new storage service which will house the persist integration, and the details of how that gets wired through adapter -> storage -> persist will likely look completely different.

### Testing

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Comment by ruchirK** [comment]
I'm going to let CI spin on this and adjust tests as needed. Ignore the commit structure here if thats easier - this will all get squashed into one commit.

**Review by benesch — APPROVED** [review]
LGTM if CI is happy!

**Comment by ruchirK** [comment]
I can look at this later tonight i suspect there was some extra deletions in the ingestion pipeline code

**Comment by ruchirK** [comment]
im not sure if the kafka exactly once sinks timestamp bindings verification was flaky before these changes but other than that CI seems good to go. @benesch I'm going to sign off for tonight but if you want to hit merge go for it

**Comment by benesch** [comment]
This is so wonderful. Thanks very much for getting this through tests, @ruchirK! LGTM.

**Review by aljoscha — COMMENTED** [review]
Also wanted to +1 this after the fact. 🎉

**Pull request merged**
