### PR TITLE
add bin/scratch-login

### PR DESCRIPTION
**Pull request by guswynn**
### Motivation

I struggle to remember the login command each day

### Tips for reviewer

This can't go in `bin/scratch login` because argument parsing in `bin/scratch` requires access to aws

### Checklist

- N/A This PR has adequate test coverage / QA involvement has been duly considered.
- N/A This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

**Comment by benesch** [comment]
> This can't go in bin/scratch login because argument parsing in bin/scratch requires access to aws

Wait, what?!

**Comment by benesch** [comment]
Oh, I see.

**Comment by benesch** [comment]
I fixed that argparse thing in https://github.com/MaterializeInc/materialize/pull/10358.

**Comment by guswynn** [comment]
closing in favor of the other pr

**Pull request closed without merging**
