### PR TITLE
Fix soundness hole in QGM implementation

### PR DESCRIPTION
**Pull request by petrosagg**
### Motivation

The API exposed was previously unsound as it was possible through safe
use to obtain two aliasing &mut references to the Model

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### CODE REVIEW

**Comment by aalexandrov** [comment]
I thought the original signature was nicer because the only way to get a mutable reference to a vertex was through a mutable reference to a `Model`.

```rust
let mut model = todo!();
let mut v1 = model.get_mut_box(BoxId(1)); // consumes a mutable reference of model as part of v1
let mut v2 = model.get_mut_box(BoxId(2)); // doesn't work because v1 is still in scope
```

**Comment by aalexandrov** [comment]
> it was possible through safe use to obtain two aliasing &mut references to the Model.

What is a minimal example that demonstrates this?

**Comment by petrosagg** [comment]
@aalexandrov I made a minimal example in order to run it through Miri and to my surprise it passed :S This is what I had in mind:

```diff
diff --git a/src/sql/src/query_model/test/mod.rs b/src/sql/src/query_model/test/mod.rs
index 0c75fab4e..250caa11b 100644
--- a/src/sql/src/query_model/test/mod.rs
+++ b/src/sql/src/query_model/test/mod.rs
@@ -15,7 +15,7 @@ use crate::plan::{HirRelationExpr, StatementContext};
 use mz_expr_test_util::generate_explanation;
 use mz_lowertest::*;

-use crate::query_model::Model;
+use crate::query_model::model::{Model, QuantifierType};
 use catalog::TestCatalog;

 use crate::names::resolve_names_stmt;
@@ -157,3 +157,14 @@ fn test_qgm() {
         })
     });
 }
+
+#[test]
+fn miri_test_qgm() {
+    let mut model = Model::default();
+    let input_id = model.make_select_box();
+    let parent_id = model.make_select_box();
+    let quantifier_id = model.make_quantifier(QuantifierType::Foreach, input_id, parent_id);
+
+    let mut quantifier = model.get_mut_quantifier(quantifier_id);
+    let _input = quantifier.input_box();
+}
```

Thanks for pushing back, I'll close this PR until I understand this better, it seems ok on a closer look

**Comment by aalexandrov** [comment]
FWIW I think it's good to remove one level of boxing (IIRC I also suggested it at some point), so I am happy to approve the second commit.

If it helps, here is my line of reasoning for the `unsafe` block in the current encoding:

- We could not find a to make the borrow-checker happy while encoding a graph structure with compile-time references.
- The solution was to to promote the graph `Model` to a first-class object and use runtime borrows.
- Originally, client code was responsible was full with code like `model.boxes.get(x).borrow()`, so I wanted to hide the fact that we are using `RefCell` internally behind an abstraction.
- The intent of the unsafe block is that you want to attach the context (that is, the owner) of the mutable `RefMut` when you return it. `BoundRefMut<'_, T>` implements `Deref<T>` so client code can treat results as references of type `T`, but we can also add convenience methods on `BoundRefMut` to reduce syntactic noise when navigating through chains of boxes and quantifiers that require the enclosing context. See [this code](https://github.com/MaterializeInc/materialize/blob/ae9174fb54d24bc0558cf450cc8df2ee4780772d/src/sql/src/query_model/model/graph.rs#L905-L913) for example. 

The last line of your example is using this convenience syntax. Take a look at #10215 for more context.

**Pull request closed without merging**
