### PR TITLE
dyncfg: split dynamic configuration into a new mz_dyncfg crate

### PR DESCRIPTION
**Pull request by danhhz**
dyncfg: split dynamic configuration into a new mz_dyncfg crate

So it can be used everywhere.

As #24621 and #24658 showed, there are some footguns left to address, in
particular around registration. So, probably not going to talk about
this too widely yet, until those are addressed somehow.

### Motivation

   * This PR refactors existing code.

### Tips for reviewer

I have a weak preference for spelling it dyncfg over dyn_cfg, but happy to discuss if someone has a strong preference otherwise!

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by benesch** [comment]
The basic structure and naming of “dyncfg” LGTM. Will leave explicit approval to Ben since this touches a lot of persist code.

**Review by ParkMyCar — APPROVED** [review]
Stamping to clear the adapter block

**Comment by danhhz** [comment]
@bkirwi friendly ping :)

**Review by bkirwi — APPROVED** [review]
Pleasantly straightforward!

**Comment by danhhz** [comment]
TFTRs!

**Pull request merged**
