### PR TITLE
Support json_agg

### PR DESCRIPTION
**Pull request by JLDLaughlin**
Fixes: #2400

```
materialize=> select jsonb_agg(1);
 jsonb_agg
-----------
 [1.0]
(1 row)

materialize=> select jsonb_agg('a');
 jsonb_agg
-----------
 ["a"]
(1 row)

materialize=> select jsonb_agg('"a", 1');
  jsonb_agg
--------------
 ["\"a\", 1"]
(1 row)
```

NOTE: This doesn't work when the input is a sql record (as mentioned by @jamii below). Created an issue for this: https://github.com/MaterializeInc/materialize/issues/2414

### CODE REVIEW

**Comment by jamii** [comment]
> Where it's breaking...

The input there is a sql record, which we don't support yet - https://github.com/MaterializeInc/materialize/issues/1514. Nothing specific to jsonb_agg.

```
jamie=# select pg_typeof(('a', 1));
 pg_typeof 
-----------
 record
(1 row)
```

**Comment by jamii** [comment]
Minor nit - it should be `jsonb_agg` rather than `json_agg` to match the other supported functions.

**Comment by cuongdo** [comment]
@JLDLaughlin could you add a relevant release note to `doc/user/release-notes.md`?

**Comment by JLDLaughlin** [comment]
Yes! https://github.com/MaterializeInc/materialize/pull/2492

**Pull request merged**
