### PR TITLE
Add a command line option to log the logging dataflows

### PR DESCRIPTION
**Pull request by ruchirK**
The first commit is a functionality preserving refactor and the second commit adds the option

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4563)

### CODE REVIEW

**Comment by ruchirK** [comment]
@elindsey this should make your work of adding a new log for up to date-ness easier to debug!

**Review by benesch — COMMENTED** [review]
Nice!

> Reviewed 6 of 6 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4563#-:-MK8ZllS652CkQ3DJp9y:b-83sjoh)* status: all files reviewed, 2 unresolved discussions (waiting on @ruchirK)

___
*[src/dataflow/src/server.rs, line 414 at r2](https://reviewable.io/reviews/materializeinc/materialize/4563#-MK8Yvno2vzSOq52rob2:-MK8Yvno2vzSOq52rob3:b-3qi185) ([raw file](https://github.com/materializeinc/materialize/blob/c93f712e5a751edcbf663f8cf1a5717edcdc2184/src/dataflow/src/server.rs#L414)):*
> ```Rust
>                 m_linked,
>             ));
>         }
> ```

Proposal:

```
let t_traces = t_traces.get_or_insert_with(|| logging::timely::construct(...));
let d_traces = d_traces.get_or_insert_with(|| logging::timely::construct(...));

for (log, (_, trace)) in t_traces {
    // ...
}
```

(Avoids having to `.expect` the options.)
___
*[src/materialized/src/bin/materialized.rs, line 103 at r2](https://reviewable.io/reviews/materializeinc/materialize/4563#-MK8ZSYo8SFOR-cB5Jxu:-MK8ZSYo8SFOR-cB5Jxv:b-e4kmxm) ([raw file](https://github.com/materializeinc/materialize/blob/c93f712e5a751edcbf663f8cf1a5717edcdc2184/src/materialized/src/bin/materialized.rs#L103)):*
> ```Rust
>         "log-logging",
>         "enable logging the logging dataflows (DANGEROUS)",
>     );
> ```

There is no valid reason for an end user to enable this, right? I'd love to avoid adding this to the public API surface if so. Can we make it look more like `--symbiosis`, where its description is "internal use only"? (One day I'll figure out how to elide those options from the usage text entirely.) Requiring experimental mode would be good too to prevent anyone from relying on it accidentally.

**Review by ruchirK — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4563)* status: all files reviewed, 2 unresolved discussions (waiting on @benesch and @ruchirK)

___
*[src/materialized/src/bin/materialized.rs, line 103 at r2](https://reviewable.io/reviews/materializeinc/materialize/4563#-MK8ZSYo8SFOR-cB5Jxu:-MKAs7K0DW0ZKEi4fsui:b-tkvg1l) ([raw file](https://github.com/materializeinc/materialize/blob/c93f712e5a751edcbf663f8cf1a5717edcdc2184/src/materialized/src/bin/materialized.rs#L103)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

There is no valid reason for an end user to enable this, right? I'd love to avoid adding this to the public API surface if so. Can we make it look more like `--symbiosis`, where its description is "internal use only"? (One day I'll figure out how to elide those options from the usage text entirely.) Requiring experimental mode would be good too to prevent anyone from relying on it accidentally.
</blockquote></details>

So the one case where a end user might want to enable this is if they have some kind of slow leak that we suspect is related to the logging dataflows -- then it would be nice to have the user log the logging and see what those dataflows are doing.

that won't be super common but it definitely would have helped us with one user in the past. not sure if that changes your opinion on what the description should be / whether it should be tied to experimental mode?

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4563)* status: all files reviewed, 2 unresolved discussions (waiting on @ruchirK)

___
*[src/materialized/src/bin/materialized.rs, line 103 at r2](https://reviewable.io/reviews/materializeinc/materialize/4563#-MK8ZSYo8SFOR-cB5Jxu:-MKAvSbm7SPqVZQSe3R-:bt8kv0d) ([raw file](https://github.com/materializeinc/materialize/blob/c93f712e5a751edcbf663f8cf1a5717edcdc2184/src/materialized/src/bin/materialized.rs#L103)):*
<details><summary><i>Previously, ruchirK (Ruchir Khaitan) wrote…</i></summary><blockquote>

So the one case where a end user might want to enable this is if they have some kind of slow leak that we suspect is related to the logging dataflows -- then it would be nice to have the user log the logging and see what those dataflows are doing.

that won't be super common but it definitely would have helped us with one user in the past. not sure if that changes your opinion on what the description should be / whether it should be tied to experimental mode?
</blockquote></details>

Hmm, ok, so maybe we don't require experimental mode and just make this "internal use only". I'm mostly worried about the naming/understandability of these CLI flags for end users. We have `--log-file` for controlling what people normally think of logging, `--logging-granularity` which controls the unrelated concept of timely logging, and now `--log-logging` which is about as confusing a name as a CLI flag can have :D. I don't have anything better to offer, which is why I think hiding this away from users is the best option for now.

**Review by ruchirK — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4563)* status: all files reviewed, 2 unresolved discussions (waiting on @benesch and @ruchirK)

___
*[src/materialized/src/bin/materialized.rs, line 103 at r2](https://reviewable.io/reviews/materializeinc/materialize/4563#-MK8ZSYo8SFOR-cB5Jxu:-MKBFTVS4Ckw46ZtSXhm:b-vv6vji) ([raw file](https://github.com/materializeinc/materialize/blob/c93f712e5a751edcbf663f8cf1a5717edcdc2184/src/materialized/src/bin/materialized.rs#L103)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Hmm, ok, so maybe we don't require experimental mode and just make this "internal use only". I'm mostly worried about the naming/understandability of these CLI flags for end users. We have `--log-file` for controlling what people normally think of logging, `--logging-granularity` which controls the unrelated concept of timely logging, and now `--log-logging` which is about as confusing a name as a CLI flag can have :D. I don't have anything better to offer, which is why I think hiding this away from users is the best option for now.
</blockquote></details>

Naming is definitely hard here. what about something like `--debug-timely-logging` - would that be better?

**Review by ruchirK — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4563)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @benesch)

___
*[src/dataflow/src/server.rs, line 414 at r2](https://reviewable.io/reviews/materializeinc/materialize/4563#-MK8Yvno2vzSOq52rob2:-MKBKGA4-vNBz2N9YLQU:bz04gn) ([raw file](https://github.com/materializeinc/materialize/blob/c93f712e5a751edcbf663f8cf1a5717edcdc2184/src/dataflow/src/server.rs#L414)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Proposal:

```
let t_traces = t_traces.get_or_insert_with(|| logging::timely::construct(...));
let d_traces = d_traces.get_or_insert_with(|| logging::timely::construct(...));

for (log, (_, trace)) in t_traces {
    // ...
}
```

(Avoids having to `.expect` the options.)
</blockquote></details>

`get_or_insert_with` seems like a nightly only method thats only available for hashsets? I reworked it to use extend and avoid the Option that way - lmk if that works for you

**Review by benesch — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4563#-:-MKGOX-tAy-z_7JnHDw0:b-uwkowd)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @benesch and @ruchirK)

___
*[src/dataflow/src/server.rs, line 414 at r2](https://reviewable.io/reviews/materializeinc/materialize/4563#-MK8Yvno2vzSOq52rob2:-MKGOaVV0exReO9B7vhl:bdb5y93) ([raw file](https://github.com/materializeinc/materialize/blob/c93f712e5a751edcbf663f8cf1a5717edcdc2184/src/dataflow/src/server.rs#L414)):*
<details><summary><i>Previously, ruchirK (Ruchir Khaitan) wrote…</i></summary><blockquote>

`get_or_insert_with` seems like a nightly only method thats only available for hashsets? I reworked it to use extend and avoid the Option that way - lmk if that works for you
</blockquote></details>

This is fine, but it's definitely a thing on `Option`! https://doc.rust-lang.org/std/option/enum.Option.html#method.get_or_insert_with

**Review by ruchirK — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4563)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @benesch)

___
*[src/dataflow/src/server.rs, line 414 at r2](https://reviewable.io/reviews/materializeinc/materialize/4563#-MK8Yvno2vzSOq52rob2:-MKGPdSb14wwUhqBOjXd:bis77wq) ([raw file](https://github.com/materializeinc/materialize/blob/c93f712e5a751edcbf663f8cf1a5717edcdc2184/src/dataflow/src/server.rs#L414)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This is fine, but it's definitely a thing on `Option`! https://doc.rust-lang.org/std/option/enum.Option.html#method.get_or_insert_with
</blockquote></details>

ohhh i see what you meant now sorry!

**Pull request merged**
