### PR TITLE
scalability framework: rework plots, introduce boxplot

### PR DESCRIPTION
**Pull request by nrainer-materialize**
* b5d05ed106 scalability framework: minor
* 10bbd8a433 scalability framework: result recording
* 8d6bec301b scalability framework: plots: refactor
* 1fa84cb524 scalability framework: plots: reduce endpoint offset
* 0a95c910f0 scalability framework: plots: boxplot for latency
* 7afcd3466a scalability framework: plots: use boxplot
* 549f3c4389 scalability framework: plots: rename methods
* 8339cf8a25 scalability framework: plots: set ticks

### CODE REVIEW

**Comment by philip-stoev** [comment]
@nrainer-materialize do you have any examples of the new plots?

**Comment by nrainer-materialize** [comment]
Hm... The linting issue does not occur locally. It is also expected to no longer occur with https://github.com/MaterializeInc/materialize/pull/22823.

**Comment by nrainer-materialize** [comment]
> @nrainer-materialize do you have any examples of the new plots?

Oh yeah, I actually wanted to append it to the PR. Forgot that, here it is:
Bildschirmfoto 2023-10-31 um 12 29 46

**Comment by philip-stoev** [comment]
@nrainer-materialize for the uninitiated, how does one interpret the circles, the box, the yellow line and the bars? I have some very rough idea but we should have it in writing in the README.md file.

**Comment by nrainer-materialize** [comment]
> @nrainer-materialize for the uninitiated, how does one interpret the circles, the box, the yellow line and the bars? I have some very rough idea but we should have it in writing in the README.md file.
> 
> EDIT: https://en.wikipedia.org/wiki/Box_plot this has a legend, if it is indeed correct you can copy it over to the README.md

Yes, you are right. I will add some description in a follow-up PR.

**Review by philip-stoev — APPROVED** [review]

**Pull request merged**
