### PR TITLE
sql: disallow multiple unnamed columns in views

### LINKED ISSUE #9376: Error while reading view with column named `?column?` on Metabase
### What version of Materialize are you using?

From the shell:

```
materialize=> select mz_version();
       mz_version
-------------------------
 v0.10.1-dev (d68ab011e)
(1 row)
```
(#9366 as of some moment yesterday)

### How did you install Materialize?

* [x] Built from source

### What was the issue?

When trying to visualize the results of a view with column with a RECORD type without giving it a proper alias, the following error is returned:
```
ERROR: column "public.record_test.?column?" does not exist
```

### Is the issue reproducible? If so, please provide reproduction instructions.

Create a view with a RECORD without aliasing the resulting column, e.g.
```sql
create view record_test as select row(1,2,3);
```
and then try to visualize it on Metabase.

### Please attach any applicable log files.

[Gist with pgwire=trace logs](https://gist.github.com/andrioni/9d2af4f49f998500cd20bb0862b5602d)

Select fragment of the queries being executed from the gist above:
```sql
BEGIN READ ONLY;

-- Metabase:: userID: 1 queryType: MBQL queryHash: f373d90ba1367f7af1fab8c2a00441a9351bac42b93d32afb1975fe961e8f8d2
SELECT "public"."record_test"."?column?" AS "?column?" FROM "public"."record_test" LIMIT 2000

error code=XX000 message=column "public.record_test.?column?" does not exist
```

### PR DESCRIPTION
**Pull request by mjibson**
Unnamed columns in views should have a concrete name of
`?column?`. Previously they were rust `None` which we ignored and
converted to `?column?` at some later time.

Fixes #9376

### Motivation

  * This PR fixes a recognized bug. #9376

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR adds a release note for any
  [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

**Comment by mjibson** [comment]
RFAL

**Comment by mjibson** [comment]
This is failing in `kafka-avro-sinks.td` because we had multiple unnamed columns, which is now an error. When changed to a single unnamed column, kafka still fails. When I hardcode the column to be named `?column?` it fails in the same way, leading me to believe that something in the sink/kafka path is not able to handle columns with question marks.

**Comment by benesch** [comment]
> When changed to a single unnamed column, kafka still fails. When I hardcode the column to be named `?column?` it fails in the same way, leading me to believe that something in the sink/kafka path is not able to handle columns with question marks.

What is the actual error in this case? I'm pretty sure record names in Avro have some serious constraints (alphanumeric IIRC), so we'll need to apply some transformation to the field names.

**Comment by mjibson** [comment]
```
> CREATE VIEW unnamed_cols AS SELECT 1 as "?column?", 2 AS b

> CREATE SINK unnamed_cols_sink FROM unnamed_cols
  INTO KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'unnamed-cols-sink'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'

$ kafka-verify format=avro sink=materialize.public.unnamed_cols_sink
{"before": null, "after": {"row": {"?column?": 1, "b": 2}}}
```

Errors with the very vague:

```
> CREATE VIEW unnamed_cols AS SELECT 1 as "?column?", 2 AS b
rows match; continuing
> CREATE SINK unnamed_cols_sink FROM unnamed_cols INTO KAFKA BROKER 'local...

test/testdrive/kafka-avro-sinks.td:19:1: error: executing query failed: db error: ERROR: error publishing kafka schemas for sink: unable to publish value schema to registry in kafka sink: Either the input schema or one its references is invalid
     |
  18 | 
  19 | > CREATE SINK unnamed_cols_sink FROM unnamed_cols
```

**Comment by mjibson** [comment]
Guessing: the avro stuff detects the `None` variant for column names and does things, but that case has been removed for Views here. I can try to dig a bit more.

**Comment by benesch** [comment]
Yeah: 

The name portion of a fullname, record field names, and enum symbols must:

> The name portion of a fullname, record field names, and enum symbols must:
> start with [A-Za-z_]
> subsequently contain only [A-Za-z0-9_]

So, the code that previously took unnamed columns and invented names for them used to live here: https://github.com/MaterializeInc/materialize/blob/47c3d7260c13add758acb7f34052304a712bf97a/src/interchange/src/encode.rs#L38-L46. That code will now never fire, which is great. Something to clean up later. 

The problem, then is that when we go to make the Avro schema we blindly use the column name as the record field name: https://github.com/MaterializeInc/materialize/blob/47c3d7260c13add758acb7f34052304a712bf97a/src/interchange/src/json.rs#L365. This is only valid if the column name happens to be a valid Avro field name. 

We should probably come up with some transformation that takes a column name to a valid Avro name. That sounds tricky though. I'd advocate for just commenting out the test for now, and filing an issue about the general problem of column names that can't be represented as Avro field names. (Like, you could just as well have a column named `@$#%&^` and we should have a better story for that in general. But the workaround of "rename your columns before you make a sink off of them" is just fine for the moment, I think!)

**Review by benesch — APPROVED** [review]
LGTM, assuming commenting out the one or two failing Avro tests as discussed is easy. This is gonna be a bit painful on our users, but that's an argument for doing it sooner rather than later.

**Pull request merged**
