### PR TITLE
lint: Warn on unused mut reference

### PR DESCRIPTION
**Pull request by jkosh44**
This commit adds a lint that produces a warning when a mutable
reference is never used mutably. Additionally, it fixes all existing
violations of this lint.

While we're altering lints, this commit also updates the
"overflow_check_conditional" lint, which has been renamed to
"panicking_overflow_checks"
(https://rust-lang.github.io/rust-clippy/master/index.html#panicking_overflow_checks)

### Motivation
This PR refactors existing code.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [X] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [X] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

**Review by antiguru — APPROVED** [review]
I think this is a fine change!

**Comment by jkosh44** [comment]
My assumption here is that the `mut`s are unintentional and not some way of marking a function as "mutable in spirit". To be safe I'll wait for an approval from all teams before merging.

Inspired by @antiguru.

**Review by benesch — APPROVED** [review]

**Review by nrainer-materialize — APPROVED** [review]

**Review by ParkMyCar — APPROVED** [review]
This will also make "mutable in spirit" cases more obvious since you'll need to allow the lint, big 👍 from me

**Comment by jkosh44** [comment]
@danhhz or @bkirwi a persist sign off is the last that I need.

**Comment by danhhz** [comment]
Oh sorry, LGTM!

**Pull request merged**
