### PR TITLE
sql: allow purify to access catalog before await

### PR DESCRIPTION
**Pull request by benesch**

### CODE REVIEW

**Comment by benesch** [comment]
Much better with whitespace enabled: https://github.com/MaterializeInc/materialize/pull/6610/files?diff=unified&w=1

**Review by petrosagg — APPROVED** [review]
that looks great! I'll try to build on top of it

**Comment by petrosagg** [comment]
actually, is it ok if I incorporate this commit in my PR, the structure might change a bit but not much

**Comment by benesch** [comment]
Yes, please do! That’s why I marked this as a draft!

**Comment by petrosagg** [comment]
This is now incorporated in #6673

**Pull request closed without merging**
