### PR TITLE
Support placeholders in EXPLAIN

### LINKED ISSUE #2498: EXPLAINing a query with a parameter panics the server
```
[nix-shell:~/materialize]$ RUST_BACKTRACE=full cargo run --bin=sqllogictest ./test/sqllogictest/explain.slt -vvvv
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
     Running `target/debug/sqllogictest ./test/sqllogictest/explain.slt -vvvv`
==> ./test/sqllogictest/explain.slt
    EXPLAIN SQL FOR SELECT * FROM (SELECT 1)
    EXPLAIN RAW PLAN FOR SELECT * FROM (SELECT 1)
    EXPLAIN RAW PLAN FOR SELECT (SELECT (SELECT 1))
    EXPLAIN TYPED RAW PLAN FOR SELECT * FROM (SELECT 1)
    EXPLAIN DECORRELATED PLAN FOR SELECT * FROM (SELECT 1)
    EXPLAIN OPTIMIZED PLAN FOR SELECT * FROM (SELECT 1)
    EXPLAIN PLAN FOR SELECT * FROM (SELECT 1)
    CREATE VIEW foo AS SELECT * FROM (SELECT 1)
    EXPLAIN DECORRELATED PLAN FOR VIEW foo
    EXPLAIN PLAN FOR VIEW foo
    EXPLAIN TYPED DECORRELATED PLAN FOR VIEW foo
    EXPLAIN PLAN FOR SELECT $1
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/sql/expr.rs:898:29
stack backtrace:
   0:     0x56506e243c24 - backtrace::backtrace::libunwind::trace::h90669f559fb267f0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x56506e243c24 - backtrace::backtrace::trace_unsynchronized::hffde4e353d8f2f9a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x56506e243c24 - std::sys_common::backtrace::_print_fmt::heaf44068b7eaaa6a
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x56506e243c24 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h88671019cf081de2
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x56506e265e9c - core::fmt::write::h4e6a29ee6319c9fd
                               at src/libcore/fmt/mod.rs:1052
   5:     0x56506e23d297 - std::io::Write::write_fmt::hf06b1c86d898d7d6
                               at src/libstd/io/mod.rs:1426
   6:     0x56506e2460a5 - std::sys_common::backtrace::_print::h404ff5f2b50cae09
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x56506e2460a5 - std::sys_common::backtrace::print::hcc4377f1f882322e
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x56506e2460a5 - std::panicking::default_hook::{{closure}}::hc172eff6f35b7f39
                               at src/libstd/panicking.rs:204
   9:     0x56506e245d91 - std::panicking::default_hook::h7a68887d113f8029
                               at src/libstd/panicking.rs:224
  10:     0x56506ddfc178 - <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call::ha7c83d594f1eb56e
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1029
  11:     0x56506ddfb95c - ore::panic::set_abort_on_panic::{{closure}}::h7870aa0c70be54d3
                               at src/ore/panic.rs:35
  12:     0x56506e2467dd - std::panicking::rust_panic_with_hook::hb7ad5693188bdb00
                               at src/libstd/panicking.rs:476
  13:     0x56506e2462f0 - rust_begin_unwind
                               at src/libstd/panicking.rs:380
  14:     0x56506e263d61 - core::panicking::panic_fmt::hb1f3e14b86a3520c
                               at src/libcore/panicking.rs:85
  15:     0x56506e263cad - core::panicking::panic::hcdc9f0ba8d71d265
                               at src/libcore/panicking.rs:52
  16:     0x56506c854ef7 - core::option::Option<T>::unwrap::hd5806ded8e09ac44
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/macros/mod.rs:10
  17:     0x56506c80051e - sql::expr::ScalarExpr::bind_parameters::h0f609ab237d9bf8b
                               at src/sql/expr.rs:898
  18:     0x56506c85ea48 - sql::expr::RelationExpr::bind_parameters::{{closure}}::hb2c7003c7e01e016
                               at src/sql/expr.rs:640
  19:     0x56506c85d854 - sql::expr::RelationExpr::visit_mut::h3485fc8fc6869f0e
                               at src/sql/expr.rs:550
  20:     0x56506c85d934 - sql::expr::RelationExpr::visit_mut::{{closure}}::hb1afd35eceb82dbe
                               at src/sql/expr.rs:549
  21:     0x56506c85dfee - sql::expr::RelationExpr::visit1_mut::hcb99a5d65364e08b
                               at src/sql/expr.rs:560
  22:     0x56506c85d838 - sql::expr::RelationExpr::visit_mut::h3485fc8fc6869f0e
                               at src/sql/expr.rs:549
  23:     0x56506c85d934 - sql::expr::RelationExpr::visit_mut::{{closure}}::hb1afd35eceb82dbe
                               at src/sql/expr.rs:549
  24:     0x56506c85e021 - sql::expr::RelationExpr::visit1_mut::hcb99a5d65364e08b
                               at src/sql/expr.rs:563
  25:     0x56506c85d838 - sql::expr::RelationExpr::visit_mut::h3485fc8fc6869f0e
                               at src/sql/expr.rs:549
  26:     0x56506c7fcac6 - sql::expr::RelationExpr::bind_parameters::h9f0791b2344a96a6
                               at src/sql/expr.rs:636
  27:     0x56506c893e68 - sql::statement::handle_query::hd502a4c3c539ea0b
                               at src/sql/statement.rs:1450
  28:     0x56506c892e75 - sql::statement::handle_explain::h31d44a2b14138deb
                               at src/sql/statement.rs:1423
  29:     0x56506c87e7cb - sql::statement::handle_statement::h3aa96441eb891f9c
                               at src/sql/statement.rs:277
  30:     0x56506c9312ea - sql::plan::hb11101122d1d6cd2
                               at src/sql/lib.rs:209
  31:     0x56506a5c30d0 - coord::coord::Coordinator<C>::handle_statement::h29b8a3eb4d4a980c
                               at /home/jamie/materialize/src/coord/coord.rs:1858
  32:     0x56506a5b1abd - coord::coord::Coordinator<C>::serve_core::{{closure}}::hd574c03d3d9f5369
                               at /home/jamie/materialize/src/coord/coord.rs:488
  33:     0x56506a59af50 - core::result::Result<T,E>::and_then::h0e9f4d49242052bd
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/result.rs:721
  34:     0x56506a5aee78 - coord::coord::Coordinator<C>::serve_core::h3062249a67ff9a75
                               at /home/jamie/materialize/src/coord/coord.rs:487
  35:     0x56506a5c4691 - coord::coord::Coordinator<C>::serve::{{closure}}::h2f42cb8aee4c978f
                               at /home/jamie/materialize/src/coord/coord.rs:374
  36:     0x56506a6b48a9 - tokio::runtime::context::enter::h83d85e7fe6af1a4b
                               at /home/jamie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/context.rs:72
  37:     0x56506a6085e5 - tokio::runtime::handle::Handle::enter::he2c30ec4a611bd41
                               at /home/jamie/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/handle.rs:34
  38:     0x56506a5c460f - coord::coord::Coordinator<C>::serve::hdc82e524cdffc2d7
                               at /home/jamie/materialize/src/coord/coord.rs:374
  39:     0x56506a59f1a8 - sqllogictest::runner::State::start::{{closure}}::h75059c3e6f3ca500
                               at src/sqllogictest/src/runner.rs:401
  40:     0x56506a65c7c3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h20e793f08ec29755
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/sys_common/backtrace.rs:129
  41:     0x56506a5fa014 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::ha9d36da937820427
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/thread/mod.rs:475
  42:     0x56506a63f606 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hfa4dde28b5a8942c
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panic.rs:318
  43:     0x56506a6bd273 - std::panicking::try::do_call::hab0fffd2392eb2b3
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panicking.rs:305
  44:     0x56506e24b757 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  45:     0x56506a6bbcd8 - std::panicking::try::hafa7303daa85a5ad
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panicking.rs:281
  46:     0x56506a63f936 - std::panic::catch_unwind::h429c28bf8f268c33
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panic.rs:394
  47:     0x56506a5f9ded - std::thread::Builder::spawn_unchecked::{{closure}}::he1cdf8a7cc8b5c27
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/thread/mod.rs:474
  48:     0x56506a555074 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h7a0b6335f0ad939f
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/ops/function.rs:232
  49:     0x56506e235d5f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::he3e3bc9932f56404
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
  50:     0x56506e24a900 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h0d82364c11057a62
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
  51:     0x56506e24a900 - std::sys_common::thread::start_thread::h6cf2238254b521b3
                               at src/libstd/sys_common/thread.rs:13
  52:     0x56506e24a900 - std::sys::unix::thread::Thread::new::thread_start::he70a06005b4d03f8
                               at src/libstd/sys/unix/thread.rs:80
  53:     0x7fda06f5eef7 - start_thread
  54:     0x7fda06c7c22f - __GI___clone
  55:                0x0 - <unknown>
```

### PR DESCRIPTION
**Pull request by justinj**
The first commit just changes a file to allow rustfmt to process it and rustfmts it (thanks for the pointer @quodlibetor).

Fixes #2498.

Two halves to changing this: first, we have to pass through the param
types of a query to also be the types of its corresponding EXPLAIN, and
second, we have to make sure we bind any params when EXPLAINing.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/2589)

### CODE REVIEW

**Comment by jamii** [comment]
Can you add a test to explain.slt showing the output? 

I'm surprised that this is the only thing that needs to be fixed for parameters to work. Eg I think https://github.com/MaterializeInc/materialize/blob/master/src/coord/coord.rs#L1265-L1266 might cause crashes downstream if the optimizer asks for the type of something. 

Certainly type annotation should fail eg `EXPLAIN TYPED PLAN FOR SELECT $1`.

**Comment by jamii** [comment]
The easiest way to write those tests is to add a blank test like:

```
query T multiline 
EXPLAIN PLAN FOR SELECT $1
---

EOF
```

and then run:

```
cargo run --bin=sqllogictest ./test/sqllogictest/explain.slt --rewrite-results
```

and inspect the result.

**Comment by benesch** [comment]
SLT doesn’t support parameters, and it can’t easily, because what do you bind those parameters to? I recommend to Justin that he punt on fixing that problem and stick to Rust tests to limit the scope. I think it should be easy enough to write these tests in the Rust test framework for now.

**Comment by justinj** [comment]
In particular anything involving a placeholder in an SLT will crash and not give a graceful error because of #2583.

What is the problem you foresee with variants like `EXPLAIN TYPED PLAN FOR SELECT $1` ? As of this change it's rejected:
```
materialize=> EXPLAIN TYPED PLAN FOR SELECT $1;
ERROR:  there is no parameter $1
```
But in general it seems sane to me to allow placeholders in any EXPLAIN context as long as you require it to be substituted first, no?

**Comment by benesch** [comment]
> But in general it seems sane to me to allow placeholders in any EXPLAIN context as long as you require it to be substituted first, no?

I agree with this assessment! This is how Postgres works too; you can explain parameters if you bind them, and not otherwise.

**Comment by jamii** [comment]
Ok, if we're checking that they're all bound first then I guess it should be ok. What does the output look like?

**Comment by jamii** [comment]
Oh, wait, we still need to fix https://github.com/MaterializeInc/materialize/blob/master/src/coord/coord.rs#L1265-L1266. The param types are not actually getting passed through at the moment.

**Comment by justinj** [comment]
Pretty much the same, with placeholders substituted:
```
text: 'explain plan for select $1::int',
values: [1],
```
```
Optimized Plan
0 =
| Constant (1)
```
Since (I think) we figured out that the params getting passed through isn't actually a problem, do you have any lingering concerns @jamii?

**Comment by jamii** [comment]
Nope, all good.

**Comment by justinj** [comment]
Cool—thanks for the reviews!

**Pull request merged**
