### PR TITLE
Docs: webhook datagen plugin

### PR DESCRIPTION
**Pull request by bobbyiliev**
### Motivation

Adding a webhooks datagen plugin to the docs. This will allow us to create a variety of use cases by generating demo data and simulating real-world scenarios without asking the users to install anything.

This can also be reused in different pages with:

```
{{% plugins/webhooks-datagen %}}
```

Example:

webhook-datagen-docs

### CODE REVIEW

**Comment by chuck-alt-delete** [comment]
I didn't get this to work with [basic authentication](https://preview.materialize.com/materialize/22067/sql/create-source/webhook/#using-basic-authentication). 400 error, so I know I did something wrong. I tried a couple of things. Could you include a little more for how to get it running? It may also be useful to put the headers in the output box to make it easier to see what I did wrong?

**Comment by bobbyiliev** [comment]
> I didn't get this to work with [basic authentication](https://preview.materialize.com/materialize/22067/sql/create-source/webhook/#using-basic-authentication). 400 error, so I know I did something wrong.

My guess would be that your secret is not correct, can you share more the DDL statements that you've used?

**Comment by morsapaes** [comment]
Sorry for the delay, @bobbyiliev. This is on my pile for tonight!

**Review by morsapaes — APPROVED** [review]
Extracted the section from the reference docs and made it into an (unrefined) guide. It should be linked from the references docs, but it's alright to merge and leave that as a follow-up.

**Comment by morsapaes** [comment]
This is awesome, @bobbyiliev!

**Comment by chuck-alt-delete** [comment]
To get this to work, I needed to do this:
```sql
CREATE SECRET basic_hook_auth AS 'hello';
CREATE SOURCE webhook_with_basic_auth in cluster chuck
FROM WEBHOOK
    BODY FORMAT JSON
    CHECK (
      WITH (
        HEADERS,
        BODY AS request_body,
        SECRET basic_hook_auth
      )
      constant_time_eq(headers->'authorization'::text, basic_hook_auth)
    );
```
I couldn't use `->>` to extract the text from the header.
```
Error: operator does not exist: map[text=>text] ->> unknown 
```

**Review by chuck-alt-delete — APPROVED** [review]

**Pull request merged**
