### PR TITLE
Advance times in constant collections to as_of

### LINKED ISSUE #7472: panic, "Invalid data in source, saw retractions" error with aggregate, NOT IN
### What version of Materialize are you using?

```
materialized v0.8.4-dev (62ffac82b)
```

### What was the issue?

A query that is a join over two derived tables that contain aggregates returns a "Invalid data in source" if the WHERE predicate references columns from both derived tables.

### Is the issue reproducible? If so, please provide reproduction instructions.

```
CREATE TABLE t2 (f1 DOUBLE PRECISION, f2 DOUBLE PRECISION NOT NULL);
INSERT INTO t2 VALUES (1, 1);
INSERT INTO t2 VALUES (2, 2);
SELECT * FROM (SELECT COUNT (*) AS f1 FROM t2) a1, (SELECT MAX (f1) AS f2 FROM t2) a2 WHERE 1 NOT IN (a1.f1 + a2.f2);
ERROR:  Invalid data in source, saw retractions (1) for row that does not exist: [Int64(0), Float64(OrderedFloat(8.0))]
```

### PR DESCRIPTION
**Pull request by frankmcsherry**
This PR changes the rendering of `Constant` collections to advance times to the `as_of` boundary for the dataflow. Collections that are not so advanced cause computation to happen prior to any time that we will observe, and unfortunately cause errors in that regime when other parts of the dataflow imagine that they will not happen (as was the case in #7472, with optimized delta join loading).

Fixes #7472

### CODE REVIEW

**Review by asenac — APPROVED** [review]
I'm very interested in the debugging process you followed to find the problem was here :)

**Comment by frankmcsherry** [comment]
Merging now, but remind me and I'll jot some notes down. Not too complicated.

**Comment by frankmcsherry** [comment]
Ok, so short version is that there were a bunch of `println` statements and recompilation. Materialize is currently not great at debugging, because we are only able to stimulate the dataflow layer through SQL, which means that prompting specific computation is difficult (e.g. removing the chaff to see what is happening often results in a different query plan). I would like us to fix that.

The plans eventually looked good, but I started there based on the expressed confusion in the issue (adding more constraints results in a smaller plan). But, once that was in place, everything about the plan still looked like it should be "correct", in that `EXPLAIN PLAN` reported a plan that "should not" produce negative output results. The delta join was the likely suspect just based on it being different, and recently changed.

I captured its input stream and output stream, which pretty quickly pointed out the problem. The input "looked ok" and the output had a negative accumulation in it. At this point I leapt to what the problem was, either by luck or by some suspicion about compaction being the problem. I didn't come to a conclusion on whether the root problem was that constant collections are "not advanced to `as_of`" or that delta joins are insufficiently robust. I fixed the first thing, and view anyone who messes up the second thing probably a bug independently, so I'm happy leaving that around for the moment / until we think a bit more.

**Comment by philip-stoev** [comment]
There was a test for this ... now I will have to push it as a separate PR.

**Pull request merged**
