### PR TITLE
storage: make suspend and restart delay configurable, drop to 5s from 30s

### PR DESCRIPTION
**Pull request by pH14**
https://github.com/MaterializeInc/materialize/issues/26139 + https://github.com/MaterializeInc/cloud/issues/8965 have the full context, but the tl;dr is that sources can take a long time reconnect after momentary network blips. This means <1s of network downtime can turn into >60s of actual source/sink unavailability. One of the primary sources of downtime is the fixed 30s `SUSPEND_AND_RESTART_DELAY`.

This PR makes two small changes to this knob:
1. Makes it configurable
2. Drops the default to 5s, down from 30s

A more advanced solution would be using exponential backoff, but it's not quite clear to me how to make that work within the healthcheck operator. Tossing this up as a proposal, and will let a member of @MaterializeInc/storage determine whether it's sufficient 😄 

### Motivation

In part addresses https://github.com/MaterializeInc/materialize/issues/26139, though it'd be nice to move to exponential backoff eventually.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by guswynn — COMMENTED** [review]
Doing backoff IS quite a bit more annoying, you are right! I am personally fine with this, will get sign off with rest of the team

**Review by guswynn — APPROVED** [review]
@pH14 looks good!

The ci failure is because that test is checking against `mz_sink_statuses`, which cycles through running and stalled; instead it should check that `mz_sink_status_history` has `stalled` in its history

**Review by benesch — APPROVED** [review]

**Review by def- — APPROVED** [review]
I fixed the test and triggered a nightly: https://buildkite.com/materialize/nightly/builds/8488
Good for me if all is green.

**Comment by benesch** [comment]
Amazing, thank you!

**Comment by pH14** [comment]
Whoa thank you so much @def-! 🙇 🙇 🙇

**Pull request merged**
