### PR TITLE
design: Refactor storage controller state cleanup

### PR DESCRIPTION
**Pull request by sploiselle**
discusses solution for #8185

### Motivation

This PR is a design doc.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by aljoscha — COMMENTED** [review]
Early, shooting-from-the-hips comments:
 - I like it!
 - We should frame this more in terms of refactoring our protocol: we were previously trying to be tightly coupled/tightly correct (phrasing tbd, of course). This change moves us towards an "embrace the distributed nature of the thing", "live a little", "clean up early and let other systems deal with it gracefully" stance where the system is more resilient against individual, slow components (workers) holding back progress for the rest of the system.
 - Yes, it is about controller state (in this specific instance), but it's about the protocol itself and what all the intermediate components like `RehydratingStorageClient` and `PartitionedStorageState` do in response to "outgoing" and "incoming" messages.

Title bikeshed: Make storage controller/worker protocol more resilient to <foo>, where <foo> is hard to specify concisely.

**Review by petrosagg — COMMENTED** [review]
The proposal makes the claim that relying on responses from LLCs is in contradiction to ensuring liveness of the ULC. While it maybe be true that the *code* today has this problem I was not convinced that this is an inherent problem of the design. We should get to the bottom of that debate before proceeding because implementing this proposal comes with undesirable properties: 
* More panics that can disrupt other processes
* Lack of protocol assertions that have caught bugs numerous times in the past
* Requiring reasoning about emergent behavior

I claim that all these are avoidable. 

Sidenote, since words are important, I don't understand what "embracing the distributed nature" means or how to measure embracedness. At the end of the day we build a system and the system must have some desirable properties. Any system that manages to have the desirable properties has managed to "embrace" the distributed nature.

### ULC liveness

Let's first address the core claim of this proposal that waiting for LLC responses can lead to stalls in ULC. My understanding of the claim is that a stall can happen when a ULC waits for a response from an LLC to perform an action but the response never arrives. This can happen if the LLC crashes, goes into a network partition, etc.

When these events happen (crash, etc) *both* the global state *and* the local state (LLC responses) will never arrive, because the machine hosting the LLC could be dead.

In order to address this problem every ULC that is communicating with an LLC via an unreliable medium (e.g TCP) regularly performs health checks to detect failures (e.g TCP keepalive). When a failure is detected the ULC *disconnects* from the current LLC and attempts to reconnect, potentially to a different machine if the original one crashed.

Getting a new LLC up and running is **mandatory** for both the global state and the local responses to move forward.

I can now make my central claim: All protocols that rely on global state to perform an action have identical failure modes to protocols that rely on sending back a response. This is because relying on contacting the system holding the global state is as strong an assumption as relying on contacting any other system.

### `DroppedIds` is actually about capabilities

In this section I want to reframe the semantics `DroppedIds` which should motivate keeping it.

When a ULC connects to a LLC there is an initialization phase that informs the LLC about the current state of the ULC. This has the form of a series of commands followed by a punctuation (`InitializationComplete`). After the punctuation is received the LLC does a reconciliation step to make its local state match the received state.

A useful property of the protocol that we want to be asserting is being able to answer the question "what IDs is a given ULC/LLC allowed to talk about at any given moment?". This question should sound familiar because this is exactly the question a timely system asks (what timestamps is a given operator allowed to talk about at any given moment). This is a powerful property to be able to assert and has proven to uncover bugs.

So how do we think about capabilities in this ULC/LLC protocol? When a connection between a ULC and a LLC is established the ULC has the capability to talk about *any* id it wants. On the other hand LLC has no initial capabilities and therefore it can send *no responses*.

Just like a timely operator, when a ULC sends a message for a particular `GlobalId` to the LLC, the message carries a capability, which is what allows the LLC to start producing responses for that particular GlobalId.

Just like a timely operator, the LLC is retaining this capability so that it can keep sending responses to the ULC for as long as it wishes.

When a ULC sends the `AllowCompaction(id, {})` message to an LLC, the LLC can interpret that as the capability being dropped. From that point onward it can assert that no further commands with that particular `id` will be received from the ULC.

Similarly, when a LLC sends the `DroppedId(id)` response to a ULC, the ULC can interpret that as the capability being dropped. From that point onward it can assert that no further responses with that particular `id` will be received from the LLC.

The capability reasoning described above is useful **regardless** of whether or not a ULC waits for the capability to be dropped to perform an action. So I would strongly suggest that we keep this mechanism (and even consider making this an actual frontier that we track), to ensure correct implementation of the protocol.

**Comment by sploiselle** [comment]
Petros and I chatted about this proposal and his response to it; to make sure we were on the same
page, we both agreed to write up our takeaway. To avoid litigation and (mis)representation, I'll
focus more on the outcomes we arrived at rather than argument and counter-argument.

# Avoiding panics

Both my original proposal and Petros' response acknowledge that panics are disruptive just in their
occurrence (things have to restart, which is slow) but have a second-order effect, as well, in that
they inculcate an acceptance of panics such that they cease to produce as meaningful of a signal.

From this perspective, we discussed methods of avoiding of panics while still letting the controller
tackle the more immediate issue of tombstoning persist shards.

## Tombstoning persist shards from linked clusters

Petros and I determined that the source of the absence of `DroppedIds` messages is that the
coordinator drops the linked cluster before it has a chance to respond with `DroppedId`s.

We can resolve this issue by, whenever we drop a cluster, synthesizing `DroppedIds` messages for all
of the IDs they contain.

The work this requires is only that we provide some mechanism of correlating storage IDs to
collections (we currently have a method of correlating collection to storage IDs) and then sending
along `DroppedIds` messages when we drop the cluster.

This approach offers a solid compromise:
- The storage controller makes more decisions based only on its own state
- The protocol is not only still strictly enforced, but is more strictly enforced now that we can
  have this silent failure properly addressed.

# Future work

We could express these (and other) operations more rigorously as a frontier.

**Comment by aljoscha** [comment]
I might be missing some context because you discussed in person, but:

I _still_ think the design doc as currently written is the way to go (removing `DroppedIds`, or at least not blocking ULC work on it). The reasons are largely what Nikhil expressed [here](https://github.com/MaterializeInc/materialize/issues/8185#issuecomment-1540632833) and [here (internal slack)](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1683686894206209?thread_ts=1683655731.570189&cid=C01CFKM1QRF):
 - As soon as we have replicated storage instances, when does the ULC act? Is it when it receives the first `DroppedIds(x)` from a replica or when it receives them from all the replicas? If the former, then the ULC might as well do it when it sends out the `StorageCommand`/when it knows that `x` is being dropped. If the latter, I'd be concerned about slow replicas holding things back.
 - Synthesising `DroppedIds` messages sounds complicated.
 - The LLCs don't _have_ to panic, we could (or maybe should!) teach them to handle situations where they would panic more gracefully. We have most of the machinery for that, with internal restarts and the like.

((Side note: the stuff about first/all `DroppedIds` messages is equivalent to how it would behave with frontier tracking, I believe?))

**Comment by aljoscha** [comment]
Also, we shouldn't do any rash moves because we eventually have to unify the storage protocol stack with the compute protocol stack for cluster unification.

**Comment by petrosagg** [comment]
> As soon as we have replicated storage instances, when does the ULC act? I'd be concerned about slow replicas holding things back.

It would be when all of them finish and indeed that would manifest as delay to cleanup state (not unbounded delay though, a non-responsive replica will eventually get forcefully replaced, which would forcefully drop its capabilities). Given that there is no need to clean up the shard as fast as possible this is a small price to pay for the benefits of having strict checks of the protocol.

> Synthesising `DroppedIds` messages sounds complicated.

We already track the information needed to generate these. The `RehydrationTask` keeps maps of `GlobalId -> <resource>` for all the resources that the LLC it is connected to might send responses for. The synthesizing code is literally:

```rust
let dropped_ids: HashSet<_> = self.sources.keys().chain(self.sinks.keys()).collect();
```

> The LLCs don't have to panic, we could (or maybe should!) teach them to handle situations where they would panic more gracefully.

Yes, that would certainly be an improvement, however regardless of what the course of action is (panic or restart) doing so will dilute the signal we get from either panics or restarts. It's fine if it's unavoidable, but my argument is that it is avoidable.

> Also, we shouldn't do any rash moves because we eventually have to unify the storage protocol stack with the compute protocol stack for cluster unification.

I wouldn't worry about that, at least for this change. Synthesizing completion responses from replicas/instances that are being decommissioned is something that can be adapted to compute as well.

**Comment by petrosagg** [comment]
The description of how the intermediate clients work doesn't match how I imagine my proposal to work. Indeed the execution trace you described is undesirable but I don't think this is what would happen! Below is the modified trace:

DroppedIds World:

> * Say we have two replicas r1 and r2 for a cluster running a source
> * Now the source is dropped, controller still holds on to relevant state because it's waiting for DroppedIds.

I'm not sure what the relevant state is here but the only thing that the controller needs to hold on to is that it needs to finalize a particular shard. All the other state could be dropped immediately.

> * The AllowCompaction commands travel through rehydration to the clusterds. rehydration holds on to the CreateSource commands.

The rehydration client also immediately clears its local state of an ingestion on the receipt of `AllowCompaction({})` commands

> * Replica r1 drops the source and returns a DroppedIds, CreateSources command is not yet cleared because we wait for the other response.

As mentioned above, the state is already gone. What the rehydration client *does* hold on to is just the "capability" (read: a GlobalId in a HashMap) that tells it that a **particular** LLC might still send responses for.

> * Replica r2 is stalled, or split-brained, or something.
> * Now replica r1 fails and restarts. We rehydrate it, and send it the CreateSources command, along with the AllowCompaction command because we still have those. <- I content we shouldn't have to do this.

When replica `r1` fails we do not send it the dropped source again, the rehydration client knows that it is dropped (and has already dropped all the descriptions).

> * They eventually go back to all being responsive and we finally drop the CreateSources command from rehydration state and eventually from controller/coordinator state.

The only thing that happens when `r2` becomes responsive is that it will sends its `DroppedIds` response back which may cause the rehydration client to also send a `DroppedIds` response back to the controller.

Up until this point nothing blocks on this mechanism, it is there to ensure that clients follow the protocol.

----

Beyond the protocol checks, and as a separate argument, I also think the controller should wait for `DroppedIds` before finalizing a shard. The reason is that there is no real downside of waiting for the graceful thing to happen. Is it really that bad to hold on to a uuid for a bit longer? Is there another downside of waiting for `DroppedIds` (synthesized or not) before finalizing that I'm not seeing?

Another way to think about it is that the controller given an `Arc<Shard>` to a bunch of places and they must all drop their ref count (or we must consider them irrelevant (when an instance is dropped)) before attempting to drop (i.e finalize a shard).

> And the other world as less-coupled, but also simpler (in my head) because each part just needs to make sure that it's state is correct, and trust that other parts will also get there eventually.

We have proven multiple times that we are not smart enough to "just make sure state is correct", which is why I'm very bullish to add checks and balances as much as possible.

**Comment by aljoscha** [comment]
> The description of how the intermediate clients work doesn't match how I imagine my proposal to work. Indeed the execution trace you described is undesirable but I don't think this is what would happen! Below is the modified trace:

That's good! 😅 I was extrapolating from a naive extension of how things _currently_ work.

Re. "state": I was mostly handwaving/not being clear sorry! When I said "state" I meant "any work/cleanup that we could already be doing but are waiting until we hear responses back". For example, for the shard UUID for finalization, I'm not only thinking about holding on to that UUID, but all the work that we could already have done but are delaying.

I am _for_ doing all finalization, cleanup, whatnot as eagerly as possible (once we know that it has to happen). But I'm not _against_ keeping additional intermediate state in the protocol nodes if it helps detect protocol violations.

**Comment by petrosagg** [comment]
> I am for doing all finalization, cleanup, whatnot as eagerly as possible (once we know that it has to happen).

Sure, but there is no free lunch and you are giving something up by doing so. What you give up is the ability of replicas to assert that `CreateSource` requests are well formed and the shard is not prematurely finalized. Why is it worth trading this insurance against coding mistakes for a faster finalization which is an extremely cheap operation that nothing else depends on and can happen at any time?

**Comment by sploiselle** [comment]
> which is an extremely cheap operation that nothing else depends on and can happen at any time

I think the fact that we treat this as "it can happen at any time" is the problem with the current protocol: if we had added an upper bound on how long we will wait and panicked when it was exceeded, we would have agreed on a fix long ago.

And things _do_ depend on it––tombstoning persist shards. We just don't have anyone yelling at us if it doesn't happen.

It sounds like the apprehension with removing `DroppedIds` is two-fold:
- We would panic if a source were added and immediately dropped because the persist shard could be closed before the ingestion had a chance to take out a read hold on it
- We cannot be sure that the `CREATE SOURCE` was well formed enough to register the ingestion on the worker from a protocol level.

Both of these could be remediated with a `StorageResponse::InitializedIds` rather than `DroppedIds`. In this world, we could keep an in-memory map of the IDs we haven't heard back from yet and would not add their shards to the finalization queue until we did (or maybe after some timeout).

On reboot, we would forcibly finalize all shards, which would mean that panics would occur only in the world where a source was created, immediately dropped, and then the adapter rebooted more quickly than the ingestion could take out its read hold. This seems obscure enough that a panic is fine, or we could also teach ingestions to exit gracefully if their shards have been sealed.

**Pull request closed without merging**
