### PR TITLE
fix(mz) swallow ctrl-c when executing psql

### PR DESCRIPTION
**Pull request by sjwiesman**
### Motivation

 psql uses ctrl-c to cancel ongoing statements. Swallow the call to ctrl-c when executing psql; otherwise, it will terminate mz, stopping the shell.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

### CODE REVIEW

**Review by joacoc — APPROVED** [review]
LGTM!

**Comment by benesch** [comment]
Oh good catch, @sjwiesman! I think the right fix here is actually to call [`Command::exec`](https://doc.rust-lang.org/std/os/unix/process/trait.CommandExt.html#tymethod.exec) to replace the `mz` process image with `psql`, rather than spawning it as a subprocess. There may be other signal handling that `psql` is doing that we don't want `mz` to get in the way of.

**Comment by sjwiesman** [comment]
@benesch is there any concern that Command::exec is Unix only? I don't know what the intended supported target are for the cil.

**Comment by joacoc** [comment]
Just in case. Alternative ways I've explored but with no happy ending (might be missing a twist or more research):
* Forking the process and killing the parent (`mz`) to let the child (`psql`) live alone (It was an unsafe operation in rust, but I felt it was the way to go.)
* Handle the CTRLC signals and send them to the child process manually (adds complexity and can't differentiate a `SIGKILL` vs. a `SIGINT` for `psql`)
* Kill everything without even interrupting

Seth's swallow approach at least keeps the experience flowing and lets the user exit with `\q`. It is the best of all the methods I've experienced so far.

**Comment by sjwiesman** [comment]
@benesch I tried `Command::exec` locally and can verify it works as expected. What's your take on:


1. Only supporting unix
2. using some `cfg` magic to doing something else on windows
3. Finding another solution, either my existing PR or something else

**Comment by benesch** [comment]
Let’s do (1) for sure. I doubt this builds on Windows for at least a few
other reasons. We can cross that bridge in bulk when we decide Windows
support is important.

**Comment by sjwiesman** [comment]
Updated based on Nikhils feedback to use `Command::exec`

**Review by benesch — APPROVED** [review]

**Pull request merged**
