### PR TITLE
The nanos portion of a timestamp needs to come before the tz

### PR DESCRIPTION
**Pull request by quodlibetor**
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/3798)

### CODE REVIEW

**Comment by quodlibetor** [comment]
I didn't see any tests for this module, happy to add one, it's a bit hard to verify with testdrive since it just does string comparison.

**Comment by benesch** [comment]
I would think that testdrive attempting to parse the timestamptz output format would break?

**Comment by benesch** [comment]
Hmm, dates-times.td already has a bunch of tests that _don't_ break. I wonder what's going wrong.

**Comment by benesch** [comment]
Oh, right, because testdrive uses the binary format, which isn't broken. Something like this should do the trick:

```diff
diff --git a/test/testdrive/dates-times.td b/test/testdrive/dates-times.td
index 4f802280..92af95c3 100644
--- a/test/testdrive/dates-times.td
+++ b/test/testdrive/dates-times.td
@@ -105,3 +105,6 @@ $ kafka-ingest format=avro topic=data schema=${schema} timestamp=10
 
 > SELECT TIMESTAMPTZ '1989-06-01 9:10:10.410+700'
 "1989-06-01 02:10:10.410 UTC"
+
+> SELECT '1989-06-01 10:10:10.410+04:00'::timestamptz::text
+"1989-06-01 06:10:10.410+00"

```

**Comment by quodlibetor** [comment]
Does it parse, or just verify that they match? I'll dig in.

**Comment by quodlibetor** [comment]
To be clear, I posted my comment about adding tests concurrently with you asking for tests, I'm happy to look into it.

**Comment by quodlibetor** [comment]
Oh that's a different category of test than I was thinking of, but yeah, that would catch this, I'll add it.

**Comment by benesch** [comment]
Yeah, sorry, GH reviews is failing to keep up with us :D. The problem is that we don't have any tests of the timestamptz->text cast. Testdrive (or SLT) can handle that if you just force the timestamptz->text cast to happen explicitly in the query, rather than implicitly as part of the pgwire format (since testdrive uses the binary serialization, and SLT looks at Datums directly).

**Comment by quodlibetor** [comment]
Yeah I was thinking of adding a unit test directly in the module to make sure that it round-trips correctly, but this seems fine to prevent regressions.

**Comment by benesch** [comment]
Yeah if you do wanna add a unit test heads up that they are in https://github.com/MaterializeInc/materialize/blob/main/src/repr/tests/strconv.rs for this module (i.e., what Cargo would fall an “integration” test). This looks great though!

**Pull request merged**
