### PR TITLE
coord: add the Send bound only where needed

### PR DESCRIPTION
**Pull request by petrosagg**
### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

**Review by frankmcsherry — APPROVED** [review]
This is much shorter and more insightful than my PR. I think we'll probably land both if that is ok, so that `Controller` inherent methods can better return errors and such (which they couldn't do when their implementations were just pushing into a channel).

**Comment by petrosagg** [comment]
@frankmcsherry sounds good! 

> which they couldn't do when their implementations were just pushing into a channel)

I didn't fully follow this part

**Comment by frankmcsherry** [comment]
The implementations previously were default implementations for any `C: Client` that pushed the right command at the client. `Controller` implemented `Client`, which locked in the `StorageClient` and `ComputeClient` implementations, which wouldn't know what errors to return. This .. was gross and expedient at the time, and I'm happy to undo it in the other PR.

**Comment by frankmcsherry** [comment]
This is the relevant edit from the other PR, arguably:
https://github.com/MaterializeInc/materialize/pull/10697/files#diff-5a511bc21d5d74cf3b908c539399888a2cf6399999e9ed2f9b8178d4b2016f9dL488-L489

**Pull request merged**
