### PR TITLE
ci: Move log uploading to pre-exit hook

### PR DESCRIPTION
**Pull request by def-**
So that it can run after a timeout, seen for example in https://buildkite.com/materialize/nightly/builds/9848

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

**Comment by danhhz** [comment]
Cool! Giving this a go in https://buildkite.com/materialize/nightly/builds/9868

**Comment by def-** [comment]
Oops, forgot to say that I triggered it too: https://buildkite.com/materialize/nightly/builds/9866
Seems to work at least, there are logs now.

**Review by nrainer-materialize — APPROVED** [review]

**Comment by def-** [comment]
@danhhz The logs are pretty full of this:
```
platform-checks-mz_4-1              | cluster-u1-replica-u1-gen-3: 2024-10-08T21:53:11.234576Z  WARN librdkafka: error: TXNERR [thrd:kafka:9092/bootstrap]: Current transaction failed in state BeginCommit: ProduceRequest for sink-config3 [0] with 2 message(s) failed: Broker: Broker failed to validate record (broker 1 PID{Id:26,Epoch:111}, base seq 0): current transaction must be aborted (INVALID_RECORD)
```
But I'm not sure if it's actually related to the hang. Another one around the time of the hang:
```
platform-checks-mz_4-1              | environmentd: 2024-10-08T21:53:08.186675Z  WARN mz_storage_client::storage_collections: error during finalization of shard sc1e95236-9f10-4e95-b499-691d77515149: FinalizationError { since: Antichain { elements: [0] }, upper: Antichain { elements: [] } }
```
Locally all I could reproduce was out of memory, not the hanging query.

**Comment by danhhz** [comment]
Oh nice, you got a repro in that run! Mine didn't :)

It's definitely not either of those. Almost certainly this line, though I couldn't tell you _why_ the dataflow is stuck. Feels like I'll probably have to spend some time trying to find a shorter repro cycle so I can turn on the debug logging

```
platform-checks-mz_4-1              | cluster-u1-replica-u1-gen-3: 2024-10-08T21:53:10.335823Z  INFO mz_persist_client::internal::machine: snapshot s0850ead9-13a2-451a-be56-ab8e76292e0a as of [1728424388175] not yet available for v3401 upper [1728424171242]
```

**Pull request merged**
