### PR TITLE
devsite: document private items

### PR DESCRIPTION
**Pull request by mjibson**
I sometimes don't have my local mz buildable but need up-to-date docs,
including private items. Add the private items to the public site for
this case.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5752)

### CODE REVIEW

**Review by benesch — COMMENTED** [review]
I'm really on the fence about this. We historically haven't done this because some crates have a proper public interface that they document well, and then a bunch of really private stuff that isn't meant to be exposed or documented.

I agree that lots of crates have a worthless public interface (like, one method called `serve` or something) and all sorts of tricky bits inside. Ugh. :/ 

Why did this seem like so much less of a problem in Go?

**Comment by mjibson** [comment]
Why does it matter what shows up on the dev site?

**Comment by benesch** [comment]
Sorry, by "isn't meant to be exposed or documented", I mean that I often use the Rustdoc to make sure that the public API of a crate is correct, and isn't exposing things that are meant to be implementation details. Not in a "no one must see these!!" sense but in a "if this was exposed, one could violate invariants" sense.

I really wish Rustdoc made this toggleable via the presence of a flag, like Go does with `?m=all` https://golang.org/pkg/math/big/?m=all

**Comment by mjibson** [comment]
Ok, that's fine. I don't need this too much and if it already has a specific use, I'm fine leaving it as is.

**Comment by benesch** [comment]
Oh sorry, I should have said that I was sending you a new proposal. Whatchya think about #5754?

**Pull request closed without merging**
