### PR TITLE
testdrive: Disable expr cache in consistency check

### PR DESCRIPTION
**Pull request by jkosh44**
This commit disables the expression cache in testdrive during catalog
consistency checks. We were noticing elevated CPU usage in testdrive
after merging the expression cache during catalog consistency checks.
The expression cache is still used by environmentd during testdrive
tests unless it's disabled.

Additionally, this commit disables the expression cache when 0dt
upgrades are disabled. Certain upgrade tests that have 0dt disabled do
not increment the deploy generation between versions which breaks the
expression cache. 

Resolves #MaterializeInc/database-issues/issues/8759

### Motivation
This PR fixes a recognized bug.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [X] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [X] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

**Review by ParkMyCar — APPROVED** [review]

**Review by def- — APPROVED** [review]
Works for me, thanks for fixing!

**Comment by jkosh44** [comment]
@def- This test failure revealed a testing issue that I overlooked with the expression cache. Since the expression cache merged, it is not valid to run two different versions of Materialize with the same deployment generation, without first wiping the entire environment. The legacy upgrade tests do not increment the deployment generation when 0dt is disabled, which is now triggering this failure condition.

I tried incrementing the deploy generation when 0dt is disabled, but the test hung forever. I think a quick fix would be to disable the expression cache when 0dt is disabled. However, we should consider trying to always increment the deployment generation when upgrading the version in a test since that's what we do in production and there are various assumptions in the code that we do that.

**Comment by def-** [comment]
> I think a quick fix would be to disable the expression cache when 0dt is disabled

I'd be worried that we don't have expression cache + 0dt coverage in our testing then, so probably needs another fix long term.

> However, we should consider trying to always increment the deployment generation when upgrading the version in a test since that's what we do in production and there are various assumptions in the code that we do that.

I'll try to do that.

**Comment by jkosh44** [comment]
> > I think a quick fix would be to disable the expression cache when 0dt is disabled
>
> I'd be worried that we don't have expression cache + 0dt coverage in our testing then, so probably needs another fix long term.

Sorry I think my wording was a little confusing.

We DO have:

- expression cache + 0dt coverage
- No expression cache + legacy upgrade coverage

We DO NOT have:

- expression cache + legacy upgrade coverage
- No expression cache + 0dt coverage (we probably don't care about this)

**Pull request merged**
