### PR TITLE
demo: run billing demo on multipartition kafka topics in ci

### PR DESCRIPTION
**Pull request by ruchirK**
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/3017)

### CODE REVIEW

**Comment by ruchirK** [comment]
@benesch I think our dependency tracking might be a little bit flawed here. I changed the mzcompose.yml for the streaming-demo CI test in the first commit, and I would expect that to cause that test to run but it didn't. What do you think?

I'll leave the first commit untouched in case you want to peek at it

**Comment by benesch** [comment]
I'm going to push up a change to fix that issue you noticed!

**Comment by benesch** [comment]
Never mind. Fixing this is much harder than I expected.

**Comment by benesch** [comment]
The fix is in!

**Pull request merged**
