### PR TITLE
ci: Allow retrying each job

### PR DESCRIPTION
**Pull request by def-**
Sets the default value for manual retries to allow retrying successful jobs

As suggested in https://materializeinc.slack.com/archives/C01CFKM1QRF/p1696064390657009?thread_ts=1695990466.832369&cid=C01CFKM1QRF

https://buildkite.com/docs/pipelines/command-step#retry-attributes-manual-retry-attributes https://buildkite.com/docs/pipelines/defining-steps#step-defaults

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by philip-stoev — APPROVED** [review]
This feature existed? Thank you!

**Review by nrainer-materialize — APPROVED** [review]
Nice!

**Comment by def-** [comment]
Apparently I misunderstood and you can't change the default for an entire pipeline. Is it ok if I add this manually to each step or should we make all pipelines into templates and do this in the template conversion python script?

I prefer the latter since 3 lines per step is quite spammy, but don't want to go through the effort and find out everyone else prefers having it manual.

**Comment by philip-stoev** [comment]
Yes it is about time we convert all pipelines into templates. Every now and then a situation comes up where everything being a template would have helped.

If you want to get this over with quickly, I would go with the single-line solution and open up a good-first-issue follow-up ticket to use templates everywhere. The reason is that I expect some back-and-forth with the templates will be needed -- it is both just YAML and yet we are using by now a bazillion Buildkite features.

**Comment by guswynn** [comment]
thank you for this!!

**Pull request merged**
