### PR TITLE
mzcompose: one last big refactor

### PR DESCRIPTION
**Pull request by benesch**
@philip-stoev I promise this is the last overarching mzcompose refactor for a while. I've copied the important commit messages below. The overarching theme is making some minor-seeming naming/hierarchy tweaks that I think contribute to making the concepts in mzcompose easier to understand.

----

**mzcompose: merge Workflow into Composition**

Merge the Workflow object into the Composition object in mzcompose.
Workflow functions now receive a `c: Composition` as their first
argument rather than a `w: Workflow`.

This is a minor change but an important one, I think. Previously the
conceptual model was "a workflow is a function that receives a workflow
as an input". That's weird! In the new model, the workflow *is* the
function, and it gets provided a composition to manipulate. This is
much cleaner, I think.

It also means you can't accidentally pass the wrong workflow object to
another workflow. In the previous API it was possible to write code like
this:

    def workflow_one(w: Workflow):
        workflow_two(w)

    def workflow_two(w: Workflow):
        print(w.name)

Here, `./mzcompose run two` would print "two" but `./mzcompose run one`
would print "one". The new model avoids this:

    def workflow_one(c: Composition):
        workflow_two(c)

    def workflow_two(c: Composition):
        # No incorrect workflow name to refer to!

Argument parsing is also simplified. Workflows now optionally receive a
premade WorkflowArgumentParser as input:

    def workflow_args(c: Composition, parser: WorkflowArgumentParser) -> None:
        parser.add_argument("--foo")
        args = parser.parse_args()
        ...

This is a bit smoother in the simple case. When one workflow wants to
call another workflow with arguments, it's still easy. You can't call
the workflow directly, but you can invoke `c.workflow`:

    def workflow_specific(c: Composition) -> None:
       c.workflow("general", ["--foo"])

    def workflow_general(c: Composition, parser: WorkflowArgumentParser) -> None:
        parser.add_argument("--foo")
        args = parser.parse_args()
        ...

There are no known behavior changes in this commit.

----

**mzcompose: use SERVICES as the magic services item**

Hopefully this makes it a bit more clear that SERVICES is special. Plus
SERVICES is effectively a constant (nothing happens if you modify it),
so this is more in line with Python style.

----

**mzcompose: rename mzworkflows.py to mzcompose.py**

Since the mzworkflows.py file can contain service definitions now, I
think it's clearer to call it "mzcompose.py"--i.e., the Python version
of what could also go in mzcompose.yml.

----

**mzcompose: decrease verbosity of composition method**

Whittle the methods on the Composition object down to their exact Docker
Compose equivalents. This makes the method calls more understandable to
folks who are familiar Docker Compose. Avoiding keyword arguments and
using *splat parameters when possible cuts down on the visual noise. All
together, I think this vastly improves the readability of your average
mzcompose.py.

### Motivation

   * This PR refactors existing code.

### Tips for reviewer

Once again it should be much less stressful to go commit by commit!

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/9924)

### CODE REVIEW

**Comment by benesch** [comment]
Oops! I forgot to push up the last commit which uses standard Docker Compose method names for everything. I retriggered the nightlies on the new commit.

**Comment by philip-stoev** [comment]
@benesch there are residual mentions of `start_services`, possibly others, in the .md file.

**Comment by benesch** [comment]
> @benesch there are residual mentions of `start_services`, possibly others, in the .md file.

Thanks, fixed. This time for sure. 🤞🏽

**Comment by benesch** [comment]
I pushed up a fix for that weird `cargo test` failure`, since this PR seems to make it so CI (properly) observes that failure.

Here's the latest nightlies run: https://buildkite.com/materialize/nightlies/builds/572#b04e256e-71a1-4683-96d4-4f30f5dc3d2d. It doesn't include the aforementioned `cargo test` fix but I think that's fine.

**Comment by benesch** [comment]
Another nightly run: https://buildkite.com/materialize/nightlies/builds/574

**Comment by benesch** [comment]
Ok, all looks good now!

**Comment by philip-stoev** [comment]
Once you push this I am going to try to add the feature benchmark to the CI

**Comment by benesch** [comment]
Does it have your approval? If so merge away!

**Review by philip-stoev — APPROVED** [review]

**Comment by philip-stoev** [comment]
Yes sorry I forgot to click Approve the day before

**Pull request merged**
