### PR TITLE
Property-test row packing

### PR DESCRIPTION
**Pull request by antifuchs**
This PR introduces a new property test for packing arbitrary combinations of (recursively nested) `Datum`s into `Row`s and unpacking them again.

It also adds some meta-tests where we ensure that the functionality used by the property tester does in fact yield correctly property-testable values.

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5911)

### CODE REVIEW

**Comment by benesch** [comment]
Ooh! cc @mjibson who has wanted something like this in the past.

**Comment by mjibson** [comment]
This is great! Random datum generation is useful. My experience is that you also need a hard coded list of interesting datums that exercise edge cases. For example: https://github.com/cockroachdb/cockroach/blob/7f4c5508e19eb18ea9f43ab6d585036adcac087d/pkg/sql/rowenc/testutils.go#L439

**Comment by antifuchs** [comment]
Yes! Extremely into having a set of "interesting" ones that we use to exercise particular code segments with (there's a lot to be said about how property testing will never fully replace "normal testing" (:)

The best practice advised by proptest is to add a "regressions" file that includes the seed&values that result in regressions, but I'm pretty sure we can also make a file that includes some values that we define.

**Comment by antifuchs** [comment]
OK, I believe this can test the entirety of the Datum enum (using the row packer to generate owned data for the Array, List and Map case - which we also use property testing to validate the correctness of (-:).

Believe this is now ready for review!

**Comment by frankmcsherry** [comment]
Unassigning myself, owing to no background in testing. Please lmk if there is a specific ask.

**Comment by antifuchs** [comment]
Ah! I was hoping to catch your expertise re. the row representation, but looking at the row.rs commit history, @benesch will be just as much of an expert (:

**Review by benesch — APPROVED** [review]
Seems great! I too am not overly familiar with property testing, so perhaps @philip-stoev could offer you more useful feedback. But this seems fine to merge!

**Comment by philip-stoev** [comment]
@antifuchs Any and all testing on all levels is much welcome! I will try to add more nested structures at our SQL-level randomized testing as well. I will also read up on property testing.

**Comment by antifuchs** [comment]
That's great news! I recommend starting with the [proptest book](https://altsysrq.github.io/proptest-book/), which gives a very good overview of what the crate that I ended up using can and can't do (or can do, with restrictions - like recursive data structures)! (:

**Pull request merged**
