### PR TITLE
parallel-workload: Ignore result size error

### PR DESCRIPTION
**Pull request by def-**
Even in DML workloads it can happen, see https://buildkite.com/materialize/nightly/builds/7961#018fe071-6fd9-476c-9e57-e153435bd12d

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by nrainer-materialize** [comment]
What is the result such a DML statement gets back?

**Review by nrainer-materialize — APPROVED** [review]

**Comment by def-** [comment]
You're right, the actual result should just be the number of rows manipulated. My thought was that internally we have a data structure that grows too big and would be discarded later. I'll try to repro on a smaller example.

**Comment by def-** [comment]
I opened https://github.com/MaterializeInc/materialize/issues/27428

**Comment by nrainer-materialize** [comment]
> I opened #27428

Thanks for following-up!

**Pull request merged**
