### PR TITLE
Rename logging source

### LINKED ISSUE #2186: Logging source misnamed
The logging source `mz_dataflow_operator_addresses` is misnamed, in that it contains addresses for both operators and for channels.
```
materialize=> select distinct id from  mz_dataflow_operators where id < 170 order by id;
 id  
-----
 167
 168
(2 rows)

materialize=> select distinct id from  mz_dataflow_operator_addresses where id < 170 order by id;
 id  
-----
 167
 168
 169
(3 rows)
```
Some of the identifiers, above `169`, correspond to channels instead
```
materialize=> select distinct id from  mz_dataflow_channels where id < 170 order by id;
 id  
-----
 169
(1 row)
```

No clue what the impact of naming is on the catalog, and whether it is easy to just swap the name around without harming other things.

### PR DESCRIPTION
**Pull request by bkirwi**
### Motivation

Fixes #2186.

In the linked issue, there was some discussion of whether the logging source should be instead two sources, one for operators and one for channels. Arguments include:
- It's a little weird to store those two things together; they're not usually considered conceptually similar, aside from the fact that both types have addresses.
- It's less work to rename than to split.
- I was curious if any existing queries against this table suffered from operators and channels being mashed together -- eg. if they needed to join against the operator table to filter the channels out -- but I couldn't find any examples of places where the status quo made things more difficult, and a few queries seem to include data from both. (Though I haven't yet chased down what the results of those queries are used for; it's conceivable that it's unintentional, but I'm not aware of any related bugs.)
- I confirmed that operators and channels will never have conflicting ids - they allocate them from the same source. So the status quo is safe.

Nothing decisive, so let's go with the smaller change.

### Tips for reviewer

The first commit is a simple search-and-replace; the rest make a few manual fixes to improve the style and fix up some tests. This PR should be squashed on merge.

### Checklist
- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-protobuf` label.
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - Rename the operator/channel address system table from `mz_dataflow_operator_addresses` to `mz_dataflow_addresses`.

### CODE REVIEW

**Comment by bkirwi** [comment]
Alright, it appears after fixing the table ordering and merging to get rid of a flaky test, the last error is in the smoke test:

```
cluster-materialized-1  | thread 'main' panicked at 'invalid persisted create sql: CREATE VIEW "mz_catalog"."mz_records_per_dataflow" AS SELECT "mz_records_per_dataflow_operator"."dataflow_id" AS "id", "mz_dataflow_names"."name", "mz_records_per_dataflow_operator"."worker", "pg_catalog"."sum"("mz_records_per_dataflow_operator"."records") AS "records" FROM [s296 AS "mz_catalog"."mz_records_per_dataflow_operator"], [s365 AS "mz_catalog"."mz_dataflow_names"] WHERE "mz_records_per_dataflow_operator"."dataflow_id" = "mz_dataflow_names"."id" AND "mz_records_per_dataflow_operator"."worker" = "mz_dataflow_names"."worker" GROUP BY "mz_records_per_dataflow_operator"."dataflow_id", "mz_dataflow_names"."name", "mz_records_per_dataflow_operator"."worker"', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-06136b3f9e749f899-1/materialize/tests/src/adapter/src/catalog.rs:1539:37
```

This is _not_ a table I've touched, but it does indirectly depend on a table I've touched. Something seems to be going awry in the automated builtins migration tooling, though I'm not sure what yet.

**Comment by bkirwi** [comment]
Okay, @jkosh44 and I have determined that this is unlikely to go through without a lot more work. My understanding of the situation:
- A core problem: the existing logging source can be (and is) referenced by other views and things, and those references are persisted in the cluster state. So we can't just rename things without doing some migration to the existing stuff.
- There are three different types of migrations in the existing code:
    1. [`migrate::migrate`](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/catalog/migrate.rs) which lets you rewrite statements one at a time. Currently unused, but has been heavily used in the past.
    2. [`storage::migrate`](https://github.com/MaterializeInc/materialize/blob/e198bf0be193a30158ee57a7667bbd1ace31ad9d/src/adapter/src/catalog/storage.rs#L65-L339) gives you whole-catalog access, but you don't have access to much other metadata. The initial setup of the standard schemas etc. happens here.
    3. [`Catalog.open`](https://github.com/MaterializeInc/materialize/blob/e198bf0be193a30158ee57a7667bbd1ace31ad9d/src/adapter/src/catalog.rs#L1947-L1953) has logic for migrating the builtins.
- Naively, iii. sounds exactly like what we want... but it explicitly does not support migrating logging builtins automatically. We had hopes that we could explicitly do a migration in i. or ii.; but i. does not actually allow migrating builtins (only user-defined types) and ii. does not easily have access to the information it needs (regenerating fingerprints, etc.) to do things correctly.
- The "right thing" is probably to extend the builtin migrations to handle sources like this... but this is apparently a significant task, and dwarfs the relatively marginal value of the feature here.

I'm going to close this one out for now. I plan to add an issue for rounding out the builtin migration feature; once that's done, we could consider picking this up again.

**Comment by bkirwi** [comment]
Alright, reviving this! Not because we've fixed any of the migration stuff, but because we've decided we're willing to accept some minor breaking changes in the next couple weeks.

There's only one other test failure, and it appears to be a symptom of #14218. Will follow up here once that issue's sorted.

**Review by jkosh44 — APPROVED** [review]
LGTM

**Pull request merged**
