### PR TITLE
sql: Require Kafka connection for Kafka sources

### LINKED ISSUE #13374: [epic] sql+storage: `CONNECTION`s supported + required
Folks agreed we should do this work, so turning this into a tracking ticket.

## Systems
- [x] Kafka (#11504) 
- [x] Confluent schema registry  (#11504)
- [x] Postgres (#13552)
- [x] SSH (#14293)
- [x] AWS, i.e. S3 + Kinesis (#13665)
- [x] PubNub (#14294)

## Requires connection
-  [ ] Kafka
    - [ ] Sources (#14295)
    - [x] Sinks (#14214)
- [x] Confluent schema registry
  - [x] Sources (#14296)
  - [x] Sinks (#14297)
- [x] Postgres sources
- [x] SSH sources (#14293)
- [x] AWS, i.e. S3 + Kinesis sources  (#13665)
- [x] PubNub sources (#14294)

<hr />

### Feature request

For background on `CONNECTION`, see [the design
doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20220404_connectors.md).

We have the option to require references to `CONNECTION` objects to connect to
external systems, e.g. Kafka, Postgres, which means removing the ability to
express the connection inline.

## Ad hoc syntax

```sql
> CREATE MATERIALIZED SOURCE data
  FROM KAFKA BROKER 'kafka:9092' TOPIC 'testdrive-data-${testdrive.seed}'
  WITH (
      security_protocol = 'SSL',
      ssl_key_pem = SECRET ssl_key_kafka,
      ssl_key_password = SECRET ssl_key_password_kafka,
      ssl_certificate_pem = '${arg.materialized-kafka-crt}',
      ssl_ca_pem = '${arg.ca-crt}'
  )
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
  WITH (
      ssl_key_pem = SECRET ssl_key_csr,
      ssl_key_password = SECRET ssl_key_password_csr,
      ssl_certificate_pem = '${arg.materialized-schema-registry-crt}',
      ssl_ca_pem = '${arg.ca-crt}',
      username = "materialize",
      password = SECRET password_csr
  )
  ENVELOPE DEBEZIUM
```

## Connector syntax

```sql

> CREATE CONNECTION kafka_ssl
  FOR KAFKA
    BROKER 'kafka:9092',
    SSL KEY = SECRET ssl_key_kafka,
    SSL KEY PASSWORD = SECRET ssl_key_password_kafka,
    SSL CERTIFICATE = '${arg.materialized-kafka-crt}',
    SSL CERTIFICATE AUTHORITY = '${arg.ca-crt}';

> CREATE CONNECTION csr_ssl
  FOR CONFLUENT SCHEMA REGISTRY
    URL '${testdrive.schema-registry-url}',
    SSL KEY = SECRET ssl_key_csr,
    SSL KEY PASSWORD = SECRET ssl_key_password_csr,
    SSL CERTIFICATE = '${arg.materialized-kafka-crt}',
    SSL CERTIFICATE AUTHORITY = '${arg.ca-crt}'
    USERNAME = 'materialize',
    PASSWORD = SECRET password_csr;

> CREATE MATERIALIZED SOURCE connector_source
  FROM KAFKA CONNECTION kafka_ssl
    TOPIC 'testdrive-data-${testdrive.seed}'
    FORMAT AVRO
  USING CONFLUENT SCHEMA REGISTRY CONNECTION csr_ssl
  ENVELOPE DEBEZIUM
```

You can also see this in situ in the
[`kafka-ssl`](https://github.com/MaterializeInc/materialize/blob/main/test/kafka-ssl/smoketest.td)
test.

Concretely, the proposal is to disallow the "Ad hoc" syntax entirely, and _only_
support the "Connector syntax." If we do not accept or implement this proposal,
we will accept _either_ syntax.

# Context

- We are in the process of turning all `WITH` options to rely on enum-based names,
rather than arbitrary strings, as a means of providing more consistent code
paths in the planner. This means breaking lots of backward compatibility with
e.g. source definitions, so now is a great time/the only time to make this
shift.
- The current process for describing options for sources is complex, e.g. all of
the security options are placed alongside _other_ options, despite the fact that
they're most likely the same for all connections to the broker. Removing the
number of valid `WITH` options in any spot simplifies the UX of creating
sources.
- The SQL + Storage + DevEx teams have all agreed on the approach for
`CONNECTION` objects. However, if we permit using either `CONNECTION` or ad hoc
option definition, we will provide two means to accomplish the same goal. It
seems ideal to provide only one means of accomplishing this task.
- Removing the ability to define connection parameters in the _ad hoc_ options
will let us simplify code paths, e.g. we will not need to add
`TryFrom<GeneralSourceOptions> for SourceConnectionOptions`.

The downside to this proposal is the same as its upside: reduced flexibility in
creating resources.

# Work entailed

After creating `CONNECTION` objects for all external systems (e.g. Postgres,
AWS) (work that we are doing anyway), removing the inline definition code paths,
and amending tests to only use `CONNECTION`.

### LINKED ISSUE #14295: sql: require Kafka `CONNECTION` for Kafka sources
### Feature request

_No response_

### PR DESCRIPTION
**Pull request by jkosh44**
This commit prevents defining a Kafka connection inline when creating a Kafka source. Instead a Kafka connection object must be created first, and then referenced in the Kafka source creation.

Fixes #14295 
Fixes #13374

### Motivation

This PR adds a known-desirable feature.

### Tips For Reviewer
- The majority of the changes are to tests
- There is some changes to documentation, some of which already looked pretty out of date. So please at least ctrl-f for `.md` files and take a look at those.
- I did not update the create kafka source docs. It looks like it was already wrong, and I'm not sure how to properly update it. I think that should go in a follow up PR.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-protobuf` label.
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - Requires a Kafka connection object to create a Kafka source

### CODE REVIEW

**Review by guswynn — COMMENTED** [review]
code looks good, now its just test failures!

**Comment by jkosh44** [comment]
@philip-stoev I don't expect you to go though through every single test if you don't want to, but please let me know if I missed a whole class of tests.

**Comment by jkosh44** [comment]
This also seems to have somehow broken the nightly test for "Instance size limits" (https://buildkite.com/materialize/nightlies/builds/1180#018361b5-d85f-4c76-a915-04cab62486be) by breaking the CREATE CLUSTER command syntax. I'm honestly not sure how that happened.

**Comment by jkosh44** [comment]
> This also seems to have somehow broken the nightly test for "Instance size limits" (https://buildkite.com/materialize/nightlies/builds/1180#018361b5-d85f-4c76-a915-04cab62486be) by breaking the CREATE CLUSTER command syntax. I'm honestly not sure how that happened.

Never mind, looks like this is broken on `main` too. So this PR is good to go!

**Review by benesch — APPROVED** [review]

**Pull request merged**
