### PR TITLE
test/lang/csharp: test against Npgsql v8.0.3

### PR DESCRIPTION
**Pull request by benesch**
🚨 Not expected to succeed yet. v8.0.3 is not yet released. 🚨 

NpgSQL v7 and v8 don't presently work against Materialize. The forthcoming v8.0.3 is expected to restore compatibility.

### Motivation

   * This PR adds a test for a new version of Npgsql.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - n/a

### CODE REVIEW

**Comment by benesch** [comment]
@MaterializeInc/testing this should have triggered the C# tests but didn't! I wonder if we've got the inputs for that workflow misconfigured.

**Comment by nrainer-materialize** [comment]
> @MaterializeInc/testing this should have triggered the C# tests but didn't! I wonder if we've got the inputs for that workflow misconfigured.

We had moved them to Nightly. I will trigger them manually.

**Comment by benesch** [comment]
Ah! Didn’t realize. Thanks!

**Comment by benesch** [comment]
Abandoned.

**Pull request closed without merging**
