### PR TITLE
persist: enable pushdown feature flags in CI

### PR DESCRIPTION
**Pull request by danhhz**
Both of these flags are "additive" in the sense that the "off" state does nothing, as opposed to executing some other codepath. This gets us performance coverage of the new code (e.g. in feature benchmarks). Combined with the "audit" feature, which we already enabled previously in CI, we automatically get correctness coverage of both the stats and interpret paths for anything already covered by existing CI tests.

This is no substitute, of course, for dedicated test coverage, but we don't lose anything by CI not exercising the "off" case and we gain a lot. Concretely, this is exactly how we found the bug fixed in #19128.

Touches #12684

### Motivation

  * This PR adds a known-desirable feature.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by danhhz** [comment]
I'll also kick off a nightly on this once build+lint pass

**Comment by bkirwi** [comment]
Mild preference for enabling the system var explicitly in tests, a la https://github.com/MaterializeInc/materialize/blob/10cd73647efa5855c9c0c631e6a9852b5fff487f/misc/python/materialize/mzcompose/services.py#L97-L101.

(Preference because having fewer ways to enable the feature means that I need to check fewer things to know whether audit mode is on or not. Mild because that cat's sort of already out of the bag even for vanilla LD...)

**Review by bkirwi — APPROVED** [review]
But in any case I am glad to have the extra testing!

**Comment by danhhz** [comment]
does that `mzcompose/services.py` apply to _all_ the same places that soft_assert does or only some of them?

**Comment by danhhz** [comment]
attempting to answer my own question

```
ci/test/cargo-test/mzcompose.py:58:        MZ_SOFT_ASSERTIONS="1",
misc/python/materialize/mzcompose/services.py:75:            "MZ_SOFT_ASSERTIONS=1",
misc/python/materialize/mzcompose/services.py:214:            "MZ_SOFT_ASSERTIONS=1",
misc/python/materialize/mzcompose/services.py:771:                "MZ_SOFT_ASSERTIONS=1",
misc/python/materialize/mzcompose/services.py:876:            "MZ_SOFT_ASSERTIONS=1",
...
test/cluster/mzcompose.py:537:                "MZ_SOFT_ASSERTIONS=0",
test/cluster/mzcompose.py:828:                "MZ_SOFT_ASSERTIONS=0",
```

seems fine:
- the two `MZ_SOFT_ASSERTIONS=0` are one-off tests that don't seem to be particularly relevant
- two of those services.py ones are envd and clusterd, which would be covered by the bootstrap var
- another services.py is the testdrive binary, which doesn't run persist code

would be a bummer:
- the cargo-test would not be covered by bootstrap
- another of the services.py is sqllogictests, which wouldn't be covered by bootstrap (probably interesting to get those covered, given they're focused on logic)

so, unfortunately, I think the two would not yield equivalent test coverage

**Comment by bkirwi** [comment]
AFAICT it should be possible to add the `MZ_BOOTSTRAP_SYSTEM_PARAMETER` environment var to both of the bummer locations? (But if that's hard or you otherwise prefer not to, not a big deal.)

**Comment by danhhz** [comment]
doesn't that increase the number of places you'd have to check whether the flag is on even more than this does?

**Comment by danhhz** [comment]
stepping back, a bigger concern I have is that things like https://materializeinc.slack.com/archives/C0246GEHL8N/p1683835189645309 worry me that we'll _think_ we've turned the flag on in ci, but really somehow we haven't. whereas this is, at least to me, far more obvious that we're always turning the flag on in ci

**Comment by bkirwi** [comment]
> doesn't that increase the number of places you'd have to check whether the flag is on even more than this does?

To be explicit about what kind of check I had in mind: right now if I want to check whether audit mode is enabled or not I can `SHOW persist_stats_audit_percent;`. After this change that doesn't work!

**Comment by danhhz** [comment]
aha! okay, I understand now. yeah, I think that's a very good point and probably worth the complexity I was worried about above

i'm think there's a chance that updating the PR will cancel my nightly run (likely not, but it certainly does for the tests run), so I'll hold off on pushing that change until after the nightlies has finished

**Comment by danhhz** [comment]
okay done! switched to your suggestion. I'll run nightlies and such again, but we'll have to wait for whatever bug found in https://github.com/MaterializeInc/materialize/pull/19335 gets fixed

**Comment by danhhz** [comment]
Replaced by #19324

**Pull request closed without merging**
