### PR TITLE
peek: move LIR optimization back on the main thread

### PR DESCRIPTION
**Pull request by aalexandrov**
We have to do this because #24130 started happening again after we moved LIR optimizatio back on a separate thread in #24569.

### Motivation

  * This PR fixes a previously unreported bug.

See [this comment](https://github.com/MaterializeInc/materialize/issues/24130#issuecomment-1909672173).

### Tips for reviewers

@def-: It's strange that the nightly run for #24569 didn't catch this. Maybe some repeated runs of the problematic stages that manifest this is needed before we merge the revert in order to ensure that this is actually solving the issue.
@teskje: please stamp this so we can merge later today if everything looks good.
@mjibson: we might need some assistance from the @MaterializeInc/adapter team in order to figure out what is going wrong here.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by teskje — APPROVED** [review]
LGTM, provided that CI says this avoids the `SinceViolation`s.

**Review by def- — APPROVED** [review]
Thanks for acting so quickly!

**Comment by def-** [comment]
Nightly looks ok so far, the failures are unrelated.

**Comment by aalexandrov** [comment]
Restarting one of the Testdrive runs (it seems that it ran on a faulty worker).

**Comment by teskje** [comment]
High confidence that this PR fixes at least one instance of the `SinceViolation` issue. I can reproduce the panic on main but not with this change.

To reproduce, apply this diff:

```diff
diff --git a/src/adapter/src/coord/sequencer/inner/peek.rs b/src/adapter/src/coord/sequencer/inner/peek.rs
index 9a31a9a73b..8bbd703209 100644
--- a/src/adapter/src/coord/sequencer/inner/peek.rs
+++ b/src/adapter/src/coord/sequencer/inner/peek.rs
@@ -630,6 +630,7 @@ impl Coordinator {
         mz_ore::task::spawn_blocking(
             || "optimize peek (LIR)",
             move || {
+                std::thread::sleep_ms(10000);
                 let pipeline =
                     || -> Result<(optimize::peek::GlobalLirPlan, UsedIndexes), AdapterError> {
                         // In `explain_~` contexts, set the trace-derived dispatch
```

Then start envd and run these statements:

```
CREATE TABLE a (a int);
SELECT * FROM a;
```

This will hang for 10 seconds before envd will crash with a `SinceViolation` panic.

**Comment by mjibson** [comment]
Idea: maybe the validity check needs to be taught about another thing.

**Comment by mjibson** [comment]
Was able to repro with the above. Looking.

**Comment by mjibson** [comment]
This was happening because before the optimize LIR step we did a timestamp determination (used during the mir->lir phase off thread) but didn't acquire read holds, so during the off thread time the since could advance.

**Comment by mjibson** [comment]
Update: I no longer certain that this is related to read holds because the read holds we acquired and added to txn_holds before the optimize_lir step.

**Comment by mjibson** [comment]
Full fix attached. Problem was single statement txns and as of statements were not acquiring read holds as an optimization. That optimization is no longer valid in the optimize lir code because it does off thread work.

**Comment by teskje** [comment]
[Related discussion in Slack.](https://materializeinc.slack.com/archives/C02FWJ94HME/p1706183894578429)

**Comment by jkosh44** [comment]
> Full fix attached. Problem was single statement txns and as of statements were not acquiring read holds as an optimization. That optimization is no longer valid in the optimize lir code because it does off thread work.

I think you might have forgotten to attach the fix? @ParkMyCar  also has a PR for this, https://github.com/MaterializeInc/materialize/pull/24701, so you may want to chat with him about the approach.

**Comment by mjibson** [comment]
The full fix is the last commit in https://github.com/MaterializeInc/materialize/pull/24710 which gets read holds always.

**Pull request merged**
