### PR TITLE
orchestrator: in Process Orchestrator, disambiguate processes by deploy generation

### PR DESCRIPTION
**Pull request by aljoscha**
Touches https://github.com/MaterializeInc/materialize/issues/27406.

This is one of the things that we need in order to locally test read-only mode and eventually zero-downtime upgrades. After this change, you cannot run multiple deploy generations of `bin/environmentd` in parallel, but it is one of the necessary steps. We are now failing because of fencing and other things having to do with access to shared resources, like writing to tables and whatnot.

The change makes it so that multiple deploy generations of a single (local) environment can peacefully co-exist. Each one can spin up their cluster processes and their scratch directories (if any) don't clash.

~Crucially, this only changes the Process Orchestrator, which is used for local testing. The Kubernetes Orchestrator which is used in production "suffers" from the same problem and we eventually have to address that as well.~ This change now applies to both the process and Kubernetes orchestrators.

~Also, this does not touch the code around cleanup of orphaned processes. The Controller does this on bootstrap, but it only works with the Kubernetes Orchestrator, because each deployment generation has a global view of processes (pods, rather) and can deprovision them. The Process Orchestrator is only aware of the processes that it's specific instance has spawned, so cannot learn about or clean up orphaned processes.~

~NOTE: The Process Orchestrator _could_ probably be taught to know about all processes, by looking at the metadata/run dir, where we keep pids of live processes. It's just that we currently don't do that.~ The process orchestrator has been taught to do this.

**Usage:**

Start the first deploy generation:

```sh
$ bin/environmentd 
```

Then start second one in parallel:

```sh
bin/environmentd -- --deploy-generation=1 -- --sql-listen-addr 127.0.0.1:6975 --http-listen-addr 127.0.0.1:6976 --internal-sql-listen-addr 127.0.0.1:6977 --internal-http-listen-addr 127.0.0.1:6978 --internal-persist-pubsub-listen-addr 127.0.0.1:6979 --persist-pubsub-url "http://localhost:6979" --balancer-sql-listen-addr 127.0.0.1:6980 --balancer-http-listen-addr 127.0.0.1:6981
```

Though, as mentioned above, we cannot currently run multiple deployment generations in parallel, because of things that we have yet to address.

### Motivation

  * This PR adds a known-desirable feature.

### Tips for reviewer

Go commit by commit.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - n/a

### CODE REVIEW

**Comment by aljoscha** [comment]
@ParkMyCar I think you can hold any reviews, @benesch might be futzing with this and AFAIK will also review it.

**Review by benesch — APPROVED** [review]

**Comment by nrainer-materialize** [comment]
Nightly: https://buildkite.com/materialize/nightly/builds/8122

**Comment by nrainer-materialize** [comment]
Fixed two cloudtests with https://github.com/MaterializeInc/materialize/pull/27559/commits/a387344cabce2c45fc137a8b8dea77640ec98690.

**Comment by benesch** [comment]
Rebased and triggered a new nightly. Expecting mostly green! https://buildkite.com/materialize/nightly/builds/8138

**Comment by benesch** [comment]
Nightly is essentially green. I broke one nightly test (platform checks upgrade) in another PR by removing the storage stash URL, and this one only breaks one more nightly test (upsert compaction). Since I've already broken one nightly test today, breaking another doesn't make the situation materially worse. So, merging this, and I'll put up another PR shortly to fix both nightly failures.

**Comment by benesch** [comment]
Nightly fix PR: https://github.com/MaterializeInc/materialize/pull/27723

**Pull request merged**
