### PR TITLE
dataflow-types: partition StorageCommand::Insert by hash of data

### LINKED ISSUE #11071: performance regression: UPDATE statements now ~50% slower against user tables
### What version of Materialize are you using?

3f7aedf33e91b8497c2f1622a4333da15a37de10

### How did you install Materialize?

Docker image

### What was the issue?

The `Update` feature benchmark is consistently reporting a performance regression:

```
Update                    \|       1.606 \|       1.096 \|    !!YES!!    \| 46.5 pct   slower  |  
```

git bisect reports the following revision:

```
3f7aedf33e91b8497c2f1622a4333da15a37de10 is the first bad commit
commit 3f7aedf33e91b8497c2f1622a4333da15a37de10
Merge: 588a9e720 253c608b1
Author: Nikhil Benesch <nikhil.benesch@gmail.com>
Date:   Sat Mar 5 19:50:34 2022 -0500

    Merge pull request #10883 from benesch/table-unspecial
    
    coord,dataflow: remove special cases for table indexes

```

The feature benchmark reports the **fastest** time the workload could execute in a given revision. There is also the problem that repeated executions of the same workload get progressively slower and slower:

```
Measurement: 1.6061623096466064
Measurement: 1.9834446907043457
Measurement: 2.016334056854248
Measurement: 2.423788547515869
Measurement: 2.916515827178955
...
Measurement: 9.298703670501709
Measurement: 9.861934185028076
Measurement: 8.153981685638428
Measurement: 8.687877178192139
Measurement: 8.837841987609863
Measurement: 9.046060562133789
Measurement: 9.261691808700562
```

What is special about the `Update` benchmark workload is that individual measurements operate on the same table without dropping it between measurements. The performance numbers indicate that some cruft is being accumulated in the process, e.g. no compaction is happening or something else long those lines.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by benesch**
Previously the inserts were partitioned by their position in the
command. This impeded compaction, because it was likely that the
retraction of a piece of data would land on a different worker than the
the original presentation of that data landed on.

This glitch was responsible for the ever-increasing time to `UPDATE` a
nonmaterialized table.

Fix #11071.

### Motivation

  * This PR fixes a recognized bug.

### Testing

- [?] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - N/A

### CODE REVIEW

**Review by antiguru — APPROVED** [review]
Thanks, I think this is fine for the insert command, but let's keep this problem in mind. In the Timely world, each operator is responsible to expressing how data needs to be partitioned, and here we have a deviation from that concept.

**Review by frankmcsherry — APPROVED** [review]
Ahhhh....

**Comment by philip-stoev** [comment]
@benesch I am pushing a test for this in your branch, please stand by.

**Review by philip-stoev — APPROVED** [review]
The progressive degradation in performance is gone and has been replaced by a perfectly regular see-saw pattern :-):

```
Measurement: 1.0535364151000977
Measurement: 1.2505369186401367
Measurement: 1.0614831447601318
Measurement: 1.2541069984436035
Measurement: 1.0959887504577637
Measurement: 1.2647860050201416
Measurement: 1.0790431499481201
Measurement: 1.2651989459991455
Measurement: 1.0835185050964355
Measurement: 1.2488768100738525
Measurement: 1.082984209060669
Measurement: 1.254788875579834
Measurement: 1.085153579711914
Measurement: 1.2448115348815918
Measurement: 1.0856339931488037
Measurement: 1.2502164840698242
Measurement: 1.0845377445220947
Measurement: 1.2577614784240723
Measurement: 1.0577623844146729
Measurement: 1.2511868476867676
Measurement: 1.0837812423706055
Measurement: 1.240565538406372
Measurement: 1.074781894683838
Measurement: 1.2493267059326172
Measurement: 1.0676851272583008
Measurement: 1.256789207458496
Measurement: 1.079594373703003
Measurement: 1.254709005355835
Measurement: 1.0783882141113281
Measurement: 1.2457389831542969
Measurement: 1.0811269283294678
Measurement: 1.2488253116607666
Measurement: 1.0740303993225098
Measurement: 1.2457807064056396
Measurement: 1.0650291442871094
Measurement: 1.2469465732574463
Measurement: 1.0584683418273926
Measurement: 1.2382948398590088
```

Even though this prevents the feature benchmark from converging quickly on a definitive performance number, I would say it is OK in the grand scheme of things -- there could be any number of reasons for things to end up in resonance like that.

**Comment by frankmcsherry** [comment]
If it helps to unpick the issue: what is happening behind the scenes is that the updates accumulate until their number has doubled, at which point they are reduced back down through compaction. I could imagine the number of updates is such that the compaction happens at a regular frequency that is lower than the measurement frequency. If you dial around the number of distinct records or the number of updates per round, it might smooth out.

Also something we should be comfortable with in our measurements though (non-stationary behavior that remains below some fixed bound).

**Comment by benesch** [comment]
> If it helps to unpick the issue: what is happening behind the scenes is that the updates accumulate until their number has doubled, at which point they are reduced back down through compaction. I could imagine the number of updates is such that the compaction happens at a regular frequency that is lower than the measurement frequency. If you dial around the number of distinct records or the number of updates per round, it might smooth out.

This is exactly right, as verified by a `println!` I was keeping an eye on before and after I fixed this.

**Pull request merged**
