### PR TITLE
doc/user: fix list indentation

### PR DESCRIPTION
**Pull request by benesch**
The docs list styling was resulting in indentation that did not properly indent the contents of each list item. This commit fixes the issue largely by removing all the special cases. This may cause regression in some of those special cases, but I can't quite tell what they were attempting to accomplish, and this fix certainly makes the basic cases more legible.

### Motivation

   * This PR refactors existing code.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - n/a

### CODE REVIEW

**Comment by benesch** [comment]
Pushed up a fix for the incorrectly bold italic text too.

**Comment by morsapaes** [comment]
Still seems a little cursed:

Screenshot 2023-03-09 at 19 21 57

The old docs template didn't have this issue, so we might just want to lift whatever was used there?

**Comment by benesch** [comment]
Does anyone know of a good doubly or triply nested list that I can use to validate the new styles?

**Comment by ruf-io** [comment]
@morsapaes what is off with that image? not seeing it

**Comment by benesch** [comment]
> The old docs template didn't have this issue, so we might just want to lift whatever was used there?

The problem is that we've been working around the bug in the new template by _not_ indenting successive paragraphs in bulleted lists.

Easiest to explain with a diff:

```diff
diff --git a/doc/user/content/releases/v0.39.md b/doc/user/content/releases/v0.39.md
index a7064af1ff..30bfb7ab95 100644
--- a/doc/user/content/releases/v0.39.md
+++ b/doc/user/content/releases/v0.39.md
@@ -31,10 +31,10 @@ patch: 3
   ORDER BY o.name DESC, ro.name ASC;
   ```
 
-It's important to note that these tables are part of an unstable interface of
-Materialize (`mz_internal`), which means that their values may change at any
-time, and you should not rely on them for tasks like capacity planning for
-the time being.
+  It's important to note that these tables are part of an unstable interface of
+  Materialize (`mz_internal`), which means that their values may change at any
+  time, and you should not rely on them for tasks like capacity planning for
+  the time being.
 
 * Add an `mz_version` system configuration parameter, which reports the
   Materialize version information. The value of this parameter is the same as
```

**Comment by morsapaes** [comment]
Thanks, @benesch! I can validate and adjust cursed alignments from here. The release notes have a bunch of cases that need indents!

**Comment by morsapaes** [comment]
@ruf-io, I posted the comment and image before realizing what Nikhil just wrote about our workaround to make things look less bd.

**Comment by benesch** [comment]
Great! Is there anyone else who should approve this?

**Review by ruf-io — APPROVED** [review]
Tested some cases and LGTM!

[image](https://user-images.githubusercontent.com/11527560/224124201-8805829f-22fe-44e7-adb6-5a5226f308cf.png)

**Review by morsapaes — APPROVED** [review]

**Review by parkerhendo — APPROVED** [review]
Seems like we're good to go! I'll tackle some other typography issues in a separate PR.

**Pull request merged**
