### PR TITLE
Avoid null skew in outer join lowering

### PR DESCRIPTION
**Pull request by ggevay**
This adds an `IS NOT NULL` filter in the left (right) join lowering before the left (right) input is fed into the semi-join. This doesn't change the result of the plan, because the right (left) input of this join was already filtered for nulls [here](https://github.com/MaterializeInc/materialize/blob/d7c1be4d2e86b2c1739b14eb2530882aa8711cb3/src/sql/src/plan/lowering.rs#L2033). This has two benefits:
- We avoid the possibility of many nulls in the left (right) input skewing the join's arrangement. (This is not just a theoretical concern, it's actually happening at https://github.com/MaterializeInc/accounts/issues/3 right now.)
- When the left (right) input's key doesn't have a NOT NULL constraint, this saves us one arrangement on the left (right) input, because of a new CSE opportunity. See for example the change in `joins.slt`.

The above change alone was introducing various performance regressions due to lost CSE opportunities. However, the second commit eliminates all these performance regressions. It does a minor change in `MirScalarExpr::reduce`: we eliminate `IS NULL` when the input type is known to be non-nullable and the input expression can't error. The non-erroring is important, otherwise we had a correctness regression in `privilege_grants.slt`, because an `error_if_null(...) IS NULL` was eliminated. In addition to eliminating all the performance regressions that the `IS NOT NULL` filter caused, this also eliminated lots of IS NOT NULL filters that were on top of joins. Additionally, it dramatically simplified some plans (see e.g. `ldbc_bi.slt` query 04, 15, 19), which is probably due to `RedundantJoin` having an easier time due to less filters standing in the way.

### Motivation

  * This PR optimizes performance:
    * https://github.com/MaterializeInc/materialize/issues/28026
    * Eliminates lots of IS NOT NULL filters from the top of joins.
    * Makes it easier for other optimizations (`RedundantJoin`) to operate.

### Tips for reviewer

Some of the plan changes are easier to view with whitespace changes not shown, because the disappearance of a Filters causes big de-indentations.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by frankmcsherry — CHANGES_REQUESTED** [review]
I think we need to be clearer about what is going on than just packing some new filters in place. I think there's a pretty easy explanation, in terms of `x = y` implying `NOT IS NULL x`, which turns in to a predicate that can be pushed down. But just appending some predicates doesn't explain this.

**Comment by ggevay** [comment]
@frankmcsherry , I've done the refactoring and added comments. This is in 03369c28323317349c758ddca2a18048f4a0f79f

Also, I've added a feature flag for the outer join lowering change, as a safeguard. (enabled by default) 2ded4b345342518ca277e6fe6d6e2f61c5c449a4

The Nightly failures in Parallel workload and Language tests are unrelated, see [here](https://materializeinc.slack.com/archives/C01LKF361MZ/p1720031210678229).

This is ready for a final review before the release cut. Could you please check?

**Review by frankmcsherry — APPROVED** [review]
I'm going to be honest, I can't really tell what is going on in the PR. The outer join lowering seems fine, there seem to be plan changes that result from changes to `MirScalarExpr::reduce` that do not result from `nonnullable.rs`, even though they appear to do similar things except that `nonnullable.rs` doesn't check about potentially erroring expressions (is it incorrect?).

We can merge this, but I don't think all the work has been done yet.

**Comment by ggevay** [comment]
Hmm, interesting, `NonNullable` looks like it should do these things. I'll look into this tomorrow why it was not doing it. There is probably some bug in it that makes it much less effective than it could be.

And the `could_error` check will probably need to be added to `NonNullable` once we fix `NonNullable`.

**Comment by ggevay** [comment]
I can see the following reasons for why `NonNullable` was missing some of these (there might be more reasons):
- It's only run near the beginning of the `logical_optimizer`. The new code runs at many more moments. For example, `JoinImplementation` (in the `physical_optimizer`) lifts some filters up above joins, and it is only at this point when it becomes visible that these filters can be eliminated. (Also note that they shouldn't be eliminated when they are under the join, to avoid null skew.)
- `NonNullable` handles only naked column references in `IS NULL`, while the new code also handles more complicated expressions. (Btw. we often decompose complex expressions in `IS NULL` into several `IS NULL` expressions (see `decompose_is_null`), which should solve this in theory. But this decomposition might not be happening in some cases, e.g., when the functions's `introduces_nulls` and `propagates_nulls` is not right.)

**Comment by frankmcsherry** [comment]
> And the could_error check will probably need to be added to NonNullable once we fix NonNullable.

This seems like a glitch, fwiw. If an expression cannot be null but can error, given the absence of specified evaluation order outside of `CASE`, why is it wrong to remove `error_if_null(...) IS NULL`? Is it rather just bad SQL we shouldn't have written, and should fix that instead?

**Pull request merged**
