### PR TITLE
Optimization: Remove FoldConstant from physical planning.

### PR DESCRIPTION
**Pull request by wangandi**
### Motivation

Alternate solution to #9930. 

Andrés mentioned that he did not understand why `FoldConstant` even exists in physical planning, so I removed `FoldConstant` from physical planning to see what happened. Turns out that `FoldConstant` exists to:
1) counteract the effect of `LiteralLifting`. So I just removed `LiteralLifting` from physical planning as well. 
2) reduce Map expressions. On main, a map `[RecordCreate( ...), RecordGet(<previous_column>)]` may be combined into `RecordGet(RecordCreate(...)...)`  in `CanonicalizeMFP`, but simplifying the `RecordGet(RecordCreate(...)...)` does not happen until `FoldConstant`. So I added code to simplify Map expressions into CanonicalizeMFP. 

It looks like `FoldConstant` and `LiteralLifting` can be removed together from physical planning without any negative plan effects. Some destroyed arrangements come back. A project changes position relative to a map but that has no impact on the LIR. 

### Tips for reviewer

Try hiding whitespace.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/9968)

### CODE REVIEW

**Comment by philip-stoev** [comment]
Item No #1. A "dummy" , whatever that means, was being pushed towards the source and therefore a distinct operator is now a reduce:

```
# 2022-01-10T11:23:32 Simplified query:  EXPLAIN  SELECT  FROM (  SELECT MIN ( a2 .f2  )  ,  AVG ( a1 .f2  ) f2  FROM t2 a1  JOIN t2 a2  ON  NOT  TRUE  ORDER  BY  TRUE  ) a1  JOIN (  SELECT  FROM t2  )  ON  TRUE  WHERE  9  IN (  SELECT agg1  FROM (  SELECT a1  , MAX (  7  ) agg1  )  )  OR  8  > f2   ;
# 2022-01-10T11:23:32 Result set diff:
# 2022-01-10T11:23:32 --- /tmp//randgen931106-1641810212-server0.dump	2022-01-10 11:23:32.533921532 +0100
# 2022-01-10T11:23:32 +++ /tmp//randgen931106-1641810212-server1.dump	2022-01-10 11:23:32.533921532 +0100
# 2022-01-10T11:23:32 @@ -8,43 +8,36 @@
# 2022-01-10T11:23:32  
# 2022-01-10T11:23:32  %2 = Let l2 =
# 2022-01-10T11:23:32  | Get %1 (l1)
# 2022-01-10T11:23:32 -| Map 7
# 2022-01-10T11:23:32 -| Reduce group=()
# 2022-01-10T11:23:32 -| | agg dummy(dummy)
# 2022-01-10T11:23:32 +| Distinct group=()
...
```

The plan in this branch has 2 more steps than in the prior commit, but this part of the diff seems to be the only one of substance.

**Comment by philip-stoev** [comment]
Item No 2 . In this branch, a Map that could be evaluating an expensive function is missing, so the expensive function is evaluated  as many times as it is needed to answer the query, which can be a lot in the case of large IN lists:

```
echo " EXPLAIN  SELECT  FROM t1  WHERE  EXISTS (  SELECT  FROM t1 as A1  JOIN t1  as A2  USING ( f2  , f1  )  WHERE POW(f1, f2)   IN (   1, 2, 3, 4, 5, 6 , 7, 8, 9, 10  )  )   ;
" | ~/diff.sh
EXPLAIN SELECT
  FROM t1
 WHERE EXISTS (
        SELECT
          FROM t1 as A1
          JOIN t1 as A2 USING (f2 , f1)
         WHERE POW(f1, f2) IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
       ) ;

--- 6875.out	2022-01-10 11:29:23.619894071 +0100
+++ 16875.out	2022-01-10 11:29:23.663894819 +0100
@@ -12,7 +12,8 @@
 | |   delta %0 %0.(#1, #0)
 | |   delta %0 %0.(#1, #0)
 | Filter !(isnull(#0))
-| Filter ((((((((((2 = power(#0, #1)) || (1 = power(#0, #1))) || (3 = power(#0, #1))) || (4 = power(#0, #1))) || (5 = power(#0, #1))) || (6 = power(#0, #1))) || (7 = power(#0, #1))) || (8 = power(#0, #1))) || (9 = power(#0, #1))) || (10 = power(#0, #1)))
+| Map power(#0, #1)
+| Filter ((((((((((#4 = 2) || (#4 = 1)) || (#4 = 3)) || (#4 = 4)) || (#4 = 5)) || (#4 = 6)) || (#4 = 7)) || (#4 = 8)) || (#4 = 9)) || (#4 = 10))
 | Project ()
 | Distinct group=()
 | ArrangeBy ()
```

**Comment by philip-stoev** [comment]
Item No 3. Maybe the same as No 1. In the query below (apologies for the complexity of it), the constant was pushed so far up that it arrived in a Reduce operator. Would that be a problem as the value now needs to be present in all the data structures that Reduce builds, rather than being tacked on after the reduction is calculated?

```
pstoev@Ubuntu-2004-focal-64-minimal:~/randgen$ echo " EXPLAIN  SELECT a1 .f1  ,  TRUE  , (  TRUE  )  TRUE  , MAX ( a1 .f2  ) agg1  FROM (  SELECT COUNT ( a1 .f1  )  AS f1  , COUNT (  5  )  AS f2  FROM t2  AS a1  RIGHT  JOIN t1 a2  USING ( f1  )  WHERE a1 .f1  IN (  SELECT agg1  FROM (  SELECT ( COUNT ( a2 .f2  )  )  AS agg1  ,  TRUE  FROM (  SELECT  TRUE  ,  TRUE f2  ) a2  )  LIMIT  0  )  OR f1  IS  NULL  ) a1  JOIN t2 a2  ON  TRUE  GROUP  BY  1  ,  2  ,  3   ;
" | ~/diff.sh
EXPLAIN SELECT a1 .f1 ,
       TRUE , (TRUE) TRUE ,
       MAX (a1 .f2) agg1
  FROM (
        SELECT COUNT (a1 .f1) AS f1 ,
               COUNT (5) AS f2
          FROM t2 AS a1
         RIGHT  JOIN t1 a2 USING (f1)
         WHERE a1 .f1 IN (
                SELECT agg1
                  FROM (
                        SELECT (COUNT (a2 .f2)) AS agg1 ,
                               TRUE
                          FROM (
                                SELECT TRUE ,
                                       TRUE f2
                               ) a2
                       )
                 LIMIT 0
               )
            OR f1 IS NULL
       ) a1
  JOIN t2 a2
    ON TRUE
 GROUP  BY 1 ,
          2 ,
          3 ;

--- 6875.out	2022-01-10 11:42:57.779490345 +0100
+++ 16875.out	2022-01-10 11:42:57.831491399 +0100
@@ -33,8 +33,8 @@
 %7 =
 | Join %5 %6
 | | implementation = Differential %6 %5.()
-| Reduce group=(0) <- Here 
+| Reduce group=()
 | | agg max(#1)
-| Map true
-| Project (#0, #2, #2, #1)
+| Map 0, true
+| Project (#1, #2, #2, #0)
```

**Comment by philip-stoev** [comment]
Item No 4. Not sure how big of a deal it is, but the Map in this query is applied to each branch of the Union separately, rather than to the result of the Union . The map value `null` seems to come from the fact that the subquery contains an impossible predicate

```
EXPLAIN SELECT CASE (SELECT o_orderkey ORDER  BY TRUE LIMIT 1)
            WHEN 1                                     THEN (SELECT o_orderkey WHERE EXISTS (SELECT WHERE l_extendedprice <> o_totalprice AND l_extendedprice = o_totalprice ) )
             END
  FROM lineitem
  JOIN orders
    ON TRUE ;

--- 6875.out	2022-01-10 11:53:28.467651898 +0100
+++ 16875.out	2022-01-10 11:53:28.507652643 +0100
@@ -46,15 +46,14 @@
 %11 =
 | Get %10 (l3)
 | Filter (#0 = 1)
-| Map null
-| Project (#1)
+| Project ()
 
 %12 =
 | Get %10 (l3)
 | Filter (isnull(#0) || (false = (#0 = 1)))
-| Map null
-| Project (#1)
+| Project ()
 
 %13 =
 | Union %11 %12
+| Map null
```

**Review by philip-stoev — APPROVED** [review]
I am able to see this code in action. Most of the plan differences that are listed as Items appear to be inconsequential so they can be disregarded if there is a larger expected benefit to this PR.

The only one that I am a bit concerned about is that an expensive expression that was previously evaluated once may now be evaluated multiple times.

There were no crashes or wrong results.

**Comment by wangandi** [comment]
> Item No # 1. A "dummy" , whatever that means, was being pushed towards the source and therefore a distinct operator is now a reduce.

I cannot reproduce the plan in the comment. What I get on main and this PR is:
```
 Optimized Plan 
----------------
 %0 =          +
 | Constant    +
```

Is there a particular schema or indexes that I need to get the plan in the comment? Is another case where the plan now has a dummy?

**Comment by philip-stoev** [comment]
Here is the schema for Item 1 . I think the thing is that I am using `DOUBLE PRECISION` columns, apologies for not mentioning that. Why double columns prevent the creation of the Constant plan I do not know.


```
CREATE TABLE t1 (f1 DOUBLE PRECISION, f2 DOUBLE PRECISION);
CREATE TABLE t2 (f1 DOUBLE PRECISION, f2 DOUBLE PRECISION);
```

**Comment by wangandi** [comment]
Closed because we do not want to remove FoldConstants from physical planning until we have some sort of invariant that guarantees physical planning will not need constant folding. See #8888.

Map simplification issue discovered as part of this experiment has been written up as part of #10130.

**Pull request closed without merging**
