### PR TITLE
frontegg-auth: refactor out a more general Client

### PR DESCRIPTION
**Pull request by mjibson**
In preparation for integration into mz.

This is only code movement, no functionality change.

### Motivation

   * This PR refactors existing code.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - n/a

### CODE REVIEW

**Comment by mjibson** [comment]
I don't understand why we need this change, because my read of the code is that mz has needs that don't overlap at all with envd's needs, so having a common client they share doesn't benefit either.

**Comment by jkosh44** [comment]
> I don't understand why we need this change, because my read of the code is that mz has needs that don't overlap at all with envd's needs, so having a common client they share doesn't benefit either.

What prompted this PR then?

**Comment by mjibson** [comment]
> What prompted this PR then?

This description of the needed refactor work: https://materializeinc.slack.com/archives/C04HRFA6DDE/p1679378949100089

**Comment by mjibson** [comment]
Reworked a tiny bit to have a new function that's just for envd. It lives in the frontegg create so that those defaults can be used by everything else, avoiding some code duplication, but leading to some awkward naming. I think this is an acceptable tradeoff between "envd must not be changed accidentally" and "make the defaults good".

**Review by parker-timmerman — APPROVED** [review]
Assuming this PR's aim to is achieve this:

> The existing `FronteggAuthentication` struct should store a `FronteggClient` rather than an `reqwest::Client`, and then `mz` will be able to use the `FronteggClient` too.

Then it looks good to me!

**Review by benesch — APPROVED** [review]
This looks great. Thanks, @mjibson!

**Review by joacoc — APPROVED** [review]
LGTM.

Should the entire file `src/frontegg-auth/src/auth.rs` have the same warning as in `src/frontegg-auth/src/client.rs`?

E.g. The function `continuously_validate_access_token` has the logic to refresh a token, which may also be useful for other packages. One could feel tempted to modify that function to reuse the logic but modifying it may impact in some possible way to `environmentd`.

**Comment by mjibson** [comment]
I think it's ok as is. Those functions are mostly logic using config values from a struct that envd is already setting itself.

**Pull request merged**
