### PR TITLE
Add checkbox about incompatible command-line args to PR template

### PR DESCRIPTION
**Pull request by umanwizard**
This should make it less likely to need fixes like https://github.com/MaterializeInc/cloud/pull/4959 at the last minute.

### CODE REVIEW

**Comment by benesch** [comment]
FYI I opened https://github.com/MaterializeInc/cloud/pull/4939/commits/d065dcc71614776119b915a4df03ea25704cbb4b to handle this, but the release window was moved forward unexpectedly. 

I don’t think this is quite the right fix, though. Would rather we say you need to open a PR against the cloud repo that accounts for the change, version gated, and mark it as a release blocker. Just telling the cloud team in Slack is too likely to introduce human error into the process.

**Comment by umanwizard** [comment]
The problem is that not everybody who works on the DB is set up to work on cloud (in fact, I'd bet most aren't), so I don't think we can require them to send PRs to the cloud repo.

**Comment by benesch** [comment]
Sure we can. It would be great for more people to get basic exposure to the
cloud repository. They can tag in a cloud engineer for help, but I think
anyone making a change to Materialize’s command line arguments should be
responsible for preparing the PR to account for those changes in the cloud
repository.

**Comment by umanwizard** [comment]
Closing this as it seems more discussion is needed.

Right now, there is a pretty major ramp-up cost (and in my personal experience, lots of difficulty and frustration) involved in working on the cloud repo. I think that needs to be solved before we can consider making it an expectation for all engineers.

**Comment by benesch** [comment]
I think it is the other way around. The way we decrease the ramp up cost on the cloud repository is by having more people ramp up on the cloud repository.

**Comment by jpepin** [comment]
Keeping a healthy and up-to-date personal stack can be challenging even for full time cloud engineers right now (though we can hope and expect that that won't always be the case).

A simple interim solution would be for the database engineer to follow the example of previous cloud PRs for arg changes and do  local testing (but not necessarily full testing in a personal stack), then tag in a cloud engineer to review the PR and test on their own stack.

**Comment by umanwizard** [comment]
You can probably also get away with not having a full personal stack (e.g., by running things in `kind` with `cloudtest`, or with `bin/serve`). But it's still non-trivial IMO.

**Comment by benesch** [comment]
I merged #17020 with the following addition to the PR template:

```md
- [ ] If this PR will require changes to cloud orchestration, there is a
   companion cloud PR to account for those changes that is tagged with
   the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
   <!-- Ask in #team-cloud on Slack if you need help preparing the cloud PR. -->
```

I think this is a good blend of asking people to take the first stab, but not making it a hard requirement. The linked example is simple enough to follow for many cases; the harder cases fall back on asking in #team-cloud, like you had here.

**Pull request closed without merging**
