### PR TITLE
storage: ensure command Sequencer is borrowed briefly during rendering

### LINKED ISSUE #27445: thread 'timely:work-0' panicked at src/storage/src/render/sinks.rs:75:49: already borrowed: BorrowMutError
### What version of Materialize are you using?

d280543eee9d

### What is the issue?

Seen in https://buildkite.com/materialize/test/builds/83142#018fe3d0-4522-4729-ab68-aa56ed29eab9, seems related to sinks
```
thread 'timely:work-0' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05b30dfdebc26b7a0-1/materialize/test/src/storage/src/render/sinks.rs:75:49:
already borrowed: BorrowMutError
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at ./rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   2: core::cell::panic_already_borrowed
             at ./rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/cell.rs:770:5
   3: <core::cell::RefCell<dyn mz_storage::internal_control::InternalCommandSender>>::borrow_mut
             at ./rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/cell.rs:1061:25
   4: mz_storage::render::sinks::render_sink::<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#1}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05b30dfdebc26b7a0-1/materialize/test/src/storage/src/render/sinks.rs:75:38
   5: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at ./rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/future/future.rs:123:9
   6: <mz_persist_client::operators::shard_source::shard_source_descs::ErrorHandler<mz_storage::render::sinks::render_sink<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#1}>>::report_and_stop::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05b30dfdebc26b7a0-1/materialize/test/src/persist-client/src/operators/shard_source.rs:282:33
   7: mz_persist_client::operators::shard_source::shard_source_descs::<mz_storage_types::sources::SourceData, (), i64, mz_storage_operators::persist_source::persist_source_core<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>, mz_storage_operators::persist_source::persist_source<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>, mz_storage::render::sinks::render_sink<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#0}, mz_storage::render::sinks::render_sink<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#1}>::{closure#0}::{closure#0}, mz_storage::render::sinks::render_sink<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#0}, mz_storage::render::sinks::render_sink<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#1}>::{closure#4}, timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>, mz_storage_operators::persist_source::persist_source_core<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>, mz_storage_operators::persist_source::persist_source<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>, mz_storage::render::sinks::render_sink<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#0}, mz_storage::render::sinks::render_sink<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#1}>::{closure#0}::{closure#0}, mz_storage::render::sinks::render_sink<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#0}, mz_storage::render::sinks::render_sink<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#1}>::{closure#3}::{closure#0}, mz_storage_operators::persist_source::persist_source<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>, mz_storage::render::sinks::render_sink<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#0}, mz_storage::render::sinks::render_sink<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#1}>::{closure#0}::{closure#0}, mz_storage::render::sinks::render_sink<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#0}, mz_storage::render::sinks::render_sink<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#1}>::{closure#1}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05b30dfdebc26b7a0-1/materialize/test/src/persist-client/src/operators/shard_source.rs:375:26
```
Full backtrace: https://gist.github.com/def-/3b464bd0734696d4724afe38b23b9748
Previously there was a similar panic: https://github.com/MaterializeInc/materialize/issues/5983

There recently was a timely/differential update, could that be related? CC @antiguru

ci-regexp: already borrowed: BorrowMutError

### PR DESCRIPTION
**Pull request by petrosagg**
The command sequencer is behind an `Rc<RefCell<_>>` and is shared by both the worker and the dataflows. In #27445 we discovered that there are cases where the operators need to use the sequencer during their first schedule, which happens synchronously as part of rendering.

This means that we must make sure to not keep a `borrow_mut` active in an earlier stack frame so that operators can take the borrow.

Fixes #27445

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Review by aljoscha — APPROVED** [review]
The explanation makes sense and I think this should work! We haven't yet managed to repro locally, so we can't verify the fix, though, right?

**Comment by petrosagg** [comment]
> We haven't yet managed to repro locally

I did. If you add an unconditional `command_tx.borrow_mut()` before the first await point of an operator it instantly crashes. You can verify with this diff:

```diff
diff --git a/src/storage/src/sink/kafka.rs b/src/storage/src/sink/kafka.rs
index 9dead1b5b2..9de5ccaf5e 100644
--- a/src/storage/src/sink/kafka.rs
+++ b/src/storage/src/sink/kafka.rs
@@ -183,6 +183,7 @@ impl<G: Scope<Timestamp = Timestamp>> SinkRender<G> for KafkaSinkConnection {
             metrics,
             statistics,
             write_frontier,
+            Rc::clone(&storage_state.internal_cmd_tx),
         );
 
         let running_status = Some(HealthStatusMessage {
@@ -555,6 +556,7 @@ fn sink_collection<G: Scope<Timestamp = Timestamp>>(
     metrics: KafkaSinkMetrics,
     statistics: SinkStatistics,
     write_frontier: Rc<RefCell<Antichain<Timestamp>>>,
+    command_tx: Rc<RefCell<dyn crate::internal_control::InternalCommandSender>>,
 ) -> (Stream<G, HealthStatusMessage>, PressOnDropButton) {
     let scope = input.scope();
     let mut builder = AsyncOperatorBuilder::new(name.clone(), input.inner.scope());
@@ -569,6 +571,7 @@ fn sink_collection<G: Scope<Timestamp = Timestamp>>(
     let sink_version = sink.version;
     let (button, errors) = builder.build_fallible(move |_caps| {
         Box::pin(async move {
+            command_tx.borrow_mut();
             if !is_active_worker {
                 write_frontier.borrow_mut().clear();
                 return Ok(());
```

**Comment by petrosagg** [comment]
Wait, it still panics even with my change! Did I miss something?

**Comment by petrosagg** [comment]
Ok, it was Rust being "helpful" and extending the lifetime of the temporary borrow till the end of the loop scope. Pushed another commit with an explicit borrow & drop that now works fine

**Pull request merged**
