### PR TITLE
Add system table that contains the aws privatelink connection principals

### PR DESCRIPTION
**Pull request by chaas**
Addresses #16446 (as part of #16140).
Exposes AWS PrivateLink connection principal in SQL via new system table `mz_aws_privatelink_connections` with columns `id` and `principal`.
Generates the principal via
1) flags passed into evironmentd: `MZ_AWS_ACCOUNT_ID` (added in this PR) and `MZ_AWS_EXTERNAL_ID_PREFIX` (already added and used by storage)
2) global id of the connection

### Tips for reviewer
* I'd appreciate some suggestions for the comment describing the `MZ_AWS_ACCOUNT_ID` flag and `AwsPrincipalContext` object, from someone who has more knowledge on aws privatelink, principals, and accounts.
* How should I handle the error case in `src/adapter/src/catalog/builtin_table_updates.rs`? I currently throw a `tracing::error!` but I'm not sure if we want something more severe to happen.
* Is there any way to test this locally? It would be nice to do some thorough stress testing.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Review by benesch — APPROVED** [review]
LGTM with a few follow-up work items:

  * An PR against the cloud repository to actually pass --aws-account-id, to be merged during the next maintenance window. (I think @alex-hunt-materialize agreed to take this one?)
  * A docs PR, to be merged during the next release.
  * A release note.

@chaas—can you make sure you file draft PRs or issues marked with "release-blocker" before you merge this, so that we don't forget?

**Comment by benesch** [comment]
> I'd appreciate some suggestions for the comment describing the MZ_AWS_ACCOUNT_ID flag and AwsPrincipalContext object, from someone who has more knowledge on aws privatelink, principals, and accounts.

Honestly seemed fine to me as is!

> How should I handle the error case in src/adapter/src/catalog/builtin_table_updates.rs? I currently throw a tracing::error! but I'm not sure if we want something more severe to happen.

I think the `tracing::error!` is good. We don't want to panic the process over this, but it's also something we should get someone looking at in cloud, and `error!` will go to Sentry. So that's pretty ideal.

> Is there any way to test this locally? It would be nice to do some thorough stress testing.

It's hard to test locally beyond cloudtest, but you can test it for real in staging!

**Comment by chaas** [comment]
> LGTM with a few follow-up work items:
> 
> * An PR against the cloud repository to actually pass --aws-account-id, to be merged during the next maintenance window. (I think @alex-hunt-materialize agreed to take this one?)
> * A docs PR, to be merged during the next release.
> * A release note.
> 
> @chaas—can you make sure you file draft PRs or issues marked with "release-blocker" before you merge this, so that we don't forget?

Done! I made tracker tickets for the above and marked them as release blockers.

**Comment by chaas** [comment]
We told sales we'd get this in by the 12/14 release, so it's not actually a release blocker per-se, though of course it would be nice to get it out earlier.

**Review by alex-hunt-materialize — APPROVED** [review]
This looks great, I'll make a PR for adding the arg from the environment-controller.

**Pull request merged**
