### PR TITLE
remove default privatelink kafka flag

### LINKED ISSUE #25468: storage/connections: promote default PrivateLink connections to Public Preview
### Feature request

Since default PrivateLink connections are being successfully used in production with a Redpanda Cloud deployment, it's safe to promote the feature to Public Preview.

- [ ] Remove the `enable_default_kafka_aws_private_link` flag. https://github.com/MaterializeInc/materialize/pull/25527
- [ ] Update the documentation.

@jubrad, I'll take the opportunity to push the docs improvements we talked about.

### LINKED ISSUE #26011: storage/connections: remove flag for default SSH connections
@guswynn: with #22871 merged, is there any remaining work to remove the `enable_default_kafka_ssh_tunnel` LD flag? This came up while discussing #25527. cc @jubrad

### PR DESCRIPTION
**Pull request by jubrad**
### Motivation
Removes the feature flag gating on the privatelink default connection for kafka syntax.
This feature is working and we do not wish to gate it per organization, per https://github.com/MaterializeInc/materialize/issues/25468

Fixes #25468.
Fixes #26011.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by jkosh44** [comment]
It looks like this flag is `false` in Launch Darkly for most environments in prod, https://app.launchdarkly.com/default/production/features/enable_default_kafka_aws_private_link/targeting. Maybe we want to set it to `true` in Launch Darkly first and then remove the flag?

**Comment by morsapaes** [comment]
Justin pointed out that we also didn't remove the flag for default SSH connections (`enable_default_kafka_ssh_tunnel`). Opened #26011 to track. cc @benesch

**Comment by jubrad** [comment]
@jkosh44 I've added the ssh flag as well and ensured targeting is set to default true for both flags in all envs.

**Review by jkosh44 — APPROVED** [review]
LGTM!

**Review by guswynn — APPROVED** [review]
ty!

**Review by morsapaes — APPROVED** [review]

**Comment by benesch** [comment]
Looks like there's a test file that needs to have its reference to `enable_default_kafka_ssh_tunnel` removed!

**Comment by jubrad** [comment]
> Looks like there's a test file that needs to have its reference to `enable_default_kafka_ssh_tunnel` removed!

Thanks!! I noticed this last night, but couldn't get back to resolving it.

**Pull request merged**
