### PR TITLE
persist: batch builder refactor take two

### PR DESCRIPTION
**Pull request by pH14**
[The last version of this PR](https://github.com/MaterializeInc/materialize/pull/16602) was reverted due to performance regressions in our feature benchmarks and an [OOM](https://github.com/MaterializeInc/materialize/issues/17044).

This updated PR fixes the OOM and skips the introduction of consolidating user batches. The investigation into the perf regression there is still in-progress, but it still seems valuable to otherwise merge the write paths for user batches and compaction. Once we better understand the perf impact, we can introduce a teeny follow-up PR that switches our batch builder to always consolidate.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a
  companion cloud PR to account for those changes that is tagged with
  the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Review by danhhz — APPROVED** [review]
we should 1000% point philip at this before merging once you're happy with it

**Comment by pH14** [comment]
Nightlies: https://buildkite.com/materialize/nightlies/builds/1645#0185a6be-bca6-48ef-a31b-b51a2d9ebb4c

**Comment by philip-stoev** [comment]
Thank you, will work on this first thing tomorrow.

**Comment by philip-stoev** [comment]
Nightly is green. Starting a release qualification test -- if it survives more than 4 hours I would say this PR is good to go.

**Comment by danhhz** [comment]
Looks like it's made it 6h so far? https://buildkite.com/materialize/release-qualification/builds/62

**Review by philip-stoev — APPROVED** [review]
Yes thanks, so this PR is good to go.

**Comment by pH14** [comment]
🙇 thanks for looking Philip!

**Pull request merged**
