### PR TITLE
test/perf-upsert: remove

### PR DESCRIPTION
**Pull request by benesch**
Per [0]. We haven't used this harness for a while in favor of other Avro
upsert benchmarks. If we do need a pure upsert benchmark in the future,
we can create a simplified version that uses the new Python-based
workflows.

[0]: https://github.com/MaterializeInc/materialize/issues/9809#issuecomment-1003378851

### Motivation

   * This PR removes existing code.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

**Comment by philip-stoev** [comment]
An upsert benchmark already exists in the new feature-benchmark framework. It is just that it uses testdrive's `$ kafka-ingest` and not kgen to populate the topic. See here:

https://github.com/MaterializeInc/materialize/blob/d232b777dbf38c8e7f2cbcd3893de722c322e951/test/feature-benchmark/scenarios.py#L605

**Comment by benesch** [comment]
Oh, fantastic! I feel even better about nuking this then. Does anyone object?

**Comment by ruchirK** [comment]
I'm afk but I certainly don't object! I have a draft that I hope can
replace this and avro upsert with mzworkflows + kgen

**Comment by benesch** [comment]
@ruchirK before you spend too much time on that, it sounds like @philip-stoev already has a replacement in his feature benchmark framework!

**Pull request merged**
