### PR TITLE
Breadcrumbs

### LINKED ISSUE #4591: docs: Implement breadcrumbs to improve usability of docs
We could implement breadcrumbs in docs. This allows for several benefits such as easy back/forth, educating the customer on a workflow (simple to complex) - especially on how-to type articles.

Examples are here - https://docs.yugabyte.com/latest/quick-start/build-apps/python/ysql-psycopg2/
https://docs.aws.amazon.com/redshift/latest/dg/welcome.html

@rjnn

### PR DESCRIPTION
**Pull request by sploiselle**
@benesch Just tagging you bc of your love of Hugo partials.

closes #4591

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4789)

### CODE REVIEW

**Comment by sploiselle** [comment]
@msudberg lmk what you think of this treatment, e.g. [on `float`](https://deploy-preview-4789--materializeinc.netlify.app/sql/types/float/).

The breadcrumbs only show up on pages that are not home, and whose parent is not home. Those whose parent is home only had "Home" in the breadcrumb and it felt _off_--the Home page doesn't meaningfully provide navigation to other pages, so it seemed pointless at best and misleading at worst.

**Comment by benesch** [comment]
Seems great to me!

> The breadcrumbs only show up on pages that are not home, and whose parent is not home. Those whose parent is home only had "Home" in the breadcrumb and it felt _off_--the Home page doesn't meaningfully provide navigation to other pages, so it seemed pointless at best and misleading at worst.

I wonder if we should elide Home from the breadcrumbs entirely by the same logic.

**Comment by sploiselle** [comment]
@benesch I thought about eliding home entirely but then it becomes far less obvious that they're actually breadcrumbs. I did a quick search and all of the help sites I looked at that used breadcrumbs anchored it with "Home", so there's a degree to which the pattern's been thoroughly baked into folks' UX expectations.

**Comment by benesch** [comment]
> @benesch I thought about eliding home entirely but then it becomes far less obvious that they're actually breadcrumbs. I did a quick search and all of the help sites I looked at that used breadcrumbs anchored it with "Home", so there's a degree to which the pattern's been thoroughly baked into folks' UX expectations.

Happy to defer to your structured thinking on this! I was just wondering out loud.

**Comment by sploiselle** [comment]
Merging this and can iterate on the design in the future

**Pull request merged**
