### PR TITLE
ore/metrics: implement `Borrow` for drop wrapper types

### PR DESCRIPTION
**Pull request by teskje**
This PR adds `Borrow` implementations to the wrapper types `DeleteOnDropHistogram`, `DeleteOnDropCounter`, and `DeleteOnDropGauge`.

This makes it possible to write code that is generic over both the prometheus type and the wrapped type. The existing `Deref` impl does not work for this.

[Slack thread for context.](https://materializeinc.slack.com/archives/CMH6PG4CW/p1686745059980529)

Blocks #19964.

### Motivation

  * This PR adds a feature that has not yet been specified.

Make it possible to write code that is generic over both `GenericGauge` and `DeleteOnDropGauge`.

### Tips for reviewer

@petrosagg points out that perhaps we shouldn't do this because `Borrow` is reserved for smart pointers. I would have called the `DeleteOnDrop*` wrappers smart pointers, but I'm also not clear about the definition. In any case, those types already implement `Deref`, which is also a smart-pointer trait.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - N/A

### CODE REVIEW

**Comment by petrosagg** [comment]
I see in the documentation of the `Borrow` trait a suggestion of using `AsRef` if the additional guarnatees of `Borrow` are not needed. Could we maybe add an `AsRef` impl to the types that we need?

If not, I think we should also add a comment in the definition of the struct warning future developers that they should not add a derive for any of `Eq`, `Ord` and `Hash` because that would invalidate the expectations of the `Borrow` impl

**Comment by teskje** [comment]
> Could we maybe add an AsRef impl to the types that we need?

I don't think that would work. The goal would be to specify a trait bound like:
```
G: AsRef<GenericGauge<_>>,
```

... and then be able to pass both `DeleteOnDropGauge` and `GenericGauge` in place of `G`. But there is no blanket `T: AsRef<T>` impl, so you'd end up in the same situation as with `Deref`.

Adding a comment is a good idea!

**Comment by teskje** [comment]
Alternatively, we could just invent our own `AsMetric` trait if people would feel more at ease with that. Implementing `Borrow` _is_ a bit scary.

**Comment by teskje** [comment]
I've added the comments as suggested by @petrosagg. In Slack we seem to have arrived at a rough consensus that the `DeleteOnDrop` wrappers are something smart-pointer like ("smart handles"?), but also that the `Borrow` do not mention smart pointers anyway. So I think adding `Borrow` impls is fine here.

**Review by petrosagg — APPROVED** [review]

**Comment by teskje** [comment]
TFTR!

**Pull request merged**
