### PR TITLE
SUBSCRIBE on arranged introspection sources

### LINKED ISSUE #16933: SUBSCRIBE for arranged introspection sources
### Feature request

Add support for SUBSCRIBEs targeting arranged introspection sources, e.g.:

```
COPY (SUBSCRIBE (SELECT * FROM mz_internal.mz_dataflow_operators)) TO STDOUT;
```

Currently, this statement fails with the following error:

```
ERROR:  SUBSCRIBE cannot reference a log source
DETAIL:  The query references the following log sources:
    mz_dataflow_operators
```

Being able to SUBSCRIBE to introspection sources is helpful for debugging. Initially, we figured that we don't need it for arranged introspection sources because persisted introspection sources provide the ability to subscribe to them. But we currently have disabled the persisted introspection sources, and it looks like getting them enabled again is more work than initially expected. In the meantime, it might be worth the effort to add the missing subscribe functionality to arranged introspection sources.

### PR DESCRIPTION
**Pull request by teskje**
This PR adds support for replica-targeted `SUBSCRIBE`s. This is useful because we can now allow subscribing to arranged introspection sources, if a target replica is selected.

The implementation works roughly like the one for replica-targeted peeks: The compute controller filters `SubscribeResponse`s received by the target replica (if any) and ignores all responses by other replicas. The major difference to replica-targeted peeks is that we cancel replica-targeted subscribes immediately when the target replica disconnects. This is done to ensure we don't see inconsistent output when subscribing to introspection sources, which are re-created on replica restarts.

### Motivation

  * This PR adds a known-desirable feature.

Closes #16933.

### Tips for reviewer

I recommend reviewing the commits separately.

We never documented the limitation that arranged introspection sources cannot be subscribed to, so there is no need to update docs.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a
  companion cloud PR to account for those changes that is tagged with
  the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - Add support for `SUBSCRIBE`s on introspection sources. The same limitations as for `SELECT`s from introspection sources apply, namely that on multi-replica clusters a target replica must be selected using `SET cluster_replica = <name>`.

### CODE REVIEW

**Comment by lluki** [comment]
Do you think it would make sense to add the following test?

Two sessions, the first session does a replica targeted subscribe and the second one does a `drop cluster replica ...` . Once when another replica is available in the cluster and once it's the last in the cluster.

**Comment by teskje** [comment]
> Two sessions, the first session does a replica targeted subscribe and the second one does a `drop cluster replica ...` . Once when another replica is available in the cluster and once it's the last in the cluster.

Isn't that roughly what `workflow_test_replica_targeted_subscribe_abort` tests? It kills the replica instead of dropping it and it doesn't test the case where there is no other replica in the cluster. It would pretty easy to add both variants to the mzcompose test. Do you think they might provide additional value?

**Review by mjibson — APPROVED** [review]
adapter changes lgtm

**Review by benesch — COMMENTED** [review]
Didn't review the code, but really happy to see this! 😍

**Comment by lluki** [comment]
> Isn't that roughly what `workflow_test_replica_targeted_subscribe_abort` tests? It kills the replica instead of dropping it and it doesn't test the case where there is no other replica in the cluster. It would pretty easy to add both variants to the mzcompose test. Do you think they might provide additional value?

I think it might exercise a different code path, ie. once we have remove replica explicitly called on the controller and once it just crashes.

**Comment by teskje** [comment]
> I think it might exercise a different code path, ie. once we have remove replica explicitly called on the controller and once it just crashes.

They both invoke `remove_replica_state` in the coordinator, which is where the subscribe shutdown is happening. But that's an implementation detail and might change, so fair point!

**Review by lluki — APPROVED** [review]
LGTM

**Comment by lluki** [comment]
> They both invoke `remove_replica_state` in the coordinator, which is where the subscribe shutdown is happening. But that's an implementation detail and might change, so fair point!

Ok, I think if there's a significant overlap in code paths, it's fine as-is!

**Comment by teskje** [comment]
I've added a `DROP CLUSTER REPLICA` test to the mzcompose test because it was easy to do.

TFTR!

**Pull request merged**
