### PR TITLE
sql-parser: derive AstDisplay and pretty documents for simple structs

### PR DESCRIPTION
**Pull request by mjibson**
SQL printing has a few uses: serializing user sql to the stash for rehydration on restart, `SHOW` statements, and pretty printers like sqlfmt. When we have to write these by hand we sometimes get them wrong (for example `extract` is currently broken and outputs the normal function syntax instead of its special variant, which will break on restart in views; also #15943). Writing by hand is much harder for sqlfmt too, due to the various nesting needed. Having a way to automate all of this may make it easier to write correct sql printing code.

Implement a new proc macro that can derive AstDisplay. It does this by deriving a trait for pretty printing and converting that to text.

This PR has various features that are not yet used because I dislike their names and ergonomics (but when applied to all statements in a test branch, I can fully roundtrip the whole test suite, so they do work; this is currently running at https://mz.sqlfum.pt/). This is instead hopefully a place where this can demonstrate its usefulness by showing what it does to some various statements that need no attributes to modify behavior.

### Motivation

  * This PR adds a feature that has not yet been specified.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a
  companion cloud PR to account for those changes that is tagged with
  the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - n/a

### CODE REVIEW

**Comment by mjibson** [comment]
Why are the axum changes happening in Cargo.lock? It seems to be messing up some other lint stuff that I don't get.

**Comment by benesch** [comment]
Innnnteresting! I can see the value on the simple cases for sure. I'm a little worried about the more complicated cases. It seems like unfamiliarity with the macro, and the general opaque-ness of macros, could be as bug prone as the current approach?

**Comment by mjibson** [comment]
That is possible! Here's what it looks like on the full codebase, with all tests passing: https://github.com/MaterializeInc/materialize/compare/main...mjibson:materialize:astdisplay#diff-4e3552eac676faaa575e9854cf9a01ad277612372ee82c68c98c8fc32998d093

There's a handful of attributes to do stuff that would be documented in the macro if we think this is good.

It's mostly only worth doing for the pretty structs, not just AstDisplay, although that's a nice bonus.

**Comment by benesch** [comment]
(I have no qualms about doing this for the simple cases you had in this PR, FYI!)

**Comment by mjibson** [comment]
IMO, only worth it if it gets used everywhere. Do you have thoughts about deriving just the pretty print trait, and leaving AstDisplay? It'd be the same amount of various struct attributes added, but we'd at least have AstDisplay as a fallback test for correctness.

**Comment by benesch** [comment]
> IMO, only worth it if it gets used everywhere. Do you have thoughts about deriving just the pretty print trait, and leaving AstDisplay? It'd be the same amount of various struct attributes added, but we'd at least have AstDisplay as a fallback test for correctness.

I think I like the sound of that!

**Pull request closed without merging**
