### PR TITLE
bump to rust 1.66

### PR DESCRIPTION
**Pull request by guswynn**
All the non-`Cargo.toml` changes are just clippy changes. The ones to `transform` look weird, but apparently its a (small) perf win: https://rust-lang.github.io/rust-clippy/master/index.html#box_default

### CODE REVIEW

**Review by benesch — APPROVED** [review]

**Comment by umanwizard** [comment]
Wait, what’s the perf win? Do those not do the exact same thing? Can you post the generated asm?

**Comment by guswynn** [comment]
> Wait, what’s the perf win? Do those not do the exact same thing? Can you post the generated asm?

I did not look into this closely

**Comment by antiguru** [comment]
Quoting from https://nnethercote.github.io/perf-book/standard-library-types.html#box:
> The expression [Box::default()](https://doc.rust-lang.org/std/boxed/struct.Box.html#method.default) has the same effect as Box::new(T::default()) but can be faster because the compiler can create the value directly on the heap, rather than constructing it on the stack and then copying it over. [Example](https://github.com/komora-io/art/commit/d5dc58338f475709c375e15976d0d77eb5d7f7ef).

**Review by umanwizard — CHANGES_REQUESTED** [review]
I would really rather not turn on random clippy lints that force you to write convoluted code unless we prove they have a legit perf impact. Can we please investigate this more before we land it? I’m afk now but I can look into it later today if nobody else has by then.

**Comment by antiguru** [comment]
> I would really rather not turn on random clippy lints that force you to write convoluted code unless we prove they have a legit perf impact. Can we please investigate this more before we land it? I’m afk now but I can look into it later today if nobody else has by then.

I'm sure this is a performance win because it'll avoid a mem copy, and it should be filed as writing ergonomic Rust code.

**Comment by guswynn** [comment]
https://rust.godbolt.org/z/xrYnaPqvY

The newer version definitely looks better, and I don't think the new version is "convoluted"

**Comment by umanwizard** [comment]
Ok, I can’t load godvolt on mobile for some reason, but if you checked and it’s doing extra work then it sounds fine to me. I do wish I understood why this was happening, though. My mental model is that rustc should be able to elide the memcpy, does anyone know why this isn’t true?

**Review by umanwizard — APPROVED** [review]

**Comment by guswynn** [comment]
> My mental model is that rustc should be able to elide the memcpy, does anyone know why this isn’t true?

This is related to a more general feature called "placement new", which is apparently extremely hard to get right, so only really the box impl can do "the right thing" here, i think

**Comment by umanwizard** [comment]
Wait again, did you compile on godbolt in release mode? I just set opt-level=3 and the code looks identical to me (as expected). Rustc compiles in debug mode by default.

**Comment by guswynn** [comment]
@umanwizard yeah in opt mode i assume it can sometimes make them the same, but our iteration cycles do involve non-release mode quite a bit

**Comment by umanwizard** [comment]
In general we shouldn’t be turning on lints for slight performance impacts in debug mode.

**Comment by guswynn** [comment]
> In general we shouldn’t be turning on lints for slight performance impacts in debug mode.

In general I agree, but the new way is documented as more performant, without relying on llvm opt passes to make it so

**Comment by umanwizard** [comment]
For example, in C, ++i is faster than i++ in debug mode. But most people would think it silly to lint for that.

**Comment by guswynn** [comment]
rustdoc started complaining about the non-` `` `'d usages of `<thing>`, so second commit is cleaning that up

**Comment by umanwizard** [comment]
If we can’t prove any perf impact on release, I would say this goes against our philosophy on clippy lints. Can we please open a broader discussion before landing this

**Comment by guswynn** [comment]
@umanwizard I don't think the code changes are very gross, and it easier to cleanup the ~20 callsites here after merging if we think this lint should be turned off, so I'd rather just merge and give people the somtimes-double-digit compilation speed increase

**Comment by umanwizard** [comment]
Our philosophy is not to turn on lints by default, though, unless we have a good reason to, because you are forcing everyone at the company into someone’s personal coding style. We have already spent tons of time and energy litigating this in the past. I’d rather back out the new lint and then land this (or show some evidence that it makes a difference in release mode)

**Comment by umanwizard** [comment]
(Or, alternatively, open a broader internal discussion if we want to change that philosophy)

**Comment by frankmcsherry** [comment]
The `transform` stuff looks especially grim, as it forces unrelated code changes when transforms implement `Default`. Those that do need the new syntax, and those that don't use the old syntax. I

**Comment by guswynn** [comment]
Merging without the `transform` changes, i added this new lint to the ignore list in `bin/check` for now

**Comment by benesch** [comment]
Sounds like the right path, in the interest of getting us onto 1.66 ASAP. Thanks, Gus!

**Pull request merged**
