### PR TITLE
adapter: Create structure around plan optimization

### PR DESCRIPTION
**Pull request by jkosh44**
See individual commit messages

### Motivation
This PR refactors existing code.

### Tips for reviewer
 - Hide whitespace
 - Review commit by commit

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [X] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [X] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - There are no user-facing behavior changes.

### CODE REVIEW

**Comment by jkosh44** [comment]
Unfortunately, when looking into other plans, it looks like their optimizations have been updated recently to require information from sequencing. For example, `SUBSCRIBE` needs a timestamp and `CREATE MATERIALIZED VIEW` needs a `GlobalId`.

So I'm not sure how feasible this approach is anymore.

**Comment by ParkMyCar** [comment]
Thanks for putting this up @jkosh44! With some tweaking I think we can get this to work for the other plan types. Although the really large `match` statements make me lean towards creating a `trait Plan` that all of the different structs would implement, then we'd pass around `Box<dyn Plan>`s. More than happy to huddle and brainstorm a solution here

**Comment by ParkMyCar** [comment]
Something that just came up [here](https://github.com/MaterializeInc/materialize/pull/24335#issuecomment-1885399751) is handling panics in off-thread work. We don't need to do anything immediately, but I'm not sure if anyone has really thought through this yet

**Comment by jkosh44** [comment]
@ParkMyCar I'm going to close this for now because I don't have the bandwidth to focus on it. Feel free to pick it back up if you're interested.

**Pull request closed without merging**
