### PR TITLE
add dark mode + make the design consistent with www.

### PR DESCRIPTION
**Pull request by nisarhassan12**
This Pr adds support for the dark mode to the docs + updates the design to be consistent and in line with the new design changes to the marketing website. 
image

### CODE REVIEW

**Comment by joacoc** [comment]
As a short-sighted, I find it difficult to read long gray texts over black backgrounds. Has it been considered turning the text white/adding more light, or different the contrasts?

**Comment by joacoc** [comment]
Minor detail: Alignment and low contrast over the _Note_ font color (similar effect as gray text over black background)
Screen Shot 2022-11-08 at 15 42 26

**Comment by joacoc** [comment]
Bullet points seem to break **only when text is more than one line.** 
Screen Shot 2022-11-08 at 15 49 01

**Comment by joacoc** [comment]
Having the dark mode and the new header, it's a 💯

Overall feedback: I find it more enjoyable to read the white version over the dark one. It feels related to the contrasts between text colors and the dark background. At the same time, it made me realize that we might be using too many links in our documentation.

If you don't mind, I will keep using it as my official source to keep the feedback flowing!

**Comment by parkerhendo** [comment]
+1 to what was said above: the gray text is difficult to read in some places and the links are a bit too vibrant for the dark background.

To adjust colors when adapting colors from a light theme to a dark theme you can slightly reduce saturation and increase lightness (if you're using the HSL color space) to help improve readability. @nisarhassan12 let me know if you'd like some help with this.

**Comment by nisarhassan12** [comment]
Many Thanks ❤️ , @joacoc for the valuable feedback. 

> If you don't mind, I will keep using it as my official source to keep the feedback flowing!

Please feel free to do so 🙂 No worries at all.

**Comment by ruf-io** [comment]
I know this is still WIP, but here are a couple additional formatting notes... excited for these updates!


1. Increase line height within a multiline note box image https://preview.materialize.com/materialize/15970/sql/create-table/
2. Spacing between successive Hx tags without content could be collapsed 
image https://materialize.com/docs/sql/create-table/
3. Something changed related to indentation within list items, where a code block nested in a list item isn't properly indented  image
4. Icons in the [Tools and Integrations](https://preview.materialize.com/materialize/15970/integrations/) page are sized incorrectly. image
5. Search placeholder text is very small.  image
6. The ordered list special style has a top margin that is off 
image https://preview.materialize.com/materialize/15970/integrations/redpanda-cloud/

**Comment by nisarhassan12** [comment]
> As a short-sighted, I find it difficult to read long gray texts over black backgrounds. Has it been considered turning the text white/adding more light, or different contrasts?/

@joacoc I have made some color changes to make the contrast better let me know how the new changes feel to you. Thanks 

| Before | After |
| - | - |
| image | image |

**Comment by nisarhassan12** [comment]
Thanks, @morsapaes for the review. 

> We should keep the links to Slack and GitHub in the bar:

Would it be OK to have those links in the footer? In my opinion, the current bar takes up too much space.

If the links are important then what about having them fixed at the top of the Table of contents on the right side ?

**Comment by morsapaes** [comment]
The improvements look great; thank you @nisarhassan12!

> Would it be OK to have those links in the footer? In my opinion, the current bar takes up too much space.

It's easy to miss them in the footer, and at least the Slack community link should be prominent. Keeping them to the right in the table of contents sounds like a good option!

> Did you find yourself uneasy seeing the text and the contrast not being good enough? If so then I can make it more white.

The issue isn't about the contrast (the text is easy to read). These blocks are supposed to stand out in the page for two reasons: on one hand because they have important information that we want users to notice, and on the other to break what are otherwise walls of text in some pages. What I meant is that, as is, the blocks themselves don't stand out!

Two other things I noticed just now: 

1. Is "Back to top" supposed to be in the Table of Contents section? If I click it once, it sticks to the `#top` anchor and doesn't have any effect when I click it again. Maybe this would make more sense at the bottom of the main section?

2. There's a lingering form at the bottom of [`Tools and Integrations`](https://preview.materialize.com/materialize/15970/integrations/#data-collaboration). Also, the buttons in the page aren't consistent with the `Copy` buttons!

Screenshot 2022-11-16 at 11 00 09

The current approach to have a little pop up widget looks better to me (also because it doesn't change the height of the table cell):

Screenshot 2022-11-16 at 11 04 45

**Comment by joacoc** [comment]
👆 The improvemenets in the docs are significant! 🚀 

Related to the text color, I will vouch for white color on the _main.content section_:

Screen Shot 2022-11-16 at 11 04 35

And a another color for `.rr-diagram rect.terminal` (currently has `#c7bede` - alt. random color pick `#ab96e0`)).

Current:
Screen Shot 2022-11-16 at 11 09 36

Alt. random color pick:
Screen Shot 2022-11-16 at 11 08 30

**Comment by nisarhassan12** [comment]
> It's easy to miss them in the footer, and at least the Slack community link should be prominent. Keeping them to the right in the table of contents sounds like a good option!

Thanks. Marta, I have added the community link at the top of the TOC and the GitHub link in the footer right after the status link. 

| Community Link | GitHub Link |
| - | - |
| image | image|

**Comment by nisarhassan12** [comment]
I have updated the annotations to have better contrast so that the stand out more:

| Before | After |
| - | - |
| image | image |

**Review by morsapaes — APPROVED** [review]
Thank you for working through all the feedback, Nisar! The current state LGTM. 🚀

**Pull request merged**
