### PR TITLE
Revert "storage: bounded memory upsert snapshot"

### LINKED ISSUE #19628: Sentry: panic: assertion failed: `(left == right)`: invalid upsert state
Sentry Issue: [DATABASE-BACKEND-2RM](https://materializeinc.sentry.io/issues/4220430629/?referrer=github_integration)

```
panic: assertion failed: `(left == right)`
  left: `4328045657276700020`,
 right: `7582626290675004269`: invalid upsert state
  File "panicking.rs", line 575, in rust_begin_unwind
  File "types.rs", in mz_storage::render::upsert::types::StateValue::ensure_decoded
  File "upsert.rs", line 389, in mz_storage::render::upsert::upsert_inner::
  File "builder_async.rs", line 501, in mz_timely_util::builder_async::OperatorBuilder<T>::build::
  File "builder_rc.rs", line 172, in <timely::dataflow::operators::generic::builder_rc::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestam...
...
(36 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by aljoscha**
Fixes #19628

This reverts https://github.com/MaterializeInc/materialize/pull/19268. Unfortunately, I also had to revert https://github.com/MaterializeInc/materialize/pull/19314 because it built on the first PR. Reverting everything was the quickest choice for now.

NOTE: When cherry-picking this on top of `v0.56.1` for creating a release, we have to drop "Revert "storage: Upsert state error handling" because it's not on the branch.

### CODE REVIEW

**Review by def- — APPROVED** [review]
Do we need to revert on main first to cherry-pick this?

**Comment by aljoscha** [comment]
> Do we need to revert on main first to cherry-pick this?

Not sure yet, it would seem cleaner to do so, yes. I updated the PR description because `v0.56.1` doesn't have one of the reverted changes.

**Comment by aljoscha** [comment]
We have confirmed that this actually fixes the bug that we observed in production by rolling a patch release to some environments.

**Comment by aljoscha** [comment]
@guswynn I'm leaning towards reverting this, until we figure out what's wrong. I don't like it because there's follow-up work already happening. But it's better to be on the safe side. Wdyt?

**Comment by guswynn** [comment]
@aljoscha I don't think we need the revert with https://github.com/MaterializeInc/materialize/pull/19641

**Pull request closed without merging**
