### PR TITLE
[mz] Add create, set, and show commands

### PR DESCRIPTION
**Pull request by sjwiesman**
### Motivation

Builds on #15815 

Adds `create`, `set`, and `show` commands so the API feels closer to the rest of Materialize. 

```
$ mz auth
$ mz create region aws/us-east-1
$ mz show region
  region
-----------------
  aws/us-east-1

$ mz show regions

  region        | status
----------------+-----------
  AWS/us-east-1 | enabled
  AWS/eu-west-1 | disabled

$ mz set region aws/us-east-1
$ mz shell

```

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Comment by benesch** [comment]
Is it right that there are two classes of change in here? One is the ability to set a region, and the other is a pretty substantial redesign of the interface? We did a good a bit of design work on the structure of these commands here: https://www.notion.so/materialize/CLI-design-document-cc9858ecaa9d4f3782ed9278d98fd65b. I'm reticent to invert the structure from `NOUN VERB` to `VERB NOUN`, as not all nouns support the same verbs. E.g., we try to consistently say "enable a region" rather than "create a region" throughout the UI and docs.

**Comment by sjwiesman** [comment]
> Is it right that there are two classes of change in here? One is the ability to set a region, and the other is a pretty substantial redesign of the interface?

That sound about right. Maybe taking a step back, the features I’ve actively found myself wanting after a few weeks of use.

1. default region for a profile
2. being able to have a current profile 
3. unified output format when describing objects
4. not logging in twice 

Using create, set, and show in a VERB NOUN schema felt like the obvious pattern for me because it is consistent with how I’d perform these operations on clusters, views, etc.

If you feel strongly, I can roll that much back. We’ll just need to figure out what the NOUN VERB pattern for setting a region should be

**Comment by sjwiesman** [comment]
how would you feel about enable being a sort of `create if not exists and set`?

**Comment by benesch** [comment]
Ugh, sorry for taking so long to get back to you! I think what I’m most
worried about blurring the line between SQL and the CLI as they’re
fundamentally different mediums in control of different resources. The
backend APIs and the config files that the CLI interacts with don’t
necessarily map neatly to SQL-like resources. Idk! I’m just nervous that it
maps ok right now with a small set of nouns and verbs, but it won’t scale.

Also, most of the modern CLIs I can think of (gh, pscale) use the NOUN VERB
form. And pscale seems to similarly maintain a strict separation between
the CLI itself and the SQL shell.

Maybe I’m looking at this the wrong way, though? Not sure! There is
something appealing about making the Materialize experience feel SQL-y
across the board. Curious to hear others’ takes on this.

Are there other features we expect to add to the CLI in the near term? Can
we quickly sketch those out to see how this VERB NOUN setup would scale?

**Comment by sjwiesman** [comment]
Do not worry, this is clearly the least important thing either of us is working on lol. 

I understand the hesitation around conflating CLI and SQL concepts. I got here because I needed a way to show the current region and all regions. We do that for clusters with `show cluster` and `show clusters`. It seemed like a clean concept to copy and then everything else came from there. 

I am really not tied to this PR at all. I would like to make one last proposal and then I will drop it. 

Have login take a profile that authorizes the current profile if not already authorized, and then makes it the current profile

```
mz-login
Login to Materialize for a specific profile

USAGE:
    mz login [OPTIONS] [PROFILE]

ARGS:
    <PROFILE>    The profile to login [default: default]

OPTIONS:
    -f, --force          force reauthorization of the profile
    -h, --help           Print help information
    -i, --interactive    Login by typing your email and password
```

And have `mz region enable [region]` enable a region if not already set and make it the default region for the current profile.

**Comment by benesch** [comment]
Those proposals both make sense to me!

**Review by benesch — APPROVED** [review]
Didn't review in depth, but LGTM if it works for you.

**Comment by sjwiesman** [comment]
appreciate it!

**Pull request merged**
