### PR TITLE
catalog: eliminate superfluous level in persist json mapping

### PR DESCRIPTION
**Pull request by danhhz**
Before this commit, this wrote json that was encoded like:

    {"kind": {"kind": "timestamp", ...}}

with an extra level of json object with always one "kind" key and the real data as a value. This makes it clunky to use when exposed via SQL. Instead, eliminate the outer object:

    {"kind": "timestamp", ...}

### Motivation

  * This PR fixes a previously unreported bug.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by danhhz** [comment]
Okay @jkosh44 cherry-picked this into my "expose catalog as SQL" branch and verified that it works as advertised. This is probably gonna break an upgrade test as-is, I'll have to remind myself where to adjust that

```
materialize=> COPY (SUBSCRIBE TO (select data from mz_internal.mz_catalog_raw where data->>'kind' = 'Timestamp') as of 19) TO STDOUT;
19	1	{"key":{"id":"M"},"kind":"Timestamp","value":{"ts":{"internal":1704225943326}}}
20	-1	{"key":{"id":"M"},"kind":"Timestamp","value":{"ts":{"internal":1704225943326}}}
20	1	{"key":{"id":"M"},"kind":"Timestamp","value":{"ts":{"internal":1704225948327}}}
21	1	{"key":{"id":"M"},"kind":"Timestamp","value":{"ts":{"internal":1704225954325}}}
21	-1	{"key":{"id":"M"},"kind":"Timestamp","value":{"ts":{"internal":1704225948327}}}
```

**Comment by jkosh44** [comment]
If this breaks an upgrade test, which I think it probably will, we have two options to fix this:

- Update the version here: https://github.com/MaterializeInc/materialize/blob/164c892916de4de64832d80f169dde0e4afc27a5/misc/python/materialize/checks/mzcompose_actions.py#L46-L50
- Write a catalog migration as described in the steps here: https://github.com/MaterializeInc/materialize/blob/164c892916de4de64832d80f169dde0e4afc27a5/src/catalog/src/durable/upgrade.rs#L18-L40

**Comment by danhhz** [comment]
I'd personally lean toward the former, given that we haven't run this on staging yet, but an argument could be made for doing the latter to sanity check the process. Thoughts?

**Comment by danhhz** [comment]
Oh, nevermind! That process you linked is the existing process, not the new "how to change the json mapping" one

**Comment by jkosh44** [comment]
I think you need to also update this which controls how the versioned proto is converted to/from `StateUpdateKindRaw`.

https://github.com/MaterializeInc/materialize/blob/164c892916de4de64832d80f169dde0e4afc27a5/src/catalog/src/durable/upgrade.rs#L70-L84

> I'd personally lean toward the former, given that we haven't run this on staging yet, but an argument could be made for doing the latter to sanity check the process. Thoughts?
> Oh, nevermind! That process you linked is the existing process, not the new "how to change the json mapping" one. Shouldn't be too hard to write an upgrade for this if you think that's worth it

I would lean towards writing a migration, but in this case I think you're better off just bumping the version. Now that I'm looking at the code, in order to write a migration properly, you'll need to do some annoying refactors around the code I linked above.

**Comment by danhhz** [comment]
> I would lean towards writing a migration, but in this case I think you're better off just bumping the version. Now that I'm looking at the code, in order to write a migration properly, you'll need to do some annoying refactors around the code I linked above. Specifically, we'll need different implementations for different versions.

Yeah, I just noticed the same myself. Force pushed a bump from "v0.81.0-dev" ->  "v0.82.0-dev"

**Review by jkosh44 — APPROVED** [review]
LGTM

**Comment by danhhz** [comment]
TFTR!

**Pull request merged**
