### PR TITLE
storage/source/mysql: fix snapshot transaction

### LINKED ISSUE #25124: mysql: data correctness issue with stream of large dataset
### What version of Materialize are you using?

7a402c18b6

### What is the issue?

https://github.com/MaterializeInc/materialize/pull/25052 introduces the `MySqlStreaming` in the feature benchmark, which, however, reveals correctness issues.
Failure instances in nightly builds are [1](https://buildkite.com/materialize/nightlies/builds/6375#018d8d00-d977-45be-b7b4-c6c3aebf76cb), [2](https://buildkite.com/materialize/nightlies/builds/6375#018d8d5f-d606-4182-9a0f-f7576a697add), and [3](https://buildkite.com/materialize/nightlies/builds/6375#018d8dfc-c66c-48c1-a14d-6ad1bdcf4a3c). I also managed to reproduce it locally by running `bin/mzcompose --find feature-benchmark down && bin/mzcompose --find feature-benchmark run default --other-tag latest --scenario MySqlStreaming` on branch [tests/mysql-benchmark](https://github.com/nrainer-materialize/materialize/tree/tests/mysql-benchmark) of [PR#25052.](https://github.com/MaterializeInc/materialize/pull/25052)

The scenario inserts 100'000 rows in chunks of 100 rows into table `t1` in MySQL. Table `t1` is defined as `CREATE TABLE t1 (pk SERIAL PRIMARY KEY, f2 BIGINT);` [(more details in the code)](https://github.com/MaterializeInc/materialize/blob/e46663511f7bd3677746f19e77b43876ce30a5de/test/feature-benchmark/scenarios.py#L1487).

All 100'000 rows arrive in MySQL:
```
mysql> select count(*), count(distinct pk) from t1;
+----------+--------------------+
| count(*) | count(distinct pk) |
+----------+--------------------+
|   100000 |             100000 |
+----------+--------------------+
1 row in set (0.02 sec)
```

However, mz shows duplicates!

```
materialize=> select count(*) from t1;
 count  
--------
 105300
(1 row)
```

```
materialize=> select * from t1;
   pk   | f2  
--------+-----
 1      |   1
 1      |   1
 2      |   2
 2      |   2
 3      |   3
 3      |   3
[...]
```

It is interesting that mz does not correctly group them. Could this be due to the optimizer knowing that column `pk` is supposed to be unique (which it is in MySQL)?

```
materialize=> select pk from t1 group by pk having count(*) > 1;
 pk 
----
(0 rows)

materialize=> select * from t1 where pk = 141;
 pk  | f2 
-----+----
 141 | 14
 141 | 14
(2 rows)

materialize=> select pk, count(*) from t1 where pk = 141 group by pk;
 pk  | count 
-----+-------
 141 |     1
 141 |     1
(2 rows)
```

This does not apply to `count(distinct)`:
```
materialize=> select count(*), count(distinct pk) from t1;
 count  | count  
--------+--------
 105300 | 100000
(1 row)
```

### PR DESCRIPTION
**Pull request by benesch**
The source snapshot code was inadvertently dropping the transaction it intended to use on the floor, leading to the correctness issue observed in #25124.

Specifically, the SELECT query to load the table's snapshot was running outside of any transaction. This allowed it to observe the handful of transactions that committed *after* the snapshot's consistent point was constructed but before the SELECT query began executing. The replication stream (correctly) did not rewind this data, resulting in the data from that handful of transactions getting ingested into Materialize twice.

As far as I can tell, the code's approach to locking is (now) sound, so we don't need any of the changes to the locking scheme proposed in #25300. In particular, FLUSH TABLES only seems relevant if you need the data to be flushed to disk--e.g., so that you can reach into MySQL's data directory and tar up the files for export to another machine. Since we export the data using a SELECT statement, it seems to me that using LOCK should be sufficient [0].

The test enclosed in this PR is based on @rjobanp's test in #25300, but modified to insert data in parallel with creating the source in Materialize. The original test only failed sporadically on current main, but the modified test failed reliably--i.e., in 100% of the 4-5 times I ran it. The modified test also reliably passes with the fix in this commit.

Closes #25300.
Fixes #25124.

[0]: Confirming that statement in the MySQL documentation is left as an exercise to the reader.

### Motivation

  * This PR fixes a recognized bug.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - n/a

### CODE REVIEW

**Review by petrosagg — APPROVED** [review]
amazing!

**Review by rjobanp — APPROVED** [review]
Thank you so much for spotting this!

**Comment by rjobanp** [comment]
Looks like the `replica-connection` test is failing - I'll try to debug what is causing that now

**Comment by rjobanp** [comment]
Ah looks like you caught the issue. From what I can tell, the source created by the `many-inserts` workflow used a table `t1` that was the same name as the table used in the `replica-connection` workflow. And even though test-drive was supposed to clear state between runs, it looks like the first source was still ingesting rows while the 2nd workflow started to run, so it likely didn't actually clean up fully before the 2nd workflow. And then it hit an error because the schema for that upstream table had changed in the meantime.

**Comment by benesch** [comment]
Oh sorry, yes! I kinda cheated by just using a different table name. Didn't want to think harder about what the more robust fix was. 😅 Please feel free to push up an improved approach.

**Comment by rjobanp** [comment]
That seems like the simplest/best fix! Alternatively we'd have to block the start of each test workflow to see if any other sources still exist and are not yet dropped, which doesn't seem great

**Comment by rjobanp** [comment]
Actually it's still failing. I think we may need to explicitly drop the source at the end of `workflow_many_inserts` to ensure it's cleaned up before other workflows start. The testdrive reset behavior doesn't seem to be working for some reason, maybe it's just best-effort?

**Comment by benesch** [comment]
> Actually it's still failing. I think we may need to explicitly drop the source at the end of `workflow_many_inserts` to ensure it's cleaned up before other workflows start. The testdrive reset behavior doesn't seem to be working for some reason, maybe it's just best-effort?

Yeah, strange! The cleanup is `DROP DATABASE materialize`—are we creating things outside of the `materialize` database maybe?

**Comment by rjobanp** [comment]
I don't believe we are. But I think now the issue is in the `schema-restart/before-restart.td` file -- since we are creating a source with `FOR ALL TABLES` it's including all the tables left in MySQL at the end of the previous workflow runs, which includes the `many_inserts` table.

Most of the other tests are using the `public` schema in MySQL and dropping it before they start, but in this case it's using a separate schema name `dummyschema` and therefore leaving the `public` schema around.

I think the easiest cleanup now is to replace all instances of `dummyschema` with `public` in `test/mysql-cdc`.

**Pull request merged**
