### PR TITLE
sql-parser,testdrive: fix CREATE SINK syntax bug

### PR DESCRIPTION
**Pull request by JLDLaughlin**
### Motivation

Our current `CREATE SINK` syntax [has a bug](https://github.com/MaterializeInc/materialize/issues/8231). This PR updates the `CREATE SINK` syntax to eliminate ambiguity between the two sequential `WITH (..)` clauses. Internal discussion can be [found here](https://materializeinc.slack.com/archives/CMHDK0DK8/p1631740333231000).

### Description

The following diagram illustrates the proposed syntax change. By introducing the consistency information with a new `WITH CONSISTENCY` clause, and by wrapping the `TOPIC` and `FORMAT` arguments in `()`, we can disambiguate sequential `WITH` options and fix the bug.

Screen Shot 2021-09-15 at 8 29 11 PM

### Tips for reviewer

So this PR is incomplete/a WIP because I am not totally sure how I'd migrate something like this. The other migrations in [`migrate.rs`](https://github.com/MaterializeInc/materialize/blob/main/src/coord/src/catalog/migrate.rs) require the stashed `create_sql` strings to still be parseable. Unfortunately, my proposed changes will not allow old `CREATE SINK` statements to be parsed.

I tried to add a new type of migration in the second commit, but I just stubbed it out because I'm not sure if it's totally unhinged. @sploiselle -- would you be able to give your expert migration guidance here? Once you do, I'll complete the PR.

### Checklist

- [ ] This PR has adequate test coverage.
- [ ] This PR adds a release note for any user-facing behavior changes.

### CODE REVIEW

**Comment by JLDLaughlin** [comment]
@sploiselle & @benesch: would you be able to take a look at the migration idea for this change? (details in Tips for Reviewer)

**Comment by sploiselle** [comment]
When chatting about all of this last night, though, I forgot that we haven't introduced any syntax migrations yet, and this would be the first. Maybe this, too, is more expressly verboten than I realized. So apologies if this is turning into a goose chase. Before sinking more time into this, I'd like @benesch to chime in as to whether or not changing syntax is possible/desirable.

If this is OK, though, I want to write down some of my thoughts:
- In this new syntax, where do the previously ambiguous `WITH` options go?
- While I think regex is a feasible approach for this because the input is normalized, I know that others on this PR are [much more leery](https://github.com/MaterializeInc/materialize/pull/3469#issuecomment-650458934) of them in parsing contexts.
- One alternative approach would be to tokenize/lex the input string, modify the tokens into whatever shape you wanted them, and then convert that back into a string.

  This has the downside that it's very hard to express optional matching and basically requires writing a little regex engine. Simple regex engines are possible to write (CRL has an hour-long interview doing it), so I don't think this disqualifies us, but we're now talking about more substantive amounts of work. FWIW, I'd be very game to do this.

**Comment by JLDLaughlin** [comment]
That all makes sense to me, thanks @sploiselle!

I definitely understand the regex hesitation. If we’re not happy with that, maybe we can create ‘parse’ functions for deprecated syntax just to perform the migrations?

(I’ll wait for Nikhil’s guidance on the change overall!)

**Comment by JLDLaughlin** [comment]
Closing in favor of https://github.com/MaterializeInc/materialize/pull/8370.

**Pull request closed without merging**
