### PR TITLE
expr: rename nullary functions to nonpure functions

### PR DESCRIPTION
**Pull request by benesch**
Presently all nullary functions are nonpure, but one day that may not be
true. Rename NullaryFunc to NonpureFunc accordingly, and similarly for
associated types and methods.

This completes the followup requested by @aalexandrov in the review of
PR #10449.

### Motivation

   * This PR refactors existing code.

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - N/A

### CODE REVIEW

**Comment by umanwizard** [comment]
As we discussed in https://materializeinc.slack.com/archives/CMHDK0DK8/p1646163974340029 , the relevant distinction for Materialize is not actually whether the functions are pure, it is whether they rely on non-dataflow state. So I find the use of the term "Nonpure" confusing.

That said, I'm not sure what term would be better.

**Comment by benesch** [comment]
Proposal from Slack discussion: "materializable" and "unmaterializable".

**Comment by benesch** [comment]
This has now been updated to use the term "unmaterializable" instead, as discussed on Slack.

**Review by frankmcsherry — APPROVED** [review]
These changes comport with my sensibilities.

**Pull request merged**
