### PR TITLE
Enable more clippy lints

### PR DESCRIPTION
**Pull request by teskje**
This commit enables a bunch of new (hopefully uncontroversial!) clippy lints in our code checks, and makes the corresponding fixes to the code.

* [clippy::deref_addrof](https://rust-lang.github.io/rust-clippy/master/#deref_addrof)
* [clippy::needless_borrow](https://rust-lang.github.io/rust-clippy/master/#needless_borrow)
* [clippy::needless_collect](https://rust-lang.github.io/rust-clippy/master/#needless_collect)
* [clippy::needless_question_mark](https://rust-lang.github.io/rust-clippy/master/#needless_question_mark)
* [clippy::needless_return](https://rust-lang.github.io/rust-clippy/master/#needless_return)
* [clippy::redundant_pattern](https://rust-lang.github.io/rust-clippy/master/#redundant_pattern)
* [clippy::redundant_slicing](https://rust-lang.github.io/rust-clippy/master/#redundant_slicing)
* [clippy::redundant_static_lifetimes](https://rust-lang.github.io/rust-clippy/master/#redundant_static_lifetimes)
* [clippy::useless_format](https://rust-lang.github.io/rust-clippy/master/#useless_format)
* ~~[clippy::writeln_empty_string](https://rust-lang.github.io/rust-clippy/master/#writeln_empty_string)~~

### Motivation

   * This PR refactors existing code.

### Tips for reviewer

Each lint has a separate commit. Definitely review them separately, they should be quite skim-able that way.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Comment by benesch** [comment]
Tagging in @brennanvincent and @frankmcsherry as two folks who have had strong opinions in the past about clippy lints that veer into style lint territory.

**Comment by brennanvincent** [comment]
I find `redundant_static_lifetimes` and `writeln_empty_string` to be a bit dubious, that is a purely stylistic choice. The other ones I am in favor of.

**Comment by teskje** [comment]
I don't really feel strongly about any of this! These are all slight readability improvements, nothing I would insist on.

I can't think of a scenario where adding `'static` to a const reference improves readability, so I'd still rather keep that lint.

Regarding `writeln_empty_string`, enforcing this might actually be less readable when you have multiple writes, e.g.:
```
writeln!(f, "a line");
writeln!(f);
writeln!(f, "another line");
```
That second line breaks the flow a bit. So I agree with you here and will remove that commit.

**Comment by brennanvincent** [comment]
OK, sounds good to me

**Review by brennanvincent — APPROVED** [review]

**Pull request merged**
