### PR TITLE
mz: add audiences for validation

### PR DESCRIPTION
**Pull request by joacoc**
### Motivation

The latest version of the `jsonwebtoken` crate validates whether the token audiences are valid; otherwise, it raises an error. This PR sets the audiences for staging and production to validate the tokens.

I scraped the audiences from the token itself since I don't have access to Frontegg. My logic reasons they are unique per environment (one for staging and another for production).

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by philip-stoev** [comment]
Please run the e2e and "canary deploy" CI steps from Nightly.

**Comment by philip-stoev** [comment]
I am not the right person to review this, as I know zilch about this feature.

**Comment by joacoc** [comment]
@philip-stoev, do you have any idea why no steps are executed when I select the canary deploy test in Buildkite? Is the branch property in `pipeline.template.yml` filtering it?

```yml
# pipeline.template.yml 
...
  - id: cloud-canary
    label: "Canary Deploy in Staging Cloud"
    artifact_paths: junit_*.xml
    timeout_in_minutes: 1200
    concurrency: 1
    concurrency_group: 'cloud-canary'
    agents:
      queue: linux-x86_64
    plugins:
      - ./ci/plugins/mzcompose:
          composition: cloud-canary
    branches: "main v*.*"
```

**Comment by def-** [comment]
Yes, we don't run this check on PRs. Let me make a draft PR which removes this `branches` filter, then we can see if this PR works.

**Comment by joacoc** [comment]
Closing in favor of https://github.com/MaterializeInc/materialize/pull/24146

**Pull request closed without merging**
