### PR TITLE
platform-checks: Upsert with unordered key

### PR DESCRIPTION
**Pull request by def-**
Reproduces https://github.com/MaterializeInc/database-issues/issues/8622

See discussion in https://materializeinc.slack.com/archives/C0761MZ3QD9/p1728396197787329

```
$ bin/mzcompose --find platform-checks down && bin/mzcompose --find platform-checks run default --scenario=RestartEntireMz --check=UpsertUnorderedKey
```
currently fails:
```
> SELECT * FROM upsert_unordered_key
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 113ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 49s 74s 78s
^^^ +++
2:1: error: non-matching rows: expected:
[["1", "fish4", "bdata"]]
got:
[["1", "fish2", "bdata"], ["1", "fish3", "bdata"], ["1", "fish4", "bdata"]]
Poor diff:
+ 1 fish2 bdata
+ 1 fish3 bdata
```

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

**Review by nrainer-materialize — COMMENTED** [review]
Issue + ignore?

**Comment by def-** [comment]
This is a correctness issue so I believe it should be fixed with near-release-blocker priority, I‘ll wait until a fix is up and then attach this commit to it.

**Comment by petrosagg** [comment]
I fixed the issue in this PR and added a testdrive test https://github.com/MaterializeInc/materialize/pull/29914

Do we also want to add a platform check? The testdrive one seems simpler to understand and control so I'll leave it up to you.

**Comment by def-** [comment]
Yes, we want both ideally. Testdrive only finds problems when a replica disappears/appears again. I'd prefer to also verify all the different scenarios that platform-checks offers.

I do also want to experiment with a Testdrive+disruptions mode which would use our large amount of existing testdrive tests to find similar issues to this.

**Pull request closed without merging**
