### PR TITLE
storage: ensure auctions integrity

### PR DESCRIPTION
**Pull request by mjibson**
Emit auctions before bids. This causes queries like:

```
subscribe (select count(distinct auctions.id), count(distinct bids.auction_id) from auctions, bids)
```

to never increment the second column before the first.

This will cause problems with any existing auction sources because the output order has changed, so there will be 1 or 2 auctions and their bids that appear twice or 0 times.

### Motivation

  * This PR fixes a previously unreported bug.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - Ensure the `AUCTION` load generator sources always emits auctions before bids. This may require dropping and recreating any such load generators to maintain consistent data.

### CODE REVIEW

**Review by guswynn — COMMENTED** [review]
The backward compatibility here is quite subtle:

When we restart an auction source, we skip records from this iterator up to the resumption frontier. Because `pending` now has a different order, it looks like this could cause inconsistency, but because we only move the resumption frontier whenever `pending` is empty, the resumption frontier will never be in between this different ordering, so things are safe.

with this in mind, this seems safe. But also, why is the subscribe giving this weird behavior if all the `pending` changes happen at the same ts?

**Comment by mjibson** [comment]
They don't happen at the same ts!

https://github.com/MaterializeInc/materialize/blob/0a9a12858ed4d1f18019662ac25b8b5f00723723/src/storage/src/source/generator/auction.rs#L157

So I think they are indeed unsafe.

**Comment by mjibson** [comment]
@guswynn Thoughts on merging this? I've added a release note about recreating those sources, but overall I don't think it matters much.

**Review by guswynn — APPROVED** [review]
@mjibson yeah its probably fine!

**Pull request merged**
