### PR TITLE
fix merge skew in copyright header lint

### PR DESCRIPTION
**Pull request by umanwizard**
Fixes https://buildkite.com/materialize/tests/builds/18215#dbc8bb44-220b-4d3a-a75c-b29da2318407

### CODE REVIEW

**Comment by benesch** [comment]
Seems like there's a spurious (?) change to the sqllogictest submodule?

**Comment by benesch** [comment]
Seems like there's a spurious (?) change to the sqllogictest submodule?

**Comment by umanwizard** [comment]
thanks, fixing

**Review by ruchirK — APPROVED** [review]
ty!

**Review by benesch — APPROVED** [review]

**Pull request merged**
