### PR TITLE
mzcompose: Print some service logs when wait-for-<service> fails

### PR DESCRIPTION
**Pull request by quodlibetor**
If a wait-for step fails, the most valuable thing to do is to check the logs of
the thing that we didn't find the port for, but experience shows that that
isn't necessarily obvious, and it can be tedious.

This implementation shows the most recent 20 lines of logs from a service that
mzcompose couldn't connect to. Even if it's not enough to debug the issue, it
at least is enough to point out that users should investigate those logs.

### CODE REVIEW

**Review by benesch — CHANGES_REQUESTED** [review]
I'm confused about the need for `get_service_logs`. Isn't that just `./mzcompose logs <SERVICE>`? Also might be simpler just to print a hint instructing users to try running that command.

**Comment by quodlibetor** [comment]
> Isn't that just `./mzcompose logs <SERVICE>`?

Ah, yeah.

> Also might be simpler just to print a hint instructing users to try running that command.

The most annoying time that this comes up (and the times that I've seen people ask about it) is in buildkite, when it's not possible to run the extra command. You have to know that the logs are in the artifacts tab.

**Comment by benesch** [comment]
> > Isn't that just `./mzcompose logs <SERVICE>`?
> 
> Ah, yeah.
> 
> > Also might be simpler just to print a hint instructing users to try running that command.
> 
> The most annoying time that this comes up (and the times that I've seen people ask about it) is in buildkite, when it's not possible to run the extra command. You have to know that the logs are in the artifacts tab.

Sure, but we could teach the hint to check `if BUILDKITE` and say "look in the artifact tab" instead of "try running `mzcompose logs`".

**Comment by quodlibetor** [comment]
I agree that would be simpler, but the thing implemented here is a much nicer failed-test experience, it always just shows you what went wrong. In my experience (historically with the ensure-stays-up step, and while testing this change) it's similar in experiential difference between a 1 second compile and a 30 second compile.

Would you like me to rip out the code and just provide the hint?

**Comment by benesch** [comment]
Well I’m confused. I think it’s fine to try to be more helpful than printing a hint since you’ve got to the trouble, but can’t we just shell out to `mzcompose logs` instead of reinventing it on top of `docker logs`?

**Comment by quodlibetor** [comment]
oh 🤦 [I switched to using docker-compose logs](https://github.com/MaterializeInc/materialize/pull/7772/files#diff-80670c527badfa360421797b7909f2781fb921542d209a58fcfcee17873e419fR422-R433), but forgot to actually delete the (now-unused) function that calls `docker logs`. I will delete it.

**Review by benesch — APPROVED** [review]

**Pull request merged**
