### PR TITLE
Downgrade k8s service watch errors to warnings

### LINKED ISSUE #16205: service watch error: error returned by apiserver during watch: too old resource version: 10131470...
Sentry Issue: [DATABASE-BACKEND-1V4](https://sentry.io/organizations/materializeinc/issues/3697919489/?referrer=github_integration)

```
service watch error: error returned by apiserver during watch: too old resource version: 101314707 (101343417): Expired
```

Filed by @antiguru

### PR DESCRIPTION
**Pull request by teskje**
Watching k8s services sometimes produces errors. The ones we have observed so far are:
 * ["too old resource version"](https://sentry.io/organizations/materializeinc/issues/3697919489/?project=6780145)
 * ["Connection refused"](https://sentry.io/organizations/materializeinc/issues/3728364110/?project=6780145)

In both cases, the errors seem to have been transient. The first ones [seem to be expected when watches are re-created](https://github.com/kubernetes/kubernetes/issues/22024#issuecomment-591814814), the second ones might be caused by networking issues.

There is not much value in showing transient k8s errors in Sentry, so this PR downgrades them to warnings.

### Motivation

  * This PR fixes a recognized bug.

Fixes #16205.

### Tips for reviewer

It is not clear whether there are any k8s errors that can be returned by the watcher API that are not transient and should be looked at by a human. An alternative, more defensive approach would be to only filter out the errors we know to not care about. The downside of this is that we will probably have to go back and add further exceptions in the future. Let me know if you still think it would be the right thing to do!

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

### CODE REVIEW

**Comment by teskje** [comment]
@tokenrove You were selected as a reviewer by fair dice roll. LMK if you'd like a call to discuss the PR!

**Comment by tokenrove** [comment]
> It is not clear whether there are any k8s errors that can be returned by the watcher API that are not transient and should be looked at by a human. An alternative, more defensive approach would be to only filter out the errors we know to not care about. The downside of this is that we will probably have to go back and add further exceptions in the future. Let me know if you still think it would be the right thing to do!

The latter approach would be my preference, especially since we have a sense of what errors we know we're comfortable ignoring, and it's a short list.  If we do this, and something truly unexpected happens, we at least have some way to notice it.

With that said, I don't know much about what other errors can be generated here, so it's possible this isn't a major concern.  For example, there are watcher errors and string parsing errors that can be generated -- do those ever indicate something an operator should triage immediately?

**Review by tokenrove — APPROVED** [review]
After discussion, it sounds like the downside of missing some errors here is probably relatively low, so I'm going to :+1: despite preferring explicit handling.  It also seems pretty cumbersome to figure out what set of errors to handle, and that may be brittle in the face of changes to kube.  If there's ever an incident where we realize we could have caught it earlier through surfacing errors here, we can revisit this code.

**Comment by teskje** [comment]
Thanks @tokenrove!

@umanwizard I'd be interested in you thoughts on downgrading these errors aggressively vs selectively.

**Comment by umanwizard** [comment]
I basically agree with what Julian wrote. The guidance (which we are not at yet, but we are supposed to be converging towards) is "error should page whoever is on-call for that component". By that standard I think these should be warnings, especially since `watch_services` is not used on any critical paths (AFAICT it just feeds diagnostic notices and `mz_cluster_replica_statuses`).

**Pull request merged**
