### PR TITLE
sinks,avro-ocf: create Avro Writer/open File only when needed

### PR DESCRIPTION
**Pull request by aljoscha**
All the writing of a Avro OCF sink happens from one worker. However,
before this change all workers would open a file, with the same file
name even.

This changes two things:
 - We make it explicit that we route all messages to one worker
 - We lazily create the Avro Writer when we receive the first messages

The type of avro_writer (Option<Result<>>) is a bit awkward, but it
reflects that fact that we try creating the writer once, and that can
result in an error. Before, we would try creating the writer outside the
sink function, and then inside check whether it was succesful.

The previous code would silently "continue" with the sink, only logging
and error once, when creating the writer failed. Now, we log an error
every time we try and receive the created writer, which will make the
error more noticeable in the logs.

Relates to #7132

### CODE REVIEW

**Comment by aljoscha** [comment]
@petrosagg I requested you because you can probably comment on how awkward the `Option<Result<>>` type is. :sweat_smile:

**Comment by petrosagg** [comment]
That's annoying indeed, but only because the surrounding context is one that doesn't support the `?` operator. In these cases I prefer to make a separate `Result` returning function and have a single `if let Err(e) = fallible_logic() { error!("{}", e) }`. I took a stab at it here https://github.com/petrosagg/materialize/blob/8d9b0c01f922a0f4728bddc56a075bf8167c2f6f/src/dataflow/src/sink/avro_ocf.rs

**Review by petrosagg — APPROVED** [review]
The code does what it says on the tin (i.e the PR description) so from that point of view it looks good to me. More generally, it looks like we're missing an error path for Sinks like the one we have for Sources. Ideally this code should somehow signal that the sink entered an error state that can be surfaced through SQL to the user

**Comment by aljoscha** [comment]
Yes! I'm just now writing up the design proposal for error handling in sinks. I think it will be my next step before I do the other bigger sink things I proposed.

**Comment by aljoscha** [comment]
Also, thanks for taking the time with the `fallible` thing! I will update the PR with this.

**Pull request merged**
