### PR TITLE
Support `EXPLAIN TIMESTAMP AS JSON`

### PR DESCRIPTION
**Pull request by umanwizard**
Title says it all

Adding @teskje as randomly-selected compute team reviewer

### Motivation

  * This PR fixes a previously unreported bug.

    `EXPLAIN TIMESTAMP AS JSON` silently did the same thing as `EXPLAIN TIMESTAMP`.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - Support `EXPLAIN TIMESTAMP AS JSON`

### CODE REVIEW

**Comment by umanwizard** [comment]
Example output:

```
~/c/materialize ❯❯❯ echo "EXPLAIN TIMESTAMP AS JSON FOR SELECT * FROM mz_internal.mz_cluster_replica_utilization;" | psql -At -h localhost -p 6875 -U materialize
{
  "determination": {
    "timestamp_context": {
      "TimelineTimestamp": [
        "EpochMilliseconds",
        1671063845130
      ]
    },
    "since": {
      "elements": [
        1671063844000
      ]
    },
    "upper": {
      "elements": [
        1671063845131
      ]
    },
    "largest_not_in_advance_of_upper": 1671063845130,
    "oracle_read_ts": 1671063845130
  },
  "sources": [
    {
      "name": "mz_catalog.mz_cluster_replicas (s289, storage)",
      "read_frontier": [
        1671063844000
      ],
      "write_frontier": [
        1671063845131
      ]
    },
    {
      "name": "mz_internal.mz_cluster_replica_metrics (s290, storage)",
      "read_frontier": [
        1671063844000
      ],
      "write_frontier": [
        1671063845131
      ]
    },
    {
      "name": "mz_internal.mz_cluster_replica_sizes (s291, storage)",
      "read_frontier": [
        1671063844000
      ],
      "write_frontier": [
        1671063845131
      ]
    }
  ]
}
```

**Review by teskje — COMMENTED** [review]
It looks like our usual approach to implementing `EXPLAIN AS JSON` is to impl the `DisplayJson` trait for the explain output type (in this case `TimestampExplanation`). This allows us to control the output format exactly and decouple it from the Rust representation. Is this something we should do here?

**Review by aalexandrov — APPROVED** [review]

**Comment by jkosh44** [comment]
Here's an issue with this feature for record purposes: https://github.com/MaterializeInc/materialize/issues/14947

**Comment by umanwizard** [comment]
@teskje I asked @aalexandrov , and he said we don't commit to the output of `EXPLAIN ... AS JSON` being stable, so I think it's okay to just go with whatever is serialized by serde here rather than using `DisplayJson`.

**Comment by umanwizard** [comment]
Some weird race condition happened with GitHub and my commit addressing Jan's comments didn't get added to the PR, even though I pushed it to my branch. I'll open a follow-up PR with those.

**Pull request merged**
