### PR TITLE
Unify Kafka source/sink parameter naming of consistency parameter

### LINKED ISSUE #6213: Finalize user options and terminology of Kafka exactly-once Sink
Right now, there are both the `consistency` option and the `exactly_once` option. You cannot have `exactly_once` without `consistency` but the other way round is allowed. 

Before releasing, we should think about the final set of options we want to provide and their naming.

### PR DESCRIPTION
**Pull request by aljoscha**
The commit messages have the details. Some things to note:

 - I changed `mz_kafka_sinks` to include the consistency topic
 - I added release notes but I'm not sure we want them because the features have been a bit under the radar for now

This closes #6213

### CODE REVIEW

**Review by elindsey — APPROVED** [review]
LGTM! Left one comment about the release notes

**Comment by cirego** [comment]
Apologies if this comment is off-topic to this PR. I noticed that we never actually documented the `consistency` parameter for sources and that lead me to the question of whether or not sinks are outputting Debezium style transactions or if they are emitting something else (CDCv2? I believe that's different from Debezium / BYO?). My reading of the code leaves me to believe that these are Debezium-style transaction messages.

However, [the messages](https://github.com/MaterializeInc/materialize/blob/4671e059bc490486aadb774dac6a78113a7fab8e/src/interchange/src/avro/encode.rs#L373) that we're emitting are not actually compatible with Debezium transactions because they are missing the `data_collections` field. This means that we cannot use this topic as a source of transaction data. [Here](https://github.com/MaterializeInc/materialize/blob/4671e059bc490486aadb774dac6a78113a7fab8e/src/coord/src/timestamp.rs#L358) is the relevant bit from `timestamp.rs`.

It seems to me that, if we want to name these topics the same, we may want to fixup the transaction metadata to include the `data_collections` field. Perhaps we should do this as part of this PR or perhaps we should open a new issue?

**Comment by aljoscha** [comment]
@cirego You're absolutely right! Here's the comment that explains why it's like this right now: https://github.com/MaterializeInc/materialize/blob/4671e059bc490486aadb774dac6a78113a7fab8e/src/interchange/src/avro/encode.rs#L26.

If it's ok, I would prefer tackling this in a separate issue (and PR) because this is mostly about parameter naming and how the parameter behaves. Although I can see the connection that you describe.

**Comment by cirego** [comment]
> @cirego You're absolutely right! Here's the comment that explains why it's like this right now:
> 
> https://github.com/MaterializeInc/materialize/blob/4671e059bc490486aadb774dac6a78113a7fab8e/src/interchange/src/avro/encode.rs#L26
> 
> .
> If it's ok, I would prefer tackling this in a separate issue (and PR) because this is mostly about parameter naming and how the parameter behaves. Although I can see the connection that you describe.

Thanks for pointing to that comment -- totally happy to address this independently from this PR!

**Comment by aljoscha** [comment]
I created https://github.com/MaterializeInc/materialize/issues/6834 (debezium: write data in sinks in a way that can be read by our sources)

**Pull request merged**
