### PR TITLE
rust: Upgrade to v1.81.0

### PR DESCRIPTION
**Pull request by ParkMyCar**
As it says on the tin!

### Motivation

Keep Rust up-to-date

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

### CODE REVIEW

**Review by def- — APPROVED** [review]
Rebased to check if nightly flakes are still from main or new in this PR.

**Review by def- — CHANGES_REQUESTED** [review]
FastPathLimit is reproducibly slower. On main it's green: https://buildkite.com/materialize/nightly/builds/9739
Two runs here both showed a ~40% slowdown: https://buildkite.com/materialize/nightly/builds/9744 & https://buildkite.com/materialize/nightly/builds/9748#_
```
NAME                                | TYPE            |      THIS       |      OTHER      |  UNIT  | THRESHOLD  |  Regression?  | 'THIS' is
--------------------------------------------------------------------------------------------------------------------------------------------------------
FastPathLimit                       | wallclock       |           0.305 |           0.225 |   s    |    10%     |    !!YES!!    | worse:  35.5% slower
FastPathLimit                       | wallclock       |           0.312 |           0.216 |   s    |    10%     |    !!YES!!    | worse:  44.4% slower
```
I'd consider this bad enough to potentially investigate before hurrying to merge. For context this is what the FastPathLimit scenario runs:

https://github.com/MaterializeInc/materialize/blob/a839d5cc7bb37aa0fb4a4750cc6ddd9b1d0d08e5/misc/python/materialize/feature_benchmark/scenarios/benchmark_main.py#L178-L202

**Comment by ParkMyCar** [comment]
rust `1.82.0` has been released

**Comment by ParkMyCar** [comment]
> FastPathLimit is reproducibly slower. On main it's green: https://buildkite.com/materialize/nightly/builds/9739 Two runs here both showed a ~40% slowdown: https://buildkite.com/materialize/nightly/builds/9744 & https://buildkite.com/materialize/nightly/builds/9748#_
> 
> ```
> NAME                                | TYPE            |      THIS       |      OTHER      |  UNIT  | THRESHOLD  |  Regression?  | 'THIS' is
> --------------------------------------------------------------------------------------------------------------------------------------------------------
> FastPathLimit                       | wallclock       |           0.305 |           0.225 |   s    |    10%     |    !!YES!!    | worse:  35.5% slower
> FastPathLimit                       | wallclock       |           0.312 |           0.216 |   s    |    10%     |    !!YES!!    | worse:  44.4% slower
> ```
> 
> I'd consider this bad enough to potentially investigate before hurrying to merge. For context this is what the FastPathLimit scenario runs:
> 
> https://github.com/MaterializeInc/materialize/blob/a839d5cc7bb37aa0fb4a4750cc6ddd9b1d0d08e5/misc/python/materialize/feature_benchmark/scenarios/benchmark_main.py#L178-L202

Good catch! Will follow up with this in v1.82.0

**Pull request closed without merging**
