### PR TITLE
Support nested structures in Avro (including arrays) by exposing them as Json

### LINKED ISSUE #2167: Support array types in Avro

### PR DESCRIPTION
**Pull request by umanwizard**
Potential users are actively being blocked by the lack of Avro arrays support, so I thought this semi hack is worth getting out in the short term.

As @benesch pointed out, this may risk backward-incompatibility, since we will at some point have better support for the actual Postgres Array type. I thought that was worth risking, since we are already doing the same thing for Protobuf sources, so we might as well unify our approach for now. But please, if there are concerns let's discuss.

Fixes #2167

### CODE REVIEW

**Comment by rjnn** [comment]
LGTM on the risking backwards incompatibility part from a product perspective

**Comment by benesch** [comment]
> LGTM on the risking backwards incompatibility part from a product perspective

This makes me really nervous. I don't think we should have done this for protobufs, and I don't think we should do it here. It might even be possible to fix it for protobufs now, but as soon as someone starts depending on this behavior, it's going to be very difficult to change.

We need row types and array types. Can we find time for someone to work on those instead?

**Comment by umanwizard** [comment]
@rjnn , would it be possible for people to use the Avro json type (which we already support as of a few days ago) -- that would probably alleviate Nikhil's concerns.

Or are they not able to change the schema they're currently using?

**Comment by rjnn** [comment]
Yes that would be fine.

**Comment by jamii** [comment]
> We need row types and array types.

I could take them after finishing the explain changes.

**Comment by umanwizard** [comment]
Example of record type with Json field:

```
{
    "name": "row",
    "type": "record",
    "fields": [
        {
            "name": "a",
            "type": "long"
        },
        {
            "name": "b",
            "type": "long"
        },
        {
            "name": "json",
            "type": {
                "connect.name": "io.debezium.data.Json",
                "type": "string"
            }
        }
    ]
}
```

**Pull request closed without merging**
