### PR TITLE
coord: fix swapped log message args

### LINKED ISSUE #6088: "Ignoring decrease in partitions" error is malformed, new and old partition counts are swapped
### What version of Materialize are you using?

```
v0.7.2-dev (5c05c16fa)
```

### What was the issue?

In ```timestamp.rs```:

```
                    cmp::Ordering::Less => {
                        error!(
                            "Ignoring decrease in partitions (from {} to {}) for topic {} (source {})",
                             new_partition_count, current_partition_count, c.topic, c.id,
                        );
                    }
```

```new_partition_count``` and ```current_partition_count``` are misplaced.

Also, how can something be both an ```ERROR``` and be "ignored".

### Is the issue reproducible? If so, please provide reproduction instructions.

Run testdrive against materialize and in the log you will see errors like:

```
2021-03-16T09:12:05.607685Z ERROR coord::timestamp: Ignoring decrease in partitions (from 0 to 3) for topic testdrive-non-dbz-data-varying-partition-3567593364 (source u71)    
```

it should be "from 3 to 0".

### PR DESCRIPTION
**Pull request by danhhz**
Also downgrade it from ERROR to INFO since it's not actionable.

Closes #6088

### CODE REVIEW

**Comment by danhhz** [comment]
Draft because I didn't immediately see where to stick a regression test. @ruchirK any pointers?

**Comment by ruchirK** [comment]
I think its fine to merge without regression tests here. Afaik we don't have any regression tests for specific log output at the moment

**Comment by ruchirK** [comment]
all the test failures you're running into seem entirely unrelated

**Review by ruchirK — APPROVED** [review]
lgtm!

**Comment by ruchirK** [comment]
I'm going to move this out of draft status and trigger a rebuild to see if that resolves the test issue but I am not optimistic because it looks like a few other prs have run into this as well.

**Review by benesch — APPROVED** [review]

**Comment by danhhz** [comment]
Thanks for the reviews!

**Pull request merged**
