### PR TITLE
ci: junit.xml content: include error details (part 1)

### PR DESCRIPTION
**Pull request by nrainer-materialize**
This is work towards https://github.com/MaterializeInc/materialize/issues/22690.

junit.xml of platform checks are the changes **(updated):**
```
		<testcase name="comment.py" time="40.914175" classname="Checks + restart of environmentd & storage clusterd (5)">
			<error type="error" message="Executing misc/python/materialize/checks/all_checks/comment.py:24 failed">^^^ +++
2:1: error: preparing query failed: db error: ERROR: type &quot;into&quot; does not exist: ERROR: type &quot;into&quot; does not exist
     |
   1 | 
   2 | &gt; CREATE TYPE comment_type AS (x text, y int, z into)
     | ^
+++ !!! Error Report
1 errors were encountered during execution
source: /Users/nrainer/Workspaces/mz-repo/misc/python/materialize/checks/all_checks/comment.py:24
</error>
		</testcase>

```

Build with a failure to check how it looks in Buildkite: https://buildkite.com/materialize/tests/builds/73337

The changes might need to be extended for further patterns / jobs (as follow-up when observed).

### CODE REVIEW

**Review by def- — APPROVED** [review]
Based on https://buildkite.com/materialize/tests/builds/73337, the name of the error messages should be changed, currently it's just `platform-checks`, maybe we can use the `Checks without restart or upgrade` from buildkite's env variables for that.

In the `Executing /var/lib/buildkite-agent/builds/buildkite-15f2293-i-055aaac7a09b73a81-1/materialize/tests/misc/python/materialize/checks/all_checks/comment.py:24 failed` message I would change it to `Executing misc/python/materialize/checks/all_checks/comment.py:24 failed`.

**Comment by nrainer-materialize** [comment]
> Based on https://buildkite.com/materialize/tests/builds/73337, the name of the error messages should be changed, currently it's just `platform-checks`, maybe we can use the `Checks without restart or upgrade` from buildkite's env variables for that.

Great idea 👍 

> The `workflow-default` also doesn't help much I think, could we put the name of the actually failing check in there, so `Comment` in this case?

I was not that convinced at the beginning since it does not really match the junit structure but still gave it a try.

> In the `Executing /var/lib/buildkite-agent/builds/buildkite-15f2293-i-055aaac7a09b73a81-1/materialize/tests/misc/python/materialize/checks/all_checks/comment.py:24 failed` message I would change it to `Executing misc/python/materialize/checks/all_checks/comment.py:24 failed`.

Yeah, absolutely.

**Comment by def-** [comment]
Do you have a new demo to see if this works?

**Comment by nrainer-materialize** [comment]
> Do you have a new demo to see if this works?

I haven't triggered one but can do so.

Here we go: https://buildkite.com/materialize/tests/builds/73396

**Review by def- — APPROVED** [review]
I think instead of `comment.py` showing the `Comment` class would be nicer, but still a huge improvement over the previous state.

**Review by philip-stoev — APPROVED** [review]
It is indeed a great improvement, so you are welcome to merge this as it is, but I think the hierarchy of things needs to be different.

Right now you have:
```
<testsuite name="platform-checks">
<testcase name="comment.py" classname="Checks + restart of environmentd & storage clusterd (5)">
```

And I think it needs to be:
```
<testsuite id="checks-restart-environmentd-clusterd-storage" name="Checks + restart of environmentd & storage clusterd (5)">
<testcase id="Comment" name="comment.py:Comment" classname="Comment">
```
or something along those lines.

**Comment by nrainer-materialize** [comment]
Further adjustments will be needed for other build jobs (e.g., Postgres CDC); they will be done in a follow-up PR.

**Comment by nrainer-materialize** [comment]
> It is indeed a great improvement, so you are welcome to merge this as it is, but I think the hierarchy of things needs to be different.
> 
> Right now you have:
> 
> ```
> <testsuite name="platform-checks">
> <testcase name="comment.py" classname="Checks + restart of environmentd & storage clusterd (5)">
> ```
> 
> And I think it needs to be:
> 
> ```
> <testsuite id="checks-restart-environmentd-clusterd-storage" name="Checks + restart of environmentd & storage clusterd (5)">
> <testcase id="Comment" name="comment.py:Comment" classname="Comment">
> ```
> 
> or something along those lines.

I will see what I can do. `testsuite` does not seem to have an `id` property and retrieving the class name of the check won't be that easy...

**Pull request merged**
