### PR TITLE
compute: drop `CollectionState` eagerly

### PR DESCRIPTION
**Pull request by teskje**
The dropping of collections happens in two phases, to ensure that dataflow sources can stop reading from the inputs before we announce the relinquishing of their read holds to the controller. Previously this was done by keeping the `CollectionState` alive until `report_dropped_collections`, so that method could inspect the reported frontiers. Keeping the `CollectionState` alive also meant keeping its `CollectionLogging` alive.

This made it possible for two `CollectionLogging` instances to be alive for the same collection after reconciliation. When reconciliation drops and reinstalls a collection, it makes sure that the `AllowCompaction` command is handled before the `CreateDataflow` command. Handling `AllowCompaction` results in a `drop_collection` call, but intentionally not in a `report_dropped_collections` call (that is deferred until after the next Timely step), so the old `CollectionLogging` instance stays alive. Then handling `CreateDataflow` creates a new `CollectionLogging` instance for the same collection ID. Creation and deletion of `CollectionLogging` instances causes emission of log events, and the logging dataflows assume that collection IDs are unique, so having two `CollectionLogging` instances for the same ID alive corrupts the logging dataflow state.

The fix is to make sure `drop_collection` also drops the `CollectionLogging` instance of the collection, as it already does with sink tokens. This commit does that, but to prevent issues like this from reappearing when we add more fields to `CollectionState`, it also introduces a separate `DroppedCollection` type that only holds the state required by `report_dropped_collections`. This forces us to be explicit about which fields we want to survive `drop_collection` and lets us make sure that none of them holds onto any shared resources.

### Motivation

  * This PR fixes a recognized bug.

Fixes https://github.com/MaterializeInc/materialize/issues/27915

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - N/A

### CODE REVIEW

**Review by ggevay — APPROVED** [review]
LGTM (but maybe wait for @antiguru's review)

**Comment by bosconi** [comment]
@antiguru could we get your review on this too?

**Review by antiguru — APPROVED** [review]
Looks good!

**Comment by teskje** [comment]
TFTRs!

**Pull request merged**
