### PR TITLE
Add Kinesis information to Materialize CREATE SOURCE docs

### PR DESCRIPTION
**Pull request by JLDLaughlin**
@sploiselle I noticed we'll have to update the `CREATE SOURCE` diagram as well, I can do that if you let me know how! Also, very open to any wording suggestions.

### CODE REVIEW

**Comment by sploiselle** [comment]
@JLDLaughlin Whoops! I had an open PR to refactor this documentation that I just merged. Let me graft this onto that. Since this is on your fork, I'll need to open a new PR with this work--hope that isn't too offensive.

**Comment by JLDLaughlin** [comment]
@sploiselle that works for me! should I close this PR?

**Comment by sploiselle** [comment]
@JLDLaughlin will close it when I open the new one!

**Comment by sploiselle** [comment]
Moving work over to #2387

**Pull request closed without merging**
