### PR TITLE
persist: fix assortment of usability issues

### PR DESCRIPTION
**Pull request by aljoscha**
### Testing

- [no] This PR has adequate test coverage / QA involvement has been duly considered.

### CODE REVIEW

**Comment by aljoscha** [comment]
I noticed the one about `Id` when trying to update the example to use file blob + sqlite consensus. But I don't think we want to expose `UUID` like IDs to users, right?

**Comment by aljoscha** [comment]
> What's the motivation for the UUID one?

Just being able to use the API from simple examples. But I'm also wondering how the API should be used in production. The only way of `open`'ing a shard is via `Id`, and the only way of getting an `Id` is via `Id::new()` which mints a random `UUID`. Or I'm very confused, which is not unlikely. 😅

**Comment by danhhz** [comment]
Ah! I think the story I was imagining there is the Serialize/Deserialize impls?

**Comment by aljoscha** [comment]
Ah ok, and then the user of the API would have to write down a `<shard name> -> Id` mapping to be able to open them again.

But that's a bit complicated for spinning up an example. 😅

**Comment by danhhz** [comment]
> Ah ok, and then the user of the API would have to write down a `<shard name> -> Id` mapping to be able to open them again.

Yeah, but I think in real world use they won't even have a name. The storage collection might have a name, but a storage collection is like a map from `<ts> -> <rendition>` and then a `rendition` is something like an array of persist shard Ids.

> But that's a bit complicated for spinning up an example. 😅

I'm sympathetic, but I'm not quite following! Can you expand on this? Concretely, I'd imagine for an example we'd use Copy?

**Comment by aljoscha** [comment]
I was thinking along the lines of an example where you do `./source_pipeline_example --shard-id the-shard`. And you can kill the process and restart to observe it.

Or for benchmarking, where we might want to start concurrent writer processes on different machines à la `./benchmark-writer --foo --bar --shard-id <...> --num-messages ...` and then also start readers à la `./benchmark-reader --foo --bar --shard-id <...> --expected-num-messages ..`

But those can be worked around by creating an `Id` and serializing it, and then passing that around as a parameter.

**Comment by aljoscha** [comment]
((I removed the last commit, so that we can merge the good changes. Could you please approve that?))

**Review by danhhz — APPROVED** [review]
Yeah of course! These two commits lgtm.

Oh I see now! Okay, for the id bit, how about this: instead of something like Serialize+Deserialize or Codec for ShardId, we add a `FromStr` impl and use the output of `Display` as a shareable format?

**Pull request merged**
