### PR TITLE
bench: aggregations over decimals

### PR DESCRIPTION
**Pull request by sploiselle**
A very simple test of an aggregation over a single decimal column; this will help us understand how much the `rust-dec`-backed decimal implementation degrades performance and increases memory usage.

This supersedes #6658 and #6643

### CODE REVIEW

**Review by cirego — APPROVED** [review]
Looks great to me!

We need to figure out why the smoke test failed in CI.

**Comment by cirego** [comment]
It looks like this failed with the following error message:

```
CREATE SOURCE
psql:/data/aggregation_views.sql:21: ERROR:  column name "OuterRecord" is ambiguous
psql:/data/aggregation_views.sql:23: ERROR:  unknown catalog item 'aggregationtest'
$ docker wait 15c81efce39dd2dcf9575085d9e51cb288a90ebdba2f625bad69ffba79c26b47
```

**Comment by cirego** [comment]
I'm able to reproduce this locally:

```
[chris-work:~/materialize/materialize:(dec-agg-test[|])] docker logs aggregations_create-views_run_f4dc208bfa72 
CREATE SOURCE
psql:/data/aggregation_views.sql:21: ERROR:  column name "OuterRecord" is ambiguous
psql:/data/aggregation_views.sql:23: ERROR:  unknown catalog item 'aggregationtest'
```

**Comment by cirego** [comment]
I also see `kgen` exiting with the following errors:

```
Spawning 4 generator processes, writing 25000 messages each
thread 'main' panicked at 'max value of 1000000000 exceeds value expressable with precision 15', src/kafka-util/src/bin/kgen.rs:294:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'max value of 1000000000 exceeds value expressable with precision 15', src/kafka-util/src/bin/kgen.rs:294:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'max value of 1000000000 exceeds value expressable with precision 15', src/kafka-util/src/bin/kgen.rs:294:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'max value of 1000000000 exceeds value expressable with precision 15', src/kafka-util/src/bin/kgen.rs:294:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
0/4 processes finished: pid=7 returncode=101
1/4 processes finished: pid=8 returncode=101
2/4 processes finished: pid=9 returncode=101
3/4 processes finished: pid=10 returncode=101
```

**Comment by cirego** [comment]
I think the "OuterRecord" error may be a red-herring, when we really should have exited with error when kgen failed.

Once #6675 lands, we should pull those improvements into this benchmark too!

**Comment by sploiselle** [comment]
@cirego tysm for checking into this; the root of the problem was just an inverted inequality that caused everything else to topped down around it. re: `UPSERT` vs. append-only envelope, I want the ability to control the total size of the view to examine memory consumption of the refactor. I guess it's possible to also throttle this with the number of messages we send, so idk––going to go with `UPSERT` because it also feels like a slightly more realistic.

**Pull request merged**
