### PR TITLE
Second pass of `Normalize` transform

### PR DESCRIPTION
**Pull request by aalexandrov**
Still WIP, I'll create a tracking issue and fill in the rest of the sections here tomorrow.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - There should be no user-facing behavior changes, but we should be careful to assert this with some tests before merging this PR.

### CODE REVIEW

**Comment by aalexandrov** [comment]
Currently, the tests pass because the following query

```sql
EXPLAIN SELECT bound, (
     WITH MUTUALLY RECURSIVE
         numbers (n int) as (
             VALUES (1)
             UNION ALL
             (
                 WITH rebound AS (SELECT * FROM numbers)
                 SELECT distinct t1.n + t2.n AS n
                 FROM rebound AS t1, rebound AS t2
                 WHERE t1.n <= bound AND t2.n <= bound
             )
         )
     SELECT count(*) FROM numbers
 )
 FROM (
     SELECT generate_series AS bound FROM generate_series(1, 10)
 );
```
runs into an infinite loop at the `monotonic_flag.apply` in `optimize_dataflow_monotonic` with the following plan.

```text
Return
  Project (#0, #2)
    Map (#1)
      Project (#0, #2)
        Join on=(#0 = #1) type=differential
          implementation
            %1[#0] » %0:l0[#0]KA
          ArrangeBy keys=[[#0]]
            Get l0
          ArrangeBy keys=[[#0]]
            Project (#0, #2)
              Join on=(#0 = #1) type=differential
                implementation
                  %1[#0] » %0:l1[#0]UKA
                ArrangeBy keys=[[#0]]
                  Get l1
                ArrangeBy keys=[[#0]]
                  Union
                    Get l6
                    CrossJoin type=differential
                      implementation
                        %0[×] » %1[×]UA
                      ArrangeBy keys=[[]]
                        Project (#0)
                          Join on=(#0 = #1) type=differential
                            implementation
                              %0[#0] » %1:l2[#0]UKA
                            ArrangeBy keys=[[#0]]
                              Union
                                Negate
                                  Distinct group_by=[#0]
                                    Project (#0)
                                      Get l6
                                Distinct group_by=[#0]
                                  Get l2
                            ArrangeBy keys=[[#0]]
                              Get l2
                      ArrangeBy keys=[[]]
                        Constant
                          - (null)
With Mutually Recursive
  cte l6 =
    Union
      Get l5
      Map (error("more than one record produced in subquery"))
        Project (#0)
          Filter (#1 > 1)
            Reduce group_by=[#0] aggregates=[count(*)]
              Project (#0)
                Get l5
  cte l5 =
    Union
      Get l4
      CrossJoin type=differential
        implementation
          %0[×] » %1[×]UA
        ArrangeBy keys=[[]]
          Project (#0)
            Join on=(#0 = #1) type=differential
              implementation
                %0[#0] » %1:l2[#0]UKA
              ArrangeBy keys=[[#0]]
                Union
                  Negate
                    Distinct group_by=[#0]
                      Project (#0)
                        Get l4
                  Distinct group_by=[#0]
                    Get l2
              ArrangeBy keys=[[#0]]
                Get l2
        ArrangeBy keys=[[]]
          Constant
            - (0)
  cte l4 =
    Reduce group_by=[#0] aggregates=[count(*)]
      Project (#0)
        Get l3
  cte l3 =
    Union
      FlatMap wrap1(1)
        Get l2
      Distinct group_by=[#0, #1]
        Project (#0, #3)
          Map ((#1 + #2))
            Filter true AND ((#1 <= #0) AND (#2 <= #0))
              Project (#0, #1, #3)
                Join on=(#0 = #2) type=differential
                  implementation
                    %1:l3[#0] » %0:l3[#0]KAf
                  ArrangeBy keys=[[#0]]
                    Filter (#1 <= #0)
                      Get l3
                  ArrangeBy keys=[[#0]]
                    Filter (#1 <= #0)
                      Get l3
  cte l2 =
    Distinct group_by=[#0]
      Get l1
  cte l1 =
    Distinct group_by=[#0]
      Get l0
  cte l0 =
    FlatMap generate_series(1, 10, 1)
      Constant
        - ()
```

**Comment by philip-stoev** [comment]
Item No 1. In this branch, a `IS NOT NULL` filter appears. As far as I was able to reason about the query, the filter is legit. Note that the diff only occurs if the `AND TRUE` predicate is present.


```
EXPLAIN SELECT
  FROM pk2 a1
  LEFT  JOIN t1 a2
    ON a2 .f2 + a1 .f2 = a2 .f1 + a1 .f2
 WHERE a1 .f2 > a2 .f1
   AND TRUE ;

--- 6875.out	2023-02-09 10:09:28.411056107 +0100
+++ 16875.out	2023-02-09 10:09:28.455057036 +0100
@@ -1,14 +1,13 @@
 Explained Query:
   Project ()
     Filter (#0 > #1)
       Join on=((#1 + #0) = (#2 + #0)) type=differential
         ArrangeBy keys=[[]]
           Project (#1)
             Get materialize.public.pk2
         ArrangeBy keys=[[]]
-          Filter (#0) IS NOT NULL
             Get materialize.public.t1
 
 Used Indexes:
   - materialize.public.t1i1
```

DDL:

```
CREATE SCHEMA public;
CREATE TABLE t1 (f1 DOUBLE PRECISION, f2 DOUBLE PRECISION NOT NULL);
CREATE INDEX t1i1 ON t1(f1);
CREATE INDEX t1i2 ON t1(f2, f1);
CREATE TABLE t2 (f1 DOUBLE PRECISION, f2 DOUBLE PRECISION NOT NULL);
CREATE INDEX t2i1 ON t2(f1);
CREATE INDEX i2i2 ON t2(f2, f1);
CREATE TABLE t3 (f1 DOUBLE PRECISION, f2 DOUBLE PRECISION NOT NULL);
CREATE INDEX t3i1 ON t2(f1);
CREATE INDEX i3i2 ON t2(f2, f1);
CREATE MATERIALIZED VIEW pk1 AS SELECT DISTINCT ON (f1) f1 , f2 FROM t1 WHERE f1 IS NOT NULL AND f2 IS NOT NULL;
CREATE MATERIALIZED VIEW pk2 AS SELECT DISTINCT ON (f1) f1 , f2 FROM t2 WHERE f1 IS NOT NULL AND f2 IS NOT NULL;
CREATE MATERIALIZED VIEW pk3 AS SELECT DISTINCT ON (f1) f1 , f2 FROM t3 WHERE f1 IS NOT NULL AND f2 IS NOT NULL;
```

**Comment by philip-stoev** [comment]
Item No 2. This query is a bit degenerate, but there are two differences as compared to the parent commit:
- one of the Filters contained 2 conditions
- another Filter references a different column (the two columns have an equality between them). So the parent commit was able to insert an extra Project, which I assume was a good thing
```
EXPLAIN SELECT
  FROM pk1
  LEFT  JOIN t1 a2 USING (f1 , f2)
 WHERE f2 = f1
   AND a2 .f2 < pk1.f2 ;;

--- 6875.out	2023-02-09 10:13:37.728316429 +0100
+++ 16875.out	2023-02-09 10:13:37.764317188 +0100
@@ -1,16 +1,17 @@
 Explained Query:
   Project ()
-    Filter (#0 = #3) AND (#3 < #1)
-      Join on=(#0 = #2) type=differential
+    Filter (#0 = #2) AND (#2 < #0)
+      Join on=(#0 = #1) type=differential
         ArrangeBy keys=[[#0]]
-          Filter (#0 = #1)
+          Project (#0)
+            Filter (#0 = #1) AND (#0 < #1)
             Get materialize.public.pk1
         ArrangeBy keys=[[#0]]
           Get materialize.public.t1
 
 Source materialize.public.pk1
-  filter=((#0 = #1))
+  filter=((#0 = #1) AND (#0 < #1))
 
 Used Indexes:
   - materialize.public.t1i1
```

**Comment by philip-stoev** [comment]
Item No # 3. I guess this is an improvement -- a column is detected as never being NULL, so COUNT(col) is replaced with COUNT(*):

```
EXPLAIN SELECT AVG (a1 .f1)
  FROM t2 a1
  LEFT  JOIN pk1 a2
    ON a2 .f1 + a1 .f1 = a2 .f2
 WHERE a2 .f2 < a2 .f1 + a1 .f1
   AND TRUE ;;

--- 6875.out	2023-02-09 10:21:36.142410470 +0100
+++ 16875.out	2023-02-09 10:21:36.186411398 +0100
@@ -1,31 +1,31 @@
 ...
-      Reduce aggregates=[sum(#0), count(*)]
+      Reduce aggregates=[sum(#0), count(#0)]
```

**Comment by philip-stoev** [comment]
Item No 4. The way I read this, in the parent commit, the filter was pushed to both sides of the join, but not anymore:

```
EXPLAIN SELECT
  FROM pk1 a1
  LEFT  JOIN pk1 a2
    ON TRUE
 WHERE TRUE
   AND a1 .f2 = a2 .f2
   AND a1 .f2 >= a1 .f2 ;

--- 6875.out	2023-02-09 10:26:56.421049932 +0100
+++ 16875.out	2023-02-09 10:26:56.465050797 +0100
@@ -1,11 +1,16 @@
 Explained Query:
+  Return
   Project ()
     Join on=(#0 = #1) type=differential
+        Get l0
+        Get l0
+  With
+    cte l0 =
       ArrangeBy keys=[[#0]]
         Project (#1)
           Filter (#1 >= #1)
             Get materialize.public.pk1
-      ArrangeBy keys=[[#0]]
-        Project (#1)
-          Get materialize.public.pk1
+
+Source materialize.public.pk1
+  filter=((#1 >= #1))
```

**Comment by philip-stoev** [comment]
Item No 5. An implicit `IS NOT NULL` filter is lost here:

```
EXPLAIN SELECT
  FROM pk2 AS a1
  LEFT JOIN t1 AS a2 USING (f2)
 WHERE a1 . f1 + a2 . f2 + a2 . f1 = a2 . f2
   AND a1 . f2 = a2 . f2 ;

--- 6875.out	2023-02-09 10:33:02.684381334 +0100
+++ 16875.out	2023-02-09 10:33:02.724382146 +0100
@@ -1,11 +1,12 @@
 Explained Query:
   Project ()
     Join on=(eq(#1, #3, ((#0 + #1) + #2))) type=differential
       ArrangeBy keys=[[#1]]
         Get materialize.public.pk2
       ArrangeBy keys=[[#1]]
+        Filter (#0) IS NOT NULL
         Get materialize.public.t1
 
 Used Indexes:
   - materialize.public.t1i1
```

**Comment by philip-stoev** [comment]
Item No6 .Here an opportunity to push a filter all the way to the source has been lost:

```
EXPLAIN SELECT
  FROM pk1
  LEFT  JOIN pk2 a2 USING (f2 , f1)
 WHERE pk1.f2 <= a2 .f2
   AND f1 = f2 ;;

--- 6875.out	2023-02-09 10:36:48.248983326 +0100
+++ 16875.out	2023-02-09 10:36:48.288984147 +0100
@@ -1,16 +1,17 @@
 Explained Query:
   Project ()
-    Filter (#1 <= #3)
-      Join on=(#0 = #2) type=differential
+    Join on=(#0 = #1) type=differential
         ArrangeBy keys=[[#0]]
-          Filter (#0 = #1)
+        Project (#0)
+          Filter (#0 = #1) AND (#1 <= #0)
             Get materialize.public.pk1
         ArrangeBy keys=[[#0]]
-          Filter (#0 = #1)
+        Project (#0)
+          Filter (#0 = #1) AND (#0 <= #1)
             Get materialize.public.pk2
 
 Source materialize.public.pk1
-  filter=((#0 = #1))
+  filter=((#0 = #1) AND (#1 <= #0))
 Source materialize.public.pk2
-  filter=((#0 = #1))
+  filter=((#0 = #1) AND (#0 <= #1))
```

**Comment by philip-stoev** [comment]
Item No 7 . Another opportunity to propagate a Filter has been lost here:

```
EXPLAIN SELECT
  FROM pk1 a1
 RIGHT  JOIN pk2 a2
    ON a1 .f2 > a1 .f2
 WHERE TRUE
   AND a2 .f1 = a1 .f2 ;

--- 6875.out	2023-02-09 10:39:48.348686060 +0100
+++ 16875.out	2023-02-09 10:39:48.396687050 +0100
@@ -1,14 +1,17 @@
 Explained Query:
   Project ()
     Join on=(#0 = #1) type=differential
       ArrangeBy keys=[[#0]]
         Project (#1)
           Filter (#1 > #1)
             Get materialize.public.pk1
       ArrangeBy keys=[[#0]]
         Project (#0)
+          Filter (#0 > #0)
           Get materialize.public.pk2
 
 Source materialize.public.pk1
   filter=((#1 > #1))
+Source materialize.public.pk2
+  filter=((#0 > #0))
```

**Comment by aalexandrov** [comment]
## Item 01
- The `Filter ((#2 + #1)) IS NOT NULL` is first added by the `predicate_pushdown` transform.
- This is a consequence of `(#2 + #1)` appearing in an equality predicate.
- I am not quite sure why the other members of this equivalence class are not constrained by a similar filter.
- After that, at some point `fusion` canonicalizes the predicate and turns it into `Filter (#1) IS NOT NULL AND (#2) IS NOT NULL`.
- This filter is then pushed through the join and for some reason one of the conjuncts is lost because it is deemed redundant based on the inferred schema.

Attached traces: [Item01.zip](https://github.com/MaterializeInc/materialize/files/10700588/Item01.zip).

**Comment by philip-stoev** [comment]
Item No 8. This degenerate query is deemed a constant in the parent commit, but not in this PR:

```
EXPLAIN SELECT *
  FROM lineitem
  JOIN orders_pk
    ON (TRUE)
  LEFT JOIN customer
    ON (c_acctbal <> o_totalprice)
 WHERE l_commitDATE = o_orderdate
   AND c_acctbal = o_totalprice ;

--- 6875.out	2023-02-10 08:25:51.862116600 +0100
+++ 16875.out	2023-02-10 08:25:51.902117317 +0100
@@ -1,20 +1,3 @@
-Explained Query:
-  Project (#0..=#19, #11, #21..=#29, #19, #31, #32)
-    Join on=(#11 = #20 AND #19 = #30) type=differential
-      ArrangeBy keys=[[#11]]
-        Filter (#11) IS NOT NULL
-          Get materialize.public.lineitem
-      ArrangeBy keys=[[#3]]
-        Filter (#4) IS NOT NULL AND (#3 != #3)
-          Get materialize.public.orders_pk
-      ArrangeBy keys=[[#5]]
-        Filter (#5 != #5)
-          Get materialize.public.customer
-
-Source materialize.public.orders_pk
-  filter=((#3 != #3) AND (#4) IS NOT NULL)
-
-Used Indexes:
-  - materialize.public.pk_customer_custkey
-  - materialize.public.pk_lineitem_orderkey_linenumber
+Explained Query (fast path):
+  Constant <empty>
```

**Comment by philip-stoev** [comment]
Item No 9. The Filter is not pushed to both sides of the join:

```
EXPLAIN SELECT
  FROM lineitem
  LEFT  JOIN orders_pk
    ON TRUE
 WHERE l_shipDATE = o_orderdate
   AND l_shipDATE < '1995-06-05' ;

--- 6875.out	2023-02-10 08:36:33.561599858 +0100
+++ 16875.out	2023-02-10 08:36:33.601600574 +0100
@@ -1,18 +1,18 @@
 Explained Query:
   Project ()
     Join on=(#0 = #1) type=differential
       ArrangeBy keys=[[#0]]
         Project (#10)
           Filter (#10 < 1995-06-05)
             Get materialize.public.lineitem
       ArrangeBy keys=[[#0]]
         Project (#4)
-          Filter (#4) IS NOT NULL
+          Filter (#4 < 1995-06-05)
             Get materialize.public.orders_pk
 
 Source materialize.public.orders_pk
-  filter=((#4) IS NOT NULL)
+  filter=((#4 < 1995-06-05))
 
 Used Indexes:
   - materialize.public.pk_lineitem_orderkey_linenumber
```

**Comment by philip-stoev** [comment]
Item No 10 . I think this is the same as No 9 , but with an expression. It is also weird that the `AND TRUE` is required for the different plan to show up:

```
EXPLAIN SELECT
  FROM orders_pk
 RIGHT  JOIN customer
    ON c_acctbal = o_totalprice
 WHERE c_acctbal - o_totalprice = 0
   AND TRUE ;;

--- 6875.out	2023-02-10 08:40:38.582785304 +0100
+++ 16875.out	2023-02-10 08:40:38.622786143 +0100
@@ -1,18 +1,18 @@
 Explained Query:
   Project ()
     Join on=(#0 = #1) type=differential
       ArrangeBy keys=[[#0]]
         Project (#3)
           Filter (0 = (#3 - #3))
             Get materialize.public.orders_pk
       ArrangeBy keys=[[#0]]
         Project (#5)
-          Filter (0 = (#5 - #5))
+          Filter (#5) IS NOT NULL
             Get materialize.public.customer
 
 Source materialize.public.orders_pk
   filter=((0 = (#3 - #3)))
 
 Used Indexes:
   - materialize.public.pk_customer_custkey
```

**Comment by philip-stoev** [comment]
Schema for the TPC-*-like items above:

https://gist.github.com/philip-stoev/23def65ad679f5c02f5e5f24bd38bcdb

**Review by philip-stoev — APPROVED** [review]
Apologies for filing that many individual queries to check -- reading through them again it seems that most are duplicates of each other. I guess "No 9" is an actual realistic query to look at , you can totally skip over all the queries with impossible or degenerate conditions.

**Comment by aalexandrov** [comment]
Looking at Item no. 9 at the moment, and it seems that in the proposed pipeline `predicate_pushdown` might be running too early  (this is the first transform that changes something after the initial `normalize`). Compared to `main` (`534cdc4db`), I see that `#10 < 1995-06-05` is pushed down before some simplifications are being made.

For reference, here is the current `logical` pipeline again:

https://github.com/aalexandrov/materialize/blob/87ec94d8061d9963469757c783f6dcdcca2106bc/src/transform/src/lib.rs#L422-L501

The problem is that at the point in time where we first `predicate_pushdown` the join between the two inputs is still a cross join and we can only push one of the two conjuncts of the original filter through the `l0` binding:
```text
With
  cte l0 =
    CrossJoin
      Filter (#10 < 1995-06-05)
        Get materialize.public.lineitem
      Get materialize.public.orders_pk
```

I managed to solve this by moving `ColumnKnowledge` before `PredicatePushdown` in their fixpoint loop.

**Comment by aalexandrov** [comment]
Looking at Item no. 9 it seems that we are not worse, as
```
Filter (0 = (#5 - #5))
```
entails
```
Filter (#5) IS NOT NULL
```

**Comment by philip-stoev** [comment]
> Looking at Item no. 10 it seems that we are not worse, as

Yes sorry my fault, `Filter (0 = (#5 - #5))` is the better one yes.

**Comment by aalexandrov** [comment]
[This comment](https://github.com/MaterializeInc/materialize/pull/19010#issuecomment-1527107915) might also be relevant for this PR.

**Comment by ggevay** [comment]
The codebase moved too far away from this in the meantime, so closing. But I linked this PR here in the "Normalizations / Canonicalizations" section: https://www.notion.so/materialize/Optimizer-Planning-369a39c062ea49a692bfddc40753047a?pvs=4#694dea3fa5d845428d6d90e27ff08f6e

**Pull request closed without merging**
