### PR TITLE
Fix issues with bigint sum -> numeric conversion

### PR DESCRIPTION
**Pull request by ruchirK**
Functional changes here in the first commit:

* make `sum_int64` have the same behavior as the rest of the reduce path
* make our reduce elision logic output the correct type

and then theres a small debug output change to pgwire in the second commit.

I tested this manually against Chris's query and it works but I'm not sure if thats suitable for an integration test or if we should do something else. Afaik we're not able to specify primary keys from sql primitives. @benesch do you have any thoughts?

---
This change is [Reviewable](https://reviewable.io/reviews/materializeinc/materialize/5299)

### CODE REVIEW

**Review by benesch — COMMENTED** [review]
Code looks good, but you think we could wrap up the bug into a test case somehow?

**Comment by ruchirK** [comment]
> Code looks good, but you think we could wrap up the bug into a test case somehow?

Yeah I'm not sure:

We could definitely repeat the query on the `mz_scheduling_elapsed` log. I'm ok with doing that in a testdrive test + a comment indicating why. Doing this does seem very brittle though.

Other than that:
* I don't know how to declare primary keys on sources, views or tables. Oh wait I actually just thought of something as I was typing -- views with reductions have primary keys. so i think attempting to double compute the sum of a view will hit this elision bug. I can do that.

* I don't know how to force `sum_int64` to execute

**Comment by benesch** [comment]
In SLT you can just create a table with a primary key actually!

**Comment by ruchirK** [comment]
tests added!

**Review by benesch — APPROVED** [review]
Awesome! Looks great to me.

**Review by cirego — APPROVED** [review]
Thanks for the looking at this!

**Comment by ruchirK** [comment]
I'm afk for a few hours but feel free to merge when green if you want

**Pull request merged**
