### PR TITLE
sql-pretty: fix

### PR DESCRIPTION
**Pull request by nrainer-materialize**

### CODE REVIEW

**Review by mjibson — COMMENTED** [review]
Any time pretty printing produces a syntax error it is because there is NOT a parser test for this syntax. Can you add a parser test with this syntax which will prevent a regression in the future?

**Comment by mjibson** [comment]
How'd you find this?

**Comment by nrainer-materialize** [comment]
> Any time pretty printing produces a syntax error it is because there is NOT a parser test for this syntax. Can you add a parser test with this syntax which will prevent a regression in the future?

Makes definitively sense. I won't be able to work immediately on it but I will add it to our backlog.

**Comment by nrainer-materialize** [comment]
> How'd you find this?

By accident when searching source code

**Comment by mjibson** [comment]
I added the missing test and made some nearby improvements.

**Review by mjibson — APPROVED** [review]

**Comment by mjibson** [comment]
Problem was SUBSCRIBE was calling this asof function, but not SELECT. So I added the test for SUBSCRIBE and called this fn in SELECT instead of the blind passthrough which wouldn't pretty print the AS OF expression argument.

**Pull request merged**
