### PR TITLE
platform-checks: Use clusterd compute for RestartEntireMz scenario

### PR DESCRIPTION
**Pull request by def-**
To speed it up, brings the runtime back to similar values as most other individual tests (26 min -> 12 min)

Part of https://github.com/MaterializeInc/materialize/issues/20132

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by danhhz** [comment]
sweet! looks like miri was the limiting factor in this test run, but miri is run in parallel with x86_64, so for a PR with a code change I think it probably wouldn't be?

**Comment by def-** [comment]
Unfortunately I'm the only QA member not on vacation. My main concern with this is whether we intentionally wanted to have an envd with cluster on the same docker for this. If so, I'd readd it in nightly, since that seems to be the limiting factor in this test.

**Review by danhhz — APPROVED** [review]
ah! well i'm happy to stamp this in the meantime, though we should probably follow up about the nightly question when the rest of y'all are back

**Comment by def-** [comment]
@philip-stoev I wanted to check in with you, is this change ok or does it make this test useless? If the latter is the case, I'd move it to nightly since it's too slow.

**Pull request merged**
